#
# cvs:affy/sdk/mas5-stat/src/Makefile ---
#
# $Id: Makefile,v 1.1 2009-04-16 14:40:20 awilli Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
sdk_cpp_cflags+=-I${sdk_root}/mas5-stat/src -I${sdk_root}/mas5 -I${sdk_root}/exp_report/src
#
include ${sdk_makefile_post}
