#
# affy/sdk/chipstream/apt-probeset-genotype/Makefile ---
#
# $Id: Makefile,v 1.4 2009-04-22 21:13:54 awilli Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
# classic
$(call sdk_define_exe,apt-copynumber-workflow,apt-copynumber-workflow.cpp)
$(call sdk_define_install_exe,apt-copynumber-workflow)

include ${sdk_makefile_post}
