#
# cvs:affy/sdk/chipstream/apt-cel-extract/CPPTest/Makefile ---
#
# $Id: Makefile,v 1.5 2009-09-25 17:48:56 mspald Exp $
#

#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
#
#
sdk_cpp_ignore=$(wildcard *.cpp)
#
$(call sdk_define_check_exe,test-cel-extract,$(wildcard *.cpp) ../CelExtract.cpp)
#
include ${sdk_makefile_post}
#
