#
# cvs:affy/sdk/util/Makefile2 ---
#
# $Id: Makefile,v 1.12 2009-09-25 17:49:05 mspald Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
#
sdk_cpp_ingore=$(wildcard *.cpp)
#
$(call sdk_define_check_exe,test-midas,$(wildcard *.cpp))
#$(call sdk_define_check_exe,test-midas,$(wildcard MidasNormalTest.cpp))
#
include ${sdk_makefile_post}

# Local Variables:
# mode: makefile
# End:
