#
# cvs:affy/sdk/label/CPPTest/Makefile ---
#
# $Id: Makefile,v 1.4 2009-09-25 17:48:50 mspald Exp $
#

#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
#
#
sdk_cpp_ingore=$(wildcard *.cpp)
#
$(call sdk_define_check_exe, test-em, $(wildcard *.cpp))
#
include ${sdk_makefile_post}

# Local Variables:
# mode: makefile
# End:
