#
# cvs:affy/sdk/file/Makefile ---
#
# $Id: Makefile,v 1.1 2009-04-16 14:40:23 awilli Exp $
#

#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
include ../../Makefile.inc
#
include ${sdk_makefile_post}
