#
# cvs:affy/sdk/file/Makefile ---
#
# $Id: Makefile,v 1.1 2007-05-22 06:51:02 awilli Exp $
#

#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
include ../../Makefile.inc
#
include ${sdk_makefile_post}
