#
# cvs:affy/sdk/rawq/example/Makefile ---
# $Id: Makefile,v 1.5 2009-09-25 17:49:06 mspald Exp $
#

ROOT = ../..

include ${ROOT}/build/config_vars.mk

SRCS = $(wildcard *.cpp)

OBJS = \
 ${OBJDIR}/Test.o


PROGS = ${BINDIR}/rawq-example

include ${ROOT}/build/build_rules.mk

include .depend
