#
# affy/sdk/bboard/dao/Makefile ---
#
# $Id: Makefile,v 1.2 2009-11-05 20:41:39 harley Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
include ${sdk_root}/bboard/Makefile.inc
# we would like to put this in affyfile,
# but it needs to go in affysdk as it requires stuff from bboard
#$(call sdk_set_lib_name,affyfile)
#
include ${sdk_makefile_post}
