#
# affy/sdk/chipstream/apt-probeset-genotype/Makefile ---
#
# $Id: Makefile,v 1.2 2009-04-22 21:13:54 awilli Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
# classic
$(call sdk_define_exe,apt-socket-run,apt-socket-run.cpp)
$(call sdk_define_install_exe,apt-socket-run)

include ${sdk_makefile_post}
