#
# cvs:affy/algorithm/em/Makefile ---
#
# Earl copied from rma
# Simon copied from Earl
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
include ${sdk_makefile_post}

# Local Variables:
# mode: makefile
# End:
