#
# cvs:affy/sdk/normalization/Makefile ---
#
# $Id: Makefile,v 1.17 2007-08-11 00:06:52 awilli Exp $
#

#
sdk_root:=..
include ${sdk_root}/Makefile.defs
#
$(call sdk_define_exe,test-sat-int16,test-sat-int16.cpp)
#
include ${sdk_makefile_post}
