#
# cvs:affy/sdk/util/CPPTest/Makefile ---
#
# $Id: Makefile,v 1.15 2009-09-25 17:49:08 mspald Exp $
#

#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
#
# moved to sdk/util/CPPTest
# $(call sdk_define_check_exe,test-fspath,$(wildcard *.cpp))
#
include ${sdk_makefile_post}

# Local Variables:
# mode: makefile
# End:
