#
# cvs:affy/sdk/chipstream/Makefile ---
#
# $Id: Makefile,v 1.30 2009-06-26 21:18:03 harley Exp $
#

# before include
sdk_root:=..
include ${sdk_root}/Makefile.defs

#
sdk_cpp_ignore:=TableReader.cpp

#
include ${sdk_makefile_post}
