Affymetrix GeneChip Experiment Information
Version	1

[Sample Info]
Chip Type	HG-U133A
Chip Lot	
Operator	
Sample Type	
Description	
Project	
Comments	
Solution Type	
Solution Lot	

[Fluidics]
Protocol	EukGE-WS1v4
REMOVE VIAL
            20°C
Aborted by user
Station	1
Module	2
Hybridize Date	Mar 28 2003 09:52AM

[Scanner]
Pixel Size	
Filter	
Scan Temperature	
Scan Date	
Scanner ID	
Number of Scans	
Scanner Type	
