#
# cvs:affy/sdk/dabg/Makefile ---
#
# $Id: Makefile,v 1.3 2009-09-25 17:48:56 mspald Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
#
$(call sdk_define_exe,apt-cel-extract,apt-cel-extract.cpp CelExtract.cpp)
$(call sdk_define_install_exe,apt-cel-extract)
#
include ${sdk_makefile_post}
