#
# cvs:affy/sdk/label/Makefile ---
#
# $Id: Makefile,v 1.3 2007-08-11 00:06:51 awilli Exp $
# Earl copied from rma

#
sdk_root:=..
include ${sdk_root}/Makefile.defs
#
include ${sdk_makefile_post}

# Local Variables:
# mode: makefile
# End:
