#
# cvs:affy/sdk/chipstream/Makefile ---
#
# $Id: Makefile,v 1.9 2009-09-25 17:48:57 mspald Exp $
#

# before include
sdk_root:=..
include ${sdk_root}/Makefile.defs
#
#
$(call sdk_ignore,test-myExpon.cpp test-CnLoadMap.cpp)
#$(call sdk_define_exe,test-myExpon,test-myExpon.cpp)
#$(call sdk_define_exe,test-CnLoadMap,test-CnLoadMap.cpp)
#
include ${sdk_makefile_post}
