#
# cvs:affy/sdk/util/apt-matrix-diff/Makefile ---
#
# $Id: Makefile,v 1.10 2009-09-25 17:49:09 mspald Exp $
#

sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
#
#$(call sdk_set_lib_name,affyutil)
#$(call sdk_set_link_libs,affyutil m xerces)
#
$(call sdk_define_exe,apt-md5-check,apt-md5-check.cpp)
$(call sdk_define_install_exe,apt-md5-check)

include ${sdk_makefile_post}
