#
# affy/sdk/chipstream/apt-geno-qc/Makefile ---
#
# $Id: Makefile,v 1.6 2009-09-23 20:37:23 harley Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
$(call sdk_define_exe,apt-geno-qc,apt-geno-qc.cpp)
$(call sdk_define_install_exe,apt-geno-qc)
#
include ${sdk_makefile_post}
