#
# affy/sdk/chipstream/apt-probeset-genotype/Makefile ---
#
# $Id: Makefile,v 1.1 2009-09-19 23:19:52 wshort Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
# classic
$(call sdk_define_exe,apt-copynumber-wave,apt-copynumber-wave.cpp)
$(call sdk_define_install_exe,apt-copynumber-wave)

include ${sdk_makefile_post}
