#
# cvs:affy/sdk/calvin_files/converters/Makefile ---
#
# $Id: Makefile,v 1.7 2009-04-16 16:31:57 awilli Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
include ../Makefile.inc
#
sdk_subdirs:=\
	utils/src \
	utils/test \
	cel/src \
	cel/comparer \
	chp/src \
	#TODO:
	#To run this we need a bunch of large files in CVS.
	#This should really be setup like APT does with separate regression
	#test target with the large files outside of CVS
	#chp/test \
	#cdf/src \
	#cdf/test
#
include ${sdk_makefile_post}
