Affymetrix Power Tools: util/AffxConv.cpp File Reference
AffxConv.cpp File Reference
This file contains some data conversion routines.
#include "util/AffxConv.h"
#include "util/Convert.h"
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <string>
#include <stdio.h>
Functions
int getInt (const std::string &str)
Converts a string with commas into an int.
unsigned int getUnsignedInt (const std::string &str)
Converts a string with commas into an unsigned int.
double getDouble (const std::string &str)
Converts a string with commas into a double.
std::string getInt (int i, unsigned int iLength)
Converts an int to a string.
std::string getInt (int i, bool bCommas)
Converts an int to a string.
std::string getUnsignedInt (unsigned int i, bool bCommas)
Converts an int64 to a string.
std::string getDouble (double d)
Converts a double to a string.
std::string getDouble (double d, int iDecimalPlaces, bool bCommas)
Converts a double to a string.
std::string formatString (const char *szValue, int iDecimalPlaces, bool bCommas)
Formats a number string.
std::string getMonth (int iMonth)
Converts Month int to Month string.
int getMonth (const std::string &strMonth)
Converts Month string to Month int.
double roundDouble (double val, int places)
Round the double and return it.
std::string likeString (const std::string &str)
Check for special characters is a string using in a SQL WHERE xxx LIKE xxx clause.
Detailed Description
This file contains some data conversion routines.
Definition in file AffxConv.cpp.
Function Documentation
std::string formatString (const char * szValue, int iDecimalPlaces, bool bCommas)
Formats a number string.
Parameters:
szValue - The const char* to convert.
iDecimalPlaces - The number of decimal places.
bCommas - true if you want commas in the string, else false (defaults to false).
Returns:
- string value.
Definition at line 232 of file AffxConv.cpp.
Referenced by getDouble(), getInt(), and getUnsignedInt().
double getDouble (const std::string & str)
Converts a string with commas into a double.
Parameters:
str - The string to convert.
Returns:
- double value.
Definition at line 79 of file AffxConv.cpp.
Referenced by AdapterTypeNormTran::AdapterTypeNormTran(), CNAnalysisEngine::calculateCalibrationParameters(), CNCytoEngine::calculateGenders(), CalvinValue::compareTo(), CNLog2RatioData::dumpCyto2Report(), CNLog2RatioData::dumpGenotypeReport(), affx::File5_File::equivalent(), Calvin::equivalentHeader(), getUnsignedInt(), Calvin::load(), Calvin::loadHeader(), CNReporter::loadParam(), CNFamilialReporterFamilial::loadParam(), CNFamilialReporter::loadParam(), LogStream::progressEnd(), CNReporterCnchp::run(), CNAnalysisMethodCNCyto2Gender::run(), Annotation::runTime(), CNAnalysisMethod::setupDoubleParameter(), CNFamilialReporter::setupFloatParameter(), CNFamilialAnalysisMethod::setupFloatParameter(), CNAnalysisMethod::setupFloatParameter(), CNLog2RatioData::writeModelFile(), CNLog2RatioEngine::writeOutputText(), and CNCytoEngine::writeOutputText().
std::string getDouble (double d, int iDecimalPlaces, bool bCommas)
Converts a double to a string.
Parameters:
d - The double to convert.
iDecimalPlaces - The number of decimal places (double will be rounded).
bCommas - true if you want commas in the string, else false (defaults to false).
Returns:
- string value.
Definition at line 207 of file AffxConv.cpp.
References formatString(), roundDouble(), and ToStr().
std::string getDouble (double d)
Converts a double to a string.
Parameters:
d - The double to convert.
Returns:
- string value.
Definition at line 184 of file AffxConv.cpp.
References ToStr().
std::string getInt (int i, unsigned int iLength)
Converts an int to a string.
Parameters:
i - The int to convert.
iLength - The length of the output string.
Returns:
- string value.
Definition at line 98 of file AffxConv.cpp.
References getInt().
std::string getInt (int i, bool bCommas)
Converts an int to a string.
Parameters:
i - The int to convert.
bCommas - true if you want commas in the string, else false (defaults to false).
Returns:
- string value.
Definition at line 111 of file AffxConv.cpp.
References formatString().
int getInt (const std::string & str)
Converts a string with commas into an int.
Parameters:
str - The string to convert.
Returns:
- int value.
Definition at line 51 of file AffxConv.cpp.
Referenced by CNFamilialReporterFamilial::addPgOptions(), CNWorkflowEngine::calculateGenders(), CNCytoEngine::calculateGenders(), CalvinValue::compareTo(), CNReferenceEngine::determineMemoryUsage(), CNLog2RatioEngine::determineMemoryUsage(), CNLog2RatioData::dumpCyto2Report(), CNLog2RatioData::dumpGenotypeReport(), IntensityReporter::endChips(), Calvin::equivalentHeader(), getInt(), CNWorkflowEngine::getNormalizationTypes(), CNCytoEngine::getNormalizationTypes(), CNWorkflowEngine::getReferenceGenderCounts(), CNCytoEngine::getReferenceGenderCounts(), Calvin::load(), AdapterTypeNormTran::loadAnnotation(), CNLog2RatioData::loadGenotypeReport(), Calvin::loadHeader(), CNReporter::loadParam(), CNFamilialReporterFamilial::loadParam(), CNFamilialReporter::loadParam(), CNReferenceEngine::processData(), CNLog2RatioEngine::processData(), CNReporterCnchp::run(), CNLog2RatioAdjustmentMethodWaveCorrection::run(), CNAnalysisMethodLOHCytoScan::run(), CNAnalysisMethodLOHCyto2::run(), CNAnalysisMethodLOH::run(), CNAnalysisMethodGaussianSmooth::run(), CNFamilialReporter::setupIntParameter(), CNFamilialAnalysisMethod::setupIntParameter(), CNAnalysisMethod::setupIntParameter(), CNCytoEngine::writeOutputHdf5(), CNLog2RatioEngine::writeOutputText(), and CNCytoEngine::writeOutputText().
std::string getMonth (int iMonth)
Converts Month int to Month string.
Parameters:
iMonth - The Month number.
Returns:
- string value.
Definition at line 325 of file AffxConv.cpp.
int getMonth (const std::string & strMonth)
Converts Month string to Month int.
Parameters:
strMonth - The Month string.
Returns:
- int value.
Definition at line 346 of file AffxConv.cpp.
unsigned int getUnsignedInt (const std::string & str)
Converts a string with commas into an unsigned int.
Parameters:
str - The string to convert.
Returns:
- unsigned int value.
Definition at line 69 of file AffxConv.cpp.
References getDouble().
Referenced by CNWorkflowEngine::calculateGenders(), CNCytoEngine::calculateGenders(), CalvinValue::compareTo(), Calvin::equivalentHeader(), Calvin::load(), and Calvin::loadHeader().
std::string getUnsignedInt (unsigned int i, bool bCommas)
Converts an int64 to a string.
Parameters:
l - The int64 to convert.
bCommas - true if you want commas in the string, else false (defaults to false).
Returns:
- string value. Converts an unsigned int64 to a string.
Parameters:
l - The unsigned int64 to convert.
bCommas - true if you want commas in the string, else false (defaults to false).
Returns:
- string value. Converts an unsigned int to a string.
Parameters:
i - The unsigned int to convert.
bCommas - true if you want commas in the string, else false (defaults to false).
Returns:
- string value.
Definition at line 167 of file AffxConv.cpp.
References formatString().
std::string likeString (const std::string & str)
Check for special characters is a string using in a SQL WHERE xxx LIKE xxx clause.
Parameters:
str - The string to check.
Returns:
- The formatted string.
Definition at line 402 of file AffxConv.cpp.
double roundDouble (double val, int places)
Round the double and return it.
Parameters:
d - The double to round.
iDecimalPlaces - The number of decimal places to round to.
Returns:
- rounded double value.
Definition at line 369 of file AffxConv.cpp.
Referenced by CNLog2RatioData::calculateMedianSignal(), CNLog2RatioData::calculateMedianSignalsPerGenotype(), CNLog2RatioData::calculateXYMedianSignal(), and getDouble().