Affymetrix Power Tools: mas5-stat/apt-mas5/apt-mas5.cpp File Reference
apt-mas5.cpp File Reference
wrapper around engine to run MAS5 algos
#include "mas5-stat/apt-mas5/MAS5Engine.h"
#include "chipstream/EngineUtil.h"
#include "util/AptVersionInfo.h"
#include "util/BaseEngine.h"
#include "util/Fs.h"
#include "util/LogStream.h"
#include "util/PgOptions.h"
#include "util/Util.h"
#include <unistd.h>
Functions
int main (int argc, const char *argv[])
Everybody's favorite function...
Detailed Description
wrapper around engine to run MAS5 algos
Author:
Alan Williams
Date:
Wed Apr 15 15:29:23 PDT 2009
Definition in file apt-mas5.cpp.
Function Documentation
int main (int argc, const char * argv[])
Everybody's favorite function...
Definition at line 48 of file apt-mas5.cpp.
References Fs::basename(), BaseEngine::checkOptions(), Err::errAbort(), affxutil::Guid::GenerateNewGuid(), Options::getOpt(), Options::getOptInt(), BaseEngine::getProgName(), Fs::join(), Fs::mkdirPath(), Fs::mustOpenToWrite(), Verbose::out(), BaseEngine::parseArgv(), Verbose::pushProgressHandler(), BaseEngine::run(), Verbose::setLevel(), Options::setOpt(), and ToStr().