Affymetrix Power Tools: chipstream/apt-cel-transformer/apt-cel-transformer.cpp File Reference
apt-cel-transformer.cpp File Reference
Program to generically transform cel file data using chipstreams and write the data to a new cel file. Also serves as relatively simple code sample to illustrate usage of chipstream code.
#include "chipstream/EngineUtil.h"
#include "chipstream/apt-cel-transformer/CELTransformerEngine.h"
#include "util/AptVersionInfo.h"
#include "util/Fs.h"
#include "util/LogStream.h"
#include "util/Util.h"
#include <iostream>
#include <string>
Functions
int main (int argc, const char *argv[])
Everbody's favorite function...
Detailed Description
Program to generically transform cel file data using chipstreams and write the data to a new cel file. Also serves as relatively simple code sample to illustrate usage of chipstream code.
Author:
Chuck Sugnet
Date:
Wed Jan 25 17:38:29 2006
Definition in file apt-cel-transformer.cpp.
Function Documentation
int main (int argc, const char * argv[])
Everbody's favorite function...
Definition at line 49 of file apt-cel-transformer.cpp.
References Fs::basename(), BaseEngine::checkOptions(), affxutil::Guid::GenerateNewGuid(), Options::getOptInt(), BaseEngine::getProgName(), BaseEngine::openStandardLog(), Verbose::out(), BaseEngine::parseArgv(), BaseEngine::run(), Verbose::setLevel(), and Options::setOpt().