Affymetrix Power Tools: translation/apt-dmet-translation.cpp File Reference
apt-dmet-translation.cpp File Reference
Commandline controller wrapper around TranslateEngine.run().
#include "translation/TranslationEngine.h"
#include "util/AptVersionInfo.h"
#include "util/Err.h"
#include "util/Fs.h"
#include "util/LogStream.h"
#include "util/Util.h"
#include "util/Verbose.h"
Functions
void translateEngineMessageHandlingCallBack (ADTOptions &adtOpts)
translateEngineMessageHandlingCallBack Synopsis:
int main (int argc, char *argv[])
apt-dmet-translation main
Detailed Description
Commandline controller wrapper around TranslateEngine.run().
Author:
Mybrid Spalding
Date:
Wed Jun 4 08:29:07 PDT 2008
Definition in file apt-dmet-translation.cpp.
Function Documentation
int main (int argc, char * argv[])
apt-dmet-translation main
Parameters:
argc -
argv -
Returns:
- exit 0 when ok.
Todo:
This isnt how an engine should be invoked or have options set. /// Attemping to process the "--help" option causes BaseEngine to print: /// "running TranslationEngine" before it prints the help message.
Definition at line 104 of file apt-dmet-translation.cpp.
References C_CMDLINE, Verbose::out(), and translateEngineMessageHandlingCallBack().
void translateEngineMessageHandlingCallBack (ADTOptions & adtOpts)
translateEngineMessageHandlingCallBack Synopsis:
There is a catch 22 where the command line message handlers need to have the PGOptions information in order to set up the message handling log file name, etc. Resolve this by passing in a call back to the TranslateEngine constructor which initializes the PGOptions.
Parameters:
atdOopts - filled in with all the PGOptions data.
Returns:
- nada, initializes message handling.
Definition at line 56 of file apt-dmet-translation.cpp.
References APT_ERR_ABORT, Fs::join(), Fs::mkdirPath(), Fs::mustOpenToWrite(), Verbose::pushProgressHandler(), Verbose::setLevel(), and Err::setThrowStatus().
Referenced by main(), ConsoleOverrideTest::run(), ConsoleMarkerListTest::run(), and ConsoleInitializationTest::run().