Affymetrix Power Tools: util/apt-matrix-diff/apt-matrix-diff.cpp File Reference
apt-matrix-diff.cpp File Reference
///
#include "util/AptVersionInfo.h"
#include "util/Convert.h"
#include "util/Err.h"
#include "util/FsPath.h"
#include "util/MatrixCheck.h"
#include "util/MixedFileCheck.h"
#include "util/PgOptions.h"
#include "util/RowFile.h"
#include "util/TableFile.h"
#include "util/TextFileCheck.h"
#include "util/Verbose.h"
#include <cstring>
#include <map>
#include <string>
#include <vector>
Functions
void define_aptmatrixdiff_options (PgOptions *opts)
int matrixDiff (PgOptions *opts)
Check each entry in two matrices to see if they are the same.
int main (int argc, const char *argv[])
Everybody's favorite function.
Detailed Description
///
Simple program to check that two matrices are the same.
Definition in file apt-matrix-diff.cpp.
Function Documentation
int main (int argc, const char * argv[])
Everybody's favorite function.
Definition at line 158 of file apt-matrix-diff.cpp.
References PgOptions::getBool(), matrixDiff(), Verbose::out(), PgOptions::parseArgv(), and PgOptions::usage().
int matrixDiff (PgOptions * opts)
Check each entry in two matrices to see if they are the same.
If doing 'match-rows' we will attempt to find the matching row by the row name.
Parameters:
opts - Options supplied to program.
Returns:
number of entries where difference is greater than epsilon
Definition at line 104 of file apt-matrix-diff.cpp.
References Err::errAbort(), PgOptions::getArg(), PgOptions::getArgCount(), PgOptions::getBool(), PgOptions::getDouble(), PgOptions::getInt(), Verbose::out(), and Verbose::setLevel().
Referenced by main().