Affymetrix Power Tools: chipstream/apt-data-subset/apt-data-subset.cpp File Reference
apt-data-subset.cpp File Reference
///
#include "calvin_files/data/src/CELData.h"
#include "calvin_files/data/src/GenericDataTypes.h"
#include "calvin_files/fusion/src/FusionCELData.h"
#include "calvin_files/utils/src/StringUtils.h"
#include "calvin_files/writers/src/CalvinCelFileWriter.h"
#include "calvin_files/writers/src/CombinedDatConstants.h"
#include "calvin_files/writers/src/MultiChannelCelFileCollater.h"
#include "chipstream/ChipLayout.h"
#include "file/TsvFile/BgpFile.h"
#include "file/TsvFile/ClfFile.h"
#include "file/TsvFile/SpfFile.h"
#include "file5/File5.h"
#include "file5/File5_Tsv.h"
#include "stats/affy_random_sample.h"
#include "util/AptVersionInfo.h"
#include "util/Convert.h"
#include "util/Err.h"
#include "util/Fs.h"
#include "util/MixedFileCheck.h"
#include "util/PgOptions.h"
#include "util/RowFile.h"
#include "util/TableFile.h"
#include "util/TextFileCheck.h"
#include "util/Verbose.h"
#include <cstring>
#include <map>
#include <string>
#include <vector>
Classes
class Meta
Helper class for meta probesets in apt-data-subset.cpp.
class FileTranslation
Helper class containing information about the subset transformation like the set of probesets to be kept and the mapping of original probe ids to new probe ids.
class DsOptions
Hold all the options for the program.
class File5Options
File5 options.
Defines
#define NO_WAVELENGTH L"wavelength unavailable"
#define MULTI_CHANNEL_FILE_ID "affymetrix-calvin-multi-intensity"
Functions
void defineDataSubsetOptions (PgOptions *opts)
User interface options.
void openSpfForWrite (affx::SpfFile &spffile, const std::string &fileName, const std::string &chipType, int version, int nCol, int nRow, int psCount, int nChannels)
Open an Spf file and write out the headers.
void fillInCelFiles (vector< string > &celFiles, const string &fileName)
Open a tsv file and read the cel files we want to process.
void fillInTsvFiles (vector< string > &tsvFiles, vector< string > &ids, const string &fileName)
Open up a tsv file and read the collection of tsv files that we are going to want to process.
void fillInFile5Files (vector< File5Options > &file5Files, const string &inputName)
Open up a tsv file and read the collection of tsv files that we are going to want to process.
void makeCelFileSubset (const string &orig, const string &outCel, const FileTranslation &trans)
Write a subset of cel file to a new file.
void makeMultiCelFileSubset (const string &orig, const string &outCel, const FileTranslation &trans)
Write a subset of cel file to a new file.
void subsetCelFile (const string &orig, const string &outCel, const FileTranslation &trans)
void convertBgpFile (vector< int > &probeMask, const string &chipType, const string &bgpFileIn, const string &bgpFileOut)
Update the bgp files with new probe ids for appropriate bgp entries.
void setBgpFile (FileTranslation &trans, string &bgpFile)
Set the bgp probes and probesets to be kept.
void copyRow (TsvFile &in, TsvFile &out, int level, const FileTranslation &trans)
Copy a tsv record from one tsv-file to another.
void recursiveWrite (TsvFile &in, TsvFile &out, int level, const FileTranslation &trans)
Recursively copy rows from one tsv-file to another.
void copyTsvHeaders (TsvFile &in, TsvFile &out, const map< string, string > &replace)
Copy all the headers with the exception of chip_type which is supplied.
void copyTsvDefinition (TsvFile &in, TsvFile &out)
Copy over the "format" of one tsvfile to another.
bool keepRow (TsvFile &in, int level, const FileTranslation &trans)
Based on the probesets and probes in the translation object determine if we're keeping this tsv row.
bool keepRow (File5_Tsv &in, int level, File5Options &f5Opts, const FileTranslation &trans, int lineCount)
Based on the probesets and probes in the translation object determine if we're keeping this tsv row.
int adjustColumn (File5_Tsv &in, string &colName, int value, File5Options &f5Opts, const FileTranslation &trans)
void checkRet (int retVal, int level, int col, File5_Tsv &tsv5)
void copyColumn (File5_Tsv &in, File5_Tsv &out, File5Options &f5Opts, int level, int colIx, const FileTranslation &trans)
void copyRow (File5_Tsv &in, File5_Tsv &out, File5Options &f5Opts, int level, const FileTranslation &trans)
void recursiveWrite (File5_Tsv &in, File5_Tsv &out, File5Options &f5Opts, int level, const FileTranslation &trans)
Recursively copy rows from one tsv-file to another.
void copyTsvFile (const string &in, const string &out, const map< string, string > &replace, const FileTranslation &trans)
Copy the appropriate entries from the input tsv file into the output tsv file.
void copyFile5File (File5Options f5Opts, const string &out, const FileTranslation &trans)
Copy the appropriate entries from the input tsv file into the output tsv file.
bool readTsvProbesetRow (TsvFile &in, int level, FileTranslation &trans, set< string > &probeSets)
Read a tsv row and see if it has a probe or probeset we want to keep.
void recursiveRead (TsvFile &in, int level, FileTranslation &trans, set< string > &probeSets)
Recursively loop through tsv entries looking for probes and probesets to keep.
void readProbesetTsvFile (const string &fileName, FileTranslation &trans, int numKeep)
void readFile5ProbesetRow (File5_Tsv &iTsv5, File5Options &f5Opts, int level, FileTranslation &trans, int &probeId, int &probesetId)
void readProbesetFile5File (File5Options &f5Opts, FileTranslation &trans)
void readMetaProbesetList (vector< Meta > &toLoad, const string &metaFile, int numLoad)
void fillPsNamesFromLayout (set< string > &keepProbeSets, ChipLayout &layout, int numKeep)
void writeMetaProbesets (vector< Meta > &metaSets, const string &fileName, const string &chipType)
void writeSpfFile (ChipLayout &layout, const string &outputSpf, const FileTranslation &trans, int version, int nChannels)
void openChipLayout (ChipLayout &layout, string &pgfFileStr, string &clfFileStr, string &spfFileStr)
string makeOutputName (const string &dir, const string &file, const string &prefix, const string &suffix)
void readProbesetList (set< string > &toLoad, const string &psFile)
void fillInProbesets (const string &metaFile, vector< Meta > &metaSets, ChipLayout &layout, FileTranslation &trans, DsOptions &o)
void loadMagicOrder (FileTranslation &trans, string &col, string &file, string &group)
void dataSubset (PgOptions *opts)
int main (int argc, const char *argv[])
Everybody's favorite function.
Detailed Description
///
Program make a smaller sample data set from a large one
Definition in file apt-data-subset.cpp.
Function Documentation
int main (int argc, const char * argv[])
Everybody's favorite function.
Definition at line 1629 of file apt-data-subset.cpp.
References defineDataSubsetOptions(), PgOptions::getBool(), PgOptions::getInt(), PgOptions::parseArgv(), Verbose::setLevel(), and PgOptions::usage().