Affymetrix Power Tools: util/apt-calvin-equivalent/apt-calvin-equivalent.cpp File Reference
apt-calvin-equivalent.cpp File Reference
///
#include "calvin_files/utils/src/Calvin.h"
#include "file/TsvFile/TsvFile.h"
#include "util/AptVersionInfo.h"
#include "util/Convert.h"
#include "util/Err.h"
#include "util/Fs.h"
#include "util/PgOptions.h"
#include "util/Verbose.h"
#include <cstring>
#include <map>
#include <string>
#include <vector>
Functions
void define_aptcalvinEquiv_options (PgOptions *opts)
int calvinEquiv (PgOptions *opts)
Check data in all sections of binary Calvin file to determine eqivalence.
int main (int argc, const char *argv[])
Everybody's favorite function.
Detailed Description
///
Simple program to check that two Calvin files are equivalent.
Definition in file apt-calvin-equivalent.cpp.
Function Documentation
int calvinEquiv (PgOptions * opts)
Check data in all sections of binary Calvin file to determine eqivalence.
Parameters:
opts - Options supplied to program.
Returns:
status 0 if equivalent, non-zero if not not equivalent.
Definition at line 90 of file apt-calvin-equivalent.cpp.
References Fs::basename(), Err::errAbort(), affx::TsvFile::extractColToVec(), PgOptions::get(), PgOptions::getArg(), PgOptions::getArgCount(), PgOptions::getBool(), PgOptions::getDouble(), PgOptions::getInt(), Verbose::out(), Verbose::setLevel(), Convert::toDoubleCheck(), and ToStr().
Referenced by main().
int main (int argc, const char * argv[])
Everybody's favorite function.
Definition at line 146 of file apt-calvin-equivalent.cpp.
References calvinEquiv(), PgOptions::getBool(), Verbose::out(), PgOptions::parseArgv(), and PgOptions::usage().