Affymetrix Power Tools: chipstream/apt-cel-extract/apt-cel-extract.cpp File Reference
apt-cel-extract.cpp File Reference
/ /
#include "chipstream/apt-cel-extract/CelExtract.h"
#include "util/AptVersionInfo.h"
#include "util/Fs.h"
#include "util/Guid.h"
#include "util/LogStream.h"
#include "util/PgOptions.h"
#include "util/Util.h"
Functions
void define_aptcelextract_options (PgOptions *opts)
void fillInOptions (PgOptions *opts, CelExtractOptions &o, int argc)
Fill in options given command line args.
void reportBasics (CelExtractOptions &o)
Report out some basics about what we think the run is:
int main (int argc, char *argv[])
The entry point for apt-cel-extract ///.
Variables
CelExtractOptions ourOpts
Detailed Description
/ /
Main for extracting probe level intensities.
Definition in file apt-cel-extract.cpp.
Function Documentation
void fillInOptions (PgOptions * opts, CelExtractOptions & o, int argc)
Fill in options given command line args.
Todo:
this should go into Engine::Util as it is used in a number of apps
Definition at line 162 of file apt-cel-extract.cpp.
References CelExtractOptions::analysisString, Fs::basename(), CelExtractOptions::bgpFile, CelExtractOptions::cdfFile, CelExtractOptions::celFiles, CelExtractOptions::clfFile, Util::cloneString(), affx::TsvFile::close(), CelExtractOptions::cvsId, Err::errAbort(), CelExtractOptions::execGuid, CelExtractOptions::force, affxutil::Guid::GenerateNewGuid(), PgOptions::get(), PgOptions::getArg(), PgOptions::getArgCount(), PgOptions::getBool(), PgOptions::getInt(), PgOptions::getProgName(), Util::getTimeStamp(), CelExtractOptions::help, CelExtractOptions::ignoreProbesWithoutMM, affx::TsvFile::m_optEscapeOk, CelExtractOptions::m_output_precision, PgOptions::mustFindOpt(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), Verbose::out(), CelExtractOptions::outFile, CelExtractOptions::pairWithBackground, CelExtractOptions::pgfFile, CelExtractOptions::pmOnly, CelExtractOptions::probeIdsFiles, CelExtractOptions::probesetIdsFiles, CelExtractOptions::progName, PgOpt::push_user_values_into(), affx::TsvFile::rewind(), CelExtractOptions::sketchInFile, CelExtractOptions::spfFile, CelExtractOptions::timeStr, ToStr(), affx::TSV_BIND_REQUIRED, CelExtractOptions::verbosity, and CelExtractOptions::version.
Referenced by main().
int main (int argc, char * argv[])
The entry point for apt-cel-extract ///.
Parameters:
argc arg count ///
argv arg strings ///
Returns:
Definition at line 258 of file apt-cel-extract.cpp.
References CelExtract::extract(), fillInOptions(), PgOptions::get(), CelExtractOptions::help, Fs::mustOpenToWrite(), Verbose::out(), PgOptions::parseArgv(), Verbose::pushProgressHandler(), reportBasics(), Verbose::setLevel(), ToStr(), PgOptions::usage(), CelExtractOptions::verbosity, and CelExtractOptions::version.
void reportBasics (CelExtractOptions & o)
Report out some basics about what we think the run is:
Parameters:
o - Program options.
Definition at line 236 of file apt-cel-extract.cpp.
References ArraySize, CelExtractOptions::commandLine, CelExtractOptions::execGuid, Verbose::out(), CelExtractOptions::timeStr, ToStr(), and CelExtractOptions::version.
Referenced by main().