Affymetrix Power Tools: chipstream/apt-summary-genotype/apt-summary-genotype.cpp File Reference
apt-summary-genotype.cpp File Reference
Program to generically transform cel file data using chipstreams and write the data to a new cel file. Also serves as relatively simple code sample to illustrate usage of chipstream code.
#include "chipstream/EngineUtil.h"
#include "chipstream/apt-summary-genotype/SummaryGenotypeEngine.h"
#include "util/AptVersionInfo.h"
#include "util/BaseEngine.h"
#include "util/Fs.h"
#include "util/LogStream.h"
#include "util/PgOptions.h"
#include "util/Util.h"
#include <unistd.h>
Functions
int main (int argc, const char *argv[])
Everybody's favorite function...
Detailed Description
Program to generically transform cel file data using chipstreams and write the data to a new cel file. Also serves as relatively simple code sample to illustrate usage of chipstream code.
Author:
Alan Williams
Date:
Fri Dec 7 09:10:30 PST 2007
Definition in file apt-summary-genotype.cpp.
Function Documentation
int main (int argc, const char * argv[])
Everybody's favorite function...
Definition at line 50 of file apt-summary-genotype.cpp.
References Fs::basename(), BaseEngine::checkOptions(), affxutil::Guid::GenerateNewGuid(), Options::getOptInt(), BaseEngine::getProgName(), BaseEngine::openStandardLog(), Verbose::out(), BaseEngine::parseArgv(), BaseEngine::run(), Verbose::setLevel(), and Options::setOpt().