Affymetrix Power Tools: dmet/apt-dmet-copynumber.cpp File Reference
apt-dmet-copynumber.cpp File Reference
#include "dmet/DmetCopyNumberEngine.h"
#include "chipstream/EngineUtil.h"
#include "util/AptVersionInfo.h"
#include "util/BaseEngine.h"
#include "util/Err.h"
#include "util/Fs.h"
#include "util/LogStream.h"
#include "util/PgOptions.h"
#include "util/Util.h"
#include <unistd.h>
Functions
int main (int argc, const char *argv[])
Everybody's favorite function...
Detailed Description
Author:
Alan Williams
Date:
Thu Jan 19 14:18:57 2006
Definition in file apt-dmet-copynumber.cpp.
Function Documentation
int main (int argc, const char * argv[])
Everybody's favorite function...
Definition at line 47 of file apt-dmet-copynumber.cpp.
References BaseEngine::checkOptions(), Err::errAbort(), affxutil::Guid::GenerateNewGuid(), Options::getOpt(), Options::getOptInt(), BaseEngine::getProgName(), Fs::join(), Fs::mkdirPath(), Fs::mustOpenToWrite(), Verbose::out(), BaseEngine::parseArgv(), Verbose::pushProgressHandler(), BaseEngine::run(), Verbose::setLevel(), and Options::setOpt().