Affymetrix Power Tools: canary/regression/canary-test.cpp File Reference
canary-test.cpp File Reference
Program for doing regression tests on canary data.
#include "util/CalvinChpCheck.h"
#include "util/ChpCheck.h"
#include "util/Convert.h"
#include "util/Fs.h"
#include "util/FsTestDir.h"
#include "util/RegressionTest.h"
#include "util/Util.h"
#include "util/Verbose.h"
#include <cstring>
#include <string>
#include <vector>
Classes
class CanaryTest
Functions
int main (int argc, char *argv[])
Everybody's favorite function.
Detailed Description
Program for doing regression tests on canary data.
Author:
Chuck Sugnet
Date:
Thu Mar 2 16:39:16 2006
Definition in file canary-test.cpp.
Function Documentation
int main (int argc, char * argv[])
Everybody's favorite function.
Definition at line 207 of file canary-test.cpp.
References Verbose::out(), Verbose::setLevel(), FsTestDir::setTestDir(), and ToStr().