Affymetrix Power Tools: util/apt-chp-to-txt/regression/chp-to-txt-test.cpp File Reference
chp-to-txt-test.cpp File Reference
Program for doing tests on chp-to-txt.
#include "util/Fs.h"
#include "util/FsTestDir.h"
#include "util/MixedFileCheck.h"
#include "util/RegressionTest.h"
#include "util/Util.h"
#include "util/Verbose.h"
#include <cstring>
#include <string>
#include <vector>
Classes
class ChpToTxtTest
Functions
int main (int argc, char *argv[])
Detailed Description
Program for doing tests on chp-to-txt.
Definition in file chp-to-txt-test.cpp.
Function Documentation
int main (int argc, char * argv[])
Todo:
regression test for "no-header" option ///
Todo:
regression test for "no-body" option ///
Todo:
regression test for "chp-files" option
Definition at line 94 of file chp-to-txt-test.cpp.
References Fs::fileCopy(), Verbose::out(), Verbose::setLevel(), FsTestDir::setTestDir(), and ToStr().