Affymetrix Power Tools: CNAnalysisMethodNormalDiploid Class Reference
CNAnalysisMethodNormalDiploid Class Reference
The NormalDiploid analysis method.
#include <CNAnalysisMethodNormalDiploid.h>