Affymetrix Power Tools: SocketClient Class Reference
SocketClient Class Reference
Class for reading and writing to a server over a socket.
#include <SocketClient.h>