Affymetrix Power Tools: affymetrix_fusion_io::FusionCDFFileHeader Class Reference
affymetrix_fusion_io::FusionCDFFileHeader Class Reference
#include <FusionCDFData.h>
Public Member Functions
int GetFormatVersion () const
std::string GetGUID () const
std::string GetIntegrityMd5 () const
int GetCols () const
int GetRows () const
int GetNumProbeSets () const
int GetNumQCProbeSets () const
std::string & GetReference ()
FusionCDFFileHeader ()
Protected Member Functions
void Initialize (affxcdf::CCDFFileData *data)
void Initialize (affymetrix_calvin_io::CDFData *data)
Protected Attributes
affxcdf::CCDFFileHeader * gcosHeader
affymetrix_calvin_io::CDFData * calvinData
std::string ref
Friends
class FusionCDFData
Detailed Description
Storage for the header in a CDF file.
Definition at line 40 of file FusionCDFData.h.
Constructor & Destructor Documentation
FusionCDFFileHeader::FusionCDFFileHeader ()
Constructor
Definition at line 157 of file FusionCDFData.cpp.
References calvinData, and gcosHeader.
Member Function Documentation
int FusionCDFFileHeader::GetCols () const
Gets the number of feature columns in the array.
Returns:
The number of columns.
Definition at line 77 of file FusionCDFData.cpp.
References calvinData, gcosHeader, affymetrix_calvin_io::CDFData::GetArrayCols(), and affxcdf::CCDFFileHeader::GetCols().
Referenced by CRawQ::ComputeRawQ(), EngineUtil::getCdfChipType(), ChipLayout::openCdf(), and ChipLayout::readProbeListCdfFileKillList().
int FusionCDFFileHeader::GetFormatVersion () const
Get CDF Format Version
Returns:
CDF Format Version
Definition at line 42 of file FusionCDFData.cpp.
References calvinData, gcosHeader, affymetrix_calvin_io::CDFData::GetFormatVersion(), and affxcdf::CCDFFileHeader::GetFormatVersion().
std::string FusionCDFFileHeader::GetGUID () const
Get GUID
Returns:
GUID
Definition at line 55 of file FusionCDFData.cpp.
References gcosHeader, and affxcdf::CCDFFileHeader::GetGUID().
std::string FusionCDFFileHeader::GetIntegrityMd5 () const
Get integrity md5
Returns:
integrity md5
Definition at line 66 of file FusionCDFData.cpp.
References gcosHeader, and affxcdf::CCDFFileHeader::GetIntegrityMd5().
int FusionCDFFileHeader::GetNumProbeSets () const
Gets the number of probe sets.
Returns:
The number of probe sets.
Definition at line 103 of file FusionCDFData.cpp.
References calvinData, gcosHeader, affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), affymetrix_calvin_io::CDFData::GetGenericData(), affxcdf::CCDFFileHeader::GetNumProbeSets(), affymetrix_calvin_io::CDFData::GetProbeSetCnt(), and affymetrix_calvin_io::GenericData::Header().
Referenced by CRawQ::ComputeRawQ(), EngineUtil::getCdfChipType(), CRawQWorkflow::IsExpressionArray(), ChipLayout::openCdf(), and ChipLayout::readProbeListCdfFileKillList().
int FusionCDFFileHeader::GetNumQCProbeSets () const
Gets the number of QC probe sets.
Returns:
The number of columns.
Definition at line 116 of file FusionCDFData.cpp.
References calvinData, gcosHeader, affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), affymetrix_calvin_io::CDFData::GetGenericData(), affxcdf::CCDFFileHeader::GetNumQCProbeSets(), affymetrix_calvin_io::CDFData::GetProbeSetCnt(), and affymetrix_calvin_io::GenericData::Header().
std::string & FusionCDFFileHeader::GetReference ()
Gets the reference sequence (for resequencing arrays only).
Returns:
The reference sequence.
Definition at line 129 of file FusionCDFData.cpp.
References ref.
int FusionCDFFileHeader::GetRows () const
Gets the number of feature rows in the array.
Returns:
The number of rows.
Definition at line 90 of file FusionCDFData.cpp.
References calvinData, gcosHeader, affymetrix_calvin_io::CDFData::GetArrayRows(), and affxcdf::CCDFFileHeader::GetRows().
Referenced by CRawQ::ComputeRawQ(), EngineUtil::getCdfChipType(), ChipLayout::openCdf(), and ChipLayout::readProbeListCdfFileKillList().
void FusionCDFFileHeader::Initialize (affxcdf::CCDFFileData * data) [protected]
Initializes the class based on GCOS information.
Parameters:
data The GCOS CDF file object.
Definition at line 137 of file FusionCDFData.cpp.
References calvinData, gcosHeader, affxcdf::CCDFFileData::GetHeader(), affxcdf::CCDFFileHeader::GetReference(), and ref.
Referenced by affymetrix_fusion_io::FusionCDFData::GetHeader().
void FusionCDFFileHeader::Initialize (affymetrix_calvin_io::CDFData * data) [protected]
Initializes the class based on Calvin information.
Parameters:
data The Calvin CDF file object.
Definition at line 147 of file FusionCDFData.cpp.
References calvinData, gcosHeader, affymetrix_calvin_io::CDFData::GetRefSequence(), and ref.
Friends And Related Function Documentation
friend class FusionCDFData [friend]
Friend to the parent.
Definition at line 63 of file FusionCDFData.h.
Member Data Documentation
affymetrix_calvin_io::CDFData* affymetrix_fusion_io::FusionCDFFileHeader::calvinData [protected]
The Calvin CDF file object.
Definition at line 47 of file FusionCDFData.h.
Referenced by FusionCDFFileHeader(), GetCols(), GetFormatVersion(), GetNumProbeSets(), GetNumQCProbeSets(), GetRows(), and Initialize().
affxcdf::CCDFFileHeader* affymetrix_fusion_io::FusionCDFFileHeader::gcosHeader [protected]
The GCOS CDF file header object.
Definition at line 44 of file FusionCDFData.h.
Referenced by FusionCDFFileHeader(), GetCols(), GetFormatVersion(), GetGUID(), GetIntegrityMd5(), GetNumProbeSets(), GetNumQCProbeSets(), GetRows(), and Initialize().
std::string affymetrix_fusion_io::FusionCDFFileHeader::ref [protected]
The reference sequence
Definition at line 50 of file FusionCDFData.h.
Referenced by GetReference(), and Initialize().
The documentation for this class was generated from the following files:
calvin_files/fusion/src/FusionCDFData.h
calvin_files/fusion/src/FusionCDFData.cpp