Affymetrix Power Tools: CNAnalysisMethodSegment Class Reference
CNAnalysisMethodSegment Class Reference
The Segment analysis method.
#include <CNAnalysisMethodSegment.h>