Affymetrix Power Tools: DTFactory Class Reference
DTFactory Class Reference
Class for creating DataTransform objects by string description.
#include <DTFactory.h>
Public Member Functions
DataTransform * dataTransformForString (const std::string &spec, PsBoard &board)
Create a pointer to a new DataTransform object as described in the string specification.
Detailed Description
Class for creating DataTransform objects by string description.
Usual chipstream, pmadjuster and quantmethod string descriptions should work. Classes must implement the setParameter() function to be initialized properly.
Definition at line 47 of file DTFactory.h.
Member Function Documentation
DataTransform * DTFactory::dataTransformForString (const std::string & spec, PsBoard & board)
Create a pointer to a new DataTransform object as described in the string specification.
Parameters:
spec - Specification string i.e. quant-norm.sketch=1000000, or med-polish.expon=true, etc.
Returns:
Pointer to new DataTransform objects, must be deleted when finished.
Definition at line 29 of file DTFactory.cpp.
References PmAdjusterFactory::canBuild(), QuantMethodFactory::canBuild(), ChipStreamFactory::canBuild(), ChipStreamFactory::chipStreamForStringBoard(), Err::errAbort(), PmAdjusterFactory::pmAdjusterForString(), and QuantMethodFactory::quantMethodForString().
The documentation for this class was generated from the following files:
chipstream/DTFactory.h
chipstream/DTFactory.cpp