Affymetrix Power Tools: MAS5Workflow Class Reference
MAS5Workflow Class Reference
#include <MAS5Workflow.h>
Public Member Functions
MAS5Workflow ()
~MAS5Workflow ()
void Clear ()
std::string GetError ()
CExpStatAlgSettings & AlgParameters ()
int & ProbePairThreshold ()
bool & SaveToLegacyFile ()
ExpressionReport::ExpressionControls & ReportControls ()
bool Execute (const std::string &celFile, const std::string &baselineCelFile, const std::string &cdfFile, const std::string &chpFile)
std::wstring & ProgramName ()
std::wstring & ProgramCompany ()
std::wstring & ProgramId ()
Detailed Description
Provide the workflow of calling the MAS5 algorithm and saving the results to a CHP file.
Definition at line 36 of file MAS5Workflow.h.
Constructor & Destructor Documentation
MAS5Workflow::MAS5Workflow ()
Constructor
Definition at line 37 of file MAS5Workflow.cpp.
References Clear().
MAS5Workflow::~MAS5Workflow ()
Destructor
Definition at line 45 of file MAS5Workflow.cpp.
References Clear().
Member Function Documentation
CExpStatAlgSettings& MAS5Workflow::AlgParameters () [inline]
Gets the algorithm parameters.
Definition at line 76 of file MAS5Workflow.h.
void MAS5Workflow::Clear (void)
Clears them members.
Definition at line 53 of file MAS5Workflow.cpp.
Referenced by MAS5Workflow(), and ~MAS5Workflow().
bool MAS5Workflow::Execute (const std::string & celFile, const std::string & baselineCelFile, const std::string & cdfFile, const std::string & chpFile)
Executes the algorithm, report and saves the results to a CHP file.
Parameters:
celFile The input CEL file.
baselineCelFile The baseline file, empty if no comparison analysis is to be performed.
cdfFile The CDF file name (full path).
chpFile The name of the output CHP file.
Returns:
True if success.
Definition at line 68 of file MAS5Workflow.cpp.
References MAS5ReportDataAccessor::IsAntiSense(), MAS5CHPUtils::SaveCHPFile(), and MAS5CHPUtils::SetProgramInformation().
std::string MAS5Workflow::GetError () [inline]
Get the last error.
Definition at line 73 of file MAS5Workflow.h.
int& MAS5Workflow::ProbePairThreshold () [inline]
The probe pair threshold for the report.
Definition at line 79 of file MAS5Workflow.h.
std::wstring& MAS5Workflow::ProgramCompany () [inline]
The company name.
Definition at line 100 of file MAS5Workflow.h.
std::wstring& MAS5Workflow::ProgramId () [inline]
The ID of the program.
Definition at line 103 of file MAS5Workflow.h.
std::wstring& MAS5Workflow::ProgramName () [inline]
The program name.
Definition at line 97 of file MAS5Workflow.h.
ExpressionReport::ExpressionControls& MAS5Workflow::ReportControls () [inline]
The expression controls for the report.
Definition at line 85 of file MAS5Workflow.h.
bool& MAS5Workflow::SaveToLegacyFile () [inline]
Indicates if the data should be saved to the old format CHP file.
Definition at line 82 of file MAS5Workflow.h.
The documentation for this class was generated from the following files:
mas5-stat/workflow/MAS5Workflow.h
mas5-stat/workflow/MAS5Workflow.cpp