Affymetrix Power Tools: TranslationTable Class Reference
TranslationTable Class Reference
Public Member Functions
TranslationTable (const RunTimeEnvironment &rte, TranslationTableModel &ttm, const CopyNumberTableModel &cntm)
TranslationTable::TranslationTable Synopsis: Main constructor.
bool hasGeneCall (const std::string &geneName)
TranslationTable::hasGeneCall Synopsis:
std::vector< GeneCall > getGeneCallGroup (const std::string &geneName)
TranslationTable::getGeneCallGroup Synopsis:
void translateExperimentGene (RunTimeEnvironment &rte, GenotypeTableModel &gtm, const TranslationTableModel &ttm, const CopyNumberTableModel &cntm, ExperimentGeneResults *egr)
TranslationTable::translateExperimentGene Snyopsis: Perform translation and invoke the translation algorithm found in the GeneCall business object.
Public Attributes
std::map< std::string,
std::vector< GeneCall > > m_geneGroup
std::map< std::string, CallSet > m_geneGroupCompleteCallSet
std::map< std::string,
std::string > m_geneExperimentCopyNumberCall
std::map< std::string, CallSet > m_geneCopyNumberZeroCallSet
Detailed Description
Definition at line 44 of file TranslationTable.h.
Constructor & Destructor Documentation
TranslationTable::TranslationTable (const RunTimeEnvironment & rte, TranslationTableModel & ttm, const CopyNumberTableModel & cntm)
TranslationTable::TranslationTable Synopsis: Main constructor.
Truth be told, this object should really be refactored to just "Translation" and not "TranslationTable". There was a time where object was closely coupled with the translation table but no more.
This object is primarily comprised of a hash of gene call business objects derived from the translation table. The key is the gene name. The value is a std::vector of GenCalls corresponding to the "Reference", "Variant", and "A1" ... "AN" columns of the translation table. Non-haplotype markers will only have GeneCalls that correspond to the "Reference" and "Variant" columns. There will be a GeneCall per each non-haplotype marker plus one for the single possible Haplotype set of markers.
During translation, each GeneCall will be attempted to match the CHP experiment data and if a match is find then the underlying CallSet contained within the GeneCall will be attached to the CallResults object.
1.) GeneCall with CallSets for making translation calls. 2.) Zero Copy Number CallSets per gene.
Parameters:
rte - the single instance run time environment
ttm - the single instance TranslationTableModel
cntm - CopyNumberTableModel which carries the override alleles.
Definition at line 137 of file TranslationTable.cpp.
References APT_ERR_ABORT, APT_ERR_ASSERT, TranslationTableModel::getColumnIndex(), TranslationTableModel::getCopyNumberColumn(), TranslationTableModel::getHaplotypeAlleleColumns(), TranslationInputTsvTableModel::getRowAsString(), TranslationTableModel::ignoreRow(), isGeneCopyNumberSensitive(), TranslationTableModel::isRowHaplotype(), Verbose::out(), ToStr(), and TranslationTableModel::validateRowIsHeader().
Member Function Documentation
std::vector< GeneCall > TranslationTable::getGeneCallGroup (const std::string & geneName)
TranslationTable::getGeneCallGroup Synopsis:
A selector for the m_geneGroup.
Typically a GeneCallGroup will be made up of SNPs (single markers) and one possilbe Haplotype CallSet. In any case, the entire set is returned with this method.
Parameters:
geneName - TranslationTableModel gene.
Returns:
std::vector<GeneCall> - the group of GeneCalls found. a
Definition at line 337 of file TranslationTable.cpp.
Referenced by translateExperimentGene().
bool TranslationTable::hasGeneCall (const std::string & geneName)
TranslationTable::hasGeneCall Synopsis:
Interrogate the std::vector of GeneCalls if a particular gene name is available for making a call. If not then there is no experiment analysis to be done.
Returns:
true - if the passed in gene name has any corresponding GeneCall.
Definition at line 356 of file TranslationTable.cpp.
Referenced by translateExperimentGene().
void TranslationTable::translateExperimentGene (RunTimeEnvironment & rte, GenotypeTableModel & gtm, const TranslationTableModel & ttm, const CopyNumberTableModel & cntm, ExperimentGeneResults * egr)
TranslationTable::translateExperimentGene Snyopsis: Perform translation and invoke the translation algorithm found in the GeneCall business object.
Marshalls all the requisite data for making each translation call and then again packages up the results in the CallResults business object whenever a call is made.
To re-state this routine is mostly just a wrapper around the GeneCall method of similar name, translateExperimentCall. The difference being is that this method iterates over all the GeneCall's in a group and summarizes the results in the return ExperimentGeneResults.
So the way this works is that each GeneCall acts as a filter on the input genotype experiment data. Genotype data is grouped into genes within the GenotypeTableModel being passed in. Each GeneCall corresponds to precisely one gene marker or probe set, or the gene's single Haplotype marker set. The input genotype data (CHP) represented by the GenotypeTableModel is searched for the probe sets required for GeneCall. The two chromatid CallSets are built from the GenotypTableModel for the GeneCall in question and then the translation algorithm is invoked to find a match.
If the input genotype data (CHP) does not contain the probe sets required for the GeneCall in question then the GeneCall is skipped. There is an exception with respect to the Haplotype set of markers. If the program option is given to enforce that entire Haplotype sets be complete for translation and markers are found missing within the input genotype data (CHP), then an exception will be thrown.
In the common case, an incomplete haplotype group results in the haplotype GeneCall being skipped, but realize that each individual marker has an individual marker GeneCall and so will still have its marker "Ref/Var" call made.
Parameters:
rte - the single instance run time environment
gtm - the experiment Genotype Tabel model filtered for a single gene.
ttm - the single instance translation table model.
cntm - DMET2 ONLY: the copy number table model
egr - the experiment gene results for return
Returns:
- egr, experiment gene results is filled in with the calls for the entire experiment gene.
Definition at line 415 of file TranslationTable.cpp.
References ExperimentGeneResults::appendCallResults(), APT_ERR_ABORT, APT_ERR_ASSERT, getGeneCallGroup(), hasGeneCall(), Verbose::out(), and Verbose::warn().
Referenced by TranslationEngine::runImp().
The documentation for this class was generated from the following files:
translation/TranslationTable.h
translation/TranslationTable.cpp