Affymetrix Power Tools: affymetrix_calvin_io::TemplateFileReader Class Reference
affymetrix_calvin_io::TemplateFileReader Class Reference
#include <TemplateFileReader.h>
Public Member Functions
TemplateFileReader ()
~TemplateFileReader ()
bool Read (const std::string &fileName, affymetrix_calvin_template::TemplateData &templateData, bool headerOnly=false)
Static Public Member Functions
static bool IsFileType (const std::string &fileName, const affymetrix_calvin_utilities::AffymetrixGuidType &dataTypeId)
static
affymetrix_calvin_utilities::AffymetrixGuidType DataTypeIdentifier (const std::string &fileName)
Protected Attributes
std::wstring fileVersionNumber
Detailed Description
This class provides interfaces to read a template file.
Definition at line 41 of file TemplateFileReader.h.
Constructor & Destructor Documentation
TemplateFileReader::TemplateFileReader ()
Constructor
Definition at line 41 of file TemplateFileReader.cpp.
TemplateFileReader::~TemplateFileReader ()
Destructor
Definition at line 48 of file TemplateFileReader.cpp.
Member Function Documentation
affymetrix_calvin_utilities::AffymetrixGuidType TemplateFileReader::DataTypeIdentifier (const std::string & fileName) [static]
The identifier of the type of data stored in the file.
Parameters:
fileName The name of the file to check.
Returns:
The identifier of the type of data.
Definition at line 117 of file TemplateFileReader.cpp.
References affymetrix_calvin_template::TemplateData::DataTypeIdentifier(), and Read().
Referenced by IsFileType().
bool TemplateFileReader::IsFileType (const std::string & fileName, const affymetrix_calvin_utilities::AffymetrixGuidType & dataTypeId) [static]
Determines if a file is of the specified type.
Parameters:
fileName The name of the file to check.
dataTypeId An identifier to the type of data.
Returns:
True if the file matches the type desired.
Definition at line 106 of file TemplateFileReader.cpp.
References DataTypeIdentifier().
bool TemplateFileReader::Read (const std::string & fileName, affymetrix_calvin_template::TemplateData & templateData, bool headerOnly = false)
Reads the entire contents of the file.
Parameters:
fileName The name of the template file to read.
templateData The template data to read from the file.
headerOnly Flag to indicate that the header line should only be read.
Definition at line 55 of file TemplateFileReader.cpp.
References affymetrix_calvin_template::TemplateData::Clear(), affymetrix_calvin_io::SAXTemplateHandlers::FileVersionNumber(), and fileVersionNumber.
Referenced by DataTypeIdentifier().
Member Data Documentation
std::wstring affymetrix_calvin_io::TemplateFileReader::fileVersionNumber [protected]
The files version number.
Definition at line 52 of file TemplateFileReader.h.
Referenced by Read().
The documentation for this class was generated from the following files:
calvin_files/parsers/src/TemplateFileReader.h
calvin_files/parsers/src/TemplateFileReader.cpp