Affymetrix Power Tools: CelExtract Class Reference
CelExtract Class Reference
Public Member Functions
CelExtract (CelExtractOptions &o)
Constructor.
~CelExtract ()
Destructor.
void extract ()
Do the extraction.
void doProbe (IntensityMart *iMart, std::vector< affx::TsvFile * > &tsv, bool bDoSaturationReport=false)
Dump intensities iterating over probes.
void doProbeSet (IntensityMart *iMart, std::vector< affx::TsvFile * > &tsv)
Dump intensities iterating over probe sets.
void defineExtractTsv (std::vector< affx::TsvFile * > &tsv, bool bDoSaturationReport=false)
Setup the TSV file for output, write headers, define columns, open ostream.
void tsvSetProbeAnnotations (affx::TsvFile *tsv, int &columnCount, ProbeSet *ps, int aIx, int plIx)
Set the various probe level annotations for a specific probeset.
Detailed Description
Definition at line 100 of file CelExtract.h.
Constructor & Destructor Documentation
CelExtract::CelExtract (CelExtractOptions & o)
Constructor.
what probesets to load, we leave this empty == load all / or fill in to restrict if probeset list file given
what probes to ignore, we leave this empty == none to kill
what probeset types (ie genotype) to load, we leave this empty == load all
Definition at line 166 of file CelExtract.cpp.
References ProbeListFactory::asProbeSet(), ProbeSet::atoms, CelExtractOptions::bgpFile, CelExtractOptions::cdfFile, CelExtractOptions::celFiles, Err::check(), CelExtractOptions::clfFile, affymetrix_fusion_io::FusionCELData::Close(), Err::errAbort(), Freez(), affymetrix_fusion_io::FusionCELData::GetChannels(), affymetrix_fusion_io::FusionCELData::GetCols(), affx::ClfFile::getOrder(), ChipLayout::getProbeListAtIndex(), ChipLayout::getProbeListByName(), ChipLayout::getProbeSetCount(), ChipLayout::getProbeSetIndexByName(), affymetrix_fusion_io::FusionCELData::GetRows(), affx::ClfFile::getSequential(), CelExtractOptions::ignoreProbesWithoutMM, ProbeSet::name, affx::ClfFile::open(), ChipLayout::openCdf(), ChipLayout::openPgf(), ChipLayout::openSpf(), Verbose::out(), CelExtractOptions::outFile, CelExtractOptions::pgfFile, CelExtractOptions::pmOnly, CelExtractOptions::probeIdsFiles, CelExtractOptions::probesetIdsFiles, affymetrix_fusion_io::FusionCELData::ReadHeader(), EngineUtil::readProbeFile(), EngineUtil::readProbeSetFile(), affymetrix_fusion_io::FusionCELData::SetFileName(), CelExtractOptions::spfFile, and ToStr().
Member Function Documentation
void CelExtract::defineExtractTsv (std::vector< affx::TsvFile * > & tsv, bool bDoSaturationReport = false)
Setup the TSV file for output, write headers, define columns, open ostream.
Parameters:
tsv - TsvFile object
Definition at line 378 of file CelExtract.cpp.
References Fs::basename(), CelExtractOptions::celFiles, CelExtractOptions::commandLine, CelExtractOptions::execGuid, CelExtractOptions::m_output_precision, ChipLayout::m_XCount, and ToStr().
Referenced by extract().
void CelExtract::doProbe (IntensityMart * iMart, std::vector< affx::TsvFile * > & tsv, bool bDoSaturationReport = false)
Dump intensities iterating over probes.
Parameters:
iMart - the intensity mart to use -- already allocated, but not loaded
tsv - the tsv object to write to
Definition at line 630 of file CelExtract.cpp.
References CelExtractOptions::celFiles, IntensityMart::getProbeIntensity(), Verbose::out(), Verbose::progressStep(), CelReader::readFiles(), AnalysisStream::registerChipStreamObjs(), IntensityReader::registerIntensityMart(), and IntensityReader::setFiles().
Referenced by extract().
void CelExtract::doProbeSet (IntensityMart * iMart, std::vector< affx::TsvFile * > & tsv)
Dump intensities iterating over probe sets.
Parameters:
iMart - the intensity mart to use -- already allocated, but not loaded
tsv - the tsv object to write to
Definition at line 560 of file CelExtract.cpp.
References ProbeListFactory::asProbeSet(), ProbeSet::atoms, CelExtractOptions::celFiles, Freez(), IntensityMart::getProbeIntensity(), ChipLayout::getProbeListAtIndex(), ChipLayout::indexToXY(), Verbose::out(), CelExtractOptions::pairWithBackground, PmAdjuster::pmAdjustment(), Verbose::progressStep(), CelReader::readFiles(), AnalysisStream::registerChipStreamObjs(), IntensityReader::registerIntensityMart(), IntensityReader::setFiles(), CelExtractOptions::subtractBackground, ToStr(), QuantMethod::transformPrimaryData(), and tsvSetProbeAnnotations().
Referenced by extract().
void CelExtract::tsvSetProbeAnnotations (affx::TsvFile * tsv, int & columnCount, ProbeSet * ps, int aIx, int plIx)
Set the various probe level annotations for a specific probeset.
Parameters:
tsv - the TsvFile object
columnCount - the column to start with. will be updated.
ps - pointer to the probeset
aIx - the atom index (relative to probeset)
plIx - the probe index (relative to probeset)
Definition at line 714 of file CelExtract.cpp.
References ProbeSet::atoms, ProbeSet::atomsPerGroup, ProbeSet::name, ProbeSet::numGroups, Verbose::out(), ProbeSet::psType, ToStr(), and ProbeSet::typeEnumToString().
Referenced by doProbeSet().
The documentation for this class was generated from the following files:
chipstream/apt-cel-extract/CelExtract.h
chipstream/apt-cel-extract/CelExtract.cpp