Affymetrix Power Tools: QuantIterPlier Class Reference
QuantIterPlier Class Reference
Class for doing probe set quantification estimate by iteratively calling PLIER with the probes that best correlate with signal estimate.
#include <QuantIterPlier.h>