Affymetrix Power Tools: QuantMethodExprCHPReport Class Reference
QuantMethodExprCHPReport Class Reference
Class for reporting results of quantification methods.
#include <QuantMethodExprCHPReport.h>