Affymetrix Power Tools: affymetrix_calvin_io::CDFData Class Reference
affymetrix_calvin_io::CDFData Class Reference
#include <CDFData.h>
Public Member Functions
CDFData ()
CDFData (const std::string &filename)
~CDFData ()
void Clear ()
void SetFilename (const std::string &p)
std::string GetFilename ()
int32_t GetFormatVersion ()
int32_t GetProbeSetCnt ()
void SetProbeSetCnt (u_int32_t cnt, CDFDataTypeIds type)
std::wstring GetProbeSetName (int32_t index)
void SetArrayRows (u_int32_t value)
u_int32_t GetArrayRows ()
void SetArrayCols (u_int32_t value)
u_int32_t GetArrayCols ()
void SetRefSequence (const std::string &seq)
std::string GetRefSequence ()
std::string GetDataTypeId ()
FileHeader * GetFileHeader ()
GenericData & GetGenericData ()
void GetProbeSetInformation (int32_t index, CDFProbeSetInformation &info)
void GetProbeSetInformation (const std::wstring &probeSetName, CDFProbeSetInformation &info)
void GetQCProbeSetInformation (int32_t index, CDFQCProbeSetInformation &info)
void GetQCProbeSetInformation (const std::wstring &probeSetName, CDFQCProbeSetInformation &info)
Friends
class CDFFileReader
Detailed Description
This class stores data from a Calvin CDF file.
Definition at line 88 of file CDFData.h.
Constructor & Destructor Documentation
CDFData::CDFData ()
Constructor
Definition at line 31 of file CDFData.cpp.
References Clear().
CDFData::CDFData (const std::string & filename)
Constructor with file name as input.
Definition at line 37 of file CDFData.cpp.
References Clear(), and SetFilename().
CDFData::~CDFData ()
Destructor
Definition at line 44 of file CDFData.cpp.
References Clear().
Member Function Documentation
void CDFData::Clear ()
Clear member variables
Definition at line 49 of file CDFData.cpp.
References affymetrix_calvin_io::DataSet::Delete(), and affymetrix_calvin_io::GenericData::Header().
Referenced by CDFData(), affymetrix_calvin_io::CDFFileReader::Read(), and ~CDFData().
u_int32_t CDFData::GetArrayCols ()
The number of columns of features in the array.
Returns:
The column count.
Definition at line 87 of file CDFData.cpp.
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::GetCols().
u_int32_t CDFData::GetArrayRows ()
The number of rows of features in the array.
Returns:
The row count.
Definition at line 77 of file CDFData.cpp.
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::GetRows().
std::string CDFData::GetDataTypeId ()
Gets the data type identifier.
Returns:
The data type identifier.
Definition at line 168 of file CDFData.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), and affymetrix_calvin_io::GenericData::Header().
Referenced by GetProbeSetInformation(), affymetrix_fusion_io::FusionCDFData::GetProbeSetType(), and GetQCProbeSetInformation().
FileHeader* affymetrix_calvin_io::CDFData::GetFileHeader () [inline]
Gets the file header object.
Returns:
The file header object.
Definition at line 173 of file CDFData.h.
References affymetrix_calvin_io::GenericData::Header().
std::string CDFData::GetFilename ()
Get filename.
Returns:
The file name.
Definition at line 118 of file CDFData.cpp.
References affymetrix_calvin_io::FileHeader::GetFilename(), and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_calvin_io::CDFFileReader::Read().
int32_t CDFData::GetFormatVersion ()
Get format version.
Returns:
The CDF format version.
Definition at line 67 of file CDFData.cpp.
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::GetFormatVersion().
GenericData& affymetrix_calvin_io::CDFData::GetGenericData () [inline]
Gets the generic data header.
Returns:
The generic data header.
Definition at line 178 of file CDFData.h.
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets(), affymetrix_fusion_io::FusionCDFFileHeader::GetNumQCProbeSets(), affymetrix_fusion_io::FusionCDFData::GetProbeSetInformation(), affymetrix_fusion_io::FusionCDFData::GetProbeSetType(), affymetrix_fusion_io::FusionCDFData::GetQCProbeSetInformation(), and affymetrix_calvin_io::CDFFileReader::Read().
int32_t CDFData::GetProbeSetCnt ()
Gets the probe set count.
Returns:
The number of probe sets.
Definition at line 123 of file CDFData.cpp.
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets(), and affymetrix_fusion_io::FusionCDFFileHeader::GetNumQCProbeSets().
void CDFData::GetProbeSetInformation (int32_t index, CDFProbeSetInformation & info)
Gets the information about a probe set.
Parameters:
index The index to the probe set. Must be between 0 and the number of probe sets - 1.
info The probe set information.
Exceptions:
CDFAccessNotSupportedByModeException
DataSetNotOpenException
Definition at line 287 of file CDFData.cpp.
References AFFY_CNTRL_PS, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), GetDataTypeId(), affymetrix_calvin_io::DataGroupHeader::GetNextGroupPos(), affymetrix_calvin_io::FileHeader::GetNumDataGroups(), affymetrix_calvin_io::DataGroup::Header(), affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_io::CDFProbeSetInformation::SetDataGroup().
void CDFData::GetProbeSetInformation (const std::wstring & probeSetName, CDFProbeSetInformation & info)
Gets the information about a probe set.
Parameters:
probeSetName The name of the probe set.
info The probe set information.
Exceptions:
CDFAccessNotSupportedByModeException
DataSetNotOpenException
ProbeSetNotFoundException
Definition at line 331 of file CDFData.cpp.
References AFFY_CNTRL_PS, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), GetDataTypeId(), and affymetrix_calvin_io::CDFProbeSetInformation::SetDataGroup().
std::wstring CDFData::GetProbeSetName (int32_t index)
Get the name of a probe set name based on index. Use this method to get the probe set name for either a regular or QC probe set.
Parameters:
index The index to the probe set. Must be between 0 and the number of probe sets - 1.
Definition at line 448 of file CDFData.cpp.
References affymetrix_calvin_io::DataGroup::DataSet(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::FileHeader::GetFirstDataGroupFilePos(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_io::DataSet::Open(), and affymetrix_calvin_io::DataSet::Rows().
Referenced by affymetrix_fusion_io::FusionCDFData::GetProbeSetName().
void CDFData::GetQCProbeSetInformation (const std::wstring & probeSetName, CDFQCProbeSetInformation & info)
Gets the information about a QC probe set.
Parameters:
probeSetName The name of the QC probe set.
info The probe set information.
Exceptions:
CDFAccessNotSupportedByModeException
DataSetNotOpenException
ProbeSetNotFoundException
Definition at line 397 of file CDFData.cpp.
References AFFY_CNTRL_PS, affymetrix_calvin_io::DataGroup::DataSet(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and GetDataTypeId().
void CDFData::GetQCProbeSetInformation (int32_t index, CDFQCProbeSetInformation & info)
Gets the information about a QC probe set.
Parameters:
index The index of the QC probe set.
info The probe set information.
Exceptions:
CDFAccessNotSupportedByModeException
DataSetNotOpenException
Definition at line 351 of file CDFData.cpp.
References AFFY_CNTRL_PS, affymetrix_calvin_io::DataGroup::DataSet(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), GetDataTypeId(), affymetrix_calvin_io::DataGroupHeader::GetNextGroupPos(), affymetrix_calvin_io::FileHeader::GetNumDataGroups(), affymetrix_calvin_io::DataGroup::Header(), and affymetrix_calvin_io::GenericData::Header().
std::string CDFData::GetRefSequence ()
Gets the reference sequence.
Returns:
The reference sequence.
Definition at line 101 of file CDFData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::Initialize().
void CDFData::SetArrayCols (u_int32_t value)
Sets the number of columns of features in the array.
Parameters:
value The column count.
Definition at line 82 of file CDFData.cpp.
void CDFData::SetArrayRows (u_int32_t value)
Sets the number of rows of features in the array.
Parameters:
value The row count.
Definition at line 72 of file CDFData.cpp.
void CDFData::SetFilename (const std::string & p)
Set filename.
Parameters:
p The name of the file.
Definition at line 113 of file CDFData.cpp.
References affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_io::FileHeader::SetFilename().
Referenced by CDFData().
void CDFData::SetProbeSetCnt (u_int32_t cnt, CDFDataTypeIds type)
The number of probe sets.
Returns:
The number of probe sets.
Definition at line 128 of file CDFData.cpp.
void CDFData::SetRefSequence (const std::string & seq)
Sets the reference sequence for a resequencing array.
Parameters:
seq The reference sequence.
Definition at line 92 of file CDFData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueAscii().
Friends And Related Function Documentation
friend class CDFFileReader [friend]
Friend to the reader.
Definition at line 310 of file CDFData.h.
The documentation for this class was generated from the following files:
calvin_files/data/src/CDFData.h
calvin_files/data/src/CDFData.cpp