Affymetrix Power Tools: CelCheck Class Reference
CelCheck Class Reference
Class for testing that CEL files are the same +/- some epsilon.
#include <CelCheck.h>