Affymetrix Power Tools: GcAdjust Class Reference
GcAdjust Class Reference
Class for doing an adjustment based on the median intensity of probes with similar GC content.
#include <GcAdjust.h>