Affymetrix Power Tools: affymetrix_fusion_io::FusionCDFProbeSetInformation Class Reference
affymetrix_fusion_io::FusionCDFProbeSetInformation Class Reference
#include <FusionCDFData.h>
Public Member Functions
affxcdf::GeneChipProbeSetType GetProbeSetType ()
affxcdf::DirectionType GetDirection () const
int GetNumLists () const
int GetNumGroups () const
int GetNumCells () const
int GetNumCellsPerList () const
int GetProbeSetNumber () const
void GetGroupInformation (int index, FusionCDFProbeGroupInformation &info)
FusionCDFProbeSetInformation ()
~FusionCDFProbeSetInformation ()
Friends
class FusionCDFData
Detailed Description
This class provides storage for a probe set.
Definition at line 284 of file FusionCDFData.h.
Constructor & Destructor Documentation
FusionCDFProbeSetInformation::FusionCDFProbeSetInformation ()
Constructor
Definition at line 817 of file FusionCDFData.cpp.
FusionCDFProbeSetInformation::~FusionCDFProbeSetInformation ()
Destructor
Definition at line 826 of file FusionCDFData.cpp.
Member Function Documentation
affxcdf::DirectionType FusionCDFProbeSetInformation::GetDirection () const
Gets the probe sets direction.
Returns:
The probe sets direction.
Definition at line 922 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFProbeSetInformation::GetDirection(), affxcdf::CCDFProbeSetInformation::GetDirection(), affymetrix_calvin_io::ProbeAntiSenseDirection, affymetrix_calvin_io::ProbeEitherDirection, affymetrix_calvin_io::ProbeNoDirection, and affymetrix_calvin_io::ProbeSenseDirection.
void FusionCDFProbeSetInformation::GetGroupInformation (int index, FusionCDFProbeGroupInformation & info)
Gets a group object.
Parameters:
index The index to the group of interest.
info The returned group data.
Definition at line 1024 of file FusionCDFData.cpp.
Referenced by CRawQ::ComputeRawQ().
int FusionCDFProbeSetInformation::GetNumCells () const
The number of probes in the set.
Returns:
The number of probes in the set.
Definition at line 985 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFProbeSetInformation::GetNumCells(), and affxcdf::CCDFProbeSetInformation::GetNumCells().
Referenced by CRawQ::ComputeRawQ().
int FusionCDFProbeSetInformation::GetNumCellsPerList () const
Gets the number of probes per list.
Returns:
The number of probes per list.
Definition at line 998 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFProbeSetInformation::GetNumCellsPerList(), and affxcdf::CCDFProbeSetInformation::GetNumCellsPerList().
int FusionCDFProbeSetInformation::GetNumGroups () const
The number of groups in the set.
Returns:
The number of groups in the set.
Definition at line 972 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFProbeSetInformation::GetNumGroups(), and affxcdf::CCDFProbeSetInformation::GetNumGroups().
Referenced by CRawQ::ComputeRawQ().
int FusionCDFProbeSetInformation::GetNumLists () const
Gets the number of lists (atoms) in the group.
Returns:
The number of lists (atoms) in the group.
Definition at line 959 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFProbeSetInformation::GetNumLists(), and affxcdf::CCDFProbeSetInformation::GetNumLists().
int FusionCDFProbeSetInformation::GetProbeSetNumber () const
Gets the probe set number.
Returns:
The probe set number.
Definition at line 1011 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFProbeSetInformation::GetProbeSetNumber(), and affxcdf::CCDFProbeSetInformation::GetProbeSetNumber().
affxcdf::GeneChipProbeSetType FusionCDFProbeSetInformation::GetProbeSetType ()
Gets the probe set type.
Returns:
The probe set type.
Definition at line 865 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CopyNumber, affymetrix_calvin_io::ExpressionControl, affymetrix_calvin_io::GenotypeControl, affymetrix_calvin_io::Genotyping, affymetrix_calvin_io::CDFProbeSetInformation::GetProbeSetType(), affxcdf::CCDFProbeSetInformation::GetProbeSetType(), affymetrix_calvin_io::Marker, affymetrix_calvin_io::MultichannelMarker, affymetrix_calvin_io::Resequencing, and affymetrix_calvin_io::Tag.
Friends And Related Function Documentation
friend class FusionCDFData [friend]
Friend to the parent class.
Definition at line 309 of file FusionCDFData.h.
The documentation for this class was generated from the following files:
calvin_files/fusion/src/FusionCDFData.h
calvin_files/fusion/src/FusionCDFData.cpp