Affymetrix Power Tools: CNAnalysisMethodAllelePeaks Class Reference
CNAnalysisMethodAllelePeaks Class Reference
The Allele Peaks reporter method.
#include <CNAnalysisMethodAllelePeaks.h>