Affymetrix Power Tools: affx::File5_MultiDataUtils Class Reference
affx::File5_MultiDataUtils Class Reference
#include <File5_MultiDataUtils.h>
Public Member Functions
File5_MultiDataUtils ()
virtual ~File5_MultiDataUtils ()
void Open (const std::string &fileName)
void Close ()
void CreateTsv (const std::string &gname, const std::string &dname)
void DefineColumn (const std::string &cname, const File5_dtype_t ctype, int csize=-1)
void AddEntry (int ival)
void AddEntry (float fval)
void AddEntry (const std::string &sval)
void AddParameter (const std::string &key, const std::string &val)
void OpenTsv (const std::string &gname)
void CloseTsv ()
File5_return_t DeleteTsv (const std::string &name)
void GetTOC (std::vector< TableOfContentsEntry > &toc)
bool headersBegin ()
bool headersNext (std::string *key, std::string *val)
void ExtractColumn (const std::string &cname, std::list< int > &col)
void ExtractColumn (const std::string &cname, std::list< float > &col)
void ExtractColumn (const std::string &cname, std::list< std::string > &col)
void ExtractColumnAsString (const std::string &cname, std::list< std::string > &col)
void ExtractColumnNames (std::list< ColumnNameType > &colInfo)
int TsvLineCount ()
bool NextLine (std::string &name, std::vector< int > &data)
bool NextLine (std::string &name, std::vector< float > &data)
bool NextLine (std::string &name, std::vector< std::string > &data)
bool NextLineAsString (std::string &name, std::vector< std::string > &data)
Detailed Description
A utility class for handling a file with multiple data tables.
Definition at line 50 of file File5_MultiDataUtils.h.
Constructor & Destructor Documentation
File5_MultiDataUtils::File5_MultiDataUtils ()
The constructor.
Definition at line 26 of file File5_MultiDataUtils.cpp.
File5_MultiDataUtils::~File5_MultiDataUtils () [virtual]
The destructor.
Definition at line 33 of file File5_MultiDataUtils.cpp.
References Close().
Member Function Documentation
void File5_MultiDataUtils::AddEntry (int ival)
Add an entry to the column.
Parameters:
ival The value to add.
Definition at line 113 of file File5_MultiDataUtils.cpp.
void File5_MultiDataUtils::AddEntry (float fval)
Add an entry to the column.
Parameters:
fval The value to add.
Definition at line 119 of file File5_MultiDataUtils.cpp.
void File5_MultiDataUtils::AddEntry (const std::string & sval)
Add an entry to the column.
Parameters:
sval The value to add.
Definition at line 125 of file File5_MultiDataUtils.cpp.
void File5_MultiDataUtils::AddParameter (const std::string & key, const std::string & val)
Add a parameter to the open group, or file header before DefineColumn is called.
Parameters:
key The parameter key name.
val The parameter value.
Definition at line 131 of file File5_MultiDataUtils.cpp.
void File5_MultiDataUtils::Close (void)
Close the file.
Definition at line 38 of file File5_MultiDataUtils.cpp.
References CloseTsv().
Referenced by Open(), and ~File5_MultiDataUtils().
void File5_MultiDataUtils::CloseTsv ()
Close the tsv group.
Definition at line 48 of file File5_MultiDataUtils.cpp.
Referenced by Close(), CreateTsv(), and OpenTsv().
void File5_MultiDataUtils::CreateTsv (const std::string & gname, const std::string & dname)
Create a new tsv group.
Parameters:
gname The name of the group.
dname The display name for the group.
Definition at line 82 of file File5_MultiDataUtils.cpp.
References CloseTsv().
void File5_MultiDataUtils::DefineColumn (const std::string & cname, const File5_dtype_t ctype, int csize = -1)
Define a new column
Parameters:
cname The name of the column.
ctype The data type for the column.
csize The size of the column.
Definition at line 105 of file File5_MultiDataUtils.cpp.
File5_return_t File5_MultiDataUtils::DeleteTsv (const std::string & name)
Delete a tsv group.
Definition at line 210 of file File5_MultiDataUtils.cpp.
void File5_MultiDataUtils::ExtractColumn (const std::string & cname, std::list< float > & col)
Extract a column
Parameters:
cname The name of the column.
col The column data.
Definition at line 276 of file File5_MultiDataUtils.cpp.
References ExtractColumn().
void File5_MultiDataUtils::ExtractColumn (const std::string & cname, std::list< std::string > & col)
Extract a column
Parameters:
cname The name of the column.
col The column data.
Definition at line 281 of file File5_MultiDataUtils.cpp.
References ExtractColumn().
void File5_MultiDataUtils::ExtractColumn (const std::string & cname, std::list< int > & col)
Extract a column
Parameters:
cname The name of the column.
col The column data.
Definition at line 271 of file File5_MultiDataUtils.cpp.
Referenced by ExtractColumn().
void File5_MultiDataUtils::ExtractColumnAsString (const std::string & cname, std::list< std::string > & col)
Extract a column as string values
Parameters:
cname The name of the column.
col The column data.
Definition at line 286 of file File5_MultiDataUtils.cpp.
void File5_MultiDataUtils::ExtractColumnNames (std::list< ColumnNameType > & colInfo)
Extract the column names.
Parameters:
colInfo The names and data types of the columns.
Definition at line 307 of file File5_MultiDataUtils.cpp.
References affx::_ColumnNameType::ctype.
void File5_MultiDataUtils::GetTOC (std::vector< TableOfContentsEntry > & toc)
Get the table of contents.
Parameters:
toc The table of contents.
Definition at line 187 of file File5_MultiDataUtils.cpp.
References affx::_TableOfContentsEntry::groupName, and affx::File5_Group::name_exists().
bool File5_MultiDataUtils::headersBegin ()
Initialize retrieval of the header.
Parameters:
groupType The type of group.
Returns:
The status
Definition at line 235 of file File5_MultiDataUtils.cpp.
bool File5_MultiDataUtils::headersNext (std::string * key, std::string * val)
Get the next header.
Parameters:
key The output header key.
val The output header value.
Returns:
The status
Definition at line 247 of file File5_MultiDataUtils.cpp.
bool File5_MultiDataUtils::NextLine (std::string & name, std::vector< float > & data)
Get the next lines data. Assumption is the first column is a name (string) value.
Parameters:
name The row name (first column)
data The remaining columns data.
Returns:
True if success.
Definition at line 165 of file File5_MultiDataUtils.cpp.
References NextLine().
bool File5_MultiDataUtils::NextLine (std::string & name, std::vector< int > & data)
Get the next lines data. Assumption is the first column is a name (string) value.
Parameters:
name The row name (first column)
data The remaining columns data.
Returns:
True if success.
Definition at line 160 of file File5_MultiDataUtils.cpp.
Referenced by NextLine().
bool File5_MultiDataUtils::NextLine (std::string & name, std::vector< std::string > & data)
Get the next lines data. Assumption is the first column is a name (string) value.
Parameters:
name The row name (first column)
data The remaining columns data.
Returns:
True if success.
Definition at line 170 of file File5_MultiDataUtils.cpp.
References NextLine().
bool File5_MultiDataUtils::NextLineAsString (std::string & name, std::vector< std::string > & data)
Get the next lines data as string values. Assumption is the first column is a name (string) value.
Parameters:
name The row name (first column)
data The remaining columns data.
Returns:
True if success.
Definition at line 175 of file File5_MultiDataUtils.cpp.
void File5_MultiDataUtils::Open (const std::string & fileName)
Open an existing, or create a new, file.
Parameters:
fileName The name of the file.
Definition at line 65 of file File5_MultiDataUtils.cpp.
References Close().
void File5_MultiDataUtils::OpenTsv (const std::string & gname)
Open an existing tsv group.
Parameters:
gname The name of the group.
Definition at line 204 of file File5_MultiDataUtils.cpp.
References CloseTsv().
int File5_MultiDataUtils::TsvLineCount ()
The line count of the open TSV group.
Definition at line 141 of file File5_MultiDataUtils.cpp.
The documentation for this class was generated from the following files:
file5/File5_MultiDataUtils.h
file5/File5_MultiDataUtils.cpp