Affymetrix Power Tools: CNFamilialAnalysisMethodHeteroUPD Class Reference
CNFamilialAnalysisMethodHeteroUPD Class Reference
The HeteroUPD Familial analysis method.
#include <CNFamilialAnalysisMethodHeteroUPD.h>