Affymetrix Power Tools: affymetrix_fusion_io::FusionCDFData Class Reference
affymetrix_fusion_io::FusionCDFData Class Reference
#include <FusionCDFData.h>
Public Member Functions
FusionCDFData ()
~FusionCDFData ()
void SetFileName (const char *name)
std::string GetFileName () const
FusionCDFFileHeader & GetHeader ()
std::string GetGUID ()
std::string GetIntegrityMd5 ()
std::string GetError () const
std::string GetProbeSetName (int index) const
std::string GetChipType ()
std::vector< std::string > GetChipTypes ()
bool Read ()
bool ReadHeader ()
bool Exists ()
void Close ()
affxcdf::GeneChipProbeSetType GetProbeSetType (int index) const
void GetProbeSetInformation (int index, FusionCDFProbeSetInformation &info)
void GetQCProbeSetInformation (int index, FusionCDFQCProbeSetInformation &info)
void GetQCProbeSetInformation (affxcdf::GeneChipQCProbeSetType qcType, FusionCDFQCProbeSetInformation &info)
Static Public Member Functions
static bool IsXDACompatibleFile (const char *fileName)
static bool IsCalvinCompatibleFile (const char *fileName)
Protected Member Functions
void CreateObject ()
Protected Attributes
affxcdf::CCDFFileData * gcosData
FusionCDFFileHeader header
affymetrix_calvin_io::CDFData * calvinData
std::string fileName
Detailed Description
This defines the combined GCOS/Calvin CDF data interaction class.
Definition at line 486 of file FusionCDFData.h.
Constructor & Destructor Documentation
FusionCDFData::FusionCDFData ()
Constructor
Definition at line 1056 of file FusionCDFData.cpp.
References calvinData, and gcosData.
FusionCDFData::~FusionCDFData ()
Destructor
Definition at line 1065 of file FusionCDFData.cpp.
References Close().
Member Function Documentation
void FusionCDFData::Close (void)
Deallocates memory and closes any file handles.
Definition at line 1294 of file FusionCDFData.cpp.
References calvinData, affxcdf::CCDFFileData::Close(), and gcosData.
Referenced by CRawQWorkflow::Clear(), CreateObject(), ChipLayout::openCdf(), and ~FusionCDFData().
void FusionCDFData::CreateObject () [protected]
Creates either the GCOS or Calvin parser object.
Definition at line 1040 of file FusionCDFData.cpp.
References calvinData, Close(), fileName, gcosData, and IsCalvinCompatibleFile().
Referenced by GetChipType(), GetChipTypes(), GetGUID(), GetIntegrityMd5(), Read(), and ReadHeader().
bool FusionCDFData::Exists ()
Checks if the file exists.
Returns:
True if the file exists.
Definition at line 1288 of file FusionCDFData.cpp.
References fileName.
Referenced by CRawQWorkflow::LoadCDFFile(), ChipLayout::openCdf(), and affymetrix_chp_converter::CHPFileConvertToCalvin::ValidateMas5File().
std::string FusionCDFData::GetChipType ()
Gets the chip type (probe array type) of the CDF file.
Returns:
The chip type. This is just the name (without extension) of the CDF file.
Definition at line 1164 of file FusionCDFData.cpp.
References calvinData, CreateObject(), fileName, gcosData, affxcdf::CCDFFileData::GetChipType(), and affxcdf::CCDFFileData::SetFileName().
Referenced by ChipLayout::openCdf().
std::vector< std::string > FusionCDFData::GetChipTypes ()
Gets the chip types (probe array type) of the CDF file. Allow substrings deliminated by '.'
Returns:
vector of chip types
Definition at line 1191 of file FusionCDFData.cpp.
References calvinData, CreateObject(), fileName, gcosData, affxcdf::CCDFFileData::GetChipTypes(), and affxcdf::CCDFFileData::SetFileName().
Referenced by EngineUtil::getCdfChipType(), and ChipLayout::openCdf().
std::string FusionCDFData::GetError () const
Gets the error string.
Returns:
A string describing the last read error.
Definition at line 1138 of file FusionCDFData.cpp.
References gcosData, and affxcdf::CCDFFileData::GetError().
Referenced by EngineUtil::getCdfChipType(), and ChipLayout::openCdf().
std::string FusionCDFData::GetFileName () const
Gets the name of the file.
Returns:
The full path of the CDF file.
Definition at line 1081 of file FusionCDFData.cpp.
References fileName.
Referenced by ChipLayout::openCdf().
std::string FusionCDFData::GetGUID ()
Get GUID
Returns:
GUID
Definition at line 1106 of file FusionCDFData.cpp.
References calvinData, CreateObject(), fileName, gcosData, affxcdf::CCDFFileData::GetGUID(), and affxcdf::CCDFFileData::SetFileName().
Referenced by ChipLayout::openCdf().
FusionCDFFileHeader & FusionCDFData::GetHeader ()
Gets the header object.
Returns:
The CDF file header object.
Definition at line 1089 of file FusionCDFData.cpp.
References calvinData, gcosData, header, and affymetrix_fusion_io::FusionCDFFileHeader::Initialize().
Referenced by CRawQ::ComputeRawQ(), EngineUtil::getCdfChipType(), CRawQWorkflow::IsExpressionArray(), ChipLayout::openCdf(), and ChipLayout::readProbeListCdfFileKillList().
std::string FusionCDFData::GetIntegrityMd5 ()
Get integrity md5
Returns:
integrity md5
Definition at line 1122 of file FusionCDFData.cpp.
References calvinData, CreateObject(), fileName, gcosData, affxcdf::CCDFFileData::GetIntegrityMd5(), and affxcdf::CCDFFileData::SetFileName().
void FusionCDFData::GetProbeSetInformation (int index, FusionCDFProbeSetInformation & info)
Gets the probe set information.
Parameters:
index The index to the probe set of interest.
info The probe set information.
Returns:
The probe set information.
Definition at line 1372 of file FusionCDFData.cpp.
References calvinData, gcosData, affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), affymetrix_calvin_io::CDFData::GetGenericData(), and affymetrix_calvin_io::GenericData::Header().
Referenced by CRawQ::ComputeRawQ(), and ChipLayout::readProbeListCdfFileKillList().
std::string FusionCDFData::GetProbeSetName (int index) const
Gets the name of a probe set.
Parameters:
index The index to the probe set name of interest.
Returns:
The probe set name.
Definition at line 1149 of file FusionCDFData.cpp.
References calvinData, gcosData, affymetrix_calvin_io::CDFData::GetProbeSetName(), and affxcdf::CCDFFileData::GetProbeSetName().
Referenced by ChipLayout::readProbeListCdfFileKillList().
affxcdf::GeneChipProbeSetType FusionCDFData::GetProbeSetType (int index) const
Gets the probe set type for non-qc probe sets.
Parameters:
index The index to the probe set of interest.
Returns:
The type of probe set.
Definition at line 1341 of file FusionCDFData.cpp.
References AFFY_EXPR_PS, AFFY_GENO_PS, AFFY_RESEQ_PS, AFFY_TAG_PS, calvinData, gcosData, affymetrix_calvin_io::CDFData::GetDataTypeId(), affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), affymetrix_calvin_io::CDFData::GetGenericData(), affxcdf::CCDFFileData::GetProbeSetType(), and affymetrix_calvin_io::GenericData::Header().
Referenced by CRawQ::ComputeRawQ(), and CRawQWorkflow::IsExpressionArray().
void FusionCDFData::GetQCProbeSetInformation (int index, FusionCDFQCProbeSetInformation & info)
Gets the QC probe set information by index.
Parameters:
index The index to the QC probe set of interest.
info The QC probe set information.
Returns:
The QC probe set information.
Definition at line 1389 of file FusionCDFData.cpp.
References calvinData, gcosData, affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), affymetrix_calvin_io::CDFData::GetGenericData(), and affymetrix_calvin_io::GenericData::Header().
void FusionCDFData::GetQCProbeSetInformation (affxcdf::GeneChipQCProbeSetType qcType, FusionCDFQCProbeSetInformation & info)
Gets the QC probe set information by type.
Parameters:
qcType The type of QC probe set to retrieve.
info The QC probe set information.
Returns:
The QC probe set information.
Definition at line 1406 of file FusionCDFData.cpp.
References calvinData, gcosData, affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), affymetrix_calvin_io::CDFData::GetGenericData(), and affymetrix_calvin_io::GenericData::Header().
bool FusionCDFData::IsCalvinCompatibleFile (const char * fileName) [static]
Determines if a CDF file is of the Calvin format.
Parameters:
fileName The name of the file to test.
Returns:
True if Calvin format.
Definition at line 1322 of file FusionCDFData.cpp.
References affymetrix_calvin_io::GenericFileReader::ReadHeader(), and affymetrix_calvin_io::GenericFileReader::SetFilename().
Referenced by CreateObject().
bool FusionCDFData::IsXDACompatibleFile (const char * fileName) [static]
Determines if a CDF file is of the XDA (binary) format.
Parameters:
fileName The name of the file to test.
Returns:
True if XDA format.
Definition at line 1312 of file FusionCDFData.cpp.
References affxcdf::CCDFFileData::IsXDACompatibleFile(), and affxcdf::CCDFFileData::SetFileName().
bool FusionCDFData::Read ()
Reads the entire file.
Returns:
True if successful.
Definition at line 1233 of file FusionCDFData.cpp.
References calvinData, CreateObject(), fileName, gcosData, affymetrix_calvin_io::CDFFileReader::Read(), affxcdf::CCDFFileData::Read(), affymetrix_calvin_io::CDFFileReader::SetFilename(), and affxcdf::CCDFFileData::SetFileName().
Referenced by CRawQWorkflow::LoadCDFFile(), and ChipLayout::openCdf().
bool FusionCDFData::ReadHeader ()
Reads the header of the file only.
Returns:
True if successful.
Definition at line 1261 of file FusionCDFData.cpp.
References calvinData, CreateObject(), fileName, gcosData, affymetrix_calvin_io::CDFFileReader::Read(), affxcdf::CCDFFileData::ReadHeader(), affymetrix_calvin_io::CDFFileReader::SetFilename(), and affxcdf::CCDFFileData::SetFileName().
Referenced by EngineUtil::getCdfChipType(), and ChipLayout::openCdf().
void FusionCDFData::SetFileName (const char * name)
Sets the name of the file.
Parameters:
name The full path of the CDF file.
Definition at line 1073 of file FusionCDFData.cpp.
References fileName.
Referenced by EngineUtil::getCdfChipType(), CRawQWorkflow::LoadCDFFile(), ChipLayout::openCdf(), and affymetrix_chp_converter::CHPFileConvertToCalvin::ValidateMas5File().
Member Data Documentation
affymetrix_calvin_io::CDFData* affymetrix_fusion_io::FusionCDFData::calvinData [protected]
The Calvin CDF file object.
Definition at line 496 of file FusionCDFData.h.
Referenced by Close(), CreateObject(), FusionCDFData(), GetChipType(), GetChipTypes(), GetGUID(), GetHeader(), GetIntegrityMd5(), GetProbeSetInformation(), GetProbeSetName(), GetProbeSetType(), GetQCProbeSetInformation(), Read(), and ReadHeader().
std::string affymetrix_fusion_io::FusionCDFData::fileName [protected]
The name of the file to read.
Definition at line 499 of file FusionCDFData.h.
Referenced by CreateObject(), Exists(), GetChipType(), GetChipTypes(), GetFileName(), GetGUID(), GetIntegrityMd5(), Read(), ReadHeader(), and SetFileName().
affxcdf::CCDFFileData* affymetrix_fusion_io::FusionCDFData::gcosData [protected]
The GCOS CDF file object.
Definition at line 490 of file FusionCDFData.h.
Referenced by Close(), CreateObject(), FusionCDFData(), GetChipType(), GetChipTypes(), GetError(), GetGUID(), GetHeader(), GetIntegrityMd5(), GetProbeSetInformation(), GetProbeSetName(), GetProbeSetType(), GetQCProbeSetInformation(), Read(), and ReadHeader().
FusionCDFFileHeader affymetrix_fusion_io::FusionCDFData::header [protected]
The header object.
Definition at line 493 of file FusionCDFData.h.
Referenced by GetHeader().
The documentation for this class was generated from the following files:
calvin_files/fusion/src/FusionCDFData.h
calvin_files/fusion/src/FusionCDFData.cpp