Affymetrix Power Tools: affxgrd::CGRDFileWriter Class Reference
affxgrd::CGRDFileWriter Class Reference
#include <GRDFileWriter.h>