Affymetrix Power Tools: CalvinChpCheck Class Reference
CalvinChpCheck Class Reference
Class for testing that CHP files are the same +/- some epsilon.
#include <CalvinChpCheck.h>