Affymetrix Power Tools: CNAnalysisMethodGaussianSmooth Class Reference
CNAnalysisMethodGaussianSmooth Class Reference
The log2 ration gaussian smooth analysis method.
#include <CNAnalysisMethodGaussianSmooth.h>