Affymetrix Power Tools: affymetrix_chp_converter::CHPConversionUtilities Class Reference
affymetrix_chp_converter::CHPConversionUtilities Class Reference
#include <CHPConversionUtilities.h>
Static Public Member Functions
static void Copy (affymetrix_calvin_io::CHPData &inFile, affxchpwriter::CCHPFileWriter &outFile)
static void SetAlgName (affxchpwriter::CCHPFileWriter &outFile, std::string algName)
Detailed Description
This class will copy Calvin data to GCOS CHP objects.
Definition at line 38 of file CHPConversionUtilities.h.
Member Function Documentation
void CHPConversionUtilities::Copy (affymetrix_calvin_io::CHPData & inFile, affxchpwriter::CCHPFileWriter & outFile) [static]
Copies the calvin object to the GCOS object.
Parameters:
inFile The Calvin CHP file object.
outFile The GCOS CHP file object.
Definition at line 46 of file CHPConversionUtilities.cpp.
References affxchpwriter::CCHPFileWriter::AddAlgorithmParameter(), affxchpwriter::CCHPFileWriter::AddBackgroundInfo(), affxchpwriter::CCHPFileWriter::AddBackgroundZone(), affxchpwriter::CCHPFileWriter::AddChipSummaryParameter(), affxchp::CGenotypeProbeSetResults::AlleleCall, affymetrix_calvin_io::_CHPReseqOrigCall::call, affxchp::_BaseCallType::call, affymetrix_calvin_io::_CHPReseqForceCall::call, affxchp::_ForceCallType::call, affymetrix_calvin_io::_CHPReseqEntry::call, affxchp::CExpressionProbeSetResults::Change, affxchp::CExpressionProbeSetResults::ChangePValue, CHP_EXPRESSION_ASSAY_TYPE, CHP_GENOTYPING_ASSAY_TYPE, CHP_RESEQUENCING_ASSAY_TYPE, CHP_UNIVERSAL_ASSAY_TYPE, affxchp::CGenotypeProbeSetResults::Confidence, affxchp::CExpressionProbeSetResults::Detection, affxchp::CExpressionProbeSetResults::DetectionPValue, affymetrix_calvin_io::CHPData::GetAlgName(), affymetrix_calvin_io::CHPData::GetAlgParams(), affymetrix_calvin_io::CHPData::GetAlgVersion(), affymetrix_calvin_io::CHPData::GetArrayType(), affymetrix_calvin_io::CHPData::GetAssayType(), affymetrix_calvin_io::CHPData::GetBackgroundZone(), affymetrix_calvin_io::CHPData::GetBackgroundZoneCnt(), affymetrix_calvin_io::CHPExpressionEntry::GetChange(), affymetrix_calvin_io::CHPExpressionEntry::GetChangePValue(), affymetrix_calvin_io::CHPData::GetChipSums(), affymetrix_calvin_io::CHPData::GetCols(), affymetrix_calvin_io::CHPExpressionEntry::GetCommonPairs(), affymetrix_calvin_io::CHPExpressionEntry::GetDetection(), affymetrix_calvin_io::CHPExpressionEntry::GetDetectionPValue(), affymetrix_calvin_io::CHPData::GetEntry(), affymetrix_calvin_io::CHPData::GetEntryCount(), affymetrix_calvin_io::CHPData::GetForceCall(), affymetrix_calvin_io::CHPData::GetForceCnt(), affymetrix_calvin_io::CHPExpressionEntry::GetHasComparisonData(), affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_io::CHPExpressionEntry::GetNumPairs(), affymetrix_calvin_io::CHPExpressionEntry::GetNumPairsUsed(), affymetrix_calvin_io::CHPData::GetOrigCall(), affymetrix_calvin_io::CHPData::GetOrigCnt(), affymetrix_calvin_io::CHPData::GetParentCell(), affymetrix_calvin_io::CHPData::GetProgId(), affymetrix_calvin_io::CHPData::GetRows(), affymetrix_calvin_io::CHPExpressionEntry::GetSigLogRatio(), affymetrix_calvin_io::CHPExpressionEntry::GetSigLogRatioHi(), affymetrix_calvin_io::CHPExpressionEntry::GetSigLogRatioLo(), affymetrix_calvin_io::CHPExpressionEntry::GetSignal(), affxchpwriter::CCHPFileWriter::InitializeForWriting(), affxchp::CExpressionProbeSetResults::m_HasCompResults, affxchp::CExpressionProbeSetResults::NumCommonPairs, affxchp::CExpressionProbeSetResults::NumPairs, affxchp::CExpressionProbeSetResults::NumUsedPairs, affymetrix_calvin_io::_CHPReseqOrigCall::position, affxchp::_BaseCallType::position, affymetrix_calvin_io::_CHPReseqForceCall::position, affxchp::_ForceCallType::position, affxchp::CGenotypeProbeSetResults::pvalue_AA, affxchp::CGenotypeProbeSetResults::pvalue_AB, affxchp::CGenotypeProbeSetResults::pvalue_BB, affxchp::CGenotypeProbeSetResults::pvalue_NoCall, affxchp::CGenotypeProbeSetResults::RAS1, affxchp::CGenotypeProbeSetResults::RAS2, affymetrix_calvin_io::_CHPReseqForceCall::reason, affxchp::_ForceCallType::reason, affxchp::CResequencingResults::ResizeCalledBases(), affxchp::CResequencingResults::ResizeForceCalls(), affxchp::CResequencingResults::ResizeOrigCalls(), affxchp::CResequencingResults::ResizeScores(), affymetrix_calvin_io::_CHPReseqEntry::score, SetAlgName(), affxchpwriter::CCHPFileWriter::SetAlgorithmVersion(), affxchp::CUniversalProbeSetResults::SetBackground(), affxchp::CResequencingResults::SetCalledBase(), affxchpwriter::CCHPFileWriter::SetExpressionEntry(), affxchp::CResequencingResults::SetForceCall(), affxchpwriter::CCHPFileWriter::SetMappingEntry(), affxchp::CResequencingResults::SetOrigCall(), affxchpwriter::CCHPFileWriter::SetParentCelFileName(), affxchpwriter::CCHPFileWriter::SetProgID(), affxchpwriter::CCHPFileWriter::SetResequencingResults(), affxchp::CResequencingResults::SetScore(), affxchpwriter::CCHPFileWriter::SetUniversalEntry(), affxchp::CExpressionProbeSetResults::Signal, affxchp::CExpressionProbeSetResults::SignalLogRatio, affxchp::CExpressionProbeSetResults::SignalLogRatioHigh, affxchp::CExpressionProbeSetResults::SignalLogRatioLow, and affymetrix_calvin_parameter::ParameterNameValueType::ToString().
Referenced by affymetrix_chp_converter::CHPFileConvertToXDA::ConvertCalvinFile().
void CHPConversionUtilities::SetAlgName (affxchpwriter::CCHPFileWriter & outFile, std::string algName) [static]
Sets the algorithm name in the CCHPFileWriter object. It ensures that the algorithm name value is appropriate before setting it.
Parameters:
outFile The GCOS CHP file object.
algName The algorithm name.
Definition at line 204 of file CHPConversionUtilities.cpp.
References affxchp::CCHPFileHeader::GetAssayType(), affxchp::CCHPFileData::GetHeader(), affxchpwriter::CCHPFileWriter::SetAlgorithmName(), and affxchp::CCHPFileHeader::SetAssayType().
Referenced by Copy().
The documentation for this class was generated from the following files:
calvin_files/converters/chp/src/CHPConversionUtilities.h
calvin_files/converters/chp/src/CHPConversionUtilities.cpp