Affymetrix Power Tools: IntensityReader Class Reference
IntensityReader Class Reference
Abstract base class for a class that read files and fills in memory representation and chip stream objects that need initialization.
#include <IntensityReader.h>