Affymetrix Power Tools: SocketUtil Class Reference
SocketUtil Class Reference
Class with static utility functions for working with Sockets.
#include <SocketUtil.h>
Public Member Functions
virtual int sendAll (int socket, const char *buf, int toSend, int &sent)
Send a message over multiple socket send calls as necessary.
virtual void parseMsgFromBuffer (std::string &buffer, std::vector< std::string > &messages)
Tokenize the buffer into distinct messages.
virtual void checkForMsgs (std::vector< std::string > &messages, int &socket)
Try to read new messages from socket.
virtual void sendMsg (const std::string &msg, int &socket)
Write char * messages into a socket.
Protected Attributes
std::string m_Buffer
Data coming over socket, including any partial messages.
Detailed Description
Class with static utility functions for working with Sockets.
Definition at line 43 of file SocketUtil.h.
Member Function Documentation
void SocketUtil::checkForMsgs (std::vector< std::string > & messages, int & socket) [virtual]
Try to read new messages from socket.
Parameters:
messages - Vector to fill with char * messages from socket.
socket - socket to read messages from. Set to -1 if disconnected.
Definition at line 61 of file SocketUtil.cpp.
References APT_ERR_ABORT, m_Buffer, Verbose::out(), parseMsgFromBuffer(), and ToStr().
void SocketUtil::parseMsgFromBuffer (std::string & buffer, std::vector< std::string > & messages) [virtual]
Tokenize the buffer into distinct messages.
Parameters:
buffer - String to break into individual messages
messages - Vector of messages to fill in
Definition at line 38 of file SocketUtil.cpp.
References APT_ERR_ASSERT, and Convert::toInt().
Referenced by checkForMsgs().
int SocketUtil::sendAll (int socket, const char * buf, int toSend, int & sent) [virtual]
Send a message over multiple socket send calls as necessary.
Parameters:
socket - Socket to write to
buf - Buffer to send over socket
toSend - How long is buffer
sent - Number characters actually sent
Returns:
Definition at line 95 of file SocketUtil.cpp.
Referenced by sendMsg().
void SocketUtil::sendMsg (const std::string & msg, int & socket) [virtual]
Write char * messages into a socket.
Parameters:
msg - Message to write to the socket.
socket - Socket that could be written to.
Definition at line 117 of file SocketUtil.cpp.
References APT_ERR_ABORT, sendAll(), and ToStr().
The documentation for this class was generated from the following files:
util/SocketUtil.h
util/SocketUtil.cpp