Affymetrix Power Tools: DmetEngine Class Reference
DmetEngine Class Reference
Class to run the DMET analysis.
#include <DmetEngine.h>