Affymetrix Power Tools: CNLog2RatioData Class Reference
CNLog2RatioData Class Reference
A class to the log2 ratio data as used by the log2 ratio engine.
#include <CNLog2RatioData.h>
Public Member Functions
CNLog2RatioData ()
Constructor.
virtual ~CNLog2RatioData ()
Destructor.
void clear ()
Release the memory associated with the object.
void clearProbeSets ()
void setLog2RatioEngine (bool b)
void setEngine (BaseEngine *pEngine)
CNExperimentArray * getExperiments ()
void setExperiments (CNExperimentArray &v)
CNProbeSetArray * getProbeSets ()
CNProbeSetArray * getProbeSetsAlternateSort ()
AffxMultiDimensionalArray
< float > * getAAlleleEstimates ()
AffxMultiDimensionalArray
< float > * getBAlleleEstimates ()
AffxMultiDimensionalArray< char > * getGenotypeCalls ()
AffxMultiDimensionalArray
< float > * getGenotypeConfidences ()
AffxMultiDimensionalArray
< float > & getV1 ()
void loadAnnotation (bool bNewProbeSets)
bool loadModelFile (const AffxString &strFileName)
Load the model file and set up the Probe Set array with the pre-calculated median values from the log2 ratio model.
bool writeModelFile (const AffxString &strFileName)
Write the model file in text format.
void loadCyto2ModelFile (const AffxString &strFileName)
Load the model file and set up the Probe Set array with the pre-calculated median values from the log2 ratio model.
void writeCyto2ModelFile (const AffxString &strFileName)
Write the model file in text format.
bool loadSnpReferenceFile (const AffxString &strFileName)
Load the SNP reference file and set up the Probe Set array with the pre-calculated median values from the log2 ratio model.
void loadGenotypeReport (const AffxString &strFileName)
Load the QC metric from the genotype report file.
void dumpGenotypeReport (const AffxString &strFileName)
Dump the QC metrics into the copynumber report file.
void dumpCyto2Report (const AffxString &strFileName)
Dump the QC metrics into the copynumber report file.
int loadExperiments (const AffxString &strFileName)
Load the allele summary table file and set up the experiment array with experiment name.
void loadQCMetrics (const AffxString &strFileName)
Load the QC metrics from the report file.
bool loadAlleleEstimatesByProbeSet (const AffxString &strFileName, int iProbeSetIndex, int iProbeSetsToProcess)
Load the allele summary table file and set up the A Allele signal matrix and the B Allele signal matrix.
bool loadAlleleEstimatesByProbeSetHdf5 (const AffxString &strFileName, int iProbeSetIndex, int iProbeSetsToProcess)
Load the allele summary table file and set up the A Allele signal matrix and the B Allele signal matrix.
bool loadAlleleEstimatesByExperiment (const AffxString &strFileName, int iExperimentIndex, int iExperimentsToProcess)
Load the allele summary table file and set up the A Allele signal matrix and the B Allele signal matrix.
bool loadAlleleEstimatesByExperimentHdf5 (const AffxString &strFileName, int iExperimentIndex, int iExperimentsToProcess)
bool loadGenotypeCallsByProbeSet (const AffxString &strCallsFileName, int iProbeSetIndex, int iProbeSetsToProcess)
Load the genotype call table file and set up the genotype call matrix.
bool loadGenotypeCallsByProbeSetHdf5 (const AffxString &strFileName, int iProbeSetIndex, int iProbeSetsToProcess)
Load the genotype call table file and set up the genotype call matrix.
bool loadGenotypeCallsByExperiment (const AffxString &strCallsFileName, int iExperimentIndex, int iExperimentsToProcess)
Load the genotype call table file and set up the genotype call matrix.
bool loadGenotypeCallsByExperimentHdf5 (const AffxString &strFileName, int iExperimentIndex, int iExperimentsToProcess)
Load the genotype call table file and set up the genotype call matrix.
bool loadGenotypeConfidencesByExperiment (const AffxString &strFileName, int iExperimentIndex, int iExperimentsToProcess)
Load the genotype confidence table file and set up the genotype confidence matrix.
bool loadGenotypeConfidencesByExperimentHdf5 (const AffxString &strFileName, int iExperimentIndex, int iExperimentsToProcess)
Load the genotype confidence table file and set up the genotype confidence matrix.
bool loadGenderOverrideFile (const AffxString &strFileName)
Load externally computed experiment genders.
void calculateMedianSignal (int iProbeSetIndex, int iProbeSetsToProcess)
Calculate the median singal for the log2 ratio model.
void calculateMedianSignalsPerGenotype (int iProbeSetIndex, int iProbeSetsToProcess)
Calculate the median singals for the log2 ratio model.
void calculateXYMedianSignal (int iProbeSetIndex, int iProbeSetsToProcess)
Calculate the median singals for the log2 ratio model.
void loadProbeSets ()
Detailed Description
A class to the log2 ratio data as used by the log2 ratio engine.
Definition at line 45 of file CNLog2RatioData.h.
Member Function Documentation
void CNLog2RatioData::calculateMedianSignal (int iProbeSetIndex, int iProbeSetsToProcess)
Calculate the median singal for the log2 ratio model.
The data is processed by probes set meaning the all the experiment data is processed for a subset of the probe sets. Note that the median signal is A + B.
Parameters:
int - The probe set index to start from.
int - The number of probe sets to process each time this function is called.
Definition at line 1824 of file CNLog2RatioData.cpp.
References Verbose::out(), and roundDouble().
Referenced by CNReferenceEngine::processData().
void CNLog2RatioData::calculateMedianSignalsPerGenotype (int iProbeSetIndex, int iProbeSetsToProcess)
Calculate the median singals for the log2 ratio model.
The data is processed by probes set meaning the all the experiment data is processed for a subset of the probe sets. Note that the median signals broken out by genotype is A - B.
Parameters:
int - The probe set index to start from.
int - The number of probe sets to process each time this function is called.
Definition at line 1846 of file CNLog2RatioData.cpp.
References Options::getOptInt(), Verbose::out(), and roundDouble().
Referenced by CNReferenceEngine::processData().
void CNLog2RatioData::calculateXYMedianSignal (int iProbeSetIndex, int iProbeSetsToProcess)
Calculate the median singals for the log2 ratio model.
The data is processed by probes set meaning the all the experiment data is processed for a subset of the probe sets. Note that the median signal is A + B. The hasXX and hasY is set in the calculateXY function.
Parameters:
int - The probe set index to start from.
int - The number of probe sets to process each time this function is called.
Definition at line 1886 of file CNLog2RatioData.cpp.
References Verbose::out(), and roundDouble().
Referenced by CNReferenceEngine::processData().
void CNLog2RatioData::dumpCyto2Report (const AffxString & strFileName)
Dump the QC metrics into the copynumber report file.
Parameters:
const AffxString& - The name of the file to dump to
Definition at line 845 of file CNLog2RatioData.cpp.
References Fs::basename(), affx::TsvFile::cidx2cname(), affx::TsvFile::clear(), affxutil::Guid::GenerateNewGuid(), affx::TsvFile::get(), affx::TsvFile::getColumnCount(), getDouble(), getInt(), Options::getOpt(), affx::TsvFile::headersBegin(), Fs::join(), affx::TsvFile::m_optAutoTrim, affx::TsvFile::nextHeaderPtr(), affx::TsvFile::nextLevel(), and affx::TsvFile::open().
void CNLog2RatioData::dumpGenotypeReport (const AffxString & strFileName)
Dump the QC metrics into the copynumber report file.
Parameters:
const AffxString& - The name of the file to dump to
Definition at line 700 of file CNLog2RatioData.cpp.
References Fs::basename(), affx::TsvFile::cidx2cname(), affx::TsvFile::clear(), affxutil::Guid::GenerateNewGuid(), affx::TsvFile::get(), affx::TsvFile::getColumnCount(), getDouble(), getInt(), Options::getOpt(), affx::TsvFile::headersBegin(), Fs::join(), affx::TsvFile::m_optAutoTrim, affx::TsvFile::nextHeaderPtr(), affx::TsvFile::nextLevel(), and affx::TsvFile::open().
Referenced by CNLog2RatioEngine::processData().
bool CNLog2RatioData::loadAlleleEstimatesByExperiment (const AffxString & strFileName, int iExperimentIndex, int iExperimentsToProcess)
Load the allele summary table file and set up the A Allele signal matrix and the B Allele signal matrix.
The data is load by experiment meaning the all the probe set data is loaded for a subset of the experiments.
Parameters:
const AffxString& - The name of the file to load.
int - The experiment index to start from.
int - The number of exeriments to process each time this function is called.
Returns:
bool - true if successful
Definition at line 1185 of file CNLog2RatioData.cpp.
References affx::TsvFile::clear(), affx::TsvFile::get(), affx::TsvFile::getColumnCount(), Options::getOptBool(), affx::TsvFile::m_optAutoTrim, Max, affx::TsvFile::nextLevel(), affx::TsvFile::openTable(), Verbose::out(), and Verbose::progressStep().
Referenced by CNReferenceEngine::processData(), and CNLog2RatioEngine::processData().
bool CNLog2RatioData::loadAlleleEstimatesByProbeSet (const AffxString & strFileName, int iProbeSetIndex, int iProbeSetsToProcess)
Load the allele summary table file and set up the A Allele signal matrix and the B Allele signal matrix.
The data is load by Probe set meaning the all the experiment data is loaded for a subset of the probe sets.
Parameters:
const AffxString& - The name of the file to load.
int - The probe set index to start from.
int - The number of probe sets to process each time this function is called.
Returns:
bool - true if successful
Definition at line 982 of file CNLog2RatioData.cpp.
References affx::TsvFile::clear(), affx::TsvFile::get(), affx::TsvFile::getColumnCount(), Options::getOptBool(), loadAlleleEstimatesByProbeSetHdf5(), affx::TsvFile::m_optAutoTrim, Max, affx::TsvFile::nextLevel(), affx::TsvFile::openTable(), and Verbose::progressStep().
Referenced by CNReferenceEngine::processData().
bool CNLog2RatioData::loadAlleleEstimatesByProbeSetHdf5 (const AffxString & strFileName, int iProbeSetIndex, int iProbeSetsToProcess)
Load the allele summary table file and set up the A Allele signal matrix and the B Allele signal matrix.
The data is load by Probe set meaning the all the experiment data is loaded for a subset of the probe sets.
Parameters:
const AffxString& - The name of the file to load.
int - The probe set index to start from.
int - The number of probe sets to process each time this function is called.
Returns:
bool - true if successful
Definition at line 1072 of file CNLog2RatioData.cpp.
References Options::getOpt(), Options::getOptBool(), Max, and Verbose::progressStep().
Referenced by loadAlleleEstimatesByProbeSet().
void CNLog2RatioData::loadCyto2ModelFile (const AffxString & strFileName)
Load the model file and set up the Probe Set array with the pre-calculated median values from the log2 ratio model.
Parameters:
const AffxString& - The name of the file to load.
Returns:
bool - true if successful
Definition at line 325 of file CNLog2RatioData.cpp.
References Verbose::out().
int CNLog2RatioData::loadExperiments (const AffxString & strFileName)
Load the allele summary table file and set up the experiment array with experiment name.
Parameters:
const AffxString& - The name of the file to load.
Returns:
int - The number of experiments loaded
Definition at line 438 of file CNLog2RatioData.cpp.
References affx::TsvFile::clear(), affx::TsvFile::get(), affx::TsvFile::getColumnCount(), Options::getOpt(), affx::TsvFile::m_optAutoTrim, affx::TsvFile::nextLevel(), and affx::TsvFile::openTable().
bool CNLog2RatioData::loadGenderOverrideFile (const AffxString & strFileName)
Load externally computed experiment genders.
Parameters:
const AffxString& - The name of the file to load from
Definition at line 515 of file CNLog2RatioData.cpp.
References Err::errAbort(), affx::Female, affx::TsvFile::get(), Options::getOpt(), affx::TsvFile::m_optAutoTrim, affx::Male, affx::TsvFile::nextLevel(), affx::TsvFile::open(), and Verbose::out().
bool CNLog2RatioData::loadGenotypeCallsByExperiment (const AffxString & strFileName, int iExperimentIndex, int iExperimentsToProcess)
Load the genotype call table file and set up the genotype call matrix.
The data is load by experiment meaning the all the probe set data is loaded for a subset of the experiments.
Parameters:
const AffxString& - The name of the file to load.
int - The experiment index to start from.
int - The number of exeriments to process each time this function is called.
Returns:
bool - true if successful
Definition at line 1533 of file CNLog2RatioData.cpp.
References Fs::basename(), affx::TsvFile::clear(), affx::TsvFile::get(), affx::TsvFile::getColumnCount(), loadGenotypeCallsByExperimentHdf5(), affx::TsvFile::m_optAutoTrim, Max, affx::TsvFile::nextLevel(), affx::TsvFile::openTable(), and Verbose::progressStep().
Referenced by CNLog2RatioEngine::processData().
bool CNLog2RatioData::loadGenotypeCallsByExperimentHdf5 (const AffxString & strFileName, int iExperimentIndex, int iExperimentsToProcess)
Load the genotype call table file and set up the genotype call matrix.
The data is load by experiment meaning the all the probe set data is loaded for a subset of the experiments.
Parameters:
const AffxString& - The name of the file to load.
int - The experiment index to start from.
int - The number of exeriments to process each time this function is called.
Returns:
bool - true if successful
Definition at line 1600 of file CNLog2RatioData.cpp.
References affx::File5_Tsv::getColumnPtr(), Options::getOpt(), Max, and Verbose::progressStep().
Referenced by loadGenotypeCallsByExperiment().
bool CNLog2RatioData::loadGenotypeCallsByProbeSet (const AffxString & strFileName, int iProbeSetIndex, int iProbeSetsToProcess)
Load the genotype call table file and set up the genotype call matrix.
The data is load by Probe set meaning the all the experiment data is loaded for a subset of the probe sets.
Parameters:
const AffxString& - The name of the file to load.
int - The probe set index to start from.
int - The number of probe sets to process each time this function is called.
Returns:
bool - true if successful
Definition at line 1380 of file CNLog2RatioData.cpp.
References Fs::basename(), affx::TsvFile::clear(), affx::TsvFile::get(), affx::TsvFile::getColumnCount(), loadGenotypeCallsByProbeSetHdf5(), affx::TsvFile::m_optAutoTrim, Max, affx::TsvFile::nextLevel(), affx::TsvFile::openTable(), and Verbose::progressStep().
Referenced by CNReferenceEngine::processData().
bool CNLog2RatioData::loadGenotypeCallsByProbeSetHdf5 (const AffxString & strFileName, int iProbeSetIndex, int iProbeSetsToProcess)
Load the genotype call table file and set up the genotype call matrix.
The data is load by Probe set meaning the all the experiment data is loaded for a subset of the probe sets.
Parameters:
const AffxString& - The name of the file to load.
int - The probe set index to start from.
int - The number of probe sets to process each time this function is called.
Returns:
bool - true if successful
Definition at line 1448 of file CNLog2RatioData.cpp.
References affx::File5_Tsv::getColumnPtr(), Options::getOpt(), Max, and Verbose::progressStep().
Referenced by loadGenotypeCallsByProbeSet().
bool CNLog2RatioData::loadGenotypeConfidencesByExperiment (const AffxString & strFileName, int iExperimentIndex, int iExperimentsToProcess)
Load the genotype confidence table file and set up the genotype confidence matrix.
The data is load by experiment meaning the all the probe set data is loaded for a subset of the experiments.
Parameters:
const AffxString& - The name of the file to load.
int - The experiment index to start from.
int - The number of exeriments to process each time this function is called.
Returns:
bool - true if successful
Definition at line 1682 of file CNLog2RatioData.cpp.
References Fs::basename(), affx::TsvFile::clear(), affx::TsvFile::get(), affx::TsvFile::getColumnCount(), loadGenotypeConfidencesByExperimentHdf5(), affx::TsvFile::m_optAutoTrim, Max, affx::TsvFile::nextLevel(), affx::TsvFile::openTable(), and Verbose::progressStep().
Referenced by CNLog2RatioEngine::processData().
bool CNLog2RatioData::loadGenotypeConfidencesByExperimentHdf5 (const AffxString & strFileName, int iExperimentIndex, int iExperimentsToProcess)
Load the genotype confidence table file and set up the genotype confidence matrix.
The data is load by experiment meaning the all the probe set data is loaded for a subset of the experiments.
Parameters:
const AffxString& - The name of the file to load.
int - The experiment index to start from.
int - The number of exeriments to process each time this function is called.
Returns:
bool - true if successful
Definition at line 1743 of file CNLog2RatioData.cpp.
References affx::File5_Tsv::getColumnPtr(), Options::getOpt(), Max, and Verbose::progressStep().
Referenced by loadGenotypeConfidencesByExperiment().
void CNLog2RatioData::loadGenotypeReport (const AffxString & strFileName)
Load the QC metric from the genotype report file.
Parameters:
const AffxString& - The name of the file to load from
Definition at line 635 of file CNLog2RatioData.cpp.
References Fs::basename(), affx::TsvFile::clear(), affx::TsvFile::cname2cidx(), affx::TsvFile::get(), getInt(), Options::getOptBool(), affx::TsvFile::m_optAutoTrim, affx::TsvFile::nextLevel(), affx::TsvFile::open(), Verbose::out(), CNExperiment::setRawIntensityRatioGenderFromString(), and affx::TSV_OK.
Referenced by CNReferenceEngine::processData(), and CNLog2RatioEngine::processData().
bool CNLog2RatioData::loadModelFile (const AffxString & strFileName)
Load the model file and set up the Probe Set array with the pre-calculated median values from the log2 ratio model.
Parameters:
const AffxString& - The name of the file to load.
Returns:
bool - true if successful
Todo:
AW: should this be "state" not "option"? Do we need to handle both for compatability reasons?
Todo:
AW: should this be "state" not "option"? Do we need to handle both for compatability reasons?
Definition at line 140 of file CNLog2RatioData.cpp.
References Fs::basename(), affx::TsvFile::cidx2cname(), affx::TsvFile::clear(), affx::TsvFile::get(), affx::TsvFile::getColumnCount(), affx::TsvFile::getLineCountInFile(), affx::TsvFile::headersBegin(), affx::TsvFile::headersNext(), affx::TsvFile::m_optAutoTrim, Max, affx::File5_Group::name_exists(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), Verbose::out(), Verbose::progressStep(), CovariateParams::restoreCovariateParams(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), Options::setOpt(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueAscii().
void CNLog2RatioData::loadQCMetrics (const AffxString & strFileName)
Load the QC metrics from the report file.
Parameters:
const AffxString& - The name of the file to load from
Definition at line 600 of file CNLog2RatioData.cpp.
References Fs::basename(), affx::TsvFile::clear(), affx::TsvFile::get(), affx::TsvFile::getColumnCount(), affx::TsvFile::m_optAutoTrim, affx::TsvFile::nextLevel(), and affx::TsvFile::open().
bool CNLog2RatioData::loadSnpReferenceFile (const AffxString & strFileName)
Load the SNP reference file and set up the Probe Set array with the pre-calculated median values from the log2 ratio model.
Parameters:
const AffxString& - The name of the file to load.
Returns:
bool - true if successful
Definition at line 370 of file CNLog2RatioData.cpp.
References Verbose::out().
void CNLog2RatioData::writeCyto2ModelFile (const AffxString & strFileName)
Write the model file in text format.
All the median signals asssociated with the probe sets are written out. Values are rounded to insure that the stored values will match the calculated values when using the same input.
Parameters:
const AffxString& - The file name to write to.
Returns:
bool - true if successful
Definition at line 2134 of file CNLog2RatioData.cpp.
References Fs::dirname(), affxutil::Guid::GenerateNewGuid(), Options::getOpt(), Options::getOptVector(), Max, Fs::mkdirPath(), Verbose::out(), and Verbose::progressStep().
bool CNLog2RatioData::writeModelFile (const AffxString & strFileName)
Write the model file in text format.
All the median signals asssociated with the probe sets are written out. Values are rounded to insure that the stored values will match the calculated values when using the same input.
Parameters:
const AffxString& - The file name to write to.
Returns:
bool - true if successful
Definition at line 1930 of file CNLog2RatioData.cpp.
References affx::TsvFile::addHeader(), affx::TsvFile::clear(), affx::TsvFile::close(), affx::TsvFile::defineColumn(), Fs::dirname(), affxutil::Guid::GenerateNewGuid(), getDouble(), Options::getOpt(), Options::getOptBool(), Options::getOptVector(), Options::isOptDefined(), Max, Fs::mkdirPath(), Verbose::out(), Verbose::progressStep(), affx::TsvFile::writeLevel(), and affx::TsvFile::writeTsv_v1().
The documentation for this class was generated from the following files:
copynumber/CNLog2RatioData.h
copynumber/CNLog2RatioData.cpp