Affymetrix Power Tools: affymetrix_calvin_io::DataGroupHeaderUpdater Class Reference
affymetrix_calvin_io::DataGroupHeaderUpdater Class Reference
#include <DataGroupHeaderUpdater.h>
Public Member Functions
DataGroupHeaderUpdater (std::ofstream &fileStream, DataGroupHeader &hdr)
~DataGroupHeaderUpdater ()
void UpdateNextDataGroupOffset (u_int32_t offset)
void UpdateLeadDataSetOffset (u_int32_t offset)
void UpdateDataSetCount (u_int32_t count)
void AppendDataSetHeader (DataSetHeader &setHdr)
void ReplaceDataSetHeader (std::wstring targetName, DataSetHeader &newHdr)
Detailed Description
This class updates the data set header of an existing file with new information.
Definition at line 41 of file DataGroupHeaderUpdater.h.
Constructor & Destructor Documentation
DataGroupHeaderUpdater::DataGroupHeaderUpdater (std::ofstream & fileStream, DataGroupHeader & hdr)
Constructor
Definition at line 36 of file DataGroupHeaderUpdater.cpp.
DataGroupHeaderUpdater::~DataGroupHeaderUpdater ()
Destructor
Definition at line 45 of file DataGroupHeaderUpdater.cpp.
Member Function Documentation
void DataGroupHeaderUpdater::AppendDataSetHeader (DataSetHeader & setHdr)
Append a new data set in this data group.
Parameters:
setHdr The new data set that will be appended.
Definition at line 94 of file DataGroupHeaderUpdater.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), affymetrix_calvin_io::DataSetHeader::SetDataStartFilePos(), affymetrix_calvin_io::DataSetHeader::SetHeaderStartFilePos(), and affymetrix_calvin_io::DataSetHeader::SetNextSetFilePos().
void DataGroupHeaderUpdater::ReplaceDataSetHeader (std::wstring targetName, DataSetHeader & newHdr)
Replace a data set in this data group with a new one.
Parameters:
targetName The name of the data set to be replaced.
newHdr The new data set that will be written into the file.
Definition at line 122 of file DataGroupHeaderUpdater.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetDataSetIterators(), affymetrix_calvin_io::DataGroupHeader::ReplaceDataSetHdr(), affymetrix_calvin_io::DataSetHeader::SetDataStartFilePos(), affymetrix_calvin_io::DataSetHeader::SetHeaderStartFilePos(), and affymetrix_calvin_io::DataSetHeader::SetNextSetFilePos().
The documentation for this class was generated from the following files:
calvin_files/writers/src/DataGroupHeaderUpdater.h
calvin_files/writers/src/DataGroupHeaderUpdater.cpp