Affymetrix Power Tools: CRawQWorkflow Class Reference
CRawQWorkflow Class Reference
#include <RawQWorkflow.h>
Public Types
enum RawQError { NoError, UnableToReadCELFile, UnableToReadCDFFile, NotExpressionArray }
Public Member Functions
CRawQWorkflow ()
~CRawQWorkflow ()
void SetDefaults ()
void SetVerticalZones (int v)
void SetHorizontalZones (int h)
void SetPercentBG (float p)
int GetVerticalZones () const
int GetHorizontalZones () const
float GetPercentBG () const
void Clear ()
RawQError ComputeRawQ (const char *celFile, const char *libPath)
float GetRawQ ()
Protected Member Functions
bool ReadCELFile (const char *celFile)
bool LoadCDFFile (const char *libPath)
bool IsExpressionArray ()
Protected Attributes
std::string m_ArrayType
affymetrix_fusion_io::FusionCDFData m_Cdf
affymetrix_fusion_io::FusionCELData m_Cel
float m_RawQ
CRawQ m_RawQAlg
Detailed Description
This class provides interfaces to compute the RawQ value from a CEL file.
Definition at line 38 of file RawQWorkflow.h.
Member Enumeration Documentation
enum CRawQWorkflow::RawQError
The error codes for the RawQ function.
Definition at line 42 of file RawQWorkflow.h.
Constructor & Destructor Documentation
CRawQWorkflow::CRawQWorkflow ()
Constructor
Definition at line 32 of file RawQWorkflow.cpp.
CRawQWorkflow::~CRawQWorkflow ()
Destructor
Definition at line 38 of file RawQWorkflow.cpp.
References Clear().
Member Function Documentation
void CRawQWorkflow::Clear (void)
Clear memory associated with the class.
Definition at line 45 of file RawQWorkflow.cpp.
References affymetrix_fusion_io::FusionCELData::Clear(), affymetrix_fusion_io::FusionCDFData::Close(), m_ArrayType, m_Cdf, and m_Cel.
Referenced by ~CRawQWorkflow().
CRawQWorkflow::RawQError CRawQWorkflow::ComputeRawQ (const char * celFile, const char * libPath)
Calculates the RawQ value.
Parameters:
celFile The full path of the CEL file.
libPath The path to where the CDF files live.
Returns:
The status of the calculation.
Definition at line 122 of file RawQWorkflow.cpp.
References CRawQ::ComputeRawQ(), IsExpressionArray(), LoadCDFFile(), m_Cdf, m_Cel, m_RawQ, m_RawQAlg, and ReadCELFile().
int CRawQWorkflow::GetHorizontalZones () const [inline]
Gets the number of horizontal zones to use.
Returns:
The number of horizontal zones for the background calculation.
Definition at line 115 of file RawQWorkflow.h.
References CRawQ::GetHorizontalZones(), and m_RawQAlg.
float CRawQWorkflow::GetPercentBG () const [inline]
Gets the percentage of background probes to use in each zone.
Returns:
The percent of probes to use for the background calculation.
Definition at line 120 of file RawQWorkflow.h.
References CRawQ::GetPercentBG(), and m_RawQAlg.
float CRawQWorkflow::GetRawQ () [inline]
Gets the RawQ value.
Returns:
The RawQ value.
Definition at line 135 of file RawQWorkflow.h.
References m_RawQ.
int CRawQWorkflow::GetVerticalZones () const [inline]
Gets the number of vertical zones to use.
Returns:
The number of vertical zones for the background calculation.
Definition at line 110 of file RawQWorkflow.h.
References CRawQ::GetVerticalZones(), and m_RawQAlg.
bool CRawQWorkflow::IsExpressionArray () [protected]
Checks that the files are of the right tile type.
Returns:
True if the array type is an expression array type.
Definition at line 105 of file RawQWorkflow.cpp.
References affymetrix_fusion_io::FusionCDFData::GetHeader(), affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets(), affymetrix_fusion_io::FusionCDFData::GetProbeSetType(), and m_Cdf.
Referenced by ComputeRawQ().
bool CRawQWorkflow::LoadCDFFile (const char * libPath) [protected]
Reads the CDF file into memory.
Parameters:
libPath The path to the CDF files.
Returns:
True if sucessful.
Definition at line 78 of file RawQWorkflow.cpp.
References affymetrix_fusion_io::FusionCDFData::Exists(), affymetrix_fusion_io::FusionCELData::GetChipType(), Fs::join(), m_ArrayType, m_Cdf, m_Cel, affymetrix_fusion_io::FusionCDFData::Read(), and affymetrix_fusion_io::FusionCDFData::SetFileName().
Referenced by ComputeRawQ().
bool CRawQWorkflow::ReadCELFile (const char * celFile) [protected]
Reads the CEL file into memory.
Parameters:
celFile The name of the CEL file.
Returns:
True if sucessful.
Definition at line 54 of file RawQWorkflow.cpp.
References affymetrix_fusion_io::FusionCELData::Exists(), m_Cel, affymetrix_fusion_io::FusionCELData::Read(), and affymetrix_fusion_io::FusionCELData::SetFileName().
Referenced by ComputeRawQ().
void CRawQWorkflow::SetDefaults () [inline]
Resets the default parameters.
Definition at line 90 of file RawQWorkflow.h.
References m_RawQAlg, and CRawQ::SetDefaults().
void CRawQWorkflow::SetHorizontalZones (int h) [inline]
Sets the number of horizontal zones to use.
Parameters:
h The number of horizontal zones for the background calculation.
Definition at line 100 of file RawQWorkflow.h.
References m_RawQAlg, and CRawQ::SetHorizontalZones().
void CRawQWorkflow::SetPercentBG (float p) [inline]
Sets the percentage of background probes to use in each zone.
Parameters:
p The percent of probes to use for the background calculation.
Definition at line 105 of file RawQWorkflow.h.
References m_RawQAlg, and CRawQ::SetPercentBG().
void CRawQWorkflow::SetVerticalZones (int v) [inline]
Sets the number of vertical zones to use.
Parameters:
v The number of vertical zones for the background calculation.
Definition at line 95 of file RawQWorkflow.h.
References m_RawQAlg, and CRawQ::SetVerticalZones().
Member Data Documentation
std::string CRawQWorkflow::m_ArrayType [protected]
The probe array type.
Definition at line 51 of file RawQWorkflow.h.
Referenced by Clear(), and LoadCDFFile().
affymetrix_fusion_io::FusionCDFData CRawQWorkflow::m_Cdf [protected]
The CDF file object.
Definition at line 54 of file RawQWorkflow.h.
Referenced by Clear(), ComputeRawQ(), IsExpressionArray(), and LoadCDFFile().
affymetrix_fusion_io::FusionCELData CRawQWorkflow::m_Cel [protected]
The CEL file object.
Definition at line 57 of file RawQWorkflow.h.
Referenced by Clear(), ComputeRawQ(), LoadCDFFile(), and ReadCELFile().
float CRawQWorkflow::m_RawQ [protected]
The computed RawQ value.
Definition at line 60 of file RawQWorkflow.h.
Referenced by ComputeRawQ(), and GetRawQ().
CRawQ CRawQWorkflow::m_RawQAlg [protected]
The RawQ algorithm interfaces.
Definition at line 63 of file RawQWorkflow.h.
Referenced by ComputeRawQ(), GetHorizontalZones(), GetPercentBG(), GetVerticalZones(), SetDefaults(), SetHorizontalZones(), SetPercentBG(), and SetVerticalZones().
The documentation for this class was generated from the following files:
rawq/src/RawQWorkflow.h
rawq/src/RawQWorkflow.cpp