Affymetrix Power Tools: affx::BgpFile Class Reference
affx::BgpFile Class Reference
To be called a BGP file, the file requires.
#include <BgpFile.h>
Public Member Functions
BgpFile ()
Create the BgpFile object.
~BgpFile ()
Destroy a BgpFile object.
void clear ()
Clears all the member vars.
void makeBgpBindings ()
Make the bindings which define a BGP file.
int open (const std::string &filename)
Open a BGP file ///.
int write (const std::string &filename)
Start the write to a file ///.
int close ()
Close a PGF file ///.
int rewind ()
Rewind back to the start of the BGP data ///.
int next_bgprobe ()
Skip to the next probe ///.
int defineFileBgp (TsvFile *tsv)
Define a tsv file as a BGP file. ///.
int defineFileBgp ()
Define this file as a pgf file ///.
Public Attributes
affx::TsvFile m_tsv
public so people can work with it
int probe_id
int probeset_id_1
int atom_id
int exon_position
int gc_count
int interrogation_position
int probe_length
std::string probe_sequence
int probeset_id_2
std::string probeset_name
std::string type
int x
int y
Detailed Description
To be called a BGP file, the file requires.
Definition at line 41 of file BgpFile.h.
Member Function Documentation
int affx::BgpFile::close ()
Close a PGF file ///.
Returns:
tsv_return_t
Definition at line 177 of file BgpFile.cpp.
References affx::TsvFile::close(), and m_tsv.
Referenced by convertBgpFile(), AnalysisStreamFactory::probeListFromBgpFile(), and setBgpFile().
int affx::BgpFile::defineFileBgp ()
Define this file as a pgf file ///.
Returns:
tsv_return_t
Definition at line 205 of file BgpFile.cpp.
References m_tsv.
int affx::BgpFile::defineFileBgp (TsvFile * tsv)
Define a tsv file as a BGP file. ///.
Parameters:
tsv pointer to tsv to define ///
Returns:
tsv_return_t
Definition at line 196 of file BgpFile.cpp.
References affx::TsvFile::defineFile().
int affx::BgpFile::next_bgprobe ()
Skip to the next probe ///.
Returns:
TSV_LEVEL_LAST when out of probesets
Definition at line 189 of file BgpFile.cpp.
References m_tsv, and affx::TsvFile::nextLevel().
Referenced by convertBgpFile(), AnalysisStreamFactory::probeListFromBgpFile(), and setBgpFile().
int affx::BgpFile::open (const std::string & filename)
Open a BGP file ///.
Parameters:
filename the pathname of the file ///
Returns:
tsv_return_t
Definition at line 164 of file BgpFile.cpp.
References m_tsv, and affx::TsvFile::open().
Referenced by convertBgpFile(), AnalysisStreamFactory::probeListFromBgpFile(), and setBgpFile().
int affx::BgpFile::rewind ()
Rewind back to the start of the BGP data ///.
Returns:
tsv_return_t
Definition at line 183 of file BgpFile.cpp.
References m_tsv, and affx::TsvFile::rewind().
int affx::BgpFile::write (const std::string & filename)
Start the write to a file ///.
Parameters:
filename ///
Returns:
tsv_return_t
Definition at line 171 of file BgpFile.cpp.
References m_tsv, and affx::TsvFile::writeTsv().
The documentation for this class was generated from the following files:
file/TsvFile/BgpFile.h
file/TsvFile/BgpFile.cpp