Affymetrix Power Tools: RowFile Class Reference
RowFile Class Reference
RowFile.
#include <RowFile.h>
Public Types
enum FileLineEnding { UNIX = 0, DOS = 1, MAC = 2, UNKNOWN = 3 }
Line endings are platform specific, this encodes different types we know of.
Public Member Functions
RowFile (char delimChar= '\t', char commentChar= '#', char commentChar2= '%')
Constructor.
~RowFile ()
Destructor.
void open (const std::string &fileName)
Open file fileName or die trying.
void close ()
Close file streams.
bool nextRowExpect (std::vector< std::string > &words, unsigned int expect)
Chop the next row into words and return them in the vector squawk and die if expected number was different from number found.
bool nextCStringRowExpect (std::vector< const char * > &words, unsigned int expect)
Chop the next row into words and return them in the vector squawk and die if expected number was different from number found.
bool nextCStringRow (std::vector< const char * > &words)
Chop the next row into words and return them in the vector.
bool nextRow (std::vector< std::string > &words)
Chop the next row into words and return them in the vector.
void setDelim (char nDelim)
Set the delimiter.
char getDelim ()
Get the delimiter.
void setComment (char nComment)
Set the comment.
char getComment ()
Get the comment.
const std::string * nextLine ()
Pull the next line from the input buffer or die trying.
const std::string * nextRealLine ()
Return the next line that is non-blank and doesn't start with a comment character.
void reuseLine ()
Reuse the same line again.
int getCurrentLineNumber ()
What line number are we reading?
enum FileLineEnding getFileType ()
What type of file is this one?
std::string getFileName ()
What is the name of the rowfile we're reading from?
Static Public Member Functions
static void readHeader (RowFile &rf, std::map< std::string, std::vector< std::string > > &header, std::vector< std::string > &lines)
Fill in a header map with data from the top of the file.
static void writeHeader (std::ostream &out, const std::vector< std::string > &lines)
Write out a header in #key=value form.
static void matrixFromFile (const std::string &fileName, std::vector< std::vector< double > > &matrix, unsigned int skipLines=0, unsigned int skipCols=0)
Read in a matrix from a file.
static void matrixFromFile (const std::string &fileName, std::vector< std::vector< float > > &matrix, unsigned int skipLines=0, unsigned int skipCols=0)
Read in a matrix from a file.
Detailed Description
RowFile.
Class for reading line oriented files and parsing them out into vectors of strings easily.
Definition at line 43 of file RowFile.h.
Member Enumeration Documentation
enum RowFile::FileLineEnding
Line endings are platform specific, this encodes different types we know of.
Definition at line 49 of file RowFile.h.
Constructor & Destructor Documentation
RowFile::RowFile (char delimChar = '\t', char commentChar = '#', char commentChar2 = '%')
Constructor.
Open an object with delimiter and comment characters.
Parameters:
delimChar - word delimiter character.
commentChar - line comment character.
commentChar2 - second line comment character.
Open an object with delimiter and comment characters.
Parameters:
delim - word delimiter character.
comment - line comment character.
Definition at line 49 of file RowFile.cpp.
Member Function Documentation
char RowFile::getComment () [inline]
Get the comment.
Returns:
current comment character.
Definition at line 139 of file RowFile.h.
int RowFile::getCurrentLineNumber () [inline]
What line number are we reading?
Returns:
Line number.
Definition at line 161 of file RowFile.h.
Referenced by TableFile::columnFromRowFile(), and TableFile::open().
char RowFile::getDelim () [inline]
Get the delimiter.
Returns:
current word delimiter.
Definition at line 127 of file RowFile.h.
std::string RowFile::getFileName () [inline]
What is the name of the rowfile we're reading from?
Returns:
name of file being read.
Definition at line 206 of file RowFile.h.
Referenced by TableFile::columnFromRowFile().
enum FileLineEnding RowFile::getFileType () [inline]
What type of file is this one?
Returns:
Type of file that has been determined.
Definition at line 200 of file RowFile.h.
void RowFile::matrixFromFile (const std::string & fileName, std::vector< std::vector< double > > & matrix, unsigned int skipLines = 0, unsigned int skipCols = 0) [static]
Read in a matrix from a file.
Parameters:
fileName - Name of file to read from.
matrix - where to read data into.
skipLines - lines (possibly header?) to skip.
skipCols - number of columns (row names?) to skip.
Definition at line 321 of file RowFile.cpp.
References Err::errAbort(), nextRow(), open(), and Convert::toDouble().
Referenced by Util::matrixDifferences().
void RowFile::matrixFromFile (const std::string & fileName, std::vector< std::vector< float > > & matrix, unsigned int skipLines = 0, unsigned int skipCols = 0) [static]
Read in a matrix from a file.
Parameters:
fileName - Name of file to read from.
matrix - where to read data into.
skipLines - lines (possibly header?) to skip.
skipCols - number of columns (row names?) to skip.
Definition at line 347 of file RowFile.cpp.
References Err::errAbort(), nextRow(), open(), and Convert::toFloat().
bool RowFile::nextCStringRow (std::vector< const char * > & words)
Chop the next row into words and return them in the vector.
char* memory in vector is owned elsewhere and will change after an calls to nextRow or nextLine.
Parameters:
words - vector to fill in with words.
Returns:
bool - false at EOF true otherwise.
Definition at line 198 of file RowFile.cpp.
References FreezArray(), and nextRealLine().
Referenced by nextCStringRowExpect().
bool RowFile::nextCStringRowExpect (std::vector< const char * > & words, unsigned int expect)
Chop the next row into words and return them in the vector squawk and die if expected number was different from number found.
Chop the next row into words and return them in the vector.
char * memory in vector is owned elsewhere and will change after an calls to nextRow or nextLine.
Parameters:
words - vector to fill in with words.
expect - number of words that should be in next row.
Returns:
bool - false at EOF true otherwise.
char* memory in vector is owned elsewhere and will change after an calls to nextRow or nextLine.
Parameters:
words - vector to fill in with words.
Returns:
bool - false at EOF true otherwise.
Definition at line 180 of file RowFile.cpp.
References Err::errAbort(), nextCStringRow(), and ToStr().
const string * RowFile::nextLine ()
Pull the next line from the input buffer or die trying.
Pull the next line from the input m_Buffer or die trying.
Returns:
- Pointer to string representation of current line or NULL at EOF.
Definition at line 94 of file RowFile.cpp.
References Err::errAbort(), ToStr(), and Util::trimString().
Referenced by nextRealLine(), and readHeader().
const string * RowFile::nextRealLine ()
Return the next line that is non-blank and doesn't start with a comment character.
Returns:
- Pointer to string repesentation of current line or NULL at EOF.
Definition at line 130 of file RowFile.cpp.
References nextLine().
Referenced by nextCStringRow(), and nextRow().
bool RowFile::nextRow (std::vector< std::string > & words)
Chop the next row into words and return them in the vector.
Parameters:
words - vector to fill in with words.
Returns:
bool - false at EOF true otherwise.
Definition at line 154 of file RowFile.cpp.
References nextRealLine().
Referenced by TableFile::columnFromFile(), TableFile::columnFromRowFile(), matrixFromFile(), nextRowExpect(), TableFile::open(), and RegressionTest::parseLogFile().
bool RowFile::nextRowExpect (std::vector< std::string > & words, unsigned int expect)
Chop the next row into words and return them in the vector squawk and die if expected number was different from number found.
Parameters:
words - vector to fill in with words.
expect - number of words that should be in next row.
Returns:
bool - false at EOF true otherwise.
Definition at line 254 of file RowFile.cpp.
References Err::errAbort(), nextRow(), and ToStr().
void RowFile::open (const std::string & fileName)
Open file fileName or die trying.
Parameters:
fileName - full path of fileName to be opened.
char * fileName - full path of fileName to be opened.
Definition at line 59 of file RowFile.cpp.
References Err::errAbort(), and FS_QUOTE_PATH.
Referenced by TableFile::columnFromFile(), matrixFromFile(), TableFile::open(), and RegressionTest::parseLogFile().
void RowFile::setComment (char nComment) [inline]
Set the comment.
Parameters:
nComment - new comment character.
Definition at line 133 of file RowFile.h.
void RowFile::setDelim (char nDelim) [inline]
Set the delimiter.
Parameters:
nDelim - new word delimiter.
Definition at line 121 of file RowFile.h.
The documentation for this class was generated from the following files:
util/RowFile.h
util/RowFile.cpp