Affymetrix Power Tools: affx::md5sum Class Reference
affx::md5sum Class Reference
an object oriented interface to generating MD5s. /// provides methods to do strings and files with one call.
#include <md5sum.h>
Public Member Functions
md5sum ()
Creation of md5sum an object ///.
int init ()
Init the starting state of the MD5 operation ///.
int update (void *buff, uint32_t buf_size)
update the MD5 state with a block of data ///
int update (const std::string &str)
update the MD5 state with a string ///
int update (char const *const str)
int update_nbo (int32_t val)
update the MD5 state with a int in network byte order. ///
int update_nbo (uint32_t val)
update the MD5 state with a int in network byte order. ///
int update_nbo (uint16_t val)
update the MD5 state with a int in network byte order. ///
int update_nbo (uint8_t val)
update the MD5 state with a int in network byte order. ///
int update_nbo (const std::vector< int > &vec)
Update the md5 with all the values of the vector ///.
int final (std::string &str)
Conclude the computation of the MD5 and generate the output ///.
int ofString (std::string str, std::string &sum)
Compute the MD5 of a std::string ///.
int ofFile (std::string filename, std::string &sum, const std::string &salt="")
Compute the MD5 of a file ///.
Public Attributes
MD5Context m_context
The basic MD5 context as wrapped by md5sum.
Detailed Description
an object oriented interface to generating MD5s. /// provides methods to do strings and files with one call.
Definition at line 42 of file md5sum.h.
Constructor & Destructor Documentation
affx::md5sum::md5sum ()
Creation of md5sum an object ///.
Returns:
an md5sum
Definition at line 45 of file md5sum.cpp.
References init().
Member Function Documentation
int affx::md5sum::final (std::string & sum)
Conclude the computation of the MD5 and generate the output ///.
Parameters:
sum The hex-encoded MD5 output
Returns:
non-zero on error
Definition at line 173 of file md5sum.cpp.
References init(), m_context, and MD5Final().
Referenced by QuantDabg::setBgProbes(), GcBg::setControlProbes(), GcAdjust::setLayout(), GcAdjust::setParameters(), GcAdjust::setProbes(), SketchQuantNormTran::setSubProbes(), and SketchQuantNormTran::SketchQuantNormTran().
int affx::md5sum::init ()
Init the starting state of the MD5 operation ///.
Returns:
non-zero on error
Definition at line 52 of file md5sum.cpp.
References m_context, and MD5Init().
Referenced by final(), md5sum(), ofFile(), and ofString().
int affx::md5sum::ofFile (std::string filename, std::string & sum, const std::string & salt = "")
Compute the MD5 of a file ///.
Parameters:
filename name of the file to ///
sum ///
Returns:
non-zero on error
Definition at line 212 of file md5sum.cpp.
References init(), and update().
int affx::md5sum::ofString (std::string str, std::string & sum)
Compute the MD5 of a std::string ///.
Parameters:
str string to checksum ///
sum output checksum ///
Returns:
non-zero on error
Definition at line 200 of file md5sum.cpp.
References init(), and update().
int affx::md5sum::update (void * buf, uint32_t buf_size)
update the MD5 state with a block of data ///
Parameters:
buf Pointer to buffer of data ///
buf_size Number of bytes in the buffer ///
Returns:
non-zero on error
Definition at line 63 of file md5sum.cpp.
References m_context, and MD5Update().
Referenced by ofFile(), and ofString().
int affx::md5sum::update (const std::string & str)
update the MD5 state with a string ///
Parameters:
str String to add to the MD5 ///
Returns:
non-zero on error
Definition at line 73 of file md5sum.cpp.
References m_context, and MD5Update().
int affx::md5sum::update_nbo (uint32_t val)
update the MD5 state with a int in network byte order. ///
Parameters:
val Value to update the md5 with. //
Returns:
non-zero on error
Definition at line 98 of file md5sum.cpp.
References m_context, and MD5Update().
int affx::md5sum::update_nbo (const std::vector< int > & vec)
Update the md5 with all the values of the vector ///.
Parameters:
vec vector of ints to add to the checksum. ///
Returns:
Definition at line 128 of file md5sum.cpp.
References update_nbo().
int affx::md5sum::update_nbo (int32_t val)
update the MD5 state with a int in network byte order. ///
Parameters:
val Value to update the md5 with. //
Returns:
non-zero on error
Definition at line 88 of file md5sum.cpp.
References m_context, and MD5Update().
Referenced by QuantDabg::setBgProbes(), GcBg::setControlProbes(), GcAdjust::setLayout(), GcAdjust::setParameters(), GcAdjust::setProbes(), SketchQuantNormTran::setSubProbes(), and update_nbo().
int affx::md5sum::update_nbo (uint16_t val)
update the MD5 state with a int in network byte order. ///
Parameters:
val Value to update the md5 with. //
Returns:
non-zero on error
Definition at line 108 of file md5sum.cpp.
References m_context, and MD5Update().
int affx::md5sum::update_nbo (uint8_t val)
update the MD5 state with a int in network byte order. ///
Parameters:
val Value to update the md5 with. //
Returns:
non-zero on error
Definition at line 118 of file md5sum.cpp.
References m_context, and MD5Update().
The documentation for this class was generated from the following files:
util/md5sum.h
util/md5sum.cpp