Affymetrix Power Tools: QuantSea Class Reference
QuantSea Class Reference
Class for doing probe set quantification using the SEA, or Simplified Expression Analysis, method.
#include <QuantSea.h>