Affymetrix Power Tools: CNAnalysisMethodChipstream Class Reference
CNAnalysisMethodChipstream Class Reference
The Chipstream Analysis Method.
#include <CNAnalysisMethodChipstream.h>