Affymetrix Power Tools: AdapterTypeNormTran Class Reference
AdapterTypeNormTran Class Reference
AdapterTypeNormTran - Class for doing adapter type normalization.
#include <AdapterTypeNormTran.h>