Affymetrix Power Tools: affymetrix_cel_converter::CELFileConvertToASCII Class Reference
affymetrix_cel_converter::CELFileConvertToASCII Class Reference
#include <CELFileConvertToASCII.h>
Public Member Functions
CELFileConvertToASCII ()
~CELFileConvertToASCII ()
CELFileConverterErrorCode ErrorCode () const
bool ConvertCalvinFile (const char *fileName, const char *newFile, CELFileConversionOptions *options=NULL)
bool ConvertXDAFile (const char *fileName, const char *newFile, CELFileConversionOptions *options=NULL)
Detailed Description
This class will convert a CEL file to ASCII format.
Definition at line 34 of file CELFileConvertToASCII.h.
Constructor & Destructor Documentation
CELFileConvertToASCII::CELFileConvertToASCII ()
Constructor
Definition at line 47 of file CELFileConvertToASCII.cpp.
CELFileConvertToASCII::~CELFileConvertToASCII ()
Destructor
Definition at line 63 of file CELFileConvertToASCII.cpp.
Member Function Documentation
bool CELFileConvertToASCII::ConvertCalvinFile (const char * fileName, const char * newFile, CELFileConversionOptions * options = NULL)
Convert the Calvin file to ASCII format.
Parameters:
fileName The full path name of the CEL file.
newFile The name of the new CEL file.
Returns:
True if successful.
Definition at line 105 of file CELFileConvertToASCII.cpp.
References affymetrix_calvin_io::CelFileData::Clear(), affymetrix_cel_converter::CELConversionUtilities::Copy(), affymetrix_calvin_io::CelFileReader::Read(), affxcel::CCELFileData::SetFileFormat(), affxcel::CCELFileData::SetFileName(), affymetrix_calvin_io::CelFileReader::SetFilename(), and affxcel::CCELFileWriter::WriteTextCel().
Referenced by affymetrix_cel_converter::CELFileConverter::ConvertFile().
bool CELFileConvertToASCII::ConvertXDAFile (const char * fileName, const char * newFile, CELFileConversionOptions * options = NULL)
Convert the XDA file to ASCII format.
Parameters:
fileName The full path name of the CEL file.
newFile The name of the new CEL file.
Returns:
True if successful.
Definition at line 71 of file CELFileConvertToASCII.cpp.
References affymetrix_cel_converter::CELConversionUtilities::Copy(), affxcel::CCELFileData::Read(), affxcel::CCELFileData::SetFileFormat(), affxcel::CCELFileData::SetFileName(), and affxcel::CCELFileWriter::WriteTextCel().
Referenced by affymetrix_cel_converter::CELFileConverter::ConvertFile().
CELFileConverterErrorCode affymetrix_cel_converter::CELFileConvertToASCII::ErrorCode () const [inline]
Gets the error code for the conversion process.
Returns:
The error code associated with the last failure.
Definition at line 47 of file CELFileConvertToASCII.h.
Referenced by affymetrix_cel_converter::CELFileConverter::ConvertFile().
The documentation for this class was generated from the following files:
calvin_files/converters/cel/src/CELFileConvertToASCII.h
calvin_files/converters/cel/src/CELFileConvertToASCII.cpp