Affymetrix Power Tools: LineFile Class Reference
LineFile Class Reference
LineFile.
#include <LineFile.h>
Public Types
enum FileLineEnding { UNIX = 0, DOS = 1, MAC = 2, UNKNOWN = 3 }
Line endings are platform specific, this encodes different types we know of.
Public Member Functions
LineFile ()
Constructor.
virtual ~LineFile ()
Destructor closes stream.
std::ifstream & open (const std::string &fileName, bool abortOnError=false)
Platform safe open for read, can be used multiple times with different file names.
void close ()
close the ifstream if needed.
bool getline (std::string &line, bool trim=false)
Platform safe reading of a line, stripping the eol.
enum FileLineEnding getFileType ()
What type of file is this one?
std::string getFileName ()
What is the name of the file we're reading from?
std::ifstream & getStream ()
get the input file stream.
bool is_open ()
bool fail ()
bool eof ()
Detailed Description
LineFile.
Platform safe class for reading lines.
For Test Code ONLY. Chances are you should be using file/TsvFile/TsvFile and not this object. This file is intended for test code in util/ being used by file/TsvFile/TsvFile and other code not using TsvFile.
Definition at line 47 of file LineFile.h.
Member Enumeration Documentation
enum LineFile::FileLineEnding
Line endings are platform specific, this encodes different types we know of.
Definition at line 54 of file LineFile.h.
Constructor & Destructor Documentation
LineFile::~LineFile () [virtual]
Destructor closes stream.
Destructor.
Definition at line 73 of file LineFile.cpp.
Member Function Documentation
void LineFile::close (void)
close the ifstream if needed.
Close file streams.
Returns:
void
Definition at line 109 of file LineFile.cpp.
std::string LineFile::getFileName () [inline]
What is the name of the file we're reading from?
Returns:
name of file being read.
Definition at line 106 of file LineFile.h.
enum FileLineEnding LineFile::getFileType () [inline]
What type of file is this one?
Returns:
Type of file that has been determined.
Definition at line 98 of file LineFile.h.
bool LineFile::getline (std::string & line, bool trim = false)
Platform safe reading of a line, stripping the eol.
LineFile::getline.
File is automatically closed when eof is reached.
Parameters:
line - returned if possible, cleared otherwise.
trim - false by default, true strips trailing spaces.
Returns:
true if line is returned. line will be cleared when false is returned. .
Read the next line if the stream is open. When eof is reached, close the file.
Returns:
- at EOF.
Definition at line 124 of file LineFile.cpp.
References Util::trimString().
Referenced by TextFileCheck::check().
std::ifstream& LineFile::getStream () [inline]
get the input file stream.
Returns:
ifstream reference.
Definition at line 114 of file LineFile.h.
std::ifstream & LineFile::open (const std::string & fileName, bool abortOnError = false)
Platform safe open for read, can be used multiple times with different file names.
Open file fileName or die trying.
Returns:
ifstream in question.
Parameters:
char * fileName - full path of fileName to be opened.
Definition at line 84 of file LineFile.cpp.
References Err::errAbort(), and FS_QUOTE_PATH.
Referenced by TextFileCheck::check().
The documentation for this class was generated from the following files:
util/LineFile.h
util/LineFile.cpp