Affymetrix Power Tools: CNAnalysisMethodCancer Class Reference
CNAnalysisMethodCancer Class Reference
The Cancer Analysis Method.
#include <CNAnalysisMethodCancer.h>