Affymetrix Power Tools: QuantMethod Class Reference
QuantMethod Class Reference
QuantMethod - Interface for computing quantification summaries from PM intensities grouped into probe set groups.
#include <QuantMethod.h>