Affymetrix Power Tools: affymetrix_fusion_io::IFusionCHPHeaderAdapter Class Reference
affymetrix_fusion_io::IFusionCHPHeaderAdapter Class Reference
Header class for the Fusion CHP adapter.
#include <FusionCHPDataAdapterInterface.h>