Affymetrix Power Tools: affymetrix_fusion_io::FusionCHPMultiDataAccessor Class Reference
affymetrix_fusion_io::FusionCHPMultiDataAccessor Class Reference
#include <FusionCHPMultiDataAccessor.h>
Public Member Functions
FusionCHPMultiDataAccessor ()
~FusionCHPMultiDataAccessor ()
bool Initialize (const std::vector< std::string > &chps)
void ExtractData (const std::vector< std::string > &snps, std::vector< std::vector< u_int8_t > > &calls, std::vector< std::vector< float > > &confidences)
Detailed Description
This class provides a simple interface to extract SNP calls and confidence values from a multi data CHP file.
Definition at line 35 of file FusionCHPMultiDataAccessor.h.
Constructor & Destructor Documentation
FusionCHPMultiDataAccessor::FusionCHPMultiDataAccessor ()
Constructor
Definition at line 30 of file FusionCHPMultiDataAccessor.cpp.
FusionCHPMultiDataAccessor::~FusionCHPMultiDataAccessor ()
Destructor
Definition at line 34 of file FusionCHPMultiDataAccessor.cpp.
Member Function Documentation
void FusionCHPMultiDataAccessor::ExtractData (const std::vector< std::string > & snps, std::vector< std::vector< u_int8_t > > & calls, std::vector< std::vector< float > > & confidences)
Extract the calls and confidences for each input SNP.
Parameters:
snps The list of snps to extract data for.
calls A matrix to hold the calls.
confidences A matrix to hold the confidence values.
Definition at line 69 of file FusionCHPMultiDataAccessor.cpp.
References affymetrix_fusion_io::FusionCHPMultiDataData::FromBase(), affymetrix_fusion_io::FusionCHPMultiDataData::GetGenoCall(), affymetrix_fusion_io::FusionCHPMultiDataData::GetGenoConfidence(), and affymetrix_fusion_io::FusionCHPDataReg::Read().
bool FusionCHPMultiDataAccessor::Initialize (const std::vector< std::string > & chps)
Initialize the map of SNP names to indicies.
Parameters:
chps The list of CHP files to extract data from.
Definition at line 38 of file FusionCHPMultiDataAccessor.cpp.
References affymetrix_fusion_io::FusionCHPMultiDataData::FromBase(), affymetrix_fusion_io::FusionCHPMultiDataData::GetEntryCount(), affymetrix_fusion_io::FusionCHPMultiDataData::GetProbeSetName(), and affymetrix_fusion_io::FusionCHPDataReg::Read().
The documentation for this class was generated from the following files:
calvin_files/fusion/src/FusionCHPMultiDataAccessor.h
calvin_files/fusion/src/FusionCHPMultiDataAccessor.cpp