Affymetrix Power Tools: FileInbred Class Reference
FileInbred Class Reference
Read sample covariate relative inbreeding level assignments from file.
#include <FileInbred.h>