Affymetrix Power Tools: affxcel::CCELFileWriter Class Reference
affxcel::CCELFileWriter Class Reference
affxcel::CCELFileWriter /// ///
#include <CELFileWriter.h>