Affymetrix Power Tools: RegressionTest Class Reference
RegressionTest Class Reference
Utility class for helping to do regression testing.
#include <RegressionTest.h>
Public Member Functions
RegressionTest (const std::string &name, const std::string &generatedFile, const std::string &goldFile, double epsilon, const std::string &command, int rowSkip, int colSkip, bool matchNames, int allowedMisMatch, bool negTest=false)
Constructor.
RegressionTest (const std::string &name, const std::string &command, const std::vector< RegressionCheck * > &fileChecks, bool doDelete=true, bool negTest=false)
void setLogFile (const std::string &logFile)
Set the log from LogStream to parse memory and other stats from.
void setValgrindLog (const std::string &vgLog)
Set the valgrind --log-file to read the memory leak and checks from.
void setDatabase (const std::string &path)
void setSuiteName (const std::string &suiteName)
int getNumPassed () const
int getNumFailed () const
bool run ()
Run the command to check the test.
bool pass ()
Do we pass our post-run tests???
std::string getErrorMsg ()
Get whatever message was reported.
void setSuite (const RegressionSuite &suite, const std::string &outDir, const std::string &logDir, const std::string &valgrindLog)
Static Public Member Functions
static bool syncDirectory (const char *targetName, const char *localName, const char *hostUrl, std::string &errorMsg)
Try to link and if necessary copy a directory from another place.
Public Attributes
std::string m_Name
bool m_NegTest
Protected Member Functions
RegressionTest ()
Constructor.
void initialize ()
Set appropriate data members to no data values.
void parseLogFile (const std::string &logFile)
Read a log file to populate things like memory used, etc.
void parseValgrindFile (const std::string &vgLog)
Read through valgrind output to determine memory leaks and errors.
void recordResults (bool success)
Protected Attributes
std::vector< RegressionCheck * > m_Checks
std::string m_CommandStr
Command that generates the generated file, platform adjusted.
std::string m_Error
Any errors generated are stored here.
std::string m_SuiteName
bool m_Delete
int64_t m_RunTime
How long did the test take to run in seconds.
int m_MaxMem
Maximum resident virtual memory during processing.
int m_MemOk
0 false, 1 true, -1 not set
int m_MemLeaks
Bytes definitely leaked according to valgrind.
int m_TimeStamp
bool m_DoMemCheck
std::string m_ValgrindLog
std::string m_LogToParse
std::string m_Database
std::string m_OpSys
std::string m_Build
bool m_64bit
int m_NumPassed
int m_NumFailed
SQLiteDatabase * m_SQL
Static Protected Attributes
static const int DATA_NA = -1
Detailed Description
Utility class for helping to do regression testing.
Definition at line 45 of file RegressionTest.h.
Constructor & Destructor Documentation
RegressionTest::RegressionTest (const std::string & name, const std::string & generatedFile, const std::string & goldFile, double epsilon, const std::string & command, int rowSkip, int colSkip, bool matchNames, int allowedMisMatch, bool negTest = false)
Constructor.
Definition at line 42 of file RegressionTest.cpp.
References Fs::convertCommandToUnc(), initialize(), and m_CommandStr.
Member Function Documentation
std::string RegressionTest::getErrorMsg () [inline]
Get whatever message was reported.
Returns:
the concatanation of any error messages that have been sent.
Definition at line 109 of file RegressionTest.h.
References m_Error.
void RegressionTest::parseLogFile (const std::string & logFile) [protected]
Read a log file to populate things like memory used, etc.
Parameters:
logFile - File produced by LogStream
Definition at line 292 of file RegressionTest.cpp.
References RowFile::close(), m_MaxMem, Max, RowFile::nextRow(), RowFile::open(), and Convert::toInt().
void RegressionTest::parseValgrindFile (const std::string & vgLog) [protected]
Read through valgrind output to determine memory leaks and errors.
Note that according to the valgrind manual it is best to compile the program with -O0 (optimization level zero) to avoid false positives. http://valgrind.org/docs/manual/quick-start.html#quick-start.prepare
Parameters:
vgLog - valgrind output with the --log-file option
Definition at line 308 of file RegressionTest.cpp.
References APT_ERR_ASSERT, m_MemLeaks, m_MemOk, and Convert::toInt().
Referenced by pass().
bool RegressionTest::pass ()
Do we pass our post-run tests???
Returns:
true if we pass our test
Definition at line 150 of file RegressionTest.cpp.
References m_Error, m_RunTime, parseValgrindFile(), Fs::rm(), run(), and ToStr().
bool RegressionTest::run (void)
Run the command to check the test.
Returns:
true if executes sucessfully, false otherwise.
Definition at line 101 of file RegressionTest.cpp.
References m_CommandStr, m_Error, m_RunTime, and ToStr().
Referenced by pass().
void RegressionTest::setLogFile (const std::string & logFile) [inline]
Set the log from LogStream to parse memory and other stats from.
Parameters:
logFile - path to log file
Definition at line 74 of file RegressionTest.h.
void RegressionTest::setValgrindLog (const std::string & vgLog) [inline]
Set the valgrind --log-file to read the memory leak and checks from.
Parameters:
vgLog - path to valgrind log file
Definition at line 81 of file RegressionTest.h.
bool RegressionTest::syncDirectory (const char * targetName, const char * localName, const char * hostUrl, std::string & errorMsg) [static]
Try to link and if necessary copy a directory from another place.
Parameters:
targetName - path to directory to be synced
localName - where we want data synced to locally.
hostUrl - url for data if copying necessary.
errorMsg - fill in error message here if something goes wrong.
Returns:
- true if sucessful, false otherwise.
Definition at line 250 of file RegressionTest.cpp.
References Verbose::out(), and ToStr().
The documentation for this class was generated from the following files:
util/RegressionTest.h
util/RegressionTest.cpp