Affymetrix Power Tools: affxbed::BEDFileData Class Reference
affxbed::BEDFileData Class Reference
#include <BEDFileData.h>