Affymetrix Power Tools: CytogeneticsTrioAnalysis Class Reference
CytogeneticsTrioAnalysis Class Reference
A class for doing trio analysis.
#include <CytogeneticsTrioAnalysis.h>
Public Member Functions
double calculateLODPaternity (std::vector< char > &vSampleGenotypeCalls, std::vector< char > &vKnownParentGenotypeCalls, std::vector< char > &vAllegedParentGenotypeCalls, std::vector< float > &vProbabilityAAlleles, std::vector< float > &vProbabilityBAlleles, double dErrorRate=0.05)
Some Trio Analysis functions for Cytogenetics.
double calculateLODPaternity (std::vector< char > &vSampleGenotypeCalls, std::vector< char > &vAllegedParentGenotypeCalls, std::vector< float > &vProbabilityAAlleles, std::vector< float > &vProbabilityBAlleles, double dErrorRate=0.05)
Calculate the LOD (Likelihood of odds) value for the paternity test with one parent.
Detailed Description
A class for doing trio analysis.
Definition at line 38 of file CytogeneticsTrioAnalysis.h.
Member Function Documentation
double CytogeneticsTrioAnalysis::calculateLODPaternity (std::vector< char > & vSampleGenotypeCalls, std::vector< char > & vKnownMotherGenotypeCalls, std::vector< char > & vAllegedFatherGenotypeCalls, std::vector< float > & vProbabilityAAlleles, std::vector< float > & vProbabilityBAlleles, double dErrorRate = 0.05)
Some Trio Analysis functions for Cytogenetics.
Calculate the LOD (Likelihood of odds) value for the paternity test with both parents. Note: all the vectors input to this function must be of the same length. One element per marker.
Parameters:
vSampleGenotypeCalls - std::vector<char> where -1 = No Call, 0 = AA, 1 = AB, and 2 = BB.
vKnownParentGenotypeCalls - std::vector<char> where -1 = No Call, 0 = AA, 1 = AB, and 2 = BB.
vAllegedParentGenotypeCalls - std::vector<char> where -1 = No Call, 0 = AA, 1 = AB, and 2 = BB.
vProbabilityAAlleles - std::vector<float> The probability of the AAllele occurring in the population.
vProbabilityBAlleles - std::vector<float> The probability of the BAllele occurring in the population.
dErrorRate - The error rate associated with this calculation (defaults to 0.05).
Returns:
- The calculated LOD score.
Definition at line 50 of file CytogeneticsTrioAnalysis.cpp.
References Err::errAbort().
Referenced by CNFamilialAnalysisMethodLOD::run().
double CytogeneticsTrioAnalysis::calculateLODPaternity (std::vector< char > & vSampleGenotypeCalls, std::vector< char > & vAllegedParentGenotypeCalls, std::vector< float > & vProbabilityAAlleles, std::vector< float > & vProbabilityBAlleles, double dErrorRate = 0.05)
Calculate the LOD (Likelihood of odds) value for the paternity test with one parent.
Note: all the vectors input to this function must be of the same length. One element per marker.
Parameters:
vSampleGenotypeCalls - std::vector<char> where -1 = No Call, 0 = AA, 1 = AB, and 2 = BB.
vAllegedParentGenotypeCalls - std::vector<char> where -1 = No Call, 0 = AA, 1 = AB, and 2 = BB.
vProbabilityAAlleles - std::vector<float> The probability of the AAllele occurring in the population.
vProbabilityBAlleles - std::vector<float> The probability of the BAllele occurring in the population.
dErrorRate - The error rate associated with this calculation (defaults to 0.05).
Returns:
- The calculated LOD score.
Definition at line 79 of file CytogeneticsTrioAnalysis.cpp.
References Err::errAbort().
The documentation for this class was generated from the following files:
copynumber/CytogeneticsTrioAnalysis.h
copynumber/CytogeneticsTrioAnalysis.cpp