Affymetrix Power Tools: TranslationEngine Class Reference
TranslationEngine Class Reference
Class to run the DMET analysis.
#include <TranslationEngine.h>