Affymetrix Power Tools: affymetrix_calvin_io::CHPFileReader Class Reference
affymetrix_calvin_io::CHPFileReader Class Reference
#include <CHPFileReader.h>
Public Member Functions
CHPFileReader ()
~CHPFileReader ()
const std::string GetFilename () const
void SetFilename (const std::string &name)
void Read (CHPData &data)
Protected Attributes
std::string fileName
Detailed Description
This class reads a CHP data file. It is an interpreter class.
Definition at line 43 of file CHPFileReader.h.
Constructor & Destructor Documentation
CHPFileReader::CHPFileReader ()
Constructor
Definition at line 33 of file CHPFileReader.cpp.
CHPFileReader::~CHPFileReader ()
Destructor
Definition at line 40 of file CHPFileReader.cpp.
Member Function Documentation
const std::string affymetrix_calvin_io::CHPFileReader::GetFilename () const [inline]
Gets the name of the input file.
Returns:
The name of the file to read.
Definition at line 57 of file CHPFileReader.h.
References fileName.
void CHPFileReader::Read (CHPData & data)
Reads the file header of the generic file and reads all the DataPlaneHeader information.
Parameters:
data A reference to a GenericData object that will receive information from the file.
Exceptions:
affymetrix_calvin_exceptions::FileNotFoundException The file does not exist.
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Definition at line 44 of file CHPFileReader.cpp.
References affymetrix_calvin_io::CHPData::Clear(), fileName, affymetrix_calvin_io::CHPData::GetFilename(), affymetrix_calvin_io::CHPData::GetGenericData(), affymetrix_calvin_io::GenericFileReader::ReadHeader(), and affymetrix_calvin_io::GenericFileReader::SetFilename().
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::CanReadFile(), CalvinChpCheck::check(), affymetrix_chp_converter::CHPFileConvertToXDA::ConvertCalvinFile(), affymetrix_fusion_io::CalvinCHPDataAdapter::Read(), and affymetrix_fusion_io::CalvinCHPDataAdapter::ReadHeader().
void affymetrix_calvin_io::CHPFileReader::SetFilename (const std::string & name) [inline]
Sets the name of the input file.
Parameters:
name The name of the file to read.
Definition at line 63 of file CHPFileReader.h.
References fileName.
Referenced by CalvinChpCheck::check(), and affymetrix_chp_converter::CHPFileConvertToXDA::ConvertCalvinFile().
Member Data Documentation
std::string affymetrix_calvin_io::CHPFileReader::fileName [protected]
Name of the file to read
Definition at line 76 of file CHPFileReader.h.
Referenced by GetFilename(), Read(), and SetFilename().
The documentation for this class was generated from the following files:
calvin_files/parsers/src/CHPFileReader.h
calvin_files/parsers/src/CHPFileReader.cpp