Affymetrix Power Tools: CEMSeed Class Reference
CEMSeed Class Reference
Object to hold all prior information to constitute an EM seed.
#include <PrimeEM.h>
Public Member Functions
CEMSeed (const int clusters=3)
, the default constructor
void set (const int clusters=3)
set the number of cluters
CEMSeed & operator= (const CEMSeed &rhs)
assignment operator
bool operator== (const CEMSeed &rhs)
equal operator
void setMu (const double c[], const int size=3)
Set the centers of clusters assuming upto three clusters in total.
void setMu (const double c1, const double c2, const double c3)
void setMu (std::vector< double > &c)
void setMinMu (const double c[], const int size=3)
Set the minimum of centers of clusters assuming upto three clusters in total.
void setMinMu (const double c1, const double c2, const double c3)
void setMinMu (std::vector< double > &c)
void setMaxMu (const double c[], const int size=3)
Set the maximum of centers of clusters assuming upto three clusters in total.
void setMaxMu (const double c1, const double c2, const double c3)
void setMaxMu (std::vector< double > &c)
void setWeight (const double w[], const int size=3)
Set the weight of clusters assuming upto three clusters in total.
void setWeight (const double w1, const double w2, const double w3)
void setWeight (std::vector< double > &w)
void setSigma (const double s[], const int size=3)
Set the sigmas of clusters assuming upto three clusters in total.
void setSigma (const double s1, const double s2, const double s3)
void setSigma (std::vector< double > &s)
void setMinSigma (const double s[], const int size=3)
Set the minimum of sigmas of clusters assuming upto three clusters in total.
void setMinSigma (const double s1, const double s2, const double s3)
void setMinSigma (std::vector< double > &s)
void setMaxSigma (const double s[], const int size=3)
Set the maximum of sigmas of clusters assuming upto three clusters in total.
void setMaxSigma (const double s1, const double s2, const double s3)
void setMaxSigma (std::vector< double > &s)
std::vector< double > getMu ()
get functions to all member variables
std::vector< double > getSigma ()
std::vector< double > getWeight ()
std::vector< double > getMinMu ()
std::vector< double > getMinSigma ()
std::vector< double > getMaxMu ()
std::vector< double > getMaxSigma ()
Protected Attributes
std::vector< double > m_mu
centers of clusters
std::vector< double > m_sigma
sigmas of clusters
std::vector< double > m_weight
weights of clusters
std::vector< double > m_minMu
minimums of cluster centers
std::vector< double > m_minSigma
minimums of cluter sigmas
std::vector< double > m_maxMu
maximums of cluster centers
std::vector< double > m_maxSigma
maximums of cluster sigmas
Friends
class CPrimeEM
Detailed Description
Object to hold all prior information to constitute an EM seed.
Definition at line 47 of file PrimeEM.h.
Constructor & Destructor Documentation
CEMSeed::CEMSeed (const int clusters = 3)
, the default constructor
Parameters:
clusters - number of clusters to cluster data into
Definition at line 110 of file PrimeEM.cpp.
References m_maxMu, m_maxSigma, m_minMu, m_minSigma, m_mu, m_sigma, and m_weight.
Member Function Documentation
std::vector<double> CEMSeed::getMu () [inline]
get functions to all member variables
Returns:
the contents of member variables
Definition at line 150 of file PrimeEM.h.
References m_mu.
void CEMSeed::set (const int clusters = 3)
set the number of cluters
Parameters:
clusters - number of clusters to cluster data into
Definition at line 124 of file PrimeEM.cpp.
References m_maxMu, m_maxSigma, m_minMu, m_minSigma, m_mu, m_sigma, and m_weight.
void CEMSeed::setMaxMu (const double c[], const int size = 3)
Set the maximum of centers of clusters assuming upto three clusters in total.
Parameters:
c1 - maximum of center for the first cluster
c2 - maximum of center for the second cluster
c3 - maximum of center for the third cluster
c[] - array of maximum of centers for all clusters
c - vector of maximum of centers of all clusters
Definition at line 222 of file PrimeEM.cpp.
References m_maxMu.
Referenced by EmGenderCelListener::CallGender(), MultiChannelHomHiLoCelListener::computeClusterPeaks(), HomHiLoCelListener::computeClusterPeaks(), and t_CallEMGender().
void CEMSeed::setMaxSigma (const double s[], const int size = 3)
Set the maximum of sigmas of clusters assuming upto three clusters in total.
Parameters:
s1 - maximum of sigma for the first cluster
s2 - maximum of sigma for the second cluster
s3 - maximum of sigma for the third cluster
s[] - array of maximum sigmas for all clusters
s - vector of maximum sigmas of all clusters
Definition at line 322 of file PrimeEM.cpp.
References m_maxSigma.
Referenced by EmGenderCelListener::CallGender(), MultiChannelHomHiLoCelListener::computeClusterPeaks(), HomHiLoCelListener::computeClusterPeaks(), and t_CallEMGender().
void CEMSeed::setMinMu (const double c[], const int size = 3)
Set the minimum of centers of clusters assuming upto three clusters in total.
Parameters:
c1 - minimum of center for the first cluster
c2 - minimum of center for the second cluster
c3 - minimum of center for the third cluster
c[] - array of minimum of centers for all clusters
c - vector of minimum of centers of all clusters
Definition at line 197 of file PrimeEM.cpp.
References m_minMu.
Referenced by EmGenderCelListener::CallGender(), MultiChannelHomHiLoCelListener::computeClusterPeaks(), HomHiLoCelListener::computeClusterPeaks(), and t_CallEMGender().
void CEMSeed::setMinSigma (const double s[], const int size = 3)
Set the minimum of sigmas of clusters assuming upto three clusters in total.
Parameters:
s1 - minimum of sigma for the first cluster
s2 - minimum of sigma for the second cluster
s3 - minimum of sigma for the third cluster
s[] - array of minimum sigmas for all clusters
s - vector of minimum sigmas of all clusters
Definition at line 297 of file PrimeEM.cpp.
References m_minSigma.
Referenced by EmGenderCelListener::CallGender(), MultiChannelHomHiLoCelListener::computeClusterPeaks(), HomHiLoCelListener::computeClusterPeaks(), and t_CallEMGender().
void CEMSeed::setMu (const double c[], const int size = 3)
Set the centers of clusters assuming upto three clusters in total.
Parameters:
c1 - center for the first cluster
c2 - center for the second cluster
c3 - center for the third cluster
c[] - array of centers of all clusters
c - vector of centers of all clusters
Definition at line 172 of file PrimeEM.cpp.
References m_mu.
Referenced by EmGenderCelListener::CallGender(), MultiChannelHomHiLoCelListener::computeClusterPeaks(), HomHiLoCelListener::computeClusterPeaks(), and t_CallEMGender().
void CEMSeed::setSigma (const double s[], const int size = 3)
Set the sigmas of clusters assuming upto three clusters in total.
Parameters:
s1 - sigma for the first cluster
s2 - sigma for the second cluster
s3 - sigma for the third cluster
s[] - array of sigmas for all clusters
s - vector of sigmas of all clusters
Definition at line 272 of file PrimeEM.cpp.
References m_sigma.
Referenced by EmGenderCelListener::CallGender(), MultiChannelHomHiLoCelListener::computeClusterPeaks(), HomHiLoCelListener::computeClusterPeaks(), and t_CallEMGender().
void CEMSeed::setWeight (const double w[], const int size = 3)
Set the weight of clusters assuming upto three clusters in total.
Parameters:
w1 - weight for the first cluster
w2 - weight of center for the second cluster
w3 - weight of center for the third cluster
w[] - array of weights for all clusters
w - vector of weights of all clusters
Definition at line 247 of file PrimeEM.cpp.
References m_weight.
Referenced by EmGenderCelListener::CallGender(), MultiChannelHomHiLoCelListener::computeClusterPeaks(), HomHiLoCelListener::computeClusterPeaks(), CPrimeEM::generateEmpiricalEMSeeds(), and t_CallEMGender().
The documentation for this class was generated from the following files:
algorithm/em/PrimeEM.h
algorithm/em/PrimeEM.cpp