Affymetrix Power Tools: Profile Class Reference
Profile Class Reference
Place to group program options.
#include <Profile.h>
Public Member Functions
void begin ()
Profile::begin Synopsis: Mark the begin time to be profiled.
void checkTimes ()
Profile::checkTimes Synopsis: Checks if endTime - startTime > 0.
void end ()
Profile::end Synopsis: Mark the end time of something profiled.
float getElapsedSeconds ()
Profile::getElapsedSeconds Synopsis: returns endTime - startTime.
std::string getElapsedFormatedString ()
Profile::getElapsedFormatedString Synopsis: returns a formated time std::string as MMmSSs.
Public Attributes
float m_totalElapsedSeconds
int m_totalCalls
timeval m_startTimeval
timeval m_endTimeval
int m_startCount
int m_endCount
Detailed Description
Place to group program options.
Definition at line 53 of file Profile.h.
Member Function Documentation
void Profile::begin ()
Profile::begin Synopsis: Mark the begin time to be profiled.
Resets endTime to startTime.
Returns:
- void
Definition at line 45 of file Profile.cpp.
Referenced by main(), and TranslationEngine::runImp().
void Profile::checkTimes ()
Profile::checkTimes Synopsis: Checks if endTime - startTime > 0.
Returns:
- void, throws exception if endTime - startTime <= 0
Definition at line 100 of file Profile.cpp.
References APT_ERR_ABORT.
Referenced by end().
void Profile::end ()
Profile::end Synopsis: Mark the end time of something profiled.
Returns:
- void, throws exception if startTime is not set.
Definition at line 68 of file Profile.cpp.
References checkTimes().
Referenced by TranslationEngine::runImp().
std::string Profile::getElapsedFormatedString ()
Profile::getElapsedFormatedString Synopsis: returns a formated time std::string as MMmSSs.
Assumes time will never be more than 60 minutes, or 1 hour.
Returns:
- void, throws exception if startTime and endTime are not set.
Definition at line 143 of file Profile.cpp.
References getElapsedSeconds().
Referenced by TranslationEngine::runImp().
float Profile::getElapsedSeconds ()
Profile::getElapsedSeconds Synopsis: returns endTime - startTime.
Returns:
- void, throws exception if startTime and endTime are not set.
Definition at line 125 of file Profile.cpp.
Referenced by getElapsedFormatedString(), and TranslationEngine::runImp().
The documentation for this class was generated from the following files:
translation/Profile.h
translation/Profile.cpp