Affymetrix Power Tools: CNFamilialAnalysisMethodFactory Class Reference
CNFamilialAnalysisMethodFactory Class Reference
A factory class for making copy number analysis methods based on a string representation.
#include <CNFamilialAnalysisMethodFactory.h>
Public Member Functions
CNFamilialAnalysisMethodFactory ()
Constructor.
void registerMethod (const SelfDoc &doc, SelfCreate::selfCreator maker)
Register the method.
CNFamilialAnalysisMethod * CNFamilialAnalysisMethodForString (const std::string &spec)
Create a pointer to a new CNFamilialAnalysisMethod object as described in the string specification.
CNFamilialReporter * CNFamilialReporterForString (const std::string &spec)
Create a pointer to a new CNFamilialReporter object as described in the string specification.
std::vector< SelfDoc > getDocs ()
Protected Attributes
std::vector< SelfDoc > m_Docs
std::vector
< SelfCreate::selfCreator > m_Creators
Detailed Description
A factory class for making copy number analysis methods based on a string representation.
Definition at line 44 of file CNFamilialAnalysisMethodFactory.h.
Constructor & Destructor Documentation
CNFamilialAnalysisMethodFactory::CNFamilialAnalysisMethodFactory ()
Constructor.
Registers the objects we know how to create and how they describe themselves.
Definition at line 47 of file CNFamilialAnalysisMethodFactory.cpp.
References CNFamilialReporterFamilial::explainSelf(), CNFamilialAnalysisMethodHemizygousParentOfOrigin::explainSelf(), CNFamilialAnalysisMethodDenovoCopyNumber::explainSelf(), CNFamilialAnalysisMethodIsoUPD::explainSelf(), CNFamilialAnalysisMethodHeteroUPD::explainSelf(), CNFamilialAnalysisMethodCNLossLOHConcordance::explainSelf(), CNFamilialAnalysisMethodCNNeutralLOHConcordance::explainSelf(), CNFamilialAnalysisMethodGenotypeDiscordance::explainSelf(), CNFamilialAnalysisMethodGenotypeConcordance::explainSelf(), CNFamilialAnalysisMethodSegmentOverlap::explainSelf(), CNFamilialAnalysisMethodLOD::explainSelf(), CNFamilialReporterFamilial::newObject(), CNFamilialAnalysisMethodHemizygousParentOfOrigin::newObject(), CNFamilialAnalysisMethodDenovoCopyNumber::newObject(), CNFamilialAnalysisMethodIsoUPD::newObject(), CNFamilialAnalysisMethodHeteroUPD::newObject(), CNFamilialAnalysisMethodCNLossLOHConcordance::newObject(), CNFamilialAnalysisMethodCNNeutralLOHConcordance::newObject(), CNFamilialAnalysisMethodGenotypeDiscordance::newObject(), CNFamilialAnalysisMethodGenotypeConcordance::newObject(), CNFamilialAnalysisMethodSegmentOverlap::newObject(), CNFamilialAnalysisMethodLOD::newObject(), and registerMethod().
Member Function Documentation
CNFamilialAnalysisMethod * CNFamilialAnalysisMethodFactory::CNFamilialAnalysisMethodForString (const std::string & spec)
Create a pointer to a new CNFamilialAnalysisMethod object as described in the string specification.
Parameters:
spec - Specification string
Returns:
Pointer to new CNFamilialAnalysisMethod objects, must be deleted when finished.
Definition at line 74 of file CNFamilialAnalysisMethodFactory.cpp.
References SelfCreate::selfCreateFromString().
CNFamilialReporter * CNFamilialAnalysisMethodFactory::CNFamilialReporterForString (const std::string & spec)
Create a pointer to a new CNFamilialReporter object as described in the string specification.
Parameters:
spec - Specification string
Returns:
Pointer to new CNFamilialReporter objects, must be deleted when finished.
Definition at line 98 of file CNFamilialAnalysisMethodFactory.cpp.
References SelfCreate::selfCreateFromString().
void CNFamilialAnalysisMethodFactory::registerMethod (const SelfDoc & doc, SelfCreate::selfCreator maker) [inline]
Register the method.
Parameters:
const SelfDoc& - The SelfDoc object
SelfCreate::selfCreator - The newObject function
Definition at line 59 of file CNFamilialAnalysisMethodFactory.h.
Referenced by CNFamilialAnalysisMethodFactory().
The documentation for this class was generated from the following files:
copynumber/CNFamilialAnalysisMethodFactory.h
copynumber/CNFamilialAnalysisMethodFactory.cpp