Affymetrix Power Tools: File5_Sqlite Class Reference
File5_Sqlite Class Reference
Class with some utility functions for converting File5 files into sqlite databases for analysis.
#include <File5_Sqlite.h>
Static Public Member Functions
static void copySchema (sqlite3 *db, affx::File5_Tsv *tsv5, File5_Sqlite_Config &config)
Use the column definitions in the File5 definition to create a table in sqlite database.
static void copyData (sqlite3 *db, affx::File5_Tsv *tsv5, File5_Sqlite_Config &config)
Fill in an sqlite databse table with the data in the File5_Tsv table.
Detailed Description
Class with some utility functions for converting File5 files into sqlite databases for analysis.
Currently static libraries to be used by other programs.
Definition at line 56 of file File5_Sqlite.h.
Member Function Documentation
void File5_Sqlite::copyData (sqlite3 * db, affx::File5_Tsv * tsv5, File5_Sqlite_Config & config) [static]
Fill in an sqlite databse table with the data in the File5_Tsv table.
Parameters:
db - Open connection to the sqlite database data will be inserted
tsv5 - File5_Tsv pointer which will be read for data
config - Various configurations to insert the data like table name etc.
Definition at line 105 of file File5_Sqlite.cpp.
References Err::errAbort(), affx::File5_Tsv::getColumnPtr(), Verbose::progressStep(), File5_Sqlite_Config::tableName, and ToStr().
void File5_Sqlite::copySchema (sqlite3 * db, affx::File5_Tsv * tsv5, File5_Sqlite_Config & config) [static]
Use the column definitions in the File5 definition to create a table in sqlite database.
Parameters:
db - Open connection to the sqlite database where table will be created.
tsv5 - File5_Tsv pointer which will be read to create column definitions.
config - Various configurations to make the table like table name, and primary column name
Definition at line 81 of file File5_Sqlite.cpp.
References File5_Sqlite_Config::numeric, Verbose::out(), File5_Sqlite_Config::primaryColumn, and File5_Sqlite_Config::tableName.
The documentation for this class was generated from the following files:
file5/File5_Sqlite.h
file5/File5_Sqlite.cpp