Affymetrix Power Tools: SnpModelConverter Class Reference
SnpModelConverter Class Reference
Public Types
enum SnpDerivedHeaderType { NONE, GTC4_1, LAST_DERIVED_TYPE }
enum SnpChipType {
UNKNOWN_CHIP, SNP5, SNP6, AXIOM,
LAST_CHP_TYPE
}
enum SnpModelFileType {
UNKNOWN_FILE, BIRDSEED_PRIOR, BIRDSEED_POSTERIOR, BRLMMP_MODEL,
BRLMMP_MODEL_HDF5, SQLITE_MODEL_FILE, LAST_MODEL_TYPE
}
Public Member Functions
SnpModelConverter (enum SnpChipType chip=UNKNOWN_CHIP, enum SnpModelFileType model=UNKNOWN_FILE)
bool vecContains (const std::string &needle, const std::vector< std::string > &haystack)
enum SnpModelConverter::SnpChipType guessChipType (enum SnpModelConverter::SnpModelFileType modelType, const std::vector< std::string > &chipTypes, const std::string &firstPsName)
int guessNumProbesets (enum SnpModelConverter::SnpChipType type)
enum SnpModelFileType determineFileType (const std::string &fileName)
void convertToDbModel (const std::string &fileIn, const std::string &fileOut, const std::string &file5Path="")
void createTables (SQLiteDatabase &db)
void convertBrlmmPToDbModel (const std::string &fileIn, const std::string &fileOut)
sqlite3_stmt * getInsertStatement (SQLiteDatabase &db)
void writeSnpDistribution (const snp_labeled_distribution &p, sqlite3_stmt &stmt, SQLiteDatabase &db)
void headersToMeta (affx::TsvFile &tsv, SQLiteDatabase &db)
void convertBirdseedPriorToDbModel (const std::string &fileIn, const std::string &fileOut)
void birdseedModelFromStrings (const std::string &name, int copynuber, const std::string &bb, const std::string &ab, const std::string &aa, char sep, snp_labeled_distribution &p)
void birdseedStringToCluster (const std::string &s, char sep, cluster_data &d)
void convertBirdseedPosteriorToDbModel (const std::string &fileIn, const std::string &fileOut)
void convertBrlmmPFile5ToDbModel (const std::string &fileIn, const std::string &file5Path, const std::string &fileOut)
enum SnpModelFileType guessTsvFileType (const std::string &file)
enum SnpModelFileType guessFileType (const std::string &file)
void addBirdseedPosteriorFromStrings (std::string &id, const std::string &aa, const std::string &ab, const std::string &bb, snp_labeled_distribution &p)
void getArrayTypeAndAlgorithm (const std::string &fileIn, std::vector< std::string > &result)
Static Public Member Functions
static bool GetModelHeaders (const std::string &modelFilePath, const std::string &headerMapType, std::map< std::string, std::string * > &headerMap, const char *headerMapValueDelimiter=NULL)
SnpModelConverter::GetModelHeaders Given a potentional model file return the headers.
Detailed Description
Definition at line 87 of file SnpModelConverter.h.
Member Function Documentation
bool SnpModelConverter::GetModelHeaders (const std::string & modelFilePath, const std::string & headerMapType, std::map< std::string, std::string * > & headerMap, const char * headerMapValueDelimiter = NULL) [static]
SnpModelConverter::GetModelHeaders Given a potentional model file return the headers.
Model files can be of type db, A5, or TSV.
Parameters:
modelFilePath - the models file, posterior or prior
headerMapType - 1.) empty for just the raw headers 2.) "GTC4.1" - GTC 4.1 map
headerMap - return header key/value pairs
headerMapValueDelimiter
return multiple header values using delimiter If this value is passed in then all ambiguous matching header values are returned delimited by the passed in value. If this value is not passed (NULL) then only the first value of the first qualifying header is returned.
Returns:
- true if the file qualifies as a models file, false otherwise.
Definition at line 1372 of file SnpModelConverter.cpp.
References APT_ERR_ABORT, Err::errAbort(), Verbose::out(), ToStr(), and Fs::Unc().
The documentation for this class was generated from the following files:
chipstream/SnpModelConverter.h
chipstream/SnpModelConverter.cpp