Affymetrix Power Tools: affymetrix_calvin_utilities::StringUtils Class Reference
affymetrix_calvin_utilities::StringUtils Class Reference
#include <StringUtils.h>
Static Public Member Functions
static void STLTrimLeft (std::string &s, char chTarget)
static void STLTrimLeft (std::string &s)
static void STLTrimRight (std::string &s, char chTarget)
static void STLTrimRight (std::string &s)
static void STLTrimLeft (std::wstring &s, wchar_t chTarget)
static void STLTrimLeft (std::wstring &s)
static void STLTrimRight (std::wstring &s, wchar_t chTarget)
static void STLTrimRight (std::wstring &s)
static std::string ConvertWCSToMBS (const std::wstring &source)
static std::wstring ConvertMBSToWCS (const std::string &source)
static std::wstring ToString (int value, int digits, wchar_t fill=L'0')
static std::vector< std::string > Split (const std::string &inputString, const std::string &separator)
Detailed Description
This class provides utility functions for strings.
Definition at line 40 of file StringUtils.h.
Member Function Documentation
std::wstring StringUtils::ConvertMBSToWCS (const std::string & source) [static]
Convert multi-byte character string to a wide character character string.
Parameters:
source Multi-byte character string to convert.
Returns:
Converted wide character character string.
Definition at line 127 of file StringUtils.cpp.
Referenced by affymetrix_fusion_io::GCOSCELDataAdapter::GetDatHeader(), CNFamilialReporter::setupBoolParameter(), CNFamilialAnalysisMethod::setupBoolParameter(), CNAnalysisMethod::setupBoolParameter(), CNAnalysisMethod::setupDoubleParameter(), CNFamilialReporter::setupFloatParameter(), CNFamilialAnalysisMethod::setupFloatParameter(), CNAnalysisMethod::setupFloatParameter(), CNFamilialReporter::setupIntParameter(), CNFamilialAnalysisMethod::setupIntParameter(), CNAnalysisMethod::setupIntParameter(), CNFamilialReporter::setupStringParameter(), CNFamilialAnalysisMethod::setupStringParameter(), and CNAnalysisMethod::setupStringParameter().
std::string StringUtils::ConvertWCSToMBS (const std::wstring & source) [static]
Convert wide character string to a multi-byte character string.
Parameters:
source Wide character string to convert.
Returns:
Converted multi-byte character string.
Definition at line 115 of file StringUtils.cpp.
void StringUtils::STLTrimLeft (std::wstring & s, wchar_t chTarget) [static]
Trim chTarget from the left of string s.
Parameters:
s String from which to remove characters.
chTarget Character to trim.
Definition at line 76 of file StringUtils.cpp.
void StringUtils::STLTrimLeft (std::string & s) [static]
Trim space characters (' ') from the left of string s.
Parameters:
s String from which to remove characters.
Definition at line 48 of file StringUtils.cpp.
References STLTrimLeft().
void StringUtils::STLTrimLeft (std::string & s, char chTarget) [static]
Trim chTarget from the left of string s.
Parameters:
s String from which to remove characters.
chTarget Character to trim.
Definition at line 37 of file StringUtils.cpp.
Referenced by affymetrix_calvin_utilities::DateTime::Date(), STLTrimLeft(), and affymetrix_calvin_utilities::DateTime::Time().
void StringUtils::STLTrimLeft (std::wstring & s) [static]
Trim space characters (' ') from the left of string s.
Parameters:
s String from which to remove characters.
Definition at line 87 of file StringUtils.cpp.
References STLTrimLeft().
void StringUtils::STLTrimRight (std::wstring & s) [static]
Trim space characters (' ') from the right of string s.
Parameters:
s String from which to remove characters.
Definition at line 107 of file StringUtils.cpp.
References STLTrimRight().
void StringUtils::STLTrimRight (std::string & s) [static]
Trim space characters (' ') from the right of string s.
Parameters:
s String from which to remove characters.
Definition at line 68 of file StringUtils.cpp.
References STLTrimRight().
void StringUtils::STLTrimRight (std::string & s, char chTarget) [static]
Trim chTarget from the right of string s.
Parameters:
s String from which to remove characters.
chTarget Character to trim.
Definition at line 56 of file StringUtils.cpp.
Referenced by affymetrix_calvin_utilities::DateTime::Date(), STLTrimRight(), and affymetrix_calvin_utilities::DateTime::Time().
void StringUtils::STLTrimRight (std::wstring & s, wchar_t chTarget) [static]
Trim chTarget from the right of string s.
Parameters:
s String from which to remove characters.
chTarget Character to trim.
Definition at line 95 of file StringUtils.cpp.
std::wstring StringUtils::ToString (int value, int digits, wchar_t fill = L'0') [static]
Convert an integer to a string.
Parameters:
value The integer
digits The number of digits for the resulting string
fill The value to fill in empty spaces.
Definition at line 139 of file StringUtils.cpp.
The documentation for this class was generated from the following files:
calvin_files/utils/src/StringUtils.h
calvin_files/utils/src/StringUtils.cpp