Affymetrix Power Tools: affymetrix_calvin_io::CHPQuantificationFileWriter Class Reference
affymetrix_calvin_io::CHPQuantificationFileWriter Class Reference
#include <CalvinCHPQuantificationFileWriter.h>
Public Member Functions
CHPQuantificationFileWriter (CHPQuantificationData &p)
~CHPQuantificationFileWriter ()
void WriteEntry (const affymetrix_calvin_data::ProbeSetQuantificationData &p)
void SeekToDataSet ()
Detailed Description
A class to write a quant CHP file.
Definition at line 35 of file CalvinCHPQuantificationFileWriter.h.
Constructor & Destructor Documentation
CHPQuantificationFileWriter::CHPQuantificationFileWriter (CHPQuantificationData & p)
Constructor
Parameters:
p Pointer to the quant CHP data object.
Definition at line 28 of file CalvinCHPQuantificationFileWriter.cpp.
References affymetrix_calvin_io::CHPQuantificationData::GetFileHeader(), and affymetrix_calvin_io::CHPQuantificationData::GetMaxProbeSetName().
CHPQuantificationFileWriter::~CHPQuantificationFileWriter ()
Destructor
Definition at line 35 of file CalvinCHPQuantificationFileWriter.cpp.
Member Function Documentation
void CHPQuantificationFileWriter::SeekToDataSet ()
Seeks to the data set.
Definition at line 59 of file CalvinCHPQuantificationFileWriter.cpp.
Referenced by QuantMethodExprCCCHPReport::prepare().
void CHPQuantificationFileWriter::WriteEntry (const affymetrix_calvin_data::ProbeSetQuantificationData & p)
Write an entry.
Parameters:
p A pointer to a quant entry.
Definition at line 66 of file CalvinCHPQuantificationFileWriter.cpp.
References affymetrix_calvin_data::_ProbeSetQuantificationData::id, affymetrix_calvin_data::_ProbeSetQuantificationData::name, and affymetrix_calvin_data::_ProbeSetQuantificationData::quantification.
Referenced by QuantMethodExprCCCHPReport::prepare().
The documentation for this class was generated from the following files:
calvin_files/writers/src/CalvinCHPQuantificationFileWriter.h
calvin_files/writers/src/CalvinCHPQuantificationFileWriter.cpp