Affymetrix Power Tools: QuantMethodRunReport Class Reference
QuantMethodRunReport Class Reference
Summarize and output basic statistics on the performance of a particular summarization or detection method across a number of cel files.
#include <QuantMethodRunReport.h>