Affymetrix Power Tools: affymetrix_calvin_io::GridControlFileWriter Class Reference
affymetrix_calvin_io::GridControlFileWriter Class Reference
#include <GridControlFileWriter.h>
Public Member Functions
GridControlFileWriter ()
~GridControlFileWriter ()
bool Write (const std::string &fileName, affymetrix_grid_control::GridControlData &data)
Detailed Description
This class provide write capabilities for GRC files.
Definition at line 40 of file GridControlFileWriter.h.
Constructor & Destructor Documentation
GridControlFileWriter::GridControlFileWriter ()
Constructor
Definition at line 37 of file GridControlFileWriter.cpp.
GridControlFileWriter::~GridControlFileWriter ()
Destructor
Definition at line 44 of file GridControlFileWriter.cpp.
Member Function Documentation
bool GridControlFileWriter::Write (const std::string & fileName, affymetrix_grid_control::GridControlData & data)
Write a new GRC file.
Parameters:
fileName The name of the GRC file.
data The grid control data to write to the file.
Returns:
True if successful.
Definition at line 51 of file GridControlFileWriter.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_io::DataSetHeader::AddUShortColumn(), affymetrix_calvin_io::DataSetHeader::Clear(), affymetrix_grid_control::GridControlData::GetB1(), affymetrix_grid_control::GridControlData::GetB2(), affymetrix_grid_control::GridControlData::GetColumns(), affymetrix_grid_control::GridControlData::GetNS(), affymetrix_grid_control::GridControlData::GetNumB1Probes(), affymetrix_grid_control::GridControlData::GetNumB2Probes(), affymetrix_grid_control::GridControlData::GetNumNSProbes(), affymetrix_grid_control::GridControlData::GetRows(), GRD_COLUMNS_PARAMETER_NAME, GRD_FILE_B1_SET_NAME, GRD_FILE_B2_SET_NAME, GRD_FILE_COORDINATE_GROUP_NAME, GRD_FILE_NS_SET_NAME, GRD_FILE_TYPE_IDENTIFIER, GRD_ROWS_PARAMETER_NAME, affymetrix_calvin_io::GenericDataHeader::SetFileId(), affymetrix_calvin_io::FileHeader::SetFilename(), affymetrix_calvin_io::GenericDataHeader::SetFileTypeId(), affymetrix_calvin_io::DataSetHeader::SetName(), affymetrix_calvin_io::DataGroupHeader::SetName(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), affymetrix_calvin_io::DataSetHeader::SetRowCnt(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueInt32(), affymetrix_grid_control::_FeatureCoordinate::x, and affymetrix_grid_control::_FeatureCoordinate::y.
The documentation for this class was generated from the following files:
calvin_files/writers/src/GridControlFileWriter.h
calvin_files/writers/src/GridControlFileWriter.cpp