Affymetrix Power Tools: affymetrix_calvin_utilities::DateTime Class Reference
affymetrix_calvin_utilities::DateTime Class Reference
#include <DateTime.h>
Public Member Functions
DateTime ()
~DateTime ()
std::wstring Date () const
void Date (std::wstring value)
std::wstring Time () const
void Time (std::wstring value)
void Clear ()
bool IsUTC ()
void UTC (bool value)
std::wstring ToString ()
Static Public Member Functions
static DateTime GetCurrentDateTime ()
static DateTime Parse (std::wstring value)
static std::wstring FormatDate (u_int32_t year, u_int32_t month, u_int32_t day)
static std::wstring FormatTime (u_int32_t hour, u_int32_t minute, u_int32_t second)
static std::wstring FormatDateTime (u_int32_t year, u_int32_t month, u_int32_t day, u_int32_t hour, u_int32_t minute, u_int32_t second, bool utc)
Static Protected Member Functions
static void CheckDateFormat (std::wstring &date)
static void CheckTimeFormat (std::wstring &time)
Protected Attributes
std::wstring affydate
std::wstring affytime
bool coordinateduniversaltime
Detailed Description
This class provides storage for a date and time object.
Definition at line 48 of file DateTime.h.
Constructor & Destructor Documentation
DateTime::DateTime ()
Constructor
Definition at line 42 of file DateTime.cpp.
References Clear().
DateTime::~DateTime ()
Destructor
Definition at line 50 of file DateTime.cpp.
Member Function Documentation
void DateTime::CheckDateFormat (std::wstring & date) [static, protected]
Check the date format and may modify it.
Parameters:
date The formatted date string.
Exceptions:
FormatException
Definition at line 232 of file DateTime.cpp.
References FormatDate(), GetCurrentDateTime(), and ToString().
Referenced by Parse().
void DateTime::CheckTimeFormat (std::wstring & time) [static, protected]
Check the itme format.
Parameters:
time The formatted time string.
Exceptions:
FormatException
Definition at line 253 of file DateTime.cpp.
References GetCurrentDateTime(), and ToString().
Referenced by Parse().
void DateTime::Clear (void)
Clears the members.
Definition at line 57 of file DateTime.cpp.
References affydate, affytime, and coordinateduniversaltime.
Referenced by affymetrix_calvin_array::ArrayAuditEntry::Clear(), DateTime(), and affymetrix_calvin_io::AuditFileReader::Read().
std::wstring DateTime::Date () const
The date.
Returns:
The date.
Definition at line 68 of file DateTime.cpp.
References affydate.
Referenced by GetCurrentDateTime(), Parse(), affymetrix_calvin_io::AuditFileReader::Read(), ToString(), and affymetrix_calvin_io::AuditFileWriter::Write().
void DateTime::Date (std::wstring value)
Set the date.
Parameters:
value The new date.
Set the date.
Definition at line 76 of file DateTime.cpp.
References affydate, affymetrix_calvin_utilities::StringUtils::STLTrimLeft(), and affymetrix_calvin_utilities::StringUtils::STLTrimRight().
std::wstring DateTime::FormatDate (u_int32_t year, u_int32_t month, u_int32_t day) [static]
Get a properly formatted Date string.
Parameters:
year A four digit year.
month A one-based month of the year.
day A one-based day of month
Returns:
A properly formatted date string.
Definition at line 201 of file DateTime.cpp.
References FormatString3.
Referenced by CheckDateFormat(), and FormatDateTime().
std::wstring DateTime::FormatDateTime (u_int32_t year, u_int32_t month, u_int32_t day, u_int32_t hour, u_int32_t minute, u_int32_t second, bool utc) [static]
Get a properly formatted date-time string.
Parameters:
year A four digit year.
month A one-based month of the year.
day A one-based day of month
hour Zero-based hour of day.
minute Zero-based minute of hour.
second Zero-based second of minute.
utc Indicates if the time is Universal Coordinated Time.
Returns:
A properly formatted date-time string.
Definition at line 221 of file DateTime.cpp.
References DATETIME_SEPERATOR_FORMAT_SPECIFIER, FormatDate(), and FormatTime().
std::wstring DateTime::FormatTime (u_int32_t hour, u_int32_t minute, u_int32_t second) [static]
Get a properly formatted Time string.
Parameters:
hour Zero-based hour of day.
minute Zero-based minute of hour.
second Zero-based second of minute.
Returns:
A properly formatted time string.
Definition at line 211 of file DateTime.cpp.
References FormatString3.
Referenced by FormatDateTime().
DateTime DateTime::GetCurrentDateTime () [static]
Gets the current date and time.
Returns:
The current date and time.
Definition at line 107 of file DateTime.cpp.
References Date(), DATEFORMAT, Time(), and TIMEFORMAT.
Referenced by affymetrix_fusion_io::FusionCHPHeader::CheckAdapter(), affymetrix_fusion_io::FusionCELData::CheckAdapter(), CheckDateFormat(), affymetrix_calvin_io::DataSet::CheckRowColumnAndType(), CheckTimeFormat(), affymetrix_calvin_io::TextFileWriter::CloseFile(), affymetrix_fusion_io::FusionCELData::CreateAdapter(), affymetrix_calvin_io::GenericData::DataGroup(), affymetrix_calvin_io::GenericData::DataSet(), affymetrix_calvin_io::DataGroup::DataSet(), affymetrix_calvin_io::GenericData::DataSetCnt(), affymetrix_calvin_io::GenericData::DataSetNames(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::DefaultValueToInt(), affymetrix_calvin_io::DataSet::FilePosition(), affymetrix_calvin_io::GenericFileReader::GetDataGroupReader(), affymetrix_calvin_io::DataGroupReader::GetDataSetReader(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::GetDefaultValueAscii(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::GetDefaultValueFloat(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::GetDefaultValueText(), affymetrix_calvin_io::CDFData::GetProbeSetInformation(), affymetrix_calvin_io::CDFData::GetProbeSetName(), affymetrix_calvin_io::CDFData::GetQCProbeSetInformation(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_io::GenericFileReader::Open(), affymetrix_calvin_io::TextFileWriter::OpenFile(), affymetrix_calvin_io::GenericFileReader::OpenFile(), affymetrix_calvin_io::GenericData::OpenFStream(), Parse(), affymetrix_calvin_io::GridControlFileReader::Read(), affymetrix_calvin_io::TextFileReader::ReadFile(), affymetrix_calvin_io::FileHeaderReader::ReadMagicNumber(), affymetrix_calvin_io::FileHeaderReader::ReadVersion(), ToString(), and affymetrix_calvin_parameter::ParameterNameValueType::ValueToInt().
bool DateTime::IsUTC ()
Gets whether or not the DateTime object time value is UTC or not.
Returns:
UTC or not.
Definition at line 136 of file DateTime.cpp.
References coordinateduniversaltime.
DateTime DateTime::Parse (std::wstring value) [static]
Converts the string into a DateTime.
Parameters:
value A wstring containing the date and time to convert. The format must match that returned by ToString().
Returns:
A DateTime equivalent to the date and time in value.
Exceptions:
FormatException
Definition at line 159 of file DateTime.cpp.
References CheckDateFormat(), CheckTimeFormat(), coordinateduniversaltime, Date(), DATETIME_SEPERATOR_FORMAT_SPECIFIER, GetCurrentDateTime(), Time(), ToString(), and ZULU_FORMAT_SPECIFIER.
void DateTime::Time (std::wstring value)
Set the time.
Parameters:
value The new time.
Set the time.
Definition at line 95 of file DateTime.cpp.
References affytime, affymetrix_calvin_utilities::StringUtils::STLTrimLeft(), and affymetrix_calvin_utilities::StringUtils::STLTrimRight().
std::wstring DateTime::Time () const
The time.
Returns:
The time.
Definition at line 87 of file DateTime.cpp.
References affytime.
Referenced by GetCurrentDateTime(), Parse(), affymetrix_calvin_io::AuditFileReader::Read(), ToString(), and affymetrix_calvin_io::AuditFileWriter::Write().
std::wstring DateTime::ToString ()
Gets the current date and time and concatinates both together.
Returns:
The string representation of the date and time.
Definition at line 141 of file DateTime.cpp.
References affydate, affytime, coordinateduniversaltime, Date(), DATETIME_SEPERATOR_FORMAT_SPECIFIER, GetCurrentDateTime(), and Time().
Referenced by CheckDateFormat(), CheckTimeFormat(), Parse(), and affymetrix_calvin_io::DATData::SetScanDate().
void affymetrix_calvin_utilities::DateTime::UTC (bool value) [inline]
Sets if the DateTime is UTC or not.
Parameters:
value True if the DateTime should be considered UTC.
Definition at line 108 of file DateTime.h.
References coordinateduniversaltime.
Member Data Documentation
std::wstring affymetrix_calvin_utilities::DateTime::affydate [protected]
The date
Definition at line 59 of file DateTime.h.
Referenced by Clear(), Date(), and ToString().
std::wstring affymetrix_calvin_utilities::DateTime::affytime [protected]
The time
Definition at line 62 of file DateTime.h.
Referenced by Clear(), Time(), and ToString().
bool affymetrix_calvin_utilities::DateTime::coordinateduniversaltime [protected]
indicates if the time falue is UTC
Definition at line 65 of file DateTime.h.
Referenced by Clear(), IsUTC(), Parse(), ToString(), and UTC().
The documentation for this class was generated from the following files:
calvin_files/utils/src/DateTime.h
calvin_files/utils/src/DateTime.cpp