Affymetrix Power Tools: affymetrix_calvin_io::CHPQuantificationFileBufferWriter Class Reference
affymetrix_calvin_io::CHPQuantificationFileBufferWriter Class Reference
Public Member Functions
CHPQuantificationFileBufferWriter ()
~CHPQuantificationFileBufferWriter ()
void SetMaxBufferSize (int MaxBufferSize)
void Cleanup ()
void Initialize (std::vector< std::string > *CHPFileNames)
void WriteQuantificationEntry (int target, float quantification)
void FlushBuffer ()
Detailed Description
Definition at line 41 of file CalvinCHPQuantificationFileBufferWriter.h.
Constructor & Destructor Documentation
CHPQuantificationFileBufferWriter::CHPQuantificationFileBufferWriter ()
Constructor
Definition at line 36 of file CalvinCHPQuantificationFileBufferWriter.cpp.
CHPQuantificationFileBufferWriter::~CHPQuantificationFileBufferWriter ()
Destructor
Definition at line 42 of file CalvinCHPQuantificationFileBufferWriter.cpp.
References Cleanup(), and FlushBuffer().
Member Function Documentation
void CHPQuantificationFileBufferWriter::Cleanup ()
Cleans up memory
Definition at line 48 of file CalvinCHPQuantificationFileBufferWriter.cpp.
Referenced by Initialize(), and ~CHPQuantificationFileBufferWriter().
void CHPQuantificationFileBufferWriter::FlushBuffer ()
Write the content of the buffer to CHP files.
Definition at line 80 of file CalvinCHPQuantificationFileBufferWriter.cpp.
References affymetrix_calvin_io::CalvinCHPFileUpdater::CloseCHPFile(), affymetrix_calvin_io::CalvinCHPFileUpdater::OpenCHPFile(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantificationBuffer().
Referenced by QuantMethodExprCCCHPReport::finish(), WriteQuantificationEntry(), and ~CHPQuantificationFileBufferWriter().
void CHPQuantificationFileBufferWriter::Initialize (std::vector< std::string > * CHPFileNames)
Initialize quantification buffer writer
Parameters:
CHPFileNames Reference to a list of CHP file names.
Definition at line 57 of file CalvinCHPQuantificationFileBufferWriter.cpp.
References Cleanup().
Referenced by QuantMethodExprCCCHPReport::prepare().
void affymetrix_calvin_io::CHPQuantificationFileBufferWriter::SetMaxBufferSize (int MaxBufferSize) [inline]
Set maximum buffer size
Definition at line 51 of file CalvinCHPQuantificationFileBufferWriter.h.
void CHPQuantificationFileBufferWriter::WriteQuantificationEntry (int target, float quantification)
Write a quantification entry to buffer. If the buffer is full, flush it.
Parameters:
target Target for the quantification entry.
quantification Value for the quantification entry.
Definition at line 70 of file CalvinCHPQuantificationFileBufferWriter.cpp.
References FlushBuffer().
Referenced by QuantMethodExprCCCHPReport::report(), and QuantMethodExprCCCHPReport::reportFailure().
The documentation for this class was generated from the following files:
calvin_files/writers/src/CalvinCHPQuantificationFileBufferWriter.h
calvin_files/writers/src/CalvinCHPQuantificationFileBufferWriter.cpp