Affymetrix Power Tools: SketchQuantNormTran Class Reference
SketchQuantNormTran Class Reference
SketchQuantNormTran for doing normalization.
#include <SketchQuantNormTran.h>