Affymetrix Power Tools: CallSet Class Reference
CallSet Class Reference
Public Member Functions
CallSet (const std::string &name="", const int &columnInTranslationTable=-1)
CallSet::CallSet Synopsis.
CallSet (const class RunTimeEnvironment &rte, class GenotypeTableModel &gtm, const CallSet &referenceSet, const int chromaTid)
CallSet::CallSet Synopsis:
bool addCallElement (class TranslationTableModel &ttm, const int row, const int base_column, const bool allowMultiAllelic=false, const bool isHaplotype=false)
CallSet::addCallElement Synopsis:
CallSet buildSecondSet (const RunTimeEnvironment &rte, const CallSet &chromatid1, const CallSet &chromatid2) const
CallSet::buildSecondSet Synopsis:
void clear ()
CallSet::clear.
bool contains (const CallSet &c) const
CallSet::contains(CallSet) Synopsis.
bool contains (const CallElement &ce) const
CallSet::contains(CallElement) Synopsis:
void describeVerbose (ADT_VERBOSE_ENUM level) const
CallSet::describeVerbose.
void describeVerbose (const RunTimeEnvironment &rte, ADT_VERBOSE_ENUM override=ADT_VERBOSE_NULL) const
CallSet::describeVerbose.
ADT_CALL_TYPE_ENUM getCallType () const
inline
std::string getMarkerProbeSet () const
CallSet::getMarkerProbeSet Synopsis.
const CallElement & getProbeSetCallElement (const std::string &probeSet) const
CallSet::getProbeSetCallElement Synopsis:
bool hasProbeSet (const std::string &probeSet) const
CallSet::hasProbeSet Synopsis:
bool hasWildCards () const
inline
bool isEmpty () const
inline
bool match (const CallSet &a, const CallSet &b) const
CallSet::match Synopsis:
int numWildCards () const
CallSet::numWildCars Synopsis:
bool operator== (const CallSet &cs) const
CallSet::operator==.
bool operator!= (const CallSet &cs) const
inline
int size () const
inline
Detailed Description
Definition at line 46 of file CallSet.h.
Constructor & Destructor Documentation
CallSet::CallSet (const std::string & name = "", const int & columnInTranslationTable = -1)
CallSet::CallSet Synopsis.
1.) Default constructor for STL containers. 2.) Translation table constructor used in "TranslationTable.cpp".
Parameters:
name - the allele or marker name "*1".
columnInTranslationTable - A1-ANN index, "Ref" or "Var" index for markers.
Definition at line 53 of file CallSet.cpp.
CallSet::CallSet (const class RunTimeEnvironment & rte, class GenotypeTableModel & gtm, const CallSet & referenceSet, const int chromaTid)
CallSet::CallSet Synopsis:
Constructor for CHP experiment data to be compared with translation table call sets instantiated with the other constructor. A call set represents one of two possible chromatids.
The GenoTypeTableModel experiment data from the CHP file is passed in preconfigured to a projection of sorted markers for one particular gene. Further the reference set represents all the probesets (markers) to be included for this gene call set. For a SNP, all the gene markers are scanned but only one is used. If a haplotype group for, say, "*7", requires six markers then all gene markers are scanned and only the six are used.
This constructor could be improved by building a probe set index (std::map) in the GenotypeTableModel.
Parameters:
rte - The single instance RunTimeEnvironment
gtm - The single instance experiment model
referenceSet - The reference set of accepted probeSets for this experiment gene (from the Translation Table).
chromoTid - 1 or 2.
Definition at line 93 of file CallSet.cpp.
References APT_ERR_ASSERT, getCallType(), GenotypeTableModel::getGeneRow(), GenotypeTableModel::getGeneRowSize(), hasProbeSet(), hasWildCards(), and CallElement::isWildCardBase().
Member Function Documentation
bool CallSet::addCallElement (class TranslationTableModel & ttm, const int row, const int base_column, const bool allowMultiAllelic = false, const bool isHaplotype = false)
CallSet::addCallElement Synopsis:
Given a row from the Translation Table, adds a CallElement ProbeSet/base pair to the CallSet. The element added will correspond to the passed in name (take from columns A1-ANN) unless reference is specified.
Returns false if the set element being added is a duplicate.
Parameters:
ttm - TranslationTableModel raw data that mirors the input TsvFile.
row - the row in question.
base_column - the Allele Name column or Reference column.
allowMultiAllelic - if the element already exists treat the duplicate ProbeSet as multiAllelic.
Returns:
true/false - true if successful
Definition at line 188 of file CallSet.cpp.
References CallElement::addBase(), APT_ERR_ASSERT, TranslationInputTsvTableModel::columnCount(), contains(), TranslationTableModel::getColumnIndex(), and CallElement::isWildCardBase().
Referenced by CallSetTest::addCallElement().
CallSet CallSet::buildSecondSet (const RunTimeEnvironment & rte, const CallSet & chromatid1, const CallSet & chromatid2) const
CallSet::buildSecondSet Synopsis:
A method used for translation. The idea is that during translation alleles in the two chromatid CallSets can be mixed and matched. One allele from chromatid 1, the rest from chromatid2 for example. This combination is instantiated as a CallSet. This method is invoked on the combination CallSet and then the difference between the elments in this set and the initial chromatid1 and chromatid2 sets is return.
In other words, given a matched allele set from any combination of probeSet/bases from the two chromatid experiment sets for a gene, then constructs difference "second" set using the components of both not found in the matched set.
Parameters:
rte - the single instance of the run time enviroment
chromatid1 - from the Genotype experiment data set.
chromatid2 - from the Genotype experiment data set.
Definition at line 264 of file CallSet.cpp.
References APT_ERR_ASSERT, and size().
Referenced by GeneCall::translateExperimentCall().
void CallSet::clear ()
CallSet::clear.
Re-iniatialize the CallSet to default conditions.
Definition at line 324 of file CallSet.cpp.
bool CallSet::contains (const CallSet & c) const
CallSet::contains(CallSet) Synopsis.
A set operator. Detemine if all the CallElements of a CallSet are all contained within the one being interogated. Calls the "contains" operator of each CallElement. See CallSet::contains(CallElement).
Parameters:
c - the presumed subset.
Returns:
true - if c is contained in this CallSet.
Definition at line 352 of file CallSet.cpp.
Referenced by addCallElement().
bool CallSet::contains (const CallElement & ce) const
CallSet::contains(CallElement) Synopsis:
If a CallElement has the same name and the CallElement::operator== matches one in this CallSet then the CallElement is said to be contained.
Primarily used in CallSet::contains(CallSet)
Parameters:
ce - the CallElement to compare with this CallSet's own list.
Returns:
true - if contained
Definition at line 387 of file CallSet.cpp.
void CallSet::describeVerbose (ADT_VERBOSE_ENUM level) const
CallSet::describeVerbose.
Run time debug routine that can be invoked with various verbose levels. ADT_VERBOSE_INPUT_FILES is the default level.
Parameters:
level - ADT_VERBOSE_INPUT_FILES by default otherwise the ADT_VERBOSE_ENUM level to output
Definition at line 448 of file CallSet.cpp.
References Verbose::out().
Referenced by describeVerbose(), and GeneCall::translateExperimentCall().
void CallSet::describeVerbose (const RunTimeEnvironment & rte, ADT_VERBOSE_ENUM override = ADT_VERBOSE_NULL) const
CallSet::describeVerbose.
Run time debug routine that can be invoked with various verbose levels. ADT_VERBOSE_INPUT_FILES is the default level.
Parameters:
rte - run time environment
override - ADT_VERBOSE_INPUT_FILES by default, otherwise the ADT_VERBOSE_ENUM level to output
Definition at line 421 of file CallSet.cpp.
References describeVerbose().
std::string CallSet::getMarkerProbeSet () const
CallSet::getMarkerProbeSet Synopsis.
A convienance method that takes advantage of the fact that a marker will have only one item in the set and hence just returns the first CallElement's name (probeSet id).
It is an exception to call this API on a non-ADT_CALL_TYPE_MARKER CallSet.
Returns:
probeSet - the probeSet name of the first element in the ceSet.
Definition at line 546 of file CallSet.cpp.
References APT_ERR_ASSERT, and getCallType().
const CallElement & CallSet::getProbeSetCallElement (const std::string & probeSet) const
CallSet::getProbeSetCallElement Synopsis:
A selector to detemine if the set of CallElements contains a particular ProbeSet and if so then return a reference to the matching CallElement.
Parameters:
probeSet - the probeSet (marker) in question
Returns:
true - if the ProbeSet std::string passed in is in the m_ceSet.
Definition at line 506 of file CallSet.cpp.
References APT_ERR_ASSERT, and hasProbeSet().
bool CallSet::hasProbeSet (const std::string & probeSet) const
CallSet::hasProbeSet Synopsis:
Detemine if the set of CallElements contains a particular ProbeSet.
Parameters:
probeSet - the probeSet in question
Returns:
true - if the ProbeSet std::string passed in is in the m_ceSet.
Definition at line 572 of file CallSet.cpp.
Referenced by CallSet(), and getProbeSetCallElement().
bool CallSet::match (const CallSet & a, const CallSet & b) const
CallSet::match Synopsis:
The heart of the translation process deep in the guts of GeneCall::translate. Detemine if the CallSet can match any combination of CallElements given a pair of chromatid CallSets.
If a translation table CallSet matches some combination of chromatid1 and chromatid2 experiment data CallSet then a match is made. Then a call to CallSet::buildSecondSet is made and the diffenerce is matched to any of the remaining translation table CallSets for for this gene. If not than an "UNK" determination is made.
Parameters:
a - chromatid1 from the CHP
b - chromatid2 from the CHP
Returns:
true - if a combination can be made.
Definition at line 608 of file CallSet.cpp.
References APT_ERR_ASSERT.
Referenced by GeneCall::translateExperimentCall().
int CallSet::numWildCards () const
CallSet::numWildCars Synopsis:
Count the number of wildcard CallElements within the CallSet.
Returns:
numWildCards
Definition at line 646 of file CallSet.cpp.
bool CallSet::operator== (const CallSet & c) const
CallSet::operator==.
Essentially just walk the list of CallElements and comparing all for equality, with some added business rules for Copy Number.
Parameters:
c - The CallSet to compare.
Returns:
true - if the CallSets are "equal".
Definition at line 679 of file CallSet.cpp.
References size().
The documentation for this class was generated from the following files:
translation/CallSet.h
translation/CallSet.cpp