Affymetrix Power Tools: CNFamilialAnalysisMethodSegmentOverlap Class Reference
CNFamilialAnalysisMethodSegmentOverlap Class Reference
The SegmentOverlap Familial analysis method.
#include <CNFamilialAnalysisMethodSegmentOverlap.h>