Affymetrix Power Tools: QuantAvgDiff Class Reference
QuantAvgDiff Class Reference
Class for doing MAS 4 average difference signal estimation.
#include <QuantAvgDiff.h>