Affymetrix Power Tools: ChipStream Class Reference
ChipStream Class Reference
ChipStream - base class for objects that can initialize themselves one at a time and transform intensity data.
#include <ChipStream.h>