Affymetrix Power Tools: affymetrix_calvin_template::TemplateData Class Reference
affymetrix_calvin_template::TemplateData Class Reference
#include <TemplateData.h>
Public Member Functions
TemplateData ()
~TemplateData ()
affymetrix_calvin_utilities::AffymetrixGuidType & TemplateFileIdentifier ()
affymetrix_calvin_utilities::AffymetrixGuidType & DataTypeIdentifier ()
std::wstring & CreationDateTime ()
std::wstring & CreatedBy ()
affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredTypeList & UserAttributes ()
void Clear ()
Protected Attributes
affymetrix_calvin_utilities::AffymetrixGuidType fileId
affymetrix_calvin_utilities::AffymetrixGuidType dataTypeId
std::wstring creationDateTime
std::wstring createdBy
affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredTypeList userAttributes
Detailed Description
This class provides interfaces to store array template information.
Definition at line 39 of file TemplateData.h.
Constructor & Destructor Documentation
TemplateData::TemplateData ()
Constructor
Definition at line 29 of file TemplateData.cpp.
TemplateData::~TemplateData ()
Destructor
Definition at line 36 of file TemplateData.cpp.
References Clear().
Member Function Documentation
void TemplateData::Clear (void)
Clears the member objects.
Definition at line 44 of file TemplateData.cpp.
References createdBy, creationDateTime, dataTypeId, fileId, and userAttributes.
Referenced by affymetrix_calvin_io::TemplateFileReader::Read(), and ~TemplateData().
std::wstring& affymetrix_calvin_template::TemplateData::CreatedBy () [inline]
The user who created the data object.
Returns:
The user name.
Definition at line 84 of file TemplateData.h.
References createdBy.
std::wstring& affymetrix_calvin_template::TemplateData::CreationDateTime () [inline]
The date and time of initial creation.
Returns:
The creation date and time.
Definition at line 79 of file TemplateData.h.
References creationDateTime.
affymetrix_calvin_utilities::AffymetrixGuidType& affymetrix_calvin_template::TemplateData::DataTypeIdentifier () [inline]
The identifier of the type of data stored in the file.
Returns:
The identifier of the type of data.
Definition at line 74 of file TemplateData.h.
References dataTypeId.
Referenced by affymetrix_calvin_io::TemplateFileReader::DataTypeIdentifier().
affymetrix_calvin_utilities::AffymetrixGuidType& affymetrix_calvin_template::TemplateData::TemplateFileIdentifier () [inline]
The unique idendifier for the array set.
Returns:
The unique idendifier for the array set.
Definition at line 69 of file TemplateData.h.
References fileId.
affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredTypeList& affymetrix_calvin_template::TemplateData::UserAttributes () [inline]
The user attributes.
Returns:
The vector of user attributes.
Definition at line 89 of file TemplateData.h.
References userAttributes.
Referenced by affymetrix_calvin_io::SAXTemplateHandlers::characters().
Member Data Documentation
std::wstring affymetrix_calvin_template::TemplateData::createdBy [protected]
The user who created the data object.
Definition at line 59 of file TemplateData.h.
Referenced by Clear(), and CreatedBy().
std::wstring affymetrix_calvin_template::TemplateData::creationDateTime [protected]
The date and time of initial creation.
Definition at line 56 of file TemplateData.h.
Referenced by Clear(), and CreationDateTime().
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_calvin_template::TemplateData::dataTypeId [protected]
An identifier to the type of data stored in the file
Definition at line 53 of file TemplateData.h.
Referenced by Clear(), and DataTypeIdentifier().
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_calvin_template::TemplateData::fileId [protected]
A unique idendifier for the array set object
Definition at line 50 of file TemplateData.h.
Referenced by Clear(), and TemplateFileIdentifier().
affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredTypeList affymetrix_calvin_template::TemplateData::userAttributes [protected]
The user attributes
Definition at line 62 of file TemplateData.h.
Referenced by Clear(), and UserAttributes().
The documentation for this class was generated from the following files:
calvin_files/template/src/TemplateData.h
calvin_files/template/src/TemplateData.cpp