Affymetrix Power Tools: affymetrix_grid_control::GridControlData Class Reference
affymetrix_grid_control::GridControlData Class Reference
#include <GridControlData.h>
Public Member Functions
GridControlData ()
~GridControlData ()
int GetRows () const
void SetRows (int rows)
int GetColumns () const
void SetColumns (int columns)
void ResizeB1 (int size)
void ResizeB2 (int size)
void ResizeNS (int size)
void SetB1 (int index, FeatureCoordinate coord)
FeatureCoordinate GetB1 (int index) const
int GetNumB1Probes () const
void SetB2 (int index, FeatureCoordinate coord)
FeatureCoordinate GetB2 (int index) const
int GetNumB2Probes () const
void SetNS (int index, FeatureCoordinate coord)
FeatureCoordinate GetNS (int index) const
int GetNumNSProbes () const
void Clear ()
Protected Attributes
std::vector< FeatureCoordinate > probesB1
std::vector< FeatureCoordinate > probesB2
std::vector< FeatureCoordinate > probesNS
int arrayColumns
int arrayRows
Detailed Description
This class provides interfaces to store GRC file information.
Definition at line 47 of file GridControlData.h.
Constructor & Destructor Documentation
affymetrix_grid_control::GridControlData::GridControlData () [inline]
Constructor
Definition at line 51 of file GridControlData.h.
affymetrix_grid_control::GridControlData::~GridControlData () [inline]
Destructor
Definition at line 54 of file GridControlData.h.
References Clear().
Member Function Documentation
void affymetrix_grid_control::GridControlData::Clear (void) [inline]
Clears the member objects.
Definition at line 160 of file GridControlData.h.
References arrayColumns, arrayRows, probesB1, probesB2, and probesNS.
Referenced by affxgrc::CGRCFileWriter::ParseLibData(), affxgrc::CGRCFileData::Read(), affymetrix_calvin_io::GridControlFileReader::Read(), and ~GridControlData().
FeatureCoordinate affymetrix_grid_control::GridControlData::GetB1 (int index) const [inline]
Gets the B1 probe at the given index.
Parameters:
index The index of the array.
Returns:
coord The coordinate.
Definition at line 118 of file GridControlData.h.
References probesB1.
Referenced by affymetrix_calvin_io::GridControlFileWriter::Write(), and affxgrc::CGRCFileWriter::WriteFile().
FeatureCoordinate affymetrix_grid_control::GridControlData::GetB2 (int index) const [inline]
Gets the B2 probe at the given index.
Parameters:
index The index of the array.
Returns:
coord The coordinate.
Definition at line 135 of file GridControlData.h.
References probesB2.
Referenced by affymetrix_calvin_io::GridControlFileWriter::Write(), and affxgrc::CGRCFileWriter::WriteFile().
int affymetrix_grid_control::GridControlData::GetColumns () const [inline]
Gets the number of columns.
Returns:
The number of columns.
Definition at line 86 of file GridControlData.h.
References arrayColumns.
Referenced by affxgrc::CGRCFileData::ReadPreReleaseFormat(), affymetrix_calvin_io::GridControlFileWriter::Write(), and affxgrc::CGRCFileWriter::WriteFile().
FeatureCoordinate affymetrix_grid_control::GridControlData::GetNS (int index) const [inline]
Gets the NS probe at the given index.
Parameters:
index The index of the array.
Returns:
coord The coordinate.
Definition at line 152 of file GridControlData.h.
References probesNS.
Referenced by affymetrix_calvin_io::GridControlFileWriter::Write(), and affxgrc::CGRCFileWriter::WriteFile().
int affymetrix_grid_control::GridControlData::GetNumB1Probes () const [inline]
Gets the number of B1 probes.
Returns:
The number of B1 probes.
Definition at line 123 of file GridControlData.h.
References probesB1.
Referenced by affxgrc::CGRCFileData::ReadPreReleaseFormat(), affxgrc::CGRCFileData::ReadReleaseFormat(), affxgrc::CGRCFileWriter::SetB1(), affymetrix_calvin_io::GridControlFileWriter::Write(), and affxgrc::CGRCFileWriter::WriteFile().
int affymetrix_grid_control::GridControlData::GetNumB2Probes () const [inline]
Gets the number of B2 probes.
Returns:
The number of B2 probes.
Definition at line 140 of file GridControlData.h.
References probesB2.
Referenced by affxgrc::CGRCFileData::ReadPreReleaseFormat(), affxgrc::CGRCFileData::ReadReleaseFormat(), affxgrc::CGRCFileWriter::SetB2(), affymetrix_calvin_io::GridControlFileWriter::Write(), and affxgrc::CGRCFileWriter::WriteFile().
int affymetrix_grid_control::GridControlData::GetNumNSProbes () const [inline]
Gets the number of NS probes.
Returns:
The number of NS probes.
Definition at line 157 of file GridControlData.h.
References probesNS.
Referenced by affxgrc::CGRCFileData::ReadPreReleaseFormat(), affxgrc::CGRCFileData::ReadReleaseFormat(), affxgrc::CGRCFileWriter::SetNS(), affymetrix_calvin_io::GridControlFileWriter::Write(), and affxgrc::CGRCFileWriter::WriteFile().
int affymetrix_grid_control::GridControlData::GetRows () const [inline]
Gets the number of rows.
Returns:
The number of rows.
Definition at line 76 of file GridControlData.h.
References arrayRows.
Referenced by affxgrc::CGRCFileData::ReadPreReleaseFormat(), affymetrix_calvin_io::GridControlFileWriter::Write(), and affxgrc::CGRCFileWriter::WriteFile().
void affymetrix_grid_control::GridControlData::ResizeB1 (int size) [inline]
Resizes the B1 array.
Parameters:
size The size of the array.
Definition at line 96 of file GridControlData.h.
References probesB1.
Referenced by affxgrc::CGRCFileWriter::ParseLibData(), affymetrix_calvin_io::GridControlFileReader::Read(), affxgrc::CGRCFileData::ReadPreReleaseFormat(), affxgrc::CGRCFileData::ReadReleaseFormat(), and affxgrc::CGRCFileWriter::ResizeB1().
void affymetrix_grid_control::GridControlData::ResizeB2 (int size) [inline]
Resizes the B2 array.
Parameters:
size The size of the array.
Definition at line 101 of file GridControlData.h.
References probesB2.
Referenced by affxgrc::CGRCFileWriter::ParseLibData(), affymetrix_calvin_io::GridControlFileReader::Read(), affxgrc::CGRCFileData::ReadPreReleaseFormat(), affxgrc::CGRCFileData::ReadReleaseFormat(), and affxgrc::CGRCFileWriter::ResizeB2().
void affymetrix_grid_control::GridControlData::ResizeNS (int size) [inline]
Resizes the NS array.
Parameters:
size The size of the array.
Definition at line 106 of file GridControlData.h.
References probesNS.
Referenced by affxgrc::CGRCFileWriter::ParseLibData(), affymetrix_calvin_io::GridControlFileReader::Read(), affxgrc::CGRCFileData::ReadPreReleaseFormat(), affxgrc::CGRCFileData::ReadReleaseFormat(), and affxgrc::CGRCFileWriter::ResizeNS().
void affymetrix_grid_control::GridControlData::SetB1 (int index, FeatureCoordinate coord) [inline]
Sets the B1 probe at the given index.
Parameters:
index The index of the array.
coord The new coordinate.
Definition at line 112 of file GridControlData.h.
References probesB1.
Referenced by affxgrc::CGRCFileWriter::ParseLibData(), affymetrix_calvin_io::GridControlFileReader::Read(), affxgrc::CGRCFileData::ReadPreReleaseFormat(), affxgrc::CGRCFileData::ReadReleaseFormat(), and affxgrc::CGRCFileWriter::SetB1().
void affymetrix_grid_control::GridControlData::SetB2 (int index, FeatureCoordinate coord) [inline]
Sets the B2 probe at the given index.
Parameters:
index The index of the array.
coord The new coordinate.
Definition at line 129 of file GridControlData.h.
References probesB2.
Referenced by affxgrc::CGRCFileWriter::ParseLibData(), affymetrix_calvin_io::GridControlFileReader::Read(), affxgrc::CGRCFileData::ReadPreReleaseFormat(), affxgrc::CGRCFileData::ReadReleaseFormat(), and affxgrc::CGRCFileWriter::SetB2().
void affymetrix_grid_control::GridControlData::SetColumns (int columns) [inline]
Sets the number of columns.
Parameters:
columns The number of columns.
Definition at line 91 of file GridControlData.h.
References arrayColumns.
Referenced by affxgrc::CGRCFileWriter::ParseLibData(), affymetrix_calvin_io::GridControlFileReader::Read(), affxgrc::CGRCFileData::ReadPreReleaseFormat(), affxgrc::CGRCFileData::ReadReleaseFormat(), and affxgrc::CGRCFileWriter::SetColumns().
void affymetrix_grid_control::GridControlData::SetNS (int index, FeatureCoordinate coord) [inline]
Sets the NS probe at the given index.
Parameters:
index The index of the array.
coord The new coordinate.
Definition at line 146 of file GridControlData.h.
References probesNS.
Referenced by affxgrc::CGRCFileWriter::ParseLibData(), affymetrix_calvin_io::GridControlFileReader::Read(), affxgrc::CGRCFileData::ReadPreReleaseFormat(), affxgrc::CGRCFileData::ReadReleaseFormat(), and affxgrc::CGRCFileWriter::SetNS().
void affymetrix_grid_control::GridControlData::SetRows (int rows) [inline]
Sets the number of rows.
Parameters:
rows The number of rows.
Definition at line 81 of file GridControlData.h.
References arrayRows.
Referenced by affxgrc::CGRCFileWriter::ParseLibData(), affymetrix_calvin_io::GridControlFileReader::Read(), affxgrc::CGRCFileData::ReadPreReleaseFormat(), affxgrc::CGRCFileData::ReadReleaseFormat(), and affxgrc::CGRCFileWriter::SetRows().
Member Data Documentation
int affymetrix_grid_control::GridControlData::arrayColumns [protected]
The number of columns of features on the array
Definition at line 67 of file GridControlData.h.
Referenced by Clear(), GetColumns(), and SetColumns().
int affymetrix_grid_control::GridControlData::arrayRows [protected]
The number of rows of features on the array
Definition at line 70 of file GridControlData.h.
Referenced by Clear(), GetRows(), and SetRows().
std::vector<FeatureCoordinate> affymetrix_grid_control::GridControlData::probesB1 [protected]
An array of coordinates for the B1 probes.
Definition at line 54 of file GridControlData.h.
Referenced by Clear(), GetB1(), GetNumB1Probes(), ResizeB1(), and SetB1().
std::vector<FeatureCoordinate> affymetrix_grid_control::GridControlData::probesB2 [protected]
An array of coordinates for the B2 probes.
Definition at line 61 of file GridControlData.h.
Referenced by Clear(), GetB2(), GetNumB2Probes(), ResizeB2(), and SetB2().
std::vector<FeatureCoordinate> affymetrix_grid_control::GridControlData::probesNS [protected]
An array of coordinates for the non-synthesized features.
Definition at line 64 of file GridControlData.h.
Referenced by Clear(), GetNS(), GetNumNSProbes(), ResizeNS(), and SetNS().
The documentation for this class was generated from the following file:
file/GridControlData.h