Affymetrix Power Tools: QuantMethodReport Class Reference
QuantMethodReport Class Reference
Class for reporting results of quantification methods.
#include <QuantMethodReport.h>