Affymetrix Power Tools: SignalBackgroundCelListener Class Reference
SignalBackgroundCelListener Class Reference
Class for computing hilo qc metric from a cel set of cel files.
#include <SignalBackgroundCelListener.h>