Affymetrix Power Tools: affxmdl::CMDLFileHeader Class Reference
affxmdl::CMDLFileHeader Class Reference
#include <MDLFileData.h>
Public Member Functions
CMDLFileHeader & operator= (CMDLFileHeader &rhs)
int32_t GetVersion () const
int32_t GetNumProbes () const
int32_t GetAnalysisType () const
bool GetMasked () const
std::string GetChipType () const
std::string GetModifiedDate () const
std::string GetReserve () const
void SetVersion (int32_t value)
void SetNumProbes (int32_t value)
void SetAnalysisType (int32_t value)
void SetMasked (bool value)
void SetChipType (const char *value)
void SetModifiedDate (const char *value)
CMDLFileHeader (int32_t nProbes=0, int32_t analysisType=MDL_PLIER)
Protected Attributes
int32_t m_nVersion
int32_t m_nNumProbes
int32_t m_nAnalysisType
bool m_bMasked
std::string m_strChipType
std::string m_strModifiedDate
std::string m_strReserve
Friends
class CMDLFileData
Detailed Description
PLIER model file header class
Definition at line 88 of file MDLFileData.h.
Constructor & Destructor Documentation
CMDLFileHeader::CMDLFileHeader (int32_t nProbes = 0, int32_t analysisType = MDL_PLIER)
Constructor
Parameters:
nProbes The number of probes
analysisType The type of analysis
Definition at line 90 of file MDLFileData.cpp.
Member Function Documentation
int32_t affxmdl::CMDLFileHeader::GetAnalysisType () const [inline]
The analysis type
Returns:
The analysis type
Definition at line 120 of file MDLFileData.h.
References m_nAnalysisType.
Referenced by affxmdl::CMDLFileData::GetHeaderInfo(), operator=(), and affxmdl::CMDLFileData::PrintMDLToTextFile().
std::string affxmdl::CMDLFileHeader::GetChipType () const [inline]
The chip type
Returns:
The chip type
Definition at line 130 of file MDLFileData.h.
References m_strChipType.
Referenced by affxmdl::CMDLFileData::GetHeaderInfo(), operator=(), and affxmdl::CMDLFileData::PrintMDLToTextFile().
bool affxmdl::CMDLFileHeader::GetMasked () const [inline]
The mask flag
Returns:
The mask flag
Definition at line 125 of file MDLFileData.h.
References m_bMasked.
Referenced by affxmdl::CMDLFileData::GetHeaderInfo(), operator=(), and affxmdl::CMDLFileData::PrintMDLToTextFile().
std::string affxmdl::CMDLFileHeader::GetModifiedDate () const [inline]
The modified date
Returns:
The modified date
Definition at line 135 of file MDLFileData.h.
References m_strModifiedDate.
Referenced by affxmdl::CMDLFileData::GetHeaderInfo(), operator=(), and affxmdl::CMDLFileData::PrintMDLToTextFile().
int32_t affxmdl::CMDLFileHeader::GetNumProbes () const [inline]
The number of probes
Returns:
The number of probes
Definition at line 116 of file MDLFileData.h.
References m_nNumProbes.
Referenced by affxmdl::CMDLFileData::GetHeaderInfo(), affxmdl::CMDLFileData::GetProbeData(), operator=(), affxmdl::CMDLFileData::PrintMDLToTextFile(), affxmdl::CMDLFileData::ReadFile(), affxmdl::CMDLFileData::SetProbeData(), and affxmdl::CMDLFileData::Write().
std::string affxmdl::CMDLFileHeader::GetReserve () const [inline]
Reserved
Definition at line 138 of file MDLFileData.h.
References m_strReserve.
Referenced by operator=().
int32_t affxmdl::CMDLFileHeader::GetVersion () const [inline]
The version number
Returns:
The version number.
Definition at line 112 of file MDLFileData.h.
Referenced by affxmdl::CMDLFileData::GetHeaderInfo(), operator=(), and affxmdl::CMDLFileData::PrintMDLToTextFile().
CMDLFileHeader & CMDLFileHeader::operator= (CMDLFileHeader & rhs)
Friend to the parent class
Operator for Header assignment
Parameters:
rhs The header object to copy
Returns:
The copied header
Definition at line 100 of file MDLFileData.cpp.
References GetAnalysisType(), GetChipType(), GetMasked(), GetModifiedDate(), GetNumProbes(), GetReserve(), GetVersion(), m_bMasked, m_nAnalysisType, m_nNumProbes, m_strChipType, m_strModifiedDate, and m_strReserve.
void affxmdl::CMDLFileHeader::SetAnalysisType (int32_t value) [inline]
Sets the analysis type
Parameters:
value The analysis type
Definition at line 150 of file MDLFileData.h.
References m_nAnalysisType.
Referenced by affxmdl::CMDLFileData::SetHeaderInfo().
void affxmdl::CMDLFileHeader::SetChipType (const char * value) [inline]
Sets the chip type
Parameters:
value The chip type
Definition at line 158 of file MDLFileData.h.
References m_strChipType.
Referenced by affxmdl::CMDLFileData::SetHeaderInfo().
void affxmdl::CMDLFileHeader::SetMasked (bool value) [inline]
Sets the mask flag
Parameters:
value The mask flag
Definition at line 154 of file MDLFileData.h.
References m_bMasked.
Referenced by affxmdl::CMDLFileData::SetHeaderInfo().
void affxmdl::CMDLFileHeader::SetModifiedDate (const char * value) [inline]
Sets the modification date
Parameters:
value The date
Definition at line 162 of file MDLFileData.h.
References m_strModifiedDate.
Referenced by affxmdl::CMDLFileData::SetHeaderInfo(), and affxmdl::CMDLFileData::Write().
void affxmdl::CMDLFileHeader::SetNumProbes (int32_t value) [inline]
Sets the number of probes
Parameters:
value The number of probes
Definition at line 146 of file MDLFileData.h.
References m_nNumProbes.
Referenced by affxmdl::CMDLFileData::SetHeaderInfo().
void affxmdl::CMDLFileHeader::SetVersion (int32_t value) [inline]
Sets the version number
Parameters:
value The version number
Definition at line 142 of file MDLFileData.h.
Referenced by affxmdl::CMDLFileData::SetHeaderInfo().
Friends And Related Function Documentation
friend class CMDLFileData [friend]
Reserved for future use
Definition at line 99 of file MDLFileData.h.
Member Data Documentation
bool affxmdl::CMDLFileHeader::m_bMasked [protected]
PLIER analysis type
Definition at line 94 of file MDLFileData.h.
Referenced by GetMasked(), operator=(), and SetMasked().
int32_t affxmdl::CMDLFileHeader::m_nAnalysisType [protected]
Number pf probes
Definition at line 93 of file MDLFileData.h.
Referenced by GetAnalysisType(), operator=(), and SetAnalysisType().
int32_t affxmdl::CMDLFileHeader::m_nNumProbes [protected]
Model file version number
Definition at line 92 of file MDLFileData.h.
Referenced by GetNumProbes(), operator=(), and SetNumProbes().
std::string affxmdl::CMDLFileHeader::m_strChipType [protected]
Model file generated with masking
Definition at line 95 of file MDLFileData.h.
Referenced by GetChipType(), operator=(), and SetChipType().
std::string affxmdl::CMDLFileHeader::m_strModifiedDate [protected]
Probe array type
Definition at line 96 of file MDLFileData.h.
Referenced by GetModifiedDate(), operator=(), and SetModifiedDate().
std::string affxmdl::CMDLFileHeader::m_strReserve [protected]
Last modified date
Definition at line 97 of file MDLFileData.h.
Referenced by GetReserve(), and operator=().
The documentation for this class was generated from the following files:
file/MDLFileData.h
file/MDLFileData.cpp