Affymetrix Power Tools: CNAnalysisEngine Class Reference
CNAnalysisEngine Class Reference
The engine for copy number calculations post log2 ratio calculation.
#include <CNAnalysisEngine.h>