Affymetrix Power Tools: CEMPrior Class Reference
CEMPrior Class Reference
Object to hold all EM prior information.
#include <PrimeEM.h>
Public Member Functions
CEMPrior (const int clusters=3)
defualt constructor
void initialize ()
initialize prior information with defaults if clusters=3
void set (const int clusters=3)
set function to initialize buffers
CEMPrior & operator= (const CEMPrior &rhs)
assignment operator
void setMu (const std::vector< double > &c)
function to set up the centers of clusters
void setMuSD (const std::vector< double > &c)
function to set up the stdev of cluster centers
void setSigma (const std::vector< double > &s)
function to set up the sigmas of clusters
void setSigmaSD (const std::vector< double > &s)
function to set up the centers of clusters
void setStatus (bool good)
function to set the prior status, must set true with valid information to proceed if initialzie() not called
Protected Attributes
bool m_good
prior status
std::vector< double > m_mu
cluster centers
std::vector< double > m_muSD
stdev of cluster centers
std::vector< double > m_sigma
cluster sigmas
std::vector< double > m_sigmaSD
stdev of cluster sigmas
Friends
class CPrimeEM
Detailed Description
Object to hold all EM prior information.
Definition at line 313 of file PrimeEM.h.
Constructor & Destructor Documentation
CEMPrior::CEMPrior (const int clusters = 3)
defualt constructor
Parameters:
clusters - number of clusters
Definition at line 468 of file PrimeEM.cpp.
References m_good, m_mu, m_muSD, m_sigma, and m_sigmaSD.
Member Function Documentation
void CEMPrior::initialize ()
initialize prior information with defaults if clusters=3
Returns:
void
Definition at line 480 of file PrimeEM.cpp.
References m_good, m_mu, setMu(), setMuSD(), setSigma(), and setSigmaSD().
Referenced by CPrimeEM::CPrimeEM(), and CPrimeEM::setParam().
void CEMPrior::set (const int clusters = 3)
set function to initialize buffers
Parameters:
clusters - number of clusters
Returns:
void
Definition at line 513 of file PrimeEM.cpp.
References m_mu, m_muSD, m_sigma, and m_sigmaSD.
Referenced by CPrimeEM::CPrimeEM(), and CPrimeEM::setParam().
void CEMPrior::setMu (const std::vector< double > & c)
function to set up the centers of clusters
Parameters:
c - a vector to hold all centers of clusters
Returns:
void
Definition at line 542 of file PrimeEM.cpp.
References m_mu.
Referenced by initialize().
void CEMPrior::setMuSD (const std::vector< double > & c)
function to set up the stdev of cluster centers
Parameters:
c - a vector to hold all centers of clusters
Returns:
void
Definition at line 552 of file PrimeEM.cpp.
References m_muSD.
Referenced by initialize().
void CEMPrior::setSigma (const std::vector< double > & s)
function to set up the sigmas of clusters
Parameters:
s - a vector to hold all of stdevs of clusters
Returns:
void
Definition at line 562 of file PrimeEM.cpp.
References m_sigma.
Referenced by initialize().
void CEMPrior::setSigmaSD (const std::vector< double > & s)
function to set up the centers of clusters
Parameters:
s - a vector to hold all stdevs of sigmas
Returns:
void
Parameters:
c - a vector to hold all stdevs of sigmas
Returns:
void
Definition at line 572 of file PrimeEM.cpp.
References m_sigmaSD.
Referenced by initialize().
void CEMPrior::setStatus (bool good) [inline]
function to set the prior status, must set true with valid information to proceed if initialzie() not called
Parameters:
good - flag to indicate the prior information status
Returns:
void
Definition at line 368 of file PrimeEM.h.
References m_good.
Referenced by CPrimeEM::checkPrior().
The documentation for this class was generated from the following files:
algorithm/em/PrimeEM.h
algorithm/em/PrimeEM.cpp