Affymetrix Power Tools: CopyNumberResultWriter Class Reference
CopyNumberResultWriter Class Reference
#include <CopyNumberResultWriter.h>
Public Member Functions
CopyNumberResultWriter ()
~CopyNumberResultWriter ()
void Clear ()
void MaximumProbeSetNameLength (int len)
void MaximumCytoRegionNameLength (int len)
void MaximumGenotypeProbeSetNameLength (int len)
std::string & AlgName ()
std::string & AlgVersion ()
std::string & ProgramName ()
std::string & ProgramVersion ()
std::string & ProgramCompany ()
int & NumberProbeSets ()
int & NumberCytoRegions ()
int & NumberGenotypeProbeSets ()
std::vector
< affymetrix_calvin_io::ColumnInfo > & Columns ()
std::vector
< affymetrix_calvin_io::ColumnInfo > & GenotypeColumns ()
std::vector
< affymetrix_calvin_io::ColumnInfo > & CytoRegionColumns ()
affymetrix_calvin_parameter::ParameterNameValueTypeList & AlgParams ()
affymetrix_calvin_parameter::ParameterNameValueTypeList & SummaryParams ()
void SetChromosomeProbeSetIndexInformation (u_int8_t chr, int startIndex, int count)
void CreateResultFile (affymetrix_fusion_io::FusionCELData &cel, const std::string &fileName)
void WriteProbeSetResult (const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData &entry)
void WriteCytoRegionResult (const affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData &entry)
void WriteGenotypeProbeSetResult (const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData &entry)
void CloseResultsFile ()
Detailed Description
This class provides a wrapper to writing a single copy number file of the Command Console format.
Definition at line 39 of file CopyNumberResultWriter.h.
Constructor & Destructor Documentation
CopyNumberResultWriter::CopyNumberResultWriter () [inline]
Initialize the class
Definition at line 99 of file CopyNumberResultWriter.h.
CopyNumberResultWriter::~CopyNumberResultWriter () [inline]
Clean up
Definition at line 102 of file CopyNumberResultWriter.h.
References Clear().
Member Function Documentation
std::string& CopyNumberResultWriter::AlgName () [inline]
The name of the algorithm.
Returns:
The algorithm name.
Definition at line 125 of file CopyNumberResultWriter.h.
affymetrix_calvin_parameter::ParameterNameValueTypeList& CopyNumberResultWriter::AlgParams () [inline]
Algorithm parameters. This should include the genome name, version, etc.
Definition at line 166 of file CopyNumberResultWriter.h.
std::string& CopyNumberResultWriter::AlgVersion () [inline]
Sets the algorithm version.
Returns:
The version.
Definition at line 130 of file CopyNumberResultWriter.h.
void CopyNumberResultWriter::Clear (void)
Clean up
Definition at line 54 of file CopyNumberResultWriter.cpp.
Referenced by ~CopyNumberResultWriter().
void CopyNumberResultWriter::CloseResultsFile ()
Close the output file.
Definition at line 151 of file CopyNumberResultWriter.cpp.
References affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
std::vector<affymetrix_calvin_io::ColumnInfo>& CopyNumberResultWriter::Columns () [inline]
The columns of data to store.
Definition at line 157 of file CopyNumberResultWriter.h.
void CopyNumberResultWriter::CreateResultFile (affymetrix_fusion_io::FusionCELData & cel, const std::string & fileName)
Create the results file with the header information (no data is written). This function will throw a std::string exception on errors.
Parameters:
cel The CEL file data object.
fileName The name of the results file to create.
Returns:
True if successful.
Definition at line 80 of file CopyNumberResultWriter.cpp.
References affymetrix_calvin_io::CHPMultiDataData::AddAlgParams(), affymetrix_calvin_io::DataSetHeader::AddNameValParam(), affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_io::GenericDataHeader::AddParent(), affymetrix_calvin_io::CHPMultiDataData::AddSummaryParams(), affymetrix_fusion_io::FusionCELData::GetChipType(), affymetrix_calvin_io::CHPMultiDataData::GetDataSetHeader(), affymetrix_calvin_io::CHPMultiDataData::GetFileHeader(), affymetrix_fusion_io::FusionCELData::GetGenericData(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::Initialize(), PROGRAM_COMPANY, PROGRAM_NAME, affymetrix_calvin_io::CHPMultiDataData::SetAlgName(), affymetrix_calvin_io::CHPMultiDataData::SetAlgVersion(), affymetrix_calvin_io::CHPMultiDataData::SetArrayType(), affymetrix_calvin_io::CHPMultiDataData::SetEntryCount(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueText(), and affymetrix_calvin_exceptions::CalvinException::ToString().
std::vector<affymetrix_calvin_io::ColumnInfo>& CopyNumberResultWriter::CytoRegionColumns () [inline]
The columns of cyto data to store.
Definition at line 163 of file CopyNumberResultWriter.h.
std::vector<affymetrix_calvin_io::ColumnInfo>& CopyNumberResultWriter::GenotypeColumns () [inline]
The columns of genotype data to store.
Definition at line 160 of file CopyNumberResultWriter.h.
void CopyNumberResultWriter::MaximumCytoRegionNameLength (int len) [inline]
Set the max cyto region name length.
Parameters:
len The maximum length.
Definition at line 115 of file CopyNumberResultWriter.h.
void CopyNumberResultWriter::MaximumGenotypeProbeSetNameLength (int len) [inline]
Set the max genotype probe set name length.
Parameters:
len The maximum length.
Definition at line 120 of file CopyNumberResultWriter.h.
void CopyNumberResultWriter::MaximumProbeSetNameLength (int len) [inline]
Set the max probe set name length.
Parameters:
len The maximum length.
Definition at line 110 of file CopyNumberResultWriter.h.
int& CopyNumberResultWriter::NumberCytoRegions () [inline]
The number of cyto regions
Returns:
The number of cyto regions
Definition at line 149 of file CopyNumberResultWriter.h.
int& CopyNumberResultWriter::NumberGenotypeProbeSets () [inline]
The number of genotype probe sets return The number of genotype probe sets.
Definition at line 154 of file CopyNumberResultWriter.h.
int& CopyNumberResultWriter::NumberProbeSets () [inline]
The number of probe sets
Returns:
The number of probe sets
Definition at line 144 of file CopyNumberResultWriter.h.
std::string& CopyNumberResultWriter::ProgramCompany () [inline]
The company name.
Definition at line 139 of file CopyNumberResultWriter.h.
std::string& CopyNumberResultWriter::ProgramName () [inline]
The program name.
Definition at line 133 of file CopyNumberResultWriter.h.
std::string& CopyNumberResultWriter::ProgramVersion () [inline]
The program version.
Definition at line 136 of file CopyNumberResultWriter.h.
void CopyNumberResultWriter::SetChromosomeProbeSetIndexInformation (u_int8_t chr, int startIndex, int count)
Store the starting probe set index and count of probe sets for the given chromosome.
Parameters:
chr The chromosome value
startIndex The index of the probe sets that the given chromosome starts at.
count The number of probe sets for the given chromosome.
Definition at line 188 of file CopyNumberResultWriter.cpp.
affymetrix_calvin_parameter::ParameterNameValueTypeList& CopyNumberResultWriter::SummaryParams () [inline]
Summary parameters. This includes items such as IQR, etc.
Definition at line 169 of file CopyNumberResultWriter.h.
void CopyNumberResultWriter::WriteCytoRegionResult (const affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData & entry)
Write the cyto region result to the file.
Parameters:
entry The results.
Definition at line 180 of file CopyNumberResultWriter.cpp.
References affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCytoRegionEntry().
void CopyNumberResultWriter::WriteGenotypeProbeSetResult (const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData & entry)
Write the genotype probe set result to the file.
Parameters:
entry The results.
Definition at line 172 of file CopyNumberResultWriter.cpp.
References affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataGenotypeEntry().
void CopyNumberResultWriter::WriteProbeSetResult (const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData & entry)
Write the probe set result to the file.
Parameters:
entry The results.
Definition at line 164 of file CopyNumberResultWriter.cpp.
References affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCopyNumberEntry().
The documentation for this class was generated from the following files:
calvin_files/writers/src/CopyNumberResultWriter.h
calvin_files/writers/src/CopyNumberResultWriter.cpp