Affymetrix Power Tools: IntensityReporter Class Reference
IntensityReporter Class Reference
IntensityReporter - Class for dumping intensities to a file.
#include <IntensityReporter.h>