Affymetrix Power Tools: QuantLabelZ Class Reference
QuantLabelZ Class Reference
This is the primary class wrapping the bayes_label_routine it handles bookkeeping, gender determination, etc.
#include <QuantLabelZ.h>