Affymetrix Power Tools: affxcdf::CCDFFileData Class Reference
affxcdf::CCDFFileData Class Reference
#include <CDFFileData.h>
Public Member Functions
void SetFileName (const char *name)
std::string GetFileName () const
CCDFFileHeader & GetHeader ()
std::string GetGUID ()
std::string GetIntegrityMd5 ()
std::string GetError () const
std::string GetProbeSetName (int index)
std::string GetChipType ()
std::vector< std::string > GetChipTypes ()
bool Read ()
bool ReadHeader ()
bool Exists ()
void Close ()
bool IsXDACompatibleFile ()
GeneChipProbeSetType GetProbeSetType (int index)
void GetProbeSetInformation (int index, CCDFProbeSetInformation &info)
void GetQCProbeSetInformation (int index, CCDFQCProbeSetInformation &info)
void GetQCProbeSetInformation (GeneChipQCProbeSetType qcType, CCDFQCProbeSetInformation &info)
CCDFFileData ()
~CCDFFileData ()
Protected Member Functions
void seekg (uint32_t pos, const std::ios_base::seekdir &dir)
bool Open ()
bool ReadTextFormat ()
bool ReadXDAFormat ()
bool ReadXDAHeader ()
Protected Attributes
std::ios::pos_type probeSetNamePos
std::ios::pos_type qcSetIndexPos
std::ios::pos_type probeSetIndexPos
uint32_t m_probeSetIndex_last
uint32_t m_probeSetIndex_last_valid
std::ifstream iteratorReader
bool readHeaderOnly
CCDFFileHeader m_Header
CCDFProbeSetNames m_ProbeSetNames
std::vector
< CCDFProbeSetInformation > m_ProbeSets
std::vector
< CCDFQCProbeSetInformation > m_QCProbeSets
std::string m_FileName
std::string m_strError
Detailed Description
This class provides storage and reading capabilities for a CDF file.
Definition at line 821 of file CDFFileData.h.
Constructor & Destructor Documentation
CCDFFileData::CCDFFileData ()
Constructor
Definition at line 73 of file CDFFileData.cpp.
CCDFFileData::~CCDFFileData ()
Destructor
Definition at line 79 of file CDFFileData.cpp.
References Close().
Member Function Documentation
void CCDFFileData::Close (void)
Deallocates memory and closes any file handles.
Definition at line 296 of file CDFFileData.cpp.
References affxcdf::CCDFProbeSetNames::Clear(), iteratorReader, m_ProbeSetNames, m_ProbeSets, and m_QCProbeSets.
Referenced by affymetrix_fusion_io::FusionCDFData::Close(), Open(), Read(), ReadHeader(), and ~CCDFFileData().
bool CCDFFileData::Exists ()
Checks if the file exists.
Returns:
True if the file exists.
Definition at line 443 of file CDFFileData.cpp.
References m_FileName.
std::string CCDFFileData::GetChipType ()
Gets the chip type (probe array type) of the CDF file.
Returns:
The chip type. This is just the name (without extension) of the CDF file.
Definition at line 367 of file CDFFileData.cpp.
References affxcdf::CCDFFileHeader::GetChipType(), affxcdf::CCDFFileHeader::GetFormatVersion(), IsXDACompatibleFile(), m_FileName, m_Header, and ReadHeader().
Referenced by affymetrix_fusion_io::FusionCDFData::GetChipType(), and affxchpwriter::CCHPFileWriter::InitializeForWriting().
std::vector< std::string > CCDFFileData::GetChipTypes ()
Gets the chip types (probe array type) of the CDF file. Allow substrings deliminated by '.'
Returns:
vector of chip types
Definition at line 397 of file CDFFileData.cpp.
References affxcdf::CCDFFileHeader::GetChipTypes(), affxcdf::CCDFFileHeader::GetFormatVersion(), IsXDACompatibleFile(), m_FileName, m_Header, and ReadHeader().
Referenced by affymetrix_fusion_io::FusionCDFData::GetChipTypes().
std::string affxcdf::CCDFFileData::GetError () const [inline]
Gets the error string.
Returns:
A string describing the last read error.
Definition at line 928 of file CDFFileData.h.
References m_strError.
Referenced by affymetrix_fusion_io::FusionCDFData::GetError().
std::string affxcdf::CCDFFileData::GetFileName () const [inline]
Gets the name of the file.
Returns:
The full path of the CDF file.
Definition at line 908 of file CDFFileData.h.
References m_FileName.
std::string CCDFFileData::GetGUID ()
Get GUID
Returns:
GUID
Definition at line 325 of file CDFFileData.cpp.
References affxcdf::CCDFFileHeader::GetFormatVersion(), affxcdf::CCDFFileHeader::GetGUID(), IsXDACompatibleFile(), m_Header, and ReadHeader().
Referenced by affymetrix_fusion_io::FusionCDFData::GetGUID().
CCDFFileHeader& affxcdf::CCDFFileData::GetHeader () [inline]
Gets the header object.
Returns:
The CDF file header object.
Definition at line 913 of file CDFFileData.h.
References m_Header.
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::Initialize(), and affxchpwriter::CCHPFileWriter::InitializeForWriting().
std::string CCDFFileData::GetIntegrityMd5 ()
Get integrity md5
Returns:
The integrity md5
Definition at line 346 of file CDFFileData.cpp.
References affxcdf::CCDFFileHeader::GetFormatVersion(), affxcdf::CCDFFileHeader::GetIntegrityMd5(), IsXDACompatibleFile(), m_Header, and ReadHeader().
Referenced by affymetrix_fusion_io::FusionCDFData::GetIntegrityMd5().
void CCDFFileData::GetProbeSetInformation (int index, CCDFProbeSetInformation & info)
Gets the probe set information.
Parameters:
index The zero-based index to the probe set of interest.
info The probe set information.
Returns:
The probe set information.
Definition at line 490 of file CDFFileData.cpp.
References iteratorReader, affxcdf::CCDFProbeGroupInformation::m_AlleleCode, affxcdf::CCDFProbeGroupInformation::m_Cells, affxcdf::CCDFProbeGroupInformation::m_Channel, affxcdf::CCDFProbeGroupInformation::m_Direction, affxcdf::CCDFProbeSetInformation::m_Direction, affxcdf::CCDFProbeInformation::m_Expos, affxcdf::CCDFProbeGroupInformation::m_GroupIndex, affxcdf::CCDFProbeSetInformation::m_Groups, m_Header, affxcdf::CCDFProbeSetInformation::m_Index, affxcdf::CCDFProbeInformation::m_ListIndex, affxcdf::CCDFProbeGroupInformation::m_Name, affxcdf::CCDFProbeGroupInformation::m_NumCells, affxcdf::CCDFProbeSetInformation::m_NumCells, affxcdf::CCDFProbeGroupInformation::m_NumCellsPerList, affxcdf::CCDFProbeSetInformation::m_NumCellsPerList, affxcdf::CCDFProbeSetInformation::m_NumGroups, affxcdf::CCDFProbeGroupInformation::m_NumLists, affxcdf::CCDFProbeSetInformation::m_NumLists, affxcdf::CCDFProbeInformation::m_PBase, affxcdf::CCDFProbeGroupInformation::m_pCells, affxcdf::CCDFProbeSetInformation::m_pGroups, affxcdf::CCDFProbeInformation::m_ProbeGrouping, affxcdf::CCDFProbeInformation::m_ProbeLength, m_probeSetIndex_last, m_probeSetIndex_last_valid, affxcdf::CCDFProbeSetInformation::m_ProbeSetNumber, m_ProbeSets, affxcdf::CCDFProbeSetInformation::m_ProbeSetType, affxcdf::CCDFProbeGroupInformation::m_RepType, affxcdf::CCDFProbeGroupInformation::m_Start, affxcdf::CCDFProbeGroupInformation::m_Stop, affxcdf::CCDFProbeInformation::m_TBase, affxcdf::CCDFFileHeader::m_Version, affxcdf::CCDFProbeGroupInformation::m_WobbleSituation, affxcdf::CCDFProbeInformation::m_X, affxcdf::CCDFProbeInformation::m_Y, affxcdf::CCDFProbeSetInformation::MakeShallowCopy(), MAX_PROBE_SET_NAME_LENGTH, and probeSetIndexPos.
std::string CCDFFileData::GetProbeSetName (int index)
Gets the name of a probe set.
Parameters:
index The zero-based index to the probe set name of interest.
Returns:
The probe set name.
Definition at line 281 of file CDFFileData.cpp.
References affxcdf::CCDFProbeSetNames::GetName(), iteratorReader, m_ProbeSetNames, MAX_PROBE_SET_NAME_LENGTH, probeSetNamePos, and seekg().
Referenced by affymetrix_fusion_io::FusionCDFData::GetProbeSetName().
GeneChipProbeSetType CCDFFileData::GetProbeSetType (int index)
Gets the probe set type for non-qc probe sets.
Parameters:
index The zero-based index to the probe set of interest.
Returns:
The type of probe set.
Definition at line 466 of file CDFFileData.cpp.
References iteratorReader, m_ProbeSets, probeSetIndexPos, and seekg().
Referenced by affymetrix_fusion_io::FusionCDFData::GetProbeSetType(), and affxchpwriter::CCHPFileWriter::InitializeForWriting().
void CCDFFileData::GetQCProbeSetInformation (int index, CCDFQCProbeSetInformation & info)
Gets the QC probe set information by index.
Parameters:
index The zero-based index to the QC probe set of interest.
info The QC probe set information.
Returns:
The QC probe set information.
Definition at line 631 of file CDFFileData.cpp.
References iteratorReader, affxcdf::CCDFQCProbeSetInformation::m_Cells, affxcdf::CCDFQCProbeSetInformation::m_NumCells, affxcdf::CCDFQCProbeSetInformation::m_pCells, m_QCProbeSets, affxcdf::CCDFQCProbeSetInformation::m_QCProbeSetType, affxcdf::CCDFQCProbeSetInformation::MakeShallowCopy(), qcSetIndexPos, and seekg().
Referenced by GetQCProbeSetInformation().
void CCDFFileData::GetQCProbeSetInformation (GeneChipQCProbeSetType qcType, CCDFQCProbeSetInformation & info)
Gets the QC probe set information by type.
Parameters:
qcType The type of QC probe set to retrieve.
info The QC probe set information.
Returns:
The QC probe set information.
Definition at line 616 of file CDFFileData.cpp.
References affxcdf::CCDFFileHeader::GetNumQCProbeSets(), GetQCProbeSetInformation(), affxcdf::CCDFQCProbeSetInformation::GetQCProbeSetType(), m_Header, and affxcdf::CCDFQCProbeSetInformation::m_NumCells.
bool CCDFFileData::IsXDACompatibleFile ()
Determines if a CDF file is of the XDA (binary) format.
Returns:
True if XDA format.
Definition at line 307 of file CDFFileData.cpp.
References m_FileName.
Referenced by GetChipType(), GetChipTypes(), GetGUID(), GetIntegrityMd5(), affymetrix_fusion_io::FusionCDFData::IsXDACompatibleFile(), and Open().
bool CCDFFileData::Open () [protected]
Opens the file for reading.
Returns:
True if successful.
Definition at line 693 of file CDFFileData.cpp.
References Close(), IsXDACompatibleFile(), ReadTextFormat(), and ReadXDAFormat().
Referenced by Read(), and ReadHeader().
bool CCDFFileData::Read ()
Reads the entire file.
Returns:
True if successful.
Definition at line 679 of file CDFFileData.cpp.
References Close(), Open(), and readHeaderOnly.
Referenced by affymetrix_fusion_io::FusionCDFData::Read().
bool CCDFFileData::ReadHeader ()
Reads the header of the file only.
Returns:
True if successful.
Definition at line 452 of file CDFFileData.cpp.
References Close(), Open(), and readHeaderOnly.
Referenced by GetChipType(), GetChipTypes(), GetGUID(), GetIntegrityMd5(), and affymetrix_fusion_io::FusionCDFData::ReadHeader().
bool CCDFFileData::ReadTextFormat () [protected]
Reads a text format CDF file.
Returns:
True if successful.
Definition at line 813 of file CDFFileData.cpp.
References affxcdf::CCDFProbeGroupInformation::m_AlleleCode, affxcdf::CCDFQCProbeInformation::m_Background, affxcdf::CCDFProbeGroupInformation::m_Cells, affxcdf::CCDFQCProbeSetInformation::m_Cells, affxcdf::CCDFProbeGroupInformation::m_Channel, affxcdf::CCDFFileHeader::m_ChipType, affxcdf::CCDFFileHeader::m_ChipTypes, affxcdf::CCDFFileHeader::m_Cols, affxcdf::CCDFProbeGroupInformation::m_Direction, affxcdf::CCDFProbeSetInformation::m_Direction, affxcdf::CCDFProbeInformation::m_Expos, m_FileName, affxcdf::CCDFProbeGroupInformation::m_GroupIndex, affxcdf::CCDFProbeSetInformation::m_Groups, affxcdf::CCDFFileHeader::m_GUID, m_Header, affxcdf::CCDFProbeSetInformation::m_Index, affxcdf::CCDFFileHeader::m_IntegrityMd5, affxcdf::CCDFProbeInformation::m_ListIndex, affxcdf::CCDFProbeGroupInformation::m_Name, affxcdf::CCDFProbeGroupInformation::m_NumCells, affxcdf::CCDFProbeSetInformation::m_NumCells, affxcdf::CCDFQCProbeSetInformation::m_NumCells, affxcdf::CCDFProbeGroupInformation::m_NumCellsPerList, affxcdf::CCDFProbeSetInformation::m_NumCellsPerList, affxcdf::CCDFProbeSetInformation::m_NumGroups, affxcdf::CCDFProbeGroupInformation::m_NumLists, affxcdf::CCDFProbeSetInformation::m_NumLists, affxcdf::CCDFFileHeader::m_NumProbeSets, affxcdf::CCDFFileHeader::m_NumQCProbeSets, affxcdf::CCDFProbeInformation::m_PBase, affxcdf::CCDFQCProbeInformation::m_PLen, affxcdf::CCDFQCProbeInformation::m_PMProbe, affxcdf::CCDFProbeInformation::m_ProbeGrouping, affxcdf::CCDFProbeInformation::m_ProbeLength, affxcdf::CCDFProbeGroupInformation::m_ProbeSetIndex, m_ProbeSetNames, affxcdf::CCDFProbeSetInformation::m_ProbeSetNumber, m_ProbeSets, affxcdf::CCDFProbeSetInformation::m_ProbeSetType, m_QCProbeSets, affxcdf::CCDFQCProbeSetInformation::m_QCProbeSetType, affxcdf::CCDFFileHeader::m_Reference, affxcdf::CCDFProbeGroupInformation::m_RepType, affxcdf::CCDFFileHeader::m_Rows, affxcdf::CCDFProbeGroupInformation::m_Start, affxcdf::CCDFProbeGroupInformation::m_Stop, m_strError, affxcdf::CCDFProbeInformation::m_TBase, affxcdf::CCDFFileHeader::m_Version, affxcdf::CCDFProbeGroupInformation::m_WobbleSituation, affxcdf::CCDFProbeInformation::m_X, affxcdf::CCDFQCProbeInformation::m_X, affxcdf::CCDFProbeInformation::m_Y, affxcdf::CCDFQCProbeInformation::m_Y, readHeaderOnly, affxcdf::CCDFProbeSetNames::Resize(), and affxcdf::CCDFProbeSetNames::SetName().
Referenced by Open().
bool CCDFFileData::ReadXDAFormat () [protected]
Reads an XDA format CDF file.
Returns:
True if successful.
Definition at line 777 of file CDFFileData.cpp.
References iteratorReader, m_FileName, m_Header, affxcdf::CCDFFileHeader::m_NumProbeSets, affxcdf::CCDFFileHeader::m_NumQCProbeSets, m_probeSetIndex_last_valid, m_strError, MAX_PROBE_SET_NAME_LENGTH, probeSetIndexPos, probeSetNamePos, qcSetIndexPos, ReadXDAHeader(), and seekg().
Referenced by Open().
bool CCDFFileData::ReadXDAHeader () [protected]
Reads the header of an XDA format CDF file.
Returns:
True if successful.
Definition at line 707 of file CDFFileData.cpp.
References INTEGRITY_MD5_LENGTH, iteratorReader, affxcdf::CCDFFileHeader::m_ChipType, affxcdf::CCDFFileHeader::m_ChipTypes, affxcdf::CCDFFileHeader::m_Cols, affxcdf::CCDFFileHeader::m_GUID, m_Header, affxcdf::CCDFFileHeader::m_IntegrityMd5, affxcdf::CCDFFileHeader::m_Magic, affxcdf::CCDFFileHeader::m_NumProbeSets, affxcdf::CCDFFileHeader::m_NumQCProbeSets, affxcdf::CCDFFileHeader::m_Reference, affxcdf::CCDFFileHeader::m_Rows, m_strError, and affxcdf::CCDFFileHeader::m_Version.
Referenced by ReadXDAFormat().
void affxcdf::CCDFFileData::seekg (uint32_t pos, const std::ios_base::seekdir & dir) [inline, protected]
Use this seekg method when seeking with the iteratorReader. It updates the state needed for sequenial reads.
Definition at line 846 of file CDFFileData.h.
References iteratorReader, and m_probeSetIndex_last_valid.
Referenced by GetProbeSetName(), GetProbeSetType(), GetQCProbeSetInformation(), and ReadXDAFormat().
void affxcdf::CCDFFileData::SetFileName (const char * name) [inline]
Sets the name of the file.
Parameters:
name The full path of the CDF file.
Definition at line 903 of file CDFFileData.h.
References m_FileName.
Referenced by affymetrix_fusion_io::FusionCDFData::GetChipType(), affymetrix_fusion_io::FusionCDFData::GetChipTypes(), affymetrix_fusion_io::FusionCDFData::GetGUID(), affymetrix_fusion_io::FusionCDFData::GetIntegrityMd5(), affymetrix_fusion_io::FusionCDFData::IsXDACompatibleFile(), affymetrix_fusion_io::FusionCDFData::Read(), and affymetrix_fusion_io::FusionCDFData::ReadHeader().
Member Data Documentation
std::ifstream affxcdf::CCDFFileData::iteratorReader [protected]
The file stream for the probe set information iterator.
Definition at line 856 of file CDFFileData.h.
Referenced by Close(), GetProbeSetInformation(), GetProbeSetName(), GetProbeSetType(), GetQCProbeSetInformation(), ReadXDAFormat(), ReadXDAHeader(), and seekg().
std::string affxcdf::CCDFFileData::m_FileName [protected]
The CDF file name (full path).
Definition at line 874 of file CDFFileData.h.
Referenced by Exists(), GetChipType(), GetChipTypes(), GetFileName(), IsXDACompatibleFile(), ReadTextFormat(), ReadXDAFormat(), and SetFileName().
CCDFFileHeader affxcdf::CCDFFileData::m_Header [protected]
The file header object.
Definition at line 862 of file CDFFileData.h.
Referenced by GetChipType(), GetChipTypes(), GetGUID(), GetHeader(), GetIntegrityMd5(), GetProbeSetInformation(), GetQCProbeSetInformation(), ReadTextFormat(), ReadXDAFormat(), and ReadXDAHeader().
uint32_t affxcdf::CCDFFileData::m_probeSetIndex_last [protected]
What was the last probesetindex read? This state allows us to handle sequential reads quickly. (no seeking.)
Definition at line 836 of file CDFFileData.h.
Referenced by GetProbeSetInformation().
uint32_t affxcdf::CCDFFileData::m_probeSetIndex_last_valid [protected]
1 if like m_probeSetIndex_last is valid. The seekg method clears this.
Definition at line 841 of file CDFFileData.h.
Referenced by GetProbeSetInformation(), ReadXDAFormat(), and seekg().
CCDFProbeSetNames affxcdf::CCDFFileData::m_ProbeSetNames [protected]
The list of probe set names.
Definition at line 865 of file CDFFileData.h.
Referenced by Close(), GetProbeSetName(), and ReadTextFormat().
std::vector<CCDFProbeSetInformation> affxcdf::CCDFFileData::m_ProbeSets [protected]
An array of probe sets.
Definition at line 868 of file CDFFileData.h.
Referenced by Close(), GetProbeSetInformation(), GetProbeSetType(), and ReadTextFormat().
std::vector<CCDFQCProbeSetInformation> affxcdf::CCDFFileData::m_QCProbeSets [protected]
An array of QC probe sets.
Definition at line 871 of file CDFFileData.h.
Referenced by Close(), GetQCProbeSetInformation(), and ReadTextFormat().
std::string affxcdf::CCDFFileData::m_strError [protected]
A string to hold an error message upon read failures.
Definition at line 877 of file CDFFileData.h.
Referenced by GetError(), ReadTextFormat(), ReadXDAFormat(), and ReadXDAHeader().
std::ios::pos_type affxcdf::CCDFFileData::probeSetIndexPos [protected]
The position of the probe set index array in the XDA file.
Definition at line 831 of file CDFFileData.h.
Referenced by GetProbeSetInformation(), GetProbeSetType(), and ReadXDAFormat().
std::ios::pos_type affxcdf::CCDFFileData::probeSetNamePos [protected]
The position of the probe set names in the XDA file.
Definition at line 825 of file CDFFileData.h.
Referenced by GetProbeSetName(), and ReadXDAFormat().
std::ios::pos_type affxcdf::CCDFFileData::qcSetIndexPos [protected]
The position of the QC probe set index array in the XDA file.
Definition at line 828 of file CDFFileData.h.
Referenced by GetQCProbeSetInformation(), and ReadXDAFormat().
bool affxcdf::CCDFFileData::readHeaderOnly [protected]
Flag to indicate that only the header part of the file is to be read.
Definition at line 859 of file CDFFileData.h.
Referenced by Read(), ReadHeader(), and ReadTextFormat().
The documentation for this class was generated from the following files:
file/CDFFileData.h
file/CDFFileData.cpp