Affymetrix Power Tools: SelfDoc Class Reference
SelfDoc Class Reference
Small interface to for algorithmic classes that can explain themselves.
#include <SelfDoc.h>