Affymetrix Power Tools: affymetrix_comparer::CHPCompareGCOStoGCOS Class Reference
affymetrix_comparer::CHPCompareGCOStoGCOS Class Reference
#include <CHPCompareGCOStoGCOS.h>
Public Member Functions
void Clear ()
bool CompareFiles (const char *file1, const char *file2)
std::string Differences () const
Detailed Description
Provides for information about CHP file versions.
Definition at line 38 of file CHPCompareGCOStoGCOS.h.
Member Function Documentation
void CHPCompareGCOStoGCOS::Clear ()
Clears the members.
Definition at line 37 of file CHPCompareGCOStoGCOS.cpp.
References affxchp::CCHPFileData::Clear().
Referenced by CompareFiles().
bool CHPCompareGCOStoGCOS::CompareFiles (const char * file1, const char * file2)
Determines the version number of the file.
Parameters:
file1 The first file.
file2 The second file.
Returns:
True if identical.
Definition at line 67 of file CHPCompareGCOStoGCOS.cpp.
References Clear().
std::string affymetrix_comparer::CHPCompareGCOStoGCOS::Differences () const [inline]
The differences between the files.
Returns:
A string representation of the differences.
Definition at line 105 of file CHPCompareGCOStoGCOS.h.
Referenced by affymetrix_comparer::CHPComparer::CompareFiles().
The documentation for this class was generated from the following files:
calvin_files/converters/chp/comparer/CHPCompareGCOStoGCOS.h
calvin_files/converters/chp/comparer/CHPCompareGCOStoGCOS.cpp