Affymetrix Power Tools: CNFamilialAnalysisMethodGenotypeDiscordance Class Reference
CNFamilialAnalysisMethodGenotypeDiscordance Class Reference
The GenotypeDiscordance Familial analysis method.
#include <CNFamilialAnalysisMethodGenotypeDiscordance.h>