Affymetrix Power Tools: AnalysisInfo Class Reference
AnalysisInfo Class Reference
Information about a particular analysis run.
#include <AnalysisInfo.h>
Public Member Functions
AnalysisInfo ()
Constructor.
void addParam (const std::string &key, const std::string &value)
Add a key/value parameter pair to our inforomation.
void addClientMetaInfo (const std::string &key, const std::string &value)
Add client supplied key/value parameter pair to our information.
std::string toString (std::string sep="\n")
Turn a Info set of parameters into a text representation of: key1=value1 key2=value2 key3=value3.
int getNumCols ()
Public Attributes
int m_MaxPsNameLength
Length of the longest probeset name.
std::string m_AnalysisName
Name of the analysis.
int m_NumExpression
Number of expression probesets.
int m_NumGenotyping
Number of genotyping expression.
int m_NumReporting
How many snps to report in CHP file.
int m_NumRows
How many rows are on the grid of the chip.
int m_NumCols
How many columns are the grid of the chip.
int m_NumProbeSets
How many probesets are on the chip and in cdf file. This is /// critical as probesets must be the exact same in number and order /// as in the cdf file.
affxcdf::GeneChipProbeSetType m_ProbeSetType
What type of chp file is this? For our purposes here it is genotyping.
std::string m_ChipType
What chip is this?
std::string m_ProgID
What is our id for GCOS?
std::string m_ProgramName
What is the name of the program.
std::string m_ProgramVersion
What program created this chp file.
std::string m_ProgramCompany
What company created this chp file.
std::string m_AlgName
What algorithm are we reporting.
std::string m_AlgVersion
What version of the algorithm is being used.
std::string m_AnalysisGuid
GUID (global unique ID) associated with a specific analysis.
std::string m_ExecGuid
GUID associated with a specific process.
std::vector< std::string > m_ParamNames
These next two vectors are matched pairs, one contains the /// keys and the other the values. Would use a map, but want to be /// guaranteed of the order.
std::vector< std::string > m_ParamValues
std::map< std::string, uint32_t > m_KeysIndex
A mapping of key names to their index in m_ParamNames.
std::vector< std::string > m_ClientInfoNames
Two vectors for client supplied meta-data. Matched pairs of vectors, one contains the /// keys and the other the values. Would use a map, but want to be /// guaranteed of the order.
std::vector< std::string > m_ClientInfoValues
std::map< std::string, uint32_t > m_ClientInfoKeysIndex
A mapping of key names to their index in m_ParamNames.
std::vector< const char * > m_ProbesetNames
Vector of probeset names and groups as they should appear in the chp file. /// this memory is owned elsewhere as it is relatively large in size. /// Only populated if there is CHP output.
std::vector< const char * > m_ProbesetDisplayNames
Vector of probeset names and groups as they should appear in the chp file. /// this memory is owned elsewhere as it is relatively large in size. /// Only populated if there is CHP output.
Detailed Description
Information about a particular analysis run.
Definition at line 45 of file AnalysisInfo.h.
Constructor & Destructor Documentation
AnalysisInfo::AnalysisInfo () [inline]
Constructor.
Definition at line 49 of file AnalysisInfo.h.
References m_AlgName, m_AlgVersion, m_AnalysisGuid, m_ChipType, m_ExecGuid, m_MaxPsNameLength, m_NumCols, m_NumExpression, m_NumGenotyping, m_NumProbeSets, m_NumReporting, m_NumRows, m_ProbeSetType, m_ProgID, m_ProgramCompany, m_ProgramName, and m_ProgramVersion.
Member Function Documentation
void AnalysisInfo::addClientMetaInfo (const std::string & key, const std::string & value) [inline]
Add client supplied key/value parameter pair to our information.
Keys must be unique strings.
Parameters:
key - name of key to be stored.
value - matching value to be associated with key.
Definition at line 91 of file AnalysisInfo.h.
References Err::errAbort(), m_ClientInfoKeysIndex, and m_ClientInfoNames.
void AnalysisInfo::addParam (const std::string & key, const std::string & value) [inline]
Add a key/value parameter pair to our inforomation.
Keys must be unique strings.
Parameters:
key - name of key to be stored.
value - matching value to be associated with key.
Definition at line 75 of file AnalysisInfo.h.
References Err::errAbort(), m_KeysIndex, and m_ParamNames.
Referenced by QuantMethodTransform::transformData().
std::string AnalysisInfo::toString (std::string sep = "\n") [inline]
Turn a Info set of parameters into a text representation of: key1=value1 key2=value2 key3=value3.
Parameters:
sep - optional separatar string, default newline
Returns:
- string representation of Info set.
Definition at line 112 of file AnalysisInfo.h.
References m_AlgName, m_AlgVersion, m_ChipType, m_NumCols, m_NumProbeSets, m_NumRows, m_ParamNames, m_ProgID, m_ProgramName, m_ProgramVersion, and ToStr().
The documentation for this class was generated from the following file:
chipstream/AnalysisInfo.h