Affymetrix Power Tools: affymetrix_calvin_io::SAXArrayHandlers Class Reference
affymetrix_calvin_io::SAXArrayHandlers Class Reference
#include <SAXArrayHandlers.h>
Public Member Functions
SAXArrayHandlers (affymetrix_calvin_array::ArrayData *data, bool headerOnly=false)
~SAXArrayHandlers ()
void startDocument ()
void endDocument ()
void characters (const XMLCh *const chars, const XMLSize_t length)
void startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList &attributes)
void endElement (const XMLCh *const name)
const
affymetrix_calvin_utilities::AffymetrixGuidType & DataTypeIdentifier () const
std::wstring FileVersionNumber () const
Detailed Description
This class provides the SAX handlers for reading calvin array files.
Definition at line 181 of file SAXArrayHandlers.h.
Constructor & Destructor Documentation
SAXArrayHandlers::SAXArrayHandlers (affymetrix_calvin_array::ArrayData * data, bool headerOnly = false)
Constructor
Parameters:
data The array data.
headerOnly Flag to indicate that the header line should only be read.
Definition at line 103 of file SAXArrayHandlers.cpp.
SAXArrayHandlers::~SAXArrayHandlers ()
Destructor
Definition at line 113 of file SAXArrayHandlers.cpp.
Member Function Documentation
void SAXArrayHandlers::characters (const XMLCh *const chars, const XMLSize_t length)
Receive notification of character data inside an element.
Parameters:
chars The character data.
length The length of the character string.
Definition at line 270 of file SAXArrayHandlers.cpp.
References affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ControlMultiValues(), affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueText(), affymetrix_calvin_array::ArrayData::UserAttributes(), and affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ValueType().
const affymetrix_calvin_utilities::AffymetrixGuidType& affymetrix_calvin_io::SAXArrayHandlers::DataTypeIdentifier () const [inline]
The identifier of the type of data stored in the file.
Returns:
The identifier of the type of data.
Definition at line 282 of file SAXArrayHandlers.h.
void SAXArrayHandlers::endDocument ()
Called at the end of the document
Definition at line 127 of file SAXArrayHandlers.cpp.
void SAXArrayHandlers::endElement (const XMLCh *const name)
Called at the end of each element.
Parameters:
name The name of the element.
Definition at line 134 of file SAXArrayHandlers.cpp.
std::wstring affymetrix_calvin_io::SAXArrayHandlers::FileVersionNumber () const [inline]
The files version number.
Returns:
The file version.
Definition at line 288 of file SAXArrayHandlers.h.
Referenced by affymetrix_calvin_io::ArrayFileReader::Read().
void SAXArrayHandlers::startDocument ()
Called at the start of the document
Definition at line 120 of file SAXArrayHandlers.cpp.
void affymetrix_calvin_io::SAXArrayHandlers::startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList & attributes)
Called at the start of each element.
Parameters:
name The name of the element.
attributes The attributes of the element.
The documentation for this class was generated from the following files:
calvin_files/parsers/src/SAXArrayHandlers.h
calvin_files/parsers/src/SAXArrayHandlers.cpp