Affymetrix Power Tools: CNAnalysisMethodSegmentLOH Class Reference
CNAnalysisMethodSegmentLOH Class Reference
The SegmentLOH analysis method.
#include <CNAnalysisMethodSegmentLOH.h>