Affymetrix Power Tools: EngineUtil Class Reference
EngineUtil Class Reference
Static Public Member Functions
static void readProbeFile (std::vector< probeid_t > &probeIds, const std::string &probeFileName)
Read in a file of probe IDs.
static void readProbeFile (std::vector< std::vector< probeid_t > > &probeIds, const std::string &probeFileName)
Read in a file of probe IDs.
static void readProbeFiles (std::vector< probeid_t > &probeIds, const std::vector< std::string > &probeFileNames)
static void readProbeSetFile (std::vector< std::string > &probeSets, const std::string &probeSetFileName)
Read in a file of probeset names or IDs.
static void readProbeSetFiles (std::vector< std::string > &probeSets, const std::vector< std::string > &probeSetFileNames)
static void readProbeClassFile (const std::string &file, const int arraySize, std::map< std::string, std::vector< bool > > &classMap)
Read in the probe class file.
static bool checkChipTypeOk (const std::string &qType, const std::vector< std::string > &possibleTypes)
Return true if the qType of chip is found in the list of possible types that are ok.
static void checkTsvFileChipType (const std::string &path, const std::vector< std::string > &chipTypes, bool mustSee=false)
Check chip types in TSV file against those in vector.
static void checkChipTypeVectors (std::vector< std::string > &chipTypesOk, std::vector< std::string > &chipTypesCheck)
Check to make sure that there is at least one match between the two vectors of chip types.
static void checkCelChipTypes (std::vector< std::string > &chipTypes, uint32_t probeCount, std::vector< std::string > &celFiles, uint32_t rows, uint32_t cols)
Check to make sure all the cel files are compatible with the chiptypes supported and number or probes on them.
static void makePSetNameSubset (const std::string &fileName, std::vector< ProbeSetGroup * > &psGroups, std::map< std::string, bool > &psNameLoadMap)
Get a list from a text file to select a subset of probe sets for analysis.
static void getPgfChipType (std::vector< std::string > &chipTypes, colrow_t &rowCount, colrow_t &colCount, int &probeCount, const std::string &pgfFile, const std::string &clfFile)
Open up a pgf and clf file pair and read the valid chiptypes (i.e.
static void getSpfChipType (std::vector< std::string > &chipTypes, colrow_t &rowCount, colrow_t &colCount, int &probeCount, int &probeSetCount, const std::string &spfFile)
Open up a spf (simple probe format) file and read the valid chiptypes (i.e.
static void getCdfChipType (std::vector< std::string > &chipTypes, colrow_t &rowCount, colrow_t &colCount, int &probeCount, int &probeSetCount, const std::string &cdfFile)
Open up a cdf file and get the chip type (i.e.
static void printSelfDocs (const char *header, std::vector< SelfDoc > doc)
Print out a header and then a series of self documenting objects.
static void explainParameter (const std::string &query)
Print out a little ditty for the given type of self documenting object.
static void getCelFiles (std::vector< std::string > &celFiles, BaseEngine *engine)
static void getChpFiles (std::vector< std::string > &celFiles, BaseEngine *engine)
Detailed Description
Definition at line 50 of file EngineUtil.h.
Member Function Documentation
void EngineUtil::checkCelChipTypes (std::vector< std::string > & chipTypes, uint32_t probeCount, std::vector< std::string > & celFiles, uint32_t rows, uint32_t cols) [static]
Check to make sure all the cel files are compatible with the chiptypes supported and number or probes on them.
Treats the empty string "" as a wildcard, so if chipTypes contains "" then any chip type is accepted, but only if number of probes is correct. Calls Err::errAbort() if something is wrong.
Parameters:
chipTypes - Names of chiptypes that are compatible.
probeCount - How many probes (aka features, ada cels) should be on array.
celFiles - Vector of cel file names to check.
Definition at line 288 of file EngineUtil.cpp.
References Fs::basename(), checkChipTypeOk(), affymetrix_fusion_io::FusionCELData::Close(), affymetrix_calvin_io::GenericData::DataGroupCnt(), Err::errAbort(), FS_QUOTE_PATH, affymetrix_fusion_io::FusionCELData::GetChannels(), affymetrix_fusion_io::FusionCELData::GetChipType(), affymetrix_fusion_io::FusionCELData::GetCols(), affymetrix_fusion_io::FusionCELData::GetGenericData(), affymetrix_fusion_io::FusionCELData::GetNumCells(), affymetrix_fusion_io::FusionCELData::GetRows(), Verbose::out(), affymetrix_fusion_io::FusionCELData::ReadHeader(), affymetrix_fusion_io::FusionCELData::SetActiveDataGroup(), affymetrix_fusion_io::FusionCELData::SetFileName(), and ToStr().
bool EngineUtil::checkChipTypeOk (const std::string & qType, const std::vector< std::string > & possibleTypes) [static]
Return true if the qType of chip is found in the list of possible types that are ok.
Note that this is a case sensitive operation and is meant to be so.
Note that this is a case sensitive operation and is meant to be so. We want to be restrictive to avoid problems later on. Filesystems we care about are at least case-preserving (HFS+)
Definition at line 205 of file EngineUtil.cpp.
References Util::downcaseString(), and Verbose::out().
Referenced by checkCelChipTypes(), and checkChipTypeVectors().
void EngineUtil::checkChipTypeVectors (std::vector< std::string > & chipTypesOk, std::vector< std::string > & chipTypesCheck) [static]
Check to make sure that there is at least one match between the two vectors of chip types.
Call Err::errAbort() if not.
Definition at line 261 of file EngineUtil.cpp.
References checkChipTypeOk(), Err::errAbort(), and Verbose::out().
void EngineUtil::checkTsvFileChipType (const std::string & path, const std::vector< std::string > & chipTypes, bool mustSee = false) [static]
Check chip types in TSV file against those in vector.
Check chip types in TSV file against those in chipTypes vector.
Call Err::errAbort if no match is found.
Definition at line 228 of file EngineUtil.cpp.
References Err::errAbort(), affx::TsvFile::headersFindNext(), and affx::TsvFile::open().
void EngineUtil::explainParameter (const std::string & query) [static]
Print out a little ditty for the given type of self documenting object.
Parameters:
query - type of analysis/adjustment/summarization information is desired for.
Definition at line 566 of file EngineUtil.cpp.
References Err::errAbort(), AnalysisStreamFactory::getDocs(), QuantMethodFactory::getDocs(), PmAdjusterFactory::getDocs(), ChipStreamFactory::getDocs(), SelfDoc::printExplanation(), and ToStr().
void EngineUtil::getCdfChipType (std::vector< std::string > & chipTypes, colrow_t & rowCount, colrow_t & colCount, int & probeCount, int & probeSetCount, const std::string & cdfFile) [static]
Open up a cdf file and get the chip type (i.e.
'Mapping250K_Sty') and number of probes on the chip.
Parameters:
chipTypes - Names of chiptypes that this pgf file is compatible with.
rowCount - Number of rows on the chip.
colCount - Number of columns on chip.
probeCount - Number of probes that are on chip according to clf file.
cdfFile - Name of cdf file to be opened and read from.
Definition at line 501 of file EngineUtil.cpp.
References Err::errAbort(), FS_QUOTE_PATH, affymetrix_fusion_io::FusionCDFData::GetChipTypes(), affymetrix_fusion_io::FusionCDFFileHeader::GetCols(), affymetrix_fusion_io::FusionCDFData::GetError(), affymetrix_fusion_io::FusionCDFData::GetHeader(), affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets(), affymetrix_fusion_io::FusionCDFFileHeader::GetRows(), affymetrix_fusion_io::FusionCDFData::ReadHeader(), and affymetrix_fusion_io::FusionCDFData::SetFileName().
void EngineUtil::getPgfChipType (std::vector< std::string > & chipTypes, colrow_t & rowCount, colrow_t & colCount, int & probeCount, const std::string & pgfFile, const std::string & clfFile) [static]
Open up a pgf and clf file pair and read the valid chiptypes (i.e.
HuEx-1_0-st-v2, HuEx-1_0-st-v1, HuEx-1_0-st-ta1) and number of probes expected from them.
Parameters:
chipTypes - Names of chiptypes that this pgf file is compatible with.
probeCount - Number of probes that are on chip according to clf file.
pgfFile - Name of pgf file to be opened and read from.
clfFile - Name of clf file to be opened and read from.
Definition at line 415 of file EngineUtil.cpp.
References affx::ClfFile::close(), affx::PgfFile::close(), Err::errAbort(), affx::TsvFile::getHeader(), affx::TsvFile::headersFindNext(), affx::ClfFile::m_tsv, affx::PgfFile::m_tsv, affx::ClfFile::open(), and affx::PgfFile::open().
void EngineUtil::getSpfChipType (std::vector< std::string > & chipTypes, colrow_t & rowCount, colrow_t & colCount, int & probeCount, int & probeSetCount, const std::string & spfFile) [static]
Open up a spf (simple probe format) file and read the valid chiptypes (i.e.
HuEx-1_0-st-v2, HuEx-1_0-st-v1, HuEx-1_0-st-ta1) and number of probes expected.
Parameters:
chipTypes - Names of chiptypes that this pgf file is compatible with.
probeCount - Number of probes that are on chip according to spf file.
spfFile - Name of spf file to be opened and read from.
Definition at line 458 of file EngineUtil.cpp.
References affx::TsvFile::close(), Err::errAbort(), affx::TsvFile::getHeader(), affx::TsvFile::headersFindNext(), and affx::TsvFile::open().
void EngineUtil::makePSetNameSubset (const std::string & fileName, std::vector< ProbeSetGroup * > & psGroups, std::map< std::string, bool > & psNameLoadMap) [static]
Get a list from a text file to select a subset of probe sets for analysis.
Parameters:
fileName - Path to file for reading probe subset from.
psGroups - Groups to be filled in, must be deleted later
psNameLoadMap - Map of probesets names to be loaded which is filled in.
Definition at line 387 of file EngineUtil.cpp.
References Util::cloneString(), affx::TsvFile::close(), Err::errAbort(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), ProbeSetGroup::probeSetNames, affx::TSV_BIND_REQUIRED, and affx::TSV_OK.
void EngineUtil::printSelfDocs (const char * header, std::vector< SelfDoc > doc) [static]
Print out a header and then a series of self documenting objects.
Parameters:
header - Descriptive header for this collection of self documenting objects.
doc - Collection of self documenting objects.
Definition at line 535 of file EngineUtil.cpp.
References PgOptions::printStringWidth().
void EngineUtil::readProbeClassFile (const std::string & file, const int arraySize, std::map< std::string, std::vector< bool > > & classMap) [static]
Read in the probe class file.
Parameters:
file - The file to read
masks - Vector of probe masks to fill in
Definition at line 173 of file EngineUtil.cpp.
References affx::TsvFile::close(), Err::errAbort(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), and affx::TSV_BIND_REQUIRED.
void EngineUtil::readProbeFile (std::vector< probeid_t > & probeIds, const std::string & probeFileName) [static]
Read in a file of probe IDs.
Parameters:
probeIds - vector of probeid_t to fill in, these are zero base
probeFileName - the file to load, file has 1 base probe IDs
Definition at line 94 of file EngineUtil.cpp.
References affx::TsvFile::close(), affx::TsvFile::cname2cidx(), Err::errAbort(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), TO_ZEROBASED, ToStr(), and affx::TSV_BIND_REQUIRED.
Referenced by CelExtract::CelExtract(), and CnProbeGenderCelListener::CnProbeGenderCelListener().
void EngineUtil::readProbeSetFile (std::vector< std::string > & probeSets, const std::string & probeSetFileName) [static]
Read in a file of probeset names or IDs.
Parameters:
probeSets - vector of probeset names or IDs to fill in
probeSetFileName - the file to load, file has 1 base probe IDs
IDs trumps names.
Definition at line 124 of file EngineUtil.cpp.
References affx::TsvFile::close(), affx::TsvFile::cname2cidx(), Err::errAbort(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), affx::TSV_BIND_REQUIRED, and affx::TSV_ERR_NOTFOUND.
Referenced by CelExtract::CelExtract().
The documentation for this class was generated from the following files:
chipstream/EngineUtil.h
chipstream/EngineUtil.cpp