Affymetrix Power Tools: CNAnalysisMethodGenotype Class Reference
CNAnalysisMethodGenotype Class Reference
The Genotype analysis method.
#include <CNAnalysisMethodGenotype.h>