Affymetrix Power Tools: FsTestDir Class Reference
FsTestDir Class Reference
Classes
class h
A class for implementing APT_TEST_DIR enviroment variable.
Public Member Functions
std::string asString () const
AptErr_t setTestDir (const std::string &testcasepath, const bool clean=false, const int64_t bytescheck=1073741824)
Public Attributes
FsPath m_path
Detailed Description
Definition at line 66 of file FsTestDir.h.
Member Function Documentation
AptErr_t FsTestDir::setTestDir (const std::string & testcasepath, const bool clean = false, const int64_t bytescheck = 1073741824)
TODO: warn users directory exists?
Definition at line 31 of file FsTestDir.cpp.
References Fs::getFreeDiskSpace(), FsPath::isAbsolute(), Fs::join(), Fs::mkdir(), Fs::mkdirPath(), Verbose::out(), Fs::rm_rf(), FsPath::setErr(), and ToStr().
Referenced by main().
The documentation for this class was generated from the following files:
util/FsTestDir.h
util/FsTestDir.cpp