Affymetrix Power Tools: affymetrix_calvin_io::DATFileReader Class Reference
affymetrix_calvin_io::DATFileReader Class Reference
#include <DATFileReader.h>
Public Member Functions
DATFileReader ()
~DATFileReader ()
const std::string GetFilename () const
void SetFilename (const std::string &name)
void Read (DATData &data)
Protected Member Functions
void ReadGlobalGrid (DATData &data, DataGroupReader &dcReader)
void ReadSubgrids (DATData &data, DataGroupReader &dcReader)
void ReadGridAlignmentAlgorithmParameters (DATData &data, const DataSetHeader &dsh)
Protected Attributes
std::string fileName
Detailed Description
This class reads a DAT data file. It is an interpreter class.
Definition at line 43 of file DATFileReader.h.
Constructor & Destructor Documentation
DATFileReader::DATFileReader ()
Constructor
Definition at line 33 of file DATFileReader.cpp.
DATFileReader::~DATFileReader ()
Destructor
Definition at line 40 of file DATFileReader.cpp.
Member Function Documentation
const std::string affymetrix_calvin_io::DATFileReader::GetFilename () const [inline]
Gets the name of the input file.
Returns:
The name of the file to read.
Definition at line 57 of file DATFileReader.h.
References fileName.
void DATFileReader::Read (DATData & data)
Reads the file header of the generic file and reads all the DataSetHeader information.
Parameters:
data A reference to a DATData object that will receive information from the file.
Exceptions:
affymetrix_calvin_exceptions::FileNotFoundException The file does not exist.
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Definition at line 46 of file DATFileReader.cpp.
References affymetrix_calvin_io::DATData::Clear(), affymetrix_calvin_io::GenericFileReader::Close(), fileName, affymetrix_calvin_io::GenericFileReader::GetDataGroupReader(), affymetrix_calvin_io::DATData::GetFilename(), affymetrix_calvin_io::DATData::GetGenericData(), affymetrix_calvin_io::GenericFileReader::Open(), ReadGlobalGrid(), ReadSubgrids(), and affymetrix_calvin_io::GenericFileReader::SetFilename().
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile(), and affymetrix_cel_converter::CELFileConvertToCalvin::GetParentGenericDataHeader().
void DATFileReader::ReadGlobalGrid (DATData & data, DataGroupReader & dcReader) [protected]
UNTESTED - Read the global grid
Definition at line 65 of file DATFileReader.cpp.
References affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), affymetrix_calvin_io::DataSetReader::GetDataSetHeader(), affymetrix_calvin_io::DataGroupReader::GetDataSetReader(), affymetrix_calvin_utilities::FRegion::pts, affymetrix_calvin_io::DataSetReader::Read(), ReadGridAlignmentAlgorithmParameters(), affymetrix_calvin_io::DATData::SetGlobalGrid(), affymetrix_calvin_utilities::FPoint::x, and affymetrix_calvin_utilities::FPoint::y.
Referenced by Read().
void DATFileReader::ReadGridAlignmentAlgorithmParameters (DATData & data, const DataSetHeader & dsh) [protected]
Read the grid alignment algorithm parameters.
Parameters:
data DATData object to which to add the grid alignment algorithm parameters.
dsh DataSetHeader from which to read the grid alignment algorithm parameters.
Definition at line 137 of file DATFileReader.cpp.
References affymetrix_calvin_io::DATData::AddGridAlignmentAlgorithmParameter(), affymetrix_calvin_io::DATData::ClearGridAlignmentAlgorithmParameters(), and affymetrix_calvin_io::DataSetHeader::GetNameValIterators().
Referenced by ReadGlobalGrid().
void DATFileReader::ReadSubgrids (DATData & data, DataGroupReader & dcReader) [protected]
UNTESTED - Read the subgrids
Definition at line 100 of file DATFileReader.cpp.
References affymetrix_calvin_io::DATData::AddSubgrid(), affymetrix_calvin_utilities::FRegion::Clear(), affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), affymetrix_calvin_io::DataSetReader::GetDataSetHeader(), affymetrix_calvin_io::DataGroupReader::GetDataSetReader(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), affymetrix_calvin_utilities::FRegion::pts, affymetrix_calvin_io::DataSetReader::Read(), affymetrix_calvin_utilities::FPoint::x, and affymetrix_calvin_utilities::FPoint::y.
Referenced by Read().
void affymetrix_calvin_io::DATFileReader::SetFilename (const std::string & name) [inline]
Sets the name of the input file.
Parameters:
name The name of the file to read.
Definition at line 63 of file DATFileReader.h.
References fileName.
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile(), and affymetrix_cel_converter::CELFileConvertToCalvin::GetParentGenericDataHeader().
Member Data Documentation
std::string affymetrix_calvin_io::DATFileReader::fileName [protected]
Name of the file to read
Definition at line 87 of file DATFileReader.h.
Referenced by GetFilename(), Read(), and SetFilename().
The documentation for this class was generated from the following files:
calvin_files/parsers/src/DATFileReader.h
calvin_files/parsers/src/DATFileReader.cpp