Affymetrix Power Tools: CNAnalysisMethodFactory Class Reference
CNAnalysisMethodFactory Class Reference
A factory class for making copy number analysis methodss based on a string representation.
#include <CNAnalysisMethodFactory.h>
Public Member Functions
CNAnalysisMethodFactory (bool bAdditionalWaves=false)
Constructor.
~CNAnalysisMethodFactory ()
Constructor.
void registerMethod (const SelfDoc &doc, SelfCreate::selfCreator maker)
CNAnalysisMethod * CNAnalysisMethodForString (const std::string &spec)
Create a pointer to a new CNAnalysisMethod object as described in the string specification.
std::vector< SelfDoc > getDocs ()
Protected Attributes
std::vector< SelfDoc > m_Docs
std::vector
< SelfCreate::selfCreator > m_Creators
Detailed Description
A factory class for making copy number analysis methodss based on a string representation.
Definition at line 43 of file CNAnalysisMethodFactory.h.
Constructor & Destructor Documentation
CNAnalysisMethodFactory::CNAnalysisMethodFactory (bool bAdditionalWaves = false)
Constructor.
Registers the objects we know how to create and how they describe themselves.
Definition at line 68 of file CNAnalysisMethodFactory.cpp.
References CNAnalysisMethodCovariateLRAdjuster::explainSelf(), CNAnalysisMethodCovariateSignalAdjuster::explainSelf(), CNAnalysisMethodChipstream::explainSelf(), CNAnalysisMethodAllelePeaks::explainSelf(), CNAnalysisMethodSegmentLOH::explainSelf(), CNAnalysisMethodSegmentCN::explainSelf(), CNAnalysisMethodCNCyto2Gender::explainSelf(), CNAnalysisMethodCNGender::explainSelf(), CNAnalysisMethodMosaicism::explainSelf(), CNAnalysisMethodNormalDiploid::explainSelf(), CNAnalysisMethodCNNeutralLOH::explainSelf(), CNAnalysisMethodLOHCytoScan::explainSelf(), CNAnalysisMethodLOHCyto2::explainSelf(), CNAnalysisMethodLOH::explainSelf(), CNAnalysisMethodKernelSmooth::explainSelf(), CNAnalysisMethodGenotype::explainSelf(), CNAnalysisMethodGaussianSmooth::explainSelf(), CNAnalysisMethodAllelicDifferenceCytoScan::explainSelf(), CNAnalysisMethodAllelicDifference::explainSelf(), CNAnalysisMethodLog2RatioCyto2::explainSelf(), CNAnalysisMethodLog2Ratio::explainSelf(), CNAnalysisMethodCNCyto2::explainSelf(), CNAnalysisMethodCN::explainSelf(), CNLog2RatioAdjustmentMethodHighPassFilter::explainSelf(), CNLog2RatioAdjustmentMethodWaveCorrection::explainSelf(), CNIntensityAdjustmentMethodHighPassFilter::explainSelf(), CNIntensityAdjustmentMethodPDNN::explainSelf(), CNReferenceMethodWaveCorrection::explainSelf(), CNReferenceMethodPDNN::explainSelf(), CNReferenceMethodAdditionalWaves::explainSelf(), CNAnalysisMethodCovariateLRAdjuster::newObject(), CNAnalysisMethodCovariateSignalAdjuster::newObject(), CNAnalysisMethodChipstream::newObject(), CNAnalysisMethodAllelePeaks::newObject(), CNAnalysisMethodSegmentLOH::newObject(), CNAnalysisMethodSegmentCN::newObject(), CNAnalysisMethodCNCyto2Gender::newObject(), CNAnalysisMethodCNGender::newObject(), CNAnalysisMethodMosaicism::newObject(), CNAnalysisMethodNormalDiploid::newObject(), CNAnalysisMethodCNNeutralLOH::newObject(), CNAnalysisMethodLOHCytoScan::newObject(), CNAnalysisMethodLOHCyto2::newObject(), CNAnalysisMethodLOH::newObject(), CNAnalysisMethodKernelSmooth::newObject(), CNAnalysisMethodGenotype::newObject(), CNAnalysisMethodGaussianSmooth::newObject(), CNAnalysisMethodAllelicDifferenceCytoScan::newObject(), CNAnalysisMethodAllelicDifference::newObject(), CNAnalysisMethodLog2RatioCyto2::newObject(), CNAnalysisMethodLog2Ratio::newObject(), CNAnalysisMethodCNCyto2::newObject(), CNAnalysisMethodCN::newObject(), CNLog2RatioAdjustmentMethodHighPassFilter::newObject(), CNLog2RatioAdjustmentMethodWaveCorrection::newObject(), CNIntensityAdjustmentMethodHighPassFilter::newObject(), CNIntensityAdjustmentMethodPDNN::newObject(), CNReferenceMethodWaveCorrection::newObject(), CNReferenceMethodPDNN::newObject(), and CNReferenceMethodAdditionalWaves::newObject().
Member Function Documentation
CNAnalysisMethod * CNAnalysisMethodFactory::CNAnalysisMethodForString (const std::string & spec)
Create a pointer to a new CNAnalysisMethod object as described in the string specification.
Parameters:
spec - Specification string
Returns:
Pointer to new CNAnalysisMethod objects, must be deleted when finished.
Definition at line 135 of file CNAnalysisMethodFactory.cpp.
References Err::errAbort(), and SelfCreate::selfCreateFromString().
The documentation for this class was generated from the following files:
copynumber/CNAnalysisMethodFactory.h
copynumber/CNAnalysisMethodFactory.cpp