Affymetrix Power Tools: MultiQuantMethodListener Class Reference
MultiQuantMethodListener Class Reference
Class for reporting results of quantification methods.
#include <MultiQuantMethodListener.h>