Affymetrix Power Tools: GcBg Class Reference
GcBg Class Reference
Class for doing an adjustment based on the median intensity of probes with similar GC content.
#include <GcBg.h>