Affymetrix Power Tools: CNCychpProbeSetsCopyNumber Class Reference
CNCychpProbeSetsCopyNumber Class Reference
A class for storing Cychp ProbeSets CopyNumber data.
#include <CNCychp.h>
Classes
struct ComparePred
struct ComparePred< 0 >
struct ComparePred< 1 >
Public Member Functions
CNCychpProbeSetsCopyNumber ()
Constructor.
void setProbeSetName (const AffxString &str)
AffxString getProbeSetName ()
void setChromosome (unsigned char uc)
unsigned char getChromosome ()
void setPosition (unsigned int ui)
unsigned int getPosition ()
void setLog2Ratio (float f)
float getLog2Ratio ()
void setSmoothSignal (float f)
float getSmoothSignal ()
void setAAlleleSignal (float f)
float getAAlleleSignal ()
void setBAlleleSignal (float f)
float getBAlleleSignal ()
void setSCAR (float f)
float getSCAR ()
void setGenotypeCall (char c)
char getGenotypeCall ()
void setIsGenotypeCallSet (bool b)
bool getIsGenotypeCallSet ()
void setGenotypeConfidence (float f)
float getGenotypeConfidence ()
void setCnCall (unsigned char uc)
unsigned char getCnCall ()
void setLohCall (unsigned char uc)
unsigned char getLohCall ()
void setSegmentInput (char c)
char getSegmentInput ()
void setSegmentOutput (char c)
char getSegmentOutput ()
void setGenotypeCallFromCode (char c)
Set the allele code ffor the genotype call from the internal representation (-1, 0, 1, 2).
int compareTo (CNCychpProbeSetsCopyNumber &that, int iCompareCode)
Compare function.
char getCNNeutral (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNNeutral call (0 or 1).
char getCNGain (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNGain call (0 or 1).
char getCNLoss (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNLoss call (0 or 1).
char getCNNeutralLoh (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNNeutralLOH call (0 or 1).
char getNormalDiploid (int iSexCode, int iXChromosome, int iYChromosome)
Return the NormalDiploid call (0 or 1).
Detailed Description
A class for storing Cychp ProbeSets CopyNumber data.
Definition at line 200 of file CNCychp.h.
Member Function Documentation
int CNCychpProbeSetsCopyNumber::compareTo (CNCychpProbeSetsCopyNumber & that, int iCompareCode)
Compare function.
Parameters:
that - A reference to an instance of this class.
iCompareCode - The code to switch on when doing compares. (Each code is a different compare.)
Returns:
- int value. (-1 if *this < that, 0 if *this == that, 1 if *this > that)
Definition at line 405 of file CNCychp.cpp.
char CNCychpProbeSetsCopyNumber::getCNGain (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNGain call (0 or 1).
Parameters:
int - The sex code for this sample.
int - The numeric value associated with the X chromosome
int - The numeric value associated with the Y chromosome
Returns:
char - The call
Definition at line 444 of file CNCychp.cpp.
References affx::Male.
Referenced by getCNNeutral().
char CNCychpProbeSetsCopyNumber::getCNLoss (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNLoss call (0 or 1).
Parameters:
int - The sex code for this sample.
int - The numeric value associated with the X chromosome
int - The numeric value associated with the Y chromosome
Returns:
char - The call
Definition at line 482 of file CNCychp.cpp.
References affx::Male.
Referenced by getCNNeutral(), and CNFamilialAnalysisMethodCNLossLOHConcordance::run().
char CNCychpProbeSetsCopyNumber::getCNNeutral (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNNeutral call (0 or 1).
Parameters:
int - The sex code for this sample.
int - The numeric value associated with the X chromosome
int - The numeric value associated with the Y chromosome
Returns:
char - The call
Definition at line 432 of file CNCychp.cpp.
References getCNGain(), and getCNLoss().
Referenced by getCNNeutralLoh(), getNormalDiploid(), and CNFamilialAnalysisMethodCNNeutralLOHConcordance::run().
char CNCychpProbeSetsCopyNumber::getCNNeutralLoh (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNNeutralLOH call (0 or 1).
Parameters:
int - The sex code for this sample.
int - The numeric value associated with the X chromosome
int - The numeric value associated with the Y chromosome
Returns:
char - The call
Definition at line 519 of file CNCychp.cpp.
References getCNNeutral().
char CNCychpProbeSetsCopyNumber::getNormalDiploid (int iSexCode, int iXChromosome, int iYChromosome)
Return the NormalDiploid call (0 or 1).
Parameters:
int - The sex code for this sample.
int - The numeric value associated with the X chromosome
int - The numeric value associated with the Y chromosome
Returns:
char - The call
Definition at line 532 of file CNCychp.cpp.
References getCNNeutral().
void CNCychpProbeSetsCopyNumber::setGenotypeCallFromCode (char c)
Set the allele code ffor the genotype call from the internal representation (-1, 0, 1, 2).
Parameters:
char - The internal representation
Definition at line 388 of file CNCychp.cpp.
References ALLELE_A_CALL, ALLELE_AB_CALL, ALLELE_B_CALL, and ALLELE_NO_CALL.
The documentation for this class was generated from the following files:
copynumber/CNCychp.h
copynumber/CNCychp.cpp