Affymetrix Power Tools: dumpPgf Class Reference
dumpPgf Class Reference
Public Member Functions
dumpPgf (const char *argv[], const std::string &version)
Constructor.
~dumpPgf ()
Destructor.
void run ()
Read, process data, write output.
Public Attributes
PgOptions m_Opts
Command line options.
Detailed Description
Definition at line 42 of file DumpPgf.h.
Constructor & Destructor Documentation
dumpPgf::dumpPgf (const char * argv[], const std::string & version)
Constructor.
Parameters:
argc Number of command line arguments.
argv Command line arguments.
version Version string.
argc Number of command line arguments.
argv Command line arguments.
version Version string.
Errors: throw exception to display help messages, if unsupported option choices were made.
Definition at line 95 of file DumpPgf.cpp.
References PgOptions::argc(), PgOptions::commandLine(), Err::errAbort(), PgOptions::get(), PgOptions::getBool(), m_Opts, PgOptions::mustFindOpt(), Fs::mustOpenToWrite(), PgOptions::parseArgv(), PgOpt::push_user_values_into(), Err::setThrowStatus(), and PgOptions::usage().
Member Function Documentation
void dumpPgf::run ()
Read, process data, write output.
Errors: abort if unable to read any input file.
Definition at line 185 of file DumpPgf.cpp.
The documentation for this class was generated from the following files:
file/TsvFile/DumpPgf.h
file/TsvFile/DumpPgf.cpp