Affymetrix Power Tools: affymetrix_calvin_io::FileHeader Class Reference
affymetrix_calvin_io::FileHeader Class Reference
#include <FileHeader.h>
Public Member Functions
void Clear ()
void SetFilename (const std::string &p)
std::string GetFilename () const
u_int8_t GetMagicNumber () const
u_int8_t GetVersion () const
int32_t GetDataGroupCnt () const
void AddDataGroupHdr (const DataGroupHeader &p)
DataGroupHeader & GetDataGroup (int32_t index)
const DataGroupHeader & GetDataGroupConst (int32_t index) const
void GetDataGroupIts (DataGroupHdrIt &begin, DataGroupHdrIt &end)
void SetGenericDataHdr (const GenericDataHeader &p)
GenericDataHeader * GetGenericDataHdr ()
DataGroupHeader * FindDataGroupHeader (const std::wstring &name)
int32_t GetNumDataGroups () const
void SetNumDataGroups (int32_t value)
u_int32_t GetFirstDataGroupFilePos ()
void SetFirstDataGroupFilePos (u_int32_t value)
Detailed Description
This class defines a data container for the generic file header
Definition at line 48 of file FileHeader.h.
Member Function Documentation
DataGroupHeader * FileHeader::FindDataGroupHeader (const std::wstring & name)
Finds a DataGroupHeader by name.
Parameters:
name The name of the DataGroup
Returns:
A pointer to the DataGroupHeader. If not found, the return is 0.
Definition at line 99 of file FileHeader.cpp.
Referenced by affymetrix_calvin_io::GenericData::FindDataGroupHeader().
DataGroupHeader & FileHeader::GetDataGroup (int32_t index)
Get a DataGroupHeader by index. Max index < GetDataGroupCnt
Definition at line 65 of file FileHeader.cpp.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::CHPTilingData::AddTilingSequenceData(), affymetrix_calvin_io::GenericData::FindDataGroupHeader(), affymetrix_calvin_io::CHPData::GetBackgroundZoneCnt(), affymetrix_calvin_io::CHPMultiDataData::GetDataGroupHeader(), affymetrix_calvin_io::CHPMultiDataData::GetDataGroupIndex(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetDataSetHeader(), affymetrix_calvin_io::CHPQuantificationData::GetDataSetHeader(), affymetrix_calvin_io::CHPMultiDataData::GetDataSetHeader(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetEntryCount(), affymetrix_calvin_io::CHPQuantificationData::GetEntryCount(), affymetrix_calvin_io::CHPData::GetEntryCount(), affymetrix_calvin_io::CHPData::GetForceCnt(), affymetrix_calvin_io::CHPData::GetOrigCnt(), affymetrix_calvin_io::CHPTilingData::GetTilingSequenceEntryCount(), affymetrix_calvin_io::DataSetUpdater::Initialize(), affymetrix_calvin_io::MMDATFileWriter::MMDATFileWriter(), affymetrix_calvin_io::CHPData::SetBackgroundZoneCnt(), affymetrix_calvin_io::CHPQuantificationDetectionData::SetEntryCount(), affymetrix_calvin_io::CHPQuantificationData::SetEntryCount(), affymetrix_calvin_io::CHPData::SetEntryCount(), affymetrix_calvin_io::CHPData::SetForceCnt(), affymetrix_calvin_io::CHPData::SetOrigCnt(), CNFamilialReporterFamilial::setupDataSetHeaderPaternityTesting(), CNFamilialReporterFamilial::setupDataSetHeaderSamples(), CNFamilialReporterFamilial::setupDataSetHeaderSegmentOverlaps(), and CNFamilialReporterFamilial::setupDataSetHeaderSegments().
int32_t FileHeader::GetDataGroupCnt () const
Get the number of DataGroupHeaders added
Definition at line 91 of file FileHeader.cpp.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::GenericData::DataGroupCnt(), affymetrix_calvin_io::GenericData::FindDataGroupHeader(), affymetrix_calvin_io::DataSetUpdater::Initialize(), affymetrix_calvin_io::GenericFileReader::ReadFileHeader(), and affymetrix_calvin_io::GenericFileReader::ReadFileHeaderMinDP().
std::string FileHeader::GetFilename () const
Definition at line 45 of file FileHeader.cpp.
Referenced by affymetrix_calvin_io::CelFileData::Exists(), affymetrix_calvin_io::DATData::GetFilename(), and affymetrix_calvin_io::CDFData::GetFilename().
u_int32_t affymetrix_calvin_io::FileHeader::GetFirstDataGroupFilePos () [inline]
Get the file position to the first DataGroup
Definition at line 96 of file FileHeader.h.
Referenced by affymetrix_calvin_io::CDFData::GetProbeSetName(), affymetrix_calvin_io::DataGroupHeaderReader::ReadAll(), and affymetrix_calvin_io::DataGroupHeaderReader::ReadAllMinimumInfo().
int32_t affymetrix_calvin_io::FileHeader::GetNumDataGroups () const [inline]
Get the number of DataGroups in a file.
Definition at line 92 of file FileHeader.h.
Referenced by affymetrix_calvin_io::CHPMultiDataData::GetDataGroupHeader(), affymetrix_calvin_io::CHPMultiDataData::GetDataGroupIndex(), affymetrix_calvin_io::CHPMultiDataData::GetDataSetHeader(), affymetrix_calvin_io::CDFData::GetProbeSetInformation(), and affymetrix_calvin_io::CDFData::GetQCProbeSetInformation().
void FileHeader::SetFilename (const std::string & p)
Definition at line 40 of file FileHeader.cpp.
Referenced by affymetrix_calvin_io::GenericFileReader::ReadFileHeader(), affymetrix_calvin_io::GenericFileReader::ReadFileHeaderMinDP(), affymetrix_calvin_io::GenericFileReader::ReadFileHeaderNoDataGroupHeader(), affymetrix_calvin_io::DATData::SetFilename(), affymetrix_calvin_io::CHPTilingData::SetFilename(), affymetrix_calvin_io::CHPQuantificationDetectionData::SetFilename(), affymetrix_calvin_io::CHPQuantificationData::SetFilename(), affymetrix_calvin_io::CHPMultiDataData::SetFilename(), affymetrix_calvin_io::CHPData::SetFilename(), affymetrix_calvin_io::CelFileData::SetFilename(), affymetrix_calvin_io::CDFData::SetFilename(), CNFamilialReporterFamilial::setupHeader(), and affymetrix_calvin_io::GridControlFileWriter::Write().
void affymetrix_calvin_io::FileHeader::SetFirstDataGroupFilePos (u_int32_t value) [inline]
Set the file postion to the first DataGroup. Method should be protected. It is set when the object is being read.
Definition at line 98 of file FileHeader.h.
Referenced by affymetrix_calvin_io::FileHeaderReader::ReadFirstDataGroupFilePos().
void affymetrix_calvin_io::FileHeader::SetNumDataGroups (int32_t value) [inline]
Set the number of DataGroups. Set when reading a file
Definition at line 94 of file FileHeader.h.
Referenced by affymetrix_calvin_io::CHPMultiDataData::CHPMultiDataData(), and affymetrix_calvin_io::FileHeaderReader::ReadDataGroupCnt().
The documentation for this class was generated from the following files:
calvin_files/data/src/FileHeader.h
calvin_files/data/src/FileHeader.cpp