Affymetrix Power Tools: CNAnalysisMethodLOHCytoScan Class Reference
CNAnalysisMethodLOHCytoScan Class Reference
The LOH analysis method.
#include <CNAnalysisMethodLOHCytoScan.h>