Affymetrix Power Tools: GenotypeTableModel Class Reference
GenotypeTableModel Class Reference