Affymetrix Power Tools: affx::File5_Group Class Reference
affx::File5_Group Class Reference