Affymetrix Power Tools: SampleInfoTableModel Class Reference
SampleInfoTableModel Class Reference