Affymetrix Power Tools: QuantMethodTransform Class Reference
QuantMethodTransform Class Reference