Affymetrix Power Tools: CNAnalysisMethodAllelicDifference Class Reference
CNAnalysisMethodAllelicDifference Class Reference
The AllelicDifference analysis method.
#include <CNAnalysisMethodAllelicDifference.h>