Affymetrix Power Tools: MixedFileCheck Class Reference
MixedFileCheck Class Reference
Class for testing whether two files, containing both text and numeric data, are equal, within tolerances for numeric data, ignoring line endings.
#include <MixedFileCheck.h>