Affymetrix Power Tools: affymetrix_calvin_io::GenericDataHeaderUpdater Class Reference
affymetrix_calvin_io::GenericDataHeaderUpdater Class Reference
#include <GenericDataHeaderUpdater.h>
Public Member Functions
GenericDataHeaderUpdater ()
~GenericDataHeaderUpdater ()
bool Update (std::ofstream &fileStream, GenericDataHeader &updateHeader, GenericDataHeader &currentHdr)
bool UpdateFileId ()
void UpdateParameters ()
Static Public Attributes
static const int32_t FIELD_LEN_SIZE = sizeof(int32_t)
Detailed Description
This class updates the GenericDataHeader of an existing file with new information.
Definition at line 39 of file GenericDataHeaderUpdater.h.
Constructor & Destructor Documentation
GenericDataHeaderUpdater::GenericDataHeaderUpdater ()
Constructor
Definition at line 37 of file GenericDataHeaderUpdater.cpp.
GenericDataHeaderUpdater::~GenericDataHeaderUpdater ()
Destructor
Definition at line 47 of file GenericDataHeaderUpdater.cpp.
Member Function Documentation
bool GenericDataHeaderUpdater::Update (std::ofstream & fileStream, GenericDataHeader & updateHeader, GenericDataHeader & currentHdr)
Update the file with the new GenericDataHeader information. The current implementation just updates the FileId.
Parameters:
fileStream An output stream open with std::ios::out|stdios::binary|stdios::in.
updateHeader A GenericDataHeader with information to update the file.
currentHdr The GenericDataHeader object with the information currently in the file.
Returns:
Returns true if the FileId could be udpated.
Definition at line 54 of file GenericDataHeaderUpdater.cpp.
References UpdateFileId(), and UpdateParameters().
Referenced by QuantMethodMultiDataCCCHPReport::finish(), QuantMethodExprCCCHPReport::finish(), and affymetrix_calvin_io::FileHeaderUpdater::Update().
bool GenericDataHeaderUpdater::UpdateFileId ()
Update the FileId. Only update the FileId if update and current fileIDs are the same size.
Returns:
Returns true if successful.
Definition at line 68 of file GenericDataHeaderUpdater.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetFileId(), affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), and affymetrix_calvin_io::FileOutput::WriteString8().
Referenced by Update().
void GenericDataHeaderUpdater::UpdateParameters ()
Update the parameter list. Can only update types that have the same name and type and value size in the source and target
Definition at line 89 of file GenericDataHeaderUpdater.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::GetMIMEValue(), affymetrix_calvin_io::GenericDataHeader::GetNameValIterators(), affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::MIMEValue::GetValue(), affymetrix_calvin_parameter::MIMEValue::Size(), and affymetrix_calvin_io::FileOutput::WriteBlob().
Referenced by Update().
The documentation for this class was generated from the following files:
calvin_files/writers/src/GenericDataHeaderUpdater.h
calvin_files/writers/src/GenericDataHeaderUpdater.cpp