Affymetrix Power Tools: affymetrix_calvin_io::CHPQuantificationDetectionData Class Reference
affymetrix_calvin_io::CHPQuantificationDetectionData Class Reference
#include <CHPQuantificationDetectionData.h>
Public Member Functions
CHPQuantificationDetectionData ()
CHPQuantificationDetectionData (const std::string &filename)
~CHPQuantificationDetectionData ()
int GetMaxProbeSetName () const
void Clear ()
void SetFilename (const std::string &p)
std::string GetFilename () const
std::wstring GetArrayType ()
void SetArrayType (const std::wstring &value)
void SetEntryCount (int32_t ln, int32_t maxln)
void SetEntryCount (int32_t ln)
int32_t GetEntryCount ()
std::wstring GetAlgName ()
void SetAlgName (const std::wstring &value)
std::wstring GetAlgVersion ()
void SetAlgVersion (const std::wstring &value)
ParameterNameValueTypeList GetAlgParams ()
void AddAlgParams (const ParameterNameValueTypeList &params)
ParameterNameValueTypeList GetSummaryParams ()
void AddSummaryParams (const ParameterNameValueTypeList &params)
FileHeader * GetFileHeader ()
GenericData & GetGenericData ()
void GetQuantificationDetectionEntry (int index, affymetrix_calvin_data::ProbeSetQuantificationDetectionData &entry)
void OpenQuantificationDetectionDataSet ()
DataSetHeader & GetDataSetHeader ()
Detailed Description
Holds data associated with quantification/detection CHP files.
Definition at line 40 of file CHPQuantificationDetectionData.h.
Constructor & Destructor Documentation
CHPQuantificationDetectionData::CHPQuantificationDetectionData ()
Constructor
Definition at line 46 of file CHPQuantificationDetectionData.cpp.
References Clear().
CHPQuantificationDetectionData::CHPQuantificationDetectionData (const std::string & filename)
Constructor with file name.
Parameters:
filename The name of the CHP file.
Definition at line 54 of file CHPQuantificationDetectionData.cpp.
References Clear(), affymetrix_calvin_io::GenericData::Header(), SetFilename(), and affymetrix_calvin_io::GenericDataHeader::SetFileTypeId().
CHPQuantificationDetectionData::~CHPQuantificationDetectionData ()
Destructor
Definition at line 66 of file CHPQuantificationDetectionData.cpp.
References Clear().
Member Function Documentation
void CHPQuantificationDetectionData::AddAlgParams (const ParameterNameValueTypeList & params)
Adds the algorithm parameters.
Parameters:
params The algorithm parameters.
Definition at line 222 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), ALGORITHM_PARAM_NAME_PREFIX_S, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
void CHPQuantificationDetectionData::AddSummaryParams (const ParameterNameValueTypeList & params)
Adds the summary parameters.
Parameters:
params The summary parameters.
Definition at line 256 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), CHIP_SUMMARY_PARAMETER_NAME_PREFIX_S, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
void CHPQuantificationDetectionData::Clear ()
Clears the members.
Definition at line 76 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::DataSet::Delete(), and affymetrix_calvin_io::GenericData::Header().
Referenced by CHPQuantificationDetectionData(), affymetrix_calvin_io::CHPQuantificationDetectionFileReader::Read(), ~CHPQuantificationDetectionData(), and affymetrix_fusion_io::FusionCHPQuantificationDetectionData::~FusionCHPQuantificationDetectionData().
std::wstring CHPQuantificationDetectionData::GetAlgName ()
Gets the name of the algorithm.
Returns:
The algorithm name.
Definition at line 180 of file CHPQuantificationDetectionData.cpp.
References ALGORITHM_NAME_PARAM_NAME.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetAlgName().
ParameterNameValueTypeList CHPQuantificationDetectionData::GetAlgParams ()
Gets the algorithm parameters
Returns:
The algoirhtm parameters.
Definition at line 200 of file CHPQuantificationDetectionData.cpp.
References ALGORITHM_PARAM_NAME_PREFIX_S, affymetrix_calvin_io::GenericDataHeader::GetNameValIterators(), affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetAlgParams().
std::wstring CHPQuantificationDetectionData::GetAlgVersion ()
Gets the algorithm version.
Returns:
The version.
Definition at line 190 of file CHPQuantificationDetectionData.cpp.
References ALG_VERSION_PARAM_NAME.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetAlgVersion().
std::wstring CHPQuantificationDetectionData::GetArrayType ()
Sets the array type
Definition at line 170 of file CHPQuantificationDetectionData.cpp.
References ARRAY_TYPE_PARAM_NAME.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetArrayType().
DataSetHeader & CHPQuantificationDetectionData::GetDataSetHeader ()
Returns the data set header.
Definition at line 71 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetDataSetHeader().
int32_t CHPQuantificationDetectionData::GetEntryCount ()
Gets the number of entries (probe sets)
Definition at line 92 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetEntryCount().
FileHeader* affymetrix_calvin_io::CHPQuantificationDetectionData::GetFileHeader () [inline]
Gets the file header.
Returns:
The file header.
Definition at line 148 of file CHPQuantificationDetectionData.h.
References affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::CHPQuantificationDetectionFileWriter().
std::string CHPQuantificationDetectionData::GetFilename () const
Gets the file name.
Returns:
The file name.
Definition at line 87 of file CHPQuantificationDetectionData.cpp.
Referenced by affymetrix_calvin_io::CHPQuantificationDetectionFileReader::Read().
GenericData& affymetrix_calvin_io::CHPQuantificationDetectionData::GetGenericData () [inline]
Gets the generic data object.
Returns:
The data object.
Definition at line 153 of file CHPQuantificationDetectionData.h.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::FileId(), affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetGenericData(), and affymetrix_calvin_io::CHPQuantificationDetectionFileReader::Read().
int affymetrix_calvin_io::CHPQuantificationDetectionData::GetMaxProbeSetName () const [inline]
The maximum length of a probe set name.
Definition at line 70 of file CHPQuantificationDetectionData.h.
Referenced by affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::CHPQuantificationDetectionFileWriter().
void CHPQuantificationDetectionData::GetQuantificationDetectionEntry (int index, affymetrix_calvin_data::ProbeSetQuantificationDetectionData & entry)
Gets the sequence data.
Parameters:
index The row index.
entry The quantification/detection value.
Definition at line 125 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::id, affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::name, OpenQuantificationDetectionDataSet(), affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::pvalue, and affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::quantification.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetQuantificationDetectionEntry().
ParameterNameValueTypeList CHPQuantificationDetectionData::GetSummaryParams ()
Gets the summary parameters
Returns:
The summary parameters.
Definition at line 234 of file CHPQuantificationDetectionData.cpp.
References CHIP_SUMMARY_PARAMETER_NAME_PREFIX_S, affymetrix_calvin_io::GenericDataHeader::GetNameValIterators(), affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetSummaryParams().
void CHPQuantificationDetectionData::OpenQuantificationDetectionDataSet ()
Opens a group for reading.
Definition at line 157 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::GenericData::DataSet(), affymetrix_calvin_io::DataSetHeader::GetColumnInfo(), affymetrix_calvin_io::ColumnInfo::GetColumnType(), affymetrix_calvin_io::DataSet::Header(), and affymetrix_calvin_io::DataSet::Open().
Referenced by GetQuantificationDetectionEntry().
void CHPQuantificationDetectionData::SetAlgName (const std::wstring & value)
Sets the name of the algorithm.
Parameters:
value The algorithm name.
Definition at line 185 of file CHPQuantificationDetectionData.cpp.
References ALGORITHM_NAME_PARAM_NAME.
void CHPQuantificationDetectionData::SetAlgVersion (const std::wstring & value)
Sets the algorithm version.
Parameters:
value The version.
Definition at line 195 of file CHPQuantificationDetectionData.cpp.
References ALG_VERSION_PARAM_NAME.
void CHPQuantificationDetectionData::SetArrayType (const std::wstring & value)
Sets the array type.
Definition at line 175 of file CHPQuantificationDetectionData.cpp.
References ARRAY_TYPE_MAX_LEN, and ARRAY_TYPE_PARAM_NAME.
void CHPQuantificationDetectionData::SetEntryCount (int32_t ln)
Sets the number of entries (probe sets). Use this function if ids are to be stored.
Parameters:
ln The number of probe sets.
Definition at line 112 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CHPQuantificationDetectionData::SetEntryCount (int32_t ln, int32_t maxln)
Sets the number of entries (probe sets). Use this function if names are to be stored.
Parameters:
ln The number of probe sets.
maxln The maximum length of a probe set name.
Definition at line 99 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CHPQuantificationDetectionData::SetFilename (const std::string & p)
Sets the file name.
Parameters:
p The name of the CHP file
Definition at line 82 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_io::FileHeader::SetFilename().
Referenced by CHPQuantificationDetectionData().
The documentation for this class was generated from the following files:
calvin_files/data/src/CHPQuantificationDetectionData.h
calvin_files/data/src/CHPQuantificationDetectionData.cpp