Affymetrix Power Tools: CNAnalysisMethod Class Reference
CNAnalysisMethod Class Reference
A base class for copy number analysis methods.
#include <CNAnalysisMethod.h>