Affymetrix Power Tools: HomHiLoCelListener Class Reference
HomHiLoCelListener Class Reference
Class for computing hilo qc metric from a cel set of cel files.
#include <HomHiLoCelListener.h>