Affymetrix Power Tools: TranslationInputStreamTableModel Class Reference
TranslationInputStreamTableModel Class Reference