Affymetrix Power Tools: affymetrix_chp_converter::CHPFileConvertToXDA Class Reference
affymetrix_chp_converter::CHPFileConvertToXDA Class Reference
#include <CHPFileConvertToXDA.h>
Public Member Functions
CHPFileConvertToXDA ()
~CHPFileConvertToXDA ()
void SetExtraParameters (const affymetrix_calvin_parameter::ParameterNameValueTypeVector *params)
CHPFileConverterErrorCode ErrorCode () const
void SetParentFileName (const char *str)
bool ConvertCalvinFile (const char *fileName, const char *newFile)
Detailed Description
This class will convert a CHP file to XDA format.
Definition at line 35 of file CHPFileConvertToXDA.h.
Constructor & Destructor Documentation
CHPFileConvertToXDA::CHPFileConvertToXDA ()
Constructor
Definition at line 44 of file CHPFileConvertToXDA.cpp.
CHPFileConvertToXDA::~CHPFileConvertToXDA ()
Destructor
Definition at line 61 of file CHPFileConvertToXDA.cpp.
Member Function Documentation
bool CHPFileConvertToXDA::ConvertCalvinFile (const char * fileName, const char * newFile)
Convert the Calvin file to XDA format.
Parameters:
fileName The full path name of the CHP file.
newFile The name of the new CHP file.
Returns:
True if successful.
Definition at line 69 of file CHPFileConvertToXDA.cpp.
References affymetrix_chp_converter::CHPConversionUtilities::Copy(), affxchpwriter::CCHPFileWriter::CreateNewFile(), affxchp::CCHPFileData::GetHeader(), affymetrix_calvin_io::CHPFileReader::Read(), affxchpwriter::CCHPFileWriter::Save(), affxchp::CCHPFileHeader::SetChipType(), affxchp::CCHPFileData::SetFileName(), affymetrix_calvin_io::CHPFileReader::SetFilename(), and affxchpwriter::CCHPFileWriter::SetParentCelFileName().
CHPFileConverterErrorCode affymetrix_chp_converter::CHPFileConvertToXDA::ErrorCode () const [inline]
Gets the error code for the conversion process.
Returns:
The error code associated with the last failure.
Definition at line 53 of file CHPFileConvertToXDA.h.
void affymetrix_chp_converter::CHPFileConvertToXDA::SetExtraParameters (const affymetrix_calvin_parameter::ParameterNameValueTypeVector * params) [inline]
Set extra parameters that are to be written to the file.
Parameters:
params A collection of ParameterNameValueTypes to add to the file.
Definition at line 48 of file CHPFileConvertToXDA.h.
void affymetrix_chp_converter::CHPFileConvertToXDA::SetParentFileName (const char * str) [inline]
The full path and name of the parent file.
Parameters:
str The full path and name of the parent file.
Definition at line 58 of file CHPFileConvertToXDA.h.
The documentation for this class was generated from the following files:
calvin_files/converters/chp/src/CHPFileConvertToXDA.h
calvin_files/converters/chp/src/CHPFileConvertToXDA.cpp