Affymetrix Power Tools: CNAnalysisMethodReference Class Reference
CNAnalysisMethodReference Class Reference
The Reference Analysis Method.
#include <CNAnalysisMethodReference.h>