Affymetrix Power Tools: midasConfigureRun Class Reference
midasConfigureRun Class Reference
midasConfigureRun
#include <MidasConfigureRun.h>
Public Member Functions
midasConfigureRun (std::string celsFileName, std::string geneDataFileName, std::string exonDataFileName, std::string metaFileName, std::string outputDirectory, const bool wantPvalues, const bool wantFstats, const bool wantNormalized, const float &logStabilize, const std::string &commandLine, const std::string &execVersion, const bool noLogTransform=false, const bool keepPath=false)
Constructor.
std::string * configure ()
Set up for run.
void run ()
Read, process data, write output.
void deleteOutputs_1 (bool want, std::string filename)
Delete output files.
void deleteOutputs ()
void throwIfFileExists (std::string fileName)
Detailed Description
midasConfigureRun
Object for midasConfigureRun.
Definition at line 44 of file MidasConfigureRun.h.
Constructor & Destructor Documentation
midasConfigureRun::midasConfigureRun (std::string celsFileName, std::string geneDataFileName, std::string exonDataFileName, std::string metaFileName, std::string outputDirectory, const bool wantPvalues, const bool wantFstats, const bool wantNormalized, const float & logStabilize, const std::string & commandLine, const std::string & execVersion, const bool noLogTransform = false, const bool keepPath = false)
Constructor.
Parameters:
celsFileName Cels file name.
geneDataFileName Gene data file name.
exonDataFileName Exon data file name.
metaFileName Meta probeset file name.
outputDirectory Output directory.
wantPvalues Caller requests p values.
wantFstats Caller requests F statistics.
wantNormalized Caller requests normalized exon signal.
logStabilize Amount to add to data before taking logarithm.
commandLine User command line.
execVersion Version, cvs id string.
noLogTransform Do not log transform data.
keepPath Keep cel file path.
Copy input file names, output directory name, flags, and log stabilization factor to local storage. option checks.
Parameters:
celsFileName Cels file name.
geneDataFileName Gene data file name.
exonDataFileName Exon data file name.
metaFileName meta probeset file name.
wantPvalues Caller requests p values.
wantFstats Caller requests F statistics.
wantNormalized Caller requests normalized exon signal.
logStabilize Amount to add to data before taking logarithm.
commandLine Copy of the command line, for output tag.
execVersion Version, cvs id string.
noLogTransform Do not log transform data.
keepPath Keep cel file path.
Errors: exception if no output chosen
Definition at line 100 of file MidasConfigureRun.cpp.
References Err::errAbort().
Member Function Documentation
std::string * midasConfigureRun::configure ()
Set up for run.
Returns:
pointer to non-fatal warning message
Definition at line 417 of file MidasConfigureRun.cpp.
References affxutil::Guid::GenerateNewGuid(), Util::getTimeStamp(), and Fs::join().
void midasConfigureRun::run (void)
Read, process data, write output.
Todo:
why do we have to copy it to another bucket?
Definition at line 489 of file MidasConfigureRun.cpp.
References affx::TSV_ADD_ALL.
The documentation for this class was generated from the following files:
midas/MidasConfigureRun.h
midas/MidasConfigureRun.cpp