Affymetrix Power Tools: QuantLabelZMulti Class Reference
QuantLabelZMulti Class Reference