Affymetrix Power Tools: affymetrix_cel_converter::CELFileConvertToCalvin Class Reference
affymetrix_cel_converter::CELFileConvertToCalvin Class Reference
#include <CELFileConvertToCalvin.h>
Public Member Functions
CELFileConvertToCalvin ()
~CELFileConvertToCalvin ()
void SetArrayID (const char *str)
void SetArrayBarcode (const wchar_t *str)
void SetParentFileName (const char *str)
void SetExtraParameters (const affymetrix_calvin_parameter::ParameterNameValueTypeVector *params)
CELFileConverterErrorCode ErrorCode () const
bool ConvertASCIIFile (const char *fileName, const char *newFile, CELFileConversionOptions *options=NULL)
bool ConvertXDAFile (const char *fileName, const char *newFile, CELFileConversionOptions *options=NULL, const char *datFileName=NULL)
Protected Member Functions
bool FillParentGenericDataHeader (affymetrix_calvin_io::GenericDataHeader &hdr, affxcel::CCELFileData &inFile)
bool GetParentGenericDataHeader (affymetrix_calvin_io::GenericDataHeader &hdr)
bool GenerateParentGenericDataHeaderFromGCOS (affymetrix_calvin_io::GenericDataHeader &hdr, affxcel::CCELFileData &inFile)
void AddExtraParameters (affymetrix_calvin_io::CelFileData &data)
std::wstring GetScannerTypeFromExtraParameters ()
Detailed Description
This class will convert a CEL file to Calvin format.
Definition at line 37 of file CELFileConvertToCalvin.h.
Constructor & Destructor Documentation
CELFileConvertToCalvin::CELFileConvertToCalvin ()
Constructor
Definition at line 49 of file CELFileConvertToCalvin.cpp.
CELFileConvertToCalvin::~CELFileConvertToCalvin ()
Destructor
Definition at line 67 of file CELFileConvertToCalvin.cpp.
Member Function Documentation
void CELFileConvertToCalvin::AddExtraParameters (affymetrix_calvin_io::CelFileData & data) [protected]
Adds any extra parameters from the extraParameter collection to the file header.
Parameters:
data The target CelFileData.
Definition at line 589 of file CELFileConvertToCalvin.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), and affymetrix_calvin_io::CelFileData::GetFileHeader().
Referenced by ConvertXDAFile().
bool CELFileConvertToCalvin::ConvertASCIIFile (const char * fileName, const char * newFile, CELFileConversionOptions * options = NULL)
Convert the file to Calvin format.
Parameters:
fileName The full path name of the CEL file.
newFile The name of the new CEL file.
Returns:
True if successful.
Definition at line 75 of file CELFileConvertToCalvin.cpp.
References ConvertXDAFile().
Referenced by affymetrix_cel_converter::CELFileConverter::ConvertFile().
bool CELFileConvertToCalvin::ConvertXDAFile (const char * fileName, const char * newFile, CELFileConversionOptions * options = NULL, const char * datFileName = NULL)
Convert the file to Calvin format.
Parameters:
fileName The full path name of the CEL file.
newFile The name of the new CEL file.
Returns:
True if successful.
Definition at line 84 of file CELFileConvertToCalvin.cpp.
References affymetrix_calvin_io::CelFileData::AddAlgorithmParameter(), AddExtraParameters(), affymetrix_calvin_io::GenericDataHeader::AddParent(), FillParentGenericDataHeader(), affxcel::CCELFileHeaderData::GetAlg(), affxcel::CCELFileHeaderData::GetAlgorithmParameter(), affxcel::CCELFileHeaderData::GetAlgorithmParameterTag(), affxcel::CCELFileHeaderData::GetCells(), affxcel::CCELFileHeaderData::GetChipType(), affxcel::CCELFileHeaderData::GetCols(), affymetrix_calvin_io::DATData::GetFileHeader(), affymetrix_calvin_io::CelFileData::GetFileHeader(), affxcel::CCELFileData::GetGridCorners(), affxcel::CCELFileData::GetHeader(), affxcel::CCELFileData::GetIntensity(), affxcel::CCELFileHeaderData::GetMasked(), affxcel::CCELFileHeaderData::GetNumberAlgorithmParameters(), affxcel::CCELFileHeaderData::GetOutliers(), affxcel::CCELFileData::GetPixels(), affxcel::CCELFileHeaderData::GetRows(), affxcel::CCELFileData::GetStdv(), GRIDLLX_PARAM_NAME, GRIDLLY_PARAM_NAME, GRIDLRX_PARAM_NAME, GRIDLRY_PARAM_NAME, GRIDULX_PARAM_NAME, GRIDULY_PARAM_NAME, GRIDURX_PARAM_NAME, GRIDURY_PARAM_NAME, affxcel::CCELFileData::IndexToX(), affxcel::CCELFileData::IndexToY(), affxcel::CCELFileData::IsMasked(), affxcel::CCELFileData::IsOutlier(), _GridCoordinatesType::lowerleft, _GridCoordinatesType::lowerright, affymetrix_cel_converter::CELFileConversionOptions::m_ChipType, affymetrix_calvin_io::DATFileReader::Read(), affxcel::CCELFileData::Read(), affymetrix_calvin_io::CelFileData::SetAlgorithmName(), affymetrix_calvin_io::CelFileData::SetArrayType(), affymetrix_calvin_io::CelFileData::SetCols(), affymetrix_calvin_io::DATFileReader::SetFilename(), affxcel::CCELFileData::SetFileName(), affymetrix_calvin_io::GenericDataHeader::SetFileTypeId(), affymetrix_calvin_io::CelFileData::SetIntensityCount(), affymetrix_calvin_io::CelFileData::SetMaskCount(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), affymetrix_calvin_io::CelFileData::SetOutlierCount(), affymetrix_calvin_io::CelFileData::SetPixelCount(), affymetrix_calvin_io::CelFileData::SetRows(), affymetrix_calvin_io::CelFileData::SetStdDevCount(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueFloat(), _GridCoordinatesType::upperleft, _GridCoordinatesType::upperright, _CoordinatePoint::x, and _CoordinatePoint::y.
Referenced by ConvertASCIIFile(), and affymetrix_cel_converter::CELFileConverter::ConvertFile().
CELFileConverterErrorCode affymetrix_cel_converter::CELFileConvertToCalvin::ErrorCode () const [inline]
Gets the error code for the conversion process.
Returns:
The error code associated with the last failure.
Definition at line 70 of file CELFileConvertToCalvin.h.
Referenced by affymetrix_cel_converter::CELFileConverter::ConvertFile().
bool CELFileConvertToCalvin::FillParentGenericDataHeader (affymetrix_calvin_io::GenericDataHeader & hdr, affxcel::CCELFileData & inFile) [protected]
Fills the GenericDataHeader with the parent file header which it gets either from the parent file or generates based on the GCOS CEL file.
Parameters:
hdr The GenericDataHeader that will be filled with the parent file header information.
inFile The GCOS CEL file.
Definition at line 294 of file CELFileConvertToCalvin.cpp.
References GenerateParentGenericDataHeaderFromGCOS(), and GetParentGenericDataHeader().
Referenced by ConvertXDAFile().
bool CELFileConvertToCalvin::GenerateParentGenericDataHeaderFromGCOS (affymetrix_calvin_io::GenericDataHeader & hdr, affxcel::CCELFileData & inFile) [protected]
Generates a parent GenericDataHeader based on the GCOS CEL file. If the arrayID member is set, it will be added to the parent header.
Parameters:
hdr The GenericDataHeader that will be filled with the parent information.
TODO: Check that this works
TODO: End check
Definition at line 332 of file CELFileConvertToCalvin.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), ARRAY_TYPE_PARAM_NAME, COLS_PARAM_NAME, DAT_HEADER_PARAM_NAME, FILTER_PARAM_NAME, affxcel::CCELFileHeaderData::GetChipType(), affxcel::CCELFileHeaderData::GetDatHeader(), affxcel::CCELFileData::GetHeader(), affymetrix_calvin_parameter::ParameterNameValueType::GetName(), GetScannerTypeFromExtraParameters(), affymetrix_cel_converter::CELFileConversionOptions::m_ChipType, affymetrix_cel_converter::CELFileConversionOptions::m_DATFileName, ORIENTATION_PARAM_NAME, PIXEL_SIZE_PARAM_NAME, ROWS_PARAM_NAME, SCAN_ACQUISITION_DATA_TYPE, SCAN_DATE_PARAM_NAME, SCANNER_ID_PARAM_NAME, SCANNER_TYPE_PARAM_NAME, affymetrix_calvin_io::GenericDataHeader::SetFileId(), affymetrix_calvin_io::GenericDataHeader::SetFileTypeId(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueText(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueUInt8().
Referenced by FillParentGenericDataHeader().
bool CELFileConvertToCalvin::GetParentGenericDataHeader (affymetrix_calvin_io::GenericDataHeader & hdr) [protected]
Gets the GenericDataHeader from the parent Command Console file. The arrayID member is ignored.
Parameters:
hdr The GenericDataHeader that will be filled with the parent file information.
Returns:
True if the parent file GenericDataHeader information was found.
Definition at line 306 of file CELFileConvertToCalvin.cpp.
References affymetrix_calvin_io::DATData::GetFileHeader(), affymetrix_calvin_io::DATFileReader::Read(), and affymetrix_calvin_io::DATFileReader::SetFilename().
Referenced by FillParentGenericDataHeader().
std::wstring CELFileConvertToCalvin::GetScannerTypeFromExtraParameters () [protected]
Gets the scanner type from the extra parameters.
Returns:
Scanner type
Definition at line 611 of file CELFileConvertToCalvin.cpp.
Referenced by GenerateParentGenericDataHeaderFromGCOS().
void affymetrix_cel_converter::CELFileConvertToCalvin::SetArrayBarcode (const wchar_t * str) [inline]
Set the array barcode.
Parameters:
str The array barcode.
Definition at line 55 of file CELFileConvertToCalvin.h.
void affymetrix_cel_converter::CELFileConvertToCalvin::SetArrayID (const char * str) [inline]
Set the physical array id.
Parameters:
str The physical array id.
Definition at line 50 of file CELFileConvertToCalvin.h.
void affymetrix_cel_converter::CELFileConvertToCalvin::SetExtraParameters (const affymetrix_calvin_parameter::ParameterNameValueTypeVector * params) [inline]
Set extra parameters that are to be written to the file.
Parameters:
params A collection of ParameterNameValueTypes to add to the file.
Definition at line 65 of file CELFileConvertToCalvin.h.
void affymetrix_cel_converter::CELFileConvertToCalvin::SetParentFileName (const char * str) [inline]
The full path and name of the parent file.
Parameters:
str The full path and name of the parent file.
Definition at line 60 of file CELFileConvertToCalvin.h.
The documentation for this class was generated from the following files:
calvin_files/converters/cel/src/CELFileConvertToCalvin.h
calvin_files/converters/cel/src/CELFileConvertToCalvin.cpp