Affymetrix Power Tools: CNCychp Class Reference
CNCychp Class Reference
A class for accessing and storing Cychp data.
#include <CNCychp.h>
Public Member Functions
CNCychp ()
CNCychp constructor.
virtual ~CNCychp ()
CNCychp destructor.
AffxString getFileName ()
void setFileName (const AffxString &str)
AffxString getARRGuid ()
void setARRGuid (const AffxString &str)
CNCychpHeader & getCychpHeader ()
CNCychpChromosomesSummaries & getCychpChromosomesSummaries ()
CNCychpProbeSetsCopyNumbers & getCychpProbeSetsCopyNumbers ()
CNCychpSegments & getCychpSegments ()
void clear ()
Initialize the CNCychp data and free any memory allocated.
void warning (const AffxString &strMessage)
Warning handling for the CNCychp class.
void error (const AffxString &strMessage)
Error handling for the CNCychp class.
bool readFile (const AffxString &strFileName, AffxArray< CNCychpProbeSetsCopyNumber > &vProbeSets, bool bLoadProbeSetName=true, bool bNonNanOnly=false)
Read the CNCychp file, and store the data in memory.
bool readFile (const AffxString &strFileName, const AffxString &strFamilialType, const AffxString &strPrompt="")
Read the CNCychp file, and store the data in memory.
bool readFile (const AffxString &strFileName, const groupDatasets_t &groupDatasets, const AffxString &strFamilialType, const AffxString &strPrompt="")
Selectively read the CNCychp file, and store the data in memory.
AffxString getGuidFromARRFile (const std::string &strFileName)
Load GUD from an XML file.
AffxString & getFamilialType ()
void setFamilialType (const AffxString &str)
unsigned char getFamilialCall ()
void setFamilialCall (unsigned char uc)
float getFamilialConfidence ()
void setFamilialConfidence (float f)
unsigned char getFamilialDuoCall ()
void setFamilialDuoCall (unsigned char uc)
float getFamilialDuoConfidence ()
void setFamilialDuoConfidence (float f)
AffxString getSelectedQC ()
void setSelectedQC (const AffxString &str)
Static Public Attributes
static std::map< unsigned char,
unsigned int > m_mMarkerCount
For Mendelian Inheritance Error (MIE) results.
static std::map< unsigned char,
int > m_mMIE_Trio
static std::map< unsigned char,
int > m_mMIE_Mat
static std::map< unsigned char,
int > m_mMIE_Pat
Protected Member Functions
void loadHeader (affymetrix_calvin_io::GenericDataHeader *pHeader)
Load the CNCychp header into memory.
void loadDataSet (const AffxString &strDataGroupName, const AffxString &strDataSetName, unsigned int uiDataSetIndex, affymetrix_calvin_io::DataSet *pDataSet)
Load the CNCychp DataSet into memory.
void loadDataSet (const AffxString &strDataGroupName, const AffxString &strDataSetName, unsigned int uiDataSetIndex, affymetrix_calvin_io::DataSet *pDataSet, AffxArray< CNCychpProbeSetsCopyNumber > &vProbeSets, bool bLoadProbeSetName=true, bool bNonNaNOnly=false)
Load the CNCychp DataSet into memory.
void setCnCalls ()
Determine the CN call values from the CycchpSegments data and set the CNCychpProbeSetsCopyNumber accordingly.
void setLohCalls ()
Determine the LOH call values from the CNCychpSegments data and set the CNCychpProbeSetsCopyNumber accordingly.
bool isGroupPresent (const groupDatasets_t &groupDatasets, const AffxString &groupName)
Helper function: is the given group name present in the given group/dataset map.
bool isGroupDatasetPresent (const groupDatasets_t &groupDatasets, const AffxString &groupName, const AffxString &datasetName)
Helper function: is the given group name AND dataset present in the given group/dataset map.
bool isGroupRedundant (const AffxString &groupName)
Detailed Description
A class for accessing and storing Cychp data.
Definition at line 432 of file CNCychp.h.
Member Function Documentation
void CNCychp::error (const AffxString & strMessage)
Error handling for the CNCychp class.
Parameters:
strMessage - The error messagae to report.
Definition at line 892 of file CNCychp.cpp.
References clear(), and Err::errAbort().
Referenced by loadDataSet(), loadHeader(), and readFile().
AffxString CNCychp::getGuidFromARRFile (const std::string & strFileName)
Load GUD from an XML file.
Parameters:
strFileName - The name of the XML file to load parameters from.
Definition at line 1532 of file CNCychp.cpp.
References Err::errAbort(), and ARRSAXHandler::toString().
bool CNCychp::isGroupDatasetPresent (const groupDatasets_t & groupDatasets, const AffxString & groupName, const AffxString & datasetName) [protected]
Helper function: is the given group name AND dataset present in the given group/dataset map.
Parameters:
groupDatasets - map containing calvin group nad dataset names
groupName - calvin group name to check for in groupDatasets
datasetName - calvin dataset name to check for in groupDatasets for group groupName
Returns:
- bool value. (true if groupDatasets contains groupName/datasetName)
Definition at line 1176 of file CNCychp.cpp.
Referenced by readFile().
bool CNCychp::isGroupPresent (const groupDatasets_t & groupDatasets, const AffxString & groupName) [protected]
Helper function: is the given group name present in the given group/dataset map.
Parameters:
groupDatasets - map containing calvin group nad dataset names
groupName - calvin group name to check for in groupDatasets
Returns:
- bool value. (true if groupDatasets contains groupName)
Definition at line 1156 of file CNCychp.cpp.
Referenced by readFile().
void CNCychp::loadDataSet (const AffxString & strDataGroupName, const AffxString & strDataSetName, unsigned int uiDataSetIndex, affymetrix_calvin_io::DataSet * pDataSet) [protected]
Load the CNCychp DataSet into memory.
Parameters:
strDataGroupName - The name of the CNCychp file data group.
strDataSetName - The name of the CNCychp file data set.
pDataSet - A pointer to the affymetrix_calvin_io::DataSet object.
Definition at line 1271 of file CNCychp.cpp.
References affymetrix_calvin_io::DataSet::Delete(), error(), affymetrix_calvin_io::DataSet::Open(), and affymetrix_calvin_io::DataSet::Rows().
Referenced by readFile().
void CNCychp::loadDataSet (const AffxString & strDataGroupName, const AffxString & strDataSetName, unsigned int uiDataSetIndex, affymetrix_calvin_io::DataSet * pDataSet, AffxArray< CNCychpProbeSetsCopyNumber > & vProbeSets, bool bLoadProbeSetName = true, bool bNonNaNOnly = false) [protected]
Load the CNCychp DataSet into memory.
Parameters:
strDataGroupName - The name of the CNCychp file data group.
strDataSetName - The name of the CNCychp file data set.
pDataSet - A pointer to the affymetrix_calvin_io::DataSet object.
Definition at line 1360 of file CNCychp.cpp.
References affymetrix_calvin_io::DataSet::Delete(), affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::Open(), and affymetrix_calvin_io::DataSet::Rows().
void CNCychp::loadHeader (affymetrix_calvin_io::GenericDataHeader * pHeader) [protected]
Load the CNCychp header into memory.
Parameters:
pHeader - A pointer to the affymetrix_calvin_io::GenericDataHeader for the specified CNCychp file.
Todo:
AW: should this be "state" not "option"? Do we need to handle both for compatability reasons?
Todo:
AW: should this be "state" not "option"? Do we need to handle both for compatability reasons?
Definition at line 1193 of file CNCychp.cpp.
References affymetrix_calvin_io::GenericDataHeader::Clear(), error(), affymetrix_calvin_io::GenericDataHeader::GetFileId(), affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_io::GenericDataHeader::GetNameValParam(), affymetrix_calvin_io::GenericDataHeader::GetNameValParamCnt(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueText().
Referenced by readFile().
bool CNCychp::readFile (const AffxString & strFileName, const groupDatasets_t & groupDatasets, const AffxString & strFamilialType, const AffxString & strPrompt = "")
Selectively read the CNCychp file, and store the data in memory.
Parameters:
groupDatasets - map containing calvin group nad dataset names to be read
strFileName - The name of the CNCychp file to load data from.
Returns:
- bool value. (true if successful)
Definition at line 1094 of file CNCychp.cpp.
References affymetrix_calvin_io::GenericData::Clear(), clear(), affymetrix_calvin_io::GenericData::DataGroupNames(), affymetrix_calvin_io::GenericData::DataSet(), affymetrix_calvin_io::GenericData::DataSetNames(), error(), affymetrix_calvin_io::GenericData::Header(), isGroupDatasetPresent(), isGroupPresent(), loadDataSet(), loadHeader(), affymetrix_calvin_io::GenericFileReader::Open(), Verbose::out(), setCnCalls(), affymetrix_calvin_io::GenericFileReader::SetFilename(), and setLohCalls().
bool CNCychp::readFile (const AffxString & strFileName, AffxArray< CNCychpProbeSetsCopyNumber > & vProbeSets, bool bLoadProbeSetName = true, bool bNonNaNOnly = false)
Read the CNCychp file, and store the data in memory.
Parameters:
strFileName - The name of the CNCychp file to load data from.
Returns:
- bool value. (true if successful)
Definition at line 993 of file CNCychp.cpp.
References affymetrix_calvin_io::GenericData::Clear(), clear(), affymetrix_calvin_io::GenericData::DataGroupNames(), affymetrix_calvin_io::GenericData::DataSet(), affymetrix_calvin_io::GenericData::DataSetNames(), error(), affymetrix_calvin_io::GenericData::Header(), loadDataSet(), loadHeader(), affymetrix_calvin_io::GenericFileReader::Open(), Verbose::out(), setCnCalls(), affymetrix_calvin_io::GenericFileReader::SetFilename(), and setLohCalls().
bool CNCychp::readFile (const AffxString & strFileName, const AffxString & strFamilialType, const AffxString & strPrompt = "")
Read the CNCychp file, and store the data in memory.
Parameters:
strFileName - The name of the CNCychp file to load data from.
Returns:
- bool value. (true if successful)
Definition at line 1044 of file CNCychp.cpp.
References affymetrix_calvin_io::GenericData::Clear(), clear(), affymetrix_calvin_io::GenericData::DataGroupNames(), affymetrix_calvin_io::GenericData::DataSet(), affymetrix_calvin_io::GenericData::DataSetNames(), error(), affymetrix_calvin_io::GenericData::Header(), loadDataSet(), loadHeader(), affymetrix_calvin_io::GenericFileReader::Open(), Verbose::out(), setCnCalls(), affymetrix_calvin_io::GenericFileReader::SetFilename(), and setLohCalls().
void CNCychp::warning (const AffxString & strMessage)
Warning handling for the CNCychp class.
Parameters:
strMessage - The warning messagae to report.
Definition at line 883 of file CNCychp.cpp.
References Verbose::out().
The documentation for this class was generated from the following files:
copynumber/CNCychp.h
copynumber/CNCychp.cpp