Affymetrix Power Tools: ARRSAXHandler Class Reference
ARRSAXHandler Class Reference
a Xerces SAX Handler class for parsing XML
Public Member Functions
ARRSAXHandler (CNCychp *p)
unsigned int getOptionCount () const
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exc)
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exc)
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exc)
void startDocument ()
void startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList &attributes)
Do the XML parsing.
Static Public Member Functions
static std::string toString (const XMLCh *const in)
Convert the internal representation to a std::string.
Detailed Description
a Xerces SAX Handler class for parsing XML
Definition at line 1455 of file CNCychp.cpp.
Member Function Documentation
void ARRSAXHandler::startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList & attributes) [inline]
Do the XML parsing.
Parameters:
const XMLCh* const - The pointer to the element name
XERCES_CPP_NAMESPACE::AttributeList& - The attribute list
Definition at line 1504 of file CNCychp.cpp.
References Err::errAbort(), and toString().
static std::string ARRSAXHandler::toString (const XMLCh *const in) [inline, static]
Convert the internal representation to a std::string.
Parameters:
const XMLCh* const - The pointer to convert
Returns:
std::string - The resulting string value
Definition at line 1492 of file CNCychp.cpp.
Referenced by CNCychp::getGuidFromARRFile(), and startElement().
The documentation for this class was generated from the following file:
copynumber/CNCychp.cpp