Affymetrix Power Tools: DmListener Class Reference
DmListener Class Reference
Class for using DM calls as cell files become available.
#include <DmListener.h>