Affymetrix Power Tools: ChipLayout Class Reference
ChipLayout Class Reference
ChipLayout - Data structure to represent the probesets encoded in the CDF, SPF or PGF files which define the probes that belong which probe sets and if they are PM, MM, genotyping etc.
#include <ChipLayout.h>
Public Types
typedef std::vector< ProbeSet * >
::const_iterator psVecIter
Typedef for utility.
Public Member Functions
ChipLayout ()
Constructor.
~ChipLayout ()
Clean up memory in hashes.
bool canAccessByName ()
Are the probesets randomly accessible by name?
ProbeListPacked getProbeListByName (const std::string &name)
Find a probe set using the name as a key.
int getProbeSetIndexByName (const std::string &name)
Find a probe set index using the name as a key.
bool containsProbeSet (const std::string &psName)
Does the layout have a reference to the probeset with name psName? Must have name map filled to call this function.
ProbeListPacked getProbeListAtIndex (unsigned int index)
Get a probelist by the index in the layout.
unsigned int getProbeSetCount () const
How many probe sets in Pgf file?
bool openPgf (const std::string &fileName, unsigned int xSize, unsigned int ySize, const std::set< const char *, Util::ltstr > &probeSetsToLoad, std::vector< const char * > *probesetNames, std::vector< const char * > *probesetDisplayNames, std::vector< bool > &probeSubset, const std::string &chipType, probeidmap_t &killList, bool justStats, bool doPList)
Open and parse out the data of a file.
bool openPgf (const std::string &fileName, unsigned int xSize, unsigned int ySize, const std::set< const char *, Util::ltstr > &probeSetsToLoad, std::vector< bool > &probeSubset, const std::string &chipType)
Open and parse out the data of a file.
bool openPgfAll (const std::string &fileName, unsigned int xSize, unsigned int ySize)
Open a file and parse the probe sets.
bool openCdf (const std::string &fileName, const std::set< const char *, Util::ltstr > &probeSetsToLoad, std::vector< const char * > *probesetNames, std::vector< bool > &probeSubset, const std::string &chipType, probeidmap_t &killList, bool justStats, std::set< affxcdf::GeneChipProbeSetType > &psTypesToLoad)
Open a file and parse the probe sets.
bool openCdf (const std::string &fileName, const std::set< const char *, Util::ltstr > &probeSetsToLoad, std::vector< const char * > *probesetNames, std::vector< bool > &probeSubset, const std::string &chipType, probeidmap_t &killList, bool justStats=false)
Open a file and parse the probe sets.
bool openCdf (const std::string &fileName, const std::set< const char *, Util::ltstr > &probeSetsToLoad, std::vector< bool > &probeSubset, const std::string &chipType)
Open a file and parse the probe sets.
bool openCdfAll (const std::string &fileName)
Open a file and parse the probe sets.
void write (const std::string &fileName)
Write out the data in class to file in PGF format.
const std::vector< bool > & getPmProbeMask ()
Get the perfect match probes of chip.
const std::vector< bool > & getMmProbeMask ()
Get the perfect match probes of chip.
void setPmProbeMask (const std::vector< bool > &mask)
Set the perfect match probes of chip.
const std::vector< std::string > & getHeaderValue (const std::string &key)
Get the value of a layout key=value header pair.
int getXCount ()
Get the number of x counts.
int getYCount ()
Get the number of y counts.
void setDimensions (unsigned int xCount, unsigned int yCount)
Set the x and y dimensions for the array.
int numChannels ()
int getProbeCount ()
Get the total number of probes on this chip.
int getProbeUsedCount ()
Get the total number of probes actually used in the cdf or pgf.
unsigned int probeIdToIndex (unsigned int probeId)
Given probe id supply the index.
unsigned int indexToProbeId (unsigned int probeIndex)
Given probe index supply the id.
void indexToXY (unsigned int probeIndex, unsigned int &x, unsigned int &y)
Translate an index (id) to the x and y coordinates on a chip.
void indexToXY (unsigned int probeIndex, int &x, int &y)
Translate an index (id) to the x and y coordinates on a chip.
int xyToIndex (int x, int y)
Turn the x and y cordinates of a probe on the array into an index.
const char * typeFromCdfType (unsigned short type)
Convert from numeric representation to string.
bool inKillList (probeid_t, const std::string &psName, probeidmap_t &killList)
Is a particular probe in the kill list (i.e.
void readProbeListPgfFileKillList (affx::PgfFile &pgf, unsigned int numProbes, ProbeListFactory &plFactory, const std::set< const char *, Util::ltstr > &probeSetsToLoad, std::vector< const char * > *probesetNames, std::vector< const char * > *probesetDisplayNames, std::vector< bool > &probeSubset, probeidmap_t &killList, bool justStats)
Read the contents of rowFile into a vector of probe sets.
void readProbeListCdfFileKillList (affymetrix_fusion_io::FusionCDFData &cdf, ProbeListFactory &plFactory, const std::set< const char *, Util::ltstr > &probeSetsToLoad, std::vector< const char * > *probesetNames, std::vector< bool > &probeSubSet, probeidmap_t &killList, bool justStats, std::set< affxcdf::GeneChipProbeSetType > &psTypesToLoad)
Read a vector of ProbeSets from a cdf file representation.
void readCdfProbe (Probe *p, Atom *parent, unsigned int numCol, unsigned int numRow, unsigned int direction, const affymetrix_fusion_io::FusionCDFProbeGroupInformation &group, const affymetrix_fusion_io::FusionCDFProbeInformation &cel)
Read cdf probe information into a Probe object.
bool validBase (int c)
Check to see if a charater is a valid DNA base of 'a','t','g', or 'c'.
void buildPmMmMap ()
Build map between pm and mm probes.
const int mmId (const int probeIx) const
Function to return the mm id associated with a given pm id.
ProbeSet::ProbeSetType getProbeSetType (int psIndex)
Get the probeset type for a particular probeset based on its index in layout file.
bool isGenotypable (int psIndex)
Determine if the probeset at the given index is a genotype probeset that has more than one annotated allele.
void readCdfProbeSet (const std::string &name, affymetrix_fusion_io::FusionCDFProbeSetInformation &set, unsigned int psIx, int numCol, int numRow, std::vector< bool > &probeSubSet, bool &keepProbeSet, probeidmap_t &killList, ProbeSet &ps, int &psNameSize, std::vector< Atom > **locAtoms, std::vector< Probe > **locProbes, int &errorCount)
///
std::vector< int > getPmMmVec ()
std::vector< int > getPmAlleleMatchVec ()
const std::vector< char > & getGcProbeVec ()
std::vector< int > getProbesetProbeCounts ()
std::vector< bool > getProbesetProbes ()
double meanProbesPerProbeset ()
double meanMemPerProbeset ()
void setNeedMismatch (bool needMisMatchMap)
void setNeedPmAlleleMatch (bool needPmAlleleMatch)
void setNeedGc (bool needGcMap)
void setSpfFileName (const std::string &fileName)
Set the name of the spf output file ///.
void openSpfForWrite (affx::SpfFile &spfFile, const std::string &spfFilename, int spfVersion=2)
void writeSpfProbeList (const std::string &spfFilename, int spfVersion=2)
Write out our probelist information in our simple probe format.
void openSpf (const std::string &fileName, const std::set< const char *, Util::ltstr > &probeSetsToLoad, std::vector< const char * > *probesetNames, std::vector< bool > &probeSubSet, const std::string &chipType, bool justStats, std::set< affxcdf::GeneChipProbeSetType > &psTypesToLoad)
Read in probelist data from a simple probe format file.
void openSpf_v2 (const std::string &fileName, const std::set< const char *, Util::ltstr > &probeSetsToLoad, std::vector< const char * > *probesetNames, std::vector< bool > &probeSubSet, const std::string &chipType, bool justStats, std::set< affxcdf::GeneChipProbeSetType > &psTypesToLoad)
void openSpf_v3 (const std::string &fileName, const std::set< const char *, Util::ltstr > &probeSetsToLoad, std::vector< const char * > *probesetNames, std::vector< bool > &probeSubSet, const std::string &chipType, bool justStats, std::set< affxcdf::GeneChipProbeSetType > &psTypesToLoad)
void openSpf_v4 (const std::string &fileName, const std::set< const char *, Util::ltstr > &probeSetsToLoad, std::vector< const char * > *probesetNames, std::vector< bool > &probeSubSet, const std::string &chipType, bool justStats, std::set< affxcdf::GeneChipProbeSetType > &psTypesToLoad)
void openSpfAll (const std::string &fileName)
const std::vector< int > & getProbeLayoutOrder ()
void parseProbeListRecord (const std::string &name, int type, int numBlocks, const std::string &blockSizesStr, const std::string &blockAnnsStr, bool have_blockAlleleStr, const std::string &blockAlleleStr, bool have_blockContextStr, const std::string &blockContextStr, bool have_blockChannelStr, const std::string &blockChannelStr, bool have_blockRepTypeStr, const std::string &blockRepTypeStr, int numMatch, int numProbes, const std::string &probesStr, int lineNumber, bool keep, std::vector< bool > &probeSubSet, bool keepOrder)
Parse the results from one record into a ProbeList if desired, othewise just keep track of statistics.
ProbeListPacked makeProbeListPacked (const std::string &name, int type, int numBlocks, const std::vector< int > &blockSizes, const std::vector< int > &blockAnns, const std::vector< int > &blockAlleles, const std::vector< int > &blockContexts, const std::vector< int > &blockChannels, const std::vector< int > &blockRepTypes, int numMatch, int numProbes, const std::vector< int > &probes)
Create a probelist allocating from the factory with the attributes passed in.
void makePsMaps ()
Make maps of the probe sets in m_PsVec by id and name if possible.
void resizeStats (uint32_t numProbes)
void resizeAtoms (std::vector< Atom > **old, int32_t newSize, ProbeSet *ps)
void resizeProbes (std::vector< Probe > **old, int32_t newSize, std::vector< Atom > *currentAtoms, uint32_t currentAtomCount)
void clearProbe (Probe &p)
void clearAtom (Atom &a)
void clearProbeSet (ProbeSet &ps)
void trackGlobalStats (ProbeSet &ps, int numBytes)
int findProbeApidByName (const std::string &qName, int qPid, int qAllele, int qContext, int qChannel) const
pass these along to the ProbeListFactory for it to handle. ///
int findProbeApidByIdx (int qPlIdx, int qPid, int qAllele, int qContext, int qChannel) const
query the Apid of a a probe (unique for this run only.) /// The qPid, qAllele, qContext and qChannel must match. /// Just like findProbeApidByName, but the first arg is the probelist index. ///
int findProbeApidByProbeId (int qPid) const
Find the Apid for a probe given its ProbeId. /// This only works in the single channel case. // (Otherwise it is not a one-to-one map.) ///.
void trackGlobalStats (const std::string &name, int type, int numBlocks, const std::vector< int > &blockSizes, int numMatch, const std::vector< int > &probes, bool multAlleles=false)
Keep track of global stats as we parse through file.
int getMaxNameLength ()
void incrementTypes (int type, int numBlocks, bool multipleAlleles)
int getNumExpressionPSets ()
Number of expression probesets.
int getNumGenotypeingPSets ()
Number of genotyping expression.
void sortProbesetNameByProbesetIdx (std::vector< std::string >::iterator begin, std::vector< std::string >::iterator end)
compare probeset names according to respective probeset ids
Static Public Member Functions
static void writePgfFile (const std::string &fileName, const std::vector< ProbeSet * > &vec)
Write out the contents of probe sets in PGF format.
static void writePgfFile (affx::PgfFile &pgf, const std::vector< ProbeSet * > &vec)
Write out the contents of probe sets in PGF format.
static void indexToXY (unsigned int probeIndex, int numCol, unsigned int &x, unsigned int &y)
Translate an index (id) to the x and y coordinates on a chip.
static bool isPm (const affymetrix_fusion_io::FusionCDFProbeInformation &cel)
Is this probe a perfect match probe?
static ProbeSet::ProbeSetType getProbeSetType (ProbeSet *ps)
static void writeSpfProbeSetRecord (affx::SpfFile &tsv, const ProbeSet &ps)
Write out a single record to the tsv file supplied.
static void writeSpfProbeListRecord (affx::SpfFile &tsv, const ProbeListPacked &pL)
Write out a single record to the tsv file supplied.
static void fillInKillList (const std::string &fileName, probeidmap_t &killList, int rows, int cols)
Reads in probes to kill.
static bool sameValues (std::vector< int > &v)
Public Attributes
bool m_NeedMismatch
Do we need gc counts?
bool m_NeedGc
Do we need pm matching?
bool m_NeedPmAlleleMatch
Name of file.
std::string m_FileName
Header parameters from thisKey=thisParam.
std::map< std::string,
std::vector< std::string > > m_Header
Verbatim lines from header.
std::vector< std::string > m_HeaderLines
ProbeListFactory m_PlFactory
unsigned int m_XCount
unsigned int m_YCount
int m_numChannels
int m_NumExpression
Iterator to walk through the map.
int m_NumGenotyping
Number of genotyping expression.
std::vector< bool > m_PmProbes
Pm probes in this layout (useful for some methods like RMA).
std::vector< bool > m_MmProbes
Mm probes in this layout.
std::vector< int > m_PmMmVec
Map between PM and MM index on chip.
std::vector< int > m_PmAlleleMatchVec
Map between PM and PM for other allele.
std::vector< char > m_ProbeGcVec
GC count of each probe as indexed by position.
std::vector< int > m_ProbeCounts
Sizes of various probesets (in probes).
std::vector< bool > m_ProbesetProbes
Bitmask of probes that are actually in probesets.
CumulativeStats< double > m_ProbesetMemSizes
CumulativeStats< double > m_ProbesPerProbeset
int m_MaxNameLength
bool m_haveKillList
Vector of the types for each probeset, used by calvin chp files to /// determine size of file. Note that probesets marked as "GenoType" but only /// having one block are changed here to "Expression".
std::vector< int > m_ProbeLayoutOrder
std::string m_SpfFileName
affx::SpfFile m_SpfFile
int m_warningCount
Detailed Description
ChipLayout - Data structure to represent the probesets encoded in the CDF, SPF or PGF files which define the probes that belong which probe sets and if they are PM, MM, genotyping etc.
Parse the file and store it in memory for easy access by index or probe set name. Note that there is currently no way to reuse a ChipLayout object, that is there is no close() function. Delete the ChipLayout and open another one if wish to open another cdf/pgf/spf file.
For the CEL file SDK the order of the probes indexes are:
  (0,0) (1,0) (2,0) (3,0) ... (numCols,0)
  (0,1) (1,1) (2,1) (3,1) ... (numCols,1)
  (0,2) (1,2) (2,2) (3,2) ... (numCols,2)
  ...
  (0,numRows)       ... (numCols,numRows)
Where in cel file terminology cols are the x dimension and rows are the y dimension. So using the standard XYToIndex() function in the cel file API you can transform into a single vector index i using:
i = ((y*numColumns) + x)
x = i % numCols
y = i / numCols
So the indexing he numbering when num cols = 10
  0  1  2  3  4  5  6  7  8  9
  10 11 12 13 14 15 16 17 18 19
  20 21 22 23 24 25 26 27 28 29
Note that these indexes are only for the CEL files as the underlying DAT files can be rotated depending on the scanner and application.
Definition at line 79 of file ChipLayout.h.
Constructor & Destructor Documentation
ChipLayout::ChipLayout ()
Constructor.
Definition at line 60 of file ChipLayout.cpp.
References m_haveKillList, m_NeedGc, m_NeedMismatch, m_NeedPmAlleleMatch, m_NumExpression, m_NumGenotyping, and m_XCount.
ChipLayout::~ChipLayout ()
Clean up memory in hashes.
Definition at line 51 of file ChipLayout.cpp.
Member Function Documentation
bool ChipLayout::canAccessByName () [inline]
Are the probesets randomly accessible by name?
Returns:
true if can lookup by name, false otherwise.
Definition at line 93 of file ChipLayout.h.
bool ChipLayout::containsProbeSet (const std::string & psName) [inline]
Does the layout have a reference to the probeset with name psName? Must have name map filled to call this function.
Parameters:
psName - identifier of probeset.
Returns:
true if in list false otherwise
Definition at line 115 of file ChipLayout.h.
References m_PlFactory.
Referenced by fillInHaploidSnpsVersion1(), and fillInHaploidSnpsVersion2().
void ChipLayout::fillInKillList (const std::string & fileName, probeidmap_t & killList, int rows, int cols) [static]
Reads in probes to kill.
Parameters:
fileName - file containing BadProbes
killList - things to kill, determined from file
rows - number of rows in cel file
cols - number of cols in cel file
Definition at line 2606 of file ChipLayout.cpp.
References Fs::basename(), affx::TsvFile::close(), affx::TsvFile::cname2cidx(), Err::errAbort(), FROM_ZEROBASED, affx::TsvFile::nextLevel(), affx::TsvFile::open(), Verbose::out(), ToStr(), affx::TSV_BIND_REQUIRED, and affymetrix_fusion_io::FusionCELData::XYToIndex().
int ChipLayout::findProbeApidByIdx (int qPlIdx, int qPid, int qAllele, int qContext, int qChannel) const [inline]
query the Apid of a a probe (unique for this run only.) /// The qPid, qAllele, qContext and qChannel must match. /// Just like findProbeApidByName, but the first arg is the probelist index. ///
Parameters:
qPlIdx ///
qPid ///
qAllele //
qContext ///
qChannel ///
Returns:
"-1" if not found. The Apid if a probe matching is found.
Definition at line 870 of file ChipLayout.h.
References m_PlFactory.
int ChipLayout::findProbeApidByName (const std::string & qName, int qPid, int qAllele, int qContext, int qChannel) const [inline]
pass these along to the ProbeListFactory for it to handle. ///
query the Apid of a a probe (unique for this run only.) /// The qPid, qAllele, qContext and qChannel must match. ///
Parameters:
qName name of probeset ///
qPid the query probeid (0-based) ///
qAllele the query allele ///
qContext the query context ///
qChannel the query channel ///
Returns:
"-1" if not found. The Apid if a probe matching is found.
Definition at line 858 of file ChipLayout.h.
References m_PlFactory.
int ChipLayout::findProbeApidByProbeId (int qPid) const [inline]
Find the Apid for a probe given its ProbeId. /// This only works in the single channel case. // (Otherwise it is not a one-to-one map.) ///.
Parameters:
qPid ///
Returns:
-1 if not found.
Definition at line 880 of file ChipLayout.h.
References m_PlFactory.
Referenced by QuantMethodFactory::openPrecompFeatureEffects().
const std::vector<std::string>& ChipLayout::getHeaderValue (const std::string & key) [inline]
Get the value of a layout key=value header pair.
Parameters:
key String to lookup value of.
Returns:
value of key/value pair.
Definition at line 320 of file ChipLayout.h.
References m_Header, and Verbose::out().
const std::vector<bool>& ChipLayout::getMmProbeMask () [inline]
Get the perfect match probes of chip.
Returns:
Bitmask representig pm probe on chip.
Definition at line 306 of file ChipLayout.h.
References m_MmProbes.
Referenced by DataStore::setValues().
const std::vector<bool>& ChipLayout::getPmProbeMask () [inline]
Get the perfect match probes of chip.
Returns:
Bitmask representig pm probe on chip.
Definition at line 300 of file ChipLayout.h.
References m_PmProbes.
Referenced by ChipStreamFactory::chipStreamForString(), and DataStore::setValues().
int ChipLayout::getProbeCount () [inline]
Get the total number of probes on this chip.
Returns:
- Number of probes on array.
Definition at line 364 of file ChipLayout.h.
References m_XCount.
Referenced by ChipStreamFactory::chipStreamForString(), AdapterTypeNormTran::loadAnnotation(), parseProbeListRecord(), and MmAdjust::setLayout().
ProbeListPacked ChipLayout::getProbeListAtIndex (unsigned int index)
Get a probelist by the index in the layout.
Parameters:
index - index of probeset in chiplayout list.
Returns:
Probelist requested.
Definition at line 1118 of file ChipLayout.cpp.
References m_PlFactory.
Referenced by callGenotypes(), CelExtract::CelExtract(), CelExtract::doProbeSet(), doRma(), FileTranslation::fillInFromProbeSets(), AdapterTypeNormTran::loadAnnotation(), DmListener::setLayout(), and QuantMethodTransform::transformData().
ProbeListPacked ChipLayout::getProbeListByName (const std::string & name)
Find a probe set using the name as a key.
canAccessByName() must be true for this to work.
Parameters:
psName - Name of probe set desired.
Returns:
Pointer to ProbeList
Parameters:
psName - Name of probe set desired.
Returns:
Reference to probe set, NULL if not found.
Definition at line 1133 of file ChipLayout.cpp.
References m_PlFactory.
Referenced by CelExtract::CelExtract(), QCMethod::createDmListener(), QuantLabelZ::makeNorm(), and QuantBRLMM::makePrior().
unsigned int ChipLayout::getProbeSetCount () const [inline]
How many probe sets in Pgf file?
Returns:
int - number of probe sets defined.
Definition at line 136 of file ChipLayout.h.
References m_PlFactory.
Referenced by callGenotypes(), CelExtract::CelExtract(), doRma(), CelExtract::extract(), FileTranslation::fillInFromProbeSets(), AdapterTypeNormTran::loadAnnotation(), openCdf(), openPgf(), DmListener::setLayout(), and QuantMethodTransform::transformData().
int ChipLayout::getProbeSetIndexByName (const std::string & name)
Find a probe set index using the name as a key.
Parameters:
psName - Name of probe set desired.
Returns:
probe set index
Definition at line 1154 of file ChipLayout.cpp.
References m_PlFactory.
Referenced by CelExtract::CelExtract(), and sortProbesetNameByProbesetIdx().
ProbeSet::ProbeSetType ChipLayout::getProbeSetType (int psIndex) [inline]
Get the probeset type for a particular probeset based on its index in layout file.
Note that probesets marked as "GenoType" but only having one block are changed here to "Expression". Currently only supported for cdf files.
Parameters:
psIndex - Index of probeset.
Returns:
- Type of probeset (i.e. ProbeSet::Genotype)
Definition at line 559 of file ChipLayout.h.
References APT_ERR_ABORT, and m_PlFactory.
int ChipLayout::getProbeUsedCount ()
Get the total number of probes actually used in the cdf or pgf.
Returns:
- Number of probes in a probeset.
int ChipLayout::getXCount () [inline]
Get the number of x counts.
Returns:
- int x maximum
Definition at line 335 of file ChipLayout.h.
References m_XCount.
int ChipLayout::getYCount () [inline]
Get the number of y counts.
Returns:
- int y maximum
Definition at line 341 of file ChipLayout.h.
unsigned int ChipLayout::indexToProbeId (unsigned int probeIndex) [inline]
Given probe index supply the id.
Parameters:
probeIndex - Index of probe
Returns:
Probe id.
Definition at line 384 of file ChipLayout.h.
static void ChipLayout::indexToXY (unsigned int probeIndex, int numCol, unsigned int & x, unsigned int & y) [inline, static]
Translate an index (id) to the x and y coordinates on a chip.
Parameters:
probeId - Id of probe of interest.
numProbes - Number of total probes on the chip
x - X coordinate of interest.
y - Y coordinate of interest.
Definition at line 394 of file ChipLayout.h.
Referenced by CelExtract::doProbeSet(), indexToXY(), and QuantMethodExprReport::report().
void ChipLayout::indexToXY (unsigned int probeIndex, unsigned int & x, unsigned int & y) [inline]
Translate an index (id) to the x and y coordinates on a chip.
Parameters:
probeId - Id of probe of interest.
x - X coordinate of interest.
y - Y coordinate of interest.
Definition at line 406 of file ChipLayout.h.
References indexToXY(), and m_XCount.
void ChipLayout::indexToXY (unsigned int probeIndex, int & x, int & y) [inline]
Translate an index (id) to the x and y coordinates on a chip.
(just like the unsigned version.)
Parameters:
probeId - Id of probe of interest.
x - X coordinate of interest.
y - Y coordinate of interest.
Definition at line 419 of file ChipLayout.h.
References m_XCount.
bool ChipLayout::inKillList (probeid_t probeId, const std::string & psName, probeidmap_t & killList)
Is a particular probe in the kill list (i.e.
not to be used?)
Parameters:
probeIx - Id of probe.
psName - Name of probeset that contains probe.
killList - Map of probes not to be used.
Returns:
true if probe id is in kill list, false otherwise.
Definition at line 1818 of file ChipLayout.cpp.
Referenced by readCdfProbeSet(), and readProbeListPgfFileKillList().
bool ChipLayout::isGenotypable (int psIndex) [inline]
Determine if the probeset at the given index is a genotype probeset that has more than one annotated allele.
Parameters:
psIndex - Index of probeset.
Returns:
- boolean
Definition at line 583 of file ChipLayout.h.
References APT_ERR_ABORT, and m_PlFactory.
bool ChipLayout::isPm (const affymetrix_fusion_io::FusionCDFProbeInformation & cel) [static]
Is this probe a perfect match probe?
Parameters:
cel - probe information from cdf.
Returns:
true if probe is a perfect match, false otherwise.
Definition at line 1729 of file ChipLayout.cpp.
References affymetrix_fusion_io::FusionCDFProbeInformation::GetPBase(), and affymetrix_fusion_io::FusionCDFProbeInformation::GetTBase().
Referenced by readCdfProbe(), and readCdfProbeSet().
ProbeListPacked ChipLayout::makeProbeListPacked (const std::string & name, int type, int numBlocks, const std::vector< int > & blockSizes, const std::vector< int > & blockAnns, const std::vector< int > & blockAlleles, const std::vector< int > & blockContexts, const std::vector< int > & blockChannels, const std::vector< int > & blockRepTypes, int numMatch, int numProbes, const std::vector< int > & probes)
Create a probelist allocating from the factory with the attributes passed in.
Parameters:
name - Probeset identifier.
type - Class of probeset (i.e. genotyping, expression, copynumber) as in ProbeSet::Type enumeration
numBlocks - How many blocks are there in probeset.
blockSizes - Size in probes of each block.
blockAnns - Annotation for each block as in ProbeSet::BlockAnnotation enumeration
numMatch - How many matches (1 for pm only, 2 for pm-mm).
numProbes - Total number of probes.
probes - Vector of probe ids (indexes).
Returns:
Created ProbeList.
Definition at line 259 of file ChipLayout.cpp.
References ProbeListFactory::add_ProbeList(), APT_ERR_ASSERT, and m_PlFactory.
Referenced by openSpf_v3(), openSpf_v4(), and parseProbeListRecord().
const int ChipLayout::mmId (const int probeIx) const
Function to return the mm id associated with a given pm id.
Parameters:
probeIx - Index of perfect match probe.
Returns:
- The index of the associated mismatch probe, if any.
Definition at line 2338 of file ChipLayout.cpp.
References Err::errAbort(), m_PmMmVec, and ToStr().
bool ChipLayout::openCdf (const std::string & fileName, const std::set< const char *, Util::ltstr > & probeSetsToLoad, std::vector< const char * > * probesetNames, std::vector< bool > & probeSubset, const std::string & chipType, probeidmap_t & killList, bool justStats, std::set< affxcdf::GeneChipProbeSetType > & psTypesToLoad)
Open a file and parse the probe sets.
Parameters:
fileName - Name of file to be opened.
probeSetsToLoad - Which probe sets should be loaded?
probeSubset - Subset of probes to be loaded.
chipType - What sort of chip should this cdf file be for?
probesetNames - If not null filled in with the probesetname for each probeset even if not actually into chiplayout. Useful for chp files where every single probeset must be included and in order.
- killList map of probes that are to be excluded from the probesets. A probe must have its id mapped to the probeset name for this to work.
justStats - just read and generate stats, don't load into memory.
psTypesToLoad - What types of probesets to load into memory.
Returns:
bool - true if success. Errors out on problems.
Definition at line 1528 of file ChipLayout.cpp.
References affx::TsvFile::close(), affymetrix_fusion_io::FusionCDFData::Close(), Err::errAbort(), affymetrix_fusion_io::FusionCDFData::Exists(), FS_QUOTE_PATH, affymetrix_fusion_io::FusionCDFData::GetChipType(), affymetrix_fusion_io::FusionCDFData::GetChipTypes(), affymetrix_fusion_io::FusionCDFFileHeader::GetCols(), affymetrix_fusion_io::FusionCDFData::GetError(), affymetrix_fusion_io::FusionCDFData::GetFileName(), affymetrix_fusion_io::FusionCDFData::GetGUID(), affymetrix_fusion_io::FusionCDFData::GetHeader(), affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets(), getProbeSetCount(), affymetrix_fusion_io::FusionCDFFileHeader::GetRows(), m_haveKillList, m_Header, m_PlFactory, makePsMaps(), Verbose::out(), affymetrix_fusion_io::FusionCDFData::Read(), affymetrix_fusion_io::FusionCDFData::ReadHeader(), readProbeListCdfFileKillList(), setDimensions(), affymetrix_fusion_io::FusionCDFData::SetFileName(), and ToStr().
Referenced by CelExtract::CelExtract(), openCdf(), and openCdfAll().
bool ChipLayout::openCdf (const std::string & fileName, const std::set< const char *, Util::ltstr > & probeSetsToLoad, std::vector< const char * > * probesetNames, std::vector< bool > & probeSubset, const std::string & chipType, probeidmap_t & killList, bool justStats = false) [inline]
Open a file and parse the probe sets.
Parameters:
fileName - Name of file to be opened.
probeSetsToLoad - Which probe sets should be loaded?
probeSubset - Subset of probes to be loaded.
chipType - What sort of chip should this cdf file be for?
probesetNames - If not null filled in with the probesetname for each probeset even if not actually into chiplayout. Useful for chp files where every single probeset must be included and in order.
- killList map of probes that are to be excluded from the probesets. A probe must have its id mapped to the probeset name for this to work.
Returns:
bool - true if success. Errors out on problems.
Definition at line 233 of file ChipLayout.h.
References openCdf().
bool ChipLayout::openCdf (const std::string & fileName, const std::set< const char *, Util::ltstr > & probeSetsToLoad, std::vector< bool > & probeSubset, const std::string & chipType) [inline]
Open a file and parse the probe sets.
Parameters:
fileName - Name of file to be opened.
probeSetsToLoad - Which probe sets should be loaded?
probeSubset - Subset of probes to be loaded.
chipType - What sort of chip should this cdf file be for?
probesetNames - If not null filled in with the probesetname for each probeset even if not actually into chiplayout. Useful for chp files where every single probeset must be included and in order.
Returns:
bool - true if success. Errors out on problems.
Definition at line 255 of file ChipLayout.h.
References openCdf().
bool ChipLayout::openCdfAll (const std::string & fileName) [inline]
Open a file and parse the probe sets.
Parameters:
fileName - Name of file to be opened.
Returns:
bool - true if success. Errors out on problems.
Definition at line 267 of file ChipLayout.h.
References openCdf().
Referenced by callGenotypes(), doRma(), and CNAnalysisMethodReference::loadLayout().
bool ChipLayout::openPgf (const std::string & fileName, unsigned int xSize, unsigned int ySize, const std::set< const char *, Util::ltstr > & probeSetsToLoad, std::vector< bool > & probeSubset, const std::string & chipType) [inline]
Open and parse out the data of a file.
Parameters:
fileName - Name of file to be opened.
xSize -
ySize -
numProbes - How many probes are on this chip?
probeSetsToLoad - Vector of probe set ids to be loaded.
probeSubset - Subset of probes to be loaded.
chipType - What sort of chip should this pgf file be for?
Returns:
bool - true if successful.
Definition at line 170 of file ChipLayout.h.
References openPgf().
bool ChipLayout::openPgf (const std::string & fileName, unsigned int xSize, unsigned int ySize, const std::set< const char *, Util::ltstr > & probeSetsToLoad, std::vector< const char * > * probesetNames, std::vector< const char * > * probesetDisplayNames, std::vector< bool > & probeSubset, const std::string & chipType, probeidmap_t & killList, bool justStats, bool doPList)
Open and parse out the data of a file.
Parameters:
fileName - Name of PGF file to be opened.
xSize - How many features in x dimension.
ySize - How many features in y dimension.
probeSetsToLoad - Vector of probe set ids to be loaded.
probeSubset - Subset of probes to be loaded.
chipType - What sort of chip should this pgf file be for?
killList - Map of individual probes that should not be used.
Returns:
bool - true if successful.
Parameters:
fileName - Name of PGF file to be opened.
xSize - How many features in x dimension.
ySize - How many features in y dimension.
probeSetsToLoad - Vector of probe set ids to be loaded.
probeSubset - Subset of probes to be loaded.
chipType - What sort of chip should this pgf file be for?
Returns:
bool - true if successful.
Todo:
move this into PgfFile.h
Definition at line 1198 of file ChipLayout.cpp.
References affx::TsvFile::close(), affx::PgfFile::close(), Err::errAbort(), getProbeSetCount(), affx::TsvFile::headersBegin(), affx::TsvFile::headersFindNext(), affx::TsvFile::headersNext(), m_haveKillList, m_Header, m_PlFactory, m_ProbeCounts, affx::PgfFile::m_tsv, m_XCount, makePsMaps(), affx::PgfFile::open(), Verbose::out(), readProbeListPgfFileKillList(), setDimensions(), Convert::toInt(), ToStr(), and affx::TSV_OK.
Referenced by CelExtract::CelExtract(), openPgf(), and openPgfAll().
bool ChipLayout::openPgfAll (const std::string & fileName, unsigned int xSize, unsigned int ySize) [inline]
Open a file and parse the probe sets.
Parameters:
fileName - Name of file to be opened.
Returns:
bool - true if success. Errors out on problems.
Definition at line 185 of file ChipLayout.h.
References openPgf().
void ChipLayout::openSpf (const std::string & fileName, const std::set< const char *, Util::ltstr > & probeSetsToLoad, std::vector< const char * > * probesetNames, std::vector< bool > & probeSubSet, const std::string & chipTypeExpected, bool justStats, std::set< affxcdf::GeneChipProbeSetType > & psTypesToLoad)
Read in probelist data from a simple probe format file.
Parameters:
fileName - Name of file to be opened.
probeSetsToLoad - Which probe sets should be loaded?
probesetNames - If not null filled in with the probesetname for each probeset even if not actually into chiplayout. Useful for chp files where every single probeset must be included and in order.
probeSubset - Subset of probes to be loaded.
chipTypeExpected - What sort of chip should this cdf file be for?
justStats - just read and generate stats, don't load into memory.
psTypesToLoad - What types of probesets to load into memory.
Todo:
openSpf should allow for a kill list
Parameters:
fileName - Name of file to be opened.
probeSetsToLoad - Which probe sets should be loaded?
probesetNames - If not null filled in with the probesetname for each probeset even if not actually into chiplayout. Useful for chp files where every single probeset must be included and in order.
probeSubset - Subset of probes to be loaded.
chipTypeExpected - What sort of chip should this cdf file be for?
justStats - just read and generate stats, don't load into memory.
psTypesToLoad - What types of probesets to load into memory.
Definition at line 537 of file ChipLayout.cpp.
References APT_ERR_ABORT, affx::TsvFile::close(), affx::SpfFile::m_spf_format, openSpf_v3(), openSpf_v4(), and ToStr().
Referenced by CelExtract::CelExtract().
void ChipLayout::openSpf_v3 (const std::string & fileName, const std::set< const char *, Util::ltstr > & probeSetsToLoad, std::vector< const char * > * probesetNames, std::vector< bool > & probeSubSet, const std::string & chipType, bool justStats, std::set< affxcdf::GeneChipProbeSetType > & psTypesToLoad)
Todo:
AW bug? probe_ids_vec.size(), // numMatch,
Definition at line 718 of file ChipLayout.cpp.
References APT_ERR_ASSERT, Util::cloneString(), affx::TsvFile::close(), Err::errAbort(), affx::TsvFile::get(), affx::TsvFile::getHeader(), m_haveKillList, affx::SpfFile::m_spf_format, m_XCount, makeProbeListPacked(), makePsMaps(), affx::TsvFile::nextLevel(), ProbeList::null_probe, Verbose::progressStep(), setDimensions(), and ToStr().
Referenced by openSpf().
void ChipLayout::openSpf_v4 (const std::string & fileName, const std::set< const char *, Util::ltstr > & probeSetsToLoad, std::vector< const char * > * probesetNames, std::vector< bool > & probeSubSet, const std::string & chipType, bool justStats, std::set< affxcdf::GeneChipProbeSetType > & psTypesToLoad)
Todo:
AW bug? probe_ids_vec.size(), // numMatch,
Definition at line 907 of file ChipLayout.cpp.
References APT_ERR_ASSERT, Util::cloneString(), affx::TsvFile::close(), Err::errAbort(), affx::TsvFile::get(), affx::TsvFile::getHeader(), m_haveKillList, affx::SpfFile::m_spf_format, m_XCount, makeProbeListPacked(), makePsMaps(), affx::TsvFile::nextLevel(), ProbeList::null_probe, Verbose::progressStep(), setDimensions(), and ToStr().
Referenced by openSpf().
void ChipLayout::parseProbeListRecord (const std::string & name, int type, int numBlocks, const std::string & blockSizesStr, const std::string & blockAnnsStr, bool have_blockAlleleStr, const std::string & blockAlleleStr, bool have_blockContextStr, const std::string & blockContextStr, bool have_blockChannelStr, const std::string & blockChannelStr, bool have_blockRepTypeStr, const std::string & blockRepTypeStr, int numMatch, int numProbes, const std::string & probesStr, int lineNumber, bool keep, std::vector< bool > & probeSubSet, bool keepOrder)
Parse the results from one record into a ProbeList if desired, othewise just keep track of statistics.
Parameters:
name - Probeset identifier.
type - Class of probeset (i.e. genotyping, expression, copynumber) as in ProbeSet::Type enumeration
numBlocks - How many blocks are there in probeset.
blockSizes - Comma separated size in probes of each block.
blockAnns - Comma separated annotation for each block as in ProbeSet::BlockAnnotation enumeration
numMatch - How many matches (1 for pm only, 2 for pm-mm).
numProbes - Total number of probes.
probesStr - Comma separated list of probe ids (indexes).
lineNumber - Line number in file.
keep - Should this probelist be kept after getting statistics.
probeSubSet - Bool array with probes to be loaded marked as true.
keepOrder - Should the order of these probes be saved for layout order
name - Probeset identifier.
type - Class of probeset (i.e. genotyping, expression, copynumber) as in ProbeSet::Type enumeration
numBlocks - How many blocks are there in probeset.
blockSizes - Comma separated size in probes of each block.
blockAnns - Comma separated annotation for each block as in ProbeSet::BlockAnnotation enumeration
numMatch - How many matches (1 for pm only, 2 for pm-mm).
numProbes - Total number of probes.
probesStr - Comma separated list of probe ids (indexes).
lineNumber - Line number in file.
keep - Should this probelist be kept after getting statistics.
probeSubSet - Bool array with probes to be loaded marked as true.
Definition at line 320 of file ChipLayout.cpp.
References Err::errAbort(), getProbeCount(), makeProbeListPacked(), ProbeList::null_probe, Convert::strToIntVec(), and ToStr().
unsigned int ChipLayout::probeIdToIndex (unsigned int probeId) [inline]
Given probe id supply the index.
Parameters:
probeId - Id of probe.
Returns:
Index in chip.
Definition at line 377 of file ChipLayout.h.
void ChipLayout::readCdfProbe (Probe * p, Atom * parent, unsigned int numCol, unsigned int numRow, unsigned int direction, const affymetrix_fusion_io::FusionCDFProbeGroupInformation & group, const affymetrix_fusion_io::FusionCDFProbeInformation & cel)
Read cdf probe information into a Probe object.
Parameters:
p - probe object to be filled in.
parent - Atom that is parent of this probe.
numCol - column on chip.
numRow - row on chip.
direction - synthesis direction.
group - group information from cdf.
cel -probe information from cdf.
p - probe object to be filled in.
parent - Atom that is parent of this probe.
numCol - column on chip.
numRow - row on chip.
direction - target direction.
group - group information from cdf.
cel -probe information from cdf.
Todo:
there should be a Probe::PM type where direction is not known
Todo:
there should be a Probe::PM type where direction is not known
Definition at line 1765 of file ChipLayout.cpp.
References Probe::gcCount, affymetrix_fusion_io::FusionCDFProbeInformation::GetPBase(), affymetrix_fusion_io::FusionCDFProbeInformation::GetTBase(), affymetrix_fusion_io::FusionCDFProbeInformation::GetX(), affymetrix_fusion_io::FusionCDFProbeInformation::GetY(), Probe::id, isPm(), Verbose::out(), ToStr(), Probe::type, validBase(), and xyToIndex().
Referenced by readCdfProbeSet().
void ChipLayout::readCdfProbeSet (const std::string & name, affymetrix_fusion_io::FusionCDFProbeSetInformation & set, unsigned int psIx, int numCol, int numRow, std::vector< bool > & probeSubSet, bool & keepProbeSet, probeidmap_t & killList, ProbeSet & ps, int & psNameSize, std::vector< Atom > ** locAtoms, std::vector< Probe > ** locProbes, int & errorCount)
///
Parameters:
name ///
set ///
psIx ///
numCol ///
numRow ///
probeSubSet ///
keepProbeSet ///
killList ///
ps //
psNameSize ///
locAtoms ///
locProbes ///
errorCount Count of errors so far.
Definition at line 1873 of file ChipLayout.cpp.
References Atom::allele_code, ProbeSet::atoms, ProbeSet::atomsPerGroup, Atom::channel_code, Atom::context_code, Err::errAbort(), FROM_ZEROBASED, affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetAlleleCode(), affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetCell(), affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetChannel(), affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetDirection(), affymetrix_fusion_io::FusionCDFProbeInformation::GetListIndex(), affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetNumCells(), affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetNumLists(), affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetRepType(), affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetWobbleSituation(), Probe::id, Atom::id, inKillList(), isPm(), m_MmProbes, m_PmProbes, ProbeSet::name, ProbeSet::numGroups, Verbose::out(), Atom::probes, ProbeSet::psType, readCdfProbe(), Atom::replication_type, ToStr(), and Probe::type.
Referenced by readProbeListCdfFileKillList().
void ChipLayout::readProbeListCdfFileKillList (affymetrix_fusion_io::FusionCDFData & cdf, ProbeListFactory & plFactory, const std::set< const char *, Util::ltstr > & probeSetsToLoad, std::vector< const char * > * probesetNames, std::vector< bool > & probeSubSet, probeidmap_t & killList, bool justStats, std::set< affxcdf::GeneChipProbeSetType > & psTypesToLoad)
Read a vector of ProbeSets from a cdf file representation.
Parameters:
cdf - cdf file object with probe set information.
psVec - vector to put newly created probe sets in.
probeSetsToLoad - which probe sets should be converted.
probeSubSet - which individual probes were loaded.
probesetNames - If not null filled in with the probesetname for each probeset even if not actually into chiplayout. Useful for chp files where every single probeset must be included and in order.
killList - map of probes ids that shouldn't be used.
justStats - just read and generate stats, don't load into memory.
psTypesToLoad - What types of probesets to load into memory.
Todo:
if we arent keeping the probeset which has an error, then maybe we should ignore the error /// on that probeset and not abort.
Definition at line 2176 of file ChipLayout.cpp.
References ProbeSet::atoms, ProbeSet::atomsPerGroup, Util::cloneString(), Err::errAbort(), affymetrix_fusion_io::FusionCDFFileHeader::GetCols(), affymetrix_fusion_io::FusionCDFData::GetHeader(), affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets(), affymetrix_fusion_io::FusionCDFData::GetProbeSetInformation(), affymetrix_fusion_io::FusionCDFData::GetProbeSetName(), affymetrix_fusion_io::FusionCDFFileHeader::GetRows(), Probe::id, m_ProbeCounts, ProbeSet::name, Verbose::out(), Atom::probes, Verbose::progressStep(), readCdfProbeSet(), ToStr(), and writeSpfProbeSetRecord().
Referenced by openCdf().
void ChipLayout::readProbeListPgfFileKillList (affx::PgfFile & pgf, unsigned int numProbes, ProbeListFactory & plFactory, const std::set< const char *, Util::ltstr > & probeSetsToLoad, std::vector< const char * > * probesetNames, std::vector< const char * > * probesetDisplayNames, std::vector< bool > & probeSubset, probeidmap_t & killList, bool justStats)
Read the contents of rowFile into a vector of probe sets.
Parameters:
pgf - Opened Pgf file to read from
numProbes - How many probes are on this chip?
psVec - vector to be filled in.
probeSetsToLoad - Vector of probe set ids to be loaded.
probeSubset - Subset of probes to be loaded.
killList - List of probes not to be used.
Definition at line 1280 of file ChipLayout.cpp.
References affx::PgfFile::atom_id, ProbeSet::atoms, ProbeSet::atomsPerGroup, Util::cloneString(), Err::errAbort(), affx::PgfFile::gc_count, Probe::gcCount, affx::TsvFile::getHeader(), affx::TsvFile::headersFindNext(), Probe::id, Atom::id, inKillList(), m_ProbeCounts, affx::PgfFile::m_tsv, ProbeSet::name, affx::PgfFile::next_atom(), affx::PgfFile::next_probe(), affx::PgfFile::next_probeset(), ProbeSet::numGroups, Verbose::out(), affx::PgfFile::probe_id, affx::PgfFile::probe_type, Atom::probes, affx::PgfFile::probeset_id, affx::PgfFile::probeset_name, Verbose::progressStep(), ProbeSet::psType, affx::PgfFile::rewind(), Convert::toInt(), ToStr(), Probe::type, Probe::typeForString(), Verbose::warn(), and writeSpfProbeSetRecord().
Referenced by openPgf().
void ChipLayout::setDimensions (unsigned int xCount, unsigned int yCount) [inline]
Set the x and y dimensions for the array.
Parameters:
xCount - Maximum value of x + 1 (corresponds to columns)
yCount - Maximium value of y + 1 (corresponds to rows)
Definition at line 349 of file ChipLayout.h.
References m_PlFactory, and m_XCount.
Referenced by openCdf(), openPgf(), openSpf_v3(), and openSpf_v4().
void ChipLayout::setPmProbeMask (const std::vector< bool > & mask) [inline]
Set the perfect match probes of chip.
Parameters:
mask with PM probes marked as true, others false.
Definition at line 312 of file ChipLayout.h.
References m_PmProbes.
void ChipLayout::setSpfFileName (const std::string & fileName) [inline]
Set the name of the spf output file ///.
Parameters:
fileName Filename to write.
Definition at line 669 of file ChipLayout.h.
void ChipLayout::sortProbesetNameByProbesetIdx (std::vector< std::string >::iterator begin, std::vector< std::string >::iterator end)
compare probeset names according to respective probeset ids
Parameters:
a,b - probeset names to be ordered Do we need mismatch probes?
a,b - probeset names to be ordered
Definition at line 2693 of file ChipLayout.cpp.
References getProbeSetIndexByName().
void ChipLayout::trackGlobalStats (const std::string & name, int type, int numBlocks, const std::vector< int > & blockSizes, int numMatch, const std::vector< int > & probes, bool multAlleles = false)
Keep track of global stats as we parse through file.
Parameters:
name - Name of probeset
type - Class of probeset (as in ProbeSet::Type)
numBlocks - How many blocks are in the probeset.
numMatch - How many matches are there (1 for pm only, 2 for pm-mm)
probes - Vector of the probe ids/indexes in the array.
Definition at line 2450 of file ChipLayout.cpp.
References CumulativeStats< T, LargeNumber >::addData(), m_MmProbes, m_PmMmVec, m_PmProbes, m_ProbeCounts, m_ProbesetProbes, Max, ProbeList::null_probe, and round().
const char * ChipLayout::typeFromCdfType (unsigned short type)
Convert from numeric representation to string.
Parameters:
type - numeric representation.
Definition at line 1704 of file ChipLayout.cpp.
References Err::errAbort(), and ToStr().
bool ChipLayout::validBase (int c)
Check to see if a charater is a valid DNA base of 'a','t','g', or 'c'.
Parameters:
c - base to check.
Returns:
- return true if c is in 'atgcATGC', false otherwise.
Definition at line 1747 of file ChipLayout.cpp.
Referenced by readCdfProbe().
void ChipLayout::write (const std::string & fileName)
Write out the data in class to file in PGF format.
Parameters:
fileName - Name of file to write data.
void ChipLayout::writePgfFile (const std::string & fileName, const std::vector< ProbeSet * > & vec) [static]
Write out the contents of probe sets in PGF format.
Parameters:
fileName - File to write data to.
vec - Vector of probe sets to be stored.
Definition at line 1631 of file ChipLayout.cpp.
References affx::PgfFile::close(), affx::PgfFile::defineFilePgf(), and affx::PgfFile::write().
void ChipLayout::writePgfFile (affx::PgfFile & pgf, const std::vector< ProbeSet * > & vec) [static]
Write out the contents of probe sets in PGF format.
Write the vector of probesets to a PGF file.
Parameters:
out - output stream to write data to.
vec - Vector of probe sets to be stored.
pgf - Pgf to write to
vec -
Todo:
shouldnt this be called "writePgfProbeSetVector"?
Todo:
type here is not right - should not be probeset ID
Todo:
these were not defined in ProbeSet.h so we cant write them out.
Definition at line 1648 of file ChipLayout.cpp.
References ProbeSet::atoms, Probe::gcCount, Probe::id, Atom::id, affx::PgfFile::m_tsv, ProbeSet::name, Atom::probes, Probe::stringForType(), ToStr(), Probe::type, and affx::TsvFile::writeLevel().
void ChipLayout::writeSpfProbeList (const std::string & fileName, int spfFormat = 2)
Write out our probelist information in our simple probe format.
Parameters:
fileName - path to write file out to
Definition at line 247 of file ChipLayout.cpp.
References affx::TsvFile::close(), m_PlFactory, and writeSpfProbeListRecord().
void ChipLayout::writeSpfProbeListRecord (affx::SpfFile & tsv, const ProbeListPacked & pL) [static]
Write out a single record to the tsv file supplied.
Parameters:
tsv - TsvFile opened and bound.
pL - ProbeList record to write out.
Definition at line 186 of file ChipLayout.cpp.
References APT_ERR_ASSERT, ProbeListPacked::get_blockSize(), affx::SpfFile::m_spf_format, ProbeList::null_probe, ToStr(), and affx::TsvFile::writeLevel().
Referenced by writeSpfProbeList().
void ChipLayout::writeSpfProbeSetRecord (affx::SpfFile & tsv, const ProbeSet & ps) [static]
Write out a single record to the tsv file supplied.
Parameters:
tsv - TsvFile opened and bound.
pL - ProbeList record to write out.
Definition at line 81 of file ChipLayout.cpp.
References APT_ERR_ASSERT, ProbeSet::atoms, ProbeSet::atomsPerGroup, Probe::id, affx::SpfFile::m_spf_format, ProbeSet::name, ProbeList::null_probe, ProbeSet::numGroups, Atom::probes, ProbeSet::psType, ToStr(), and affx::TsvFile::writeLevel().
Referenced by readProbeListCdfFileKillList(), and readProbeListPgfFileKillList().
int ChipLayout::xyToIndex (int x, int y)
Turn the x and y cordinates of a probe on the array into an index.
Should be exactly the same index as provided by cel files.
Parameters:
x - x coordinate on array.
y - y coordinate on array.
Returns:
- index (id) of feature in cel file and other arrays.
Definition at line 1695 of file ChipLayout.cpp.
References m_XCount.
Referenced by readCdfProbe().
Member Data Documentation
bool ChipLayout::m_haveKillList
Vector of the types for each probeset, used by calvin chp files to /// determine size of file. Note that probesets marked as "GenoType" but only /// having one block are changed here to "Expression".
Was the chip layout read in with a kill list
Definition at line 1006 of file ChipLayout.h.
Referenced by ChipLayout(), openCdf(), openPgf(), openSpf_v3(), and openSpf_v4().
int ChipLayout::m_NumExpression
Iterator to walk through the map.
Todo:
: harley remove this /// map of probe sets by names.
map of probe sets by ids Are probe sets accesible by name? Number of expression probesets
Definition at line 980 of file ChipLayout.h.
Referenced by ChipLayout(), and getNumExpressionPSets().
ProbeListFactory ChipLayout::m_PlFactory
Todo:
: harley remove this ///< Vector of actual probe sets that got read information
Definition at line 961 of file ChipLayout.h.
Referenced by containsProbeSet(), findProbeApidByIdx(), findProbeApidByName(), findProbeApidByProbeId(), getProbeListAtIndex(), getProbeListByName(), getProbeSetCount(), getProbeSetIndexByName(), getProbeSetType(), isGenotypable(), makeProbeListPacked(), openCdf(), openPgf(), QuantMethodFactory::openPrecompFeatureEffects(), QuantMethodFactory::quantMethodForString(), QuantMethodFactory::readPrecompFeatureEffectsFromFile(), setDimensions(), QuantRma::setParameters(), QuantPlierBase::setParameters(), and writeSpfProbeList().
unsigned int ChipLayout::m_XCount
Todo:
change to colrow_t /// Number of values in X and Y axis of chip.
Definition at line 964 of file ChipLayout.h.
Referenced by ChipLayout(), CelExtract::defineExtractTsv(), getProbeCount(), getXCount(), indexToXY(), openPgf(), openSpf_v3(), openSpf_v4(), setDimensions(), and xyToIndex().
The documentation for this class was generated from the following files:
chipstream/ChipLayout.h
chipstream/ChipLayout.cpp