Affymetrix Power Tools: CNFamilialAnalysisMethodCNLossLOHConcordance Class Reference
CNFamilialAnalysisMethodCNLossLOHConcordance Class Reference
The CNLossLOHConcordance Familial analysis method.
#include <CNFamilialAnalysisMethodCNLossLOHConcordance.h>