Affymetrix Power Tools: CNFamilialAnalysisMethodCNNeutralLOHConcordance Class Reference
CNFamilialAnalysisMethodCNNeutralLOHConcordance Class Reference
The CNNeutralLOHConcordance Familial analysis method.
#include <CNFamilialAnalysisMethodCNNeutralLOHConcordance.h>