Affymetrix Power Tools: CovariateParams Class Reference
CovariateParams Class Reference
A class to process the covariate command line.
#include <CNAnalysisMethodCovariateParams.h>
Static Public Member Functions
static void checkParams (BaseEngine &engine)
static void determineCovariateMap (BaseEngine &engine)
Initializes the signal and LR covariate map members.
static void restoreCovariateParams (std::string str)
Restore covariate parameter from the Parameters section of the CN reference to the corresponding class member:
static int mapCovariateNameToIndex (const std::string &str)
static std::string translateToParamString (const std::map< string, int > &covMap)
static void translateFromParamString (const std::string &str, std::map< std::string, int > &retMap)
static bool isReservedCovariateName (const std::string &str)
static bool useEquallyPopulatedSignalBins (int covariateIndex)
static bool useEquallySpacedSignalBins (int covariateIndex)
static bool isSignalCovariateDiscrete (int covariateIndex)
static int getNumSignalBins (int covariateIndex)
static bool useEquallyPopulatedLRBins (int covariateIndex)
static bool useEquallySpacedLRBins (int covariateIndex)
static bool isLRCovariateDiscrete (int covariateIndex)
static int getNumLRBins (int covariateIndex)
static bool useEquallyPopulatedAPBins (int covariateIndex)
static bool useEquallySpacedAPBins (int covariateIndex)
static bool isAPCovariateDiscrete (int covariateIndex)
static int getNumAPBins (int covariateIndex)
Static Public Attributes
static const std::string m_CNReferencePrefix
static std::map< string, int > m_allCovariateMap
static std::vector< int > m_vSignalCovariates
static std::vector< int > m_vLRCovariates
static std::vector< int > m_vAPCovariates
static std::vector< std::string > m_vSignalBinningType
static std::vector< int > m_vSignalBinSizes
static std::vector< std::string > m_vLRBinningType
static std::vector< int > m_vLRBinSizes
static std::vector< std::string > m_vIQRScaling
static std::vector< std::string > m_vLRSubractFromXY
static std::vector< std::string > m_vAPBinningType
static std::vector< int > m_vAPBinSizes
static std::vector< std::string > m_vCoarseAPAdjust
static std::vector< int > m_vCoarseAPAdjustStep
static std::vector< int > m_vCoarseAPAdjustWindow
static std::vector< int > m_vCoarseAPAdjustPointCount
static std::vector< double > m_vCoarseAPAdjustBandwidth
static std::vector< double > m_vCoarseAPAdjustCutoff
static std::vector< double > m_vCoarseAPAdjustCleanthreshold
static std::vector< double > m_vCoarseAPAdjustOutliertrim
static int m_masterPeakPointCount
static double m_masterPeakBandwidth
static int m_covariatePeakPointCount
static double m_covariatePeakBandwidth
static std::string m_kernelFunctionSelection
static std::string m_signalCommand
static std::string m_LRCommand
static std::string m_APCommand
Detailed Description
A class to process the covariate command line.
Definition at line 45 of file CNAnalysisMethodCovariateParams.h.
Member Function Documentation
void CovariateParams::determineCovariateMap (BaseEngine & engine) [static]
Initializes the signal and LR covariate map members.
The value represents the index in CNProbeSet::getCovariateValue(). The index is the CovariateEnum. Side effect: this method also initializes the number of bins and binning type paramters.
Definition at line 249 of file CNAnalysisMethodCovariateParams.cpp.
References SelfCreate::fillInNameParam(), Options::getOpt(), Options::isOptDefined(), Verbose::out(), and Convert::toString().
void CovariateParams::restoreCovariateParams (std::string str) [static]
Restore covariate parameter from the Parameters section of the CN reference to the corresponding class member:
"all" -> m_allCovariateMap "signal" -> m_vSignalCovariates "log2ratio -> m_vLRCovariates "signal-binning-types" -> m_vSignalBinningType "signal-bin-sizes" -> m_vSignalBinSizes "log2ratio-binning-types" -> m_vLRBinningType "log2ratio-bin-sizes" -> m_vLRBinSizes "log2ratio-iqr-scaling" -> m_vIQRScaling "log2ratio-subtract-from-XY" -> m_vLRSubractFromXY
Definition at line 326 of file CNAnalysisMethodCovariateParams.cpp.
References Convert::strToDoubleVec(), Convert::strToIntVec(), Convert::strToStrVec(), Convert::toDouble(), and Convert::toInt().
Referenced by CNLog2RatioData::loadModelFile().
The documentation for this class was generated from the following files:
copynumber/CNAnalysisMethodCovariateParams.h
copynumber/CNAnalysisMethodCovariateParams.cpp