Affymetrix Power Tools: ProbeListFactory Class Reference
ProbeListFactory Class Reference
A Factory for allocating and retrieving ProbeListPacked objects. /// It really should be called ProbeListPackedFactory or PackedProbeListFactory.
#include <ProbeListFactory.h>
Public Member Functions
int getXYsize ()
int getProbeSetCount () const
int getProbeSetIndexByName (const std::string &name) const
void reserve (int size)
void getDimensions (int cols, int rows) const
void setDimensions (int cols, int rows)
int numChannels () const
void setNumChannels (int num_channels)
void incApid (int cnt)
unsigned int getApidMax () const
int findProbeApidByName (const std::string &qName, int qPid, int qAllele, int qContext, int qChannel) const
int findProbeApidByIdx (int qPlIdx, int qPid, int qAllele, int qContext, int qChannel) const
void buildProbeId2ApidIndex () const
This only works when the probeids are unique. (Ie: single channel).
int findProbeApidByProbeId (int qPid) const
void set_default_region_size (int size)
void new_region ()
void new_region (int region_size)
void delete_regions ()
void clear ()
char * alloc_ProbeList_bytes (int size)
ProbeListPacked add_ProbeList (int block_cnt, int probe_cnt, int name_len)
ProbeListPacked add_ProbeList (int block_cnt, int probe_cnt, const std::string &name)
ProbeListPacked add_ProbeList (const ProbeListStl &pl)
void pListFromPSet (const ProbeSet &ps)
void readSpfFile (const std::string &spfName)
void readSpfFile (affx::SpfFile &spfFile)
void writeSpfFile (const std::string &spfName, int spfFormat) const
void writeSpfFile (const std::string &spfName, int spfFormat, int with_allelecontext, int with_channel) const
void writeToSpfFile (affx::SpfFile &spfFile) const
void writeToSpfFile_v2 (affx::SpfFile &spfFile) const
void writeToSpfFile_v3 (affx::SpfFile &spfFile) const
void writeToSpfFile_v4 (affx::SpfFile &spfFile) const
ProbeListPacked getProbeListAtIndex (int i) const
ProbeListPacked getProbeListByName (const std::string &name) const
int getProbeListIndexByName (const std::string &name) const
std::string getProbeListName (int i) const
const char * getProbeListNameCstr (int i) const
void assertName2IdxSorted (int verbose) const
check that the probelists are indeed sorted by name. /// shouldnt need to call this unless you think they arent sorted.
void ensureSortedName2Idx () const
ensures that the map is sorted.
void sortFactoryByName ()
put the probelists in order by their name. /// NB: this will change the index order; Thus the results of getProbeListAtIndex will change.
void dump () const
for debugging... display the contents of the Factory.
void dump_regions () const
for debugging...
void dump_probelist (int i) const
void dump_probelists () const
Static Public Member Functions
static bool hasNonPm (const ProbeSet &ps)
static unsigned int countPmProbes (const ProbeSet *ps)
static bool maybeInsertProbe (Atom *a, int position, int id, unsigned char gcCount, unsigned char type, int apid)
static ProbeSet * asProbeSet (const ProbeListPacked &pl)
static double safe_div (double a, double b)
static void writeProbeListToSpfFile_v4 (affx::SpfFile &spfFile, ProbeListPacked pl)
static void writeProbeListToSpfFile_v3 (affx::SpfFile &spfFile, ProbeListPacked pl)
Public Attributes
std::vector
< ProbeListFactory_Region > m_region
regions which this factory has available to fill.
unsigned int m_ridx
current region in which allocations will occur.
int m_default_region_size
how big should automaticly allocated regions be?
unsigned int m_allocs
keep track of the number of allocations for usage info.
std::vector< ProbeListPacked > m_probelist_vec
Pointers to the start of each Probelist in our regions.
std::vector< std::string > m_chipTypes
int m_numCols
int m_numRows
int m_numChannels
std::vector< int > m_name2idx_vec
these are mutable as we lazily sort when needed. /// A vector of indexes sorted by name.
bool m_name2idx_issorted
Is the vector currenly sorted? (So we dont have to sort each time.).
int m_name2idx_sortcnt
std::vector< int > * m_probeid2apid_vecptr
unsigned int m_probecnt_total
the total number of probes in this factory. /// this is used to assign AnalysisProbeIds as probes are added.
Static Public Attributes
static double timecheck1
static double timecheck2
static double timecheck3
static double timecheck4
static double timecheck5
Detailed Description
A Factory for allocating and retrieving ProbeListPacked objects. /// It really should be called ProbeListPackedFactory or PackedProbeListFactory.
Definition at line 694 of file ProbeListFactory.h.
Member Function Documentation
ProbeListPacked ProbeListFactory::add_ProbeList (int block_cnt, int probe_cnt, int name_len)
Todo:
change all asserts to APT_ERR_ASSERT()
Definition at line 786 of file ProbeListFactory.cpp.
Referenced by apt_falcon_merge_plf2plf_nonas(), and ChipLayout::makeProbeListPacked().
ProbeSet * ProbeListFactory::asProbeSet (const ProbeListPacked & pl) [static]
Todo:
this should be "ProbeSet::operator=()"
Todo:
I do not think we keep track of st vs at probes -- so we should really /// have a Probe::PM and Probe::MM and set that here
Definition at line 1010 of file ProbeListFactory.cpp.
References Atom::allele_code, ProbeSet::atoms, ProbeSet::atomsPerGroup, Atom::channel_code, Util::cloneString(), Atom::context_code, Err::errAbort(), ProbeListPacked::get_blockSize(), ProbeListPacked::get_probeApid(), Atom::id, ProbeSet::name, ProbeList::null_probe, ProbeSet::numGroups, Atom::probes, ProbeSet::psType, Atom::replication_type, and ToStr().
Referenced by VariabilityScoreCelListener::calcStats(), callGenotypes(), CelExtract::CelExtract(), CelExtract::doProbeSet(), doRma(), HomHiLoCelListener::fillInContrastValues(), EmGenderCelListener::fillInContrastValues(), MultiChannelNonOverlapCelListener::GimmeContrast(), MultiChannelHomHiLoCelListener::GimmeContrast(), AdapterTypeNormTran::loadAnnotation(), QuantLabelZ::makeNorm(), QuantBRLMM::makePrior(), DmListener::newChip(), and QuantMethodTransform::transformData().
void ProbeListFactory::buildProbeId2ApidIndex () const
This only works when the probeids are unique. (Ie: single channel).
Build an index mapping ProbeId to Apid of _unique_ probeids /// Having a non-unique mapping is ok, using it is not.
Definition at line 1917 of file ProbeListFactory.cpp.
References APT_ERR_ABORT, ProbeList::null_probe, Verbose::out(), and ToStr().
void ProbeListFactory::sortFactoryByName ()
put the probelists in order by their name. /// NB: this will change the index order; Thus the results of getProbeListAtIndex will change.
This changes the order of the probes in m_probelist_vec to be /// in name order.
Definition at line 1699 of file ProbeListFactory.cpp.
References APT_ERR_ASSERT, ensureSortedName2Idx(), m_name2idx_vec, and m_probelist_vec.
The documentation for this class was generated from the following files:
chipstream/ProbeListFactory.h
chipstream/ProbeListFactory.cpp