Affymetrix Power Tools: CNFamilialAnalysisMethod Class Reference
CNFamilialAnalysisMethod Class Reference
A base class for copy number quant methods.
#include <CNFamilialAnalysisMethod.h>