Affymetrix Power Tools: affymetrix_dttarray::DttArrayFileReader Class Reference
affymetrix_dttarray::DttArrayFileReader Class Reference
#include <DttArrayFileReader.h>
Public Member Functions
DttArrayFileReader ()
~DttArrayFileReader ()
std::string GetFileName () const
void SetFileName (const char *file)
bool Read (DttArrayData &arrayData)
bool Exists ()
Protected Attributes
std::string m_FileName
Detailed Description
This class provides interfaces to read an array file.
Definition at line 112 of file DttArrayFileReader.h.
Constructor & Destructor Documentation
DttArrayFileReader::DttArrayFileReader ()
Constructor
Definition at line 62 of file DttArrayFileReader.cpp.
DttArrayFileReader::~DttArrayFileReader ()
Destructor
Definition at line 69 of file DttArrayFileReader.cpp.
Member Function Documentation
bool DttArrayFileReader::Exists ()
Checks for the existance of the file.
Returns:
True if the file exists.
Definition at line 121 of file DttArrayFileReader.cpp.
References m_FileName.
std::string affymetrix_dttarray::DttArrayFileReader::GetFileName () const [inline]
Gets the file name.
Returns:
The full path of the array file.
Definition at line 128 of file DttArrayFileReader.h.
References m_FileName.
bool DttArrayFileReader::Read (DttArrayData & arrayData)
Reads the entire contents of the array file.
Parameters:
arrayData The array data to read from the file.
Returns:
True if successfully read.
Definition at line 76 of file DttArrayFileReader.cpp.
References affymetrix_dttarray::DttArrayData::Clear(), and m_FileName.
Referenced by affymetrix_fusion_io::FusionArrayFileReader::Read().
void affymetrix_dttarray::DttArrayFileReader::SetFileName (const char * file) [inline]
Sets the file name.
Parameters:
file The full path of the array file.
Definition at line 133 of file DttArrayFileReader.h.
References m_FileName.
Referenced by affymetrix_fusion_io::FusionArrayFileReader::Read().
Member Data Documentation
std::string affymetrix_dttarray::DttArrayFileReader::m_FileName [protected]
The full path name to the DTT array file.
Definition at line 116 of file DttArrayFileReader.h.
Referenced by Exists(), GetFileName(), Read(), and SetFileName().
The documentation for this class was generated from the following files:
file/DttArrayFileReader.h
file/DttArrayFileReader.cpp