Affymetrix Power Tools: CNFamilialAnalysisMethodIsoUPD Class Reference
CNFamilialAnalysisMethodIsoUPD Class Reference
The IsoUPD Familial analysis method.
#include <CNFamilialAnalysisMethodIsoUPD.h>