Affymetrix Power Tools: affx::File5_File Class Reference
affx::File5_File Class Reference