Affymetrix Power Tools: affxcdf::CCDFFileHeader Class Reference
affxcdf::CCDFFileHeader Class Reference
#include <CDFFileData.h>
Public Member Functions
int GetFormatVersion () const
std::string GetGUID () const
std::string GetIntegrityMd5 () const
std::string GetChipType () const
std::vector< std::string > GetChipTypes () const
int GetCols () const
int GetRows () const
int GetNumProbeSets () const
int GetNumQCProbeSets () const
std::string & GetReference ()
CCDFFileHeader ()
Protected Attributes
int m_Magic
int m_Version
std::string m_GUID
std::string m_IntegrityMd5
std::string m_ChipType
std::vector< std::string > m_ChipTypes
int m_NumProbeSets
int m_NumQCProbeSets
std::string m_Reference
unsigned short m_Cols
unsigned short m_Rows
Friends
class CCDFFileData
Detailed Description
Storage for the header in a CDF file.
Definition at line 62 of file CDFFileData.h.
Constructor & Destructor Documentation
CCDFFileHeader::CCDFFileHeader ()
Constructor
Definition at line 61 of file CDFFileData.cpp.
Member Function Documentation
std::string affxcdf::CCDFFileHeader::GetChipType () const [inline]
Get chip type - array type name without version
Returns:
The chip type.
Definition at line 120 of file CDFFileData.h.
References m_ChipType.
Referenced by affxcdf::CCDFFileData::GetChipType().
std::vector<std::string> affxcdf::CCDFFileHeader::GetChipTypes () const [inline]
Get chip types - array type names with and without version
Returns:
The chip types.
Definition at line 125 of file CDFFileData.h.
References m_ChipTypes.
Referenced by affxcdf::CCDFFileData::GetChipTypes().
int affxcdf::CCDFFileHeader::GetCols () const [inline]
Gets the number of feature columns in the array.
Returns:
The number of columns.
Definition at line 130 of file CDFFileData.h.
References m_Cols.
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::GetCols().
int affxcdf::CCDFFileHeader::GetFormatVersion () const [inline]
Get CDF Format Version
Returns:
CDF Format Version
Definition at line 105 of file CDFFileData.h.
References m_Version.
Referenced by affxcdf::CCDFFileData::GetChipType(), affxcdf::CCDFFileData::GetChipTypes(), affymetrix_fusion_io::FusionCDFFileHeader::GetFormatVersion(), affxcdf::CCDFFileData::GetGUID(), and affxcdf::CCDFFileData::GetIntegrityMd5().
std::string affxcdf::CCDFFileHeader::GetGUID () const [inline]
Get GUID
Returns:
GUID
Definition at line 110 of file CDFFileData.h.
References m_GUID.
Referenced by affxcdf::CCDFFileData::GetGUID(), and affymetrix_fusion_io::FusionCDFFileHeader::GetGUID().
std::string affxcdf::CCDFFileHeader::GetIntegrityMd5 () const [inline]
Get integrity md5
Returns:
The integrity md5
Definition at line 115 of file CDFFileData.h.
References m_IntegrityMd5.
Referenced by affxcdf::CCDFFileData::GetIntegrityMd5(), and affymetrix_fusion_io::FusionCDFFileHeader::GetIntegrityMd5().
int affxcdf::CCDFFileHeader::GetNumProbeSets () const [inline]
Gets the number of probe sets.
Returns:
The number of probe sets.
Definition at line 140 of file CDFFileData.h.
References m_NumProbeSets.
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets().
int affxcdf::CCDFFileHeader::GetNumQCProbeSets () const [inline]
Gets the number of QC probe sets.
Returns:
The number of QC probe sets.
Definition at line 145 of file CDFFileData.h.
References m_NumQCProbeSets.
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::GetNumQCProbeSets(), and affxcdf::CCDFFileData::GetQCProbeSetInformation().
std::string& affxcdf::CCDFFileHeader::GetReference () [inline]
Gets the reference sequence (for resequencing arrays only).
Returns:
The reference sequence.
Definition at line 150 of file CDFFileData.h.
References m_Reference.
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::Initialize().
int affxcdf::CCDFFileHeader::GetRows () const [inline]
Gets the number of feature rows in the array.
Returns:
The number of rows.
Definition at line 135 of file CDFFileData.h.
References m_Rows.
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::GetRows().
Friends And Related Function Documentation
friend class CCDFFileData [friend]
Friend to the parent class
Definition at line 99 of file CDFFileData.h.
Member Data Documentation
std::string affxcdf::CCDFFileHeader::m_ChipType [protected]
The chip type - array type name without version (only apply to XDA version 4 or above
Definition at line 78 of file CDFFileData.h.
Referenced by GetChipType(), affxcdf::CCDFFileData::ReadTextFormat(), and affxcdf::CCDFFileData::ReadXDAHeader().
std::vector<std::string> affxcdf::CCDFFileHeader::m_ChipTypes [protected]
The array of chip types - all array type names with and without versions (only apply to XDA version 4 or above
Definition at line 81 of file CDFFileData.h.
Referenced by GetChipTypes(), affxcdf::CCDFFileData::ReadTextFormat(), and affxcdf::CCDFFileData::ReadXDAHeader().
unsigned short affxcdf::CCDFFileHeader::m_Cols [protected]
The number of feature columns in the array
Definition at line 93 of file CDFFileData.h.
Referenced by GetCols(), affxcdf::CCDFFileData::ReadTextFormat(), and affxcdf::CCDFFileData::ReadXDAHeader().
std::string affxcdf::CCDFFileHeader::m_GUID [protected]
The GUID
Definition at line 72 of file CDFFileData.h.
Referenced by GetGUID(), affxcdf::CCDFFileData::ReadTextFormat(), and affxcdf::CCDFFileData::ReadXDAHeader().
std::string affxcdf::CCDFFileHeader::m_IntegrityMd5 [protected]
The integrity md5
Definition at line 75 of file CDFFileData.h.
Referenced by GetIntegrityMd5(), affxcdf::CCDFFileData::ReadTextFormat(), and affxcdf::CCDFFileData::ReadXDAHeader().
int affxcdf::CCDFFileHeader::m_Magic [protected]
The magic number in an XDA file
Definition at line 66 of file CDFFileData.h.
Referenced by affxcdf::CCDFFileData::ReadXDAHeader().
int affxcdf::CCDFFileHeader::m_NumProbeSets [protected]
The number of probe sets defined in the file
Definition at line 84 of file CDFFileData.h.
Referenced by GetNumProbeSets(), affxcdf::CCDFFileData::ReadTextFormat(), affxcdf::CCDFFileData::ReadXDAFormat(), and affxcdf::CCDFFileData::ReadXDAHeader().
int affxcdf::CCDFFileHeader::m_NumQCProbeSets [protected]
The number of QC probe sets in the file
Definition at line 87 of file CDFFileData.h.
Referenced by GetNumQCProbeSets(), affxcdf::CCDFFileData::ReadTextFormat(), affxcdf::CCDFFileData::ReadXDAFormat(), and affxcdf::CCDFFileData::ReadXDAHeader().
std::string affxcdf::CCDFFileHeader::m_Reference [protected]
The reference sequence (used for resequencing arrays only)
Definition at line 90 of file CDFFileData.h.
Referenced by GetReference(), affxcdf::CCDFFileData::ReadTextFormat(), and affxcdf::CCDFFileData::ReadXDAHeader().
unsigned short affxcdf::CCDFFileHeader::m_Rows [protected]
The number of feature rows in the array
Definition at line 96 of file CDFFileData.h.
Referenced by GetRows(), affxcdf::CCDFFileData::ReadTextFormat(), and affxcdf::CCDFFileData::ReadXDAHeader().
int affxcdf::CCDFFileHeader::m_Version [protected]
The version number
Definition at line 69 of file CDFFileData.h.
Referenced by GetFormatVersion(), affxcdf::CCDFFileData::GetProbeSetInformation(), affxcdf::CCDFFileData::ReadTextFormat(), and affxcdf::CCDFFileData::ReadXDAHeader().
The documentation for this class was generated from the following files:
file/CDFFileData.h
file/CDFFileData.cpp