Affymetrix Power Tools: GenderCalls Class Reference
GenderCalls Class Reference
Class for determining gender from a cel set of cel files.
#include <GenderCalls.h>