Affymetrix Power Tools: EmGenderCelListener Class Reference
EmGenderCelListener Class Reference
Class for determining gender from a cel set of cel files.
#include <EmGenderCelListener.h>