Affymetrix Power Tools: Convert Class Reference
Convert Class Reference
Convert.
#include <Convert.h>
Static Public Member Functions
static int toInt (const std::string &num)
Make an int from a c string or die trying.
static int toIntCheck (const std::string &num, bool *success)
Make an int from a c string.
static unsigned int toUnsignedInt (const std::string &num)
Make an unsigned int from a c string or die trying.
static unsigned int toUnsignedIntCheck (const std::string &num, bool *success)
Make an unsigned int from a c string.
static uint64_t toUnsignedInt64 (const std::string &num)
Make an unsigned int from a c string or die trying.
static uint64_t toUnsignedInt64Check (const std::string &num, bool *success)
Make an unsigned int from a c string.
static float toFloat (const std::string &num)
Make an float from a c string.
static float toFloatCheck (const std::string &num, bool *success)
Make an float from a c string.
static double toDouble (const std::string &num)
Make an double from a c string.
static double toDoubleCheck (const std::string &num, bool *success)
Make an double from a c string.
static bool toBool (const std::string &flag)
Make an bool from a c string.
static bool toBoolCheck (const std::string &flag, bool *success)
Make an bool from a c string.
static std::string toString (int i)
Make a string from an integer.
static std::string toString (double d)
Make a string from an double.
static bool doubleCloseEnough (double d1, double d2, int digits=6)
Test to make sure that two doubles are pretty similar.
static float floatLowPrecision (float f)
Make a low precision float from a normal one.
static void strToIntVec (const std::string &s, char delim, std::vector< int > &vec)
Utility function to cut a delimited string into a vector of ints.
static void strToDoubleVec (const std::string &s, const char delim, std::vector< double > &vec)
Utility function to cut a delimited string into a vector of doubles.
static void strToStrVec (const std::string &s, const char delim, std::vector< std::string > &vec)
Utility function to cut a delimited string into a vector of strings.
static std::string intVecToString (const std::vector< int > &inputVector, const std::string &delim)
The inverse of strToIntVec.
static std::string doubleVecToString (const std::vector< double > &inputVector, const std::string &delim)
The inverse of strToDoubleVec.
static std::string strVecToString (const std::vector< std::string > &inputVector, const std::string &delim)
Same as intVecToString but using string vectors.
Detailed Description
Convert.
Utility functions to convert between different types.
Definition at line 45 of file Convert.h.
Member Function Documentation
bool Convert::doubleCloseEnough (double d1, double d2, int digits = 6) [static]
Test to make sure that two doubles are pretty similar.
Parameters:
d1
d2
digits - number of decimal places to examine.
Returns:
true if doubles are same to digits decimal places.
Parameters:
f1
f2
Returns:
true if doubles are same to 6 significant digits.
Definition at line 411 of file Convert.cpp.
std::string Convert::doubleVecToString (const std::vector< double > & inputVector, const std::string & delim) [static]
The inverse of strToDoubleVec.
Convert a double vector to string.
Parameters:
inputVector - the vector to convert
delim - delimiter to use
Returns:
- the resulting string
Definition at line 472 of file Convert.cpp.
References toString().
float Convert::floatLowPrecision (float f) [static]
Make a low precision float from a normal one.
Used originally to mimic truncation seen in cel files.
Parameters:
f float to be truncated.
Returns:
truncated float
Definition at line 424 of file Convert.cpp.
Referenced by SketchQuantNormTran::newChipSuppliedTargetSketch(), SketchQuantNormTran::transform(), and MedNormTran::transform().
std::string Convert::intVecToString (const std::vector< int > & inputVector, const std::string & delim) [static]
The inverse of strToIntVec.
Convert an integer vector to string.
Parameters:
inputVector - the vector to convert
delim - delimiter to use
Returns:
- the resulting string
Definition at line 455 of file Convert.cpp.
References toString().
void Convert::strToDoubleVec (const std::string & s, const char delim, std::vector< double > & vec) [static]
Utility function to cut a delimited string into a vector of doubles.
Parameters:
s - delimited string.
delim - delimiter to chop on.
vec - vector to be filled in.
Definition at line 441 of file Convert.cpp.
References Util::chopString(), and toDouble().
Referenced by CovariateParams::restoreCovariateParams().
void Convert::strToIntVec (const std::string & s, char delim, std::vector< int > & vec) [static]
Utility function to cut a delimited string into a vector of ints.
Parameters:
s - delimited string.
delim - delimiter to chop on.
vec - vector to be filled in.
Definition at line 429 of file Convert.cpp.
References Util::chopString(), and toInt().
Referenced by ChipLayout::parseProbeListRecord(), and CovariateParams::restoreCovariateParams().
void Convert::strToStrVec (const std::string & s, const char delim, std::vector< std::string > & vec) [static]
Utility function to cut a delimited string into a vector of strings.
Parameters:
s - delimited string.
delim - delimiter to chop on.
vec - vector to be filled in.
Definition at line 504 of file Convert.cpp.
References Util::chopString().
Referenced by CovariateParams::restoreCovariateParams().
std::string Convert::strVecToString (const std::vector< std::string > & inputVector, const std::string & delim) [static]
Same as intVecToString but using string vectors.
Convert a string vector to string.
Parameters:
inputVector - the vector to convert
delim - delimiter to use
Returns:
- the resulting string
Silly but someone's got to do it.
Definition at line 489 of file Convert.cpp.
bool Convert::toBool (const std::string & flag) [static]
Make an bool from a c string.
Parameters:
flag - c string representation of number to be parsed. allowed value are 'true' && 'false'
Returns:
- Bool representation of flag
Definition at line 361 of file Convert.cpp.
References Err::errAbort(), and toBoolCheck().
Referenced by PgOpt::getValueBool().
bool Convert::toBoolCheck (const std::string & flag, bool * success) [static]
Make an bool from a c string.
Parameters:
flag - c string representation of number to be parsed. allowed value are 'true' && 'false'
success - If success != NULL set to true upon successful conversion and false upon failur.
Returns:
- Bool representation of flag, false on failure.
Definition at line 378 of file Convert.cpp.
Referenced by PgOptions::matchOneArg(), and toBool().
double Convert::toDouble (const std::string & num) [static]
Make an double from a c string.
Parameters:
num - c string representation of number to be parsed.
Returns:
- Double representation of num
Definition at line 284 of file Convert.cpp.
References Err::errAbort(), and toDoubleCheck().
Referenced by SelfDoc::Opt::checkOption(), QuantBRLMM::clusterModelFromStrings(), QuantBRLMM::clusterPriorFromStrings(), PgOpt::getValueDouble(), RowFile::matrixFromFile(), CovariateParams::restoreCovariateParams(), and strToDoubleVec().
double Convert::toDoubleCheck (const std::string & num, bool * success) [static]
Make an double from a c string.
Parameters:
num - c string representation of number to be parsed.
success - If success != NULL set to true upon successful conversion and false upon failur.
Returns:
- Double representation of num
Definition at line 301 of file Convert.cpp.
References Verbose::out().
Referenced by calvinEquiv(), MixedFileCheck::check(), PgOpt::checkParseIsOk(), toDouble(), and toFloatCheck().
float Convert::toFloat (const std::string & num) [static]
Make an float from a c string.
Parameters:
num - c string representation of number to be parsed.
Returns:
- Float representation of num
Definition at line 255 of file Convert.cpp.
References Err::errAbort(), and toFloatCheck().
Referenced by SelfDoc::Opt::checkOption(), RowFile::matrixFromFile(), and TableReader::readFiles().
float Convert::toFloatCheck (const std::string & num, bool * success) [static]
Make an float from a c string.
Parameters:
num - c string representation of number to be parsed.
success - If success != NULL set to true upon successful conversion and false upon failur.
Returns:
- Float representation of num
Definition at line 270 of file Convert.cpp.
References toDoubleCheck().
Referenced by toFloat().
int Convert::toInt (const std::string & num) [static]
Make an int from a c string or die trying.
Parameters:
num - c string representation of number to be parsed.
Returns:
- Integer representation of num
Definition at line 118 of file Convert.cpp.
References Err::errAbort(), and toIntCheck().
Referenced by SelfDoc::Opt::checkOption(), copyRow(), PgOpt::getValueInt(), SocketTextHandler::handleMessage(), SequentialClfFile::isSequential(), keepRow(), ChipLayout::openPgf(), RegressionTest::parseLogFile(), SocketUtil::parseMsgFromBuffer(), RegressionTest::parseValgrindFile(), Probe::Probe(), ChipLayout::readProbeListPgfFileKillList(), readTsvProbesetRow(), CovariateParams::restoreCovariateParams(), and strToIntVec().
int Convert::toIntCheck (const std::string & num, bool * success) [static]
Make an int from a c string.
Parameters:
num - c string representation of number to be parsed.
success - If success != NULL set to true upon successful conversion and false upon failur.
Returns:
- Integer representation of num
Parameters:
num - c string representation of number to be parsed.
success - If success != NULL set to true upon successful conversion and false upon failur.
Returns:
- Integer representation of num, 0 if success == false
Definition at line 133 of file Convert.cpp.
Referenced by PgOpt::checkParseIsOk(), and toInt().
std::string Convert::toString (double d) [static]
Make a string from an double.
Parameters:
d - double to be converted.
Returns:
- String version of int i;
Definition at line 69 of file Convert.cpp.
string Convert::toString (int i) [static]
Make a string from an integer.
Parameters:
i - integer to be converted.
Returns:
- String version of int i;
Definition at line 55 of file Convert.cpp.
Referenced by CovariateParams::determineCovariateMap(), doubleVecToString(), intVecToString(), TableFile::open(), PmSumAdjust::pmAdjustment(), and MmAdjust::pmAdjustment().
unsigned int Convert::toUnsignedInt (const std::string & num) [static]
Make an unsigned int from a c string or die trying.
Make an uint from a c string or die trying.
Parameters:
num - c string representation of number to be parsed.
Returns:
- Unsigned Integer representation of num
Definition at line 168 of file Convert.cpp.
References Err::errAbort(), and toUnsignedIntCheck().
uint64_t Convert::toUnsignedInt64 (const std::string & num) [static]
Make an unsigned int from a c string or die trying.
Parameters:
num - c string representation of number to be parsed.
Returns:
- Unsigned Integer representation of num
Definition at line 176 of file Convert.cpp.
References Err::errAbort(), and toUnsignedInt64Check().
uint64_t Convert::toUnsignedInt64Check (const std::string & num, bool * success) [static]
Make an unsigned int from a c string.
Parameters:
num - c string representation of number to be parsed.
success - If success != NULL set to true upon successful conversion and false upon failur.
Returns:
- Unsigned Integer representation of num, 0 if success == false
Definition at line 220 of file Convert.cpp.
Referenced by toUnsignedInt64().
unsigned int Convert::toUnsignedIntCheck (const std::string & num, bool * success) [static]
Make an unsigned int from a c string.
Parameters:
num - c string representation of number to be parsed.
success - If success != NULL set to true upon successful conversion and false upon failur.
Returns:
- Unsigned Integer representation of num, 0 if success == false
Definition at line 191 of file Convert.cpp.
Referenced by toUnsignedInt().
The documentation for this class was generated from the following files:
util/Convert.h
util/Convert.cpp