Affymetrix Power Tools: affymetrix_calvin_io::CelFileReader Class Reference
affymetrix_calvin_io::CelFileReader Class Reference
#include <CelFileReader.h>
Public Member Functions
CelFileReader ()
~CelFileReader ()
const std::string GetFilename () const
void SetFilename (const std::string &name)
void Read (CelFileData &data)
Protected Attributes
std::string fileName
Detailed Description
This class reads a CEL data file. It is an interpreter class.
Definition at line 44 of file CelFileReader.h.
Constructor & Destructor Documentation
CelFileReader::CelFileReader ()
Constructor
Definition at line 31 of file CelFileReader.cpp.
CelFileReader::~CelFileReader ()
Destructor
Definition at line 38 of file CelFileReader.cpp.
Member Function Documentation
const std::string affymetrix_calvin_io::CelFileReader::GetFilename () const [inline]
Gets the name of the input file.
Returns:
The name of the file to read.
Definition at line 58 of file CelFileReader.h.
References fileName.
void CelFileReader::Read (CelFileData & data)
Reads the file header of the generic file and reads all the DataSetHeader information.
Parameters:
data A reference to a GenericData object that will receive information from the file.
Exceptions:
affymetrix_calvin_exceptions::FileNotFoundException The file does not exist.
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Definition at line 44 of file CelFileReader.cpp.
References affymetrix_calvin_io::CelFileData::Clear(), fileName, affymetrix_calvin_io::CelFileData::GetFilename(), affymetrix_calvin_io::CelFileData::GetGenericData(), affymetrix_calvin_io::GenericFileReader::ReadHeader(), and affymetrix_calvin_io::GenericFileReader::SetFilename().
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::CanReadFile(), affymetrix_cel_converter::CELFileConvertToXDA::ConvertCalvinFile(), affymetrix_cel_converter::CELFileConvertToASCII::ConvertCalvinFile(), affymetrix_chp_converter::CHPFileConvertToCalvin::GetParentGenericDataHeader(), affymetrix_fusion_io::CalvinCELDataAdapter::Read(), and affymetrix_fusion_io::CalvinCELDataAdapter::ReadHeader().
void affymetrix_calvin_io::CelFileReader::SetFilename (const std::string & name) [inline]
Sets the name of the input file.
Parameters:
name The name of the file to read.
Definition at line 64 of file CelFileReader.h.
References fileName.
Referenced by affymetrix_cel_converter::CELFileConvertToXDA::ConvertCalvinFile(), affymetrix_cel_converter::CELFileConvertToASCII::ConvertCalvinFile(), and affymetrix_chp_converter::CHPFileConvertToCalvin::GetParentGenericDataHeader().
Member Data Documentation
std::string affymetrix_calvin_io::CelFileReader::fileName [protected]
Name of the file to read
Definition at line 77 of file CelFileReader.h.
Referenced by GetFilename(), Read(), and SetFilename().
The documentation for this class was generated from the following files:
calvin_files/parsers/src/CelFileReader.h
calvin_files/parsers/src/CelFileReader.cpp