Affymetrix Power Tools: ProbeListStl Class Reference
ProbeListStl Class Reference
If.
#include <ProbeListStl.h>
Public Member Functions
ProbeListStl (const ProbeListStl &pl)
ProbeListStl (const ProbeListPacked &pl)
ProbeListStl (const std::string &name)
ProbeListStl (int block_cnt, int probe_cnt)
ProbeListStl (int block_cnt, int probe_cnt, const std::string &name)
ProbeListStl & operator= (const ProbeListPacked &plp)
Make ourselves a copy of a ProbeListPacked object. ///.
void clear ()
clear the contents of this object.
void resize (int block_cnt, int probe_cnt)
set the size of this probelist ///
void reserve (int block_cnt, int probe_cnt)
reserve space in this probelist ///
int get_type () const
these are the basic accessors, shared with ProbeListPacked /// see ProbeList.h for more info.
void set_type (int type)
int block_cnt () const
int probe_cnt () const
int max_name_len () const
int get_numMatch () const
void set_numMatch (int numMatch)
int get_blockSize (int b) const
void set_blockSize (int b, int val)
short get_blockAnn (int b) const
void set_blockAnn (int b, short val)
int get_blockAllele (int b) const
void set_blockAllele (int b, int val)
int get_blockContext (int b) const
void set_blockContext (int b, int val)
int get_blockChannel (int b) const
void set_blockChannel (int b, char val)
int get_blockRepType (int b) const
void set_blockRepType (int b, char val)
int get_probeId (int b) const
void set_probeId (int b, int val)
int8_t get_probeGc (int d) const
void set_probeGc (int d, int8_t val)
int get_probeApid (int d) const
void set_probeApid (int d, int val)
void set_name (const std::string &name)
const char * get_name () const
const char * get_name_cstr () const
std::string get_name_string () const
void push_block (const ProbeListStlBlock &b)
///
void push_block (const ProbeListStlBlock *b)
void push_block (int bAnn, int bAllele, int bContext, int bChannel, int bRepType=0)
///
void push_probe (const ProbeListStlProbe &p)
push a probe onto the end of a probelist ///
void push_probe (int id)
push a probe with just an id ///
void push_probe (int id, int det, int apid)
create and push a probe with these three values. ///
void push_probelist (const ProbeListStl &pl)
push an entire probelist onto this one. ///
const ProbeListStlBlock * getBlockPtr (int b)
Get a pointer to the block B ///.
int findBlockMatch (int qAllele, int qContext, int qChannel) const
Find the index of the block with matchin ACC /.
bool hasDuplicateBlocks () const
Return true if two or more blocks have matching ACCs ///.
void dump () const
For debuggging...
Public Attributes
std::string m_name
the name of this probelist
int m_max_name_len
the longest name which could be stored.
int m_type
type
int m_num_match
number of matching probes
std::vector< ProbeListStlBlock > m_block_vec
collection of blocks in this ProbeList
std::vector< ProbeListStlProbe > m_probe_vec
collection of probes in this ProbeList
Detailed Description
If.
Definition at line 136 of file ProbeListStl.h.
Member Function Documentation
int ProbeListStl::findBlockMatch (int qAllele, int qContext, int qChannel) const
Find the index of the block with matchin ACC /.
Parameters:
qAllele ///
qContext ///
qChannel ///
Returns:
the index or -1
Definition at line 407 of file ProbeListStl.cpp.
Referenced by hasDuplicateBlocks().
int ProbeListStl::get_type () const
these are the basic accessors, shared with ProbeListPacked /// see ProbeList.h for more info.
These are just like ProbeListPacked.
Definition at line 235 of file ProbeListStl.cpp.
References m_type.
const ProbeListStlBlock * ProbeListStl::getBlockPtr (int b)
Get a pointer to the block B ///.
Parameters:
b ///
Returns:
the pointer or NULL
Definition at line 398 of file ProbeListStl.cpp.
References m_block_vec.
bool ProbeListStl::hasDuplicateBlocks () const
Return true if two or more blocks have matching ACCs ///.
Returns:
Definition at line 419 of file ProbeListStl.cpp.
References findBlockMatch().
ProbeListStl & ProbeListStl::operator= (const ProbeListPacked & plp)
Make ourselves a copy of a ProbeListPacked object. ///.
Parameters:
plp ///
Returns:
Definition at line 175 of file ProbeListStl.cpp.
References APT_ERR_ASSERT, clear(), ProbeListPacked::get_blockSize(), push_block(), push_probe(), reserve(), and set_numMatch().
void ProbeListStl::push_block (const ProbeListStlBlock & b)
///
Parameters:
b
Definition at line 346 of file ProbeListStl.cpp.
References m_block_vec.
Referenced by operator=().
void ProbeListStl::push_block (int bAnn, int bAllele, int bContext, int bChannel, int bRepType = 0)
///
Parameters:
bAnn ///
bAllele ///
bContext ///
bChannel ///
bRepType
Definition at line 355 of file ProbeListStl.cpp.
References m_block_vec.
void ProbeListStl::push_probe (const ProbeListStlProbe & p)
push a probe onto the end of a probelist ///
Parameters:
p probelist probe to push
Todo:
blocks should contain probes. /// we need the pls ref as we need it to get the probes. ///
Definition at line 374 of file ProbeListStl.cpp.
References m_probe_vec.
Referenced by operator=().
void ProbeListStl::push_probe (int id, int det, int apid)
create and push a probe with these three values. ///
Parameters:
id ///
det ///
apid
Definition at line 382 of file ProbeListStl.cpp.
References m_probe_vec.
void ProbeListStl::push_probe (int id)
push a probe with just an id ///
Parameters:
id id of the probe.
Definition at line 378 of file ProbeListStl.cpp.
References m_probe_vec.
void ProbeListStl::push_probelist (const ProbeListStl & pl)
push an entire probelist onto this one. ///
Parameters:
pl
Definition at line 388 of file ProbeListStl.cpp.
References m_block_vec, and m_probe_vec.
Referenced by apt_falcon_merge_plf2plf_nonas().
void ProbeListStl::reserve (int block_cnt, int probe_cnt)
reserve space in this probelist ///
Parameters:
block_cnt ///
probe_cnt
Definition at line 219 of file ProbeListStl.cpp.
References m_block_vec, and m_probe_vec.
Referenced by operator=().
void ProbeListStl::resize (int block_cnt, int probe_cnt)
set the size of this probelist ///
Parameters:
block_cnt ///
probe_cnt
Definition at line 215 of file ProbeListStl.cpp.
References m_block_vec, and m_probe_vec.
void ProbeListStl::set_numMatch (int numMatch)
Todo:
this is for debugging. Maybe we could have 0 matches.
Definition at line 254 of file ProbeListStl.cpp.
References APT_ERR_ASSERT, and m_num_match.
Referenced by apt_falcon_merge_plf2plf_nonas(), and operator=().
The documentation for this class was generated from the following files:
chipstream/ProbeListStl.h
chipstream/ProbeListStl.cpp