Affymetrix Power Tools: affymetrix_calvin_io::GenericFileReader Class Reference
affymetrix_calvin_io::GenericFileReader Class Reference
#include <GenericFileReader.h>
Public Types
enum OpenHint { All, Sequential, None }
enum ReadHeaderOption { ReadAllHeaders, ReadMinDataGroupHeader, ReadNoDataGroupHeader }
Public Member Functions
GenericFileReader ()
~GenericFileReader ()
const std::string GetFilename () const
void SetFilename (const std::string &name)
void ReadHeader (GenericData &data, ReadHeaderOption option=ReadAllHeaders)
void Open (GenericData &data, OpenHint hint=All)
u_int32_t GetDataGroupCnt () const
DataGroupReader GetDataGroupReader (int32_t index)
DataGroupReader GetDataGroupReader (const std::wstring &name)
void Close ()
Protected Member Functions
void OpenFile ()
void ReadFileHeaderMinDP (GenericData &data)
void ReadFileHeader (GenericData &data)
void ReadFileHeaderNoDataGroupHeader (GenericData &data)
void CloseFile ()
Protected Attributes
std::string fileName
std::ifstream fileStream
GenericData * gendata
Detailed Description
This class reads a generic data file. It is the top-level generic data file reader.
Definition at line 45 of file GenericFileReader.h.
Member Enumeration Documentation
enum affymetrix_calvin_io::GenericFileReader::OpenHint
Hint used when opening a file
Definition at line 55 of file GenericFileReader.h.
enum affymetrix_calvin_io::GenericFileReader::ReadHeaderOption
Indicates how much header information to read
Definition at line 58 of file GenericFileReader.h.
Constructor & Destructor Documentation
GenericFileReader::GenericFileReader ()
Constructor
Definition at line 40 of file GenericFileReader.cpp.
References gendata.
GenericFileReader::~GenericFileReader ()
Destructor
Definition at line 48 of file GenericFileReader.cpp.
References CloseFile().
Member Function Documentation
void GenericFileReader::Close (void)
Gets the DataGroupReader based on the file position of the DataGroup.
Parameters:
index Data dataGroup file position.
Returns:
A DataGroupReader to use to read the data.
Closes the file.
Definition at line 212 of file GenericFileReader.cpp.
References CloseFile().
Referenced by affymetrix_calvin_io::DataSetUpdater::Initialize(), and affymetrix_calvin_io::DATFileReader::Read().
void GenericFileReader::CloseFile () [protected]
Closes the file
Definition at line 90 of file GenericFileReader.cpp.
References fileStream, and gendata.
Referenced by Close(), ReadHeader(), and ~GenericFileReader().
u_int32_t GenericFileReader::GetDataGroupCnt () const
Gets the number of DataGroups in the file.
Returns:
The number of DataGroups in the file.
Definition at line 161 of file GenericFileReader.cpp.
References affymetrix_calvin_io::GenericData::DataGroupCnt(), and gendata.
DataGroupReader GenericFileReader::GetDataGroupReader (int32_t index)
Gets DataGroupReader by index. OpenHint should be All or sequential.
Parameters:
index Data dataGroup index. If opened for sequential access the index should be an increment of one from call to call.
Returns:
A DataGroupReader to use to read the data.
Exceptions:
DataGroupNotFoundException
Definition at line 171 of file GenericFileReader.cpp.
References fileStream, affymetrix_calvin_io::GenericData::FindDataGroupHeader(), gendata, and affymetrix_calvin_utilities::DateTime::GetCurrentDateTime().
Referenced by affymetrix_calvin_io::DATFileReader::Read().
DataGroupReader GenericFileReader::GetDataGroupReader (const std::wstring & name)
Gets the DataGroupReader by name. OpenHint must be All.
Parameters:
name Data dataGroup name.
Returns:
A DataGroupReader to use to read the data.
Exceptions:
DataGroupNotFoundException
Definition at line 192 of file GenericFileReader.cpp.
References fileStream, affymetrix_calvin_io::GenericData::FindDataGroupHeader(), gendata, and affymetrix_calvin_utilities::DateTime::GetCurrentDateTime().
const std::string affymetrix_calvin_io::GenericFileReader::GetFilename () const [inline]
Gets the name of the input file.
Returns:
The name of the input file.
Definition at line 65 of file GenericFileReader.h.
References fileName.
void GenericFileReader::Open (GenericData & data, OpenHint hint = All)
Open the file for reading
Parameters:
data A reference to a GenericData object that will receive header information from the file. Amount of info depends on the hint.
hint A hint on how to open the file.
Exceptions:
affymetrix_calvin_exceptions::FileNotFoundException The file does not exist.
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Definition at line 143 of file GenericFileReader.cpp.
References gendata, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), OpenFile(), and ReadFileHeader().
Referenced by CNFamilialReporterFamilial::addParentHeaders(), affymetrix_calvin_io::DataSetUpdater::Initialize(), Calvin::load(), affymetrix_calvin_io::DATFileReader::Read(), and CNCychp::readFile().
void GenericFileReader::OpenFile () [protected]
Opens the file for reading
Definition at line 78 of file GenericFileReader.cpp.
References fileName, fileStream, and affymetrix_calvin_utilities::DateTime::GetCurrentDateTime().
Referenced by Open(), and ReadHeader().
void GenericFileReader::ReadFileHeader (affymetrix_calvin_io::GenericData & data) [protected]
Reads the file header of the generic file and reads all the DataSetHeader information.
Parameters:
data Reference to the GenericData object to fill.
Definition at line 116 of file GenericFileReader.cpp.
References fileName, fileStream, affymetrix_calvin_io::FileHeader::GetDataGroupCnt(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::DataGroupHeaderReader::ReadAll(), and affymetrix_calvin_io::FileHeader::SetFilename().
Referenced by Open(), and ReadHeader().
void GenericFileReader::ReadFileHeaderMinDP (affymetrix_calvin_io::GenericData & data) [protected]
Read the file header and minimize amount of information read from the DataSetHeaders. It does not attempt to read the complete DataSetHeader. That is deferred until accessed by the DataSet object.
Parameters:
data Reference to the GenericData object to fill.
Definition at line 100 of file GenericFileReader.cpp.
References fileName, fileStream, affymetrix_calvin_io::FileHeader::GetDataGroupCnt(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::DataGroupHeaderReader::ReadAllMinimumInfo(), and affymetrix_calvin_io::FileHeader::SetFilename().
Referenced by ReadHeader().
void GenericFileReader::ReadFileHeaderNoDataGroupHeader (GenericData & data) [protected]
Reads the file header of the generic file but does not read any DataGroupHeaders or DataSetHeaders.
Parameters:
data Reference to the GenericData object to fill.
Definition at line 131 of file GenericFileReader.cpp.
References fileName, fileStream, affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_io::FileHeader::SetFilename().
Referenced by ReadHeader().
void GenericFileReader::ReadHeader (affymetrix_calvin_io::GenericData & data, ReadHeaderOption option = ReadAllHeaders)
Read the file header of the generic file.
Parameters:
data A reference to a GenericData object that will receive header information from the file.
option Indicates how much DataGroupHeader and DataSetHeader information to read.
Exceptions:
affymetrix_calvin_exceptions::FileNotFoundException The file does not exist.
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Definition at line 56 of file GenericFileReader.cpp.
References CloseFile(), OpenFile(), ReadFileHeader(), ReadFileHeaderMinDP(), and ReadFileHeaderNoDataGroupHeader().
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), QuantMethodMultiDataCCCHPReport::finish(), QuantMethodExprCCCHPReport::finish(), affymetrix_fusion_io::FusionCDFData::IsCalvinCompatibleFile(), affymetrix_calvin_io::GridControlFileReader::Read(), affymetrix_calvin_io::CHPTilingFileReader::Read(), affymetrix_calvin_io::CHPQuantificationFileReader::Read(), affymetrix_calvin_io::CHPQuantificationDetectionFileReader::Read(), affymetrix_calvin_io::CHPMultiDataFileReader::Read(), affymetrix_calvin_io::CHPFileReader::Read(), affymetrix_calvin_io::CelFileReader::Read(), and affymetrix_calvin_io::CDFFileReader::Read().
void affymetrix_calvin_io::GenericFileReader::SetFilename (const std::string & name) [inline]
Sets the name of the input file.
Parameters:
name The name of the input file.
Definition at line 71 of file GenericFileReader.h.
References fileName.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), CNFamilialReporterFamilial::addParentHeaders(), QuantMethodMultiDataCCCHPReport::finish(), QuantMethodExprCCCHPReport::finish(), affymetrix_calvin_io::DataSetUpdater::Initialize(), affymetrix_fusion_io::FusionCDFData::IsCalvinCompatibleFile(), Calvin::load(), affymetrix_calvin_io::GridControlFileReader::Read(), affymetrix_calvin_io::DATFileReader::Read(), affymetrix_calvin_io::CHPTilingFileReader::Read(), affymetrix_calvin_io::CHPQuantificationFileReader::Read(), affymetrix_calvin_io::CHPQuantificationDetectionFileReader::Read(), affymetrix_calvin_io::CHPMultiDataFileReader::Read(), affymetrix_calvin_io::CHPFileReader::Read(), affymetrix_calvin_io::CelFileReader::Read(), affymetrix_calvin_io::CDFFileReader::Read(), and CNCychp::readFile().
Member Data Documentation
std::string affymetrix_calvin_io::GenericFileReader::fileName [protected]
The name of the input file.
Definition at line 147 of file GenericFileReader.h.
Referenced by GetFilename(), OpenFile(), ReadFileHeader(), ReadFileHeaderMinDP(), ReadFileHeaderNoDataGroupHeader(), and SetFilename().
std::ifstream affymetrix_calvin_io::GenericFileReader::fileStream [protected]
The file stream.
Definition at line 150 of file GenericFileReader.h.
Referenced by CloseFile(), GetDataGroupReader(), OpenFile(), ReadFileHeader(), ReadFileHeaderMinDP(), and ReadFileHeaderNoDataGroupHeader().
GenericData* affymetrix_calvin_io::GenericFileReader::gendata [protected]
A pointer to the GenericData object
Definition at line 153 of file GenericFileReader.h.
Referenced by CloseFile(), GenericFileReader(), GetDataGroupCnt(), GetDataGroupReader(), and Open().
The documentation for this class was generated from the following files:
calvin_files/parsers/src/GenericFileReader.h
calvin_files/parsers/src/GenericFileReader.cpp