Affymetrix Power Tools: MetaProbeset Class Reference
MetaProbeset Class Reference
Very basic class to store the meta probesets (groups of probesets) that a user specifies for analysis.
#include <MetaProbeset.h>
Static Public Member Functions
static void readProbesetSubset (affx::TsvFile &tsv, std::vector< MetaProbeset * > &metaSets)
Read in a subset of probes to be processed.
static void readMetaProbesetList (affx::TsvFile &tsv, std::vector< MetaProbeset * > &metaSets)
Read in a grouping file for probesets which merges probesets into larger probesets called "meta" probesets.
static void readMetaProbesets (const std::string fileName, const bool metaFile, std::vector< MetaProbeset * > &metaSets)
Open a file that could be either a meta probesets file or a subset list of probesets and fill in the metaSets vector appropriately.
Public Attributes
const char * name
const char * displayName
FrugalVector< const char * > probesets
bool freeSubs
Detailed Description
Very basic class to store the meta probesets (groups of probesets) that a user specifies for analysis.
Definition at line 33 of file MetaProbeset.h.
Member Function Documentation
void MetaProbeset::readMetaProbesetList (affx::TsvFile & tsv, std::vector< MetaProbeset * > & metaSets) [static]
Read in a grouping file for probesets which merges probesets into larger probesets called "meta" probesets.
Requires at least two columns of data, a probeset_id for the newly created probeset and a probeset_list which contains a space separated list of probesets to merge.
Parameters:
tsv - File to read meta probesets from.
metaSets - Meta probesets to fill in from file.
Definition at line 68 of file MetaProbeset.cpp.
References Util::chopString(), Util::cloneString(), affx::TsvFile::cname2cidx(), Err::errAbort(), affx::TsvFile::getFileName(), affx::TsvFile::lineNumber(), affx::TsvFile::nextLevel(), ToStr(), and affx::TSV_BIND_REQUIRED.
Referenced by readMetaProbesets().
void MetaProbeset::readMetaProbesets (const std::string fileName, const bool metaFile, std::vector< MetaProbeset * > & metaSets) [static]
Open a file that could be either a meta probesets file or a subset list of probesets and fill in the metaSets vector appropriately.
Parameters:
o - Options
metaSets - Vector to be filled in with resulting probests or meta probests.
Definition at line 109 of file MetaProbeset.cpp.
References affx::TsvFile::close(), affx::TsvFile::cname2cidx(), Err::errAbort(), affx::TsvFile::open(), Verbose::out(), readMetaProbesetList(), readProbesetSubset(), and ToStr().
void MetaProbeset::readProbesetSubset (affx::TsvFile & tsv, std::vector< MetaProbeset * > & metaSets) [static]
Read in a subset of probes to be processed.
Can be probeset ids or names depending on the options.
Parameters:
tsv - File to read from.
metaSets - Meta probeset vector to fill in.
Definition at line 51 of file MetaProbeset.cpp.
References Util::cloneString(), Err::errAbort(), affx::TsvFile::getFileName(), affx::TsvFile::nextLevel(), and affx::TSV_BIND_REQUIRED.
Referenced by readMetaProbesets().
The documentation for this class was generated from the following files:
chipstream/MetaProbeset.h
chipstream/MetaProbeset.cpp