Affymetrix Power Tools: affymetrix_cel_converter::CELFileConverter Class Reference
affymetrix_cel_converter::CELFileConverter Class Reference
#include <CELFileConverter.h>
Public Member Functions
CELFileConverter ()
~CELFileConverter ()
CELFileConverterErrorCode ErrorCode () const
bool ConvertFile (const char *fileName, CELFileVersionType fileVersion, CELFileConversionOptions *options=NULL)
bool ConvertFile (const char *fileName, const char *newFileName, CELFileVersionType fileVersion, CELFileConversionOptions *options=NULL)
Detailed Description
This class will convert a CEL file between GCOS and Calvin formats.
Definition at line 38 of file CELFileConverter.h.
Constructor & Destructor Documentation
CELFileConverter::CELFileConverter ()
Constructor
Definition at line 40 of file CELFileConverter.cpp.
CELFileConverter::~CELFileConverter ()
Destructor
Definition at line 56 of file CELFileConverter.cpp.
Member Function Documentation
bool CELFileConverter::ConvertFile (const char * fileName, CELFileVersionType fileVersion, CELFileConversionOptions * options = NULL)
Convert the file to the specified format.
Parameters:
fileName The full path name of the CEL file.
fileVersion The file version to convert to.
Returns:
True if successful.
Definition at line 91 of file CELFileConverter.cpp.
References affymetrix_cel_converter::CELFileVersion::DetermineCELFileVersion().
bool CELFileConverter::ConvertFile (const char * fileName, const char * newFileName, CELFileVersionType fileVersion, CELFileConversionOptions * options = NULL)
Convert the file to the specified format.
Parameters:
fileName The full path name of the input CEL file.
newFileName The full path name of the new CEL file to be written.
fileVersion The file version to convert to.
Returns:
True if successful.
Definition at line 132 of file CELFileConverter.cpp.
References affymetrix_cel_converter::Calvin_Version1, affymetrix_cel_converter::CELFileConvertToCalvin::ConvertASCIIFile(), affymetrix_cel_converter::CELFileConvertToXDA::ConvertASCIIFile(), affymetrix_cel_converter::CELFileConvertToXDA::ConvertCalvinFile(), affymetrix_cel_converter::CELFileConvertToASCII::ConvertCalvinFile(), affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile(), affymetrix_cel_converter::CELFileConvertToASCII::ConvertXDAFile(), affymetrix_cel_converter::CELFileVersion::DetermineCELFileVersion(), affymetrix_cel_converter::CELFileConvertToCalvin::ErrorCode(), affymetrix_cel_converter::CELFileConvertToXDA::ErrorCode(), affymetrix_cel_converter::CELFileConvertToASCII::ErrorCode(), affymetrix_cel_converter::GCOS_Version3, and affymetrix_cel_converter::GCOS_Version4.
CELFileConverterErrorCode affymetrix_cel_converter::CELFileConverter::ErrorCode () const [inline]
Gets the error code for the conversion process.
Returns:
The error code associated with the last failure.
Definition at line 51 of file CELFileConverter.h.
The documentation for this class was generated from the following files:
calvin_files/converters/cel/src/CELFileConverter.h
calvin_files/converters/cel/src/CELFileConverter.cpp