Affymetrix Power Tools: SpfReader Class Reference
SpfReader Class Reference
Class for parsing the Simple Probe Format (SPF) text files.
#include <SpfReader.h>
Public Member Functions
void openSpf (const std::string &fileName)
Open a text file for reading.
~SpfReader ()
Destructor to cleanup open files.
ProbeSet * readNextProbeSet ()
Read the next record.
bool isFileOpen ()
int getNumProbeSets ()
Detailed Description
Class for parsing the Simple Probe Format (SPF) text files.
Reads one record at a time to ease memory requirements
Definition at line 45 of file SpfReader.h.
Constructor & Destructor Documentation
SpfReader::~SpfReader () [inline]
Destructor to cleanup open files.
Definition at line 53 of file SpfReader.h.
References affx::TsvFile::close().
Member Function Documentation
void SpfReader::openSpf (const std::string & fileName)
Open a text file for reading.
Definition at line 173 of file SpfReader.cpp.
References Err::errAbort(), affx::TsvFile::open(), ToStr(), and affx::TSV_BIND_REQUIRED.
ProbeSet * SpfReader::readNextProbeSet ()
Read the next record.
Returned probeset must be deleted by caller
Definition at line 164 of file SpfReader.cpp.
References affx::TsvFile::lineNumber(), and affx::TsvFile::nextLevel().
The documentation for this class was generated from the following files:
chipstream/SpfReader.h
chipstream/SpfReader.cpp