Affymetrix Power Tools: AnnotationTable Class Reference
AnnotationTable Class Reference
Public Member Functions
AnnotationTable (sqlite3 *AnnotationDb, Configuration *ConfigPtr, LocalizationTable *LocalizationTablePtr, ChromosomeTable *ChromosomeTablePtr)
void LoadColumntTypes ()
bool InsertTsvFiles (std::vector< std::string > ListOfTsvFiles)
void AnalyzeFiles (std::vector< std::string > ListOfTsvFiles)
void ReportNumberOfRecordsToInsertUpdate (int TotalLinesCount)
void ReportRequiredColumns ()
void CheckIfNeedToAddColumn (string CsvColumnName)
void CheckIfNeedToAddColumn (string DbColumnName, string ColumnType)
void AddColumns ()
Static Public Attributes
static map< string, string > m_columnNameToColumnTypeMap
Detailed Description
Definition at line 42 of file AnnotationTable.h.
Member Function Documentation
void AnnotationTable::AnalyzeFiles (std::vector< std::string > ListOfTsvFiles)
Analyze required columns
Analyze ProbeSet Uniqueness
Definition at line 294 of file AnnotationTable.cpp.
References Fs::basename(), affx::TsvFile::close(), affx::dequote(), Fs::fileSize(), affx::TsvFile::get(), affx::TsvFile::gotoLine(), affx::TsvFile::line_fpos(), affx::TsvFile::lineNum(), affx::TsvFile::lineNumber(), affx::TsvFile::nextLine(), and affx::TsvFile::open().
The documentation for this class was generated from the following files:
dbtools/apt-annotation-converter/AnnotationTable.h
dbtools/apt-annotation-converter/AnnotationTable.cpp