Affymetrix Power Tools: affymetrix_fusion_io::FusionResequencingResults Class Reference
affymetrix_fusion_io::FusionResequencingResults Class Reference
Resequencing results.
#include <FusionProbeSetResults.h>
Public Member Functions
FusionResequencingResults ()
~FusionResequencingResults ()
void Clear ()
const Int8Vector & GetCalledBases ()
Gets the called bases.
int8_t GetCalledBase (int index)
Gets the called base at the given index.
int32_t GetCalledBasesSize () const
Gets the size of the called bases array.
void ResizeCalledBases (int32_t size)
Resizes the called bases array.
void SetCalledBase (int32_t index, int8_t call)
Sets the called base.
void AddCalledBase (int8_t call)
Adds the called base to the end of the list.
const FloatVector & GetScores ()
Gets the scores.
float GetScore (int32_t index)
Gets the score at the given index.
int32_t GetScoresSize () const
Gets the size of the scores array.
void ResizeScores (int32_t size)
Resizes the scores array.
void SetScore (int index, float score)
Sets the score.
void AddScore (float score)
Adds the score to the end of the list.
const FusionForceCallVector & GetForceCalls ()
Gets the force calls.
FusionForceCallType GetForceCall (int32_t index)
Gets the force call at the given index.
int32_t GetForceCallsSize () const
Gets the size of the force calls array.
void ResizeForceCalls (int32_t size)
Resizes the force calls array.
void SetForceCall (int32_t index, FusionForceCallType call)
Sets the force call.
void AddForceCall (FusionForceCallType call)
Adds the force call to the end of the list.
const FusionBaseCallVector & GetOrigCalls ()
Gets the original called bases.
FusionBaseCallType GetOrigCall (int32_t index)
Gets the original called base at the given index.
int32_t GetOrigCallsSize () const
Gets the size of the original calls array.
void ResizeOrigCalls (int32_t size)
Resizes the original calls array.
void SetOrigCall (int32_t index, FusionBaseCallType call)
Sets the original call.
void AddOrigCall (FusionBaseCallType call)
Adds the original call to the end of the list.
Detailed Description
Resequencing results.
Definition at line 520 of file FusionProbeSetResults.h.
Constructor & Destructor Documentation
FusionResequencingResults::FusionResequencingResults ()
Constructor
Definition at line 466 of file FusionProbeSetResults.cpp.
References Clear().
FusionResequencingResults::~FusionResequencingResults ()
Destructor
Definition at line 471 of file FusionProbeSetResults.cpp.
References Clear().
Member Function Documentation
void FusionResequencingResults::AddCalledBase (int8_t call)
Adds the called base to the end of the list.
Parameters:
call Call.
Definition at line 510 of file FusionProbeSetResults.cpp.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults().
void FusionResequencingResults::AddForceCall (FusionForceCallType call)
Adds the force call to the end of the list.
Parameters:
call Force call.
Definition at line 570 of file FusionProbeSetResults.cpp.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults().
void FusionResequencingResults::AddOrigCall (FusionBaseCallType call)
Adds the original call to the end of the list.
Parameters:
call Original call.
Definition at line 600 of file FusionProbeSetResults.cpp.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults().
void FusionResequencingResults::AddScore (float score)
Adds the score to the end of the list.
Parameters:
score Score.
Definition at line 540 of file FusionProbeSetResults.cpp.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults().
void FusionResequencingResults::Clear (void)
Clears the members.
Definition at line 476 of file FusionProbeSetResults.cpp.
Referenced by FusionResequencingResults(), and ~FusionResequencingResults().
int8_t FusionResequencingResults::GetCalledBase (int index)
Gets the called base at the given index.
Parameters:
index Index to the called bases array.
Returns:
Called base.
Definition at line 489 of file FusionProbeSetResults.cpp.
const Int8Vector & FusionResequencingResults::GetCalledBases ()
Gets the called bases.
Returns:
Array of called bases.
Definition at line 484 of file FusionProbeSetResults.cpp.
int32_t FusionResequencingResults::GetCalledBasesSize () const
Gets the size of the called bases array.
Returns:
Size of the called bases array.
Definition at line 494 of file FusionProbeSetResults.cpp.
FusionForceCallType FusionResequencingResults::GetForceCall (int32_t index)
Gets the force call at the given index.
Parameters:
index Index to the force calls array.
Returns:
Force call.
Definition at line 550 of file FusionProbeSetResults.cpp.
const FusionForceCallVector & FusionResequencingResults::GetForceCalls ()
Gets the force calls.
Returns:
Array of force calls.
Definition at line 545 of file FusionProbeSetResults.cpp.
int32_t FusionResequencingResults::GetForceCallsSize () const
Gets the size of the force calls array.
Returns:
Size of the force calls array.
Definition at line 555 of file FusionProbeSetResults.cpp.
FusionBaseCallType FusionResequencingResults::GetOrigCall (int32_t index)
Gets the original called base at the given index.
Parameters:
index Index to the original calls array.
Returns:
Original call.
Definition at line 580 of file FusionProbeSetResults.cpp.
const FusionBaseCallVector & FusionResequencingResults::GetOrigCalls ()
Gets the original called bases.
Returns:
Array of original calls.
Definition at line 575 of file FusionProbeSetResults.cpp.
int32_t FusionResequencingResults::GetOrigCallsSize () const
Gets the size of the original calls array.
Returns:
Size of the original calls array.
Definition at line 585 of file FusionProbeSetResults.cpp.
float FusionResequencingResults::GetScore (int32_t index)
Gets the score at the given index.
Parameters:
index Index to the scores array.
Returns:
Score.
Definition at line 520 of file FusionProbeSetResults.cpp.
const FloatVector & FusionResequencingResults::GetScores ()
Gets the scores.
Returns:
Array of scores.
Definition at line 515 of file FusionProbeSetResults.cpp.
int32_t FusionResequencingResults::GetScoresSize () const
Gets the size of the scores array.
Returns:
Size of the scores array.
Definition at line 525 of file FusionProbeSetResults.cpp.
void FusionResequencingResults::ResizeCalledBases (int32_t size)
Resizes the called bases array.
Parameters:
size Size of the array.
Definition at line 500 of file FusionProbeSetResults.cpp.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
void FusionResequencingResults::ResizeForceCalls (int32_t size)
Resizes the force calls array.
Parameters:
size Size of the array.
Definition at line 560 of file FusionProbeSetResults.cpp.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
void FusionResequencingResults::ResizeOrigCalls (int32_t size)
Resizes the original calls array.
Parameters:
size Size of the array.
Definition at line 590 of file FusionProbeSetResults.cpp.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
void FusionResequencingResults::ResizeScores (int32_t size)
Resizes the scores array.
Parameters:
size Size of the array.
Definition at line 530 of file FusionProbeSetResults.cpp.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
void FusionResequencingResults::SetCalledBase (int32_t index, int8_t call)
Sets the called base.
Parameters:
index Index to the array.
call Call.
Definition at line 505 of file FusionProbeSetResults.cpp.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
void FusionResequencingResults::SetForceCall (int32_t index, FusionForceCallType call)
Sets the force call.
Parameters:
index Index to the array.
call Force call.
Definition at line 565 of file FusionProbeSetResults.cpp.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
void FusionResequencingResults::SetOrigCall (int32_t index, FusionBaseCallType call)
Sets the original call.
Parameters:
index Index to the array.
call Original call.
Definition at line 595 of file FusionProbeSetResults.cpp.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
void FusionResequencingResults::SetScore (int index, float score)
Sets the score.
Parameters:
index Index to the array.
score Score.
Definition at line 535 of file FusionProbeSetResults.cpp.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
The documentation for this class was generated from the following files:
calvin_files/fusion/src/FusionProbeSetResults.h
calvin_files/fusion/src/FusionProbeSetResults.cpp