Affymetrix Power Tools: PmOnlyAdjust Class Reference
PmOnlyAdjust Class Reference
Pm adjustment class that does no modification.
#include <PmOnlyAdjust.h>