Affymetrix Power Tools: affymetrix_calvin_array::ArrayData Class Reference
affymetrix_calvin_array::ArrayData Class Reference
#include <ArrayData.h>
Public Member Functions
ArrayData ()
~ArrayData ()
affymetrix_calvin_utilities::AffymetrixGuidType & ArraySetFileIdentifier ()
affymetrix_calvin_utilities::AffymetrixGuidType & DataTypeIdentifier ()
CreateStep & CreatedStep ()
std::wstring & InitialProject ()
std::wstring & CreationDateTime ()
std::wstring & CreatedBy ()
ArrayAttributesVector & PhysicalArraysAttributes ()
affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredTypeList & UserAttributes ()
void Clear ()
Protected Attributes
affymetrix_calvin_utilities::AffymetrixGuidType fileId
affymetrix_calvin_utilities::AffymetrixGuidType dataTypeId
CreateStep createdStep
std::wstring initialProject
std::wstring creationDateTime
std::wstring createdBy
ArrayAttributesVector physicalArraysAttributes
affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredTypeList userAttributes
Detailed Description
This class provides interfaces to store array information.
Definition at line 42 of file ArrayData.h.
Constructor & Destructor Documentation
ArrayData::ArrayData ()
Constructor
Definition at line 29 of file ArrayData.cpp.
ArrayData::~ArrayData ()
Destructor
Definition at line 36 of file ArrayData.cpp.
References Clear().
Member Function Documentation
affymetrix_calvin_utilities::AffymetrixGuidType& affymetrix_calvin_array::ArrayData::ArraySetFileIdentifier () [inline]
The unique idendifier for the array set.
Returns:
The unique idendifier for the array set.
Definition at line 81 of file ArrayData.h.
References fileId.
Referenced by FusionArrayFileReaderTest::testmethod_Read_calvin_array_file(), FusionArrayFileReaderTest::testmethod_Read_dtt_array_file(), FusionArrayFileReaderTest::testmethod_Read_invalid_file(), FusionArrayFileReaderTest::testmethod_Read_mas_array_file(), and FusionArrayFileReaderTest::testmethod_Read_missing_file().
void ArrayData::Clear ()
Clears the member objects.
Definition at line 44 of file ArrayData.cpp.
References createdBy, createdStep, creationDateTime, dataTypeId, fileId, initialProject, physicalArraysAttributes, and userAttributes.
Referenced by affymetrix_calvin_io::ArrayFileReader::Read(), affymetrix_fusion_io::FusionArrayFileReader::Read(), and ~ArrayData().
std::wstring& affymetrix_calvin_array::ArrayData::CreatedBy () [inline]
The user who created the data object.
Returns:
The user name.
Definition at line 106 of file ArrayData.h.
References createdBy.
Referenced by FusionArrayFileReaderTest::testmethod_Read_calvin_array_file().
CreateStep& affymetrix_calvin_array::ArrayData::CreatedStep () [inline]
The step in Calvin that created the array set data.
Returns:
The step in calvin that create the array set data.
Definition at line 91 of file ArrayData.h.
References createdStep.
Referenced by FusionArrayFileReaderTest::testmethod_Read_calvin_array_file().
std::wstring& affymetrix_calvin_array::ArrayData::CreationDateTime () [inline]
The date and time of initial creation.
Returns:
The creation date and time.
Definition at line 101 of file ArrayData.h.
References creationDateTime.
Referenced by FusionArrayFileReaderTest::testmethod_Read_calvin_array_file().
affymetrix_calvin_utilities::AffymetrixGuidType& affymetrix_calvin_array::ArrayData::DataTypeIdentifier () [inline]
The identifier of the type of data stored in the file.
Returns:
The identifier of the type of data.
Definition at line 86 of file ArrayData.h.
References dataTypeId.
Referenced by affymetrix_calvin_io::ArrayFileReader::DataTypeIdentifier(), FusionArrayFileReaderTest::testmethod_Read_calvin_array_file(), FusionArrayFileReaderTest::testmethod_Read_invalid_file(), and FusionArrayFileReaderTest::testmethod_Read_missing_file().
std::wstring& affymetrix_calvin_array::ArrayData::InitialProject () [inline]
The name of the project that initially created the array set data.
Returns:
The project name.
Definition at line 96 of file ArrayData.h.
References initialProject.
Referenced by FusionArrayFileReaderTest::testmethod_Read_calvin_array_file().
ArrayAttributesVector& affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes () [inline]
The arrays attributes. Each array in a set will have its own attributes.
Returns:
The vector of arrays attributes.
Definition at line 111 of file ArrayData.h.
References physicalArraysAttributes.
Referenced by affymetrix_calvin_io::SAXArrayHandlers::characters(), affymetrix_fusion_io::FusionArrayFileReader::Read(), FusionArrayFileReaderTest::testmethod_Read_calvin_array_file(), FusionArrayFileReaderTest::testmethod_Read_dtt_array_file(), FusionArrayFileReaderTest::testmethod_Read_invalid_file(), FusionArrayFileReaderTest::testmethod_Read_mas_array_file(), and FusionArrayFileReaderTest::testmethod_Read_missing_file().
affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredTypeList& affymetrix_calvin_array::ArrayData::UserAttributes () [inline]
The user attributes.
Returns:
The vector of user attributes.
Definition at line 116 of file ArrayData.h.
References userAttributes.
Referenced by affymetrix_calvin_io::SAXArrayHandlers::characters(), affymetrix_fusion_io::FusionArrayFileReader::Read(), FusionArrayFileReaderTest::testmethod_Read_calvin_array_file(), FusionArrayFileReaderTest::testmethod_Read_dtt_array_file(), FusionArrayFileReaderTest::testmethod_Read_invalid_file(), FusionArrayFileReaderTest::testmethod_Read_mas_array_file(), and FusionArrayFileReaderTest::testmethod_Read_missing_file().
Member Data Documentation
std::wstring affymetrix_calvin_array::ArrayData::createdBy [protected]
The user who created the data object.
Definition at line 68 of file ArrayData.h.
Referenced by Clear(), and CreatedBy().
CreateStep affymetrix_calvin_array::ArrayData::createdStep [protected]
The step in Calvin that created the array set data.
Definition at line 59 of file ArrayData.h.
Referenced by Clear(), and CreatedStep().
std::wstring affymetrix_calvin_array::ArrayData::creationDateTime [protected]
The date and time of initial creation.
Definition at line 65 of file ArrayData.h.
Referenced by Clear(), and CreationDateTime().
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_calvin_array::ArrayData::dataTypeId [protected]
An identifier to the type of data stored in the file
Definition at line 56 of file ArrayData.h.
Referenced by Clear(), and DataTypeIdentifier().
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_calvin_array::ArrayData::fileId [protected]
A unique idendifier for the array set object
Definition at line 53 of file ArrayData.h.
Referenced by ArraySetFileIdentifier(), and Clear().
std::wstring affymetrix_calvin_array::ArrayData::initialProject [protected]
The name of the project that initially created the array set data.
Definition at line 62 of file ArrayData.h.
Referenced by Clear(), and InitialProject().
ArrayAttributesVector affymetrix_calvin_array::ArrayData::physicalArraysAttributes [protected]
The arrays attributes for the arrays in the set
Definition at line 71 of file ArrayData.h.
Referenced by Clear(), and PhysicalArraysAttributes().
affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredTypeList affymetrix_calvin_array::ArrayData::userAttributes [protected]
The user attributes
Definition at line 74 of file ArrayData.h.
Referenced by Clear(), and UserAttributes().
The documentation for this class was generated from the following files:
calvin_files/array/src/ArrayData.h
calvin_files/array/src/ArrayData.cpp