Affymetrix Power Tools: TranslationTableModel Class Reference
TranslationTableModel Class Reference