Affymetrix Power Tools: AnalysisStreamExpression Class Reference
AnalysisStreamExpression Class Reference