Affymetrix Power Tools: QuantBRLMM Class Reference
QuantBRLMM Class Reference
Implements a SNP genotype calling method motivated by Nusrat Rabbee's RLMM (Robust Linear Model with Mahalanobis Distance Classifier) that utilizes a Baysian prior about the centers of SNP clusters.
#include <QuantBRLMM.h>