Affymetrix Power Tools: MultiChannelNonOverlapCelListener Class Reference
MultiChannelNonOverlapCelListener Class Reference
Class for computing hilo qc metric from a cel set of cel files.
#include <MultiChannelNonOverlapCelListener.h>