Affymetrix Power Tools: GeneCall Class Reference
GeneCall Class Reference
Public Member Functions
GeneCall (const RunTimeEnvironment &rte, class TranslationTableModel &ttm, const int headerRow, bool isHaplotypeCall)
GeneCall::GeneCall Synopsis:
bool addCallElementToAlleleCallSet (class TranslationTableModel &ttm, const int headerRow, const int row, const int column, bool allowMultiAllelic, bool rowIsHaplotype)
GeneCall::addCallElementToAlleleCallSet Synopsis:
void describeVerbose (const RunTimeEnvironment &rte, ADT_VERBOSE_ENUM level=ADT_VERBOSE_NULL)
GeneCall::describeVerbose Synopsis:
bool existsAlleleCallSet (const std::string &alleleName)
GeneCall::existsAlleleCallSet Synopsis:
CallSet & getAlleleCallSet (unsigned int index)
GeneCall::getAlleleCallSet Synopsis:
CallSet & getReferenceCallSet ()
CallSet & getVariantCallSet ()
class CallResults translateExperimentCall (RunTimeEnvironment &rte, const CallSet &completeSet, GenotypeTableModel &gtm, CallSet &chromatid1, CallSet &chromatid2, const std::string &copyNumberCall, const CallSet &copyNumberZeroCallSet)
Translating an experiment call means checking for allele names that correspond in the DMET3 translation table.
Public Attributes
std::vector< CallSet > m_alleleSet
std::string m_gene
Detailed Description
Definition at line 35 of file GeneCall.h.
Constructor & Destructor Documentation
GeneCall::GeneCall (const RunTimeEnvironment & rte, class TranslationTableModel & ttm, const int headerRow, bool isHaplotypeCall)
GeneCall::GeneCall Synopsis:
Translation Table constructer. The translation table row order is per marker. The column order starting with Reference, Variant and then A1 - ANN is what is being defined here as a call. The translation table is rows of markes with columns of calls.
Each gene has a number of calls designated. The GeneCall object represents the entire set of calls for a gene. The GeneCall is a set of sets, where the sets are CallSets. The CallSets are sets of CallElements where the CallElements represent the probset id with reference and variant alleles.
A GeneCall then represents the set of columns A1 - A50 (ANN) of the translation table for a particular gene.
The columns are chopped up at the Gene level. Within a gene, the column is subdivided by haplotype or marker. A column, like A1, then will have one GeneCall per marker where the "Haplotype" column is "N". For those markers of the gene where "Haplotype" column is "Y" then exactly one GeneCall is created.
NOTE: While in general the "Haplotype" column is "Y" records are grouped together for a particular gene in the translation table, this is not always the case. Probe sets with "Haplotype" column of "Y" can be interpersed with the "Haplotype" column "N" probesets.
For a particular gene there is ever only one haplotype group. That group is designated by the set of markers for the gene with "Haplotype" column indicator of "Y". A gene haplotype call (GeneCall) then corresponds to a column for all those rows of a gene in the translation table within a haplotype group.
This constructor takes in the header row for a particular gene and then instantiates all the CallSets for all the columns.
The CallSets for each call is subsequently filled with the probe set ids, reference and variant alleles when the translation table is scanned.
In other words, multiple data structures are being created when the translation table is being scanned. To prevent scanning the table multiple times this constructor simply instantiates the empty CallSet per call and the callee (TranslationTable) is responsible for filling in the CallSets per call as the subsequent rows are being scanned.
Parameters:
rte - RunTimeEnvironment which contains options
ttm - TranslationTableModel with the meta data about the call.
headerRow - the row in the ttm that has the meta data.
isHaplotypeCall - if the data row has been predetermined to have "Y" in the "Haplotype" column.
Definition at line 100 of file GeneCall.cpp.
References APT_ERR_ASSERT, TranslationInputTsvTableModel::columnCount(), existsAlleleCallSet(), TranslationTableModel::getColumnIndex(), TranslationTableModel::getHeaderRowColumnName(), TranslationInputTsvTableModel::getRowAsString(), Verbose::out(), and Verbose::warn().
Member Function Documentation
bool GeneCall::addCallElementToAlleleCallSet (class TranslationTableModel & ttm, const int headerRow, const int row, const int column, bool allowMultiAllelic, bool rowIsHaplotype)
GeneCall::addCallElementToAlleleCallSet Synopsis:
Initialize a CallElement from the translation table (and not an experiment data in the Genotype data (CHP)). To do this we need to identify the ProbeSet and the reference and variant base. The variant base will be either in the column that resides between A1-A29 or in the "Variant" column itself if no such animal exists.
Parameters:
ttm - TranslationTableModel with the meta data about the call.
headerRow - the row in the ttm that has the meta data.
row - the row in the TranslationTableModel in question.
column - the column in the TranslationTableModel in question.
allowMultiAllelic - probeSet may appear multiple times.
rowIsHaplotype - "Haplotype" column has "Y"
Returns:
- true upon successfull add.
Definition at line 205 of file GeneCall.cpp.
References APT_ERR_ASSERT, TranslationInputTsvTableModel::columnCount(), TranslationTableModel::getColumnIndex(), TranslationTableModel::getHeaderRowColumnName(), and Verbose::out().
void GeneCall::describeVerbose (const RunTimeEnvironment & rte, ADT_VERBOSE_ENUM level = ADT_VERBOSE_NULL)
GeneCall::describeVerbose Synopsis:
Run time debug routine that can be invoked with various verbose levels. ADT_VERBOSE_INPUT_FILES is the default level.
Parameters:
rte - run time environment
level - ADT_VERBOSE_INPUT_FILES by default, otherwise the ADT_VERBOSE_ENUM level to output
Definition at line 317 of file GeneCall.cpp.
References Verbose::out().
bool GeneCall::existsAlleleCallSet (const std::string & alleleName)
GeneCall::existsAlleleCallSet Synopsis:
Returns true if a CallSet in m_alleleSet has the passed in allele name.
alleleName - the call name to check (i.e. "Ref", "*4")
Definition at line 365 of file GeneCall.cpp.
Referenced by GeneCall().
CallSet & GeneCall::getAlleleCallSet (unsigned int index)
GeneCall::getAlleleCallSet Synopsis:
Convienance function to return either the Reference or Variant allele set.
Parameters:
index - between 0 and num m_alleleSet.size()
Returns:
CallSet reference corresponding to the index.
Definition at line 391 of file GeneCall.cpp.
References APT_ERR_ASSERT.
CallResults GeneCall::translateExperimentCall (RunTimeEnvironment & rte, const CallSet & completeSet, GenotypeTableModel & gtm, CallSet & chromatid1, CallSet & chromatid2, const std::string & dmet2CopyNumberCall, const CallSet & geneCopyNumberZeroCallSet)
Translating an experiment call means checking for allele names that correspond in the DMET3 translation table.
For reporting purposes all input experiment records from the Genotype CHIP or Short Report files are to have a corresponding record somewhere in the reporting, i.e. be included in the result set. There only exception are for unrecognized genes. An unrecognized gene is simply skipped over. Records for unrecognized genes will not be in the experiment results.
Parameters:
rte - RunTimeEnvironment which contains options
ttm - TranslationTableModel with the meta data about the call.
headerRow - the row in the ttm that has the meta data.
Definition at line 797 of file GeneCall.cpp.
References CallResults::appendAlleleCall(), APT_ERR_ABORT, CallSet::buildSecondSet(), CallSet::describeVerbose(), CallSet::getCallType(), CallSet::match(), CallResults::orderCalls(), and Verbose::out().
The documentation for this class was generated from the following files:
translation/GeneCall.h
translation/GeneCall.cpp