Affymetrix Power Tools: QuantMethodSqlExprReport Class Reference
QuantMethodSqlExprReport Class Reference
Class for reporting results of quantification methods.
#include <QuantMethodSqlExprReport.h>