Affymetrix Power Tools: FileGenders Class Reference
FileGenders Class Reference
Read gender assignments from file.
#include <FileGenders.h>