Affymetrix Power Tools: Verbose Class Reference
Verbose Class Reference
Verbose.
#include <Verbose.h>
Classes
class Param
Utility class for remembering our parameters of interest.
Static Public Member Functions
static Param & getParam ()
This function gets around the problem of static variable initialization as local static variables work more consistently.
static void pushProgressHandler (ProgressHandler *handler)
Functions to add and remove handlers for communcation functions.
static void popProgressHandler ()
static void removeProgressHandler (ProgressHandler *h)
static void removeProgressHandler (std::vector< ProgressHandler * > &vec, ProgressHandler *h)
static void pushMsgHandler (MsgHandler *handler)
static void popMsgHandler ()
static void removeMsgHandler (MsgHandler *handler)
static void removeMsgHandler (std::vector< MsgHandler * > &vec, MsgHandler *h)
static void pushWarnHandler (MsgHandler *handler)
static void popWarnHandler ()
static void progressBegin (int verbosity, const std::string &msg, int total, int dotMod, int maxCalls)
static void progressStep (int verbosity)
Print a dot out to let the user know we are still alive and making progress.
static void progressEnd (int verbosity, const std::string &msg)
static void removeDefault ()
static void setOutput (bool output)
Set whether or not output messages are logged useful to turn off output when catching expected errors.
static void setLevel (int level)
Set the level of verbosity desired.
static void out (int level, const std::string &s, bool nl=true)
Print a message to the stream.
static void warn (int level, const std::string &s, bool nl=true, const std::string prefix="\nWARNING: ")
Print a warning message.
Detailed Description
Verbose.
Class for doing logging and some command line ui.
Definition at line 53 of file Verbose.h.
Member Function Documentation
Verbose::Param & Verbose::getParam () [static]
This function gets around the problem of static variable initialization as local static variables work more consistently.
Returns:
Param - Our static parameters for this class.
Definition at line 103 of file Verbose.cpp.
References out().
Referenced by out(), BaseEngine::parseArgv(), progressStep(), pushProgressHandler(), TranslationEngine::runImp(), setLevel(), setOutput(), and warn().
void Verbose::out (int level, const std::string & s, bool nl = true) [static]
Print a message to the stream.
Parameters:
level - What level of verbosity this message should be printed at.
s - Message to be printed.
nl - Should a newline be appended to message?
Definition at line 259 of file Verbose.cpp.
References getParam(), Verbose::Param::m_MsgHandler, and Verbose::Param::m_Output.
Referenced by _validateInputExperimentFilesFromVectorDMET3(), SocketServer::acceptNewConnection(), GeneCall::addCallElementToAlleleCallSet(), CNFamilialReporterFamilial::addParentHeaders(), TranslationAudit::auditAnnotation(), BaseEngine::BaseEngine(), ProbeListFactory::buildProbeId2ApidIndex(), MultiChannelNonOverlapCelListener::calcCrossThreshold(), MultiChannelNonOverlapCelListener::calcLogDiff(), MultiChannelNonOverlapCelListener::calcNonOverlap(), VariabilityScoreCelListener::calcStats(), CNWorkflowEngine::calculateGenders(), CNCytoEngine::calculateGenders(), CNLog2RatioData::calculateMedianSignal(), CNLog2RatioData::calculateMedianSignalsPerGenotype(), CNLog2RatioData::calculateXYMedianSignal(), CnProbeGenderCelListener::callGender(), callGenotypes(), calvinEquiv(), QuantGTypeMethod::canSetUpProbeSet(), CelExtract::CelExtract(), MixedFileCheck::check(), DMET3TestCaseCheck::check(), ModelFileHeaderCheck::check(), ModelFileValidCheck::check(), EngineUtil::checkCelChipTypes(), EngineUtil::checkChipTypeOk(), EngineUtil::checkChipTypeVectors(), SocketUtil::checkForMsgs(), ExportImputeFormatEngine::checkOptionsImp(), ExportDataFilesEngine::checkOptionsImp(), ChipStreamFactory::chipStreamForString(), ChipStreamFactory::chipStreamForStringBoard(), TranslationExperimentReport::close(), RegressionExperimentReport::close(), MarkerExperimentReport::close(), TableFile::columnFromFile(), CNAnalysisMethodCNCyto2::computeMAPD(), HomHiLoCelListener::computeStatistic(), copyFile5File(), File5_Sqlite::copySchema(), copyTsvFile(), ProbeSetGroup::countPmProbes(), MarkerListModel::describeVerbose(), GenotypeOverrideTableModel::describeVerbose(), GeneCall::describeVerbose(), CallSet::describeVerbose(), GenotypeTableModel::describeVerboseExperimentGene(), CovariateParams::determineCovariateMap(), CNLog2RatioEngine::determineMemoryUsage(), AnalysisStreamExpSpectSel::doAnalysis(), AnalysisStreamExpression::doAnalysis(), AnalysisStreamExpPcaSel::doAnalysis(), AnalysisStream::doAnalysis(), CelExtract::doProbe(), CelExtract::doProbeSet(), doRma(), Mas5Test::doU133Calvin(), Mas5Test::doU133Xda(), affx::File5_File::equivalent(), Calvin::equivalentHeader(), file5Equiv(), SocketBase::fillBufferFromSocket(), GcAdjust::fillChipBins(), fillInCelFiles(), fillInFile5Files(), FileTranslation::fillInFromProbeSets(), fillInHaploidSnpsVersion1(), fillInHaploidSnpsVersion2(), ChipLayout::fillInKillList(), SelfCreate::fillInNameParam(), fillInOptions(), fillInTsvFiles(), RMA::findBandWidth(), QuantMethodMultiDataCCCHPReport::finish(), QuantMethodExprCCCHPReport::finish(), GeneCall::GeneCall(), GenotypeOverrideTableModel::GenotypeOverrideTableModel(), getDMET2AlgorithmChecks(), getDMET3ReportChecks(), ChipLayout::getHeaderValue(), SnpModelConverter::GetModelHeaders(), getParam(), DiskIntensityMart::getProbeIntensity(), MultiChannelNonOverlapCelListener::GimmeContrast(), MultiChannelHomHiLoCelListener::GimmeContrast(), VerboseErrHandler::handleError(), MyErrHandler::handleError(), SocketTextHandler::handleMessage(), affx::TsvFile::headers_to_fields_v2(), RmaBgTran::initializeData(), MedNormTran::initializeData(), TranslationCommonControl::initializeInputFileModels(), GcBg::learnParameters(), Calvin::load(), CNLog2RatioData::loadAlleleEstimatesByExperiment(), AdapterTypeNormTran::loadAnnotation(), CNLog2RatioData::loadCyto2ModelFile(), CNLog2RatioData::loadGenderOverrideFile(), CNLog2RatioData::loadGenotypeReport(), QuantLabelZ::loadInitialCallsForSnp(), CNLog2RatioData::loadModelFile(), loadSNPHints(), CNLog2RatioData::loadSnpReferenceFile(), CNAnalysisMethodLOHCyto2::lohPreProcessing(), main(), DmListener::makeCall(), QuantLabelZ::makeNorm(), QuantBRLMM::makePrior(), affymetrix_calvin_io::GenericData::MapFile(), PgOptions::matchOneArg(), matrixDiff(), Util::matrixDifferences(), MultiChannelHomHiLoCelListener::MultiChannelHomHiLoCelListener(), VariabilityScoreCelListener::newChip(), SignalBackgroundCelListener::newChip(), MultiChannelNonOverlapCelListener::newChip(), MultiChannelHomHiLoCelListener::newChip(), HomHiLoCelListener::newChip(), SketchQuantNormTran::newChipSuppliedTargetSketch(), SketchQuantNormTran::newDataSet(), TableFile::open(), SQLiteRecordset::open(), SQLiteDatabase::open(), affx::TsvFile::open(), ChipLayout::openCdf(), ChipLayout::openPgf(), QuantMethodFactory::openPrecompFeatureEffects(), PgOptions::parseArgv(), BaseEngine::parseArgv(), DmetEngine::parseArgv(), CNAnalysisEngine::postProcessing(), QuantMethodMultiDataCCCHPReport::prepare(), QuantMethodGTypeReport::prepare(), QuantMethodExprCHPReport::prepare(), QuantMethodExprCCCHPReport::prepare(), QuantLabelZ::prepare(), affx::TsvFile::printBindingErrors(), Options::printOptions(), TranslationTableModel::probeSetFilter(), CNReferenceEngine::processData(), CNLog2RatioEngine::processData(), QuantMethodFactory::quantMethodForString(), ChipLayout::readCdfProbe(), ChipLayout::readCdfProbeSet(), CNCychp::readFile(), CelReader::readFiles(), GenoSeedTxt::readInPrecompGenoTypes(), MetaProbeset::readMetaProbesets(), QuantMethodFactory::readPrecompFeatureEffectsFromFile(), ChipLayout::readProbeListCdfFileKillList(), ChipLayout::readProbeListPgfFileKillList(), TranslationInputTsvTableModel::readTsvFile(), QuantMethodGTypeChipSummary::report(), reportBasics(), RegressionCheck::reportError(), SparseMart::reserve(), BaseEngine::run(), CNReporterCnchp::run(), CNReferenceMethodWaveCorrection::run(), CNReferenceMethodPDNN::run(), CNLog2RatioAdjustmentMethodWaveCorrection::run(), CNLog2RatioAdjustmentMethodHighPassFilter::run(), CNIntensityAdjustmentMethodPDNN::run(), CNIntensityAdjustmentMethodHighPassFilter::run(), CNFamilialReporterFamilial::run(), CNFamilialAnalysisMethodSegmentOverlap::run(), CNFamilialAnalysisMethodLOD::run(), CNFamilialAnalysisMethodIsoUPD::run(), CNFamilialAnalysisMethodHeteroUPD::run(), CNFamilialAnalysisMethodHemizygousParentOfOrigin::run(), CNFamilialAnalysisMethodGenotypeDiscordance::run(), CNFamilialAnalysisMethodGenotypeConcordance::run(), CNFamilialAnalysisMethodDenovoCopyNumber::run(), CNFamilialAnalysisMethodCNNeutralLOHConcordance::run(), CNFamilialAnalysisMethodCNLossLOHConcordance::run(), CNAnalysisMethodSegmentLOH::run(), CNAnalysisMethodSegmentCN::run(), CNAnalysisMethodNormalDiploid::run(), CNAnalysisMethodNoCall::run(), CNAnalysisMethodMosaicism::run(), CNAnalysisMethodLOHCytoScan::run(), CNAnalysisMethodLOHCyto2::run(), CNAnalysisMethodLOH::run(), CNAnalysisMethodKernelSmooth::run(), CNAnalysisMethodGenotype::run(), CNAnalysisMethodGaussianSmooth::run(), CNAnalysisMethodCNNeutralLOH::run(), CNAnalysisMethodCNGender::run(), CNAnalysisMethodCNCyto2Gender::run(), CNAnalysisMethodCNCyto2::run(), CNAnalysisMethodChipstream::run(), CNAnalysisMethodAllelicDifferenceCytoScan::run(), CNAnalysisMethodAllelicDifference::run(), CNAnalysisMethodAllelePeaks::run(), summaryVis::run(), runDmet2AlgorithmRegression(), runDmet3ReportRegression(), TranslationEngine::runImp(), SketchQuantNormTran::scaleTargetSketch(), QuantRma::setFeaturePriorEffects(), QuantPlier::setFeaturePriorEffects(), PgOptions::setOptionsFromXMLFile(), SketchQuantNormTran::setParameters(), QuantRma::setParameters(), QuantPlierBase::setParameters(), RmaBgTran::setPmProbes(), TranslationTableModel::setReportAlleles(), MedNormTran::setTarget(), FsTestDir::setTestDir(), QuantRma::setUp(), QuantPlierBase::setUp(), QuantBRLMM::setUp(), QuantAvgDiff::setUp(), QuantMethodFactory::setupQuantMethodFactory(), SignalBackgroundCelListener::SignalBackgroundCelListener(), SnpClusterStore::SnpClusterStore(), SocketClient::socketConnect(), TranslationInputStreamTableModel::sortTsvFileByExperiment(), RegressionTest::syncDirectory(), Convert::toDoubleCheck(), CNLog2RatioEngine::transferProbeSetData(), ChipStreamDataTransform::transformData(), GeneCall::translateExperimentCall(), TranslationTable::translateExperimentGene(), TranslationTable::TranslationTable(), CelExtract::tsvSetProbeAnnotations(), TranslationCommonControl::validateCommonOptions(), ExperimentFileTableModel::validateFiles(), VariabilityScoreCelListener::VariabilityScoreCelListener(), CNCychp::warning(), CNLog2RatioData::writeCyto2ModelFile(), CNLog2RatioData::writeModelFile(), CNLog2RatioEngine::writeOutputHdf5(), CNCytoEngine::writeOutputHdf5(), CNLog2RatioEngine::writeOutputText(), CNCytoEngine::writeOutputText(), BaseEngine::~BaseEngine(), and DataStore::~DataStore().
void Verbose::progressStep (int verbosity) [static]
Print a dot out to let the user know we are still alive and making progress.
Parameters:
verbosity - What level of verbosity this message should be printed at.
Definition at line 78 of file Verbose.cpp.
References getParam(), Verbose::Param::m_DotCount, Verbose::Param::m_DotMod, Verbose::Param::m_ProHandler, and Verbose::Param::m_Verbosity.
Referenced by callGenotypes(), File5_Sqlite::copyData(), CelExtract::doProbe(), CelExtract::doProbeSet(), QuantMethodMultiDataCCCHPReport::finish(), QuantMethodExprCCCHPReport::finish(), SocketTextHandler::handleMessage(), CNLog2RatioData::loadAlleleEstimatesByExperiment(), CNLog2RatioData::loadAlleleEstimatesByProbeSet(), CNLog2RatioData::loadAlleleEstimatesByProbeSetHdf5(), AdapterTypeNormTran::loadAnnotation(), CNLog2RatioData::loadGenotypeCallsByExperiment(), CNLog2RatioData::loadGenotypeCallsByExperimentHdf5(), CNLog2RatioData::loadGenotypeCallsByProbeSet(), CNLog2RatioData::loadGenotypeCallsByProbeSetHdf5(), CNLog2RatioData::loadGenotypeConfidencesByExperiment(), CNLog2RatioData::loadGenotypeConfidencesByExperimentHdf5(), CNLog2RatioData::loadModelFile(), SketchQuantNormTran::newDataSet(), ChipLayout::openSpf_v3(), ChipLayout::openSpf_v4(), QuantMethodGTypeCHPReport::prepare(), QuantMethodExprCHPReport::prepare(), CNLog2RatioEngine::processData(), TableReader::readFiles(), CelReader::readFiles(), ChipLayout::readProbeListCdfFileKillList(), ChipLayout::readProbeListPgfFileKillList(), CNIntensityAdjustmentMethodPDNN::run(), CNFamilialAnalysisMethodSegmentOverlap::run(), CNFamilialAnalysisMethodLOD::run(), CNFamilialAnalysisMethodIsoUPD::run(), CNFamilialAnalysisMethodHeteroUPD::run(), CNFamilialAnalysisMethodHemizygousParentOfOrigin::run(), CNFamilialAnalysisMethodGenotypeDiscordance::run(), CNFamilialAnalysisMethodGenotypeConcordance::run(), CNFamilialAnalysisMethodDenovoCopyNumber::run(), CNFamilialAnalysisMethodCNNeutralLOHConcordance::run(), CNFamilialAnalysisMethodCNLossLOHConcordance::run(), CNAnalysisMethodMosaicism::run(), CNAnalysisMethodLOHCyto2::run(), CNAnalysisMethodLog2RatioCyto2::run(), CNAnalysisMethodCNCyto2::run(), TranslationEngine::runImp(), ExportImputeFormatEngine::runImp(), ExportDataFilesEngine::runImp(), QuantMethodTransform::transformData(), ChipStreamDataTransform::transformData(), CNLog2RatioData::writeCyto2ModelFile(), and CNLog2RatioData::writeModelFile().
void Verbose::setLevel (int level) [static]
Set the level of verbosity desired.
0 == no messages 1 == normal messages, 2,3,4, etc. == more verbose.
Parameters:
level - level of verbosity desired.
Definition at line 242 of file Verbose.cpp.
References getParam(), Verbose::Param::m_MsgHandler, Verbose::Param::m_ProHandler, and Verbose::Param::m_Verbosity.
Referenced by calvinEquiv(), CallSetTest::describeVerbose(), file5Equiv(), getOptions(), main(), matrixDiff(), RunTimeEnvironment::setVerbosity(), and translateEngineMessageHandlingCallBack().
void Verbose::setOutput (bool output) [static]
Set whether or not output messages are logged useful to turn off output when catching expected errors.
Parameters:
output - true or false
Definition at line 232 of file Verbose.cpp.
References getParam(), and Verbose::Param::m_Output.
void Verbose::warn (int level, const std::string & s, bool nl = true, const std::string prefix = "\nWARNING: ") [static]
Print a warning message.
Parameters:
level - What level of verbosity this message should be printed at.
s - Message to be printed.
nl - Should a newline be appended to message?
Definition at line 277 of file Verbose.cpp.
References getParam(), Verbose::Param::m_Output, and Verbose::Param::m_WarnHandler.
Referenced by GenoCallCoder::abstractAlleleIntegersToGenotypeCallNum(), GenoCallCoder::abstractAlleleToGenotypeCallNum(), GenoCallCoder::abstractAlleleVecToGenotypeCallNumVec(), IdxGroup::addGroup(), ModelFileHeaderCheck::check(), IdxGroup::elementIdxRequire(), GeneCall::GeneCall(), GenoCallCoder::genotypeCallNumToAbstractAllele(), GenoCallCoder::genotypeCallNumVecToAbstractAlleleVec(), IdxGroup::groupIdxRequire(), IdxGroup::groupingNameRequire(), GenoCallCoder::initialize(), CNAnalysisMethodLOHCyto2::newSegments(), CelReader::readFiles(), ChipLayout::readProbeListPgfFileKillList(), CNAnalysisMethodAllelePeaks::run(), Err::setExitOnError(), Err::setExitOnErrorValue(), TranslationTable::translateExperimentGene(), TranslationTableModel::validateRowIsHeader(), QuantMethodSqlExprReport::~QuantMethodSqlExprReport(), and QuantMethodSqlGTypeReport::~QuantMethodSqlGTypeReport().
The documentation for this class was generated from the following files:
util/Verbose.h
util/Verbose.cpp