Affymetrix Power Tools: affx::Dabg Class Reference
affx::Dabg Class Reference
#include <Dabg.h>
Public Types
typedef float intensity_t
Public Member Functions
Dabg ()
Creates a new Dabg object and inits it.
Dabg (int intensity_cap)
Creates a new Dabg object with space reserved. ///.
void clear ()
Initialize the object to empty.
void intensity_reserve (int approx_probe_cnt)
reserve space for intensity values ///
void intensity_reserve_copy (affx::Dabg &dabg2)
Copy the reservations from another dabg ///.
size_t intensity_count (int gc_bin)
void add_intensitiy_vec (std::vector< int > gc_vec, std::vector< intensity_t > intensity_vec)
void add_intensity (int gc_idx, intensity_t intensity)
Add a single intensity ///.
double intensity_to_pvalue (int gc_idx, intensity_t intensity)
Convert an intensity to a p-value ///.
void dump (int level)
Dump the contents of the object ///.
void prepare ()
prepare this object for use. //! At the moment, this just means sorting the vectors. //! also see prepare_maybe in "Dabg.h" ///
void prepare_maybe ()
void compute_target_fisher (int probe_cnt, int *gc_arr, double *pm_arr, int dof_adjustment, double *out_target, double *out_pval_arr)
Compute the targets and pvals for all the chips. ///.
void compute_target_percentile (int probe_cnt, int *gc_arr, double *pm_arr, double per_cut, double *out_target, double *out_pval_arr)
void dabgfile_write (const std::string &filename)
void dabgfile_read (const std::string &filename)
Public Attributes
int chip_capacity
int intensity_capacity
int is_prepared
std::vector< std::vector
< intensity_t > > data
where the data is held. dabg[gc_count][idx]=intensity
Detailed Description
Todo:
template <typename intensity_t>="">
Definition at line 42 of file Dabg.h.
Constructor & Destructor Documentation
affx::Dabg::Dabg (int capacity)
Creates a new Dabg object with space reserved. ///.
Parameters:
chip_cap reserve space for this many chips ///
intensity_cap reserve space for this many intensities per chip
Definition at line 47 of file Dabg.cpp.
References clear(), and intensity_reserve().
Member Function Documentation
void affx::Dabg::add_intensity (int gcbin, intensity_t intensity)
Add a single intensity ///.
Parameters:
chip_idx the chip to add it to. ///
gcbin the gc value of this probe ///
intensity the intensity value of this probe
Definition at line 128 of file Dabg.cpp.
References data.
Referenced by run_test_1().
void affx::Dabg::compute_target_fisher (int probe_cnt, int * gc_arr, double * pm_arr, int dof_adjustment, double * out_target, double * out_pval_arr)
Compute the targets and pvals for all the chips. ///.
Parameters:
probe_cnt number of probes ///
gc_arr array of probe gc values ///
pm_arr array of probe pm intensities ///
target_arr output array of target probabilities ///
pvalues_arr output array of probe probabilities Compute the target and pvals for one chip.
chip_idx Index of the chip ///
probe_cnt number of probes in set ///
gc_arr gc values of the probles ///
pm_arr pm intensity values of the probles /
target Output: probability of the probset above background. ///
pval_arr Output: probability of the probe above background
Todo:
This should be replaced with a constant bias rather than a step function.
Todo:
Why '-2*'?
Definition at line 262 of file Dabg.cpp.
References affxstat::chisqrprob(), and intensity_to_pvalue().
Referenced by QuantDabg::computeEstimate(), run_test_2(), and run_test_3().
void affx::Dabg::dabgfile_write (const std::string & filename)
Todo:
Turn these into ">>" and "<<" operators.
Definition at line 329 of file Dabg.cpp.
References data.
Referenced by run_test_1().
void affx::Dabg::dump (int level)
Dump the contents of the object ///.
Parameters:
level The level of verbosity ///
Remarks:
//! level=0: summary //! level=1: gcbins with sizes>0 //! level=2: all gcbins //! level=3: all data
Definition at line 216 of file Dabg.cpp.
References data.
void affx::Dabg::intensity_reserve (int capacity)
reserve space for intensity values ///
Parameters:
chip_idx the chip to reserve space for.
Definition at line 68 of file Dabg.cpp.
References data.
Referenced by Dabg(), and run_test_1().
void affx::Dabg::intensity_reserve_copy (affx::Dabg & dabg_from)
Copy the reservations from another dabg ///.
Parameters:
dabg_from Dabg to copy from
Definition at line 98 of file Dabg.cpp.
References AFFYDABG_GC_COUNT_MAX, and data.
double affx::Dabg::intensity_to_pvalue (int gcbin, Dabg::intensity_t intensity)
Convert an intensity to a p-value ///.
Parameters:
chip which chip to use ///
gcbin which gc bin the probe is in ///
intensity the intensity of the probe ///
Returns:
the probablity that this p-value is above the background. ///
Remarks:
//! this is the left-tail probablity. //! Prob=value is larger than all items to the left. // vectors are sorted in increasing order.
Definition at line 158 of file Dabg.cpp.
References data.
Referenced by compute_target_fisher(), and run_test_1().
void affx::Dabg::prepare ()
prepare this object for use. //! At the moment, this just means sorting the vectors. //! also see prepare_maybe in "Dabg.h" ///
prepare the object for use (sort all the intensities)
Definition at line 139 of file Dabg.cpp.
References data.
The documentation for this class was generated from the following files:
dabg/Dabg.h
dabg/Dabg.cpp