Affymetrix Power Tools: CNAnalysisMethodLog2RatioCyto2 Class Reference
CNAnalysisMethodLog2RatioCyto2 Class Reference
The Log2RatioCyto2 analysis method.
#include <CNAnalysisMethodLog2RatioCyto2.h>