Affymetrix Power Tools: PmSumAdjust Class Reference
PmSumAdjust Class Reference
Class for doing an adjustment based on the median intensity of probes with similar GC content.
#include <PmSumAdjust.h>