Affymetrix Power Tools: affymetrix_calvin_io::DataGroupHeader Class Reference
affymetrix_calvin_io::DataGroupHeader Class Reference
Public Member Functions
DataGroupHeader (const std::wstring &n)
void Clear ()
void SetName (const std::wstring &p)
std::wstring GetName () const
int32_t GetDataSetCnt () const
void AddDataSetHdr (const DataSetHeader &p)
void ReplaceDataSetHdr (const DataSetHeader &p)
DataSetHeader & GetDataSet (int32_t index)
const DataSetHeader & GetDataSetConst (int32_t index) const
void GetDataSetIterators (DataSetHdrIt &begin, DataSetHdrIt &end)
void SetHeaderStartFilePos (u_int32_t pos)
u_int32_t GetHeaderStartFilePos () const
void SetDataSetPos (u_int32_t pos)
u_int32_t GetDataSetPos () const
void SetNextGroupPos (u_int32_t pos)
u_int32_t GetNextGroupPos () const
affymetrix_calvin_io::DataSetHeader * FindDataSetHeader (const std::wstring &dataSetName)
Detailed Description
Definition at line 38 of file DataGroupHeader.h.
Member Function Documentation
void DataGroupHeader::AddDataSetHdr (const DataSetHeader & p)
Definition at line 69 of file DataGroupHeader.cpp.
Referenced by affymetrix_calvin_io::CHPTilingData::AddTilingSequenceData(), affymetrix_calvin_io::DataGroupHeaderUpdater::AppendDataSetHeader(), affymetrix_calvin_io::CDFFileWriter::OpenDataGroup(), affymetrix_calvin_io::CDFCntrlFileWriter::OpenDataGroup(), affymetrix_calvin_io::DataSetHeaderReader::ReadAll(), affymetrix_calvin_io::DataSetHeaderReader::ReadAllMinimumInfo(), affymetrix_calvin_io::CHPData::SetBackgroundZoneCnt(), affymetrix_calvin_io::CHPQuantificationDetectionData::SetEntryCount(), affymetrix_calvin_io::CHPQuantificationData::SetEntryCount(), affymetrix_calvin_io::CHPMultiDataData::SetEntryCount(), affymetrix_calvin_io::CHPData::SetEntryCount(), affymetrix_calvin_io::CHPData::SetForceCnt(), affymetrix_calvin_io::CHPData::SetOrigCnt(), CNFamilialReporterFamilial::setupDataSetHeaderPaternityTesting(), CNFamilialReporterFamilial::setupDataSetHeaderSamples(), CNFamilialReporterFamilial::setupDataSetHeaderSegmentOverlaps(), CNFamilialReporterFamilial::setupDataSetHeaderSegments(), and affymetrix_calvin_io::GridControlFileWriter::Write().
void DataGroupHeader::Clear ()
Definition at line 46 of file DataGroupHeader.cpp.
DataSetHeader & DataGroupHeader::GetDataSet (int32_t index)
Definition at line 86 of file DataGroupHeader.cpp.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::DataGroupHeaderUpdater::AppendDataSetHeader(), affymetrix_calvin_io::GenericData::FindDataSetHeader(), affymetrix_calvin_io::CHPData::GetBackgroundZoneCnt(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetDataSetHeader(), affymetrix_calvin_io::CHPQuantificationData::GetDataSetHeader(), affymetrix_calvin_io::CHPMultiDataData::GetDataSetHeader(), affymetrix_calvin_io::DataGroupReader::GetDataSetReader(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetEntryCount(), affymetrix_calvin_io::CHPQuantificationData::GetEntryCount(), affymetrix_calvin_io::CHPData::GetEntryCount(), affymetrix_calvin_io::CHPData::GetForceCnt(), affymetrix_calvin_io::CHPData::GetOrigCnt(), affymetrix_calvin_io::CHPTilingData::GetTilingSequenceEntryCount(), and affymetrix_calvin_io::DataSetUpdater::Initialize().
int32_t DataGroupHeader::GetDataSetCnt () const
Get the data set count
Definition at line 64 of file DataGroupHeader.cpp.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::CHPTilingData::AddTilingSequenceData(), affymetrix_calvin_io::DataGroupHeaderUpdater::AppendDataSetHeader(), affymetrix_calvin_io::GenericData::DataSetCnt(), affymetrix_calvin_io::DataGroupReader::GetDataSetCnt(), affymetrix_calvin_io::CHPMultiDataData::GetDataSetHeader(), affymetrix_calvin_io::DataGroupReader::GetDataSetReader(), affymetrix_calvin_io::DataSetUpdater::Initialize(), and affymetrix_calvin_io::CDFProbeSetInformation::SetDataGroup().
const DataSetHeader & DataGroupHeader::GetDataSetConst (int32_t index) const
Definition at line 91 of file DataGroupHeader.cpp.
Referenced by affymetrix_calvin_io::CDFProbeSetInformation::SetDataGroup().
void DataGroupHeader::GetDataSetIterators (DataSetHdrIt & begin, DataSetHdrIt & end)
Definition at line 96 of file DataGroupHeader.cpp.
Referenced by affymetrix_calvin_io::GenericData::DataSetNames(), and affymetrix_calvin_io::DataGroupHeaderUpdater::ReplaceDataSetHeader().
u_int32_t affymetrix_calvin_io::DataGroupHeader::GetDataSetPos () const [inline]
Get the file position of the DataSet header.
Definition at line 97 of file DataGroupHeader.h.
Referenced by affymetrix_calvin_io::DataSetHeaderReader::ReadAll(), and affymetrix_calvin_io::DataSetHeaderReader::ReadAllMinimumInfo().
u_int32_t affymetrix_calvin_io::DataGroupHeader::GetHeaderStartFilePos () const [inline]
Get the file position of the start of the DataSet header.
Definition at line 90 of file DataGroupHeader.h.
std::wstring DataGroupHeader::GetName () const
Definition at line 59 of file DataGroupHeader.cpp.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::CHPMultiDataData::GetDataGroupHeader(), affymetrix_calvin_io::CHPMultiDataData::GetDataGroupIndex(), affymetrix_calvin_io::DataGroupReader::GetDataGroupName(), affymetrix_calvin_io::CDFProbeSetInformation::GetName(), and ReplaceDataSetHdr().
u_int32_t affymetrix_calvin_io::DataGroupHeader::GetNextGroupPos () const [inline]
Get the file position of the next DataGroup header.
Definition at line 101 of file DataGroupHeader.h.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::CDFData::GetProbeSetInformation(), affymetrix_calvin_io::CDFData::GetQCProbeSetInformation(), affymetrix_calvin_io::DataGroupHeaderReader::Read(), and affymetrix_calvin_io::DataGroupHeaderReader::ReadMinimumInfo().
void DataGroupHeader::ReplaceDataSetHdr (const DataSetHeader & p)
Replace a data set header with a new data set header of the same name.
Parameters:
new data set header with the same name as the header it replaces.
Definition at line 74 of file DataGroupHeader.cpp.
References affymetrix_calvin_io::DataSetHeader::GetName(), and GetName().
Referenced by affymetrix_calvin_io::DataGroupHeaderUpdater::ReplaceDataSetHeader().
void affymetrix_calvin_io::DataGroupHeader::SetDataSetPos (u_int32_t pos) [inline]
Set the file position of the DataSet header. The value set here is not necessarily the value written to the file.
Definition at line 95 of file DataGroupHeader.h.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), and affymetrix_calvin_io::DataGroupHeaderReader::ReadFirstDataSetFilePos().
void affymetrix_calvin_io::DataGroupHeader::SetHeaderStartFilePos (u_int32_t pos) [inline]
Set the file position of the start of the DataSet header. The value set here is not written to the file.
Definition at line 87 of file DataGroupHeader.h.
Referenced by affymetrix_calvin_io::DataGroupHeaderReader::ReadDataGroupStartFilePos().
void DataGroupHeader::SetName (const std::wstring & p)
Definition at line 54 of file DataGroupHeader.cpp.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::DataGroupHeaderReader::ReadDataGroupName(), and affymetrix_calvin_io::GridControlFileWriter::Write().
void affymetrix_calvin_io::DataGroupHeader::SetNextGroupPos (u_int32_t pos) [inline]
Set the file position of the next DataGroup header.
Definition at line 99 of file DataGroupHeader.h.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), and affymetrix_calvin_io::DataGroupHeaderReader::ReadNextDataGroupFilePos().
The documentation for this class was generated from the following files:
calvin_files/data/src/DataGroupHeader.h
calvin_files/data/src/DataGroupHeader.cpp