Affymetrix Power Tools: affx::File5_Vector Class Reference
affx::File5_Vector Class Reference