Affymetrix Power Tools: affymetrix_calvin_io::GenericDataHeader Class Reference
affymetrix_calvin_io::GenericDataHeader Class Reference
Public Member Functions
void Clear ()
void SetFileTypeId (const std::string &p)
std::string GetFileTypeId () const
void SetFileId (const affymetrix_calvin_utilities::AffymetrixGuidType &p)
affymetrix_calvin_utilities::AffymetrixGuidType GetFileId () const
void SetFileCreationTime (const std::wstring &f)
std::wstring GetFileCreationTime () const
void SetLocale (const std::wstring &p)
std::wstring GetLocale () const
void AddNameValParam (const ParameterNameValueType &p)
void AddNameValParam (const ParameterNameValueType &p, bool doUniqueAdds)
This override of the original method of the same name adds the parameter bool doUniqueAdds.
ParameterNameValueType GetNameValParam (int32_t index)
int32_t GetNameValParamCnt () const
void GetNameValIterators (ParameterNameValueTypeIt &begin, ParameterNameValueTypeIt &end)
int32_t GetParentCnt () const
void AddParent (const GenericDataHeader &hdr)
GenericDataHeader GetParent (int32_t index) const
void GetParentIterators (std::vector< GenericDataHeader >::iterator &begin, std::vector< GenericDataHeader >::iterator &end)
GenericDataHeader * FindParent (const std::string &fileTypeId)
bool FindNameValParam (const std::wstring &name, ParameterNameValueType &result)
bool GetNameValParamsBeginsWith (const std::wstring &beginsWith, ParameterNameValueTypeVector &p)
Protected Member Functions
ParameterNameValueTypeIt FindNameValParam (const ParameterNameValueType &p)
Detailed Description
Definition at line 44 of file GenericDataHeader.h.
Member Function Documentation
void GenericDataHeader::AddNameValParam (const ParameterNameValueType & p)
Calls AddNameValParam with the doUniqueAddds set to true.
Definition at line 85 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::CelFileData::AddAlgorithmParameter(), affymetrix_calvin_io::CHPTilingData::AddAlgParams(), affymetrix_calvin_io::CHPQuantificationDetectionData::AddAlgParams(), affymetrix_calvin_io::CHPQuantificationData::AddAlgParams(), affymetrix_calvin_io::CHPMultiDataData::AddAlgParams(), affymetrix_calvin_io::CHPMultiDataData::AddAppMetaInfo(), affymetrix_chp_converter::CHPFileConvertToCalvin::AddExtraParameters(), affymetrix_cel_converter::CELFileConvertToCalvin::AddExtraParameters(), CNFamilialReporterFamilial::addPgOptions(), CNFamilialReporterFamilial::addStandardHeader(), affymetrix_calvin_io::CHPQuantificationDetectionData::AddSummaryParams(), affymetrix_calvin_io::CHPQuantificationData::AddSummaryParams(), affymetrix_calvin_io::CHPMultiDataData::AddSummaryParams(), ConverterCreateAndAddParentArrayGenericDataHeader(), CopyNumberResultWriter::CreateResultFile(), QuantMethodMultiDataCCCHPReport::finish(), QuantMethodExprCCCHPReport::finish(), affymetrix_cel_converter::CELFileConvertToCalvin::GenerateParentGenericDataHeaderFromGCOS(), makeMultiCelFileSubset(), QuantMethodMultiDataCCCHPReport::prepare(), QuantMethodExprCCCHPReport::prepare(), affymetrix_calvin_io::GenericDataHeaderReader::Read(), CNReporterCnchp::run(), affymetrix_calvin_io::DATData::SetArrayBarcode(), affymetrix_calvin_io::DATData::SetArrayId(), affymetrix_calvin_io::CHPData::SetFloatToGenericHdr(), affymetrix_calvin_io::CHPData::SetInt32ToGenericHdr(), affymetrix_calvin_io::DATData::SetPixelSize(), affymetrix_calvin_io::CDFData::SetRefSequence(), CNFamilialReporterFamilial::setupHeader(), affymetrix_calvin_io::CHPData::SetWStringToGenericHdr(), and affymetrix_calvin_io::GridControlFileWriter::Write().
void GenericDataHeader::AddNameValParam (const ParameterNameValueType & entry, bool doUniqueAdds)
This override of the original method of the same name adds the parameter bool doUniqueAdds.
Adds a ParameterNameValueType to the collection.
Parameters:
Parameter to add.
Hint to either perform a check to ensure unique parameters are in the collection (N^2 performance), else do not perfomr the check.
This parameter is a hint flag to determine whether to bypass the FindParameter call within. FindParameter is used to ensure duplicates do not get entered into the collection. In most cases, the calling application is not updating or adding parameter to the collection, but is just reading the header parameters. Through testing it has been found that bypassing the FindParameter call made, will reduce reads of the header greatly.
If an application is updating or adding parameters to the collection and require no duplicates to be added, then do not use this override method, but if you are just reading header parameters, then this will save time reading headers.
Definition at line 101 of file GenericDataHeader.cpp.
References FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetName().
void GenericDataHeader::AddParent (const GenericDataHeader & hdr)
Definition at line 139 of file GenericDataHeader.cpp.
Referenced by CNFamilialReporterFamilial::addParentHeaders(), ConverterCreateAndAddParentArrayGenericDataHeader(), affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile(), affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile(), CopyNumberResultWriter::CreateResultFile(), affymetrix_calvin_io::DATData::GetParentArrayGenericDataHeader(), makeMultiCelFileSubset(), QuantMethodMultiDataCCCHPReport::prepare(), QuantMethodExprCCCHPReport::prepare(), affymetrix_calvin_io::GenericDataHeaderReader::Read(), and CNReporterCnchp::run().
void GenericDataHeader::Clear ()
Definition at line 36 of file GenericDataHeader.cpp.
Referenced by CNCychp::loadHeader().
bool GenericDataHeader::FindNameValParam (const std::wstring & name, ParameterNameValueType & result)
Finds a ParameterNameValueType by name in the nameValPairs collection
Parameters:
name The name of the NameValPair to find
result Reference to a ParameterNameValueType to fill with the found ParameterNameValueType.
Returns:
true if the ParameterNameValueType was found
Definition at line 179 of file GenericDataHeader.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueText().
Referenced by AddNameValParam(), affymetrix_calvin_io::GenericData::ArrayIdentifier(), affymetrix_calvin_io::CelFileData::FindAlgorithmParameter(), QuantMethodMultiDataCCCHPReport::finish(), QuantMethodExprCCCHPReport::finish(), FromHP(), affymetrix_calvin_io::CHPData::GetAlgParam(), affymetrix_calvin_io::DATData::GetArrayBarcode(), affymetrix_calvin_io::DATData::GetArrayId(), affymetrix_calvin_io::CelFileData::GetChannels(), affymetrix_calvin_io::CHPData::GetChipSum(), affymetrix_fusion_io::CalvinCELDataAdapter::GetDatHeader(), affymetrix_calvin_io::CelFileData::GetDatHeader(), affymetrix_calvin_io::CHPData::GetInt32FromGenericHdr(), affymetrix_calvin_io::DATData::GetPixelSize(), affymetrix_calvin_io::CDFData::GetRefSequence(), affymetrix_calvin_io::CelFileData::GetVersion(), affymetrix_calvin_io::CHPData::GetWStringFromGenericHdr(), affymetrix_calvin_io::GridControlFileReader::Read(), and affymetrix_calvin_io::GenericDataHeaderUpdater::UpdateParameters().
ParameterNameValueTypeIt GenericDataHeader::FindNameValParam (const ParameterNameValueType & p) [protected]
Finds a ParameterNameValueType by name in the nameValPairs collection
Parameters:
p The ParameterNameValueType to find
Returns:
An iterator referencing the NameValPair if it exists, otherwise it returns nameValPairs.end()
Definition at line 193 of file GenericDataHeader.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetName().
GenericDataHeader * GenericDataHeader::FindParent (const std::string & fileTypeId)
Find an immediate parent GenericDataHeader based on file type id. Does not search grand-parents or above.
Parameters:
fileTypeId The fileTypeId of the parent header to find.
Returns:
Returns a pointer to the parent GenericDataHeader if found, otherwise returns 0.
Definition at line 163 of file GenericDataHeader.cpp.
References GetParentIterators().
Referenced by affymetrix_calvin_io::GenericData::ArrayFileIdentifier(), affymetrix_calvin_io::GenericData::ArrayIdentifier(), affymetrix_calvin_io::CelFileData::GetChannels(), affymetrix_fusion_io::CalvinCELDataAdapter::GetDatHeader(), affymetrix_calvin_io::CelFileData::GetDatHeader(), and affymetrix_calvin_io::DATData::GetParentArrayGenericDataHeader().
std::wstring GenericDataHeader::GetFileCreationTime () const
Definition at line 70 of file GenericDataHeader.cpp.
affymetrix_calvin_utilities::AffymetrixGuidType GenericDataHeader::GetFileId () const
Definition at line 60 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::GenericData::ArrayFileIdentifier(), Calvin::equivalentHeader(), affymetrix_fusion_io::CalvinCHPDataAdapter::FileId(), affymetrix_calvin_io::GenericData::FileIdentifier(), affymetrix_fusion_io::CalvinCELDataAdapter::GetFileId(), CNCychp::loadHeader(), Calvin::loadHeader(), QuantMethodMultiDataCCCHPReport::prepare(), QuantMethodExprCCCHPReport::prepare(), and affymetrix_calvin_io::GenericDataHeaderUpdater::UpdateFileId().
std::string GenericDataHeader::GetFileTypeId () const
Definition at line 50 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::CHPData::AddColumns(), CalvinChpCheck::check(), Calvin::equivalentHeader(), affymetrix_calvin_io::CHPData::GetAssayType(), affymetrix_calvin_io::CDFData::GetDataTypeId(), affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets(), affymetrix_fusion_io::FusionCDFFileHeader::GetNumQCProbeSets(), affymetrix_fusion_io::FusionCDFData::GetProbeSetInformation(), affymetrix_fusion_io::FusionCDFData::GetProbeSetType(), affymetrix_fusion_io::FusionCDFData::GetQCProbeSetInformation(), Calvin::loadHeader(), and affymetrix_calvin_io::GenericDataHeaderUpdater::UpdateFileId().
std::wstring GenericDataHeader::GetLocale () const
Definition at line 80 of file GenericDataHeader.cpp.
Referenced by Calvin::equivalentHeader(), and Calvin::loadHeader().
void GenericDataHeader::GetNameValIterators (ParameterNameValueTypeIt & begin, ParameterNameValueTypeIt & end)
Definition at line 133 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::CHPTilingData::GetAlgParams(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetAlgParams(), affymetrix_calvin_io::CHPQuantificationData::GetAlgParams(), affymetrix_calvin_io::CHPMultiDataData::GetAlgParams(), affymetrix_calvin_io::CHPData::GetAlgParams(), affymetrix_calvin_io::CHPData::GetChipSums(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetSummaryParams(), affymetrix_calvin_io::CHPQuantificationData::GetSummaryParams(), affymetrix_calvin_io::CHPMultiDataData::GetSummaryParams(), and affymetrix_calvin_io::GenericDataHeaderUpdater::UpdateParameters().
ParameterNameValueType GenericDataHeader::GetNameValParam (int32_t index)
Definition at line 123 of file GenericDataHeader.cpp.
Referenced by Calvin::equivalentHeader(), CNCychp::loadHeader(), and Calvin::loadHeader().
int32_t GenericDataHeader::GetNameValParamCnt () const
Definition at line 128 of file GenericDataHeader.cpp.
Referenced by Calvin::equivalentHeader(), CNCychp::loadHeader(), and Calvin::loadHeader().
bool GenericDataHeader::GetNameValParamsBeginsWith (const std::wstring & beginsWith, ParameterNameValueTypeVector & p)
Gets all ParameterNameValueType where the name starts with a given string.
Parameters:
beginsWith The string that the beginning of the ParameterNameValueType name needs to match.
p A result vector of ParameterNameValueTypes where the name begins with the beginsWith argument.
Definition at line 203 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::CelFileData::GetAlgorithmParameters().
GenericDataHeader GenericDataHeader::GetParent (int32_t index) const
Definition at line 155 of file GenericDataHeader.cpp.
Referenced by FromHP().
int32_t GenericDataHeader::GetParentCnt () const
Definition at line 150 of file GenericDataHeader.cpp.
Referenced by FromHP().
void affymetrix_calvin_io::GenericDataHeader::GetParentIterators (std::vector< GenericDataHeader >::iterator & begin, std::vector< GenericDataHeader >::iterator & end)
Referenced by FindParent(), affymetrix_cel_converter::CELConversionUtilities::GetDatHeader(), and makeMultiCelFileSubset().
void GenericDataHeader::SetFileCreationTime (const std::wstring & f)
Definition at line 65 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::GenericDataHeaderReader::Read(), CNReporterCnchp::run(), and CNFamilialReporterFamilial::setupHeader().
void GenericDataHeader::SetFileId (const affymetrix_calvin_utilities::AffymetrixGuidType & p)
Definition at line 55 of file GenericDataHeader.cpp.
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::GenerateParentGenericDataHeaderFromGCOS(), affymetrix_calvin_io::GenericDataHeaderReader::Read(), CNReporterCnchp::run(), and affymetrix_calvin_io::GridControlFileWriter::Write().
void GenericDataHeader::SetFileTypeId (const std::string & p)
Definition at line 45 of file GenericDataHeader.cpp.
Referenced by CNFamilialReporterFamilial::addStandardHeader(), affymetrix_calvin_io::CelFileData::CelFileData(), affymetrix_calvin_io::CHPData::CHPData(), affymetrix_calvin_io::CHPMultiDataData::CHPMultiDataData(), affymetrix_calvin_io::CHPQuantificationData::CHPQuantificationData(), affymetrix_calvin_io::CHPQuantificationDetectionData::CHPQuantificationDetectionData(), affymetrix_calvin_io::CHPTilingData::CHPTilingData(), ConverterCreateAndAddParentArrayGenericDataHeader(), affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile(), affymetrix_calvin_io::DATData::DATData(), affymetrix_cel_converter::CELFileConvertToCalvin::GenerateParentGenericDataHeaderFromGCOS(), affymetrix_calvin_io::DATData::GetParentArrayGenericDataHeader(), affymetrix_calvin_io::GenericDataHeaderReader::Read(), CNReporterCnchp::run(), and affymetrix_calvin_io::GridControlFileWriter::Write().
void GenericDataHeader::SetLocale (const std::wstring & p)
Definition at line 75 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::GenericDataHeaderReader::Read().
The documentation for this class was generated from the following files:
calvin_files/data/src/GenericDataHeader.h
calvin_files/data/src/GenericDataHeader.cpp