Affymetrix Power Tools: affxdat::CDATFileData Class Reference
affxdat::CDATFileData Class Reference
#include <DATFileData.h>
Public Member Functions
CDATFileData ()
~CDATFileData ()
void SetFileName (const char *str)
std::string GetFileName () const
CDATFileHeaderData & GetHeader ()
void GetPixels (int rowIndex, uint16_t *pixels)
void GetPixels (int rowIndex, int rowCount, uint16_t *pixels)
uint16_t GetPixel (int x, int y)
bool Exists ()
bool Read ()
void Close ()
Static Public Member Functions
static bool UpdateGridCorners (const char *datFile, const GridCoordinatesType &grid)
static bool IsGCOSDATFile (const char *datFile)
Protected Attributes
std::string m_FileName
CDATFileHeaderData m_HeaderData
std::ifstream m_File
Detailed Description
This class provides parsing and access interfaces to a GCOS DAT file.
Definition at line 156 of file DATFileData.h.
Constructor & Destructor Documentation
CDATFileData::CDATFileData ()
Constructor
Definition at line 225 of file DATFileData.cpp.
CDATFileData::~CDATFileData ()
Destructor
Definition at line 231 of file DATFileData.cpp.
References Close().
Member Function Documentation
void CDATFileData::Close (void)
Closes the file when finished accessing it.
Definition at line 238 of file DATFileData.cpp.
References m_File.
Referenced by Read(), and ~CDATFileData().
bool CDATFileData::Exists ()
Checks if the file exists.
Returns:
True if exists.
Definition at line 68 of file DATFileData.cpp.
References m_FileName.
std::string affxdat::CDATFileData::GetFileName () const [inline]
Gets the full path of the DAT file.
Returns:
The full path of the DAT file.
Definition at line 184 of file DATFileData.h.
References m_FileName.
CDATFileHeaderData& affxdat::CDATFileData::GetHeader () [inline]
Gets the DAT file header object.
Returns:
The header.
Definition at line 189 of file DATFileData.h.
References m_HeaderData.
uint16_t CDATFileData::GetPixel (int x, int y)
Gets a single pixel value.
Parameters:
x The x coordinate.
y The y coordinate.
Returns:
The pixel value at the coordinate.
Definition at line 181 of file DATFileData.cpp.
References affxdat::CDATFileHeaderData::GetCols(), m_File, and m_HeaderData.
void CDATFileData::GetPixels (int rowIndex, uint16_t * pixels)
Gets row of data.
Parameters:
rowIndex The index to the row to extract.
pixels An array to store the pixel data.
Definition at line 192 of file DATFileData.cpp.
References affxdat::CDATFileHeaderData::GetCols(), m_File, and m_HeaderData.
void CDATFileData::GetPixels (int rowIndex, int rowCount, uint16_t * pixels)
Gets row of data.
Parameters:
rowIndex The index to the row to extract.
rowCount The number of rows to extract.
pixels An array to store the pixel data.
Definition at line 208 of file DATFileData.cpp.
References affxdat::CDATFileHeaderData::GetCols(), m_File, and m_HeaderData.
bool CDATFileData::IsGCOSDATFile (const char * datFile) [static]
Determines if the file is a GCOS DAT file.
Parameters:
datFile The full path name of the DAT file to update.
Returns:
True if the file is a GCOS DAT file.
Definition at line 246 of file DATFileData.cpp.
Referenced by UpdateGridCorners().
bool CDATFileData::Read ()
Reads the file.
Returns:
True if successful.
Definition at line 77 of file DATFileData.cpp.
References Close(), _GridCoordinatesType::lowerleft, _GridCoordinatesType::lowerright, m_File, m_FileName, m_HeaderData, affxdat::CDATFileHeaderData::SetArrayType(), affxdat::CDATFileHeaderData::SetCols(), affxdat::CDATFileHeaderData::SetGridCorners(), affxdat::CDATFileHeaderData::SetMaxValue(), affxdat::CDATFileHeaderData::SetMinValue(), affxdat::CDATFileHeaderData::SetRows(), affxdat::CDATFileHeaderData::SetScannerID(), _GridCoordinatesType::upperleft, _GridCoordinatesType::upperright, _CoordinatePoint::x, and _CoordinatePoint::y.
void affxdat::CDATFileData::SetFileName (const char * str) [inline]
Sets the full path of the DAT file.
Parameters:
str The full path of the DAT file.
Definition at line 179 of file DATFileData.h.
References m_FileName.
bool CDATFileData::UpdateGridCorners (const char * datFile, const GridCoordinatesType & grid) [static]
Update the grid coordinates in a DAT file.
Parameters:
datFile The full path name of the DAT file to update.
grid The new grid coordinates.
Returns:
True if successful.
Definition at line 258 of file DATFileData.cpp.
References IsGCOSDATFile(), _GridCoordinatesType::lowerleft, _GridCoordinatesType::lowerright, _GridCoordinatesType::upperleft, _GridCoordinatesType::upperright, _CoordinatePoint::x, and _CoordinatePoint::y.
Member Data Documentation
std::ifstream affxdat::CDATFileData::m_File [protected]
The file handle.
Definition at line 173 of file DATFileData.h.
Referenced by Close(), GetPixel(), GetPixels(), and Read().
std::string affxdat::CDATFileData::m_FileName [protected]
The full path of the DAT file.
Definition at line 167 of file DATFileData.h.
Referenced by Exists(), GetFileName(), Read(), and SetFileName().
CDATFileHeaderData affxdat::CDATFileData::m_HeaderData [protected]
The DAT file header
Definition at line 170 of file DATFileData.h.
Referenced by GetHeader(), GetPixel(), GetPixels(), and Read().
The documentation for this class was generated from the following files:
file/DATFileData.h
file/DATFileData.cpp