Affymetrix Power Tools: QuantGTypeMethod Class Reference
QuantGTypeMethod Class Reference
Quantification methods used for making genotyping calls implement (currently just brlmm) this interface.
#include <QuantGTypeMethod.h>