Affymetrix Power Tools: QuantExprMethod Class Reference
QuantExprMethod Class Reference
QuantExprMethod - Interface for computing quantification summaries from PM intensities grouped into probe set groups.
#include <QuantExprMethod.h>