Affymetrix Power Tools: SgIoHelper Class Reference
SgIoHelper Class Reference
Class to wrap up the complexity of the different possible input files to SummaryGenotypeEngine.
#include <SummaryGenotypeEngine.h>
Public Member Functions
SgIoHelper (const std::string &summariesFile, const std::string &summariesFileA, const std::string &summariesFileB, const std::string &file5, const std::string &file5Group)
Constructor.
~SgIoHelper ()
Destructor.
void getLine (std::string &label, std::vector< double > &vals, affx::TsvFile &summaries, std::vector< std::string > &colNames)
Read in a single line from out summaries file and fill label and values.
void getFile5Line (std::string &label, std::vector< double > &vals, affx::File5_Tsv *summaries, std::vector< std::string > &colNames)
Read in a single line from out summaries file5 and fill label and values.
bool getNextMarkerTsvSingle (std::vector< std::string > &colNames, std::vector< double > &aVals, std::vector< double > &bVals, std::string &probesetName)
Read the next snp marker from the single interleved file5 summary file.
bool getNextMarkerFile5 (std::vector< std::string > &colNames, std::vector< double > &aVals, std::vector< double > &bVals, std::string &probesetName)
Read the next snp marker from the file5.
bool getNextMarkerTwoTsv (std::vector< std::string > &colNames, std::vector< double > &aVals, std::vector< double > &bVals, std::string &probesetName)
Read the next snp marker from the paired summary A & B files.
bool getNextMarker (std::vector< std::string > &colNames, std::vector< double > &aVals, std::vector< double > &bVals, std::string &probesetName)
Read the next snp marker.
std::vector< std::string > getColNames ()
Get the names of the columns in the summary files.
Detailed Description
Class to wrap up the complexity of the different possible input files to SummaryGenotypeEngine.
Definition at line 47 of file SummaryGenotypeEngine.h.
Constructor & Destructor Documentation
SgIoHelper::SgIoHelper (const std::string & summariesFile, const std::string & summariesFileA, const std::string & summariesFileB, const std::string & file5, const std::string & file5Group)
Constructor.
Take a number of files and figure out which one(s) has been set to read from.
Parameters:
summariesFile Text summary file with results interleved.
summariesFileA Text summary file for A alleles
summariesFileB Text summary file for B alleles
file5 File5 version of the summary file above
file5Group Which group the summary file5 is in with name "summaries"
Definition at line 58 of file SummaryGenotypeEngine.cpp.
References affx::TsvFile::cidx2cname(), Err::errAbort(), affx::TsvFile::getColumnCount(), affx::TsvFile::open(), and ToStr().
Member Function Documentation
std::vector<std::string> SgIoHelper::getColNames () [inline]
Get the names of the columns in the summary files.
Returns:
names in order of the columns
Definition at line 147 of file SummaryGenotypeEngine.h.
void SgIoHelper::getFile5Line (std::string & label, std::vector< double > & vals, affx::File5_Tsv * summaries, std::vector< std::string > & colNames)
Read in a single line from out summaries file5 and fill label and values.
Parameters:
label Probesetname to be filled in
vals Values to be filled in
summaries File5 to read next row from
colNames Names of the column in summaries file
Definition at line 156 of file SummaryGenotypeEngine.cpp.
References Err::errAbort(), and ToStr().
Referenced by getNextMarkerFile5().
void SgIoHelper::getLine (std::string & label, std::vector< double > & vals, affx::TsvFile & summaries, std::vector< std::string > & colNames)
Read in a single line from out summaries file and fill label and values.
Parameters:
label Probesetname to be filled in
vals Values to be filled in
summaries File to read next row from
colNames Names of the column in summaries file
Definition at line 142 of file SummaryGenotypeEngine.cpp.
References Err::errAbort(), affx::TsvFile::get(), and ToStr().
Referenced by getNextMarkerTsvSingle(), and getNextMarkerTwoTsv().
bool SgIoHelper::getNextMarker (std::vector< std::string > & colNames, std::vector< double > & aVals, std::vector< double > & bVals, std::string & probesetName)
Read the next snp marker.
Parameters:
colNames Names of the columns in summary file.
aVals Summary values for the A allele
bVals Summary values for the B allele
probesetName Name of probeset
Returns:
true if successful, false otherwise
Definition at line 254 of file SummaryGenotypeEngine.cpp.
References Err::errAbort(), getNextMarkerFile5(), getNextMarkerTsvSingle(), and getNextMarkerTwoTsv().
bool SgIoHelper::getNextMarkerFile5 (std::vector< std::string > & colNames, std::vector< double > & aVals, std::vector< double > & bVals, std::string & probesetName)
Read the next snp marker from the file5.
Parameters:
colNames Names of the columns in summary file.
aVals Summary values for the A allele
bVals Summary values for the B allele
probesetName Name of probeset
Returns:
true if successful, false otherwise
Definition at line 204 of file SummaryGenotypeEngine.cpp.
References Err::errAbort(), and getFile5Line().
Referenced by getNextMarker().
bool SgIoHelper::getNextMarkerTsvSingle (std::vector< std::string > & colNames, std::vector< double > & aVals, std::vector< double > & bVals, std::string & probesetName)
Read the next snp marker from the single interleved file5 summary file.
Parameters:
colNames Names of the columns in summary file.
aVals Summary values for the A allele
bVals Summary values for the B allele
probesetName Name of probeset
Returns:
true if successful, false otherwise
Definition at line 170 of file SummaryGenotypeEngine.cpp.
References Err::errAbort(), getLine(), and affx::TsvFile::nextLevel().
Referenced by getNextMarker().
bool SgIoHelper::getNextMarkerTwoTsv (std::vector< std::string > & colNames, std::vector< double > & aVals, std::vector< double > & bVals, std::string & probesetName)
Read the next snp marker from the paired summary A & B files.
Parameters:
colNames Names of the columns in summary file.
aVals Summary values for the A allele
bVals Summary values for the B allele
probesetName Name of probeset
Returns:
true if successful, false otherwise
Definition at line 238 of file SummaryGenotypeEngine.cpp.
References Err::errAbort(), getLine(), and affx::TsvFile::nextLevel().
Referenced by getNextMarker().
The documentation for this class was generated from the following files:
chipstream/apt-summary-genotype/SummaryGenotypeEngine.h
chipstream/apt-summary-genotype/SummaryGenotypeEngine.cpp