Affymetrix Power Tools: affymetrix_fusion_io::FusionCDFQCProbeSetInformation Class Reference
affymetrix_fusion_io::FusionCDFQCProbeSetInformation Class Reference
#include <FusionCDFData.h>
Public Member Functions
affxcdf::GeneChipQCProbeSetType GetQCProbeSetType () const
int GetNumCells () const
void GetProbeInformation (int index, FusionCDFQCProbeInformation &info)
FusionCDFQCProbeSetInformation ()
~FusionCDFQCProbeSetInformation ()
Friends
class FusionCDFData
Detailed Description
This class provides storage for the probes in a QC probe set.
Definition at line 422 of file FusionCDFData.h.
Constructor & Destructor Documentation
FusionCDFQCProbeSetInformation::FusionCDFQCProbeSetInformation ()
Constructor
Definition at line 329 of file FusionCDFData.cpp.
FusionCDFQCProbeSetInformation::~FusionCDFQCProbeSetInformation ()
Destructor
Definition at line 338 of file FusionCDFData.cpp.
Member Function Documentation
int FusionCDFQCProbeSetInformation::GetNumCells () const
Gets the number of probes in the set.
Returns:
The number of probes in the set.
Definition at line 303 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFQCProbeSetInformation::GetNumCells(), and affxcdf::CCDFQCProbeSetInformation::GetNumCells().
void FusionCDFQCProbeSetInformation::GetProbeInformation (int index, FusionCDFQCProbeInformation & info)
Gets the information about a single probe in the set.
Parameters:
index The index to the probe of interest.
info The information about the probe.
Definition at line 316 of file FusionCDFData.cpp.
affxcdf::GeneChipQCProbeSetType FusionCDFQCProbeSetInformation::GetQCProbeSetType () const
Gets the probe set type.
Returns:
The probe set type.
Definition at line 278 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFQCProbeSetInformation::GetQCProbeSetType(), affxcdf::CCDFQCProbeSetInformation::GetQCProbeSetType(), and affymetrix_fusion_io::FusionCDFQCProbeSetNames::GetStaticCDFQCProbeSetName().
Friends And Related Function Documentation
friend class FusionCDFData [friend]
Friend to the parent class.
Definition at line 459 of file FusionCDFData.h.
The documentation for this class was generated from the following files:
calvin_files/fusion/src/FusionCDFData.h
calvin_files/fusion/src/FusionCDFData.cpp