Affymetrix Power Tools: TableReader Class Reference
TableReader Class Reference
IntensityMart object for reading intensity files for text, useful for testing via text files.
#include <TableReader.h>