Affymetrix Power Tools: QCProbesetOptions Class Reference
QCProbesetOptions Class Reference
A simple class which contains various QC probeset information. /// Typically populated from the QCC file.
#include <QCProbesetOptions.h>
Public Types
typedef std::pair< std::string,
std::string > nameLigationBase_t
A map keyed by the groupName(label) of probeset name (or IDs) vector.
Public Member Functions
virtual ~QCProbesetOptions ()
Virtual Destructor.
Static Public Member Functions
static void readQCCFile (const std::string &qccFileName, QCProbesetOptions &opts)
Read in a QCC File and populate a QCProbesetOptions instance.
Public Attributes
bool useNames
Indicates if the primary key is probeset name or ID.
std::map< std::string,
std::vector
< nameLigationBase_t > > probesetGroups
bool m_hasLigationBase
std::vector< std::string > headerProbesets
A vector of probesets flagged for inclusion in CHP header.
std::string m_sketchInFile
std::string m_channelFile
std::string m_exprAnalysisString
std::string m_tempdir
Detailed Description
A simple class which contains various QC probeset information. /// Typically populated from the QCC file.
Definition at line 35 of file QCProbesetOptions.h.
Member Function Documentation
void QCProbesetOptions::readQCCFile (const std::string & qccFileName, QCProbesetOptions & opts) [static]
Read in a QCC File and populate a QCProbesetOptions instance.
Parameters:
qccFileName - the name of the qcc file to load
opts - the QCProbesetOptions instance to populate
Todo:
check that probeset_id was bound
Todo:
AW: This block should go, or otherwise only be executed if the parsing of ligation bases from probeset names was requested.
Definition at line 52 of file QCProbesetOptions.cpp.
References APT_ERR_ABORT, APT_ERR_ASSERT, Util::chopString(), affx::TsvFile::close(), affx::TsvFile::cname2cidx(), Util::endsWithStr(), Err::errAbort(), affx::TsvFile::getError(), affx::TsvFile::getHeader(), headerProbesets, affx::TsvFile::nextLevel(), affx::TsvFile::open(), ToStr(), affx::TSV_BIND_REQUIRED, affx::TSV_ERR_EOF, affx::TSV_ERR_FILEIO, affx::TSV_OK, and useNames.
The documentation for this class was generated from the following files:
chipstream/QCProbesetOptions.h
chipstream/QCProbesetOptions.cpp