Affymetrix Power Tools: CEMEst Class Reference
CEMEst Class Reference
Object to hold all EM posterior information including some classification quality stats.
#include <PrimeEM.h>
Public Member Functions
CEMEst (const int clusters=3)
, the default constructor
void set (const int clusters=3)
set the number of cluters
CEMEst & operator= (const CEMEst &rhs)
assignment operator
Public Attributes
std::vector< double > m_mu
cluster centers
std::vector< double > m_sigma
cluster sigmas
std::vector< double > m_weight
cluster weights
std::vector< double > m_minMu
minimum of cluster centers
std::vector< double > m_maxMu
maximums of cluster centers
std::vector< double > m_minSigma
minimums of cluster sigmas
std::vector< double > m_maxSigma
maximums of cluster sigmas
std::vector< bool > m_cluster
number of clusters remaining
std::vector< int > m_class
EM cluster member assignment.
std::vector< double > m_prob
probability to best fit cluster
std::vector< double > m_probRatio
probability ratio, best vs. second best
std::vector< double > m_confidence
genotype confidence
double m_ML
total maximum likelihood
double m_FLD1
Fisher's linear discriminant of the first two clusters.
double m_FLD2
Fisher's linear discriminant of the second two clusters.
double m_sep
separation of the clustering results
Protected Member Functions
void reset (const int dim)
reset the buffer size for posterior information
Friends
class CPrimeEM
Detailed Description
Object to hold all EM posterior information including some classification quality stats.
Definition at line 180 of file PrimeEM.h.
Constructor & Destructor Documentation
CEMEst::CEMEst (const int clusters = 3)
, the default constructor
Parameters:
clusters - number of clusters to cluster data into
Definition at line 344 of file PrimeEM.cpp.
References m_cluster, m_FLD1, m_FLD2, m_maxMu, m_maxSigma, m_minMu, m_minSigma, m_ML, m_mu, m_sep, m_sigma, and m_weight.
Member Function Documentation
void CEMEst::reset (const int dim) [protected]
reset the buffer size for posterior information
Parameters:
dim - dimension of the data to be classified
Definition at line 406 of file PrimeEM.cpp.
References m_class, m_confidence, m_prob, and m_probRatio.
Referenced by CPrimeEM::goPrimeEM(), and CPrimeEM::reset().
void CEMEst::set (const int clusters = 3)
set the number of cluters
Parameters:
clusters - number of clusters to cluster data into
Definition at line 363 of file PrimeEM.cpp.
References m_cluster, m_FLD1, m_FLD2, m_maxMu, m_maxSigma, m_minMu, m_minSigma, m_ML, m_mu, m_sep, m_sigma, and m_weight.
Referenced by CPrimeEM::CPrimeEM(), CPrimeEM::goPrimeEM(), CPrimeEM::setParam(), and CPrimeEM::validate().
The documentation for this class was generated from the following files:
algorithm/em/PrimeEM.h
algorithm/em/PrimeEM.cpp