Affymetrix Power Tools: IdxGroup Class Reference
IdxGroup Class Reference
Public Member Functions
IdxGroup ()
Constructor.
unsigned int addGroup (std::string grouping_name, std::vector< unsigned int > group)
Insert group of indexes into grouping of given name.
int getGroupCount (std::string grouping_name)
Get count of groups with given grouping name.
std::vector< std::vector
< unsigned int > > getGroupingVec (std::string grouping_name)
Get vector of vectors constituting the groups of indexes for given grouping name.
std::vector< unsigned int > getGroup (std::string grouping_name, unsigned int group_idx)
Get group at given index with given grouping name.
std::vector< unsigned int > getGroupContainingIdx (std::string grouping_name, unsigned int idx)
Get group containing given index with given grouping name.
std::vector< unsigned int > getOthersGroupContainingIdx (std::string grouping_name, unsigned int idx)
Get other elements of a group containing given index with given grouping name.
bool groupingNameExists (std::string grouping_name)
Verify that the grouping name exists.
bool groupingNameRequire (std::string grouping_name)
Verify that the grouping name exists.
bool groupIdxRequire (std::string grouping_name, unsigned int group_idx)
Verify that the given group index is valid for the given grouping name.
bool elementIdxRequire (std::string grouping_name, unsigned int idx)
Verify that the given index element has been entered for the given grouping name.
Detailed Description
Definition at line 39 of file IdxGroup.h.
Member Function Documentation
unsigned int IdxGroup::addGroup (std::string grouping_name, std::vector< unsigned int > group)
Insert group of indexes into grouping of given name.
Parameters:
groupname - name/category of grouping
group - integers that belong to a group
groupname - name of grouping
group - integers that belong to a group
Definition at line 50 of file IdxGroup.cpp.
References groupingNameExists(), ToStr(), and Verbose::warn().
Referenced by CelReader::readFiles().
bool IdxGroup::elementIdxRequire (std::string grouping_name, unsigned int idx)
Verify that the given index element has been entered for the given grouping name.
Verify that the given group index is valid for the given grouping name.
Parameters:
groupname - name of grouping
idx - index that is an element of some group
groupname - name of grouping
group_idx - index of group in grouping vector
Definition at line 214 of file IdxGroup.cpp.
References groupingNameRequire(), ToStr(), and Verbose::warn().
Referenced by getGroupContainingIdx(), and getOthersGroupContainingIdx().
std::vector< unsigned int > IdxGroup::getGroup (std::string grouping_name, unsigned int group_idx)
Get group at given index with given grouping name.
Parameters:
groupname - name/category of grouping
group_idx - index of group in grouping vector
groupname - name of grouping
group_idx - index of group in grouping vector
Definition at line 118 of file IdxGroup.cpp.
References groupIdxRequire().
std::vector< unsigned int > IdxGroup::getGroupContainingIdx (std::string grouping_name, unsigned int idx)
Get group containing given index with given grouping name.
Get group at given index with given grouping name.
Parameters:
groupname - name/category of grouping
idx - element inside group of interest
groupname - name of grouping
group_idx - index of group in grouping vector Get group containing given index with given grouping name
groupname - name of grouping
idx - element inside group of interest
Definition at line 142 of file IdxGroup.cpp.
References elementIdxRequire().
int IdxGroup::getGroupCount (std::string grouping_name)
Get count of groups with given grouping name.
Parameters:
groupname - name/category of grouping
groupname - name of grouping
Definition at line 91 of file IdxGroup.cpp.
References groupingNameExists().
std::vector< std::vector< unsigned int > > IdxGroup::getGroupingVec (std::string grouping_name)
Get vector of vectors constituting the groups of indexes for given grouping name.
Parameters:
groupname - name/category of grouping
groupname - name of grouping
Definition at line 103 of file IdxGroup.cpp.
References groupingNameRequire().
Referenced by SparseMart::setChannelMapping(), and DiskIntensityMart::setChannelMapping().
std::vector< unsigned int > IdxGroup::getOthersGroupContainingIdx (std::string grouping_name, unsigned int idx)
Get other elements of a group containing given index with given grouping name.
Parameters:
groupname - name/category of grouping
idx - element inside group of interest
groupname - name of grouping
idx - element inside group of interest
Definition at line 158 of file IdxGroup.cpp.
References elementIdxRequire(), Err::errAbort(), and ToStr().
bool IdxGroup::groupIdxRequire (std::string grouping_name, unsigned int group_idx)
Verify that the given group index is valid for the given grouping name.
Parameters:
groupname - name of grouping
group_idx - index of group in grouping vector
Definition at line 197 of file IdxGroup.cpp.
References groupingNameRequire(), ToStr(), and Verbose::warn().
Referenced by getGroup().
bool IdxGroup::groupingNameRequire (std::string grouping_name)
Verify that the grouping name exists.
Parameters:
groupname - name of grouping
Definition at line 182 of file IdxGroup.cpp.
References Verbose::warn().
Referenced by elementIdxRequire(), getGroupingVec(), and groupIdxRequire().
The documentation for this class was generated from the following files:
chipstream/IdxGroup.h
chipstream/IdxGroup.cpp