Affymetrix Power Tools: affymetrix_fusion_io::FusionCELData Class Reference
affymetrix_fusion_io::FusionCELData Class Reference
#include <FusionCELData.h>
Public Types
enum { CEL_ALL = 1, CEL_DATA = 2, CEL_OUTLIER = 4, CEL_MASK = 8 }
Public Member Functions
FusionCELData ()
~FusionCELData ()
void SetFileName (const char *value)
std::string GetFileName () const
affymetrix_calvin_utilities::AffymetrixGuidType GetFileId () const
void SetError (const wchar_t *value)
std::wstring GetError ()
std::wstring GetHeaderKey (const wchar_t *key)
int GetVersion ()
int GetCols ()
int GetRows ()
int GetNumCells ()
std::wstring GetHeader ()
std::wstring GetAlg ()
std::wstring GetAlgVer ()
std::wstring GetParams ()
std::wstring GetAlgorithmParameter (const wchar_t *tag)
std::wstring GetAlgorithmParameterTag (int index)
int GetNumberAlgorithmParameters ()
std::wstring GetAlgorithmParameters ()
FusionTagValuePairTypeList & GetParameters ()
std::wstring GetDatHeader ()
std::wstring GetChipType ()
std::wstring GetLibraryPackageName ()
std::wstring GetMasterFileName ()
int GetCellMargin ()
unsigned int GetNumOutliers ()
unsigned int GetNumMasked ()
FGridCoords GetGridCorners ()
int IndexToX (int index)
int IndexToY (int index)
int XYToIndex (int x, int y)
void GetEntry (int index, FusionCELFileEntryType &entry)
void GetEntry (int x, int y, FusionCELFileEntryType &entry)
float GetIntensity (int index)
int GetIntensities (int index, std::vector< float > &intensity_vec)
Get a vector of intensities. ///.
float GetIntensity (int x, int y)
float GetStdv (int index)
float GetStdv (int x, int y)
short GetPixels (int index)
short GetPixels (int x, int y)
bool IsMasked (int x, int y)
bool IsMasked (int index)
bool IsOutlier (int x, int y)
bool IsOutlier (int index)
void Close ()
unsigned int GetFileSize ()
bool Exists ()
bool ReadHeader ()
bool Read (bool bIncludeMaskAndOutliers=true)
bool ReadEx (const char *filename=0, int state=CEL_ALL)
int GetReadState ()
void Clear ()
affymetrix_calvin_io::GenericData * GetGenericData ()
affymetrix_calvin_parameter::ParameterNameValueTypeList GetDataSetParameters (const std::wstring &setName)
void SetActiveDataGroup (const std::wstring &groupName)
bool IsMultiColor ()
WStringVector GetChannels ()
Static Public Member Functions
static int XYToIndex (int x, int y, int r, int c)
Protected Member Functions
void CreateAdapter ()
void DeleteAdapter ()
void CheckAdapter () const
void FillParameterList ()
Detailed Description
This defines the combined GCOS/Calvin CEL data interaction class.
Definition at line 36 of file FusionCELData.h.
Member Enumeration Documentation
anonymous enum
CEL file reading states
Definition at line 40 of file FusionCELData.h.
Constructor & Destructor Documentation
FusionCELData::FusionCELData ()
Constructor
Definition at line 44 of file FusionCELData.cpp.
FusionCELData::~FusionCELData ()
Destructor
Definition at line 53 of file FusionCELData.cpp.
References Clear(), and DeleteAdapter().
Member Function Documentation
void FusionCELData::CheckAdapter () const [protected]
Check the adapter and throw exception if not set
Exceptions:
FileNotOpenException
Definition at line 632 of file FusionCELData.cpp.
References affymetrix_calvin_utilities::DateTime::GetCurrentDateTime().
Referenced by GetAlg(), GetAlgorithmParameter(), GetAlgorithmParameters(), GetAlgorithmParameterTag(), GetAlgVer(), GetCellMargin(), GetChannels(), GetChipType(), GetCols(), GetDataSetParameters(), GetDatHeader(), GetEntry(), GetError(), GetFileId(), GetGenericData(), GetGridCorners(), GetHeader(), GetHeaderKey(), GetIntensities(), GetIntensity(), GetLibraryPackageName(), GetMasterFileName(), GetNumberAlgorithmParameters(), GetNumCells(), GetNumMasked(), GetNumOutliers(), GetParameters(), GetParams(), GetPixels(), GetReadState(), GetRows(), GetStdv(), GetVersion(), IndexToX(), IndexToY(), IsMasked(), IsMultiColor(), IsOutlier(), SetActiveDataGroup(), SetError(), and XYToIndex().
void FusionCELData::Clear (void)
Clears the members.
Definition at line 572 of file FusionCELData.cpp.
References affymetrix_fusion_io::IFusionCELDataAdapter::Clear().
Referenced by CRawQWorkflow::Clear(), and ~FusionCELData().
void FusionCELData::Close (void)
Closes the file
Definition at line 481 of file FusionCELData.cpp.
References affymetrix_fusion_io::IFusionCELDataAdapter::Close().
Referenced by CNWorkflowEngine::calculateGenders(), CNCytoEngine::calculateGenders(), CelExtract::CelExtract(), EngineUtil::checkCelChipTypes(), DiskIntensityMart::getProbeCountFromCel(), DataStore::initFromCelFile(), QuantMethodMultiDataCCCHPReport::prepare(), QuantMethodExprCCCHPReport::prepare(), DataStore::readCelFile(), CelReader::readFiles(), and CNReporterCnchp::run().
void FusionCELData::CreateAdapter () [protected]
Factory method to create the appropriate adapter class.
Exceptions:
UnableToOpenFileException
Definition at line 582 of file FusionCELData.cpp.
References affymetrix_fusion_io::IFusionCELDataAdapter::CanReadFile(), DeleteAdapter(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and affymetrix_fusion_io::IFusionCELDataAdapter::SetFileName().
Referenced by Read(), ReadEx(), and ReadHeader().
void FusionCELData::DeleteAdapter () [protected]
Delete the adapter member
Definition at line 623 of file FusionCELData.cpp.
Referenced by CreateAdapter(), and ~FusionCELData().
bool FusionCELData::Exists ()
Check if the file exists.
Returns:
True if the file exists.
Definition at line 498 of file FusionCELData.cpp.
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), Read(), CRawQWorkflow::ReadCELFile(), ReadEx(), ReadHeader(), and affymetrix_chp_converter::CHPFileConvertToCalvin::ValidateMas5File().
void FusionCELData::FillParameterList () [protected]
Definition at line 643 of file FusionCELData.cpp.
References affymetrix_fusion_io::IFusionCELDataAdapter::GetParameters().
Referenced by GetParameters().
std::wstring FusionCELData::GetAlg ()
Retrieve algorithm name
Returns:
Algorithm name
Definition at line 187 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetAlg().
std::wstring FusionCELData::GetAlgorithmParameter (const wchar_t * tag)
Retrieve algorithm parameter of specified tag
Parameters:
tag Algorithm parameter tag
Returns:
Algorithm parameter value
Definition at line 214 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetAlgorithmParameter().
std::wstring FusionCELData::GetAlgorithmParameters ()
Retrieve algorithm parameters
Returns:
Algorithm parameters
Definition at line 241 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetAlgorithmParameters().
std::wstring FusionCELData::GetAlgorithmParameterTag (int index)
Retrieves the algorithm parameter name (tag) for a given index position.
Parameters:
index The zero based index to the parameter array (0 to the number of alg parameters - 1).
Returns:
The parameter name (tag).
Definition at line 223 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetAlgorithmParameterTag().
std::wstring FusionCELData::GetAlgVer ()
Retrieve algorithm version
Returns:
Algorithm version
Definition at line 196 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetAlgVer().
int FusionCELData::GetCellMargin ()
Retrieve cell margin
Returns:
Cell margin
Definition at line 296 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetCellMargin().
WStringVector FusionCELData::GetChannels ()
Returns a list of the channel (ie data group) names
Returns:
list of channel names
Definition at line 668 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetChannels().
Referenced by CelExtract::CelExtract(), EngineUtil::checkCelChipTypes(), DataStore::initFromCelFile(), makeMultiCelFileSubset(), VariabilityScoreCelListener::newChip(), SignalBackgroundCelListener::newChip(), DataStore::newChip(), and CelReader::readFiles().
std::wstring FusionCELData::GetChipType ()
Retrieve chip type
Returns:
Chip type
Definition at line 269 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetChipType().
Referenced by EngineUtil::checkCelChipTypes(), CopyNumberResultWriter::CreateResultFile(), CRawQWorkflow::LoadCDFFile(), and affymetrix_chp_converter::CHPFileConvertToCalvin::ValidateMas5File().
int FusionCELData::GetCols ()
Retrieve number of columns in array
Returns:
Number of columns in array
Definition at line 151 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetCols().
Referenced by CNCytoEngine::calculateGenders(), CelExtract::CelExtract(), EngineUtil::checkCelChipTypes(), DiskIntensityMart::getProbeCountFromCel(), DataStore::initFromCelFile(), DataStore::newChip(), and CelReader::readFiles().
ParameterNameValueTypeList FusionCELData::GetDataSetParameters (const std::wstring & setName)
Returns the list of parameters associated with a data set, empty for GCOS files
Parameters:
setName The data set name
Returns:
The list of parameters
Definition at line 108 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetDataSetParameters().
std::wstring FusionCELData::GetDatHeader ()
Get the DatHeader string.
Returns:
The DatHeader string.
Definition at line 260 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetDatHeader().
Referenced by FromHP().
void FusionCELData::GetEntry (int index, FusionCELFileEntryType & entry)
Retrieve a CEL file entry.
Parameters:
index The index to the CEL file entries.
entry The CEL file entry.
Definition at line 361 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetEntry().
void FusionCELData::GetEntry (int x, int y, FusionCELFileEntryType & entry)
Retrieve a CEL file entry.
Parameters:
x The X coordinate.
y The Y coordinate.
entry The CEL file entry.
Definition at line 370 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetEntry().
std::wstring FusionCELData::GetError ()
Retrieve error string
Returns:
Error string
Definition at line 126 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetError().
Referenced by DiskIntensityMart::getProbeCountFromCel(), DataStore::initFromCelFile(), makeCelFileSubset(), makeMultiCelFileSubset(), DataStore::readCelFile(), and CelReader::readFiles().
AffymetrixGuidType FusionCELData::GetFileId () const
Get the id of the file (only valid for Command Console "calvin" files)
Returns:
The unique file id.
Definition at line 78 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetFileId().
std::string FusionCELData::GetFileName () const
Get the file name.
Returns:
File name
Definition at line 70 of file FusionCELData.cpp.
Referenced by SignalBackgroundCelListener::calcStats(), CnProbeGenderCelListener::callGender(), DiskIntensityMart::getProbeCountFromCel(), MultiChannelNonOverlapCelListener::GimmeContrast(), MultiChannelHomHiLoCelListener::GimmeContrast(), DataStore::initFromCelFile(), makeCelFileSubset(), makeMultiCelFileSubset(), VariabilityScoreCelListener::newChip(), SignalBackgroundCelListener::newChip(), MultiChannelNonOverlapCelListener::newChip(), MultiChannelHomHiLoCelListener::newChip(), KitAOCelListener::newChip(), HomHiLoCelListener::newChip(), EmGenderCelListener::newChip(), DataStore::newChip(), CnProbeGenderCelListener::newChip(), AdjHomHiLoCelListener::newChip(), DataStore::readCelFile(), and CelReader::readFiles().
unsigned int FusionCELData::GetFileSize ()
Returns the file size.
Returns:
The file size.
Definition at line 490 of file FusionCELData.cpp.
References Fs::fileSize().
GenericData * FusionCELData::GetGenericData ()
Returns the GenericData object associated with a Calvin file, NULL for GCOS files.
Definition at line 87 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetGenericData().
Referenced by EngineUtil::checkCelChipTypes(), CopyNumberResultWriter::CreateResultFile(), FromHP(), makeMultiCelFileSubset(), QuantMethodMultiDataCCCHPReport::prepare(), QuantMethodExprCCCHPReport::prepare(), and CNReporterCnchp::run().
affymetrix_fusion_io::FGridCoords FusionCELData::GetGridCorners ()
Get the grid coordinates.
Returns:
Returns the grid coordinates.
Definition at line 323 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetGridCorners().
Referenced by FromHP().
std::wstring FusionCELData::GetHeader ()
Retrieve header in a single string
Returns:
Header string
Definition at line 178 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetHeader().
std::wstring FusionCELData::GetHeaderKey (const wchar_t * key)
Accessors for header information.
Definition at line 132 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetHeaderKey().
int FusionCELData::GetIntensities (int index, std::vector< float > & intensity_vec)
Get a vector of intensities. ///.
Parameters:
index The index of where to start. ///
intensity_vec The vector to fill, its size is the number of intensities.
Definition at line 388 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetIntensities().
Referenced by DataStore::newChip(), and CelReader::readFiles().
float FusionCELData::GetIntensity (int index)
Retrieve a CEL file intensity.
Parameters:
index The index to the CEL file entries.
Returns:
The CEL file intensity.
Definition at line 379 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetIntensity().
Referenced by alleleMedians(), SignalBackgroundCelListener::calcStats(), CNCytoEngine::calculateGenders(), CRawQ::ComputeRawQ(), DmListener::fillInQuartet(), makeCelFileSubset(), and makeMultiCelFileSubset().
float FusionCELData::GetIntensity (int x, int y)
Retrieve a CEL file intensity.
Parameters:
x The X coordinate.
y The Y coordinate.
Returns:
The CEL file intensity.
Definition at line 397 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetIntensity().
std::wstring FusionCELData::GetLibraryPackageName ()
Get the library package
Returns:
library package name (blank for GCOS format CEL files)
Definition at line 278 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetLibraryPackageName().
std::wstring FusionCELData::GetMasterFileName ()
Get the master file
Returns:
master file name (blank for GCOS format CEL files)
Definition at line 287 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetMasterFileName().
int FusionCELData::GetNumberAlgorithmParameters ()
Retrieves the number of algorithm parameters.
Returns:
The number of algorithm parameters.
Definition at line 232 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetNumberAlgorithmParameters().
int FusionCELData::GetNumCells ()
Retrieve number of cells in array
Returns:
Number of cells in array
Definition at line 169 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetNumCells().
Referenced by SignalBackgroundCelListener::calcStats(), EngineUtil::checkCelChipTypes(), makeCelFileSubset(), and makeMultiCelFileSubset().
unsigned int FusionCELData::GetNumMasked ()
Retrieve number of masked cells
Returns:
Number of masked cells
Definition at line 314 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetNumMasked().
unsigned int FusionCELData::GetNumOutliers ()
Retrieve number of outliers
Returns:
Number of outliers
Definition at line 305 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetNumOutliers().
FusionTagValuePairTypeList & FusionCELData::GetParameters ()
Retreive the algorithm parameters in a list.
Returns:
An STL list of algorithm parameters
Definition at line 250 of file FusionCELData.cpp.
References CheckAdapter(), and FillParameterList().
std::wstring FusionCELData::GetParams ()
Retrieve algorithm parameters
Returns:
Algorithm parameters
Definition at line 205 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetParams().
short FusionCELData::GetPixels (int index)
Retrieve a CEL file pixel count.
Parameters:
index The index to the CEL file entries.
Returns:
The CEL file pixel count.
Definition at line 424 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetPixels().
Referenced by CRawQ::ComputeRawQ(), DmListener::fillInQuartet(), makeCelFileSubset(), and makeMultiCelFileSubset().
short FusionCELData::GetPixels (int x, int y)
Retrieve a CEL file pixel count.
Parameters:
x The X coordinate.
y The Y coordinate.
Returns:
The CEL file pixel count.
Definition at line 433 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetPixels().
int FusionCELData::GetReadState ()
Returns the reading state.
Returns:
The reading state.
Definition at line 563 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetReadState().
int FusionCELData::GetRows ()
Retrieve number of rows in array
Returns:
Number of rows in array
Definition at line 160 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetRows().
Referenced by CNCytoEngine::calculateGenders(), CelExtract::CelExtract(), EngineUtil::checkCelChipTypes(), DiskIntensityMart::getProbeCountFromCel(), DataStore::initFromCelFile(), DataStore::newChip(), and CelReader::readFiles().
float FusionCELData::GetStdv (int x, int y)
Retrieve a CEL file stdv value.
Parameters:
x The X coordinate.
y The Y coordinate.
Returns:
The CEL file stdv value.
Definition at line 415 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetStdv().
float FusionCELData::GetStdv (int index)
Retrieve a CEL file stdv value.
Parameters:
index The index to the CEL file entries.
Returns:
The CEL file stdv value.
Definition at line 406 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetStdv().
Referenced by CRawQ::ComputeRawQ(), DmListener::fillInQuartet(), makeCelFileSubset(), and makeMultiCelFileSubset().
int FusionCELData::GetVersion ()
Retrieve CEL file format version number.
Returns:
CEL file format version number
Definition at line 142 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::GetVersion().
int FusionCELData::IndexToX (int index)
Get x coordinates from index
Returns:
X coordinates
Definition at line 333 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::IndexToX().
int FusionCELData::IndexToY (int index)
Get y coordinates from index
Returns:
Y coordinates
Definition at line 342 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::IndexToY().
bool FusionCELData::IsMasked (int index)
Retrieve a CEL file mask flag.
Parameters:
index The index to the CEL file entries.
Returns:
True if the feature is masked.
Definition at line 452 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::IsMasked().
bool FusionCELData::IsMasked (int x, int y)
Retrieve a CEL file mask flag.
Parameters:
x The X coordinate.
y The Y coordinate.
Returns:
True if the feature is masked.
Definition at line 443 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::IsMasked().
bool FusionCELData::IsMultiColor ()
Is this a multi-color CEL file?
Returns:
True if it is multi-color
Definition at line 660 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::IsMultiColor().
bool FusionCELData::IsOutlier (int x, int y)
Retrieve a CEL file outlier flag.
Parameters:
x The X coordinate.
y The Y coordinate.
Returns:
True if the feature is an outlier.
Definition at line 461 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::IsOutlier().
bool FusionCELData::IsOutlier (int index)
Retrieve a CEL file outlier flag.
Parameters:
index The index to the CEL file entries.
Returns:
True if the feature is an outlier.
Definition at line 470 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::IsOutlier().
bool FusionCELData::Read (bool bIncludeMaskAndOutliers = true)
Reads the CEL file.
Parameters:
bIncludeMaskAndOutliers Flag to indicate if the mask and outlier sections should also be read.
Returns:
True if successful.
Definition at line 526 of file FusionCELData.cpp.
References CreateAdapter(), Exists(), and affymetrix_fusion_io::IFusionCELDataAdapter::Read().
Referenced by CNWorkflowEngine::calculateGenders(), CNCytoEngine::calculateGenders(), affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), DiskIntensityMart::getProbeCountFromCel(), makeCelFileSubset(), makeMultiCelFileSubset(), CRawQWorkflow::ReadCELFile(), DataStore::readCelFile(), and CelReader::readFiles().
bool FusionCELData::ReadEx (const char * filename = 0, int state = CEL_ALL)
Determine CEL file format and call appropriate function to read file using the specified file name.
Parameters:
filename The name of the file.
state Reading state
Returns:
bool true if success, false if fail
state can be one or combination of the following values: CEL_ALL Read all information in file (default) CEL_DATA Read header and intensities only CEL_OUTLIER Read header, intensities and outliers CEL_MASK Read header, intensities and masked cells
Definition at line 544 of file FusionCELData.cpp.
References CreateAdapter(), Exists(), and affymetrix_fusion_io::IFusionCELDataAdapter::ReadEx().
bool FusionCELData::ReadHeader ()
Reads the header of the CEL file.
Returns:
True if successful.
Definition at line 508 of file FusionCELData.cpp.
References CreateAdapter(), Exists(), and affymetrix_fusion_io::IFusionCELDataAdapter::ReadHeader().
Referenced by CelExtract::CelExtract(), EngineUtil::checkCelChipTypes(), DataStore::initFromCelFile(), QuantMethodMultiDataCCCHPReport::prepare(), QuantMethodExprCCCHPReport::prepare(), CNReporterCnchp::run(), and affymetrix_chp_converter::CHPFileConvertToCalvin::ValidateMas5File().
void FusionCELData::SetActiveDataGroup (const std::wstring & groupName)
Sets the active data group for a multi-group CEL file. Default is the first group.
Definition at line 653 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::SetActiveDataGroup().
Referenced by EngineUtil::checkCelChipTypes(), makeMultiCelFileSubset(), VariabilityScoreCelListener::newChip(), SignalBackgroundCelListener::newChip(), DataStore::newChip(), and CelReader::readFiles().
void FusionCELData::SetError (const wchar_t * value)
Set the error string.
Parameters:
value The error.
Definition at line 117 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::SetError().
void FusionCELData::SetFileName (const char * value)
Set the file name. @ value The file name. Can have the full path or relative path
Definition at line 62 of file FusionCELData.cpp.
Referenced by CNWorkflowEngine::calculateGenders(), CNCytoEngine::calculateGenders(), CelExtract::CelExtract(), EngineUtil::checkCelChipTypes(), affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), DiskIntensityMart::getProbeCountFromCel(), DataStore::initFromCelFile(), makeCelFileSubset(), makeMultiCelFileSubset(), QuantMethodMultiDataCCCHPReport::prepare(), QuantMethodExprCCCHPReport::prepare(), CRawQWorkflow::ReadCELFile(), DataStore::readCelFile(), CelReader::readFiles(), CNReporterCnchp::run(), and affymetrix_chp_converter::CHPFileConvertToCalvin::ValidateMas5File().
int FusionCELData::XYToIndex (int x, int y, int r, int c) [static]
Maps X/Y coordinates to CEL file index.
Parameters:
x The x coordinate.
y The y coordinate.
r The number of rows.
c The number of columns.
Returns:
The index to the intensity arrays.
Definition at line 100 of file FusionCELData.cpp.
int FusionCELData::XYToIndex (int x, int y)
Convert x, y coordinates to index
Returns:
Index
Definition at line 351 of file FusionCELData.cpp.
References CheckAdapter(), and affymetrix_fusion_io::IFusionCELDataAdapter::XYToIndex().
Referenced by CRawQ::ComputeRawQ(), and ChipLayout::fillInKillList().
The documentation for this class was generated from the following files:
calvin_files/fusion/src/FusionCELData.h
calvin_files/fusion/src/FusionCELData.cpp