Affymetrix Power Tools: affymetrix_cel_converter::CELConversionUtilities Class Reference
affymetrix_cel_converter::CELConversionUtilities Class Reference
#include <CELConversionUtilities.h>
Static Public Member Functions
static GridCoordinatesType GetGrid (affymetrix_calvin_io::CelFileData &inFile)
static std::string GetDatHeader (affymetrix_calvin_io::CelFileData &inFile)
static bool Copy (affymetrix_calvin_io::CelFileData &inFile, affxcel::CCELFileData &outFile, CELFileConversionOptions *options=NULL)
static bool Copy (affxcel::CCELFileData &inFile, affxcel::CCELFileData &outFile, CELFileConversionOptions *options=NULL)
static void SetCellMargin (affymetrix_calvin_io::CelFileData &inFile, affxcel::CCELFileData &outFile, int defaultValue)
static void FindAndAddAlgorithmParameter (std::string name, std::string defaultValue, affymetrix_calvin_io::CelFileData &inFile, affxcel::CCELFileData &outFile)
Detailed Description
This class will convert a CEL file from GCOS to Calvin format.
Definition at line 39 of file CELConversionUtilities.h.
Member Function Documentation
bool CELConversionUtilities::Copy (affymetrix_calvin_io::CelFileData & inFile, affxcel::CCELFileData & outFile, CELFileConversionOptions * options = NULL) [static]
Copies the calvin object to the GCOS object.
Parameters:
inFile The Calvin CEL file object.
outFile The GCOS CEL file object.
Definition at line 143 of file CELConversionUtilities.cpp.
References affxcel::CCELFileData::AddAlgorithmParameter(), FindAndAddAlgorithmParameter(), affymetrix_calvin_io::CelFileData::GetAlgorithmParameters(), affymetrix_calvin_io::CelFileData::GetArrayType(), affymetrix_calvin_io::CelFileData::GetCols(), GetDatHeader(), GetGrid(), affxcel::CCELFileHeaderData::GetHeader(), affxcel::CCELFileData::GetHeader(), affymetrix_calvin_io::CelFileData::GetIntensities(), affymetrix_calvin_io::CelFileData::GetMaskedCoords(), affymetrix_calvin_io::CelFileData::GetNumCells(), affymetrix_calvin_io::CelFileData::GetNumPixels(), affymetrix_calvin_io::CelFileData::GetOutlierCoords(), affymetrix_calvin_io::CelFileData::GetRows(), affymetrix_calvin_io::CelFileData::GetStdev(), affymetrix_cel_converter::CELFileConversionOptions::m_ChipType, affymetrix_cel_converter::CELFileConversionOptions::m_DATFileName, affxcel::CCELFileData::SetAlgorithmName(), SetCellMargin(), affxcel::CCELFileData::SetChipType(), affxcel::CCELFileHeaderData::SetDatHeader(), affxcel::CCELFileData::SetDimensions(), affxcel::CCELFileData::SetGridCorners(), affxcel::CCELFileHeaderData::SetHeader(), affxcel::CCELFileData::SetIntensity(), affxcel::CCELFileData::SetMask(), affxcel::CCELFileData::SetOutlier(), affxcel::CCELFileData::SetPixels(), and affxcel::CCELFileData::SetStdv().
Referenced by affymetrix_cel_converter::CELFileConvertToXDA::ConvertASCIIFile(), affymetrix_cel_converter::CELFileConvertToXDA::ConvertCalvinFile(), affymetrix_cel_converter::CELFileConvertToASCII::ConvertCalvinFile(), and affymetrix_cel_converter::CELFileConvertToASCII::ConvertXDAFile().
bool CELConversionUtilities::Copy (affxcel::CCELFileData & inFile, affxcel::CCELFileData & outFile, CELFileConversionOptions * options = NULL) [static]
Copies a GCOS CEL object to another GCOS CEL object.
Parameters:
inFile The GCOS CEL file object to copy.
outFile The resulting GCOS CEL file object.
Definition at line 257 of file CELConversionUtilities.cpp.
References affxcel::CCELFileData::AddAlgorithmParameter(), affxcel::CCELFileData::GetAlg(), affxcel::CCELFileData::GetAlgorithmParameter(), affxcel::CCELFileData::GetAlgorithmParameterTag(), affxcel::CCELFileData::GetChipType(), affxcel::CCELFileData::GetCols(), affxcel::CCELFileHeaderData::GetDatHeader(), affxcel::CCELFileData::GetGridCorners(), affxcel::CCELFileHeaderData::GetHeader(), affxcel::CCELFileData::GetHeader(), affxcel::CCELFileData::GetIntensity(), affxcel::CCELFileData::GetNumberAlgorithmParameters(), affxcel::CCELFileData::GetNumCells(), affxcel::CCELFileData::GetPixels(), affxcel::CCELFileData::GetRows(), affxcel::CCELFileData::GetStdv(), affxcel::CCELFileData::IsMasked(), affxcel::CCELFileData::IsOutlier(), affymetrix_cel_converter::CELFileConversionOptions::m_ChipType, affymetrix_cel_converter::CELFileConversionOptions::m_DATFileName, affxcel::CCELFileData::SetAlgorithmName(), affxcel::CCELFileData::SetChipType(), affxcel::CCELFileHeaderData::SetDatHeader(), affxcel::CCELFileData::SetDimensions(), affxcel::CCELFileData::SetGridCorners(), affxcel::CCELFileHeaderData::SetHeader(), affxcel::CCELFileData::SetIntensity(), affxcel::CCELFileData::SetMask(), affxcel::CCELFileData::SetOutlier(), affxcel::CCELFileData::SetPixels(), and affxcel::CCELFileData::SetStdv().
void CELConversionUtilities::FindAndAddAlgorithmParameter (std::string name, std::string defaultValue, affymetrix_calvin_io::CelFileData & inFile, affxcel::CCELFileData & outFile) [static]
Finds the algorithm parameter value in the inFile and sets the value to the outFile algorithm parameters. If the value is not found in inFile, then the default value is written to the outFile.
Parameters:
name The name of the parameter to find in the inFile.
defaultValue The value to use if the parameter is not found in inFile.
inFile The Calvin CEL file ojbect.
outFile The resulting GCOS CEL object.
Definition at line 338 of file CELConversionUtilities.cpp.
References affxcel::CCELFileData::AddAlgorithmParameter(), affymetrix_calvin_io::CelFileData::FindAlgorithmParameter(), and affymetrix_calvin_parameter::ParameterNameValueType::ToString().
Referenced by Copy().
string CELConversionUtilities::GetDatHeader (affymetrix_calvin_io::CelFileData & inFile) [static]
Gets the Dat header from the calvin data object.
Parameters:
inFile The Calvin CEL file object.
Returns:
The Dat header string.
Definition at line 85 of file CELConversionUtilities.cpp.
References DAT_HEADER_PARAM_NAME, FormatString2, affymetrix_calvin_io::CelFileData::GetFileHeader(), affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_io::GenericDataHeader::GetParentIterators(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), MAX_PIXEL_INTENSITY_PARAM_NAME, MIN_PIXEL_INTENSITY_PARAM_NAME, and PARTIAL_DAT_HEADER_PARAM_NAME.
Referenced by Copy().
GridCoordinatesType CELConversionUtilities::GetGrid (affymetrix_calvin_io::CelFileData & inFile) [static]
Gets the grid coordinates from the calvin data object.
Parameters:
inFile The Calvin CEL file object.
Returns:
The grid coordinates.
Definition at line 45 of file CELConversionUtilities.cpp.
References affymetrix_calvin_io::CelFileData::FindAlgorithmParameter(), affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), GRIDLLX_PARAM_NAME, GRIDLLY_PARAM_NAME, GRIDLRX_PARAM_NAME, GRIDLRY_PARAM_NAME, GRIDULX_PARAM_NAME, GRIDULY_PARAM_NAME, GRIDURX_PARAM_NAME, GRIDURY_PARAM_NAME, _GridCoordinatesType::lowerleft, _GridCoordinatesType::lowerright, _GridCoordinatesType::upperleft, _GridCoordinatesType::upperright, _CoordinatePoint::x, and _CoordinatePoint::y.
Referenced by Copy().
void CELConversionUtilities::SetCellMargin (affymetrix_calvin_io::CelFileData & inFile, affxcel::CCELFileData & outFile, int defaultValue) [static]
Sets the cell margin in the outFile. It converts the parameter is required.
Parameters:
inFile The GCOS CEL file holding the CellMargin value.
outFile The GCOS CEL file object to which the cell margin is set.
defaultValue The cell margin value to write if the value is not found in inFile.
Definition at line 318 of file CELConversionUtilities.cpp.
References affymetrix_calvin_io::CelFileData::FindAlgorithmParameter(), affxcel::CCELFileData::GetHeader(), affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), and affxcel::CCELFileHeaderData::SetMargin().
Referenced by Copy().
The documentation for this class was generated from the following files:
calvin_files/converters/cel/src/CELConversionUtilities.h
calvin_files/converters/cel/src/CELConversionUtilities.cpp