Affymetrix Power Tools: CPrimeEM Class Reference
CPrimeEM Class Reference
The primary class to hold all EM operations.
#include <PrimeEM.h>
Public Member Functions
CPrimeEM ()
default constructor
bool generateEmpiricalEMSeeds ()
generate variable number of EM seeds based on some prior information this function is designed specifically for 3-clusters scenario, hence only works if three-clusters is specified, otherwise return false and do nothing
bool goPrimeEM ()
The function to run EM for genotyping, function only works for three cluster cases.
bool EMEstimate (CEMSeed &seed)
the function to get EM's estimate with a specific initial seed
CEMEst * getEMEstimates ()
get to posterior
std::vector< CEMSeed > getSeeds ()
get seeds generated by generateEmpiricalEMSeeds()
bool reset (const int dim)
reset the data dimension
void setData (const std::vector< double > &x)
set the data to be classified
void setPrior (const CEMPrior &prior)
set the prior information
void setParam (const CEMParam &param)
set EM parameters
bool checkPrior ()
check integrety of settings
void setThreshold (const double thresh)
confidence threshold set function, for backward compatibility
bool doEstep (bool final=false)
the Expectation step of EM algorithm
bool doMstep ()
the Maximization step of EM algorithm
bool checkStatus (const int it)
check the convergence status
bool computeOptimalEstimates ()
compute all posterior estimates
bool evaluateEstimates (CEMEst &bestEst)
compare the current estimates to the best by far
bool useInitialEstimate (CEMSeed &seed)
roll back to the initial values
bool updateMu ()
update cluster centers
bool updateSigma ()
update cluster variances
bool updateWeight ()
update cluster weights
bool adjustMu ()
adjust cluster centers according to constraints
bool adjustSigma ()
adjust cluster variances according to constraints
bool validate (CEMSeed &seed)
validate and adjust seed according to constraints
void initializeTypeLikelihoodPair (std::vector< std::pair< double, int > > &typeLikelihoodPair)
initialize the type and likelihood pair vector, assign likelihood to infinity
void assignLogLikelihood (std::vector< std::pair< double, int > > &typeLikelihoodPair, const int i)
assign likelihood to each cluster for data point i
void computeFLD ()
compute Fisher's Linear discrimants only computed if clusters are 2 or three
void assignClassAndConfidence (const int i, std::vector< std::pair< double, int > > &typeLikelihoodPair)
assign class membership and associated confidence to data point i
void adjustClassAndConfidence (const int i)
adjust class membership and associated confidence to data point i
Public Attributes
std::vector< double > m_data
the data to be classified
std::vector< std::vector
< double > > m_p
container of probabilities
std::vector< std::vector
< double > > m_np
container of normalized probabilities
std::vector< double > m_clusterP
container of total cluster probabilities
std::vector< double > m_clusterNP
container of total cluster normalized probabilities
double m_sumNP
container of total probabilities
CEMEst m_est
current estimates
CEMSeed * m_pSeed
pointer to the current seed in use
Protected Attributes
int m_nDim
number of data points
double m_lamda
parameter to the scale of FLD penalty of a classification, calculated from m_nDim on the fly
std::vector< CEMSeed > m_seeds
container to hold all EM seeds
CEMPrior m_prior
the generic prior, kept in the level to be adjustable case specific intead of generic
CEMParam m_param
EM parameters.
CEMEst m_preEst
best estimates so far
Detailed Description
The primary class to hold all EM operations.
Definition at line 385 of file PrimeEM.h.
Constructor & Destructor Documentation
CPrimeEM::CPrimeEM ()
default constructor
Parameters:
clusters - number of clusters
Definition at line 581 of file PrimeEM.cpp.
References CEMPrior::initialize(), m_clusterNP, m_clusterP, m_est, CEMParam::m_nClusters, m_nDim, m_param, m_prior, m_pSeed, m_sumNP, CEMPrior::set(), and CEMEst::set().
Member Function Documentation
void CPrimeEM::adjustClassAndConfidence (const int i)
adjust class membership and associated confidence to data point i
Parameters:
i - data point index
Returns:
void
Definition at line 988 of file PrimeEM.cpp.
References CEMEst::m_class, CEMEst::m_cluster, CEMEst::m_confidence, m_est, m_param, CEMEst::m_prob, CEMEst::m_probRatio, and CEMParam::m_threshold.
Referenced by assignClassAndConfidence().
bool CPrimeEM::adjustMu ()
adjust cluster centers according to constraints
Returns:
true if no error, false otherwise
Definition at line 1272 of file PrimeEM.cpp.
References CEMEst::m_cluster, m_est, CEMEst::m_maxMu, CEMEst::m_maxSigma, CEMEst::m_minMu, CEMEst::m_minSigma, CEMEst::m_mu, CEMParam::m_nClusters, m_param, and CEMEst::m_sigma.
Referenced by doMstep().
bool CPrimeEM::adjustSigma ()
adjust cluster variances according to constraints
Returns:
true if no error, false otherwise
Definition at line 1297 of file PrimeEM.cpp.
References CEMEst::m_cluster, m_est, CEMParam::m_HetReductionCoef, CEMParam::m_HomReductionCoef, CEMEst::m_maxSigma, CEMSeed::m_maxSigma, CEMEst::m_minSigma, CEMSeed::m_minSigma, CEMEst::m_mu, CEMParam::m_nClusters, m_param, m_pSeed, CEMEst::m_sigma, CEMParam::m_SigmaPower, and CEMEst::m_weight.
Referenced by doMstep().
void CPrimeEM::assignClassAndConfidence (const int i, std::vector< std::pair< double, int > > & typeLikelihoodPair)
assign class membership and associated confidence to data point i
Parameters:
typeLikelihoodPair - the type and likelihood pair container
i - data point index
Returns:
void
Definition at line 1014 of file PrimeEM.cpp.
References adjustClassAndConfidence(), calcGaussianWithExpTail(), calcProbability(), INF, CEMEst::m_class, CEMEst::m_cluster, m_data, m_est, CEMParam::m_factor, CEMEst::m_ML, CEMEst::m_mu, m_np, m_param, CEMEst::m_prob, CEMEst::m_probRatio, CEMEst::m_sigma, CEMParam::m_tailCut, CEMEst::m_weight, and MAX_DOUBLE.
Referenced by computeOptimalEstimates().
void CPrimeEM::assignLogLikelihood (std::vector< std::pair< double, int > > & typeLikelihoodPair, const int i)
assign likelihood to each cluster for data point i
Parameters:
typeLikelihoodPair - the type and likelihood pair container
i - data point index
Returns:
void
Definition at line 915 of file PrimeEM.cpp.
References CEMEst::m_cluster, m_est, CEMParam::m_nClusters, m_np, and m_param.
Referenced by computeOptimalEstimates().
bool CPrimeEM::checkPrior ()
check integrety of settings
Returns:
true if settings are valid and consistent, false otherwise
Definition at line 622 of file PrimeEM.cpp.
References CEMPrior::m_mu, CEMPrior::m_muSD, CEMParam::m_nClusters, m_param, m_prior, CEMPrior::m_sigma, CEMPrior::m_sigmaSD, and CEMPrior::setStatus().
Referenced by goPrimeEM().
bool CPrimeEM::checkStatus (const int it)
check the convergence status
Parameters:
it - current iteration
Returns:
true if not converged, false otherwise
Definition at line 870 of file PrimeEM.cpp.
References CEMEst::m_cluster, m_est, CEMParam::m_fTolerance, CEMEst::m_mu, CEMParam::m_nClusters, m_param, m_preEst, CEMEst::m_sigma, and CEMEst::m_weight.
Referenced by EMEstimate().
void CPrimeEM::computeFLD ()
compute Fisher's Linear discrimants only computed if clusters are 2 or three
Parameters:
FLD1 - FLD for the first two clusters
FLD2 - FLD for the second two clusters
Returns:
void
Definition at line 942 of file PrimeEM.cpp.
References CEMEst::m_cluster, m_est, CEMEst::m_FLD1, CEMEst::m_FLD2, CEMEst::m_mu, CEMParam::m_nClusters, m_param, CEMEst::m_sep, CEMEst::m_sigma, and NA.
Referenced by EMEstimate(), and useInitialEstimate().
bool CPrimeEM::computeOptimalEstimates ()
compute all posterior estimates
Returns:
true if no error, false otherwise
Definition at line 1086 of file PrimeEM.cpp.
References assignClassAndConfidence(), assignLogLikelihood(), initializeTypeLikelihoodPair(), CEMEst::m_cluster, m_est, CEMEst::m_ML, CEMParam::m_nClusters, m_nDim, and m_param.
Referenced by EMEstimate(), and useInitialEstimate().
bool CPrimeEM::doEstep (bool final = false)
the Expectation step of EM algorithm
Parameters:
final - flag to indicate it's step to calculate posterior
Returns:
true if no error, false otherwise
Definition at line 777 of file PrimeEM.cpp.
References calcProbability(), CEMEst::m_cluster, CEMParam::m_clusterDropThres, m_clusterNP, m_data, m_est, CEMEst::m_mu, CEMParam::m_nClusters, m_nDim, m_np, m_p, m_param, CEMEst::m_sigma, m_sumNP, CEMParam::m_tailCut, CEMParam::m_useWeight, and CEMEst::m_weight.
Referenced by EMEstimate(), and useInitialEstimate().
bool CPrimeEM::doMstep ()
the Maximization step of EM algorithm
Returns:
true if no error, false otherwise
Definition at line 845 of file PrimeEM.cpp.
References adjustMu(), adjustSigma(), updateMu(), updateSigma(), and updateWeight().
Referenced by EMEstimate().
bool CPrimeEM::EMEstimate (CEMSeed & seed)
the function to get EM's estimate with a specific initial seed
Start EM from the initial seed to get estimates for a given data set, all the posterior information will be calculated.
Parameters:
seed - the specific initial seed
Returns:
true if there is no error, false otherwise
Parameters:
seed - the initial seed for EM to start with
Returns:
true if no error, false otherwise
Definition at line 735 of file PrimeEM.cpp.
References checkStatus(), computeFLD(), computeOptimalEstimates(), doEstep(), doMstep(), m_est, CEMEst::m_FLD1, CEMEst::m_FLD2, CEMParam::m_nMaxIter, m_param, m_preEst, m_pSeed, and validate().
Referenced by EmGenderCelListener::CallGender(), MultiChannelHomHiLoCelListener::computeClusterPeaks(), HomHiLoCelListener::computeClusterPeaks(), goPrimeEM(), and t_CallEMGender().
bool CPrimeEM::evaluateEstimates (CEMEst & bestEst)
compare the current estimates to the best by far
Parameters:
bestEst - best estimates so far
Returns:
true if current is better
Definition at line 1120 of file PrimeEM.cpp.
References CEMEst::m_cluster, m_est, m_lamda, CEMParam::m_lossFunction, CEMEst::m_ML, m_param, and CEMEst::m_sep.
Referenced by goPrimeEM().
bool CPrimeEM::generateEmpiricalEMSeeds ()
generate variable number of EM seeds based on some prior information this function is designed specifically for 3-clusters scenario, hence only works if three-clusters is specified, otherwise return false and do nothing
Returns:
true if no error, false otherwise
Definition at line 1428 of file PrimeEM.cpp.
References EPSILON, m_data, CEMParam::m_epsilon, CEMSeed::m_maxMu, CEMSeed::m_maxSigma, CEMSeed::m_minMu, CEMSeed::m_minSigma, CEMSeed::m_mu, CEMPrior::m_mu, CEMPrior::m_muSD, CEMParam::m_nClusters, m_nDim, m_param, m_prior, m_seeds, CEMSeed::m_sigma, CEMPrior::m_sigma, CEMPrior::m_sigmaSD, CEMSeed::m_weight, NA, and CEMSeed::setWeight().
Referenced by goPrimeEM().
std::vector<CEMSeed> CPrimeEM::getSeeds () [inline]
get seeds generated by generateEmpiricalEMSeeds()
Returns:
void
Definition at line 419 of file PrimeEM.h.
References m_seeds.
bool CPrimeEM::goPrimeEM ()
The function to run EM for genotyping, function only works for three cluster cases.
Run EM for genotyping, first generate variable number of EM seeds based some prior information and the data to be classified, then use EM to get estimates starting from each seeds this function only works for three cluster cases as it is designed for genotyping only.
Returns:
true if there is no error, false otherwise
Definition at line 665 of file PrimeEM.cpp.
References checkPrior(), EMEstimate(), evaluateEstimates(), generateEmpiricalEMSeeds(), CEMEst::m_cluster, m_est, CEMParam::m_nClusters, m_nDim, m_param, m_seeds, CEMEst::reset(), and CEMEst::set().
void CPrimeEM::initializeTypeLikelihoodPair (std::vector< std::pair< double, int > > & typeLikelihoodPair)
initialize the type and likelihood pair vector, assign likelihood to infinity
Parameters:
typeLikelihoodPair - the type and likelihood pair vector to be initialized
Returns:
void
Definition at line 900 of file PrimeEM.cpp.
References CEMParam::m_nClusters, and m_param.
Referenced by computeOptimalEstimates().
bool CPrimeEM::reset (const int dim)
reset the data dimension
Parameters:
dim - data dimenstion
Returns:
true if no error, false otherwise
Definition at line 597 of file PrimeEM.cpp.
References m_data, m_est, m_lamda, CEMParam::m_nClusters, m_nDim, m_np, m_p, m_param, m_preEst, and CEMEst::reset().
Referenced by setData().
void CPrimeEM::setData (const std::vector< double > & x)
set the data to be classified
Parameters:
x - the data to be classified
Returns:
void
Definition at line 651 of file PrimeEM.cpp.
References m_data, and reset().
Referenced by EmGenderCelListener::CallGender(), MultiChannelHomHiLoCelListener::computeClusterPeaks(), HomHiLoCelListener::computeClusterPeaks(), and t_CallEMGender().
void CPrimeEM::setParam (const CEMParam & param)
set EM parameters
Parameters:
param - the parameters
Returns:
void
Definition at line 637 of file PrimeEM.cpp.
References CEMPrior::initialize(), m_clusterNP, m_clusterP, m_est, CEMParam::m_nClusters, m_param, m_prior, CEMPrior::set(), and CEMEst::set().
void CPrimeEM::setPrior (const CEMPrior & prior) [inline]
set the prior information
Parameters:
prior - the prior information
Returns:
void
Definition at line 437 of file PrimeEM.h.
References m_prior.
bool CPrimeEM::updateMu ()
update cluster centers
Returns:
true if no error, false otherwise
Definition at line 1156 of file PrimeEM.cpp.
References CEMEst::m_cluster, m_clusterNP, m_data, m_est, CEMEst::m_mu, CEMParam::m_nClusters, m_nDim, m_np, and m_param.
Referenced by doMstep().
bool CPrimeEM::updateSigma ()
update cluster variances
Returns:
true if no error, false otherwise
Definition at line 1179 of file PrimeEM.cpp.
References CEMEst::m_cluster, m_clusterNP, m_data, m_est, CEMEst::m_mu, CEMParam::m_nClusters, m_nDim, m_np, m_param, and CEMEst::m_sigma.
Referenced by doMstep().
bool CPrimeEM::updateWeight ()
update cluster weights
Returns:
true if no error, false otherwise
Definition at line 1204 of file PrimeEM.cpp.
References CEMEst::m_cluster, m_clusterNP, m_est, CEMParam::m_nClusters, m_param, m_sumNP, and CEMEst::m_weight.
Referenced by doMstep().
bool CPrimeEM::useInitialEstimate (CEMSeed & seed)
roll back to the initial values
Roll back to initial values for all estimates.
Parameters:
seed - the seed which contains the initial info to roll back to
Returns:
true if no error, false otherwise
Parameters:
seed - the container with the initial values
Returns:
true is no error, false otherwise
Definition at line 710 of file PrimeEM.cpp.
References computeFLD(), computeOptimalEstimates(), doEstep(), m_est, CEMEst::m_FLD1, CEMEst::m_FLD2, and validate().
bool CPrimeEM::validate (CEMSeed & seed)
validate and adjust seed according to constraints
Parameters:
seed - the seed to be adjusted and returned after adjustment
Returns:
true if no error, false otherwise
Definition at line 1221 of file PrimeEM.cpp.
References CEMEst::m_cluster, m_est, CEMEst::m_maxMu, CEMSeed::m_maxMu, CEMEst::m_maxSigma, CEMSeed::m_maxSigma, CEMEst::m_minMu, CEMSeed::m_minMu, CEMEst::m_minSigma, CEMSeed::m_minSigma, CEMEst::m_mu, CEMSeed::m_mu, CEMParam::m_nClusters, m_param, m_preEst, CEMEst::m_sigma, CEMSeed::m_sigma, CEMEst::m_weight, CEMSeed::m_weight, and CEMEst::set().
Referenced by EMEstimate(), and useInitialEstimate().
The documentation for this class was generated from the following files:
algorithm/em/PrimeEM.h
algorithm/em/PrimeEM.cpp