Affymetrix Power Tools: CNReferenceEngine Class Reference
CNReferenceEngine Class Reference
The engine for calculating the log2 ratios.
#include <CNReferenceEngine.h>