Affymetrix Power Tools: QuantBirdseed Class Reference
QuantBirdseed Class Reference