Affymetrix Power Tools: ConsoleMarkerListTest Class Reference
ConsoleMarkerListTest Class Reference
Public Member Functions
void setUp ()
Initialization method called before each test routine.
void run ()
ConsoleMarkerListTest::run.
Detailed Description
Definition at line 95 of file ConsoleMarkerListTest.cpp.
Member Function Documentation
void ConsoleMarkerListTest::run (void)
ConsoleMarkerListTest::run.
Definition at line 285 of file ConsoleMarkerListTest.cpp.
References C_CMDLINE, C_CONSOLE, BaseEngine::run(), Options::setOpt(), and translateEngineMessageHandlingCallBack().
The documentation for this class was generated from the following file:
translation/CPPTest/ConsoleMarkerListTest.cpp