Affymetrix Power Tools: QuantMedian Class Reference
QuantMedian Class Reference
Class for doing probe set quantification using median as does MEDIAN.
#include <QuantMedian.h>