Affymetrix Power Tools: DiskIntensityMart Class Reference
DiskIntensityMart Class Reference
Very simple version of an IntensityMart based directly on cel files for comparison and troubleshooting.
#include <DiskIntensityMart.h>