Affymetrix Power Tools: MmAdjust Class Reference
MmAdjust Class Reference
Class for supplying the mismatch intensity as pm adjustment.
#include <MmAdjust.h>