Affymetrix Power Tools: CNAnalysisMethodCNCyto2 Class Reference
CNAnalysisMethodCNCyto2 Class Reference
The CN analysis method.
#include <CNAnalysisMethodCNCyto2.h>