Affymetrix Power Tools: QCMethod Class Reference
QCMethod Class Reference
A simple class which contains the basic specification for a QC /// analysis method. Typically populated from a row in the QCA file.
#include <QCAnalysisOptions.h>
Public Types
enum AnalysisType {
DM, GENDER, HOMHILO, ADJHOMHILO,
MULTICHANNEL_DISHQC, MULTICHANNEL_HOMHILO, MULTICHANNEL_SIGNALBACKGROUND, MULTICHANNEL_VARIABILITY
}
Enumeration of possible analysis types.
Public Member Functions
virtual ~QCMethod ()
Virtual Destructor.
CelListener * createCelListener (ChipLayout *layout, vector< string > &celFiles, QCProbesetOptions &psOpts)
Create a CelListener for the encapsulated method.
DmListener * createDmListener (ChipLayout *layout, const std::vector< QCProbesetOptions::nameLigationBase_t > &probesetNames, const std::vector< std::string > &celFiles)
Create a DmListener from an DM analysis method.
EmGenderCelListener * createEmGenderCelListener (ChipLayout *layout, const std::vector< QCProbesetOptions::nameLigationBase_t > &probesetNames, const std::vector< std::string > &celFiles)
Create a EmGenderCelListener from a GENDER analysis method.
HomHiLoCelListener * createHomHiLoCelListener (ChipLayout *layout, const std::vector< QCProbesetOptions::nameLigationBase_t > &probesetNames, const std::vector< std::string > &celFiles)
Create a HomHiLoCelListener from a homhilo analysis method.
AdjHomHiLoCelListener * createAdjHomHiLoCelListener (ChipLayout *layout, QCProbesetOptions &psOpts, std::vector< std::string > &celFiles)
Create a AdjHomHiLoCelListener from a adj-homhilo analysis method.
MultiChannelNonOverlapCelListener * createMultiChannelNonOverlapCelListener (ChipLayout *layout, const vector< QCProbesetOptions::nameLigationBase_t > &probesetNames, QCProbesetOptions &psOpts)
MultiChannelHomHiLoCelListener * createMultiChannelHomHiLoCelListener (ChipLayout *layout, const std::vector< QCProbesetOptions::nameLigationBase_t > &probesetNames, QCProbesetOptions &psOpts)
SignalBackgroundCelListener * createSignalBackgroundCelListener (ChipLayout *layout, const vector< QCProbesetOptions::nameLigationBase_t > &probesetNames, QCProbesetOptions &psOpts)
VariabilityScoreCelListener * createVariabilityScoreCelListener (ChipLayout *layout, const vector< QCProbesetOptions::nameLigationBase_t > &probesetNames, QCProbesetOptions &psOpts)
Public Attributes
std::string analysisName
The name of the analysis.
std::string groupName
The group of probesets to use.
AnalysisType analysis
The analysis type.
std::map< std::string,
std::string > options
Analysis options.
Detailed Description
A simple class which contains the basic specification for a QC /// analysis method. Typically populated from a row in the QCA file.
Definition at line 46 of file QCAnalysisOptions.h.
Member Enumeration Documentation
enum QCMethod::AnalysisType
Enumeration of possible analysis types.
Enumerator:
DM
DM Call Rate.
GENDER
EM ChrX Het Rate Gender Call.
HOMHILO
Min Diff between Hom Peak and Valley.
ADJHOMHILO
Adjusted Hom Min Hi Low used for SNP6.
Definition at line 50 of file QCAnalysisOptions.h.
Member Function Documentation
AdjHomHiLoCelListener * QCMethod::createAdjHomHiLoCelListener (ChipLayout * layout, QCProbesetOptions & psOpts, std::vector< std::string > & celFiles)
Create a AdjHomHiLoCelListener from a adj-homhilo analysis method.
Parameters:
layout - ChipLayout info w/ QC probesets loaded
psOpts - QCProbesetOptions
celFiles - vector of cel file names to process
Returns:
pointer to AdjHomHiLoCelListener. caller needs to free.
Definition at line 681 of file QCAnalysisOptions.cpp.
References analysisName, and options.
Referenced by createCelListener().
CelListener * QCMethod::createCelListener (ChipLayout * layout, std::vector< string > & celFiles, QCProbesetOptions & psOpts)
Create a CelListener for the encapsulated method.
Todo:
it would be nice to handle more sophisticated options (ie not just doubles). Something /// like ChipStream and QuantMethod analysis /// string configurations
Parameters:
layout - ChipLayout info w/ QC probesets loaded
celFiles - vector of cel file names to process
psOpts - QCProbesetOptions instance with info on QC probesets
Returns:
pointer to CelListener. caller needs to free.
Todo:
err checking that probeset list for groupName exists and is not empty
Definition at line 37 of file QCAnalysisOptions.cpp.
References ADJHOMHILO, analysis, APT_ERR_ABORT, createAdjHomHiLoCelListener(), createDmListener(), createEmGenderCelListener(), createHomHiLoCelListener(), DM, GENDER, groupName, HOMHILO, and ToStr().
DmListener * QCMethod::createDmListener (ChipLayout * layout, const std::vector< QCProbesetOptions::nameLigationBase_t > & probesetNames, const std::vector< std::string > & celFiles)
Create a DmListener from an DM analysis method.
Parameters:
layout - ChipLayout info w/ QC probesets loaded
probesetNames - vector of QC probesets to use
celFiles - vector of cel file names to process
Returns:
pointer to DmListener. caller needs to free.
Definition at line 567 of file QCAnalysisOptions.cpp.
References analysisName, ChipLayout::getProbeListByName(), options, DmListener::setDefaultCallIndex(), and DmListener::setDefaultChrXCallIndex().
Referenced by createCelListener().
EmGenderCelListener * QCMethod::createEmGenderCelListener (ChipLayout * layout, const std::vector< QCProbesetOptions::nameLigationBase_t > & probesetNames, const std::vector< std::string > & celFiles)
Create a EmGenderCelListener from a GENDER analysis method.
Parameters:
layout - ChipLayout info w/ QC probesets loaded
probesetNames - vector of QC probesets to use
celFiles - vector of cel file names to process
Returns:
pointer to EmGenderCelListener. caller needs to free.
Definition at line 624 of file QCAnalysisOptions.cpp.
References options.
Referenced by createCelListener().
HomHiLoCelListener * QCMethod::createHomHiLoCelListener (ChipLayout * layout, const std::vector< QCProbesetOptions::nameLigationBase_t > & probesetNames, const std::vector< std::string > & celFiles)
Create a HomHiLoCelListener from a homhilo analysis method.
Parameters:
layout - ChipLayout info w/ QC probesets loaded
probesetNames - vector of QC probesets to use
celFiles - vector of cel file names to process
Returns:
pointer to HomHiLoCelListener. caller needs to free.
Definition at line 655 of file QCAnalysisOptions.cpp.
References analysisName, and options.
Referenced by createCelListener().
The documentation for this class was generated from the following files:
chipstream/QCAnalysisOptions.h
chipstream/QCAnalysisOptions.cpp