Affymetrix Power Tools: ChipStreamFactory Class Reference
ChipStreamFactory Class Reference
Factory class for making chip streams based on a string representation.
#include <ChipStreamFactory.h>
Public Member Functions
ChipStreamFactory ()
Constructor.
ChipStream * cStreamForString (const std::string &spec)
Create a pointer to a new ChipStream object as described in the string specification.
void setTargetSketch (const std::vector< float > &sketch)
Set the distribution for doing quantile normalizations.
int getTargetSketchSize ()
Get the skize of the sketch distribution for doing quantile normalizations.
void setAnnotationFileName (const std::string &str)
Set the annotaiton-file.
void setWriteSketchDir (const std::string &writeSketchDir)
Toggle whether or not we're writing out the normalization distribution.
void setWriteSketchDir_a5 (const std::string &writeSketchDir)
void setWriteSketchGroup_a5 (affx::File5_Group *group5)
void setWriteProfileDir (const std::string &writeProfileDir)
void setreadReferenceProfile (const std::string &readProfile)
void setProbesForNorm (const std::vector< int > &probeIds)
void readNormProbesFromFile (const std::string &fileName)
ChipStream * chipStreamForString (const std::string &spec, ChipLayout &layout, const std::string &description)
Factory for making ChipStreams from a string description.
ChipStream * chipStreamForStringBoard (PsBoard &board, const std::string &spec, const std::string &description)
Factory for making ChipStreams from a string description.
void readTargetSketchFromFile (const std::string &fileName)
Open and read a target distribution from a text file.
void readTargetSketchFromFile_a5 (const std::string &fileName)
void readTargetSketchFromFile_a5_tsv (affx::File5_Group *group5, const std::string &name)
std::vector< SelfDoc > getDocs ()
Get the vector of documentation objects that this factory is aware of.
void setControlProbes (const std::vector< Probe * > controlProbes)
Set the probes to be used as a background distribution.
void setCelFileCount (unsigned int ui)
bool canBuild (const std::string &spec)
Can this factory be used to build from this specification?
Protected Attributes
std::string m_WriteSketchDir
Should we write out our normalization distribution.
std::string m_WriteSketchDir_a5
affx::File5_Group * m_WriteSketchGroup_a5
std::string m_WriteProfileDir
Should we write out our normalization distribution.
std::string m_WriteProfileDir_a5
affx::File5_Group * m_WriteProfileGroup_a5
std::string m_ReadProfile
std::vector< float > m_TargetSketch
Distribution to normalize data to.
std::vector< int > m_NormProbes
Probes to use for normalization.
std::vector< SelfDoc > m_Docs
Self documentation.
std::vector
< SelfCreate::selfCreator > m_Creators
Self creation.
std::vector< Probe * > m_GcControlProbes
Background probes to use. Note that memory is owned elsewhere.
std::string m_strAnnotationFileName
annotaiton-file
std::string m_strIntensityReporterFileName
intensity-reporter.file
unsigned int m_uiCelFileCount
Detailed Description
Factory class for making chip streams based on a string representation.
Definition at line 55 of file ChipStreamFactory.h.
Constructor & Destructor Documentation
ChipStreamFactory::ChipStreamFactory ()
Constructor.
Registers the objects we know how to create and how they describe themselves.
Definition at line 53 of file ChipStreamFactory.cpp.
References ChipStream::explainSelf(), IntensityReporter::explainSelf(), GcBg::explainSelf(), AdapterTypeNormTran::explainSelf(), MedNormTran::explainSelf(), ArtifactReduction::explainSelf(), SketchQuantNormTran::explainSelf(), RmaBgTran::explainSelf(), m_Creators, m_Docs, ChipStream::newObject(), IntensityReporter::newObject(), GcBg::newObject(), AdapterTypeNormTran::newObject(), MedNormTran::newObject(), ArtifactReduction::newObject(), SketchQuantNormTran::newObject(), and RmaBgTran::newObject().
Member Function Documentation
bool ChipStreamFactory::canBuild (const std::string & spec)
Can this factory be used to build from this specification?
Parameters:
spec - Specification in form "chipstream.key=value.key=value"
Returns:
true if this factory knows how to build from this specification, false otherwise
Definition at line 302 of file ChipStreamFactory.cpp.
References SelfCreate::canMake(), and m_Docs.
Referenced by DTFactory::dataTransformForString().
ChipStream * ChipStreamFactory::chipStreamForString (const std::string & spec, ChipLayout & layout, const std::string & description)
Factory for making ChipStreams from a string description.
Parameters:
spec - Specification in form "chipstream.key=value.key=value"
layout - Probe and probe set info.
description - name of chipstream path so far.
Returns:
ChipStream requested.
Definition at line 123 of file ChipStreamFactory.cpp.
References cStreamForString(), Err::errAbort(), ChipLayout::getPmProbeMask(), ChipLayout::getProbeCount(), IntensityTransformer::getType(), SketchQuantNormTran::getUsePmSubset(), Fs::join(), m_GcControlProbes, m_NormProbes, m_strAnnotationFileName, m_TargetSketch, m_WriteProfileDir, m_WriteSketchDir, Verbose::out(), ArtifactReduction::saveReferenceProfile(), SketchQuantNormTran::saveTargetSketch(), GcBg::setControlProbes(), GcBg::setProbeGcVec(), SketchQuantNormTran::setSubProbes(), MedNormTran::setSubProbes(), SketchQuantNormTran::setTargetSketch(), and ToStr().
Referenced by AnalysisStreamFactory::constructExpressionAnalysisStages(), AnalysisStreamFactory::constructExpressionAnalysisStream(), and AnalysisStreamFactory::fillInAnalysisStream().
ChipStream * ChipStreamFactory::chipStreamForStringBoard (PsBoard & board, const std::string & spec, const std::string & description)
Factory for making ChipStreams from a string description.
Parameters:
board - Blackboard with program state.
spec - Specification in form "chipstream.key=value.key=value"
description - name of chipstream path so far.
Returns:
ChipStream requested.
Definition at line 234 of file ChipStreamFactory.cpp.
References cStreamForString(), IntensityTransformer::getType(), Verbose::out(), ChipStream::setParameters(), and ToStr().
Referenced by DTFactory::dataTransformForString().
ChipStream * ChipStreamFactory::cStreamForString (const std::string & spec)
Create a pointer to a new ChipStream object as described in the string specification.
Parameters:
spec - Specification string i.e. quant-norm.sketch=1000000
Returns:
Pointer to new ChipStream objects, must be deleted when finished.
Definition at line 101 of file ChipStreamFactory.cpp.
References Err::errAbort(), m_Creators, m_Docs, and SelfCreate::selfCreateFromString().
Referenced by chipStreamForString(), and chipStreamForStringBoard().
std::vector<SelfDoc> ChipStreamFactory::getDocs () [inline]
Get the vector of documentation objects that this factory is aware of.
Returns:
- vector of documentation objects.
Definition at line 168 of file ChipStreamFactory.h.
References m_Docs.
Referenced by EngineUtil::explainParameter().
void ChipStreamFactory::readTargetSketchFromFile (const std::string & fileName)
Open and read a target distribution from a text file.
Must have a column called 'intensities' with distribution quantiles sorted from highest to lowest.
Parameters:
fileName - text file containing column of quantiles.
Definition at line 271 of file ChipStreamFactory.cpp.
References m_TargetSketch.
Referenced by AnalysisStreamFactory::readTargetSketchFromFile().
void ChipStreamFactory::setAnnotationFileName (const std::string & str) [inline]
Set the annotaiton-file.
Parameters:
str - the annotation file name
Definition at line 94 of file ChipStreamFactory.h.
References m_strAnnotationFileName.
Referenced by AnalysisStreamFactory::setAnnotationFileName().
void ChipStreamFactory::setControlProbes (const std::vector< Probe * > controlProbes) [inline]
Set the probes to be used as a background distribution.
Parameters:
controlProbes - probes to use as controls.
Definition at line 176 of file ChipStreamFactory.h.
References m_GcControlProbes.
Referenced by AnalysisStreamFactory::readControlProbes(), and AnalysisStreamFactory::setGcControlProbes().
void ChipStreamFactory::setTargetSketch (const std::vector< float > & sketch) [inline]
Set the distribution for doing quantile normalizations.
Parameters:
sketch - distribution to normalize to.
Definition at line 79 of file ChipStreamFactory.h.
References m_TargetSketch.
void ChipStreamFactory::setWriteSketchDir (const std::string & writeSketchDir) [inline]
Toggle whether or not we're writing out the normalization distribution.
Parameters:
writeSketch - true to write out the distrubtion false otherwise.
Definition at line 102 of file ChipStreamFactory.h.
References m_WriteSketchDir.
Referenced by AnalysisStreamFactory::setWriteSketchDir().
The documentation for this class was generated from the following files:
chipstream/ChipStreamFactory.h
chipstream/ChipStreamFactory.cpp