Affymetrix Power Tools: CNAnalysisMethodLog2Ratio Class Reference
CNAnalysisMethodLog2Ratio Class Reference
The Log2Ratio analysis method.
#include <CNAnalysisMethodLog2Ratio.h>