Affymetrix Power Tools: QuantMethodExprReport Class Reference
QuantMethodExprReport Class Reference
Class for reporting results of quantification methods.
#include <QuantMethodExprReport.h>