Affymetrix Power Tools: affymetrix_cel_converter::CELFileVersion Class Reference
affymetrix_cel_converter::CELFileVersion Class Reference
#include <CELFileVersion.h>
Static Public Member Functions
static CELFileVersionType DetermineCELFileVersion (const char *fileName)
Detailed Description
Provides for information about CEL file versions.
Definition at line 47 of file CELFileVersion.h.
Member Function Documentation
CELFileVersionType CELFileVersion::DetermineCELFileVersion (const char * fileName) [static]
Determines the version number of the file.
Parameters:
fileName The file name of the CEL file.
Returns:
The file version.
Definition at line 61 of file CELFileVersion.cpp.
References affxcel::CCELFileData::IsVersion3CompatibleFile(), affxcel::CCELFileData::IsXDACompatibleFile(), and affxcel::CCELFileData::SetFileName().
Referenced by affymetrix_cel_converter::CELFileConverter::ConvertFile().
The documentation for this class was generated from the following files:
calvin_files/converters/cel/src/CELFileVersion.h
calvin_files/converters/cel/src/CELFileVersion.cpp