Affymetrix Power Tools: SnpClusterStore Class Reference
SnpClusterStore Class Reference
Class for reading the posterior from snp clustering.
#include <SnpClusterStore.h>
Public Types
enum ClusterModelType { UNKNOWN, AXIOM }
Enum for types supported.
Public Member Functions
SnpClusterStore (const std::string &fileName, const std::string &tmpName="")
Constructor that will open up the hdf5 file supplied and index probe sets by position.
~SnpClusterStore ()
Clean up.
bool snpClusterExists (const std::string &snpName, int copyNumber) const
Return true if the model exists for this snp probeset for this copynumber.
snp_distribution getSnpCluster (const std::string &snpName, int copyNumber) const
Given the name of a snp probeset and the copynumber desired return the cluster distributions in a snp_distribution object.
void getHeaderValue (const std::string &key, std::vector< std::string > &values) const
Get the values associated with a particular key in the header information.
Detailed Description
Class for reading the posterior from snp clustering.
Currently supports only Axiom but goal is to support all GTC Affymetrix Genotyping algorithms. Goal is to provide relatively quick random access to snp posteriors for display in cluster plots.
Definition at line 50 of file SnpClusterStore.h.
Member Enumeration Documentation
enum SnpClusterStore::ClusterModelType
Enum for types supported.
Definition at line 55 of file SnpClusterStore.h.
Constructor & Destructor Documentation
SnpClusterStore::SnpClusterStore (const std::string & fileName, const std::string & tmpName = "")
Constructor that will open up the hdf5 file supplied and index probe sets by position.
Parameters:
fileName - Name of the model file of interest (eg AxiomGT1.snp-posteriors.a5)
tmpFileName - Optional name of temp file to write if necessary.
Definition at line 34 of file SnpClusterStore.cpp.
References TmpFileFactory::genFilename_basic(), and Verbose::out().
Member Function Documentation
void SnpClusterStore::getHeaderValue (const std::string & key, std::vector< std::string > & values) const
Get the values associated with a particular key in the header information.
Parameters:
key - Name of the value to search for.
values - Values associated with the key specified.
Definition at line 80 of file SnpClusterStore.cpp.
snp_distribution SnpClusterStore::getSnpCluster (const std::string & snpName, int copyNumber) const
Given the name of a snp probeset and the copynumber desired return the cluster distributions in a snp_distribution object.
For example the Axiom SNP has copynumber 2 in women but copynumber 1 in men. This may be extended to other duplications and deletions in the future.
Parameters:
snpName - Name of snp probeset (eg AX-11088371)
copyNumber - Usually 2, but can be 1 for chr X snps in men or chrY snps in men
Returns:
- object with cluster information filled in.
Definition at line 65 of file SnpClusterStore.cpp.
References APT_ERR_ASSERT, and ToStr().
bool SnpClusterStore::snpClusterExists (const std::string & snpName, int copyNumber) const
Return true if the model exists for this snp probeset for this copynumber.
Parameters:
snpName - Name of snp probeset (eg AX-11088371)
copyNumber - Usually 2, but can be 1 for chr X snps in men or chrY snps in men
Returns:
- true if there is a model available, false otherwise
Definition at line 60 of file SnpClusterStore.cpp.
The documentation for this class was generated from the following files:
chipstream/SnpClusterStore.h
chipstream/SnpClusterStore.cpp