Affymetrix Power Tools: Mas5Test Class Reference
Mas5Test Class Reference
Public Member Functions
void doU133Calvin ()
void doU133Xda ()
Public Attributes
int numPassed
int numFailed
std::string testDir
Detailed Description
Definition at line 48 of file mas5-test.cpp.
Member Function Documentation
void Mas5Test::doU133Calvin ()
Todo:
APT-378: fix win32 differences in mean signal for P/A/M/All probesets
Definition at line 63 of file mas5-test.cpp.
References Fs::join(), and Verbose::out().
void Mas5Test::doU133Xda ()
Todo:
APT-378: fix win32 differences in mean signal for P/A/M/All probesets
Definition at line 105 of file mas5-test.cpp.
References Fs::join(), and Verbose::out().
The documentation for this class was generated from the following file:
mas5-stat/apt-mas5/regression/mas5-test.cpp