Affymetrix Power Tools: QuantMethodExprChipSummary Class Reference
QuantMethodExprChipSummary Class Reference
Summarize basic statistics on the performance of a particular summarization or detection method across a number of cel files.
#include <QuantMethodExprChipSummary.h>