Affymetrix Power Tools: FusionArrayFileReaderTest Class Reference
FusionArrayFileReaderTest Class Reference
#include <FusionArrayFileTest.h>
Public Member Functions
void setUp ()
void tearDown ()
void testCreation ()
void testmethod_Read_invalid_file ()
void testmethod_Read_missing_file ()
void testmethod_Read_calvin_array_file ()
void testmethod_Read_dtt_array_file ()
void testmethod_Read_mas_array_file ()
Detailed Description
Test Fixture for testing the Array File Reader.
Definition at line 31 of file FusionArrayFileTest.h.
Member Function Documentation
void FusionArrayFileReaderTest::testCreation ()
Test the ability to create the ArrayFileReader class.
Definition at line 49 of file FusionArrayFileTest.cpp.
void FusionArrayFileReaderTest::testmethod_Read_calvin_array_file ()
Test the ability to read a valid Calvin array file.
Definition at line 81 of file FusionArrayFileTest.cpp.
References affymetrix_calvin_array::ArrayData::ArraySetFileIdentifier(), affymetrix_calvin_array::ArrayData::CreatedBy(), affymetrix_calvin_array::ArrayData::CreatedStep(), affymetrix_calvin_array::ArrayData::CreationDateTime(), affymetrix_calvin_array::ArrayData::DataTypeIdentifier(), affymetrix_calvin_array::ArrayData::InitialProject(), affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes(), affymetrix_fusion_io::FusionArrayFileReader::Read(), and affymetrix_calvin_array::ArrayData::UserAttributes().
void FusionArrayFileReaderTest::testmethod_Read_dtt_array_file ()
Test the ability to read an Data Transfer Tool formated array file.
Definition at line 183 of file FusionArrayFileTest.cpp.
References affymetrix_calvin_array::ArrayData::ArraySetFileIdentifier(), affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes(), affymetrix_fusion_io::FusionArrayFileReader::Read(), and affymetrix_calvin_array::ArrayData::UserAttributes().
void FusionArrayFileReaderTest::testmethod_Read_invalid_file ()
Test the handling of attempting to read an invalid array file.
Definition at line 57 of file FusionArrayFileTest.cpp.
References affymetrix_calvin_array::ArrayData::ArraySetFileIdentifier(), affymetrix_calvin_array::ArrayData::DataTypeIdentifier(), affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes(), affymetrix_fusion_io::FusionArrayFileReader::Read(), and affymetrix_calvin_array::ArrayData::UserAttributes().
void FusionArrayFileReaderTest::testmethod_Read_mas_array_file ()
Test the ability to read an Micro Array Suit formated array file (EXP).
Definition at line 217 of file FusionArrayFileTest.cpp.
References affymetrix_calvin_array::ArrayData::ArraySetFileIdentifier(), affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes(), affymetrix_fusion_io::FusionArrayFileReader::Read(), and affymetrix_calvin_array::ArrayData::UserAttributes().
void FusionArrayFileReaderTest::testmethod_Read_missing_file ()
Test the handling of attempting to read an array file that does not exist.
Definition at line 69 of file FusionArrayFileTest.cpp.
References affymetrix_calvin_array::ArrayData::ArraySetFileIdentifier(), affymetrix_calvin_array::ArrayData::DataTypeIdentifier(), affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes(), affymetrix_fusion_io::FusionArrayFileReader::Read(), and affymetrix_calvin_array::ArrayData::UserAttributes().
The documentation for this class was generated from the following files:
calvin_files/fusion/test/FusionArrayFileTest.h
calvin_files/fusion/test/FusionArrayFileTest.cpp