Affymetrix Power Tools: QuantRma Class Reference
QuantRma Class Reference
Class for doing probe set quantification using median polish as does RMA.
#include <QuantRma.h>