Affymetrix Power Tools: GenoSeedTxt Class Reference
GenoSeedTxt Class Reference
Implements interface for a genotyping oracle used for genotyping seeds in brlmm.
#include <GenoSeedTxt.h>