Affymetrix Power Tools: DataStore Class Reference
DataStore Class Reference
Class that stores data about probes and probesets out of core but loads into RAM as necessary for computation.
#include <DataStore.h>