Affymetrix Power Tools: affymetrix_fusion_io::FusionArrayFileReader Class Reference
affymetrix_fusion_io::FusionArrayFileReader Class Reference
#include <FusionArrayFileReader.h>
Public Member Functions
FusionArrayFileReader ()
~FusionArrayFileReader ()
bool Read (const std::string &fileName, affymetrix_calvin_array::ArrayData &arrayData)
const
affymetrix_calvin_utilities::AffymetrixGuidType & DataTypeIdentifier () const
Protected Attributes
affymetrix_calvin_utilities::AffymetrixGuidType dataTypeIdentifier
Detailed Description
This class provides the fusion parsing interfaces for reading array files.
The array files can be one of the following: MAS5 EXP files MAGE-ML XML files generated by the DTT version 1.1 software MAGE-ML XML files generated by the GDAC Exporter SDK
In all cases the parser will populate an array data object.
Definition at line 44 of file FusionArrayFileReader.h.
Constructor & Destructor Documentation
FusionArrayFileReader::FusionArrayFileReader ()
Constructor
Definition at line 42 of file FusionArrayFileReader.cpp.
FusionArrayFileReader::~FusionArrayFileReader ()
Destructor
Definition at line 49 of file FusionArrayFileReader.cpp.
Member Function Documentation
const affymetrix_calvin_utilities::AffymetrixGuidType& affymetrix_fusion_io::FusionArrayFileReader::DataTypeIdentifier () const [inline]
The identifier of the type of data stored in the file.
Returns:
The identifier of the type of data.
Definition at line 67 of file FusionArrayFileReader.h.
References dataTypeIdentifier.
bool FusionArrayFileReader::Read (const std::string & fileName, affymetrix_calvin_array::ArrayData & arrayData)
Reads the entire contents of the file.
Parameters:
fileName The name of the array file to read.
arrayData The array data to read from the file.
Definition at line 69 of file FusionArrayFileReader.cpp.
References ARRAY_SET_FILE_TYPE_IDENTIFIER, affymetrix_calvin_array::ArrayAttributes::Attributes(), affymetrix_dttarray::DttArrayData::Attributes(), affymetrix_calvin_array::ArrayData::Clear(), affxexp::CEXPFileData::GetArrayType(), affymetrix_dttarray::DttArrayData::GetArrayType(), affxexp::CEXPFileData::GetSampleParameters(), affymetrix_calvin_parameter::_tagParameterNameValuePair::Name, affymetrix_dttarray::_AttributeNameValueType::name, affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes(), affxexp::CEXPFileData::Read(), affymetrix_dttarray::DttArrayFileReader::Read(), affymetrix_calvin_io::ArrayFileReader::Read(), affxexp::CEXPFileData::SetFileName(), affymetrix_dttarray::DttArrayFileReader::SetFileName(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueText(), _TagValuePairType::Tag, affymetrix_calvin_array::ArrayData::UserAttributes(), _TagValuePairType::Value, affymetrix_calvin_parameter::_tagParameterNameValuePair::Value, and affymetrix_dttarray::_AttributeNameValueType::value.
Referenced by FusionArrayFileReaderTest::testmethod_Read_calvin_array_file(), FusionArrayFileReaderTest::testmethod_Read_dtt_array_file(), FusionArrayFileReaderTest::testmethod_Read_invalid_file(), FusionArrayFileReaderTest::testmethod_Read_mas_array_file(), and FusionArrayFileReaderTest::testmethod_Read_missing_file().
Member Data Documentation
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_fusion_io::FusionArrayFileReader::dataTypeIdentifier [protected]
An identifier to the type of data stored in the file
Definition at line 49 of file FusionArrayFileReader.h.
Referenced by DataTypeIdentifier().
The documentation for this class was generated from the following files:
calvin_files/fusion/src/FusionArrayFileReader.h
calvin_files/fusion/src/FusionArrayFileReader.cpp