Affymetrix Power Tools: BaseEngine Class Reference
BaseEngine Class Reference
Base class for analysis engines.
#include <BaseEngine.h>