Affymetrix Power Tools: affymetrix_calvin_io::CDFProbeSetInformation Class Reference
affymetrix_calvin_io::CDFProbeSetInformation Class Reference
#include <CDFProbeSetInformation.h>
Public Member Functions
CDFProbeSetInformation ()
~CDFProbeSetInformation ()
std::wstring GetName () const
affymetrix_calvin_io::DirectionType GetDirection () const
u_int32_t GetNumLists () const
u_int32_t GetNumGroups () const
u_int32_t GetNumCells () const
u_int8_t GetNumCellsPerList () const
u_int32_t GetProbeSetNumber () const
void GetGroupInformation (u_int32_t groupIdx, CDFProbeGroupInformation &info)
CDFDataTypeIds GetProbeSetType () const
Protected Member Functions
void SetDataGroup (DataGroup &dg)
Protected Attributes
DataGroup * dataGroup
CDFDataTypeIds type
u_int8_t direction
u_int32_t groupCnt
u_int32_t listCnt
u_int32_t cellCnt
u_int32_t probeSetNumber
u_int8_t cellsPerList
Friends
class CDFData
Detailed Description
Class that exposes the CDF probe set information
Definition at line 43 of file CDFProbeSetInformation.h.
Constructor & Destructor Documentation
CDFProbeSetInformation::CDFProbeSetInformation ()
Constructor
Definition at line 33 of file CDFProbeSetInformation.cpp.
References cellCnt, cellsPerList, dataGroup, direction, groupCnt, listCnt, probeSetNumber, and type.
CDFProbeSetInformation::~CDFProbeSetInformation ()
Destructor
Definition at line 48 of file CDFProbeSetInformation.cpp.
References dataGroup.
Member Function Documentation
affymetrix_calvin_io::DirectionType affymetrix_calvin_io::CDFProbeSetInformation::GetDirection () const [inline]
Get the probe set direction
Definition at line 54 of file CDFProbeSetInformation.h.
References direction.
Referenced by affymetrix_fusion_io::FusionCDFProbeSetInformation::GetDirection().
void CDFProbeSetInformation::GetGroupInformation (u_int32_t groupIdx, CDFProbeGroupInformation & info)
Get information for a probe set group by index
Definition at line 107 of file CDFProbeSetInformation.cpp.
References dataGroup, affymetrix_calvin_io::DataGroup::DataSet(), and groupCnt.
std::wstring affymetrix_calvin_io::CDFProbeSetInformation::GetName () const [inline]
Get the probe set name
Definition at line 52 of file CDFProbeSetInformation.h.
References dataGroup, affymetrix_calvin_io::DataGroupHeader::GetName(), and affymetrix_calvin_io::DataGroup::Header().
u_int32_t affymetrix_calvin_io::CDFProbeSetInformation::GetNumCells () const [inline]
Get the total number of cells in the probe set
Definition at line 60 of file CDFProbeSetInformation.h.
References cellCnt.
Referenced by affymetrix_fusion_io::FusionCDFProbeSetInformation::GetNumCells().
u_int8_t affymetrix_calvin_io::CDFProbeSetInformation::GetNumCellsPerList () const [inline]
Get the number of cells per list (atom)
Definition at line 62 of file CDFProbeSetInformation.h.
References cellsPerList.
Referenced by affymetrix_fusion_io::FusionCDFProbeSetInformation::GetNumCellsPerList().
u_int32_t affymetrix_calvin_io::CDFProbeSetInformation::GetNumGroups () const [inline]
Get the number of groups (block) in the probe set
Definition at line 58 of file CDFProbeSetInformation.h.
References groupCnt.
Referenced by affymetrix_fusion_io::FusionCDFProbeSetInformation::GetNumGroups().
u_int32_t affymetrix_calvin_io::CDFProbeSetInformation::GetNumLists () const [inline]
Get the total number of lists (atoms) in the probe set
Definition at line 56 of file CDFProbeSetInformation.h.
References listCnt.
Referenced by affymetrix_fusion_io::FusionCDFProbeSetInformation::GetNumLists().
u_int32_t affymetrix_calvin_io::CDFProbeSetInformation::GetProbeSetNumber () const [inline]
Get the probe set number
Definition at line 64 of file CDFProbeSetInformation.h.
References probeSetNumber.
Referenced by affymetrix_fusion_io::FusionCDFProbeSetInformation::GetProbeSetNumber().
CDFDataTypeIds affymetrix_calvin_io::CDFProbeSetInformation::GetProbeSetType () const [inline]
Get the probe set type.
Definition at line 68 of file CDFProbeSetInformation.h.
References type.
Referenced by affymetrix_fusion_io::FusionCDFProbeSetInformation::GetProbeSetType().
void CDFProbeSetInformation::SetDataGroup (DataGroup & dg) [protected]
Definition at line 53 of file CDFProbeSetInformation.cpp.
References cellCnt, cellsPerList, dataGroup, direction, affymetrix_calvin_io::DataSetHeader::FindNameValParam(), affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), affymetrix_calvin_io::DataGroupHeader::GetDataSetConst(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8(), groupCnt, affymetrix_calvin_io::DataGroup::Header(), listCnt, probeSetNumber, and type.
Referenced by affymetrix_calvin_io::CDFData::GetProbeSetInformation().
Member Data Documentation
u_int32_t affymetrix_calvin_io::CDFProbeSetInformation::cellCnt [protected]
Total number of cells in the probe set - sum of all DataSets
Definition at line 87 of file CDFProbeSetInformation.h.
Referenced by CDFProbeSetInformation(), GetNumCells(), and SetDataGroup().
u_int8_t affymetrix_calvin_io::CDFProbeSetInformation::cellsPerList [protected]
Cells per list (Cell per atom) - based on value in the first DataSet, same as NumCellsPerList in C++
Definition at line 91 of file CDFProbeSetInformation.h.
Referenced by CDFProbeSetInformation(), GetNumCellsPerList(), and SetDataGroup().
DataGroup* affymetrix_calvin_io::CDFProbeSetInformation::dataGroup [protected]
DataGroup
Definition at line 76 of file CDFProbeSetInformation.h.
Referenced by CDFProbeSetInformation(), GetGroupInformation(), GetName(), SetDataGroup(), and ~CDFProbeSetInformation().
u_int8_t affymetrix_calvin_io::CDFProbeSetInformation::direction [protected]
Direction - based on first DataSet
Definition at line 81 of file CDFProbeSetInformation.h.
Referenced by CDFProbeSetInformation(), GetDirection(), and SetDataGroup().
u_int32_t affymetrix_calvin_io::CDFProbeSetInformation::groupCnt [protected]
Total number of groups (blocks), = number of DataSets in the DataGroup
Definition at line 83 of file CDFProbeSetInformation.h.
Referenced by CDFProbeSetInformation(), GetGroupInformation(), GetNumGroups(), and SetDataGroup().
u_int32_t affymetrix_calvin_io::CDFProbeSetInformation::listCnt [protected]
Total number of lists (atoms) in the probe set - sum of all DataSets
Definition at line 85 of file CDFProbeSetInformation.h.
Referenced by CDFProbeSetInformation(), GetNumLists(), and SetDataGroup().
u_int32_t affymetrix_calvin_io::CDFProbeSetInformation::probeSetNumber [protected]
Probe set number - based on value in first DataSet, same as ProbeSetNumber in C++
Definition at line 89 of file CDFProbeSetInformation.h.
Referenced by CDFProbeSetInformation(), GetProbeSetNumber(), and SetDataGroup().
CDFDataTypeIds affymetrix_calvin_io::CDFProbeSetInformation::type [protected]
Probe set type - based on unitType of first DataSet u_int8_t
Definition at line 79 of file CDFProbeSetInformation.h.
Referenced by CDFProbeSetInformation(), GetProbeSetType(), and SetDataGroup().
The documentation for this class was generated from the following files:
calvin_files/data/src/CDFProbeSetInformation.h
calvin_files/data/src/CDFProbeSetInformation.cpp