Affymetrix Power Tools: CNIntensityAdjustmentMethodHighPassFilter Class Reference
CNIntensityAdjustmentMethodHighPassFilter Class Reference
A class for calulating background.
#include <CNIntensityAdjustmentMethodHighPassFilter.h>