Affymetrix Power Tools: AdjHomHiLoCelListener Class Reference
AdjHomHiLoCelListener Class Reference
Class for computing hilo qc metric from a cel set of cel files.
#include <AdjHomHiLoCelListener.h>