Affymetrix Power Tools: RmaBgTran Class Reference
RmaBgTran Class Reference
RmaBgTran - Class for doing RMA style background subtraction.
#include <RmaBgTran.h>