Affymetrix Power Tools: QuantMethodSqlGTypeReport Class Reference
QuantMethodSqlGTypeReport Class Reference
Class for reporting results of quantification methods.
#include <QuantMethodSqlGTypeReport.h>