Affymetrix Power Tools: affymetrix_calvin_io::CelFileData Class Reference
affymetrix_calvin_io::CelFileData Class Reference
#include <CELData.h>
Public Member Functions
CelFileData ()
CelFileData (const std::string &filename)
~CelFileData ()
void Clear ()
bool Exists ()
void SetActiveChannel (const std::wstring &channel)
void SetFilename (const std::string &p)
std::string GetFilename () const
void SetIntensityCount (int32_t ln)
void SetStdDevCount (int32_t ln)
void SetPixelCount (int32_t ln)
void SetOutlierCount (int32_t ln)
void SetMaskCount (int32_t ln)
FileHeader * GetFileHeader ()
u_int8_t GetVersion ()
void SetArrayType (const std::wstring &value)
std::wstring GetArrayType ()
void SetMasterFileName (const std::wstring &value)
std::wstring GetMasterFileName ()
void SetLibraryPackageName (const std::wstring &value)
std::wstring GetLibraryPackageName ()
void SetAlgorithmName (const std::wstring &value)
std::wstring GetAlgorithmName ()
void SetAlgorithmVersion (const std::wstring &value)
std::wstring GetAlgorithmVersion ()
void SetRows (int32_t value)
int32_t GetRows ()
void SetCols (int32_t value)
int32_t GetCols ()
int32_t GetNumCells ()
void GetAlgorithmParameters (ParameterNameValueTypeVector &algParams)
bool FindAlgorithmParameter (const std::wstring &name, ParameterNameValueType &param)
void AddAlgorithmParameter (ParameterNameValueType &nvt)
void GetData (int32_t cellIdx, float &intensity, float &stdev, int16_t &numPixels, bool &outlier, bool &masked)
bool HasStdev ()
bool HasNumPixels ()
float GetIntensity (int index)
bool GetIntensities (int32_t cellIdxStart, int32_t count, FloatVector &values)
bool GetStdev (int32_t cellIdxStart, int32_t count, FloatVector &values)
bool GetNumPixels (int32_t cellIdxStart, int32_t count, Int16Vector &values)
bool GetOutliers (int32_t cellIdxStart, int32_t count, BoolVector &values)
bool GetMasked (int32_t cellIdxStart, int32_t count, BoolVector &values)
void GetOutlierCoords (XYCoordVector &coords)
void GetMaskedCoords (XYCoordVector &coords)
GenericData & GetGenericData ()
std::wstring GetDatHeader ()
void ComputeXY (int32_t cellIdx, int16_t &x, int16_t &y)
ParameterNameValueTypeList GetDataSetParameters (const std::wstring &setName)
bool IsMultiColor ()
WStringVector GetChannels ()
Protected Member Functions
void CloseDataSets ()
void ResetMaskAndOutliers ()
Friends
class CelFileReader
class CelFileWriter
class MultiChannelCelFileWriter
Detailed Description
This is the container class for CEL data.
Definition at line 65 of file CELData.h.
Constructor & Destructor Documentation
CelFileData::CelFileData ()
Default Constructor
Definition at line 39 of file CELData.cpp.
References Clear().
CelFileData::CelFileData (const std::string & filename)
Constructor
Parameters:
filename Name of the cel file.
Definition at line 50 of file CELData.cpp.
References CelDataGroupName, Clear(), affymetrix_calvin_io::GenericData::Header(), INTENSITY_DATA_TYPE, SetFilename(), and affymetrix_calvin_io::GenericDataHeader::SetFileTypeId().
CelFileData::~CelFileData ()
Destructor
Definition at line 66 of file CELData.cpp.
References Clear().
Member Function Documentation
void CelFileData::AddAlgorithmParameter (ParameterNameValueType & nvt)
Add an algorithm parameter. The algorithm parameter prefix will be added by the method.
Parameters:
nvt Algorithm parameter to add to the list.
Definition at line 993 of file CELData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), ALGORITHM_PARAM_NAME_PREFIX, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile().
void CelFileData::Clear ()
Clear the object members
Definition at line 74 of file CELData.cpp.
References affymetrix_calvin_io::GenericData::Header().
Referenced by CelFileData(), affymetrix_fusion_io::CalvinCELDataAdapter::Clear(), affymetrix_cel_converter::CELFileConvertToASCII::ConvertCalvinFile(), affymetrix_calvin_io::CelFileReader::Read(), affymetrix_fusion_io::CalvinCELDataAdapter::~CalvinCELDataAdapter(), and ~CelFileData().
void CelFileData::ComputeXY (int32_t cellIdx, int16_t & x, int16_t & y)
Determine the x-y coordinate given a cell index.
Parameters:
cellIdx Cell index
x Cell x-coordinate
y Cell y-coordinate
Definition at line 899 of file CELData.cpp.
References GetCols().
bool CelFileData::Exists ()
Check if the file exists
Definition at line 130 of file CELData.cpp.
References affymetrix_calvin_io::FileHeader::GetFilename(), and affymetrix_calvin_io::GenericData::Header().
bool CelFileData::FindAlgorithmParameter (const std::wstring & name, ParameterNameValueType & param)
Return an algorithm parameter given a name.
Parameters:
name Name of the parameter to find.
param The found parameter.
Returns:
True if the parameter was found.
Definition at line 1005 of file CELData.cpp.
References ALGORITHM_PARAM_NAME_PREFIX, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_cel_converter::CELConversionUtilities::FindAndAddAlgorithmParameter(), affymetrix_fusion_io::CalvinCELDataAdapter::GetAlgorithmParameter(), affymetrix_fusion_io::CalvinCELDataAdapter::GetCellMargin(), affymetrix_cel_converter::CELConversionUtilities::GetGrid(), affymetrix_fusion_io::CalvinCELDataAdapter::GetGridCorners(), and affymetrix_cel_converter::CELConversionUtilities::SetCellMargin().
std::wstring CelFileData::GetAlgorithmName ()
Get the name of the algorithm used to generate the results.
Returns:
Algorithm name
Definition at line 717 of file CELData.cpp.
References ALGORITHM_NAME_PARAM_NAME.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetAlg().
void CelFileData::GetAlgorithmParameters (ParameterNameValueTypeVector & algParams)
Return the algorithm parameters. The algorithm parameter prefix is removed from the name.
Parameters:
algParams Vector with algorithm parameters.
Definition at line 974 of file CELData.cpp.
References ALGORITHM_PARAM_NAME_PREFIX, affymetrix_calvin_io::GenericDataHeader::GetNameValParamsBeginsWith(), and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_cel_converter::CELConversionUtilities::Copy(), affymetrix_fusion_io::CalvinCELDataAdapter::GetAlgorithmParameterTag(), affymetrix_fusion_io::CalvinCELDataAdapter::GetNumberAlgorithmParameters(), affymetrix_fusion_io::CalvinCELDataAdapter::GetParameters(), and affymetrix_fusion_io::CalvinCELDataAdapter::GetParams().
std::wstring CelFileData::GetArrayType ()
Get the array type
Returns:
array type name
Definition at line 669 of file CELData.cpp.
References ARRAY_TYPE_PARAM_NAME.
Referenced by affymetrix_cel_converter::CELConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCELDataAdapter::GetChipType().
WStringVector CelFileData::GetChannels ()
Returns a list of the channel (ie data group) names
Returns:
list of channel names
Definition at line 771 of file CELData.cpp.
References CelDataGroupName, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_io::GenericDataHeader::FindParent(), GetFileHeader(), MULTI_SCAN_ACQUISITION_DATA_TYPE, and affymetrix_calvin_parameter::ParameterNameValueType::ToString().
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetChannels(), and IsMultiColor().
int32_t CelFileData::GetCols ()
Get the number of columns of cells on the array.
Returns:
Number of columns of cells.
Definition at line 811 of file CELData.cpp.
References CEL_COLS_PARAM_NAME.
Referenced by ComputeXY(), affymetrix_cel_converter::CELConversionUtilities::Copy(), affymetrix_fusion_io::CalvinCELDataAdapter::GetCols(), affymetrix_fusion_io::CalvinCELDataAdapter::IndexToX(), affymetrix_fusion_io::CalvinCELDataAdapter::IndexToY(), and affymetrix_fusion_io::CalvinCELDataAdapter::XYToIndex().
void CelFileData::GetData (int32_t cellIdx, float & intensity, float & stdev, int16_t & numPixels, bool & outlier, bool & masked)
Get the cell intensity, standard deviation, number of pixels, outlier flag and mask flag.
Parameters:
cellIdx Index of the cell.
intensity The intensity of the cell.
stdev The standard deviation of the cell.
numPixels The number of pixels in the cell.
outlier The outlier flag of the cell.
masked The masked flag of the cell.
Definition at line 426 of file CELData.cpp.
References affymetrix_calvin_io::DataSet::GetData().
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetEntry().
ParameterNameValueTypeList CelFileData::GetDataSetParameters (const std::wstring & setName)
Returns the list of parameters associated with a data set.
Parameters:
setName The data set name
Returns:
The list of parameters
Definition at line 1025 of file CELData.cpp.
References affymetrix_calvin_io::GenericData::DataSet(), affymetrix_calvin_io::DataSetHeader::GetNameValIterators(), and affymetrix_calvin_io::DataSet::Header().
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetDataSetParameters().
std::wstring CelFileData::GetDatHeader ()
Return a wstring for DatHeader
Returns:
DatHeader
Definition at line 907 of file CELData.cpp.
References DAT_HEADER_PARAM_NAME, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_io::GenericDataHeader::FindParent(), FormatString2, GetFileHeader(), affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), MAX_PIXEL_INTENSITY_PARAM_NAME, MIN_PIXEL_INTENSITY_PARAM_NAME, MULTI_SCAN_ACQUISITION_DATA_TYPE, and PARTIAL_DAT_HEADER_PARAM_NAME.
FileHeader* affymetrix_calvin_io::CelFileData::GetFileHeader () [inline]
Definition at line 148 of file CELData.h.
References affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::AddExtraParameters(), affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile(), GetChannels(), affymetrix_fusion_io::CalvinCELDataAdapter::GetDatHeader(), GetDatHeader(), affymetrix_cel_converter::CELConversionUtilities::GetDatHeader(), affymetrix_fusion_io::CalvinCELDataAdapter::GetFileId(), and affymetrix_chp_converter::CHPFileConvertToCalvin::GetParentGenericDataHeader().
std::string CelFileData::GetFilename () const
Get the file name
Returns:
file name
Definition at line 154 of file CELData.cpp.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetFileName(), and affymetrix_calvin_io::CelFileReader::Read().
GenericData& affymetrix_calvin_io::CelFileData::GetGenericData () [inline]
Return a reference to the generic layer object
Returns:
Generic layer object
Definition at line 326 of file CELData.h.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetGenericData(), makeMultiCelFileSubset(), and affymetrix_calvin_io::CelFileReader::Read().
bool CelFileData::GetIntensities (int32_t cellIdxStart, int32_t count, FloatVector & values)
Get the intensities for a range of cell indexes.
Parameters:
cellIdxStart Cell index of the first intensity to retrieve.
count Number of intensities to retrieve.
values Retrieved cell intensities.
Returns:
True if all intensities were retrieved.
Definition at line 498 of file CELData.cpp.
References affymetrix_calvin_io::DataSet::GetData(), and affymetrix_calvin_io::DataSet::IsOpen().
Referenced by affymetrix_cel_converter::CELConversionUtilities::Copy(), affymetrix_fusion_io::CalvinCELDataAdapter::GetIntensities(), affymetrix_fusion_io::CalvinCELDataAdapter::GetIntensity(), and GetIntensity().
float CelFileData::GetIntensity (int index)
Get the intensity for a cell index.
Parameters:
cell index of the intensity to retrieve.
Returns:
float of a particular intensity value.
Definition at line 486 of file CELData.cpp.
References GetIntensities().
std::wstring CelFileData::GetLibraryPackageName ()
Get the library package
Returns:
library package name
Definition at line 701 of file CELData.cpp.
References LIBRARY_PACKAGE_PARAM_NAME.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetLibraryPackageName().
bool CelFileData::GetMasked (int32_t cellIdxStart, int32_t count, BoolVector & values)
Get the mask flags for a range of cell indexes.
Parameters:
cellIdxStart Cell index of the first mask flag to retrieve.
count Number of cell mask flags to retrieve.
values Retrieved cell mask flags
Returns:
True if all mask flags were retrieved.
Definition at line 568 of file CELData.cpp.
References GetNumCells().
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::IsMasked().
void CelFileData::GetMaskedCoords (XYCoordVector & coords)
Get the coordinates of all masked cells (i.e. mask flag is true).
Parameters:
coords Cell coordinates.
Definition at line 599 of file CELData.cpp.
Referenced by affymetrix_cel_converter::CELConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCELDataAdapter::GetNumMasked().
std::wstring CelFileData::GetMasterFileName ()
Get the master file
Returns:
master file name
Definition at line 685 of file CELData.cpp.
References MASTER_FILE_PARAM_NAME.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetMasterFileName().
int32_t CelFileData::GetNumCells ()
Return the number of cells on the array. This is the number of the intensity data elements and is == GetRows() * GetCols() Stdev, NumPixels, Outlier and Masked data is optional, but if present they will have GetNumCells elements.
Returns:
Number of cells in the array.
Definition at line 276 of file CELData.cpp.
References affymetrix_calvin_io::DataSet::Rows().
Referenced by affymetrix_cel_converter::CELConversionUtilities::Copy(), GetMasked(), affymetrix_fusion_io::CalvinCELDataAdapter::GetNumCells(), and GetOutliers().
bool CelFileData::GetNumPixels (int32_t cellIdxStart, int32_t count, Int16Vector & values)
Get the number of pixels for a range of cell indexes.
Parameters:
cellIdxStart Cell index of the first pixel count to retrieve.
count Number of cell pixels to retrieve.
values Retrieved cell pixel counts
Returns:
True if all pixel count (number of pixels) were retrieved.
Definition at line 536 of file CELData.cpp.
References affymetrix_calvin_io::DataSet::GetData(), and affymetrix_calvin_io::DataSet::IsOpen().
Referenced by affymetrix_cel_converter::CELConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCELDataAdapter::GetPixels().
void CelFileData::GetOutlierCoords (XYCoordVector & coords)
Get the coordinates of all outlier cells (i.e. outlier flag is true).
Parameters:
coords Cell coordinates.
Definition at line 586 of file CELData.cpp.
Referenced by affymetrix_cel_converter::CELConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCELDataAdapter::GetNumOutliers().
bool CelFileData::GetOutliers (int32_t cellIdxStart, int32_t count, BoolVector & values)
Get the outlier flags for a range of cell indexes.
Parameters:
cellIdxStart Cell index of the first outlier flag to retrieve.
count Number of cell outlier flags to retrieve.
values Retrieved cell outlier flags
Returns:
True if all outlier flags were retrieved.
Definition at line 550 of file CELData.cpp.
References GetNumCells().
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::IsOutlier().
int32_t CelFileData::GetRows ()
Get the number of rows of cells on the array.
Returns:
Number of rows of cells.
Definition at line 750 of file CELData.cpp.
References CEL_ROWS_PARAM_NAME.
Referenced by affymetrix_cel_converter::CELConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCELDataAdapter::GetRows().
bool CelFileData::GetStdev (int32_t cellIdxStart, int32_t count, FloatVector & values)
Get the standard deviations for a range of cell indexes.
Parameters:
cellIdxStart Cell index of the first standard deviation to retrieve.
count Number of cell standard deviations to retrieve.
values Retrieved cell standard deviations.
Returns:
True if all standard deviations were retrieved.
Definition at line 522 of file CELData.cpp.
References affymetrix_calvin_io::DataSet::GetData(), and affymetrix_calvin_io::DataSet::IsOpen().
Referenced by affymetrix_cel_converter::CELConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCELDataAdapter::GetStdv().
u_int8_t CelFileData::GetVersion ()
Get the version of the CEL file
Returns:
CEL file version
Definition at line 646 of file CELData.cpp.
References FILE_VERSION_PARAM_NAME, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8(), and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetVersion().
bool CelFileData::HasNumPixels ()
Indicates whether there are number of pixel values.
Returns:
True if there are number of pixels values.
Definition at line 623 of file CELData.cpp.
References CelPixelLabel, and affymetrix_calvin_io::DataSetHeader::GetRowCnt().
bool CelFileData::HasStdev ()
Indicates whether there are standard deviation values.
Returns:
True if there are standard deviation values.
Definition at line 612 of file CELData.cpp.
References CelStdDevLabel, and affymetrix_calvin_io::DataSetHeader::GetRowCnt().
bool CelFileData::IsMultiColor ()
Is this a multi-color CEL file?
Returns:
True if it is multi-color
Definition at line 766 of file CELData.cpp.
References GetChannels().
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::IsMultiColor().
void CelFileData::SetActiveChannel (const std::wstring & channel)
Sets the active channel for a multi-channel CEL file. Default is single channel.
Definition at line 117 of file CELData.cpp.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::SetActiveDataGroup().
void CelFileData::SetAlgorithmName (const std::wstring & value)
Set name of the algorithm used to generate the results.
Parameters:
value algorithm name
Definition at line 709 of file CELData.cpp.
References ALGORITHM_NAME_PARAM_NAME.
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile().
void CelFileData::SetAlgorithmVersion (const std::wstring & value)
Set version of the algorithm used to generate the results.
Parameters:
value algorithm name
Definition at line 725 of file CELData.cpp.
References ALG_VERSION_PARAM_NAME.
void CelFileData::SetArrayType (const std::wstring & value)
Set the array type
Parameters:
value array type name
Definition at line 661 of file CELData.cpp.
References ARRAY_TYPE_MAX_LEN, and ARRAY_TYPE_PARAM_NAME.
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile(), and makeMultiCelFileSubset().
void CelFileData::SetCols (int32_t value)
Set the number of columns of cells on the array.
Parameters:
value Number of columns of cells.
Definition at line 760 of file CELData.cpp.
References CEL_COLS_PARAM_NAME.
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile(), and makeMultiCelFileSubset().
void CelFileData::SetFilename (const std::string & p)
Set the file name
Parameters:
p file name
Definition at line 146 of file CELData.cpp.
References affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_io::FileHeader::SetFilename().
Referenced by CelFileData(), affymetrix_fusion_io::CalvinCELDataAdapter::ReadEx(), and affymetrix_fusion_io::CalvinCELDataAdapter::SetFileName().
void CelFileData::SetIntensityCount (int32_t ln)
Definition at line 159 of file CELData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), CelIntensityLabel, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile(), and makeMultiCelFileSubset().
void CelFileData::SetLibraryPackageName (const std::wstring & value)
Set the library package
Parameters:
value library package name
Definition at line 693 of file CELData.cpp.
References ARRAY_TYPE_MAX_LEN, and LIBRARY_PACKAGE_PARAM_NAME.
void CelFileData::SetMaskCount (int32_t ln)
Definition at line 228 of file CELData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddShortColumn(), CelMaskLabel, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile().
void CelFileData::SetMasterFileName (const std::wstring & value)
Set the master file
Parameters:
value master file name
Definition at line 677 of file CELData.cpp.
References MASTER_FILE_PARAM_NAME.
void CelFileData::SetOutlierCount (int32_t ln)
Definition at line 210 of file CELData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddShortColumn(), CelOutlierLabel, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile().
void CelFileData::SetPixelCount (int32_t ln)
Definition at line 193 of file CELData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddShortColumn(), CelPixelLabel, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile(), and makeMultiCelFileSubset().
void CelFileData::SetRows (int32_t value)
Set the number of rows of cells on the array.
Parameters:
value Number of rows of cells.
Definition at line 741 of file CELData.cpp.
References CEL_ROWS_PARAM_NAME.
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile(), and makeMultiCelFileSubset().
void CelFileData::SetStdDevCount (int32_t ln)
Definition at line 176 of file CELData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), CelStdDevLabel, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by affymetrix_cel_converter::CELFileConvertToCalvin::ConvertXDAFile(), and makeMultiCelFileSubset().
The documentation for this class was generated from the following files:
calvin_files/data/src/CELData.h
calvin_files/data/src/CELData.cpp