Affymetrix Power Tools: MultiChannelHomHiLoCelListener Class Reference
MultiChannelHomHiLoCelListener Class Reference
Class for computing hilo qc metric from a cel set of cel files.
#include <MultiChannelHomHiLoCelListener.h>