Affymetrix Power Tools: CNFamilialReporterFamilial Class Reference
CNFamilialReporterFamilial Class Reference
The Familial file Familial Reporter.
#include <CNFamilialReporterFamilial.h>