Affymetrix Power Tools: CNIntensityAdjustmentMethodPDNN Class Reference
CNIntensityAdjustmentMethodPDNN Class Reference
The PDNN intensity adjustment method.
#include <CNIntensityAdjustmentMethodPDNN.h>