Affymetrix Power Tools: QCAnalysisOptions Class Reference
QCAnalysisOptions Class Reference
A simple class to contain the multiple analysis specified / in a QCA file.
#include <QCAnalysisOptions.h>
Public Member Functions
virtual ~QCAnalysisOptions ()
Virtual Destructor.
Static Public Member Functions
static void readQCAFile (const std::string &qcaFileName, QCAnalysisOptions &opts)
Read in a QCA File and populate a QCAnalysisOptions instance.
static float ToFloat (std::string valString)
Public Attributes
std::string defaultAnalysisName
The default analysis name.
std::vector< QCMethod > methods
Vector of analysis methods.
Detailed Description
A simple class to contain the multiple analysis specified / in a QCA file.
Definition at line 171 of file QCAnalysisOptions.h.
Member Function Documentation
void QCAnalysisOptions::readQCAFile (const std::string & qcaFileName, QCAnalysisOptions & opts) [static]
Read in a QCA File and populate a QCAnalysisOptions instance.
Parameters:
qcaFileName - the name of the qca file to load
opts - the QCAnalysisOptions instance to populate
Todo:
add line number ///
Todo:
have tsv.getError add the file and linenumber
Definition at line 774 of file QCAnalysisOptions.cpp.
References QCMethod::analysis, QCMethod::analysisName, APT_ERR_ABORT, APT_ERR_ASSERT, affx::TsvFile::close(), defaultAnalysisName, Util::downcaseString(), Err::errAbort(), affx::TsvFile::getError(), affx::TsvFile::getHeader(), QCMethod::groupName, methods, affx::TsvFile::nextLevel(), affx::TsvFile::open(), QCMethod::options, affx::TSV_BIND_REQUIRED, affx::TSV_ERR_EOF, affx::TSV_ERR_FILEIO, and affx::TSV_OK.
The documentation for this class was generated from the following files:
chipstream/QCAnalysisOptions.h
chipstream/QCAnalysisOptions.cpp