Affymetrix Power Tools: QuantPlierBase Class Reference
QuantPlierBase Class Reference
Base class for doing probe set quantification using either the PLIER (Probe Logarithmic Error Intensity Estimate) method or the ITER-PLIER method, which iteratively calls PLIER with the probes that best correlate with signal estimate.
#include <QuantPlierBase.h>