Affymetrix Power Tools: CNLog2RatioEngine Class Reference
CNLog2RatioEngine Class Reference
The engine for calculating the log2 ratios.
#include <CNLog2RatioEngine.h>