Affymetrix Power Tools: affymetrix_calvin_io::TextFileWriter Class Reference
affymetrix_calvin_io::TextFileWriter Class Reference
#include <TextFileWriter.h>
Public Member Functions
TextFileWriter ()
~TextFileWriter ()
void WriteFile (const std::string &fileName, std::map< std::string, std::string > &textData)
Protected Member Functions
void OpenFile (const std::string &fileName)
void WriteFileBody (std::map< std::string, std::string > &textData)
void CloseFile ()
Protected Attributes
std::ofstream fileStream
Detailed Description
This class provides interfaces to store text parameter information.
Definition at line 43 of file TextFileWriter.h.
Constructor & Destructor Documentation
TextFileWriter::TextFileWriter ()
Constructor
Definition at line 31 of file TextFileWriter.cpp.
TextFileWriter::~TextFileWriter ()
Destructor
Definition at line 38 of file TextFileWriter.cpp.
Member Function Documentation
void TextFileWriter::CloseFile () [protected]
Closes the file
Definition at line 68 of file TextFileWriter.cpp.
References fileStream, and affymetrix_calvin_utilities::DateTime::GetCurrentDateTime().
Referenced by WriteFile().
void TextFileWriter::OpenFile (const std::string & fileName) [protected]
Opens the file for writing.
Parameters:
fileName The name of the file to open.
Definition at line 55 of file TextFileWriter.cpp.
References fileStream, and affymetrix_calvin_utilities::DateTime::GetCurrentDateTime().
Referenced by WriteFile().
void TextFileWriter::WriteFile (const std::string & fileName, std::map< std::string, std::string > & textData)
Writes the parameters to the text file.
Parameters:
fileName The name of the text file to write.
textData The text file parameter name/value pairs.
Exceptions:
affymetrix_calvin_exceptions::CFileCreateException The output file cannot be created.
affymetrix_calvin_exceptions::CFileWriteException The file was not written properly.
Definition at line 45 of file TextFileWriter.cpp.
References CloseFile(), OpenFile(), and WriteFileBody().
void TextFileWriter::WriteFileBody (std::map< std::string, std::string > & textData) [protected]
Writes the body of the file.
Parameters:
textData The parameter name/value pairs.
Definition at line 81 of file TextFileWriter.cpp.
References fileStream.
Referenced by WriteFile().
Member Data Documentation
std::ofstream affymetrix_calvin_io::TextFileWriter::fileStream [protected]
The file stream.
Definition at line 54 of file TextFileWriter.h.
Referenced by CloseFile(), OpenFile(), and WriteFileBody().
The documentation for this class was generated from the following files:
calvin_files/writers/src/TextFileWriter.h
calvin_files/writers/src/TextFileWriter.cpp