Affymetrix Power Tools: affxchp::CCHPFileHeader Class Reference
affxchp::CCHPFileHeader Class Reference
#include <CHPFileData.h>
Public Types
enum GeneChipAssayType {
Expression, Genotyping, Resequencing, Universal,
Unknown
}
Public Member Functions
CCHPFileHeader ()
~CCHPFileHeader ()
int GetCols () const
int GetRows () const
int GetNumProbeSets () const
GeneChipAssayType GetAssayType () const
std::string GetChipType () const
std::string GetAlgName () const
std::string GetAlgVersion () const
TagValuePairTypeList & AlgorithmParameters ()
TagValuePairTypeList & SummaryParameters ()
std::string GetParentCellFile () const
std::string GetProgID () const
std::string GetAlgorithmParameter (const char *tag)
std::string GetSummaryParameter (const char *tag)
BackgroundZoneInfo & GetBackgroundZoneInfo ()
BackgroundZoneTypeList & GetBackgroundZones ()
BackgroundZoneType GetBackgroundZone (int x, int y)
int GetMagicNumber () const
int GetVersionNumber () const
void SetCols (int n)
void SetRows (int n)
void SetNumProbeSets (int n)
void SetAssayType (GeneChipAssayType t)
void SetChipType (const char *s)
void SetAlgName (const char *s)
void SetAlgVersion (const char *s)
void SetParentCellFile (const char *s)
void SetProgID (const char *s)
Protected Member Functions
void ParseString (TagValuePairTypeList &tagList, std::string strSource, std::string sDelimiter1, std::string sDelimiter2)
void Clear ()
Protected Attributes
int m_Magic
int m_Version
unsigned short m_Cols
unsigned short m_Rows
int m_NumProbeSets
GeneChipAssayType m_AssayType
std::string m_ChipType
std::string m_AlgorithmName
std::string m_AlgorithmVersion
std::string m_ParentCellFile
std::string m_ProgID
TagValuePairTypeList m_AlgorithmParameters
TagValuePairTypeList m_SummaryParameters
BackgroundZoneInfo m_BackgroundZoneInfo
Friends
class CCHPFileData
Detailed Description
This class provides storage for the CHP file header
Definition at line 99 of file CHPFileData.h.
Member Enumeration Documentation
enum affxchp::CCHPFileHeader::GeneChipAssayType
Defines the assay type for the array
Definition at line 110 of file CHPFileData.h.
Constructor & Destructor Documentation
CCHPFileHeader::CCHPFileHeader ()
Constructor
Definition at line 199 of file CHPFileData.cpp.
References Clear().
CCHPFileHeader::~CCHPFileHeader ()
Destructor
Definition at line 228 of file CHPFileData.cpp.
References Clear().
Member Function Documentation
TagValuePairTypeList& affxchp::CCHPFileHeader::AlgorithmParameters () [inline]
Gets the algorithm parameters
Returns:
The number of feature columns
Definition at line 211 of file CHPFileData.h.
References m_AlgorithmParameters.
Referenced by affxchpwriter::CCHPFileWriter::AddAlgorithmParameter(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetAlgorithmParameterCount(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetAlgorithmParameters(), and affxchpwriter::CCHPFileWriter::SaveHeader().
void CCHPFileHeader::Clear (void) [protected]
Clears the class members
Definition at line 206 of file CHPFileData.cpp.
References m_AlgorithmName, m_AlgorithmParameters, m_AlgorithmVersion, m_AssayType, m_BackgroundZoneInfo, m_ChipType, m_Cols, m_Magic, m_NumProbeSets, m_ParentCellFile, m_ProgID, m_Rows, m_SummaryParameters, m_Version, affxchp::_BackgroundZoneInfo::number_zones, affxchp::_BackgroundZoneInfo::smooth_factor, and affxchp::_BackgroundZoneInfo::zones.
Referenced by CCHPFileHeader(), affxchp::CCHPFileData::Clear(), and ~CCHPFileHeader().
std::string affxchp::CCHPFileHeader::GetAlgName () const [inline]
Gets the algorithm name
Returns:
The algorithm name
Definition at line 201 of file CHPFileData.h.
References m_AlgorithmName.
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetAlgName(), and affxchpwriter::CCHPFileWriter::SaveHeader().
std::string CCHPFileHeader::GetAlgorithmParameter (const char * tag)
Gets a specific algorithm parameter given a name/tag
Returns:
The specific algorithm parameter given a name/tag
Definition at line 147 of file CHPFileData.cpp.
References m_AlgorithmParameters.
Referenced by affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetAlgorithmParameter().
std::string affxchp::CCHPFileHeader::GetAlgVersion () const [inline]
Gets the algorithm version
Returns:
The algorithm version
Definition at line 206 of file CHPFileData.h.
References m_AlgorithmVersion.
Referenced by affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetAlgVersion(), and affxchpwriter::CCHPFileWriter::SaveHeader().
GeneChipAssayType affxchp::CCHPFileHeader::GetAssayType () const [inline]
Gets the assay type
Returns:
The assay type
Definition at line 191 of file CHPFileData.h.
References m_AssayType.
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetAssayType(), affxchp::CCHPFileData::GetExpressionResults(), affxchp::CCHPFileData::GetGenotypingResults(), affxchp::CCHPFileData::GetResequencingResults(), affxchp::CCHPFileData::GetUniversalResults(), affxchpwriter::CCHPFileWriter::Save(), affxchpwriter::CCHPFileWriter::SaveHeader(), affymetrix_chp_converter::CHPConversionUtilities::SetAlgName(), affxchpwriter::CCHPFileWriter::SetAlgorithmName(), and affymetrix_chp_converter::CHPFileConvertToCalvin::ValidateMas5File().
BackgroundZoneType CCHPFileHeader::GetBackgroundZone (int x, int y)
Gets the background value for a given center coordinate
Returns:
The background value for a given center coordinate
Definition at line 181 of file CHPFileData.cpp.
References m_BackgroundZoneInfo, and affxchp::_BackgroundZoneInfo::zones.
Referenced by affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetBackgroundZone().
BackgroundZoneInfo& affxchp::CCHPFileHeader::GetBackgroundZoneInfo () [inline]
Gets the background zone information
Returns:
The background zone information
Definition at line 241 of file CHPFileData.h.
References m_BackgroundZoneInfo.
Referenced by affxchpwriter::CCHPFileWriter::AddBackgroundInfo(), affxchpwriter::CCHPFileWriter::AddBackgroundZone(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetBackgroundZoneInfo(), and affxchpwriter::CCHPFileWriter::SaveHeader().
BackgroundZoneTypeList& affxchp::CCHPFileHeader::GetBackgroundZones () [inline]
Gets the list of background zone positions and values
Returns:
The list of background zone positions and values
Definition at line 246 of file CHPFileData.h.
References m_BackgroundZoneInfo, and affxchp::_BackgroundZoneInfo::zones.
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile(), and affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetBackgroundZones().
std::string affxchp::CCHPFileHeader::GetChipType () const [inline]
Gets the chip type
Returns:
The chip type
Definition at line 196 of file CHPFileData.h.
References m_ChipType.
Referenced by affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetChipType(), and affxchpwriter::CCHPFileWriter::SaveHeader().
int affxchp::CCHPFileHeader::GetCols () const [inline]
Gets the number of feature columns
Returns:
The number of feature columns
Definition at line 176 of file CHPFileData.h.
References m_Cols.
Referenced by affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetCols(), and affxchpwriter::CCHPFileWriter::SaveHeader().
int affxchp::CCHPFileHeader::GetMagicNumber () const [inline]
Gets the magic number
Returns:
The magic number
Definition at line 256 of file CHPFileData.h.
References m_Magic.
Referenced by affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetMagic().
int affxchp::CCHPFileHeader::GetNumProbeSets () const [inline]
Gets the number of probe sets
Returns:
The number of probe sets
Definition at line 186 of file CHPFileData.h.
References m_NumProbeSets.
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile(), affxchp::CCHPFileData::GetExpressionResults(), affxchp::CCHPFileData::GetGenotypingResults(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetNumProbeSets(), affxchp::CCHPFileData::GetUniversalResults(), affxchpwriter::CCHPFileWriter::Save(), and affxchpwriter::CCHPFileWriter::SaveHeader().
std::string affxchp::CCHPFileHeader::GetParentCellFile () const [inline]
Gets the parent CEL file
Returns:
The parent CEL file
Definition at line 221 of file CHPFileData.h.
References m_ParentCellFile.
Referenced by affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetParentCellFile(), and affxchpwriter::CCHPFileWriter::SaveHeader().
std::string affxchp::CCHPFileHeader::GetProgID () const [inline]
Gets the prog ID
Returns:
The prog ID
Definition at line 226 of file CHPFileData.h.
References m_ProgID.
Referenced by affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetProgID(), and affxchpwriter::CCHPFileWriter::SaveHeader().
int affxchp::CCHPFileHeader::GetRows () const [inline]
Gets the number of feature rows
Returns:
The number of feature rows
Definition at line 181 of file CHPFileData.h.
References m_Rows.
Referenced by affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetRows(), and affxchpwriter::CCHPFileWriter::SaveHeader().
std::string CCHPFileHeader::GetSummaryParameter (const char * tag)
Gets a specific summary parameter given a name/tag
Returns:
The specific summary parameter given a name/tag
Definition at line 164 of file CHPFileData.cpp.
References m_SummaryParameters.
Referenced by affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetSummaryParameter().
int affxchp::CCHPFileHeader::GetVersionNumber () const [inline]
Gets the version number
Returns:
The version number
Definition at line 261 of file CHPFileData.h.
References m_Version.
Referenced by affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetVersion().
void CCHPFileHeader::ParseString (TagValuePairTypeList & tagList, std::string strSource, std::string sDelimiter1, std::string sDelimiter2) [protected]
Parses the parameters string into a list given the delimiters.
Parameters:
tagList The resulting parameter name/value list.
strSource The parameters in a string representation
sDelimiter1 The delimiter between each parameter
sDelimiter2 The delimiter between the tag and value
Definition at line 61 of file CHPFileData.cpp.
References _TagValuePairType::Tag, and _TagValuePairType::Value.
Referenced by affxchp::CCHPFileData::Open().
void affxchp::CCHPFileHeader::SetAlgName (const char * s) [inline]
Sets the algorithm name
Parameters:
s The algorithm name.
Definition at line 291 of file CHPFileData.h.
References m_AlgorithmName.
Referenced by affxchpwriter::CCHPFileWriter::SetAlgorithmName().
void affxchp::CCHPFileHeader::SetAlgVersion (const char * s) [inline]
Sets the algorithm version
Parameters:
s The algorithm version.
Definition at line 296 of file CHPFileData.h.
References m_AlgorithmVersion.
Referenced by affxchpwriter::CCHPFileWriter::SetAlgorithmVersion().
void affxchp::CCHPFileHeader::SetAssayType (GeneChipAssayType t) [inline]
Sets the assay type
Parameters:
t The assay type.
Definition at line 281 of file CHPFileData.h.
References m_AssayType.
Referenced by affxchpwriter::CCHPFileWriter::InitializeForWriting(), and affymetrix_chp_converter::CHPConversionUtilities::SetAlgName().
void affxchp::CCHPFileHeader::SetChipType (const char * s) [inline]
Sets the chip type or probe array type
Parameters:
s The chip type or probe array type.
Definition at line 286 of file CHPFileData.h.
References m_ChipType.
Referenced by affymetrix_chp_converter::CHPFileConvertToXDA::ConvertCalvinFile(), and affxchpwriter::CCHPFileWriter::InitializeForWriting().
void affxchp::CCHPFileHeader::SetCols (int n) [inline]
Sets the number of columns
Parameters:
n The number of columns.
Definition at line 266 of file CHPFileData.h.
References m_Cols.
Referenced by affxchpwriter::CCHPFileWriter::InitializeForWriting().
void affxchp::CCHPFileHeader::SetNumProbeSets (int n) [inline]
Sets the number of probe sets
Parameters:
n The number of probe sets.
Definition at line 276 of file CHPFileData.h.
References m_NumProbeSets.
Referenced by affxchpwriter::CCHPFileWriter::InitializeForWriting().
void affxchp::CCHPFileHeader::SetParentCellFile (const char * s) [inline]
Sets the parent CEL file
Parameters:
s The parent CEL file.
Definition at line 301 of file CHPFileData.h.
References m_ParentCellFile.
Referenced by affxchpwriter::CCHPFileWriter::SetParentCelFileName().
void affxchp::CCHPFileHeader::SetProgID (const char * s) [inline]
Sets the prog ID
Parameters:
s The programatic identifier
Definition at line 306 of file CHPFileData.h.
References m_ProgID.
Referenced by affxchpwriter::CCHPFileWriter::SetProgID().
void affxchp::CCHPFileHeader::SetRows (int n) [inline]
Sets the number of rows
Parameters:
n The number of rows.
Definition at line 271 of file CHPFileData.h.
References m_Rows.
Referenced by affxchpwriter::CCHPFileWriter::InitializeForWriting().
TagValuePairTypeList& affxchp::CCHPFileHeader::SummaryParameters () [inline]
Gets the summary parameters
Returns:
The summary parameters
Definition at line 216 of file CHPFileData.h.
References m_SummaryParameters.
Referenced by affxchpwriter::CCHPFileWriter::AddChipSummaryParameter(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetSummaryParameterCount(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetSummaryParameters(), and affxchpwriter::CCHPFileWriter::SaveHeader().
Friends And Related Function Documentation
friend class CCHPFileData [friend]
Friend to the parent object
Definition at line 170 of file CHPFileData.h.
Member Data Documentation
std::string affxchp::CCHPFileHeader::m_AlgorithmName [protected]
The name of the algorithm used to create the CHP file
Definition at line 135 of file CHPFileData.h.
Referenced by Clear(), GetAlgName(), affxchp::CCHPFileData::Open(), and SetAlgName().
TagValuePairTypeList affxchp::CCHPFileHeader::m_AlgorithmParameters [protected]
The list of algorithm parameters
Definition at line 147 of file CHPFileData.h.
Referenced by AlgorithmParameters(), Clear(), GetAlgorithmParameter(), and affxchp::CCHPFileData::Open().
std::string affxchp::CCHPFileHeader::m_AlgorithmVersion [protected]
The version number of the algorithm used to create the CHP file
Definition at line 138 of file CHPFileData.h.
Referenced by Clear(), GetAlgVersion(), affxchp::CCHPFileData::Open(), and SetAlgVersion().
GeneChipAssayType affxchp::CCHPFileHeader::m_AssayType [protected]
The type of results stored in the CHP file
Definition at line 129 of file CHPFileData.h.
Referenced by Clear(), GetAssayType(), affxchp::CCHPFileData::Open(), and SetAssayType().
BackgroundZoneInfo affxchp::CCHPFileHeader::m_BackgroundZoneInfo [protected]
The background's for each of the zones (calculated by the expression algorithm)
Definition at line 153 of file CHPFileData.h.
Referenced by Clear(), GetBackgroundZone(), GetBackgroundZoneInfo(), GetBackgroundZones(), and affxchp::CCHPFileData::Open().
std::string affxchp::CCHPFileHeader::m_ChipType [protected]
The chip type or probe array type of the CHP file
Definition at line 132 of file CHPFileData.h.
Referenced by Clear(), GetChipType(), affxchp::CCHPFileData::Open(), and SetChipType().
unsigned short affxchp::CCHPFileHeader::m_Cols [protected]
The number of feature columns in the array
Definition at line 120 of file CHPFileData.h.
Referenced by Clear(), GetCols(), affxchp::CCHPFileData::Open(), and SetCols().
int affxchp::CCHPFileHeader::m_Magic [protected]
The magic number in the file
Definition at line 114 of file CHPFileData.h.
Referenced by Clear(), GetMagicNumber(), and affxchp::CCHPFileData::Open().
int affxchp::CCHPFileHeader::m_NumProbeSets [protected]
The number of probe set results
Definition at line 126 of file CHPFileData.h.
Referenced by Clear(), GetNumProbeSets(), affxchp::CCHPFileData::Open(), and SetNumProbeSets().
std::string affxchp::CCHPFileHeader::m_ParentCellFile [protected]
The name of the CEL file used in the creation of the CHP file
Definition at line 141 of file CHPFileData.h.
Referenced by Clear(), GetParentCellFile(), affxchp::CCHPFileData::Open(), and SetParentCellFile().
std::string affxchp::CCHPFileHeader::m_ProgID [protected]
The programmatic identifier of the algorithm used to create the CHP file
Definition at line 144 of file CHPFileData.h.
Referenced by Clear(), GetProgID(), affxchp::CCHPFileData::Open(), and SetProgID().
unsigned short affxchp::CCHPFileHeader::m_Rows [protected]
The number of feature rows in the array
Definition at line 123 of file CHPFileData.h.
Referenced by Clear(), GetRows(), affxchp::CCHPFileData::Open(), and SetRows().
TagValuePairTypeList affxchp::CCHPFileHeader::m_SummaryParameters [protected]
A list of summary parameters generated by the CHP file generating algorithm
Definition at line 150 of file CHPFileData.h.
Referenced by Clear(), GetSummaryParameter(), affxchp::CCHPFileData::Open(), and SummaryParameters().
int affxchp::CCHPFileHeader::m_Version [protected]
The version number in the file
Definition at line 117 of file CHPFileData.h.
Referenced by Clear(), GetVersionNumber(), and affxchp::CCHPFileData::Open().
The documentation for this class was generated from the following files:
file/CHPFileData.h
file/CHPFileData.cpp