Affymetrix Power Tools: affxcdf::CCDFQCProbeInformation Class Reference
affxcdf::CCDFQCProbeInformation Class Reference
#include <CDFFileData.h>
Public Member Functions
CCDFQCProbeInformation ()
int GetX () const
int GetY () const
int GetPLen () const
bool IsPerfectMatchProbe () const
bool IsBackgroundProbe () const
Protected Attributes
unsigned short m_X
unsigned short m_Y
unsigned char m_PLen
unsigned char m_PMProbe
unsigned char m_Background
Friends
class CCDFQCProbeSetInformation
class CCDFFileData
Detailed Description
This class provides storage for QC probes
Definition at line 644 of file CDFFileData.h.
Constructor & Destructor Documentation
CCDFQCProbeInformation::CCDFQCProbeInformation ()
Constructor
Definition at line 153 of file CDFFileData.cpp.
Member Function Documentation
int affxcdf::CCDFQCProbeInformation::GetPLen () const [inline]
Gets the probe length.
Returns:
The probe length. This value may be 1 for non-synthesized features.
Definition at line 686 of file CDFFileData.h.
References m_PLen.
Referenced by affymetrix_fusion_io::FusionCDFQCProbeInformation::GetPLen().
int affxcdf::CCDFQCProbeInformation::GetX () const [inline]
Gets the X coordinate of the probe.
Returns:
The X coordinate.
Definition at line 676 of file CDFFileData.h.
References m_X.
Referenced by affymetrix_fusion_io::FusionCDFQCProbeInformation::GetX().
int affxcdf::CCDFQCProbeInformation::GetY () const [inline]
Gets the Y cooridnate of the probe.
Returns:
The Y coordinate.
Definition at line 681 of file CDFFileData.h.
References m_Y.
Referenced by affymetrix_fusion_io::FusionCDFQCProbeInformation::GetY().
bool affxcdf::CCDFQCProbeInformation::IsBackgroundProbe () const [inline]
Gets a flag indicating if the probe is used for background calculations (blank feature).
Returns:
Flag indicating if the probe is used for background calculations (blank feature).
Definition at line 696 of file CDFFileData.h.
References m_Background.
Referenced by affymetrix_fusion_io::FusionCDFQCProbeInformation::IsBackgroundProbe().
bool affxcdf::CCDFQCProbeInformation::IsPerfectMatchProbe () const [inline]
Gets the flag indicating if the probe is a perfect match probe.
Returns:
The flag indicating if the probe is a perfect match probe
Definition at line 691 of file CDFFileData.h.
References m_PMProbe.
Referenced by affymetrix_fusion_io::FusionCDFQCProbeInformation::IsPerfectMatchProbe().
Friends And Related Function Documentation
friend class CCDFFileData [friend]
Friend to the top level CDF class
Definition at line 670 of file CDFFileData.h.
friend class CCDFQCProbeSetInformation [friend]
Friend to the parent class
Definition at line 667 of file CDFFileData.h.
Member Data Documentation
unsigned char affxcdf::CCDFQCProbeInformation::m_Background [protected]
Flag indicating if the probe is used for background calculations (blank feature).
Definition at line 664 of file CDFFileData.h.
Referenced by IsBackgroundProbe(), and affxcdf::CCDFFileData::ReadTextFormat().
unsigned char affxcdf::CCDFQCProbeInformation::m_PLen [protected]
The probe length. This value may be 1 for non-synthesized features
Definition at line 658 of file CDFFileData.h.
Referenced by GetPLen(), and affxcdf::CCDFFileData::ReadTextFormat().
unsigned char affxcdf::CCDFQCProbeInformation::m_PMProbe [protected]
Flag indicating if the probe is a perfect match probe.
Definition at line 661 of file CDFFileData.h.
Referenced by IsPerfectMatchProbe(), and affxcdf::CCDFFileData::ReadTextFormat().
unsigned short affxcdf::CCDFQCProbeInformation::m_X [protected]
The X coordinate of the probe
Definition at line 652 of file CDFFileData.h.
Referenced by GetX(), and affxcdf::CCDFFileData::ReadTextFormat().
unsigned short affxcdf::CCDFQCProbeInformation::m_Y [protected]
The Y coordinate of the probe
Definition at line 655 of file CDFFileData.h.
Referenced by GetY(), and affxcdf::CCDFFileData::ReadTextFormat().
The documentation for this class was generated from the following files:
file/CDFFileData.h
file/CDFFileData.cpp