Affymetrix Power Tools: CNAnalysisMethodCNGender Class Reference
CNAnalysisMethodCNGender Class Reference
The CNGender analysis method.
#include <CNAnalysisMethodCNGender.h>