Affymetrix Power Tools: CNReporter Class Reference
CNReporter Class Reference
A base class for copy number reporters.
#include <CNReporter.h>