Affymetrix Power Tools: CNAnalysisMethodCovariateSignalAdjuster Class Reference
CNAnalysisMethodCovariateSignalAdjuster Class Reference
CNAnalysisMethodCovariateSignalAdjuster - Class for doing covariate-based signal adjustment.
#include <CNAnalysisMethodCovariateSignalAdjuster.h>