Affymetrix Power Tools: MedNormTran Class Reference
MedNormTran Class Reference
MedNormTran - Class for doing median, or average, normalization.
#include <MedNormTran.h>