Affymetrix Power Tools: CNAnalysisMethodKernelSmooth Class Reference
CNAnalysisMethodKernelSmooth Class Reference
The log2 ration Kernel smooth analysis method.
#include <CNAnalysisMethodKernelSmooth.h>