Affymetrix Power Tools: AnalysisStreamFactory Class Reference
AnalysisStreamFactory Class Reference
Object for making new analysis streams from a text specification.
#include <AnalysisStreamFactory.h>
Public Member Functions
AnalysisStreamFactory (QuantMethodFactory::QuantType type=QuantMethodFactory::Expression)
Constructor.
~AnalysisStreamFactory ()
Destructor.
AnalysisStream * constructAnalysisStream (const std::string &s, ChipLayout &layout, std::map< std::string, std::string > &stdMethods, std::string analysisName="")
Factory for created AnalysisStreams from a string description.
AnalysisStreamExpression * constructExpressionAnalysisStream (const std::string &s, ChipLayout &layout, std::map< std::string, std::string > &stdMethods, std::string analysisName="")
Factory for creatng mRNA expression AnalysisStream from a string description.
AnalysisStreamExpression * constructExpressionAnalysisStages (const std::string &s, ChipLayout &layout, std::map< std::string, std::string > &stdMethods, std::string analysisName)
Factory for creatng mRNA expression AnalysisStream from a string description.
AnalysisStreamGType * constructGTypeAnalysisStream (const std::string &s, ChipLayout &layout, std::map< std::string, std::string > &stdMethods, std::string analysisName="")
Factory for creatng Genotype SNP chip AnalysisStream from a string description.
AnalysisStream * constructAnalysisStream (const std::string &s, ChipLayout &layout, std::string analysisName="")
Factory for created AnalysisStreams from a string description.
void setGcControlProbes (const std::vector< Probe * > &gcControlProbes)
Specify the probes that should be used for gc controls.
const std::vector< Probe * > & getGcControlProbes ()
Get the vector of probes that are considered to be background.
void readPrecompFeatureEffectsFromFile (int iProbeCount, const std::string &fileName, const ChipLayout layout)
Parse the feature responses from a text file.
void readPrecompFeatureEffectsFrom_A5 (int iProbeCount, affx::File5_Group *group5, const std::string &name, const ChipLayout layout)
void readControlProbes (const std::string &fileName)
Read in the control probes from a text file.
void setWriteSketchDir (const std::string &writeSketchDir)
Toggle whether or not we're writing out the normalization distribution.
void setWriteSketchDir_a5 (const std::string &writeSketchDir)
void setWriteSketchGroup_a5 (affx::File5_Group *group5)
void setWriteProfileDir (const std::string &writeProfileDir)
Profile.
void setreadReferenceProfile (const std::string &fileName)
void readTargetSketchFromFile (const std::string &fileName)
Read in the target sketch from a.
void readTargetSketchFromFile_a5 (const std::string &fileName)
void readTargetSketchFromFile_a5_tsv (affx::File5_Group *group5, const std::string &tsv_name)
void setAnnotationFileName (const std::string &str)
Set the annotation-file.
std::vector< SelfDoc > getDocs ()
Get the vector of documentation objects that this factory is aware of.
void setCelFileCount (unsigned int ui)
ChipStreamDataTransform * chipstreamStageFromSpec (AnalysisStream *stream, ChipLayout &layout)
Static Public Member Functions
static void probeListFromBgpFile (const std::string &fileName, std::vector< Probe * > &controlProbes)
Load up a list of probes from a .bgp file.
static void setupAnalysisStreamFactory (AnalysisStreamFactory &asFactory, affx::File5_File *inputFile, affx::File5_Group *inputGroup, affx::File5_File *outputFile, affx::File5_Group *outputGroup, uint32_t celFileCount, uint32_t probeCount, const std::string &outDir, bool writeSketch, const std::string &targetSketch, bool writeProfile, const std::string &referenceProfile, bool a5Sketch, bool a5SketchUseGlobal, bool a5SketchInputGlobal, const std::string &a5SketchInputFile, const std::string &a5SketchInputName, const std::string &a5SketchInputGroup, const std::string &useFeatEff, bool a5FeatureEffectsInputGlobal, const std::string &a5FeatureEffectsInputFile, const std::string &a5FeatureEffectsInputName, const std::string &a5FeatureEffectsInputGroup, const std::string &a5InputGroup, const std::string &a5Group, const std::string &setAnalysisName, const std::string &quantMethodSpec, const std::string &bgpFile, const std::string &AnnotFile, const ChipLayout &layout)
Public Attributes
ChipStreamFactory m_CsFac
Module for making chipstreams.
PmAdjusterFactory m_PmAdjustFac
Module for making pmadjusters.
QuantMethodFactory m_QuantMethFac
Module for making quantification methods.
Protected Member Functions
AnalysisStreamExpression * tryToMakeAnalysisStream (const std::string &spec)
void fillInAnalysisStream (AnalysisStream *stream, ChipLayout &layout, std::string &pmSpec, std::vector< std::string > &chipStreamSpec, std::string &name)
Utility function to fill the chipstream and pm adjuster portions of analysisstream.
void fillInAnalysisStages (AnalysisStream *stream, ChipLayout &layout, const std::string &pmSpec, std::vector< std::string > &chipStreamSpec, std::string &name)
Protected Attributes
std::vector< Probe * > m_GcControlProbes
Probes to be used for background distributions. /// Note that memory is owned elsewhere.
QuantMethodFactory::QuantType m_QuantType
What type of quantification are we doing? i.e. Expression, GenoType.
std::vector< SelfDoc > m_Docs
Self documentation.
std::vector
< SelfCreate::selfCreator > m_Creators
Self creation.
unsigned int m_uiCelFileCount
Detailed Description
Object for making new analysis streams from a text specification.
Encapsulates all the work of separately making chipstream, pm adjuster and quantification methods.
Definition at line 56 of file AnalysisStreamFactory.h.
Constructor & Destructor Documentation
AnalysisStreamFactory::AnalysisStreamFactory (QuantMethodFactory::QuantType type = QuantMethodFactory::Expression) [inline]
Constructor.
Parameters:
What type of Quantification method will be used? I.e. Expression, GenoType, ...
Definition at line 65 of file AnalysisStreamFactory.h.
References AnalysisStreamExpSpectSel::explainSelf(), AnalysisStreamExpPcaSel::explainSelf(), AnalysisStreamExpression::explainSelf(), m_Creators, m_Docs, m_QuantType, AnalysisStreamExpSpectSel::newObject(), AnalysisStreamExpPcaSel::newObject(), and AnalysisStreamExpression::newObject().
AnalysisStreamFactory::~AnalysisStreamFactory () [inline]
Destructor.
Definition at line 80 of file AnalysisStreamFactory.h.
References m_GcControlProbes.
Member Function Documentation
AnalysisStream* AnalysisStreamFactory::constructAnalysisStream (const std::string & s, ChipLayout & layout, std::string analysisName = "") [inline]
Factory for created AnalysisStreams from a string description.
Parameters:
s - String description.
layout - Probe and probe set info.
analysisName -
Returns:
analysis stream requested.
Definition at line 140 of file AnalysisStreamFactory.h.
References constructAnalysisStream().
AnalysisStream * AnalysisStreamFactory::constructAnalysisStream (const std::string & s, ChipLayout & layout, std::map< std::string, std::string > & stdMethods, std::string analysisName = "")
Factory for created AnalysisStreams from a string description.
Parameters:
s - String description.
layout - Probe and probe set info.
stdMethods - Aliases for standard methods like RMA.
Returns:
analysis stream requested.
Definition at line 118 of file AnalysisStreamFactory.cpp.
References Util::chopString(), Err::errAbort(), fillInAnalysisStream(), m_QuantMethFac, m_QuantType, QuantMethodFactory::quantMethodForString(), AnalysisStream::setName(), and AnalysisStream::setQuantMethod().
Referenced by callGenotypes(), constructAnalysisStream(), doRma(), MultiChannelNonOverlapCelListener::GimmeContrast(), and MultiChannelHomHiLoCelListener::GimmeContrast().
AnalysisStreamExpression * AnalysisStreamFactory::constructExpressionAnalysisStages (const std::string & s, ChipLayout & layout, std::map< std::string, std::string > & stdMethods, std::string analysisName)
Factory for creatng mRNA expression AnalysisStream from a string description.
Parameters:
s - String description.
layout - Probe and probe set info.
stdMethods - Aliases for standard methods like RMA.
Returns:
analysis stream requested.
Definition at line 261 of file AnalysisStreamFactory.cpp.
References ChipStreamFactory::chipStreamForString(), Util::chopString(), Err::errAbort(), SelfDoc::getDocName(), AnalysisStream::getName(), m_CsFac, m_QuantMethFac, m_QuantType, QuantMethodFactory::quantExprMethodForString(), AnalysisStream::setName(), and AnalysisStreamExpression::setQuantMethod().
AnalysisStreamExpression * AnalysisStreamFactory::constructExpressionAnalysisStream (const std::string & s, ChipLayout & layout, std::map< std::string, std::string > & stdMethods, std::string analysisName = "")
Factory for creatng mRNA expression AnalysisStream from a string description.
Parameters:
s - String description.
layout - Probe and probe set info.
stdMethods - Aliases for standard methods like RMA.
Returns:
analysis stream requested.
Definition at line 184 of file AnalysisStreamFactory.cpp.
References ChipStreamFactory::chipStreamForString(), Util::chopString(), Err::errAbort(), fillInAnalysisStream(), SelfDoc::getDocName(), AnalysisStream::getName(), ChipStreamFactory::getTargetSketchSize(), m_CsFac, m_QuantMethFac, m_QuantType, QuantMethodFactory::quantExprMethodForString(), AnalysisStream::setName(), AnalysisStreamExpression::setQuantMethod(), and ToStr().
AnalysisStreamGType * AnalysisStreamFactory::constructGTypeAnalysisStream (const std::string & s, ChipLayout & layout, std::map< std::string, std::string > & stdMethods, std::string analysisName = "")
Factory for creatng Genotype SNP chip AnalysisStream from a string description.
Parameters:
s - String description.
layout - Probe and probe set info.
stdMethods - Aliases for standard methods like RMA.
Returns:
analysis stream requested.
Definition at line 340 of file AnalysisStreamFactory.cpp.
References Util::chopString(), Err::errAbort(), fillInAnalysisStream(), m_QuantMethFac, m_QuantType, QuantMethodFactory::quantGTypeMethodForString(), AnalysisStream::setName(), and AnalysisStreamGType::setQuantMethod().
void AnalysisStreamFactory::fillInAnalysisStream (AnalysisStream * stream, ChipLayout & layout, std::string & pmSpec, std::vector< std::string > & chipStreamSpec, std::string & name) [protected]
Utility function to fill the chipstream and pm adjuster portions of analysisstream.
Allows functions like constructAnalysisStream() and constructExpressionAnalysisStream() to share same methods for doing this and then just cap with QuantificationMethod.
Parameters:
stream - Stream to be filled in.
layout - Information about layout of probes on chip.
pmSpec - String description of pm adjuster.
chipStreamSpec - Vector of strings describing chipstream modules to be created.
name - Name to be filled in as pm adjusters and chipstream modules are created.
Definition at line 58 of file AnalysisStreamFactory.cpp.
References AnalysisStream::addChipStream(), ChipStreamFactory::chipStreamForString(), PmAdjuster::getType(), IntensityTransformer::getType(), m_CsFac, m_PmAdjustFac, PmAdjusterFactory::pmAdjusterForString(), and AnalysisStream::setPmAdjuster().
Referenced by constructAnalysisStream(), constructExpressionAnalysisStream(), and constructGTypeAnalysisStream().
std::vector<SelfDoc> AnalysisStreamFactory::getDocs () [inline]
Get the vector of documentation objects that this factory is aware of.
Returns:
- vector of documentation objects.
Definition at line 271 of file AnalysisStreamFactory.h.
References m_Docs.
Referenced by EngineUtil::explainParameter().
const std::vector<Probe *>& AnalysisStreamFactory::getGcControlProbes () [inline]
Get the vector of probes that are considered to be background.
Returns:
vector of the probe pointers that are being used.
Definition at line 176 of file AnalysisStreamFactory.h.
References m_GcControlProbes.
void AnalysisStreamFactory::probeListFromBgpFile (const std::string & fileName, std::vector< Probe * > & controlProbes) [static]
Load up a list of probes from a .bgp file.
Parameters:
fileName - name of bgp file.
controlProbes - vector to be filled in with probes.
Definition at line 387 of file AnalysisStreamFactory.cpp.
References affx::BgpFile::close(), Err::errAbort(), Probe::id, affx::BgpFile::next_bgprobe(), affx::BgpFile::open(), and ToStr().
Referenced by readControlProbes(), and DataStore::setValues().
void AnalysisStreamFactory::readControlProbes (const std::string & fileName) [inline]
Read in the control probes from a text file.
File must be tab delimited and contain columns named "probe_id" and "gc_count"
Parameters:
fileName - file containing the control probes.
Definition at line 202 of file AnalysisStreamFactory.h.
References m_CsFac, m_GcControlProbes, m_PmAdjustFac, m_QuantMethFac, probeListFromBgpFile(), ChipStreamFactory::setControlProbes(), PmAdjusterFactory::setControlProbes(), and QuantMethodFactory::setGcControlProbes().
void AnalysisStreamFactory::readPrecompFeatureEffectsFromFile (int iProbeCount, const std::string & fileName, const ChipLayout layout) [inline]
Parse the feature responses from a text file.
File must be tab delimited and contain the columns: "probeset_id", "atom_id", and "feature_response"
Parameters:
fileName - file containing feature responses.
Definition at line 187 of file AnalysisStreamFactory.h.
References m_QuantMethFac, and QuantMethodFactory::readPrecompFeatureEffectsFromFile().
void AnalysisStreamFactory::readTargetSketchFromFile (const std::string & fileName) [inline]
Read in the target sketch from a.
Parameters:
fileName
Definition at line 242 of file AnalysisStreamFactory.h.
References m_CsFac, and ChipStreamFactory::readTargetSketchFromFile().
Referenced by callGenotypes(), MultiChannelNonOverlapCelListener::GimmeContrast(), and MultiChannelHomHiLoCelListener::GimmeContrast().
void AnalysisStreamFactory::setAnnotationFileName (const std::string & str) [inline]
Set the annotation-file.
Parameters:
fileName
Definition at line 257 of file AnalysisStreamFactory.h.
References m_CsFac, and ChipStreamFactory::setAnnotationFileName().
void AnalysisStreamFactory::setGcControlProbes (const std::vector< Probe * > & gcControlProbes) [inline]
Specify the probes that should be used for gc controls.
Parameters:
gcControlProbes - Which probes are considered background.
Definition at line 158 of file AnalysisStreamFactory.h.
References Probe::cloneProbe(), m_CsFac, m_GcControlProbes, m_PmAdjustFac, m_QuantMethFac, ChipStreamFactory::setControlProbes(), PmAdjusterFactory::setControlProbes(), and QuantMethodFactory::setGcControlProbes().
void AnalysisStreamFactory::setWriteSketchDir (const std::string & writeSketchDir) [inline]
Toggle whether or not we're writing out the normalization distribution.
Parameters:
writeSketch - true to write out the distrubtion false otherwise.
Definition at line 215 of file AnalysisStreamFactory.h.
References m_CsFac, and ChipStreamFactory::setWriteSketchDir().
Referenced by callGenotypes().
The documentation for this class was generated from the following files:
chipstream/AnalysisStreamFactory.h
chipstream/AnalysisStreamFactory.cpp