Affymetrix Power Tools: affymetrix_comparer::CHPComparer Class Reference
affymetrix_comparer::CHPComparer Class Reference
#include <CHPComparer.h>
Public Member Functions
void Clear ()
bool CompareFiles (const char *file1, const char *file2)
std::string Differences () const
Detailed Description
Provides for information about CHP file versions.
Definition at line 34 of file CHPComparer.h.
Member Function Documentation
void CHPComparer::Clear ()
Clears the members.
Definition at line 39 of file CHPComparer.cpp.
bool CHPComparer::CompareFiles (const char * file1, const char * file2)
Determines the version number of the file.
Parameters:
file1 The first file to compare.
file2 The second file to compare.
Returns:
True if identical.
Definition at line 47 of file CHPComparer.cpp.
References affymetrix_cel_converter::Calvin_Version1, affymetrix_comparer::CHPCompareCalvintoCalvin::Differences(), affymetrix_comparer::CHPCompareGCOStoGCOS::Differences(), affymetrix_comparer::CHPCompareGCOStoCalvin::Differences(), and affymetrix_chp_converter::GCOS_XDA_Version.
std::string affymetrix_comparer::CHPComparer::Differences () const [inline]
The differences between the files.
Returns:
A string representation of the differences.
Definition at line 55 of file CHPComparer.h.
The documentation for this class was generated from the following files:
calvin_files/converters/chp/comparer/CHPComparer.h
calvin_files/converters/chp/comparer/CHPComparer.cpp