Affymetrix Power Tools: TmpFileFactory Class Reference
TmpFileFactory Class Reference
Allocate temporary filenames and arrange to remove them when done.
#include <TmpFileFactory.h>
Public Member Functions
TmpFileFactory ()
The default constructor.
virtual ~TmpFileFactory ()
The destructor.
void cleanUp ()
Remove all the files and directories we have generated. /// Called from ~TmpFileFactory().
void setTmpdir (const std::string &tmpdir)
Sets the directory in which the tmp files will be allocated. ///.
std::string makeTmpDir ()
Generate and create a directory for tmp files. ///.
void setPrefix (const std::string &prefix)
Set the default prefix for tmp names. ///.
void setSuffix (const std::string &suffix)
Sets the default suffix (".tmp") for name from ///.
std::string genUniqueString ()
Generates a string which is unique for this run of the program. ///.
std::string genFilename_basic (const std::string &prefix, const std::string &suffix)
Generate a name which does not exist in the filesystem. /// Does NOT remember to delete the filename later. ///.
std::string genFilename (const std::string &prefix, const std::string &suffix)
Generates a unique filename with user supplied prefix and suffix. /// Remembers to delete it later. ///.
std::string genFilename ()
Generates a unique filename with the default prefix and suffix. /// Remembers to delete it later. ///.
std::vector< std::string > genFilenames (int cnt)
generate a vector of filenames in one call. //
std::string genDirname ()
Generates and creates a unique directory ///.
void rememberToRemove (const std::string &filename)
Remeber this filename to delete later. ///.
void rememberToRemoveDir (const std::string &dirname)
Remeber this dirname to delete later. ///.
void setDebug (int level)
Sets the debugging options /// 0=None /// 1=Dont remove the tmp files, leave them for debugging. ///.
void setVerbose (int level)
Sets the verbose level /// 0=No output /// 1 or more = logs more actions. ///.
std::string getSystemTmpDir ()
Get The suggested tmp directory for this system. ///.
Static Public Member Functions
static int incFileCounter ()
Return the next value of the file counter. ///.
Public Attributes
std::vector< std::string > m_tmpfilenames
filenames we have allocated
std::vector< std::string > m_tmpdirnames
directory names we have allocated
std::string m_tmpdir
the directory in which the files will be allocated within.
std::string m_prefix
the default prefix for the file and dir names.
std::string m_suffix
the default suffix for the file names.
int m_opt_debug
Controls the behavior to help debugging.
int m_opt_verbose
When set produces extra output for debugging.
int m_maxTrialCnt
Static Public Attributes
static int m_fileCount = 0
Detailed Description
Allocate temporary filenames and arrange to remove them when done.
Definition at line 32 of file TmpFileFactory.h.
Member Function Documentation
void TmpFileFactory::cleanUp ()
Remove all the files and directories we have generated. /// Called from ~TmpFileFactory().
Todo:
: replace with "Log"
Todo:
: replace with "Log"
Definition at line 144 of file TmpFileFactory.cpp.
References m_opt_debug, m_opt_verbose, m_tmpdirnames, m_tmpfilenames, Fs::rm(), and Fs::rmdir().
Referenced by GlobalTmpFileFactoryFree(), and ~TmpFileFactory().
std::string TmpFileFactory::genDirname ()
Generates and creates a unique directory ///.
Returns:
the pathname to the directory.
Definition at line 238 of file TmpFileFactory.cpp.
References Err::errAbort(), genFilename_basic(), m_prefix, Fs::mkdirPath(), and rememberToRemoveDir().
std::string TmpFileFactory::genFilename (const std::string & prefix, const std::string & suffix)
Generates a unique filename with user supplied prefix and suffix. /// Remembers to delete it later. ///.
Parameters:
prefix user override to prefix ///
suffix user override to suffix ///
Returns:
a unique pathname
Definition at line 212 of file TmpFileFactory.cpp.
References genFilename_basic(), and rememberToRemove().
Referenced by DiskIntensityMart::DiskIntensityMart().
std::string TmpFileFactory::genFilename ()
Generates a unique filename with the default prefix and suffix. /// Remembers to delete it later. ///.
Returns:
a unique file name.
Definition at line 221 of file TmpFileFactory.cpp.
References m_prefix, and m_suffix.
Referenced by genFilenames().
std::string TmpFileFactory::genFilename_basic (const std::string & prefix, const std::string & suffix)
Generate a name which does not exist in the filesystem. /// Does NOT remember to delete the filename later. ///.
Parameters:
prefix prefix for the unique string. ///
suffix suffix for the unique string. ///
Returns:
the unique pathname (dir+prefix+unique+suffix)
Definition at line 191 of file TmpFileFactory.cpp.
References Err::errAbort(), genUniqueString(), Fs::join(), m_opt_verbose, and m_tmpdir.
Referenced by CNWorkflowEngine::callCNReferenceEngine(), genDirname(), genFilename(), CNReferenceMethodWaveCorrection::run(), and SnpClusterStore::SnpClusterStore().
std::vector< std::string > TmpFileFactory::genFilenames (int cnt)
generate a vector of filenames in one call. //
Parameters:
cnt The number of filenames to generate. ///
Returns:
the vec of filenames.
Definition at line 228 of file TmpFileFactory.cpp.
References genFilename().
std::string TmpFileFactory::genUniqueString ()
Generates a string which is unique for this run of the program. ///.
Returns:
A 'unique' string.
Definition at line 176 of file TmpFileFactory.cpp.
References incFileCounter().
Referenced by genFilename_basic().
std::string TmpFileFactory::getSystemTmpDir ()
Get The suggested tmp directory for this system. ///.
Returns:
The suggested path name.
Definition at line 256 of file TmpFileFactory.cpp.
int TmpFileFactory::incFileCounter () [static]
Return the next value of the file counter. ///.
Returns:
the next value.
Definition at line 46 of file TmpFileFactory.cpp.
Referenced by genUniqueString().
std::string TmpFileFactory::makeTmpDir ()
Generate and create a directory for tmp files. ///.
Returns:
The directory path
void TmpFileFactory::rememberToRemove (const std::string & filename)
Remeber this filename to delete later. ///.
Parameters:
filename What to remove when "cleanUp()" is called.
Definition at line 131 of file TmpFileFactory.cpp.
References m_tmpfilenames.
Referenced by genFilename().
void TmpFileFactory::rememberToRemoveDir (const std::string & dirname)
Remeber this dirname to delete later. ///.
Parameters:
filename What to remove when "cleanUp()" is called.
Definition at line 136 of file TmpFileFactory.cpp.
References m_tmpdirnames.
Referenced by genDirname().
void TmpFileFactory::setDebug (int level)
Sets the debugging options /// 0=None /// 1=Dont remove the tmp files, leave them for debugging. ///.
Parameters:
level
Definition at line 106 of file TmpFileFactory.cpp.
References m_opt_debug.
void TmpFileFactory::setPrefix (const std::string & prefix)
Set the default prefix for tmp names. ///.
Parameters:
prefix The prefix to use.
Definition at line 122 of file TmpFileFactory.cpp.
References m_prefix.
void TmpFileFactory::setSuffix (const std::string & suffix)
Sets the default suffix (".tmp") for name from ///.
Parameters:
suffix
Definition at line 126 of file TmpFileFactory.cpp.
References m_suffix.
void TmpFileFactory::setTmpdir (const std::string & tmpdir)
Sets the directory in which the tmp files will be allocated. ///.
Parameters:
dirname
Definition at line 117 of file TmpFileFactory.cpp.
References m_tmpdir.
Referenced by CNWorkflowEngine::callCNReferenceEngine(), DiskIntensityMart::DiskIntensityMart(), and CNReferenceMethodWaveCorrection::run().
void TmpFileFactory::setVerbose (int level)
Sets the verbose level /// 0=No output /// 1 or more = logs more actions. ///.
Parameters:
level
Definition at line 111 of file TmpFileFactory.cpp.
References m_opt_verbose.
The documentation for this class was generated from the following files:
util/TmpFileFactory.h
util/TmpFileFactory.cpp