Affymetrix Power Tools: CNReferenceMethodWaveCorrection Class Reference
CNReferenceMethodWaveCorrection Class Reference
A class for calulating WaveCorrection.
#include <CNReferenceMethodWaveCorrection.h>