Affymetrix Power Tools: VariabilityScoreCelListener Class Reference
VariabilityScoreCelListener Class Reference
Class for computing hilo qc metric from a cel set of cel files.
#include <VariabilityScoreCelListener.h>