Affymetrix Power Tools: TranslationAudit Class Reference
TranslationAudit Class Reference
Public Member Functions
TranslationAudit (const class RunTimeEnvironment &rte)
TranslationAudit::TranslationAudit Synopsis:
int audit (class RunTimeEnvironment &rte)
TranslationAudit::audit Synopsis:
int auditAnnotation (class RunTimeEnvironment &rte)
TranslationAudit::auditAnnotation Synopsis:
Detailed Description
Definition at line 37 of file TranslationAudit.h.
Constructor & Destructor Documentation
TranslationAudit::TranslationAudit (const class RunTimeEnvironment & rte)
TranslationAudit::TranslationAudit Synopsis:
Main constructor. Does not start the audit logic. To start the audit see TranslationAudit::audit
Parameters:
rte - the single instance RunTimeEnvironment
Definition at line 64 of file TranslationAudit.cpp.
References APT_ERR_ABORT, and APT_ERR_ASSERT.
Member Function Documentation
int TranslationAudit::audit (class RunTimeEnvironment & rte)
TranslationAudit::audit Synopsis:
The "main" program if you will. Wrapper for the various call backs registered in the TranslationAuditType TRANSLATE_AUDIT_TYPES at the top of this file.
At the command line the audit option is passed an audit type, i.e. "annotation". This type is then looked up in the type table and if found the audit is run. Only one audit can be run at a time. Invoke the command line multiple times with the various names to run various audits.
An audit type is similar to a regression type or unit test scenario where new classes of audits are completely independent of other. To implement a new audit type create the the code as methods here and then register the top level method in TranslationAuditType TRANSLATE_AUDIT_TYPES. Pass in the type name at the command line "-a mynewtype" to run the audit.
Parameters:
rte - the single instance RunTimeEnvironment
TRANSLATE_AUDIT_TYPES - with the registered call backs to invoke.
Returns:
- exit value 0 if ok, -1 otherwise
Definition at line 116 of file TranslationAudit.cpp.
References APT_ERR_ABORT, and APT_ERR_ASSERT.
Referenced by TranslationEngine::runImp().
int TranslationAudit::auditAnnotation (class RunTimeEnvironment & rte)
TranslationAudit::auditAnnotation Synopsis:
Audit the translation file. This is a work in progress as of 11/04/2008 and needs completion.
Parameters:
rte - the single instance RunTimeEnvironment
Returns:
- exit value, 0 when all is ok, -1 otherwise.
Definition at line 153 of file TranslationAudit.cpp.
References TranslationTableModel::getColumnIndex(), Verbose::out(), and TranslationTableModel::validateRowIsHeader().
The documentation for this class was generated from the following files:
translation/TranslationAudit.h
translation/TranslationAudit.cpp