Affymetrix Power Tools: PmAdjusterFactory Class Reference
PmAdjusterFactory Class Reference
Factory class for making chip streams based on a string representation.
#include <PmAdjusterFactory.h>
Public Member Functions
PmAdjusterFactory ()
Constructor.
PmAdjuster * adjusterForString (const std::string &spec)
Create a pointer to a new PmAdjuster object as described in the string specification.
PmAdjuster * pmAdjusterForString (const std::string &spec, ChipLayout &layout)
Factory for creating PmAdjuster from string representation.
PmAdjuster * pmAdjusterForString (const std::string &spec, PsBoard &board)
Factory for creating PmAdjuster from string representation.
void setControlProbes (const std::vector< Probe * > controlProbes)
Set the probes to be used as a background distribution.
std::vector< SelfDoc > getDocs ()
Get the vector of documentation objects that this factory is aware of.
bool canBuild (const std::string &spec)
Can this factory be used to build from this specification?
Protected Attributes
std::vector< Probe * > m_GcControlProbes
Background probes to use. Note that memory is owned elsewhere.
std::vector< SelfDoc > m_Docs
Self documentation.
std::vector
< SelfCreate::selfCreator > m_Creators
Self creation.
Detailed Description
Factory class for making chip streams based on a string representation.
Definition at line 50 of file PmAdjusterFactory.h.
Constructor & Destructor Documentation
PmAdjusterFactory::PmAdjusterFactory ()
Constructor.
Registers the objects we know how to create and how they describe themselves.
Definition at line 49 of file PmAdjusterFactory.cpp.
References PmSumAdjust::explainSelf(), GcAdjust::explainSelf(), MmAdjust::explainSelf(), PmOnlyAdjust::explainSelf(), m_Creators, m_Docs, PmSumAdjust::newObject(), GcAdjust::newObject(), MmAdjust::newObject(), and PmOnlyAdjust::newObject().
Member Function Documentation
PmAdjuster * PmAdjusterFactory::adjusterForString (const std::string & spec)
Create a pointer to a new PmAdjuster object as described in the string specification.
Parameters:
spec - Specification string i.e. pm-gcbg
Returns:
Pointer to new PmAdjuster objects, must be deleted when finished.
Definition at line 75 of file PmAdjusterFactory.cpp.
References Err::errAbort(), m_Creators, m_Docs, and SelfCreate::selfCreateFromString().
Referenced by pmAdjusterForString().
bool PmAdjusterFactory::canBuild (const std::string & spec) [inline]
Can this factory be used to build from this specification?
Parameters:
spec - Specification in form "chipstream.key=value.key=value"
Returns:
true if this factory knows how to build from this specification, false otherwise
Definition at line 110 of file PmAdjusterFactory.h.
References SelfCreate::canMake(), and m_Docs.
Referenced by DTFactory::dataTransformForString().
std::vector<SelfDoc> PmAdjusterFactory::getDocs () [inline]
Get the vector of documentation objects that this factory is aware of.
Returns:
- vector of documentation objects.
Definition at line 101 of file PmAdjusterFactory.h.
References m_Docs.
Referenced by EngineUtil::explainParameter().
PmAdjuster * PmAdjusterFactory::pmAdjusterForString (const std::string & spec, ChipLayout & layout)
Factory for creating PmAdjuster from string representation.
Parameters:
spec - Name of PmAdjuster.
layout - Probe and probe set info.
Returns:
PmAdjuster requested.
Definition at line 97 of file PmAdjusterFactory.cpp.
References adjusterForString(), Err::errAbort(), and m_GcControlProbes.
Referenced by DTFactory::dataTransformForString(), and AnalysisStreamFactory::fillInAnalysisStream().
PmAdjuster * PmAdjusterFactory::pmAdjusterForString (const std::string & spec, PsBoard & board)
Factory for creating PmAdjuster from string representation.
Parameters:
spec - Name of PmAdjuster.
board - Blackboard with various state info
Returns:
PmAdjuster requested.
Definition at line 124 of file PmAdjusterFactory.cpp.
References adjusterForString(), and PmAdjuster::setParameters().
void PmAdjusterFactory::setControlProbes (const std::vector< Probe * > controlProbes) [inline]
Set the probes to be used as a background distribution.
Parameters:
controlProbes - probes to use as controls.
Definition at line 93 of file PmAdjusterFactory.h.
References m_GcControlProbes.
Referenced by AnalysisStreamFactory::readControlProbes(), and AnalysisStreamFactory::setGcControlProbes().
The documentation for this class was generated from the following files:
chipstream/PmAdjusterFactory.h
chipstream/PmAdjusterFactory.cpp