Affymetrix Power Tools: CNFamilialAnalysisMethodHemizygousParentOfOrigin Class Reference
CNFamilialAnalysisMethodHemizygousParentOfOrigin Class Reference
The HemizygousParentOfOrigin Familial analysis method.
#include <CNFamilialAnalysisMethodHemizygousParentOfOrigin.h>