Affymetrix Power Tools: CNWorkflowEngine Class Reference
CNWorkflowEngine Class Reference
The engine for controlling the copynumber workflows.
#include <CNWorkflowEngine.h>