Affymetrix Power Tools: CNLog2RatioAdjustmentMethodWaveCorrection Class Reference
CNLog2RatioAdjustmentMethodWaveCorrection Class Reference
The WaveCorrection log2 ratio adjustment method.
#include <CNLog2RatioAdjustmentMethodWaveCorrection.h>