Affymetrix Power Tools: affymetrix_calvin_io::CHPData Class Reference
affymetrix_calvin_io::CHPData Class Reference
#include <CHPData.h>
Public Member Functions
CHPData ()
CHPData (const std::string &filename, const std::string &assayType)
virtual ~CHPData ()
void Clear ()
void SetFilename (const std::string &p)
std::string GetFilename () const
u_int8_t GetVersion ()
u_int8_t GetMagic ()
int32_t GetRows ()
void SetRows (int32_t value)
int32_t GetCols ()
void SetCols (int32_t value)
std::wstring GetProgId ()
void SetProgId (const std::wstring &value)
std::wstring GetArrayType ()
std::string GetAssayType ()
backwards compatibility for gcos like calls
void SetArrayType (const std::wstring &value)
std::wstring GetAlgName ()
void SetAlgName (const std::wstring &value)
std::wstring GetParentCell ()
void SetParentCell (const std::wstring &value)
std::wstring GetAlgVersion ()
void SetAlgVersion (const std::wstring &value)
void AddAlgParam (const std::wstring &name, const std::wstring &param)
void AddAlgParam (const std::wstring &name, int param)
void AddAlgParam (const std::wstring &name, float param)
ParameterNameValueTypeVector GetAlgParams ()
ParameterNameValueType GetAlgParam (const std::wstring &tag)
void AddChipSum (const std::wstring &name, const std::wstring &param)
void AddChipSum (const std::wstring &name, float param)
void AddChipSum (const std::wstring &name, int param)
ParameterNameValueTypeVector GetChipSums ()
ParameterNameValueType GetChipSum (const std::wstring &tag)
FileHeader * GetFileHeader ()
GenericData & GetGenericData ()
void SetEntryCount (int32_t ln, int32_t maxln, bool hasCompData=false)
int32_t GetEntryCount ()
int32_t GetBackgroundZoneCnt ()
void SetBackgroundZoneCnt (int32_t ln)
void GetBackgroundZone (int32_t row, CHPBackgroundZone &zone)
void GetBackgroundZones (int32_t row, int32_t rowCnt, CHPBackgroundZoneVector &zones)
void GetEntry (int32_t row, CHPUniversalEntry &e)
void GetEntry (int32_t row, CHPGenotypeEntry &e)
void GetEntry (int32_t row, CHPExpressionEntry &e)
void GetEntry (int32_t row, CHPReseqEntry &e)
int32_t GetForceCnt ()
void SetForceCnt (int32_t ln)
void GetForceCall (int32_t row, CHPReseqForceCall &force)
int32_t GetOrigCnt ()
void SetOrigCnt (int32_t ln)
void GetOrigCall (int32_t row, CHPReseqOrigCall &orig)
int GetMaxProbeSetName () const
Protected Member Functions
void PrepareGenoEntryDataSet ()
void PrepareExprEntryDataSet ()
void PrepareUnivEntryDataSet ()
void PrepareReseqEntryDataSet ()
void AddUnivColumns (DataSetHeader &hdr)
void AddExprColumns (DataSetHeader &hdr, bool hasCompData)
void AddGenoColumns (DataSetHeader &hdr)
void AddReseqColumns (DataSetHeader &hdr)
std::wstring GetWStringFromGenericHdr (const std::wstring &name)
void SetWStringToGenericHdr (const std::wstring &name, const std::wstring value, int32_t reserve=-1)
int32_t GetInt32FromGenericHdr (const std::wstring &name)
void SetInt32ToGenericHdr (const std::wstring &name, int32_t value)
void SetFloatToGenericHdr (const std::wstring &name, float value)
void PrepareBackgroundZoneDataSet ()
void PrepareForceDataSet ()
void PrepareOrigDataSet ()
void AddColumns (DataSetHeader &hdr, bool hasCompData)
Protected Attributes
bool wideProbeSetNames
int maxProbeSetName
GenericData genericData
int32_t cachedRows
int32_t cachedCols
DataSet * entriesExp
DataSet * entriesGeno
DataSet * entriesUniv
DataSet * entriesReseq
DataSet * bgZones
DataSet * forceSet
DataSet * origSet
Detailed Description
Defines a base class for older CHP file data.
Definition at line 81 of file CHPData.h.
Constructor & Destructor Documentation
CHPData::CHPData ()
Constructor
Definition at line 63 of file CHPData.cpp.
References bgZones, Clear(), entriesExp, entriesGeno, entriesReseq, entriesUniv, forceSet, origSet, and wideProbeSetNames.
CHPData::CHPData (const std::string & filename, const std::string & assayType)
Constructor with file and type.
Parameters:
filename The name of the CHP file.
assayType The type of data in the CHP file.
Definition at line 76 of file CHPData.cpp.
References bgZones, CHP_BG_ZONE_GROUP, CHP_EXPRESSION_ASSAY_TYPE, CHP_GENOTYPING_ASSAY_TYPE, CHP_RESEQ_FORCE_CALL_GROUP, CHP_RESEQ_ORIG_CALL_GROUP, CHP_RESEQUENCING_ASSAY_TYPE, CHP_UNIVERSAL_ASSAY_TYPE, Clear(), entriesExp, entriesGeno, entriesReseq, entriesUniv, forceSet, genericData, affymetrix_calvin_io::GenericData::Header(), origSet, SetFilename(), affymetrix_calvin_io::GenericDataHeader::SetFileTypeId(), and wideProbeSetNames.
CHPData::~CHPData () [virtual]
Destructor
Definition at line 468 of file CHPData.cpp.
References Clear().
Member Function Documentation
void CHPData::AddAlgParam (const std::wstring & name, const std::wstring & param)
Adds a parameter to the alg parameters section
Definition at line 690 of file CHPData.cpp.
References ALGORITHM_PARAM_NAME_PREFIX_S, and SetWStringToGenericHdr().
void CHPData::AddAlgParam (const std::wstring & name, int param)
Adds a parameter to the alg parameters section
Definition at line 696 of file CHPData.cpp.
References ALGORITHM_PARAM_NAME_PREFIX_S, and SetInt32ToGenericHdr().
void CHPData::AddAlgParam (const std::wstring & name, float param)
Adds a parameter to the alg parameters section
Definition at line 702 of file CHPData.cpp.
References ALGORITHM_PARAM_NAME_PREFIX_S, and SetFloatToGenericHdr().
void CHPData::AddChipSum (const std::wstring & name, const std::wstring & param)
Adds a parameter to the chip summary section
Definition at line 730 of file CHPData.cpp.
References CHIP_SUMMARY_PARAMETER_NAME_PREFIX_S, and SetWStringToGenericHdr().
void CHPData::AddChipSum (const std::wstring & name, float param)
Adds a parameter to the chip summary section
Definition at line 736 of file CHPData.cpp.
References CHIP_SUMMARY_PARAMETER_NAME_PREFIX_S, and SetFloatToGenericHdr().
void affymetrix_calvin_io::CHPData::AddChipSum (const std::wstring & name, int param)
Adds a parameter to the chip summary section
void CHPData::AddColumns (DataSetHeader & hdr, bool hasCompData) [protected]
Adds columns to the data set.
Definition at line 315 of file CHPData.cpp.
References AddExprColumns(), AddGenoColumns(), AddReseqColumns(), AddUnivColumns(), genericData, affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), and affymetrix_calvin_io::GenericData::Header().
Referenced by SetEntryCount().
void CHPData::AddExprColumns (DataSetHeader & hdr, bool hasCompData) [protected]
Adds columns to the data set.
Definition at line 369 of file CHPData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddAsciiColumn(), affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), affymetrix_calvin_io::DataSetHeader::AddUByteColumn(), affymetrix_calvin_io::DataSetHeader::AddUShortColumn(), CHP_EXPR_GROUP, maxProbeSetName, and affymetrix_calvin_io::DataSetHeader::SetName().
Referenced by AddColumns().
void CHPData::AddGenoColumns (DataSetHeader & hdr) [protected]
Adds columns to the data set.
Definition at line 346 of file CHPData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddAsciiColumn(), affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), affymetrix_calvin_io::DataSetHeader::AddUByteColumn(), CHP_GENO_GROUP, maxProbeSetName, and affymetrix_calvin_io::DataSetHeader::SetName().
Referenced by AddColumns().
void CHPData::AddReseqColumns (DataSetHeader & hdr) [protected]
Adds columns to the data set.
Definition at line 330 of file CHPData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddByteColumn(), affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), CHP_RESEQ_GROUP, and affymetrix_calvin_io::DataSetHeader::SetName().
Referenced by AddColumns().
void CHPData::AddUnivColumns (DataSetHeader & hdr) [protected]
Adds columns to the data set.
Definition at line 339 of file CHPData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), CHP_UNIV_GROUP, and affymetrix_calvin_io::DataSetHeader::SetName().
Referenced by AddColumns().
void CHPData::Clear ()
Clears the members.
Definition at line 473 of file CHPData.cpp.
References bgZones, cachedCols, cachedRows, affymetrix_calvin_io::DataSet::Delete(), entriesExp, entriesGeno, entriesReseq, entriesUniv, forceSet, genericData, affymetrix_calvin_io::GenericData::Header(), and origSet.
Referenced by CHPData(), affymetrix_fusion_io::CalvinCHPDataAdapter::Clear(), affymetrix_comparer::CHPCompareGCOStoCalvin::Clear(), affymetrix_comparer::CHPCompareCalvintoCalvin::Clear(), affymetrix_calvin_io::CHPFileReader::Read(), and ~CHPData().
std::wstring CHPData::GetAlgName ()
Gets the algorithm name
Definition at line 606 of file CHPData.cpp.
References ALGORITHM_NAME_PARAM_NAME, and GetWStringFromGenericHdr().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetAlgName().
ParameterNameValueType CHPData::GetAlgParam (const std::wstring & tag)
Gets a single algorithm parameter by name.
Definition at line 646 of file CHPData.cpp.
References ALGORITHM_PARAM_NAME_PREFIX_S, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), genericData, affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetAlgorithmParameter().
ParameterNameValueTypeVector CHPData::GetAlgParams ()
Gets the alg parameters
Definition at line 668 of file CHPData.cpp.
References ALGORITHM_PARAM_NAME_PREFIX_S, genericData, affymetrix_calvin_io::GenericDataHeader::GetNameValIterators(), affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetAlgorithmParameterCount(), and affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetAlgorithmParameters().
std::wstring CHPData::GetAlgVersion ()
Gets the algorithm version.
Definition at line 626 of file CHPData.cpp.
References ALG_VERSION_PARAM_NAME, and GetWStringFromGenericHdr().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetAlgVersion().
std::wstring CHPData::GetArrayType ()
Sets the array type
Definition at line 596 of file CHPData.cpp.
References ARRAY_TYPE_PARAM_NAME, and GetWStringFromGenericHdr().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetChipType().
std::string CHPData::GetAssayType ()
backwards compatibility for gcos like calls
Gets the assay type
Definition at line 403 of file CHPData.cpp.
References genericData, affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetAssayType(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetProbeSetName(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults(), and affymetrix_fusion_io::CalvinCHPDataAdapter::GetUniversalResults().
void CHPData::GetBackgroundZone (int32_t row, CHPBackgroundZone & zone)
Gets CHP background zone value
Parameters:
row The row from which to start copying
zone The data object to be filled
Definition at line 419 of file CHPData.cpp.
References bgZones, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), and PrepareBackgroundZoneDataSet().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetBackgroundZone(), and GetBackgroundZones().
int32_t CHPData::GetBackgroundZoneCnt ()
Gets the number of background zones.
Definition at line 524 of file CHPData.cpp.
References genericData, affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetBackgroundZoneInfo(), and affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetBackgroundZones().
void CHPData::GetBackgroundZones (int32_t row, int32_t rowCnt, CHPBackgroundZoneVector & zones)
Gets the background zones.
Definition at line 408 of file CHPData.cpp.
References GetBackgroundZone().
Referenced by affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetBackgroundZoneInfo(), and affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetBackgroundZones().
ParameterNameValueType CHPData::GetChipSum (const std::wstring & tag)
Gets a chip summary parameter by name
Definition at line 657 of file CHPData.cpp.
References CHIP_SUMMARY_PARAMETER_NAME_PREFIX_S, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), genericData, affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetSummaryParameter().
ParameterNameValueTypeVector CHPData::GetChipSums ()
Gets all the chip summary parameters
Definition at line 708 of file CHPData.cpp.
References CHIP_SUMMARY_PARAMETER_NAME_PREFIX_S, genericData, affymetrix_calvin_io::GenericDataHeader::GetNameValIterators(), affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetSummaryParameterCount(), and affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetSummaryParameters().
int32_t CHPData::GetCols ()
Gets the number of columns of features on the array.
Definition at line 761 of file CHPData.cpp.
References cachedCols, CEL_COLS_PARAM_NAME, and GetInt32FromGenericHdr().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetCols().
void CHPData::GetEntry (int32_t row, CHPUniversalEntry & e)
Gets the expression entry (probe set).
Definition at line 242 of file CHPData.cpp.
References entriesUniv, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), and PrepareUnivEntryDataSet().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetProbeSetName(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults(), and affymetrix_fusion_io::CalvinCHPDataAdapter::GetUniversalResults().
void CHPData::GetEntry (int32_t row, CHPGenotypeEntry & e)
Gets the expression entry (probe set).
Definition at line 122 of file CHPData.cpp.
References entriesGeno, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), PrepareGenoEntryDataSet(), and wideProbeSetNames.
void CHPData::GetEntry (int32_t row, CHPExpressionEntry & e)
Gets the expression entry (probe set).
Definition at line 172 of file CHPData.cpp.
References affymetrix_calvin_io::DataSet::Cols(), entriesExp, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), PrepareExprEntryDataSet(), affymetrix_calvin_io::CHPExpressionEntry::SetChange(), affymetrix_calvin_io::CHPExpressionEntry::SetChangePValue(), affymetrix_calvin_io::CHPExpressionEntry::SetCommonPairs(), affymetrix_calvin_io::CHPExpressionEntry::SetDetection(), affymetrix_calvin_io::CHPExpressionEntry::SetDetectionPValue(), affymetrix_calvin_io::CHPExpressionEntry::SetHasComparisonData(), affymetrix_calvin_io::CHPExpressionEntry::SetNumPairs(), affymetrix_calvin_io::CHPExpressionEntry::SetNumPairsUsed(), affymetrix_calvin_io::CHPExpressionEntry::SetProbeSetName(), affymetrix_calvin_io::CHPExpressionEntry::SetSigLogRatio(), affymetrix_calvin_io::CHPExpressionEntry::SetSigLogRatioHi(), affymetrix_calvin_io::CHPExpressionEntry::SetSigLogRatioLo(), affymetrix_calvin_io::CHPExpressionEntry::SetSignal(), and wideProbeSetNames.
void CHPData::GetEntry (int32_t row, CHPReseqEntry & e)
Gets the resequence entry.
Definition at line 253 of file CHPData.cpp.
References affymetrix_calvin_io::_CHPReseqEntry::call, entriesReseq, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), PrepareReseqEntryDataSet(), and affymetrix_calvin_io::_CHPReseqEntry::score.
int32_t CHPData::GetEntryCount ()
Gets the number of entries (probe sets)
Definition at line 507 of file CHPData.cpp.
References genericData, affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetNumProbeSets(), and affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
FileHeader* affymetrix_calvin_io::CHPData::GetFileHeader () [inline]
Gets the file header
Definition at line 215 of file CHPData.h.
References genericData, and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::AddExtraParameters(), CalvinChpCheck::check(), affymetrix_calvin_io::CHPFileWriter::CHPFileWriter(), affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile(), and affymetrix_fusion_io::CalvinCHPDataAdapter::FileId().
std::string CHPData::GetFilename () const
The name of the CHP file.
Definition at line 492 of file CHPData.cpp.
References genericData.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetFileName(), and affymetrix_calvin_io::CHPFileReader::Read().
void CHPData::GetForceCall (int32_t row, CHPReseqForceCall & force)
Gets the force call value
Parameters:
row The row index
force The data object to be filled
Definition at line 442 of file CHPData.cpp.
References affymetrix_calvin_io::_CHPReseqForceCall::call, forceSet, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_io::_CHPReseqForceCall::position, PrepareForceDataSet(), and affymetrix_calvin_io::_CHPReseqForceCall::reason.
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
int32_t CHPData::GetForceCnt ()
Gets the number of force calls.
Definition at line 550 of file CHPData.cpp.
References genericData, affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
GenericData& affymetrix_calvin_io::CHPData::GetGenericData () [inline]
Gets the file data object.
Definition at line 218 of file CHPData.h.
References genericData.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenericData(), and affymetrix_calvin_io::CHPFileReader::Read().
int32_t CHPData::GetInt32FromGenericHdr (const std::wstring & name) [protected]
Gets an integer parameter from the header.
Definition at line 795 of file CHPData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), genericData, affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), and affymetrix_calvin_io::GenericData::Header().
Referenced by GetCols(), and GetRows().
u_int8_t CHPData::GetMagic ()
Gets the files magic number.
Definition at line 502 of file CHPData.cpp.
References genericData, and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetMagic().
int affymetrix_calvin_io::CHPData::GetMaxProbeSetName () const [inline]
The maximum length of a probe set name.
Definition at line 282 of file CHPData.h.
References maxProbeSetName.
Referenced by affymetrix_calvin_io::CHPFileWriter::CHPFileWriter().
void CHPData::GetOrigCall (int32_t row, CHPReseqOrigCall & orig)
Gets the original call value from the orig set.
Parameters:
row The row index
orig The orginal call value.
Definition at line 456 of file CHPData.cpp.
References affymetrix_calvin_io::_CHPReseqOrigCall::call, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), origSet, affymetrix_calvin_io::_CHPReseqOrigCall::position, and PrepareOrigDataSet().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
int32_t CHPData::GetOrigCnt ()
Gets the number of orig calls.
Definition at line 574 of file CHPData.cpp.
References genericData, affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCHPDataAdapter::GetResequencingResults().
std::wstring CHPData::GetParentCell ()
Gets the name of the parent CEL file.
Definition at line 616 of file CHPData.cpp.
References CHP_PARENT_CELL, and GetWStringFromGenericHdr().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetParentCellFile().
std::wstring CHPData::GetProgId ()
Gets the CHP file prog Id.
Definition at line 636 of file CHPData.cpp.
References CHP_PROGID, and GetWStringFromGenericHdr().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetProgID().
int32_t CHPData::GetRows ()
Gets the number of rows of features on the array.
Definition at line 748 of file CHPData.cpp.
References cachedRows, CEL_ROWS_PARAM_NAME, and GetInt32FromGenericHdr().
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetRows().
u_int8_t CHPData::GetVersion ()
Gets the version in the file.
Definition at line 497 of file CHPData.cpp.
References genericData, and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetVersion().
std::wstring CHPData::GetWStringFromGenericHdr (const std::wstring & name) [protected]
Gets a string parameter to the header.
Definition at line 774 of file CHPData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), genericData, affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), and affymetrix_calvin_io::GenericData::Header().
Referenced by GetAlgName(), GetAlgVersion(), GetArrayType(), GetParentCell(), and GetProgId().
void CHPData::PrepareBackgroundZoneDataSet () [protected]
Prepares the data set for the bg set.
Definition at line 825 of file CHPData.cpp.
References bgZones, CHP_BG_ZONE_GROUP, affymetrix_calvin_io::GenericData::DataSet(), genericData, and affymetrix_calvin_io::DataSet::Open().
Referenced by GetBackgroundZone().
void CHPData::PrepareExprEntryDataSet () [protected]
Prepares the data set.
Definition at line 278 of file CHPData.cpp.
References CHP_EXPR_GROUP, affymetrix_calvin_io::GenericData::DataSet(), entriesExp, genericData, affymetrix_calvin_io::DataSetHeader::GetColumnInfo(), affymetrix_calvin_io::ColumnInfo::GetColumnType(), affymetrix_calvin_io::DataSet::Header(), affymetrix_calvin_io::DataSet::Open(), and wideProbeSetNames.
Referenced by GetEntry().
void CHPData::PrepareForceDataSet () [protected]
Prepares the data set for the force call set.
Definition at line 837 of file CHPData.cpp.
References CHP_RESEQ_FORCE_CALL_GROUP, affymetrix_calvin_io::GenericData::DataSet(), forceSet, genericData, and affymetrix_calvin_io::DataSet::Open().
Referenced by GetForceCall().
void CHPData::PrepareGenoEntryDataSet () [protected]
Prepares the data set.
Definition at line 265 of file CHPData.cpp.
References CHP_GENO_GROUP, affymetrix_calvin_io::GenericData::DataSet(), entriesGeno, genericData, affymetrix_calvin_io::DataSetHeader::GetColumnInfo(), affymetrix_calvin_io::ColumnInfo::GetColumnType(), affymetrix_calvin_io::DataSet::Header(), affymetrix_calvin_io::DataSet::Open(), and wideProbeSetNames.
Referenced by GetEntry().
void CHPData::PrepareOrigDataSet () [protected]
Prepares the data set for the orig call set.
Definition at line 849 of file CHPData.cpp.
References CHP_RESEQ_ORIG_CALL_GROUP, affymetrix_calvin_io::GenericData::DataSet(), genericData, affymetrix_calvin_io::DataSet::Open(), and origSet.
Referenced by GetOrigCall().
void CHPData::PrepareReseqEntryDataSet () [protected]
Prepares the data set.
Definition at line 303 of file CHPData.cpp.
References CHP_RESEQ_GROUP, affymetrix_calvin_io::GenericData::DataSet(), entriesReseq, genericData, and affymetrix_calvin_io::DataSet::Open().
Referenced by GetEntry().
void CHPData::PrepareUnivEntryDataSet () [protected]
Prepares the data set.
Definition at line 291 of file CHPData.cpp.
References CHP_UNIV_GROUP, affymetrix_calvin_io::GenericData::DataSet(), entriesUniv, genericData, and affymetrix_calvin_io::DataSet::Open().
Referenced by GetEntry().
void CHPData::SetAlgName (const std::wstring & value)
Sets the algorithm name.
Definition at line 611 of file CHPData.cpp.
References ALGORITHM_NAME_PARAM_NAME, and SetWStringToGenericHdr().
void CHPData::SetAlgVersion (const std::wstring & value)
Sets the algorithm version.
Definition at line 631 of file CHPData.cpp.
References ALG_VERSION_PARAM_NAME, and SetWStringToGenericHdr().
void CHPData::SetArrayType (const std::wstring & value)
Sets the array type.
Definition at line 601 of file CHPData.cpp.
References ARRAY_TYPE_MAX_LEN, ARRAY_TYPE_PARAM_NAME, and SetWStringToGenericHdr().
void CHPData::SetBackgroundZoneCnt (int32_t ln)
Sets the number of background zones.
Definition at line 531 of file CHPData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), CHP_BG_ZONE_GROUP, genericData, affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), and affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile().
void CHPData::SetCols (int32_t value)
Sets the number of columns of features on the array.
Definition at line 768 of file CHPData.cpp.
References cachedCols, CEL_COLS_PARAM_NAME, and SetInt32ToGenericHdr().
void CHPData::SetEntryCount (int32_t ln, int32_t maxln, bool hasCompData = false)
Sets the number of entries (probe sets)
Parameters:
ln The number of probe sets.
maxln The maximum length of a probe set name.
hasCompData A flag for expression results, true if comparison data exists.
Definition at line 514 of file CHPData.cpp.
References AddColumns(), affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), genericData, affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::GenericData::Header(), maxProbeSetName, and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), and affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile().
void CHPData::SetFilename (const std::string & p)
Sets the name of the CHP file.
Definition at line 487 of file CHPData.cpp.
References genericData, affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_io::FileHeader::SetFilename().
Referenced by CHPData(), and affymetrix_fusion_io::CalvinCHPDataAdapter::SetFileName().
void CHPData::SetFloatToGenericHdr (const std::wstring & name, float value) [protected]
Adds an float parameter to the header.
Definition at line 816 of file CHPData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), genericData, affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueFloat().
Referenced by AddAlgParam(), and AddChipSum().
void CHPData::SetForceCnt (int32_t ln)
Sets the number of force calls.
Definition at line 557 of file CHPData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddByteColumn(), affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::DataSetHeader::AddIntColumn(), CHP_RESEQ_FORCE_CALL_GROUP, genericData, affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), and affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile().
void CHPData::SetInt32ToGenericHdr (const std::wstring & name, int32_t value) [protected]
Adds an integer parameter to the header.
Definition at line 807 of file CHPData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), genericData, affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueInt32().
Referenced by AddAlgParam(), SetCols(), and SetRows().
void CHPData::SetOrigCnt (int32_t ln)
Sets the number of orig calls.
Definition at line 581 of file CHPData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddByteColumn(), affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::DataSetHeader::AddIntColumn(), CHP_RESEQ_ORIG_CALL_GROUP, genericData, affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), and affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile().
void CHPData::SetParentCell (const std::wstring & value)
Sets the name of the parent CEL file
Definition at line 621 of file CHPData.cpp.
References CHP_PARENT_CELL, and SetWStringToGenericHdr().
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), and affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile().
void CHPData::SetProgId (const std::wstring & value)
Sets the prog ID for the CHP file.
Definition at line 641 of file CHPData.cpp.
References CHP_PROGID, and SetWStringToGenericHdr().
void CHPData::SetRows (int32_t value)
Sets the number of rows of features on the array.
Definition at line 755 of file CHPData.cpp.
References cachedCols, CEL_ROWS_PARAM_NAME, and SetInt32ToGenericHdr().
void CHPData::SetWStringToGenericHdr (const std::wstring & name, const std::wstring value, int32_t reserve = -1) [protected]
Adds a string parameter to the header.
Definition at line 786 of file CHPData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), genericData, affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueText().
Referenced by AddAlgParam(), AddChipSum(), SetAlgName(), SetAlgVersion(), SetArrayType(), SetParentCell(), and SetProgId().
Member Data Documentation
DataSet* affymetrix_calvin_io::CHPData::bgZones [protected]
chp background zones DataSet
Definition at line 116 of file CHPData.h.
Referenced by CHPData(), Clear(), GetBackgroundZone(), and PrepareBackgroundZoneDataSet().
int32_t affymetrix_calvin_io::CHPData::cachedCols [protected]
keep cols from being read from the header all the time
Definition at line 106 of file CHPData.h.
Referenced by Clear(), GetCols(), SetCols(), and SetRows().
int32_t affymetrix_calvin_io::CHPData::cachedRows [protected]
keep rows from being read from the header all the time
Definition at line 104 of file CHPData.h.
Referenced by Clear(), and GetRows().
DataSet* affymetrix_calvin_io::CHPData::entriesExp [protected]
expression entries DataSet
Definition at line 108 of file CHPData.h.
Referenced by CHPData(), Clear(), GetEntry(), and PrepareExprEntryDataSet().
DataSet* affymetrix_calvin_io::CHPData::entriesGeno [protected]
genotyping entries DataSet
Definition at line 110 of file CHPData.h.
Referenced by CHPData(), Clear(), GetEntry(), and PrepareGenoEntryDataSet().
DataSet* affymetrix_calvin_io::CHPData::entriesReseq [protected]
resequencing entries DataSet
Definition at line 114 of file CHPData.h.
Referenced by CHPData(), Clear(), GetEntry(), and PrepareReseqEntryDataSet().
DataSet* affymetrix_calvin_io::CHPData::entriesUniv [protected]
universal entries DataSet
Definition at line 112 of file CHPData.h.
Referenced by CHPData(), Clear(), GetEntry(), and PrepareUnivEntryDataSet().
DataSet* affymetrix_calvin_io::CHPData::forceSet [protected]
chp force call DataSet
Definition at line 118 of file CHPData.h.
Referenced by CHPData(), Clear(), GetForceCall(), and PrepareForceDataSet().
GenericData affymetrix_calvin_io::CHPData::genericData [protected]
The generic file data object.
Definition at line 102 of file CHPData.h.
Referenced by AddColumns(), CHPData(), Clear(), GetAlgParam(), GetAlgParams(), GetAssayType(), GetBackgroundZoneCnt(), GetChipSum(), GetChipSums(), GetEntryCount(), GetFileHeader(), GetFilename(), GetForceCnt(), GetGenericData(), GetInt32FromGenericHdr(), GetMagic(), GetOrigCnt(), GetVersion(), GetWStringFromGenericHdr(), PrepareBackgroundZoneDataSet(), PrepareExprEntryDataSet(), PrepareForceDataSet(), PrepareGenoEntryDataSet(), PrepareOrigDataSet(), PrepareReseqEntryDataSet(), PrepareUnivEntryDataSet(), SetBackgroundZoneCnt(), SetEntryCount(), SetFilename(), SetFloatToGenericHdr(), SetForceCnt(), SetInt32ToGenericHdr(), SetOrigCnt(), and SetWStringToGenericHdr().
int affymetrix_calvin_io::CHPData::maxProbeSetName [protected]
The maximum length of a probe set name.
Definition at line 100 of file CHPData.h.
Referenced by AddExprColumns(), AddGenoColumns(), GetMaxProbeSetName(), and SetEntryCount().
DataSet* affymetrix_calvin_io::CHPData::origSet [protected]
chp orig DataSet
Definition at line 120 of file CHPData.h.
Referenced by CHPData(), Clear(), GetOrigCall(), and PrepareOrigDataSet().
bool affymetrix_calvin_io::CHPData::wideProbeSetNames [protected]
Flag indicating if the probe set names were stored in wide character format.
Definition at line 98 of file CHPData.h.
Referenced by CHPData(), GetEntry(), PrepareExprEntryDataSet(), and PrepareGenoEntryDataSet().
The documentation for this class was generated from the following files:
calvin_files/data/src/CHPData.h
calvin_files/data/src/CHPData.cpp