Affymetrix Power Tools: CNAnalysisMethodLOH Class Reference
CNAnalysisMethodLOH Class Reference
The LOH analysis method.
#include <CNAnalysisMethodLOH.h>