Affymetrix Power Tools: IntensityTransformer Class Reference
IntensityTransformer Class Reference
IntensityTransformer - Abstract base class for objects that transform intensity data.
#include <IntensityTransformer.h>