Affymetrix Power Tools: CNAnalysisMethodSegmentCN Class Reference
CNAnalysisMethodSegmentCN Class Reference
The SegmentCN analysis method.
#include <CNAnalysisMethodSegmentCN.h>