Affymetrix Power Tools: Probe Class Reference
Probe Class Reference
Represents an individual feature on a chip.
#include <ProbeSet.h>
Public Types
enum ProbeType {
PMST = 0, MMST = 1, PMAT = 2, MMAT = 3,
GENERICST = 4, GENERICAT = 5, JUMBOAT = 6, JUMBOST = 7,
THERMOAT = 8, THERMOST = 9, TRIGRIDAT = 10, TRIGRIDST = 11,
BLANK = 12
}
Type of probe.
Public Member Functions
Probe ()
Default constructor.
void clear ()
Probe (const std::vector< std::string > &vec, unsigned int offSet=0)
Construct probe from a list of strings.
Probe (const std::vector< const char * > &vec, unsigned int offSet=0)
Construct probe from a list of char *.
unsigned int numFields ()
Minimum number of fields that a probe requires.
int getApid () const
bool isNull ()
Static Public Member Functions
static const char * stringForType (Probe::ProbeType t)
String reprentation of probe type.
static ProbeType typeForString (const std::string &cs)
What type of probe does a string indicate?
static bool isPm (const Probe &p)
static bool isMm (const Probe &p)
static Probe * cloneProbe (const Probe &p)
Allocate new memory for a probe and fill in values coppied from supplied probe.
Public Attributes
probeid_t id
Id of probe, in practice usually realated to position on array.
unsigned char type
Type of probe.
char gcCount
How many G/C nucleotides does the probe have? NULLPROBEGC is null value.
int m_apid
Atom that this probe is a part of. Memory not owned here.
Detailed Description
Represents an individual feature on a chip.
NOTE The Probe, Atom and ProbeSet classes were determined to be wasting valuable RAM and are being transitioned to the ProbeList class. Please code accordingly.
In principle a probe is a piece of dna of a particular sequence. In practice probes are treated differently if the are different x,y spots on the array even if they contain exactly the same sequence.
For the CEL file SDK the order of the probes indexes are:
   (0,0) (1,0) (2,0) (3,0) ... (numCols,0)
   (0,1) (1,1) (2,1) (3,1) ... (numCols,1)
   (0,2) (1,2) (2,2) (3,2) ... (numCols,2)
   ...
   (0,numRows)       ... (numCols,numRows)
Where in cel file terminology cols are the x dimension and rows are the y dimension. So using the standard XYToIndex() function in the cel file API you can transform into a single vector index i using:
i = ((y*numColumns) + x)
x = i % numCols
y = i / numCols
This index, i, is used as the probe id in the probe data structure as it is unique and provides an easy index into a vector that represent all of the data in the array. While it is 0 based there are files that are 1 based (notably the PGF file) and sometimes it is necessary to increment or decrement the id to accomedate the application or file format.
So the index (and thus probe ids) numbering when num cols = 10
   0  1  2  3  4  5  6  7  8  9
   10 11 12 13 14 15 16 17 18 19
   20 21 22 23 24 25 26 27 28 29
Note that these indexes are only for the CEL files as the underlying DAT files can be rotated depending on the scanner and application.
Definition at line 109 of file ProbeSet.h.
Constructor & Destructor Documentation
Probe::Probe (const std::vector< std::string > & vec, unsigned int offSet = 0)
Construct probe from a list of strings.
Constructor for creating a probe from a vector of words.
Parameters:
vec - Collection of strings.
offSet - Where in vector strings of intrest start.
vec - vector of strings containing probe information.
Definition at line 65 of file ProbeSet.cpp.
References Err::errAbort(), gcCount, m_apid, numFields(), Convert::toInt(), ToStr(), type, and typeForString().
Probe::Probe (const std::vector< const char * > & vec, unsigned int offSet = 0)
Construct probe from a list of char *.
Constructor for creating a probe from a vector of words.
Parameters:
vec - char * with data to make probe.
offSet - Offset of data in vector.
vec - vector of strings containing probe information.
Definition at line 83 of file ProbeSet.cpp.
References Err::errAbort(), gcCount, m_apid, numFields(), Convert::toInt(), ToStr(), type, and typeForString().
Member Function Documentation
static Probe* Probe::cloneProbe (const Probe & p) [inline, static]
Allocate new memory for a probe and fill in values coppied from supplied probe.
Must delete this memory when finished.
Parameters:
p - probe to be cloned.
Returns:
- new probe object allocated on heap, delete when done.
Todo:
this should be "probe->copy()"
Definition at line 185 of file ProbeSet.h.
References gcCount, id, m_apid, Probe(), and type.
Referenced by AnalysisStreamExpression::makeSelectProbesetGroup(), and AnalysisStreamFactory::setGcControlProbes().
unsigned int Probe::numFields () [inline]
Minimum number of fields that a probe requires.
Returns:
Minimum number of fields
Definition at line 201 of file ProbeSet.h.
Referenced by Probe().
const char * Probe::stringForType (Probe::ProbeType t) [static]
String reprentation of probe type.
Parameters:
t Type of probe.
Returns:
Character description of probe type.
Definition at line 96 of file ProbeSet.cpp.
References Err::errAbort(), and ToStr().
Referenced by operator<<(), and ChipLayout::writePgfFile().
Probe::ProbeType Probe::typeForString (const std::string & cs) [static]
What type of probe does a string indicate?
Parameters:
cs - Description of probe type.
Returns:
Type of probe.
Definition at line 131 of file ProbeSet.cpp.
References APT_ERR_ABORT.
Referenced by Probe(), and ChipLayout::readProbeListPgfFileKillList().
Member Data Documentation
int Probe::m_apid
Atom that this probe is a part of. Memory not owned here.
The AnalysisProbeId. /// This is set when the a ProbeSet extracted from a ProbeListFactory. /// -1 otherwise.
Definition at line 226 of file ProbeSet.h.
Referenced by cloneProbe(), and Probe().
The documentation for this class was generated from the following files:
chipstream/ProbeSet.h
chipstream/ProbeSet.cpp