Affymetrix Power Tools: CNFamilialAnalysisMethodDenovoCopyNumber Class Reference
CNFamilialAnalysisMethodDenovoCopyNumber Class Reference
The DenovoCopyNumber Familial analysis method.
#include <CNFamilialAnalysisMethodDenovoCopyNumber.h>