Affymetrix Power Tools: CQuartet Class Reference
CQuartet Class Reference
An object to probe quartet, each quartet contains 4 cells each cell contains intensity, variance and number of pixels, store variance instead of stdev.
#include <DM.h>
Public Types
enum Allele { A_Allele, B_Allele }
alleles
enum MatchType { PM, MM }
match types
Public Member Functions
int GetIndex (const int &allele, const int &matchtype)
get the probe quartet given the allele type and match type
CQuartet ()
default constructor
void SetIntensity (const int &allele, const int &matchtype, const float &val)
set intensity for allele type=allele and match type = matchtype
void SetVariance (const int &allele, const int &matchtype, const float &val)
set variance for allele type=allele and match type = matchtype
void SetPixels (const int &allele, const int &matchtype, const int &val)
set number of pixels for allele type=allele and match type = matchtype
Public Attributes
int pixels [NUMCELLS]
four cells in the order of PM_A, MM_A, PM_B and MM_B /// number of pixels per cell
float intensity [NUMCELLS]
intensities of each cell of the quartet
float variance [NUMCELLS]
variances of each cell of the quartet
Detailed Description
An object to probe quartet, each quartet contains 4 cells each cell contains intensity, variance and number of pixels, store variance instead of stdev.
Definition at line 52 of file DM.h.
Member Function Documentation
int CQuartet::GetIndex (const int & allele, const int & matchtype)
get the probe quartet given the allele type and match type
Parameters:
allele - allele type: A or B
matchtype - the match type: perfect or mis
Returns:
the probe index
Definition at line 52 of file DM.cpp.
Referenced by SetIntensity(), SetPixels(), and SetVariance().
void CQuartet::SetIntensity (const int & allele, const int & matchtype, const float & val) [inline]
set intensity for allele type=allele and match type = matchtype
Parameters:
allele - allele type: A or B
matchtype - the match type: perfect or mis
val - the value to be set
Returns:
void
Definition at line 98 of file DM.h.
References GetIndex(), and intensity.
Referenced by DmListener::fillInQuartet().
void CQuartet::SetPixels (const int & allele, const int & matchtype, const int & val) [inline]
set number of pixels for allele type=allele and match type = matchtype
Parameters:
allele - allele type: A or B
matchtype - the match type: perfect or mis
val - the value to be set
Returns:
void
Definition at line 122 of file DM.h.
References GetIndex(), and pixels.
Referenced by DmListener::fillInQuartet().
void CQuartet::SetVariance (const int & allele, const int & matchtype, const float & val) [inline]
set variance for allele type=allele and match type = matchtype
Parameters:
allele - allele type: A or B
matchtype - the match type: perfect or mis
val - the value to be set
Returns:
void
Definition at line 110 of file DM.h.
References GetIndex(), and variance.
Referenced by DmListener::fillInQuartet().
The documentation for this class was generated from the following files:
dm/DM.h
dm/DM.cpp