Affymetrix Power Tools: AnalysisStreamGType Class Reference
AnalysisStreamGType Class Reference