Affymetrix Power Tools: affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter Class Reference
affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter Class Reference
Public Member Functions
CHPQuantificationDetectionFileBufferWriter ()
~CHPQuantificationDetectionFileBufferWriter ()
void SetMaxBufferSize (int MaxBufferSize)
void Cleanup ()
void Initialize (std::vector< std::string > *CHPFileNames)
void WriteQuantificationDetectionEntry (int target, float quantification, float pvalue)
void FlushBuffer ()
Detailed Description
Definition at line 41 of file CalvinCHPQuantificationDetectionFileBufferWriter.h.
Constructor & Destructor Documentation
CHPQuantificationDetectionFileBufferWriter::CHPQuantificationDetectionFileBufferWriter ()
Constructor
Definition at line 36 of file CalvinCHPQuantificationDetectionFileBufferWriter.cpp.
CHPQuantificationDetectionFileBufferWriter::~CHPQuantificationDetectionFileBufferWriter ()
Destructor
Definition at line 42 of file CalvinCHPQuantificationDetectionFileBufferWriter.cpp.
References Cleanup(), and FlushBuffer().
Member Function Documentation
void CHPQuantificationDetectionFileBufferWriter::Cleanup ()
Cleans up memory
Definition at line 48 of file CalvinCHPQuantificationDetectionFileBufferWriter.cpp.
Referenced by Initialize(), and ~CHPQuantificationDetectionFileBufferWriter().
void CHPQuantificationDetectionFileBufferWriter::FlushBuffer ()
Write the content of the buffer to CHP files.
Definition at line 80 of file CalvinCHPQuantificationDetectionFileBufferWriter.cpp.
References affymetrix_calvin_io::CalvinCHPFileUpdater::CloseCHPFile(), affymetrix_calvin_io::CalvinCHPFileUpdater::OpenCHPFile(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantificationDetectionBuffer().
Referenced by WriteQuantificationDetectionEntry(), and ~CHPQuantificationDetectionFileBufferWriter().
void CHPQuantificationDetectionFileBufferWriter::Initialize (std::vector< std::string > * CHPFileNames)
Initialize Quantification buffer writer
Parameters:
CHPFileNames Reference to a list of CHP file names.
Definition at line 57 of file CalvinCHPQuantificationDetectionFileBufferWriter.cpp.
References Cleanup().
void affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter::SetMaxBufferSize (int MaxBufferSize) [inline]
Set maximum buffer size
Definition at line 51 of file CalvinCHPQuantificationDetectionFileBufferWriter.h.
void CHPQuantificationDetectionFileBufferWriter::WriteQuantificationDetectionEntry (int target, float quantification, float pvalue)
Write a quantification entry to buffer. If the buffer is full, flush it.
Parameters:
target Target for the quantification entry.
quantification Value for the quantification entry.
pvalue The pvalue for the entry.
Definition at line 70 of file CalvinCHPQuantificationDetectionFileBufferWriter.cpp.
References FlushBuffer().
The documentation for this class was generated from the following files:
calvin_files/writers/src/CalvinCHPQuantificationDetectionFileBufferWriter.h
calvin_files/writers/src/CalvinCHPQuantificationDetectionFileBufferWriter.cpp