Affymetrix Power Tools: CNAnalysisMethodCovariateLRAdjuster Class Reference
CNAnalysisMethodCovariateLRAdjuster Class Reference
CNAnalysisMethodCovariateLRAdjuster - Class for doing covariate-based log2ratio adjustment.
#include <CNAnalysisMethodCovariateLRAdjuster.h>