Affymetrix Power Tools: CNAnalysisMethodCN Class Reference
CNAnalysisMethodCN Class Reference
The CN analysis method.
#include <CNAnalysisMethodCN.h>