Affymetrix Power Tools: SelfDoc::Opt Class Reference
SelfDoc::Opt Class Reference
Description of one possible option/parameter for a self describing class.
#include <SelfDoc.h>
Public Types
enum OptType {
String, Double, Float, Integer,
Boolean
}
Types of options supported.
Public Member Functions
bool checkOption () const
Check to see that an option's value is valid.
double asDouble () const
float asFloat () const
int asInt () const
bool asBool () const
std::string asString () const
Public Attributes
std::string name
Name of option.
enum SelfDoc::Opt::OptType type
What data type is our option.
std::string value
Current value for option.
std::string defaultVal
Default value for option.
std::string minVal
Minimum value acceptable for numeric types, or NA if not used.
std::string maxVal
Maximum value acceptable for numeric types, or NA if not used.
std::string descript
Short description of our option and what it is used for.
Detailed Description
Description of one possible option/parameter for a self describing class.
Definition at line 53 of file SelfDoc.h.
Member Enumeration Documentation
enum SelfDoc::Opt::OptType
Types of options supported.
Definition at line 56 of file SelfDoc.h.
Member Function Documentation
bool SelfDoc::Opt::checkOption () const
Check to see that an option's value is valid.
Returns:
true if option is valid - false otherwise.
Definition at line 24 of file SelfDoc.cpp.
References Err::errAbort(), Err::getThrowStatus(), maxVal, minVal, name, Err::setThrowStatus(), Convert::toDouble(), Convert::toFloat(), Convert::toInt(), ToStr(), type, value, and Except::what().
Referenced by SelfDoc::setOptValue().
The documentation for this class was generated from the following files:
chipstream/SelfDoc.h
chipstream/SelfDoc.cpp