Affymetrix Power Tools: affymetrix_fusion_io::CalvinCHPHeaderAdapter Class Reference
affymetrix_fusion_io::CalvinCHPHeaderAdapter Class Reference
Header class for the Calvin CHP adapter.
#include <CalvinCHPDataAdapter.h>