Affymetrix Power Tools: QuantMethodFactory Class Reference
QuantMethodFactory Class Reference
Factory class for making chip streams based on a string representation.
#include <QuantMethodFactory.h>
Public Types
enum QuantType { Expression, GenoType }
Public Member Functions
QuantMethodFactory ()
Constructor.
QuantMethodFactory (enum QuantType type)
Constructor.
void registerMethod (SelfDoc &doc, SelfCreate::selfCreator maker)
QuantMethod * qMethodForString (const std::string &spec)
Create a pointer to a new QuantMethod object as described in the string specification.
QuantMethod * quantMethodForString (const string &spec, PsBoard &board, QuantType type)
Create a pointer to a new QuantMethod object as described in the string specification.
QuantMethod * quantMethodForString (const string &spec, PsBoard &board)
Create a pointer to a new QuantMethod object as described in the string specification.
QuantMethod * quantMethodForString (string &spec, ChipLayout &layout, QuantType type)
Factory for creating QuantMethod from string representation.
QuantExprMethod * quantExprMethodForString (string &spec, ChipLayout &layout, QuantType type)
Factory for creating QuantMethod from string representation.
QuantGTypeMethod * quantGTypeMethodForString (string &spec, ChipLayout &layout, QuantType type)
Factory for creating genotyping QuantMethod from string representation.
void setGcControlProbes (const std::vector< Probe * > &gcControlProbes)
Set the probes to be used as gc background for quantification methods.
int openPrecompFeatureEffects_A5 (affx::File5_Group *group5, const std::string &name, double *effects, const ChipLayout &layout)
const void readPrecompFeatureEffectsFromFile (int iProbeCount, const std::string &fileName, const ChipLayout &layout)
Read the feature responses from a file.
void readPrecompFeatureEffectsFrom_A5 (int iProbeCount, affx::File5_Group *group5, const std::string &name, const ChipLayout &layout)
std::vector< SelfDoc > getDocs ()
Get the vector of documentation objects that this factory is aware of.
bool canBuild (const std::string &spec)
Can this factory be used to build from this specification?
Static Public Member Functions
static int openPrecompFeatureEffects (const std::string &fileName, double *effects, const ChipLayout &layout)
Open a file and read the precomputed probe effects to use in plier from it.
static void setupQuantMethodFactory (QuantMethodFactory &qFactory, affx::File5_File *inputFile, affx::File5_Group *inputGroup, affx::File5_File *outputFile, affx::File5_Group *outputGroup, uint32_t probeCount, const std::string &outDir, const std::string &useFeatEff, bool a5FeatureEffectsInputGlobal, const std::string &a5FeatureEffectsInputFile, const std::string &a5FeatureEffectsInputName, const std::string &a5FeatureEffectsInputGroup, const std::string &a5InputGroup, const std::string &a5Group, const std::string &setAnalysisName, const std::string &quantMethodSpec, const ChipLayout &layout)
Protected Attributes
double * m_PrecompFeatureEffects
int m_iFeatureEffectSize
std::vector< Probe * > m_GcControlProbes
Background probes to use. Note that the memory is owned elsewhere.
std::vector< SelfDoc > m_Docs
Self documentation.
std::vector
< SelfCreate::selfCreator > m_Creators
Self creation.
Detailed Description
Factory class for making chip streams based on a string representation.
Definition at line 58 of file QuantMethodFactory.h.
Constructor & Destructor Documentation
QuantMethodFactory::QuantMethodFactory ()
Constructor.
Registers the objects we know how to create and how they describe themselves.
Definition at line 133 of file QuantMethodFactory.cpp.
References QuantBirdseedLegacy::explainSelf(), QuantBirdseedv2::explainSelf(), QuantBirdseedDev::explainSelf(), QuantBirdseedv1::explainSelf(), QuantLabelZMulti::explainSelf(), QuantLabelZ::explainSelf(), QuantBRLMM::explainSelf(), QuantMedian::explainSelf(), QuantAvgDiff::explainSelf(), QuantDabg::explainSelf(), QuantRma::explainSelf(), QuantIterPlier::explainSelf(), QuantSea::explainSelf(), QuantPlier::explainSelf(), QuantBirdseedLegacy::newObject(), QuantBirdseedv2::newObject(), QuantBirdseedDev::newObject(), QuantBirdseedv1::newObject(), QuantLabelZMulti::newObject(), QuantLabelZ::newObject(), QuantBRLMM::newObject(), QuantMedian::newObject(), QuantAvgDiff::newObject(), QuantDabg::newObject(), QuantRma::newObject(), QuantIterPlier::newObject(), QuantSea::newObject(), and QuantPlier::newObject().
QuantMethodFactory::QuantMethodFactory (enum QuantType type)
Constructor.
Registers the objects we know how to create and how they describe themselves.
Parameters:
Type of Quantification methods to make available.
Registers the objects we know how to create and how they describe themselves.
Definition at line 60 of file QuantMethodFactory.cpp.
References Err::errAbort(), QuantBirdseedLegacy::explainSelf(), QuantBirdseedv2::explainSelf(), QuantBirdseedDev::explainSelf(), QuantBirdseedv1::explainSelf(), QuantLabelZMulti::explainSelf(), QuantLabelZ::explainSelf(), QuantBRLMM::explainSelf(), QuantMedian::explainSelf(), QuantAvgDiff::explainSelf(), QuantDabg::explainSelf(), QuantRma::explainSelf(), QuantIterPlier::explainSelf(), QuantSea::explainSelf(), QuantPlier::explainSelf(), QuantBirdseedLegacy::newObject(), QuantBirdseedv2::newObject(), QuantBirdseedDev::newObject(), QuantBirdseedv1::newObject(), QuantLabelZMulti::newObject(), QuantLabelZ::newObject(), QuantBRLMM::newObject(), QuantMedian::newObject(), QuantAvgDiff::newObject(), QuantDabg::newObject(), QuantRma::newObject(), QuantIterPlier::newObject(), QuantSea::newObject(), QuantPlier::newObject(), and ToStr().
Member Function Documentation
bool QuantMethodFactory::canBuild (const std::string & spec) [inline]
Can this factory be used to build from this specification?
Parameters:
spec - Specification in form "chipstream.key=value.key=value"
Returns:
true if this factory knows how to build from this specification, false otherwise
Definition at line 225 of file QuantMethodFactory.h.
References SelfCreate::canMake(), and m_Docs.
Referenced by DTFactory::dataTransformForString().
std::vector<SelfDoc> QuantMethodFactory::getDocs () [inline]
Get the vector of documentation objects that this factory is aware of.
Returns:
- vector of documentation objects.
Definition at line 195 of file QuantMethodFactory.h.
References m_Docs.
Referenced by EngineUtil::explainParameter().
int QuantMethodFactory::openPrecompFeatureEffects (const std::string & fileName, double * effects, const ChipLayout & layout) [static]
Open a file and read the precomputed probe effects to use in plier from it.
Parameters:
fileName - Path to file containing probe effects.
effects - Map of probe ids to probe effects to be filled in.
File must be tab delimited and contain the columns: "probeset_id", "probe_id", and "feature_response"
Parameters:
fileName - Path to file containing probe effects.
effects - Map of probe ids to probe effects to be filled in.
opts - Options used in filling in.
Definition at line 346 of file QuantMethodFactory.cpp.
References affx::TsvFile::close(), affx::TsvFile::cname2cidx(), Err::errAbort(), ChipLayout::findProbeApidByProbeId(), affx::TsvFile::formatOk(), ChipLayout::m_PlFactory, affx::TsvFile::nextLevel(), affx::TsvFile::open(), Verbose::out(), ToStr(), and affx::TSV_BIND_REQUIRED.
Referenced by readPrecompFeatureEffectsFromFile(), QuantRma::setParameters(), and QuantPlierBase::setParameters().
QuantMethod * QuantMethodFactory::qMethodForString (const std::string & spec)
Create a pointer to a new QuantMethod object as described in the string specification.
Parameters:
spec - Specification string i.e. quant-norm.sketch=1000000
Returns:
Pointer to new QuantMethod objects, must be deleted when finished.
Definition at line 209 of file QuantMethodFactory.cpp.
References Err::errAbort(), m_Creators, m_Docs, and SelfCreate::selfCreateFromString().
Referenced by quantMethodForString().
QuantExprMethod * QuantMethodFactory::quantExprMethodForString (string & spec, ChipLayout & layout, QuantType type)
Factory for creating QuantMethod from string representation.
Parameters:
spec - Name of QuantMethod.
layout - Probe and probe set info.
Returns:
Quantification method requested.
Definition at line 309 of file QuantMethodFactory.cpp.
References Err::errAbort(), QuantMethod::getType(), and quantMethodForString().
Referenced by AnalysisStreamFactory::constructExpressionAnalysisStages(), AnalysisStreamFactory::constructExpressionAnalysisStream(), QuantBRLMM::setUp(), QuantBirdseed::setUp(), and QuantLabelZ::SetUpProbeSet().
QuantGTypeMethod * QuantMethodFactory::quantGTypeMethodForString (string & spec, ChipLayout & layout, QuantType type)
Factory for creating genotyping QuantMethod from string representation.
Parameters:
spec - Name of QuantMethod.
layout - Probe and probe set info.
Returns:
Quantification method requested.
Definition at line 328 of file QuantMethodFactory.cpp.
References Err::errAbort(), QuantMethod::getType(), and quantMethodForString().
Referenced by callGenotypes(), and AnalysisStreamFactory::constructGTypeAnalysisStream().
QuantMethod * QuantMethodFactory::quantMethodForString (const string & spec, PsBoard & board)
Create a pointer to a new QuantMethod object as described in the string specification.
Factory for creating QuantMethod from string representation.
Parameters:
spec - Specification string i.e. quant-norm.sketch=1000000
board - Blackboard with various state
Returns:
Pointer to new QuantMethod objects, must be deleted when finished.
Parameters:
spec - Name of QuantMethod.
layout - Probe and probe set info.
Returns:
Quantification method requested.
Definition at line 292 of file QuantMethodFactory.cpp.
References qMethodForString(), and QuantMethod::setParameters().
QuantMethod * QuantMethodFactory::quantMethodForString (string & spec, ChipLayout & layout, QuantType type)
Factory for creating QuantMethod from string representation.
Parameters:
spec - Name of QuantMethod.
layout - Probe and probe set info.
Returns:
Quantification method requested.
Definition at line 232 of file QuantMethodFactory.cpp.
References Err::errAbort(), m_GcControlProbes, ChipLayout::m_PlFactory, Verbose::out(), qMethodForString(), and ToStr().
QuantMethod * QuantMethodFactory::quantMethodForString (const string & spec, PsBoard & board, QuantType type)
Create a pointer to a new QuantMethod object as described in the string specification.
Factory for creating QuantMethod from string representation.
Parameters:
spec - Specification string i.e. quant-norm.sketch=1000000
board - Blackboard with various state
Returns:
Pointer to new QuantMethod objects, must be deleted when finished.
Parameters:
spec - Name of QuantMethod.
layout - Probe and probe set info.
Returns:
Quantification method requested.
Definition at line 274 of file QuantMethodFactory.cpp.
References qMethodForString(), and QuantMethod::setParameters().
Referenced by AnalysisStreamFactory::constructAnalysisStream(), DTFactory::dataTransformForString(), quantExprMethodForString(), quantGTypeMethodForString(), QuantLabelZ::setParameters(), and QuantBirdseed::setParameters().
const void QuantMethodFactory::readPrecompFeatureEffectsFromFile (int iProbeCount, const std::string & fileName, const ChipLayout & layout)
Read the feature responses from a file.
File should have columns for 'probeset_id', 'probe_id' and 'feature_response'.
Parameters:
fileName - text file with feature responses.
Definition at line 512 of file QuantMethodFactory.cpp.
References ChipLayout::m_PlFactory, openPrecompFeatureEffects(), Verbose::out(), and ToStr().
Referenced by AnalysisStreamFactory::readPrecompFeatureEffectsFromFile(), and setupQuantMethodFactory().
void QuantMethodFactory::setGcControlProbes (const std::vector< Probe * > & gcControlProbes) [inline]
Set the probes to be used as gc background for quantification methods.
Note that memory for the probes is owned elsewhere.
Parameters:
gcControlProbes - Probes that should be used for background distribution.
Definition at line 153 of file QuantMethodFactory.h.
References m_GcControlProbes.
Referenced by AnalysisStreamFactory::readControlProbes(), and AnalysisStreamFactory::setGcControlProbes().
void QuantMethodFactory::setupQuantMethodFactory (QuantMethodFactory & qFactory, affx::File5_File * inputFile, affx::File5_Group * inputGroup, affx::File5_File * outputFile, affx::File5_Group * outputGroup, uint32_t probeCount, const std::string & outDir, const std::string & useFeatEff, bool a5FeatureEffectsInputGlobal, const std::string & a5FeatureEffectsInputFile, const std::string & a5FeatureEffectsInputName, const std::string & a5FeatureEffectsInputGroup, const std::string & a5InputGroup, const std::string & a5Group, const std::string & setAnalysisName, const std::string & quantMethodSpec, const ChipLayout & layout) [static]
Todo:
this should really be based on the analysis name which means /// that this functionality needs to be in a QuantMethod instance /// and not in the factory
Definition at line 549 of file QuantMethodFactory.cpp.
References Err::errAbort(), Freez(), Verbose::out(), and readPrecompFeatureEffectsFromFile().
The documentation for this class was generated from the following files:
chipstream/QuantMethodFactory.h
chipstream/QuantMethodFactory.cpp