Affymetrix Power Tools: CNExperiment Class Reference
CNExperiment Class Reference
A class for storing CNExperiment data.
#include <CNExperiment.h>
Classes
struct ComparePred
struct ComparePred< 0 >
Public Types
typedef std::vector< std::pair
< int, float > > wavAmplitudes_t
Public Member Functions
CNExperiment ()
Constructor.
virtual ~CNExperiment ()
Destructor.
int getIndex ()
void setIndex (int i)
AffxString getExperimentNormalDiploidFileName ()
void setExperimentNormalDiploidFileName (const AffxString &str)
int getCNCallGenderNotZero ()
void setCNCallGenderNotZero (int i)
int getCNCallGenderYCount ()
void setCNCallGenderYCount (int i)
bool getCNCallGenderComputed ()
void setCNCallGenderComputed (bool b)
AffxString getExperimentName ()
void setExperimentName (const AffxString &str)
bool hasXX ()
void setXX (bool b)
bool hasY ()
void setY (bool b)
float getXXRatio ()
void setXXRatio (float f)
float getYRatio ()
void setYRatio (float f)
float getMedianAutosomeMedian ()
void setMedianAutosomeMedian (float f)
float getMadDiffCN ()
void setMadDiffCN (float f)
float getIqr ()
void setIqr (float f)
float getMeanAbsRle ()
void setMeanAbsRle (float f)
float getGCCorrectionMetric ()
void setGCCorrectionMetric (float f)
AffxArray< AffxString > * getQCMetricColumnValues ()
float getChrXMean ()
void setChrXMean (float f)
float getChrYMean ()
void setChrYMean (float f)
float getCNCallGenderRatio ()
void setCNCallgenderRatio (float f)
float getRawIntensityRatio ()
void setRawIntensityRatio (float f)
float getMedianCnState ()
void setMedianCnState (float f)
float getHomFrequency ()
void setHomFrequency (float f)
float getHetFrequency ()
void setHetFrequency (float f)
double getPError ()
void setPError (double d)
float getCNCallGenderConfidence ()
void setCNCallGenderConfidence (float f)
void setCNCallGenderRatio (float f)
float getMedianRawIntensity ()
void setMedianRawIntensity (float f)
float getCallRate ()
void setCallRate (float f)
float getSNPQC ()
void setSNPQC (float f)
bool isSNPQCset ()
void setIsSNPQCset (bool b)
float getRawSNPQC ()
void setRawSNPQC (float f)
float getAntigenomicRatio ()
void setAntigenomicRatio (float f)
int getWavinessSegCountLoss ()
void setWavinessSegCountLoss (int i)
int getWavinessSegCountGain ()
void setWavinessSegCountGain (int i)
int getWavinessSegCountTotal ()
float getWavinessSd ()
void setWavinessSd (float f)
wavAmplitudes_t getWavinessAmplitudes ()
void addWavinessAmplitude (int iWaveIndex, float wavAmplitude)
std::pair< char, float > getChromosomeLOH (int iIndex)
void addChromosomeSummaryData (std::pair< char, float > data)
float getGenomeLOH ()
void setGenomeLOH (float fGenomeLOH)
float getAutosomeGenomeLOH ()
void setAutosomeGenomeLOH (float fAutosomeGenomeLOH)
int getNumberOfChromosomesToReport ()
void setNumberOfChromosomesToReport (int iNumberOfChromosomes)
int getNumberOfWavesUsed ()
void setNumberOfWavesUsed (int iNumberOfWavesUsed)
void setCNReferenceHeader (const std::vector< std::string > &vInput)
std::vector< std::string > * getCNReferenceHeader ()
float getL2Gradient ()
void setL2Gradient (float value)
int compareTo (CNExperiment &that, int iCompareCode)
Compare function.
void setCNCallGender (affx::Gender eGender)
Set the gender for the sample using the affx gender code.
void setRawIntensityRatioGender (affx::Gender eGender)
void setRawIntensityRatioGenderFromString (const AffxString &strIn)
Set the gender for the sample using a string 'male' or 'female'.
void setCNCallGenderFromString (const AffxString &strIn)
AffxString getRawIntensityRatioGender ()
AffxString getCNCallGender ()
int getCNCallGenderAsInt ()
int getRawIntensityRatioGenderAsInt ()
Static Public Member Functions
static AffxArray< AffxString > * getQCMetricColumnNames ()
Detailed Description
A class for storing CNExperiment data.
Definition at line 38 of file CNExperiment.h.
Member Function Documentation
int CNExperiment::compareTo (CNExperiment & that, int iCompareCode)
Compare function.
Parameters:
that - A reference to an instance of this class.
iCompareCode - The code to switch on when doing compares. (Each code is a different compare.)
Returns:
- int value. (-1 if *this < that, 0 if *this == that, 1 if *this > that)
Definition at line 439 of file CNExperiment.cpp.
void CNExperiment::setCNCallGender (affx::Gender eGender)
Set the gender for the sample using the affx gender code.
Parameters:
affx::Gender - The affx gender code
Definition at line 454 of file CNExperiment.cpp.
Referenced by CNCytoEngine::calculateGenders(), CNAnalysisMethodCNGender::run(), and CNAnalysisMethodCNCyto2Gender::run().
void CNExperiment::setRawIntensityRatioGenderFromString (const AffxString & strIn)
Set the gender for the sample using a string 'male' or 'female'.
Parameters:
AffxString& - The gender string
Definition at line 479 of file CNExperiment.cpp.
References affx::Female, affx::Male, and affx::UnknownGender.
Referenced by CNLog2RatioData::loadGenotypeReport().
The documentation for this class was generated from the following files:
copynumber/CNExperiment.h
copynumber/CNExperiment.cpp