Affymetrix Power Tools: CNAnalysisMethodCNCyto2Gender Class Reference
CNAnalysisMethodCNCyto2Gender Class Reference
The CNGender analysis method.
#include <CNAnalysisMethodCNCyto2Gender.h>