Affymetrix Power Tools: CIniFile Class Reference
CIniFile Class Reference
#include <IniFile.h>
Classes
struct Record
struct RecordSectionKeyIs
Public Types
enum CommentChar { Pound = '#', SemiColon = ';' }
Public Member Functions
CIniFile (void)
virtual ~CIniFile (void)
std::vector< Record > GetRecord (std::string KeyName, std::string SectionName, std::string FileName)
std::vector< Record > GetSection (std::string SectionName, std::string FileName)
std::vector< std::string > GetSectionNames (std::string FileName)
std::string GetValue (std::string KeyName, std::string SectionName, std::string FileName)
std::vector< Record > GetAllRecords (std::string FileName)
Detailed Description
This class provides storages and parsing capabilities of INI files.
Definition at line 42 of file IniFile.h.
Member Enumeration Documentation
enum CIniFile::CommentChar
Enumerant for identifying characters used for comments
Definition at line 57 of file IniFile.h.
Constructor & Destructor Documentation
CIniFile::CIniFile (void)
Constructor
Definition at line 26 of file IniFile.cpp.
CIniFile::~CIniFile (void) [virtual]
Destructor
Definition at line 31 of file IniFile.cpp.
Member Function Documentation
std::vector< CIniFile::Record > CIniFile::GetAllRecords (std::string FileName)
Returns all key contents of the file.
Parameters:
FileName Name of file.
Returns:
Vector of all record structures that contain the contents of all keys in all sections of the file.
Definition at line 196 of file IniFile.cpp.
Referenced by affxsmd::SMDFileData::ReadData().
std::vector< CIniFile::Record > CIniFile::GetRecord (std::string KeyName, std::string SectionName, std::string FileName)
Returns the contents of a specific key within a given section
Parameters:
KeyName Key name of interest
SectionName Section name of interest
FileName Name of file
Returns:
Record structure that contains the contents of specific section and key
Definition at line 146 of file IniFile.cpp.
Referenced by GetValue().
std::vector< CIniFile::Record > CIniFile::GetSection (std::string SectionName, std::string FileName)
Returns all key contents of a specific section
Parameters:
SectionName Section name of interest
FileName Name of file
Returns:
Vector of record structures that contain the contents of all keys in a section
Definition at line 127 of file IniFile.cpp.
std::vector< std::string > CIniFile::GetSectionNames (std::string FileName)
Returns all sections names of a given file
Parameters:
FileName Name of file
Returns:
Vector of section names
Definition at line 109 of file IniFile.cpp.
std::string CIniFile::GetValue (std::string KeyName, std::string SectionName, std::string FileName)
Returns the value of a specific key within a given section
Parameters:
KeyName Key name of interest
SectionName Section name of interest
FileName Name of file
Returns:
String that contains the value associated with a specific key wihtin a given section
Definition at line 167 of file IniFile.cpp.
References GetRecord().
The documentation for this class was generated from the following files:
file/IniFile.h
file/IniFile.cpp