Affymetrix Power Tools: Options Class Reference
Options Class Reference
base class for tracking class options
#include <Options.h>