Affymetrix Power Tools: CNFamilialReporter Class Reference
CNFamilialReporter Class Reference
A base class for copy number quant methods.
#include <CNFamilialReporter.h>