Affymetrix Power Tools: CnProbeGenderCelListener Class Reference
CnProbeGenderCelListener Class Reference
Class for determining gender from a cel set of cel files.
#include <CnProbeGenderCelListener.h>