Affymetrix Power Tools: SummaryStats Class Reference
SummaryStats Class Reference
Public Member Functions
void addData (const std::vector< double > &dat)
Add a vector of data, keeping a running tab of the mean, and variance statistics.
void resize (int size)
double getStdev (int index)
double getMean (int index)
void reportIndex (std::ofstream &out, int index)
void report (std::ofstream &out, const std::string &name)
Detailed Description
Definition at line 41 of file SummaryStats.h.
Member Function Documentation
void SummaryStats::addData (const std::vector< double > & dat)
Add a vector of data, keeping a running tab of the mean, and variance statistics.
Algorithm from: Donald E. Knuth (1998). The Art of Computer Programming, volume 2: Seminumerical Algorithms, 3rd edn., p. 232. Boston: Addison-Wesley.
Parameters:
dat - New vector of data with one data point per chip.
Definition at line 43 of file SummaryStats.cpp.
References delta().
Referenced by QuantMethodGTypeExprChipSummary::addIntensityValues(), and QuantMethodGTypeChipSummary::report().
The documentation for this class was generated from the following files:
chipstream/SummaryStats.h
chipstream/SummaryStats.cpp