Affymetrix Power Tools: CRawQ Class Reference
CRawQ Class Reference
#include <RawQ.h>
Public Member Functions
CRawQ ()
~CRawQ ()
void SetDefaults ()
void SetVerticalZones (int v)
int GetVerticalZones () const
void SetHorizontalZones (int h)
int GetHorizontalZones () const
void SetPercentBG (float p)
float GetPercentBG () const
float ComputeRawQ (affymetrix_fusion_io::FusionCELData &cell, affymetrix_fusion_io::FusionCDFData &cdf)
Detailed Description
A class to compute the RawQ value of an expression array.
Definition at line 36 of file RawQ.h.
Constructor & Destructor Documentation
CRawQ::CRawQ ()
Constructor
Definition at line 47 of file RawQ.cpp.
References SetDefaults().
CRawQ::~CRawQ ()
Destructor
Definition at line 54 of file RawQ.cpp.
Member Function Documentation
float CRawQ::ComputeRawQ (affymetrix_fusion_io::FusionCELData & cell, affymetrix_fusion_io::FusionCDFData & cdf)
Computes the RawQ value. The CDF file must be of an expression array.
Parameters:
cell The CEL file intensities.
cdf The CDF file data.
Returns:
The RawQ value.
Definition at line 81 of file RawQ.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetCell(), affymetrix_fusion_io::FusionCDFFileHeader::GetCols(), affymetrix_fusion_io::FusionCDFProbeSetInformation::GetGroupInformation(), affymetrix_fusion_io::FusionCDFData::GetHeader(), affymetrix_fusion_io::FusionCELData::GetIntensity(), affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetNumCells(), affymetrix_fusion_io::FusionCDFProbeSetInformation::GetNumCells(), affymetrix_fusion_io::FusionCDFProbeSetInformation::GetNumGroups(), affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets(), affymetrix_fusion_io::FusionCELData::GetPixels(), affymetrix_fusion_io::FusionCDFData::GetProbeSetInformation(), affymetrix_fusion_io::FusionCDFData::GetProbeSetType(), affymetrix_fusion_io::FusionCDFFileHeader::GetRows(), affymetrix_fusion_io::FusionCELData::GetStdv(), affymetrix_fusion_io::FusionCDFProbeInformation::GetX(), affymetrix_fusion_io::FusionCDFProbeInformation::GetY(), and affymetrix_fusion_io::FusionCELData::XYToIndex().
Referenced by CRawQWorkflow::ComputeRawQ().
int CRawQ::GetHorizontalZones () const [inline]
Gets the number of horizontal zones for the background calculation.
Returns:
The number of horizontal zones for the background calculation.
Definition at line 77 of file RawQ.h.
Referenced by CRawQWorkflow::GetHorizontalZones().
float CRawQ::GetPercentBG () const [inline]
Gets the percentage of probes in a zone to use for the background calculation.
Returns:
The percentage of probes in a zone to use for the background calculation.
Definition at line 87 of file RawQ.h.
Referenced by CRawQWorkflow::GetPercentBG().
int CRawQ::GetVerticalZones () const [inline]
Gets the number of vertical zones for the background calculation.
Returns:
The number of vertical zones for the background calculation.
Definition at line 67 of file RawQ.h.
Referenced by CRawQWorkflow::GetVerticalZones().
void CRawQ::SetDefaults ()
Sets the default values.
Definition at line 60 of file RawQ.cpp.
Referenced by CRawQ(), and CRawQWorkflow::SetDefaults().
void CRawQ::SetHorizontalZones (int h) [inline]
Sets the number of horizontal zones for the background calculation.
Parameters:
h The number of horizontal zones for the background calculation.
Definition at line 72 of file RawQ.h.
Referenced by CRawQWorkflow::SetHorizontalZones().
void CRawQ::SetPercentBG (float p) [inline]
Sets the percentage of probes in a zone to use for the background calculation.
Parameters:
p The percentage of probes in a zone to use for the background calculation.
Definition at line 82 of file RawQ.h.
Referenced by CRawQWorkflow::SetPercentBG().
void CRawQ::SetVerticalZones (int v) [inline]
Sets the number of vertical zones for the background calculation.
Parameters:
v The number of vertical zones for the background calculation.
Definition at line 62 of file RawQ.h.
Referenced by CRawQWorkflow::SetVerticalZones().
The documentation for this class was generated from the following files:
rawq/src/RawQ.h
rawq/src/RawQ.cpp