Affymetrix Power Tools: CNAnalysisMethodLOHCyto2 Class Reference
CNAnalysisMethodLOHCyto2 Class Reference
The Cyto2LOH analysis method.
#include <CNAnalysisMethodLOHCyto2.h>