Affymetrix Power Tools: CNProbeSet Class Reference
CNProbeSet Class Reference
A class to store probe set data.
#include <CNProbeSet.h>
Classes
struct ComparePred
struct ComparePred< 0 >
struct ComparePred< 1 >
Public Member Functions
CNProbeSet (const CNProbeSet &that)
const CNProbeSet & operator= (const CNProbeSet &that)
void clear ()
void setProcess (bool b)
bool isProcess ()
std::string getProbeSetName () const
void setProbeSetName (const AffxString &str)
unsigned char getChromosome ()
void setChromosome (unsigned char c)
int getPosition ()
void setPosition (int i)
float getMedianSignal ()
void setMedianSignal (float f)
float getXXMedianSignal ()
void setXXMedianSignal (float f)
float getYMedianSignal ()
void setYMedianSignal (float f)
float getAAMedianSignal ()
void setAAMedianSignal (float f)
float getABMedianSignal ()
void setABMedianSignal (float f)
float getBBMedianSignal ()
void setBBMedianSignal (float f)
char getProcessFlag ()
void setProcessFlag (char c)
void setTrulySNP (bool bInput)
void setTrulyCN (bool bInput)
bool processAsCNNormalize ()
bool processAsSNPNormalize ()
bool processAsCN ()
bool processAsSNP ()
bool processAsVisualization ()
bool processAll ()
bool isSty ()
bool isNsp ()
char getStyAdapterCode ()
void setStyAdapterCode (char c)
char getNspAdapterCode ()
void setNspAdapterCode (char c)
float getGCContent ()
void setGCContent (float f)
float getAMedianIntensity ()
void setAMedianIntensity (float f)
float getBMedianIntensity ()
void setBMedianIntensity (float f)
float getAAlleleSignal ()
void setAAlleleSignal (float f)
float getBAlleleSignal ()
void setBAlleleSignal (float f)
float getLog2Ratio ()
void setLog2Ratio (float f)
float getLog2RatioMedianSmooth ()
void setLog2RatioMedianSmooth (float f)
float getAllelicDifference ()
void setAllelicDifference (float f)
float getGcAdjustment ()
void setGcAdjustment (float f)
bool isPseudoAutosomalRegion ()
void setPseudoAutosomalRegion (bool b)
int getGCBinIndex ()
void setGCBinIndex (int i)
char getGenotypeCall ()
void setGenotypeCall (char c)
float getGenotypeConfidence ()
void setGenotypeConfidence (float f)
int getImputedCNState ()
void setImputedCNState (int i)
int getCNState ()
void setCNState (int i)
float getCNConfidence ()
void setCNConfidence (float f)
float getSmoothedLog2Ratio ()
void setSmoothedLog2Ratio (float f)
float getLoh ()
void setLoh (float f)
float getSCAR ()
void setSCAR (float f)
float getFLD ()
void setFLD (float f)
int getMaxPeaks ()
void setMaxPeaks (int i)
bool isUseForSketch ()
void setUseForSketch (bool b)
snp_distribution * getSnpDistribution ()
void setSnpDistribution (snp_distribution *p)
float getMosaicismMixture ()
void setMosaicismMixture (float f)
int getReplicateCount ()
void setReplicateCount (int i)
unsigned int getAllelePeaks1 ()
void setAllelePeaks1 (unsigned int ui)
unsigned int getAllelePeaks2 ()
void setAllelePeaks2 (unsigned int ui)
std::vector< float > & getWaves ()
float getWaveValue (int iWaveIndex)
float getSignalEstimate ()
float getMuAA ()
void setMuAA (float f)
float getMuAB ()
void setMuAB (float f)
float getMuBB ()
void setMuBB (float f)
float getInformation ()
void setInformation (float input)
int getUseInEMAlgorithm ()
void setUseInEMAlgorithm (int input)
float getSignalContrast (double dK=2.0)
float getSignalContrastMvA ()
float getSignalStrength ()
float getSignalStrengthMvA ()
float getIntensityContrast (double dK=2.0)
float getIntensityStrength ()
float getCalibratedLog2Ratio (double dAlphaCNCalibrate, double dBetaCNCalibrate)
float getCalibratedSmoothedLog2Ratio (double dAlphaCNCalibrate, double dBetaCNCalibrate)
bool getValidSCARExists ()
void setValidSCARExists (bool b)
bool getValidFLDExists ()
void setValidFLDExists (bool b)
bool getValidHomHetExists ()
void setValidHomHetExists (bool b)
bool isUseForAllelePeaks ()
bool isUseForCyto2LOH ()
bool lohCalled ()
int compareTo (CNProbeSet &that, int iCompareCode)
Compare function.
char getCNNeutral (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNNeutral call (0 or 1).
char getCNGain (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNGain call (0 or 1).
char getCNLoss (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNLoss call (0 or 1).
char getCNNeutralLOH (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNNeutralLOH call (0 or 1).
char getNormalDiploid (int iSexCode, int iXChromosome, int iYChromosome)
Return the NormalDipload call (0 or 1).
char getSegmentTypeCall (int iSegmentType, int iSexCode, int iXChromosome, int iYChromosome)
Return the specified segment type call.
float getSegmentTypeConfidence (int iSegmentType)
Return the specified segment type confidence.
char getGenotypeCallCode ()
Return the affx genotype call code.
void setCovariateValue (int index, float value)
float getCovariateValue (int index)
int getNumCovariates ()
Detailed Description
A class to store probe set data.
Definition at line 43 of file CNProbeSet.h.
Member Function Documentation
int CNProbeSet::compareTo (CNProbeSet & that, int iCompareCode)
Compare function.
Parameters:
that - A reference to an instance of this class.
iCompareCode - The code to switch on when doing compares. (Each code is a different compare.)
Returns:
- int value. (-1 if *this < that, 0 if *this == that, 1 if *this > that)
Definition at line 201 of file CNProbeSet.cpp.
char CNProbeSet::getCNGain (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNGain call (0 or 1).
Parameters:
int - The sex code for this sample.
int - The numeric value associated with the X chromosome
int - The numeric value associated with the Y chromosome
Returns:
char - The call
Definition at line 243 of file CNProbeSet.cpp.
References affx::Male.
Referenced by getCNNeutral().
char CNProbeSet::getCNLoss (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNLoss call (0 or 1).
Parameters:
int - The sex code for this sample.
int - The numeric value associated with the X chromosome
int - The numeric value associated with the Y chromosome
Returns:
char - The call
Definition at line 282 of file CNProbeSet.cpp.
References affx::Male.
Referenced by getCNNeutral().
char CNProbeSet::getCNNeutral (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNNeutral call (0 or 1).
Parameters:
int - The sex code for this sample.
int - The numeric value associated with the X chromosome
int - The numeric value associated with the Y chromosome
Returns:
char - The call
Definition at line 230 of file CNProbeSet.cpp.
References getCNGain(), and getCNLoss().
char CNProbeSet::getCNNeutralLOH (int iSexCode, int iXChromosome, int iYChromosome)
Return the CNNeutralLOH call (0 or 1).
Parameters:
int - The sex code for this sample.
int - The numeric value associated with the X chromosome
int - The numeric value associated with the Y chromosome
Returns:
char - The call
Definition at line 320 of file CNProbeSet.cpp.
Referenced by getSegmentTypeCall().
char CNProbeSet::getGenotypeCallCode ()
Return the affx genotype call code.
Returns:
char - The call
Definition at line 397 of file CNProbeSet.cpp.
char CNProbeSet::getNormalDiploid (int iSexCode, int iXChromosome, int iYChromosome)
Return the NormalDipload call (0 or 1).
Parameters:
int - The sex code for this sample.
int - The numeric value associated with the X chromosome
int - The numeric value associated with the Y chromosome
Returns:
char - The call
Definition at line 334 of file CNProbeSet.cpp.
Referenced by getSegmentTypeCall().
char CNProbeSet::getSegmentTypeCall (int iSegmentType, int iSexCode, int iXChromosome, int iYChromosome)
Return the specified segment type call.
Parameters:
int - The segment type code
int - The sex code for this sample
int - The numeric value associated with the X chromosome
int - The numeric value associated with the Y chromosome
Returns:
char - The call
Definition at line 349 of file CNProbeSet.cpp.
References getCNNeutralLOH(), and getNormalDiploid().
Referenced by CNAnalysisMethodSegment::newSegments(), and CNAnalysisMethodLOHCyto2::newSegments().
float CNProbeSet::getSegmentTypeConfidence (int iSegmentType)
Return the specified segment type confidence.
Parameters:
int - The segment type code
Returns:
float - The comnfidence
Definition at line 377 of file CNProbeSet.cpp.
Referenced by CNAnalysisMethodSegment::newSegments().
The documentation for this class was generated from the following files:
copynumber/CNProbeSet.h
copynumber/CNProbeSet.cpp