Affymetrix Power Tools: RMA Class Reference
RMA Class Reference
Holds methods for computing the popular Robust Muliarray Average of Microarrays (RMA).
#include <RMA.h>
Public Member Functions
void medianPolishPSet (const std::vector< int > &indexes, std::vector< float > &results)
Use median polish to get a summary of probe set concentrations using probes that are at the row positions in PM specified by indexes.
Static Public Member Functions
static void medianPolishPsetFromMatrix (std::vector< std::vector< float > > &pmMatrix, int numRow, int numCol, std::vector< float > &colEstimates, std::vector< float > &rowEstimates, bool doLog=true)
Static version of medianPolishSet for when it isn't convenient to have an RMA instance.
static void medianPolish (std::vector< std::vector< float > > &pmMatrix, int numRow, int numCol, std::vector< float > &colEstimates, std::vector< float > &rowEstimates)
Static version of medianPolishSet for when it isn't convenient to have an RMA instance.
static void medianPolishWithPrecomputedEffectsOnePass (std::vector< std::vector< float > > &pmMatrix, int numChips, int numProbes, std::vector< float > &colEstimates, std::vector< float > &rowEstimates, bool doLog=true)
Static version of medianPolishWithPrecomputedEffectsOnePass This version will use precomputed feature effects as input values and perform the usual median polish algorithm until convergence.
static void medianPolishWithPrecomputedEffectsUsedAsSeedValues (std::vector< std::vector< float > > &pmMatrix, int numChips, int numProbes, std::vector< float > &colEstimates, std::vector< float > &rowEstimates, bool doLog=true)
Static version of medianPolishWithPrecomputedEffectsUsedAsSeedValues This version will use precomputed feature effects as input values and perform the usual median polish algorithm until convergence.
static double vectorMin (std::vector< float > &dat)
Find the minimum value in a vector.
static double vectorMax (std::vector< float > &dat)
Find the maximum value in a vector.
static double vectorMean (std::vector< float > &dat)
Compute the mean of a given vector.
static double vectorVariance (std::vector< float > &dat)
Compute the variance of a given column.
static double vectorQuantile (std::vector< float > &dat, double quantile)
Return the value at a particular quantile, Example quantile would be .5 which is equivalent to the median.
static double vectorIqr (std::vector< float > &dat)
Return the range of values from .75 quantile to .25 quantile.
static double findBandWidth (std::vector< float > &dat)
Implementation of the bw.nrd0() function in R to decide kernel bandwidth.
static void colMassDist (std::vector< float > &dat, double bandWidth, double from, double to, std::vector< float > &yVec, int numBins)
Spread the mass around our histogram bins.
static void columnToVector (double **PM, int numRows, int colIx, std::vector< float > &toFill)
Fill in a vector from a given column of data.
static double linearInterpolate (double d, std::vector< float > &x, std::vector< float > &y)
Find the interpolation for value d between x and y.
static void linearApprox (std::vector< float > &x, std::vector< float > &y, std::vector< float > &xOut, std::vector< float > &yOut)
Linearly interpolate x and y using values in x out.
static double modeOfData (std::vector< float > &dat, int numBins)
Here we are recreating the density() function in R with an Epanechnikov kernel.
static void printArray (float *dat, int size, float thresh=0)
static void printArray (double *dat, int size, double thresh=0)
static double arrayMax (double *d, int count)
static void printVector (std::vector< float > &dat)
static void fft (std::vector< float > &dat, bool inverse)
Do a fast fourier transform on data.
static void convolveDataKernel (std::vector< float > &yVec, std::vector< float > &kernelWords, int count)
Convolves the real numbers in two vectors.
static void estimateBgParam (std::vector< float > &data, double *mu, double *sigma, double *alpha, int numBins=16384)
Calculate the parameters necesary to do the RMA background subtraction.
static float bgSubData (float value, double mu, double sigma, double alpha, bool &error)
The "true" signal is then estimated as:
static void backgroundCorrect (std::vector< float > &data, int numBins=16384)
RMA background correct subtraction.
static void getRowEffect (std::vector< std::vector< float > > &psMatrix, int numRow, int numCol, std::vector< float > &rowEffect)
Find the median for the rows.
static void subRowEffect (std::vector< std::vector< float > > &psMatrix, int numRow, int numCol, std::vector< float > &rowEffect)
Subtract the median off of each row.
static void getColEffect (std::vector< std::vector< float > > &psMatrix, int numRow, int numCol, std::vector< float > &colEffect)
Find the median for the columns.
static void subColEffect (std::vector< std::vector< float > > &psMatrix, int numRow, int numCol, std::vector< float > &colEffect)
Subtract the median off of each column.
static double matrixSum (std::vector< std::vector< float > > &psMatrix, int numRow, int numCol)
Return the sum of a matrix.
static double phi (double x)
Standard normal probability density function.
static double PHI (double x)
The cdf function for standard normal distribution consistant with Bolstad's RMA notatation.
static double pnorm (double z)
Cumulative standard normal density function.
static void getRanks (struct _rmaPair *pairs, int count, std::vector< int > &ranks)
Get the ranks of _rmaPair structures using the same algorthim as R to break ties.
static void quantileNorm (std::vector< std::vector< float > > &data)
Quantile Norm data using same algorithm to break ties as RMA This function is deprecated as normalization sdk module now supports bioconductor style quantile normalization.
Detailed Description
Holds methods for computing the popular Robust Muliarray Average of Microarrays (RMA).
Implements the method described in "Exploration, normalization, and summaries of high density oligonucleotide array probe level data", Irizarry RA, Hobbs B, Collin F, Beazer-Barclay YD, Antonellis KJ, Scherf U, Speed TP., Biostatistics. 2003 Apr;4(2):249-64. Core routines are two static functions for manipulating matrices. This class is mainly a collection of static methods to manipulate vectors and matrices to perform an RMA analysis. RMA really consists of three separate steps:
1) Background estimation which occurs at the chip level as implemented by backgroundCorrect(). The background subtraction is more complicated than a simple subtraction and accounts for a substantial amount of the code.
2) Quantile normalization. As the original normalization module of the affy sdk used a different manner of resolving ties than the bioconductor version there are methods to normalize a matrix of chip data implemented in quantileNorm(). The normalization module has since been extended to reproduce the bioconductor results and the code here will be deprecated soon.
3) Probeset summary. Use the median polish algorithm to estimate the target response and feature response using medianPolishPsetFromMatrix(). Target response is used as the signal level estimates. While this is where the real "work" of doing probeset level estimates occurs, it takes up very little code as the median polish algorithm is simple to implement.
Definition at line 68 of file RMA.h.
Member Function Documentation
void RMA::backgroundCorrect (std::vector< float > & data, int numBins = 16384) [static]
RMA background correct subtraction.
The RMA bacground subtraction is a little complicated. The details are available in Ben Bolstad's thesis dissertation: http://stat-www.berkeley.edu/users/bolstad/Dissertation/Bolstad_2004_Dissertation.pdf The basic idea is that the signal is exponential and the background is additive gaussian. There are a lot of fun integrals to show that the joint distribution can be found to estimate the true signal given the observed signal on the chip and the parameters mu and sigma for the background and alpha for the exponential. Estimating mu, sigma and alpha explicitly is difficult though so RMA uses an ad-hoc method where mu is estimated as the mode of the data, sigma is estimated by the variation in the lower 50% quantile tail and alpha is estimated as an exponential fit to the upper 50% quantile tail. The "true" signal is then estimated as:
X = a + b(phi(a/b)/PHI(a/b)) where a = signal - mu - (sigma^2 * alpha) b = sigma
phi and PHI are standard normal density function and distribution function respectively given as:
phi(z) = 1 / sqrt(2*pi) * exp(-.5*z^2) PHI(z) = -inf^z 1 / sqrt(2*pi) exp(-.5w^2) dw
Note that this all happens on a per chip basis.
Parameters:
data - vector of data for a chip.
numBins - number of bins to use for estimating mode of data for background parameters. Must be a power of 2.
Definition at line 1065 of file RMA.cpp.
References bgSubData(), Err::errAbort(), and estimateBgParam().
static float RMA::bgSubData (float value, double mu, double sigma, double alpha, bool & error) [inline, static]
The "true" signal is then estimated as:
X = a + b(phi(a/b)/PHI(a/b)) where a = signal - mu - (sigma^2 * alpha) b = sigma
phi and PHI are standard normal density function and distribution function respectively given as:
phi(z) = 1 / sqrt(2*pi) * exp(-.5*z^2) PHI(z) = -inf^z 1 / sqrt(2*pi) exp(-.5w^2) dw
Parameters:
value original value.
mu - mode of "background" signal.
sigma - stdev of "background" signal
alpha - mean of exponential "true" signal
Returns:
bg adjusted value.
Definition at line 341 of file RMA.h.
References phi(), and pnorm().
Referenced by backgroundCorrect(), and RmaBgTran::transform().
void RMA::colMassDist (std::vector< float > & dat, double bandWidth, double from, double to, std::vector< float > & yVec, int numBins) [static]
Spread the mass around our histogram bins.
Parameters:
dat - data of interest.
bandWidth - Bandwidth of mass distribution.
from - begininning of dist.
to - end of values.
yVec - vector of bins to spread mass into.
numBins - number of bins in yVec.
dat - data of interest.
bandWidth - Bandwidth of mass distribution.
yVec - vector of bins to spread mass into.
numBins - number of bins in yVec.
Definition at line 608 of file RMA.cpp.
References vectorMax(), and vectorMin().
Referenced by modeOfData().
void RMA::columnToVector (double ** PM, int numRows, int colIx, std::vector< float > & toFill) [static]
Fill in a vector from a given column of data.
Parameters:
PM - Matrix to fill in from.
numRows - Number of rows in matrix, will be vector length.
colIx - Column number to create vector from.
toFill - Vector to fill in with column data.
Definition at line 805 of file RMA.cpp.
void RMA::convolveDataKernel (std::vector< float > & yVec, std::vector< float > & kernelWords, int count) [static]
Convolves the real numbers in two vectors.
Fill in kerelwords with the convolved data.
Parameters:
yVec - binned up data.
kernelWords - kernel function.
count - Number of entries in yVec and kernelWords.
Fill in kerelwords with the convolved data. Note that yVec and kernel words must be a size which is a power of two (i.e. 256, 512, 1024, etc.)
Parameters:
yVec - binned up data.
kernelWords - kernel function.
count - Number of entries in yVec and kernelWords.
Todo:
This check looks ok, but on some hardware very small deviations make the floor and ceil fail /// assert(floor(log((double)yVec.size()) / log(2.0)) == ceil(log((double)yVec.size()) / log(2.0)));
Definition at line 658 of file RMA.cpp.
References fft().
Referenced by modeOfData().
void RMA::estimateBgParam (std::vector< float > & data, double * mu, double * sigma, double * alpha, int numBins = 16384) [static]
Calculate the parameters necesary to do the RMA background subtraction.
Parameters:
data - all of the data for a given cel file.
mu - pointer to parameter mu to be filled in by function.
sigma - pointer to parameter sigma to be filled in by function.
alpha - pointer to paramter alpha to be filled in.
numBins - number of bins to use in denstiy. RMA traditionally uses 16,384. It is essential that this number be a power of two.
Definition at line 909 of file RMA.cpp.
References modeOfData(), and Util::round().
Referenced by backgroundCorrect(), and RmaBgTran::initializeData().
void RMA::fft (std::vector< float > & dat, bool doInverse) [static]
Do a fast fourier transform on data.
Do a fast fourier transform on data using the Danielson-Lanczos algorithm.
Values in data vector will be overwritten with the results. The format of data must be that of real and imaginary numbers interleaved together. So if the real portion of the number is at index 0, the imaginary portion will be at index 1. The next real number is at index 2 and imaginary portion is at index 3, etc. The input data vector must be a power of two (i.e. 32, 64, 128, etc) if your data is not a power of two in length you must pad it with zeros. Be warned that this bit of code is not terribly user friendly and can be tough to work with.
Parameters:
dat - data of interest.
inverse - should we perform the inverse fourier transform?
Values in data vector will be overwritten with the results. The format of data must be that of real and imaginary numbers interleaved together. So if the real portion of the number is at index 0, the imaginary portion will be at index 1. The next real number is at index 2 and imaginary portion is at index 3, etc. The input data vector must be a power of two (i.e. 32, 64, 128, etc) if your data is not a power of two in length you must pad it with zeros. Be warned that this bit of code is not terribly user friendly and can be tough to work with.
Parameters:
data - data of interest with interleaving real and imaginary portions.
doInverse - should we perform the inverse fourier transform?
Todo:
This check looks ok, but on some hardware very small deviations make the floor and ceil fail
Definition at line 1095 of file RMA.cpp.
Referenced by convolveDataKernel().
double RMA::findBandWidth (std::vector< float > & dat) [static]
Implementation of the bw.nrd0() function in R to decide kernel bandwidth.
Parameters:
dat - vector of data of interest.
Returns:
- Bandwidth of kernel to use.
Definition at line 577 of file RMA.cpp.
References Verbose::out(), vectorIqr(), and vectorVariance().
Referenced by modeOfData().
void RMA::getColEffect (std::vector< std::vector< float > > & psMatrix, int numRow, int numCol, std::vector< float > & colEffect) [static]
Find the median for the columns.
Parameters:
psMatrix - matrix.
numRow - number of rows in matrix.
numCol - number of columns in matrix.
colEffect - fill in column effect.
Definition at line 140 of file RMA.cpp.
Referenced by medianPolishPsetFromMatrix(), and medianPolishWithPrecomputedEffectsUsedAsSeedValues().
void RMA::getRanks (struct _rmaPair * pairs, int count, std::vector< int > & ranks) [static]
Get the ranks of _rmaPair structures using the same algorthim as R to break ties.
Parameters:
pairs - array of _rmaPair strucutres.
count - size of array.
ranks - vector of ranks.
Definition at line 1194 of file RMA.cpp.
References _rmaPair::data.
Referenced by quantileNorm().
void RMA::getRowEffect (std::vector< std::vector< float > > & psMatrix, int numRow, int numCol, std::vector< float > & rowEffect) [static]
Find the median for the rows.
Parameters:
psMatrix - matrix.
numRow - number of rows in matrix.
numCol - number of rows in matrix.
rowEffect - fill in row effect.
psMatrix - matrix.
numRow - number of rows in matrix.
numCol - number of rows in matrix.
colEffect - fill in row effect.
Definition at line 89 of file RMA.cpp.
Referenced by medianPolishPsetFromMatrix(), medianPolishWithPrecomputedEffectsOnePass(), and medianPolishWithPrecomputedEffectsUsedAsSeedValues().
void RMA::linearApprox (std::vector< float > & x, std::vector< float > & y, std::vector< float > & xOut, std::vector< float > & yOut) [static]
Linearly interpolate x and y using values in x out.
Parameters:
x - vector 1 for interpolation from.
y - vector 2 for interpolation to.
xOut - vector with data to interpolate.
yOut - output vector for interpolated data.
Definition at line 748 of file RMA.cpp.
References linearInterpolate().
Referenced by modeOfData().
double RMA::linearInterpolate (double d, std::vector< float > & x, std::vector< float > & y) [static]
Find the interpolation for value d between x and y.
Assumes that x and y are sorted.
Parameters:
d - value to interpolate.
x - vector 1
y - vector 2
Returns:
interpolation of d from x into y.
Definition at line 704 of file RMA.cpp.
Referenced by linearApprox().
double RMA::matrixSum (std::vector< std::vector< float > > & psMatrix, int numRow, int numCol) [static]
Return the sum of a matrix.
Parameters:
psMatrix - matrix.
numRow - number of rows in matrix.
numCol - number of columns in matrix.
Returns:
sum of matrix.
Definition at line 169 of file RMA.cpp.
Referenced by medianPolishPsetFromMatrix(), and medianPolishWithPrecomputedEffectsUsedAsSeedValues().
static void RMA::medianPolish (std::vector< std::vector< float > > & pmMatrix, int numRow, int numCol, std::vector< float > & colEstimates, std::vector< float > & rowEstimates) [inline, static]
Static version of medianPolishSet for when it isn't convenient to have an RMA instance.
Parameters:
pmMatrix - Matrix of perfect match probe intensities. Values will be modified in place, residuals will be filled in here.
numRow - Number of rows in the matrix.
numCol - Number of columns in the matrix.
indexes - Indexes of the probes for probe set of interest into PM matrix.
results - Vector in which probe sets summaries, one per GeneChip, will be returned as log2 values.
Definition at line 110 of file RMA.h.
References medianPolishPsetFromMatrix().
void RMA::medianPolishPSet (const std::vector< int > & indexes, std::vector< float > & results)
Use median polish to get a summary of probe set concentrations using probes that are at the row positions in PM specified by indexes.
results will be a vector with one summary value for each GeneChip for the probe set requested.
Parameters:
indexes - Rows that are probes in the probe set of interest.
results - Vector in which probe sets summaries, one per GeneChip, will be returned as log2 values.
void RMA::medianPolishPsetFromMatrix (std::vector< std::vector< float > > & pmMatrix, int numRow, int numCol, std::vector< float > & colEstimates, std::vector< float > & rowEstimates, bool doLog = true) [static]
Static version of medianPolishSet for when it isn't convenient to have an RMA instance.
Note that both the the colEstimates and rowEstimates by convention have the global median added back to them. The identifiability function used by RMA is median(log(f)) = 0 for both feature and target effects. By convention the global median is added back onto target estimates to avoid negative expression summaries. The same is done for feature effects although subtracting off the median for a probeset will give the median(log(f)) = 0 adjusted feature effects.
Parameters:
pmMatrix - Matrix of perfect match probe intensities. Values will be modified in place, residuals will be filled in here.
numRow - Number of rows in the matrix.
numCol - Number of columns in the matrix.
colEstimates - Feature effects.
rowEstimates - Target effects.
PM - Matrix of perfect match probe intensities. Values will be modified in place, residuals will be filled in here.
numRow - Number of rows in the matrix.
numCol - Number of columns in the matrix.
indexes - Indexes of the probes for probe set of interest into PM matrix.
results - Vector in which probe sets summaries, one per GeneChip, will be returned.
Definition at line 195 of file RMA.cpp.
References delta(), Err::errAbort(), getColEffect(), getRowEffect(), matrixSum(), subColEffect(), and subRowEffect().
Referenced by QuantRma::computeEstimate(), and medianPolish().
void RMA::medianPolishWithPrecomputedEffectsOnePass (std::vector< std::vector< float > > & pmMatrix, int numChips, int numProbes, std::vector< float > & colEstimates, std::vector< float > & rowEstimates, bool doLog = true) [static]
Static version of medianPolishWithPrecomputedEffectsOnePass This version will use precomputed feature effects as input values and perform the usual median polish algorithm until convergence.
Static version of medianPolishWithPrecomputedEffects.
Parameters:
pmMatrix - Matrix of perfect match probe intensities. Values will be modified in place, residuals will be filled in here.
numRow - Number of rows in the matrix.
numCol - Number of columns in the matrix.
colEstimates - This is the precomputed vector of probe (feature) effects.
rowEstimates - This is the output vector of chip effects.
doLog - This is a boolean switch to turn on or off the computation of logs of the input matrix.
This version does the last steps of the usual median-polish algorithm but does not iterate until convergence. If the feature effects that are used have been generated from the same data on which the analysis is done, the chip effect values will not change.
Parameters:
pmMatrix - Matrix of perfect match probe intensities. Values will be modified in place, residuals will be filled in here.
numRow - Number of rows in the matrix.
numCol - Number of columns in the matrix.
colEstimates - This is the precomputed vector of probe (feature) effects.
rowEstimates - This is the output vector of chip effects.
doLog - This is a boolean switch to turn on or off the computation of logs of the input matrix.
Definition at line 422 of file RMA.cpp.
References delta(), Err::errAbort(), getRowEffect(), and subColEffect().
Referenced by QuantRma::computeEstimate().
void RMA::medianPolishWithPrecomputedEffectsUsedAsSeedValues (std::vector< std::vector< float > > & pmMatrix, int numRow, int numCol, std::vector< float > & colEstimates, std::vector< float > & rowEstimates, bool doLog = true) [static]
Static version of medianPolishWithPrecomputedEffectsUsedAsSeedValues This version will use precomputed feature effects as input values and perform the usual median polish algorithm until convergence.
Static version of medianPolish.
Parameters:
pmMatrix - Matrix of perfect match probe intensities. Values will be modified in place, residuals will be filled in here.
numRow - Number of rows in the matrix.
numCol - Number of columns in the matrix.
colEstimates - This is the precomputed vector of probe (feature) effects.
rowEstimates - This is the output vector of chip effects.
doLog - This is a boolean switch to turn on or off the computation of logs of the input matrix.
In this version precomputed values are used as seed values to the usual median-polish algorithm. It is allowed to run until the usual convergence criterion are met.
Parameters:
PM - Matrix of perfect match probe intensities. Values will be modified in place, residuals will be filled in here.
numRow - Number of rows in the matrix.
numCol - Number of columns in the matrix.
indexes - Indexes of the probes for probe set of interest into PM matrix.
results - Vector in which probe sets summaries, one per GeneChip, will be returned.
Definition at line 318 of file RMA.cpp.
References delta(), Err::errAbort(), getColEffect(), getRowEffect(), matrixSum(), subColEffect(), and subRowEffect().
Referenced by QuantRma::computeEstimate().
double RMA::modeOfData (std::vector< float > & dat, int numBins) [static]
Here we are recreating the density() function in R with an Epanechnikov kernel.
There are three steps 1) Compute a Epanechikov kernel. 2) Convolve the mass distribution with a fast fourier transform. 3) Linearly interpolate the results.
Parameters:
dat - data of interest.
numBins - number of bins to spread data over (16384 for original RMA method).
Returns:
- Mode of the data.
Definition at line 827 of file RMA.cpp.
References colMassDist(), convolveDataKernel(), findBandWidth(), linearApprox(), vectorMax(), and vectorMin().
Referenced by estimateBgParam().
double RMA::phi (double x) [static]
Standard normal probability density function.
Parameters:
x - value of interest.
Returns:
- density at value supplied. Specifically: 1/sqrt(2*pi)*exp(-0.5*x^2)
Parameters:
x - value of interest.
Returns:
- density at value supplied
Definition at line 968 of file RMA.cpp.
Referenced by bgSubData().
double RMA::PHI (double x) [static]
The cdf function for standard normal distribution consistant with Bolstad's RMA notatation.
The cdf function for standard normal distribution.
Also see pnorm.
Parameters:
x - value.
Returns:
- probability that standard normal value has probability <= x.
Parameters:
x - value.
Returns:
- probability that standard normal value has probability <= x.
Definition at line 959 of file RMA.cpp.
References pnorm().
double RMA::pnorm (double u) [static]
Cumulative standard normal density function.
Cumulative normal density function.
Parameters:
z - value for which to calculate the distribution function.
Returns:
- probability that value is < z.
Parameters:
u - value for which to calculate the distribution function.
Returns:
- probability that value is < u.
Definition at line 978 of file RMA.cpp.
Referenced by bgSubData(), and PHI().
void RMA::quantileNorm (std::vector< std::vector< float > > & data) [static]
Quantile Norm data using same algorithm to break ties as RMA This function is deprecated as normalization sdk module now supports bioconductor style quantile normalization.
Parameters:
data - matrix of data.
Definition at line 1219 of file RMA.cpp.
References _rmaPair::data, Err::errAbort(), getRanks(), and _rmaPair::rank.
void RMA::subColEffect (std::vector< std::vector< float > > & psMatrix, int numRow, int numCol, std::vector< float > & colEffect) [static]
Subtract the median off of each column.
Subtract the median off of each row.
Parameters:
psMatrix - matrix.
numRow - number of rows.
numCol - number of columns.
colEffect - values to subtract from each column.
psMatrix - matrix.
numRow - number of rows.
numCol - number of columns.
rowEffect - values to subtract from each row.
Definition at line 118 of file RMA.cpp.
Referenced by medianPolishPsetFromMatrix(), medianPolishWithPrecomputedEffectsOnePass(), and medianPolishWithPrecomputedEffectsUsedAsSeedValues().
void RMA::subRowEffect (std::vector< std::vector< float > > & psMatrix, int numRow, int numCol, std::vector< float > & rowEffect) [static]
Subtract the median off of each row.
Parameters:
psMatrix - matrix.
numRow - number of rows.
numCol - number of columns.
rowEffect - values to subtract from each row.
Definition at line 68 of file RMA.cpp.
Referenced by medianPolishPsetFromMatrix(), and medianPolishWithPrecomputedEffectsUsedAsSeedValues().
double RMA::vectorIqr (std::vector< float > & dat) [static]
Return the range of values from .75 quantile to .25 quantile.
Parameters:
dat - Data of interest.
Returns:
- difference between .75 and .25 quantiles.
Definition at line 528 of file RMA.cpp.
References vectorQuantile().
Referenced by findBandWidth().
double RMA::vectorMax (std::vector< float > & dat) [static]
Find the maximum value in a vector.
Parameters:
dat - vector of data.
Returns:
maximum value.
Definition at line 559 of file RMA.cpp.
Referenced by colMassDist(), and modeOfData().
double RMA::vectorMean (std::vector< float > & dat) [static]
Compute the mean of a given vector.
sum(column)/n
Parameters:
dat - vector of doubles to take average of.
Returns:
- mean value of vector
Definition at line 461 of file RMA.cpp.
Referenced by vectorVariance().
double RMA::vectorMin (std::vector< float > & dat) [static]
Find the minimum value in a vector.
Parameters:
dat - vector of data.
Returns:
minimum value.
Definition at line 541 of file RMA.cpp.
Referenced by colMassDist(), and modeOfData().
double RMA::vectorQuantile (std::vector< float > & dat, double quantile) [static]
Return the value at a particular quantile, Example quantile would be .5 which is equivalent to the median.
Parameters:
dat - Data of interest.
quantile - Quantile of interest to report between [0,1];
Returns:
value at quantile.
Definition at line 499 of file RMA.cpp.
Referenced by vectorIqr().
double RMA::vectorVariance (std::vector< float > & dat) [static]
Compute the variance of a given column.
(sum(average - actual))^2 / n-1
Parameters:
dat - vector of doubles to take variance of.
Returns:
- variance of vectorn
Definition at line 477 of file RMA.cpp.
References vectorMean().
Referenced by findBandWidth().
The documentation for this class was generated from the following files:
rma/RMA.h
rma/RMA.cpp