Affymetrix Power Tools: SelfCreate Class Reference
SelfCreate Class Reference
Small interface for functions that know how to make an instance of themselves given a map of key, value parameters.
#include <SelfCreate.h>