Affymetrix Power Tools: AnalysisStreamExpPcaSel Class Reference
AnalysisStreamExpPcaSel Class Reference
An analysis stream that takes the expression data and does a pca selection on the probes before passing them to the quantification method.
#include <AnalysisStreamExpPcaSel.h>