Affymetrix Power Tools: AnalysisStream Class Reference
AnalysisStream Class Reference
Utility class for centralizing analysis pathway.
#include <AnalysisStream.h>