Affymetrix Power Tools: CNCytoEngine Class Reference
CNCytoEngine Class Reference
The engine for controlling the copynumber Cytos.
#include <CNCytoEngine.h>