Affymetrix Power Tools: affymetrix_comparer::CHPCompareGCOStoCalvin Class Reference
affymetrix_comparer::CHPCompareGCOStoCalvin Class Reference
#include <CHPCompareGCOStoCalvin.h>
Public Member Functions
void Clear ()
bool CompareFiles (const char *gcosFile, const char *calvinFile)
std::string Differences () const
Detailed Description
Provides for information about CHP file versions.
Definition at line 38 of file CHPCompareGCOStoCalvin.h.
Member Function Documentation
void CHPCompareGCOStoCalvin::Clear ()
Clears the members.
Definition at line 39 of file CHPCompareGCOStoCalvin.cpp.
References affymetrix_calvin_io::CHPData::Clear(), and affxchp::CCHPFileData::Clear().
Referenced by CompareFiles().
bool CHPCompareGCOStoCalvin::CompareFiles (const char * gcosFile, const char * calvinFile)
Determines the version number of the file.
Parameters:
gcosFile The file name of the gcos CHP file.
calvinFile The file name of the calvin CHP file.
Returns:
True if identical.
Definition at line 75 of file CHPCompareGCOStoCalvin.cpp.
References Clear().
std::string affymetrix_comparer::CHPCompareGCOStoCalvin::Differences () const [inline]
The differences between the files.
Returns:
A string representation of the differences.
Definition at line 105 of file CHPCompareGCOStoCalvin.h.
Referenced by affymetrix_comparer::CHPComparer::CompareFiles().
The documentation for this class was generated from the following files:
calvin_files/converters/chp/comparer/CHPCompareGCOStoCalvin.h
calvin_files/converters/chp/comparer/CHPCompareGCOStoCalvin.cpp