Affymetrix Power Tools: tsvJoin Class Reference
tsvJoin Class Reference
Public Member Functions
tsvJoin (int argc, const char *argv[], const std::string &version)
Constructor.
~tsvJoin ()
Destructor.
void run ()
Read, process data, write output.
Detailed Description
Definition at line 41 of file TsvJoin.h.
Constructor & Destructor Documentation
tsvJoin::tsvJoin (int argc, const char * argv[], const std::string & version)
Constructor.
Parameters:
argc Number of command line arguments.
argv Command line arguments.
version Version string.
argc Number of command line arguments.
argv Command line arguments.
version Version string.
Errors: throw exception to display help messages, if too few input files.
Definition at line 68 of file TsvJoin.cpp.
References Err::errAbort(), PgOptions::get(), PgOptions::getArg(), PgOptions::getArgCount(), PgOptions::getBool(), Fs::mustOpenToWrite(), PgOptions::parseArgv(), Err::setThrowStatus(), and PgOptions::usage().
Member Function Documentation
void tsvJoin::run (void)
Read, process data, write output.
Errors: abort if unable to read any input file.
Definition at line 141 of file TsvJoin.cpp.
The documentation for this class was generated from the following files:
file/TsvFile/TsvJoin.h
file/TsvFile/TsvJoin.cpp