Affymetrix Power Tools: CumulativeStats< T, LargeNumber > Class Template Reference
CumulativeStats< T, LargeNumber > Class Template Reference
Public Member Functions
CumulativeStats ()
Constructor.
CumulativeStats (const std::string &name)
Constructor.
void addData (T dat)
Add a vector of data, keeping a running tab of the mean, and variance statistics.
void setUpFullMethod ()
LargeNumber getStdev ()
LargeNumber getMean ()
T getMax ()
T getMin ()
void setFull ()
uint64_t getCount ()
std::string getName ()
LargeNumber getMedian ()
LargeNumber getIQR ()
Detailed Description
template<class T, class LargeNumber = double>
class CumulativeStats< T, LargeNumber >
Definition at line 38 of file CumulativeStats.h.
Constructor & Destructor Documentation
template<class T, class LargeNumber = double> CumulativeStats< T, LargeNumber >::CumulativeStats () [inline]
Constructor.
Definition at line 43 of file CumulativeStats.h.
template<class T, class LargeNumber = double> CumulativeStats< T, LargeNumber >::CumulativeStats (const std::string & name) [inline]
Constructor.
Definition at line 50 of file CumulativeStats.h.
Member Function Documentation
template<class T, class LargeNumber = double> void CumulativeStats< T, LargeNumber >::addData (T dat) [inline]
Add a vector of data, keeping a running tab of the mean, and variance statistics.
Algorithm from: Donald E. Knuth (1998). The Art of Computer Programming, volume 2: Seminumerical Algorithms, 3rd edn., p. 232. Boston: Addison-Wesley.
Parameters:
dat - New vector of data with one data point per chip.
Definition at line 66 of file CumulativeStats.h.
Referenced by MultiChannelNonOverlapCelListener::calcLogDiff(), MultiChannelNonOverlapCelListener::calcMedianDiff(), MultiChannelNonOverlapCelListener::calcNonOverlap(), VariabilityScoreCelListener::calcStats(), and ChipLayout::trackGlobalStats().
The documentation for this class was generated from the following file:
chipstream/CumulativeStats.h