Affymetrix Power Tools: ProbeSetGroup Class Reference
ProbeSetGroup Class Reference
Group of probe sets that should be processed as a single large probe set.
#include <ProbeSet.h>
Public Member Functions
ProbeSetGroup (ProbeSet *ps)
Constructor for making singleton probe set group.
ProbeSetGroup ()
Constructor assures that name is NULL initially.
~ProbeSetGroup ()
Destructor.
bool pointersLoaded () const
int probesetCount () const
int countPmProbes ()
How many perfect match probes are there for a particular probeset group?
Public Attributes
bool ownMem
Should we try to free memory in destructor?
char * name
Name of probe set group.
const char * displayName
std::vector< ProbeSet * > probeSets
Vector of probe set pointers.
std::vector< char * > probeSetNames
Vector of probe set names.
Detailed Description
Group of probe sets that should be processed as a single large probe set.
Definition at line 613 of file ProbeSet.h.
Constructor & Destructor Documentation
ProbeSetGroup::ProbeSetGroup (ProbeSet * ps) [inline]
Constructor for making singleton probe set group.
Parameters:
ps - Probe set to make singleton from.
Definition at line 621 of file ProbeSet.h.
References Util::cloneString(), name, ProbeSet::name, ownMem, and probeSets.
Member Function Documentation
int ProbeSetGroup::countPmProbes () [inline]
How many perfect match probes are there for a particular probeset group?
Returns:
- number of perfect match probes for this group and chip.
Definition at line 668 of file ProbeSet.h.
References ProbeSet::atoms, Verbose::out(), Atom::probes, probeSets, ToStr(), and Probe::type.
Referenced by AnalysisStreamExpSpectSel::fillInSelectProbes(), QuantRma::setUp(), QuantPlierBase::setUp(), QuantMedian::setUp(), QuantDabg::setUp(), and QuantAvgDiff::setUp().
The documentation for this class was generated from the following file:
chipstream/ProbeSet.h