Affymetrix Power Tools: RegressionCheck Class Reference
RegressionCheck Class Reference
Abstract base class (i.e.
#include <RegressionCheck.h>