Affymetrix Power Tools: CallElement Class Reference
CallElement Class Reference
Public Member Functions
CallElement ()
CallElement::CallElement() Synopsis:
CallElement (const std::string &probeSet, const std::string &base, const unsigned int copyNumber=2, const bool hasRevComp=false)
CallElement::CallElement() Synopsis: GenotypeTableModel (CHP) version of the CallElement constructor.
bool addBase (const std::string &base)
CallElement::addBase Synopsis:
std::string basesToString (bool reverseComplement=false) const
CallElement::basesToString Synopsis:
void describeVerbose (const RunTimeEnvironment &rte, ADT_VERBOSE_ENUM override=ADT_VERBOSE_NULL) const
CallElement::describeVerbose Synopsis:
void describeVerbose (ADT_VERBOSE_ENUM level) const
int getCompleteSetSize () const
bool isValidBase (const std::string &)
CallElement::isValidBase Synopsis:
bool isValidProbeSet (const std::string &)
CallElement::isValidProbeSet Synopsis:
int setCompleteSetSize ()
CallElement::setCompleteSetSize Synopsis:
bool hasWildCards () const
bool operator== (CallElement const &) const
CallElement::operator== Synopsis:
bool operator!= (CallElement const &b) const
Static Public Member Functions
static bool isWildCardBase (std::string base)
CallElement::isWildCardBase Synopsis:
static std::string reverseComplement (const std::string seq)
CallElement::reverseComplement.
Public Attributes
std::vector< std::string > m_bases
unsigned int m_chromatid
unsigned int m_copyNumber
bool m_hasReverseComplement
std::string m_probeSet
std::vector< std::string > m_rbases
Detailed Description
Definition at line 41 of file CallElement.h.
Constructor & Destructor Documentation
CallElement::CallElement ()
CallElement::CallElement() Synopsis:
Empty constructor for STL storage containers or for translation file call elements.
NOTE: base is used interchangabley to mean allele. In DMET 2 alleles where always represented as just one base.
Definition at line 52 of file CallElement.cpp.
CallElement::CallElement (const std::string & probeSet, const std::string & base, const unsigned int copyNumber = 2, const bool hasRevComp = false)
CallElement::CallElement() Synopsis: GenotypeTableModel (CHP) version of the CallElement constructor.
This is not obvious but when a CallElement is created for the GenotypeTableModel, it will always have exactly one base. Multiple bases only apply to mult-allelic defintions in the Translation table.
NOTE: base is used interchangabley to mean allele. In DMET two alleles where always represented as just one base.
Parameters:
probeSet - aka "marker", ie.e AM_14633, etc.
base - aka "alleles", A, or ATATGGA. For multiallelic markers intialize with one base and then append markers using CallElement::addBase().
copyNumber - 2 by default. 0 and 1 are the only other legal values.
hasRevComp - reverse complement, if the "Switch" field in translation file or annotation file is "Y/1" then the reverse compliment of the base will be used durring translation. See "CallElement::reverseComplement".
Definition at line 88 of file CallElement.cpp.
References addBase(), APT_ERR_ABORT, APT_ERR_ASSERT, isValidBase(), isValidProbeSet(), and isWildCardBase().
Member Function Documentation
bool CallElement::addBase (const std::string & base)
CallElement::addBase Synopsis:
Append a base (allele) to the std::vector of bases (alleles). Insure the added base is not a duplicate as well that the base is valid. Also adds the passed in base to its reverse complement list if the element the 'hasReverseComplement' attribute is true;
Parameters:
base - the base to add.
Returns:
true - if base was added successfully.
Definition at line 125 of file CallElement.cpp.
References isValidBase(), and reverseComplement().
Referenced by CallSet::addCallElement(), and CallElement().
std::string CallElement::basesToString (bool reverseComplement = false) const
CallElement::basesToString Synopsis:
Return a list of the bases (alleles) for this CallElement as a comma separated list. For most bi-allelic markers in the translation table the list size will be one.
Parameters:
reverseComplement - return the list of reverse complements and not the original bases (alleles).
Returns:
basesString - i.e. "A,T,G".
Definition at line 165 of file CallElement.cpp.
void CallElement::describeVerbose (const RunTimeEnvironment & rte, ADT_VERBOSE_ENUM override = ADT_VERBOSE_NULL) const
CallElement::describeVerbose Synopsis:
Run time debug routine that can be invoked with various verbose levels. ADT_VERBOSE_INPUT_FILES is the default level.
Parameters:
rte - run time environment
override - ADT_VERBOSE_INPUT_FILES by default, otherwise the ADT_VERBOSE_ENUM level to output
Definition at line 242 of file CallElement.cpp.
bool CallElement::isValidBase (const std::string & testBase)
CallElement::isValidBase Synopsis:
Regular expression test to examine if a base (allele) is valid. Wildcard designations such as "PossibleRareAllele" and "NoCall" are handled correctly and will return true.
Parameters:
testBase - the base (allele) std::string to validate.
Returns:
- true if valid
Definition at line 322 of file CallElement.cpp.
References isWildCardBase().
Referenced by addBase(), and CallElement().
bool CallElement::isValidProbeSet (const std::string & testProbeSet)
CallElement::isValidProbeSet Synopsis:
Regular expression test to examine if a probe set (marker) std::string is valid.
Parameters:
testProbeSet - the std::string to validate
Returns:
true - if valid
Definition at line 296 of file CallElement.cpp.
Referenced by CallElement().
bool CallElement::isWildCardBase (std::string base) [static]
CallElement::isWildCardBase Synopsis:
Regular exxpression test to examine if a base (allele) is a wild card.
Wildcard list: 1.) NoCall (NC) 2.) PossibleRareAllele (PRA) 3.) NotAvailable
Parameters:
base - the base (allele) to test.
Returns:
true - if the base (allele) is a wild card.
Definition at line 352 of file CallElement.cpp.
Referenced by CallSet::addCallElement(), CallElement(), CallSet::CallSet(), GenotypeOverrideTableModel::GenotypeOverrideTableModel(), isValidBase(), operator==(), and reverseComplement().
bool CallElement::operator== (CallElement const & ce1) const
CallElement::operator== Synopsis:
The purpose of the CallElement class is to provide this one operator.
This operator treats the probe set (marker) id and a corresponding list of bases (alleles) as an atomic unit.
Comparing call elements as equivalent means the atomic consituents must also be equivalent according to a set of rules.
Business rules treat no call and possible rare allele as wildcards that match any base. It also compares multi-allelic CallElements and if they share a common base then they are equal. Note that for CallElements derived from the Genotype Short Report data they can never be multi-allelic. This means that the only multi-allelic CallElement being compared will be the Translation Table file CallElement with the GenotypeTableModel (CHP) CallElement.
Parameters:
ce1 - the CallElement to compare
Returns:
true - if equal.
Definition at line 392 of file CallElement.cpp.
References isWildCardBase().
std::string CallElement::reverseComplement (const std::string seq) [static]
CallElement::reverseComplement.
Synopsis:
Switch to the other strand by taking the reverse complement.
Parameters:
seq - the base (allele) sequence to take the complement of.
Returns:
rev - the reverse complement
Definition at line 432 of file CallElement.cpp.
References isWildCardBase().
Referenced by addBase(), and TranslationTableModel::setReportAlleles().
int CallElement::setCompleteSetSize ()
CallElement::setCompleteSetSize Synopsis:
A CallElement typically represents one marker, but in one special case the complete call element set represents all alleles (bases) possible for a marker. This API is used in that one special case to get the complete set size. The complete set size is used in the translation algorithm.
Complete set size, n: 1 The count of all allels (bases) minus any copy number bases.
return size - the count
Definition at line 212 of file CallElement.cpp.
The documentation for this class was generated from the following files:
translation/CallElement.h
translation/CallElement.cpp