Affymetrix Power Tools: affymetrix_calvin_io::FileInput Class Reference
affymetrix_calvin_io::FileInput Class Reference
Static Public Member Functions
static int8_t ReadInt8 (std::ifstream &instr)
static int16_t ReadInt16 (std::ifstream &instr)
static int32_t ReadInt32 (std::ifstream &instr)
static u_int8_t ReadUInt8 (std::ifstream &instr)
static u_int16_t ReadUInt16 (std::ifstream &instr)
static u_int32_t ReadUInt32 (std::ifstream &instr)
static float ReadFloat (std::ifstream &instr)
static int8_t ReadInt8 (char *&instr)
static int16_t ReadInt16 (char *&instr)
static int32_t ReadInt32 (char *&instr)
static u_int8_t ReadUInt8 (char *&instr)
static u_int16_t ReadUInt16 (char *&instr)
static u_int32_t ReadUInt32 (char *&instr)
static float ReadFloat (char *&instr)
static std::wstring ReadString16 (std::ifstream &instr, int32_t len)
static std::wstring ReadString16 (std::ifstream &instr)
static std::string ReadString8 (std::ifstream &instr, int32_t len)
static std::string ReadString8 (std::ifstream &instr)
static std::wstring ReadString16 (char *&instr, int32_t len)
static std::wstring ReadString16 (char *&instr)
static std::string ReadString8 (char *&instr, int32_t len)
static std::string ReadString8 (char *&instr)
static int32_t ReadBlob (std::ifstream &instr, const void *&value)
Detailed Description
Definition at line 37 of file FileInput.h.
Member Function Documentation
int32_t FileInput::ReadBlob (std::ifstream & instr, const void *& value) [static]
Reads a blob from a file (as is; no htonl). It is the responsibility of the caller to convert elements of the blob to system types.
Parameters:
instr The input file stream.
value A returned pointer to the blob. The caller must delete[] the returned pointer.
Returns:
The size of the blob read from the file.
Definition at line 184 of file FileInput.cpp.
References ReadInt32().
Referenced by affymetrix_calvin_io::GenericDataHeaderReader::Read(), and affymetrix_calvin_io::DataSetHeaderReader::ReadParameters().
float FileInput::ReadFloat (std::ifstream & instr) [static]
Reads a 32 bit floating point number from a big endian file.
Parameters:
instr The input file stream.
Returns:
The floating point number read from the file.
Definition at line 124 of file FileInput.cpp.
References ReadInt32().
Referenced by affymetrix_calvin_io::DataSetReader::Read().
float FileInput::ReadFloat (char *& instr) [static]
Reads a 32 bit floating point number from a big endian file stream (memory map pointer).
Parameters:
instr The input file stream.
Returns:
The floating point number read from the file stream.
Definition at line 216 of file FileInput.cpp.
References ReadInt32().
int16_t FileInput::ReadInt16 (char *& instr) [static]
Reads a 16 bit integer from a big endian file stream (memory map pointer).
Parameters:
instr The input file stream.
Returns:
The integer read from the file stream.
Definition at line 229 of file FileInput.cpp.
int16_t FileInput::ReadInt16 (std::ifstream & instr) [static]
Reads a 16 bit integer from a big endian file.
Parameters:
instr The input file stream.
Returns:
The integer read from the file.
Definition at line 69 of file FileInput.cpp.
Referenced by affymetrix_calvin_io::DataSetReader::Read().
int32_t FileInput::ReadInt32 (char *& instr) [static]
Reads a 32 bit integer from a big endian file stream (memory map pointer).
Parameters:
instr The input file stream.
Returns:
The integer read from the file stream.
Definition at line 240 of file FileInput.cpp.
int32_t FileInput::ReadInt32 (std::ifstream & instr) [static]
Reads a 32 bit integer from a big endian file.
Parameters:
instr The input file stream.
Returns:
The integer read from the file.
Definition at line 80 of file FileInput.cpp.
Referenced by affymetrix_calvin_io::DataSetReader::Read(), ReadBlob(), affymetrix_calvin_io::DataSetHeaderReader::ReadColumns(), ReadFloat(), affymetrix_calvin_io::DataSetHeaderReader::ReadRowCount(), ReadString16(), and ReadString8().
int8_t FileInput::ReadInt8 (std::ifstream & instr) [static]
Reads an 8 bit integer from a big endian file.
Parameters:
instr The input file stream.
Returns:
The integer read from the file.
Definition at line 59 of file FileInput.cpp.
Referenced by affymetrix_calvin_io::DataSetReader::Read(), affymetrix_calvin_io::DataSetHeaderReader::ReadColumns(), affymetrix_calvin_io::FileHeaderReader::ReadMagicNumber(), and affymetrix_calvin_io::FileHeaderReader::ReadVersion().
int8_t FileInput::ReadInt8 (char *& instr) [static]
Reads an 8 bit integer from a big endian file stream (memory map pointer).
Parameters:
instr The input file stream.
Returns:
The integer read from the file stream.
Definition at line 196 of file FileInput.cpp.
std::wstring FileInput::ReadString16 (std::ifstream & instr) [static]
Reads a 16 bit unicode string from a big endian file.
Parameters:
instr The input file stream.
Returns:
The string read from the file stream.
Definition at line 156 of file FileInput.cpp.
References ReadInt32(), and ReadString16().
std::wstring FileInput::ReadString16 (char *& instr, int32_t len) [static]
Reads a 16 bit unicode string of fixed size from a big endian file stream (memory map pointer).
Parameters:
instr The input file stream.
len The length of the string.
Returns:
The string read from the file stream.
Definition at line 273 of file FileInput.cpp.
std::wstring FileInput::ReadString16 (char *& instr) [static]
Reads a 16 bit unicode string from a big endian file stream (memory map pointer).
Parameters:
instr The input file stream.
Returns:
The string read from the file stream.
Definition at line 394 of file FileInput.cpp.
References ReadInt32(), and ReadString16().
std::wstring FileInput::ReadString16 (std::ifstream & instr, int32_t len) [static]
Reads a 16 bit unicode string of fixed size from a big endian file.
Parameters:
instr The input file stream.
len The length of the string.
Returns:
The string read from the file stream.
Definition at line 165 of file FileInput.cpp.
Referenced by affymetrix_calvin_io::GenericDataHeaderReader::Read(), affymetrix_calvin_io::DataSetReader::Read(), affymetrix_calvin_io::DataSetHeaderReader::ReadColumns(), affymetrix_calvin_io::DataGroupHeaderReader::ReadDataGroupName(), affymetrix_calvin_io::DataSetHeaderReader::ReadName(), affymetrix_calvin_io::DataSetHeaderReader::ReadParameters(), and ReadString16().
std::string FileInput::ReadString8 (char *& instr) [static]
Reads an 8 bit string from a big endian file stream (memory map pointer).
Parameters:
instr The input file stream.
Returns:
The string read from the file stream.
Definition at line 371 of file FileInput.cpp.
References ReadInt32(), and ReadString8().
std::string FileInput::ReadString8 (std::ifstream & instr, int32_t len) [static]
Reads an 8 bit string of fixed size from a big endian file.
Parameters:
instr The input file stream.
len The length of the string.
Returns:
The string read from the file stream.
Definition at line 143 of file FileInput.cpp.
Referenced by affymetrix_calvin_io::GenericDataHeaderReader::Read(), affymetrix_calvin_io::DataSetReader::Read(), and ReadString8().
std::string FileInput::ReadString8 (char *& instr, int32_t len) [static]
Reads an 8 bit string of fixed size from a big endian file stream (memory map pointer).
Parameters:
instr The input file stream.
len The length of the string.
Returns:
The string read from the file stream.
Definition at line 380 of file FileInput.cpp.
std::string FileInput::ReadString8 (std::ifstream & instr) [static]
Reads an 8 bit string from a big endian file.
Parameters:
instr The input file stream.
Returns:
The string read from the file stream.
Definition at line 134 of file FileInput.cpp.
References ReadInt32(), and ReadString8().
u_int16_t FileInput::ReadUInt16 (std::ifstream & instr) [static]
Reads a 16 bit unsigned integer from a big endian file.
Parameters:
instr The input file stream.
Returns:
The integer read from the file.
Definition at line 102 of file FileInput.cpp.
Referenced by affymetrix_calvin_io::DataSetReader::Read().
u_int16_t FileInput::ReadUInt16 (char *& instr) [static]
Reads a 16 bit unsigned integer from a big endian file stream (memory map pointer).
Parameters:
instr The input file stream.
Returns:
The integer read from the file stream.
Definition at line 251 of file FileInput.cpp.
u_int32_t FileInput::ReadUInt32 (std::ifstream & instr) [static]
Reads a 32 bit unsigned integer from a big endian file.
Parameters:
instr The input file stream.
Returns:
The integer read from the file.
Definition at line 113 of file FileInput.cpp.
Referenced by affymetrix_calvin_io::GenericDataHeaderReader::Read(), affymetrix_calvin_io::DataSetReader::Read(), affymetrix_calvin_io::DataSetHeaderReader::ReadColumns(), affymetrix_calvin_io::DataSetHeaderReader::ReadDataFilePos(), affymetrix_calvin_io::FileHeaderReader::ReadDataGroupCnt(), affymetrix_calvin_io::DataGroupHeaderReader::ReadDataSetCnt(), affymetrix_calvin_io::FileHeaderReader::ReadFirstDataGroupFilePos(), affymetrix_calvin_io::DataGroupHeaderReader::ReadFirstDataSetFilePos(), affymetrix_calvin_io::DataGroupHeaderReader::ReadNextDataGroupFilePos(), affymetrix_calvin_io::DataSetHeaderReader::ReadNextDataSetFilePos(), and affymetrix_calvin_io::DataSetHeaderReader::ReadParameters().
u_int32_t FileInput::ReadUInt32 (char *& instr) [static]
Reads a 32 bit unsigned integer from a big endian file stream (memory map pointer).
Parameters:
instr The input file stream.
Returns:
The integer read from the file stream.
Definition at line 262 of file FileInput.cpp.
u_int8_t FileInput::ReadUInt8 (std::ifstream & instr) [static]
Reads an 8 bit unsigned integer from a big endian file.
Parameters:
instr The input file stream.
Returns:
The integer read from the file.
Definition at line 92 of file FileInput.cpp.
Referenced by affymetrix_calvin_io::DataSet::AssignValue(), affymetrix_calvin_io::DataSet::GetData(), and affymetrix_calvin_io::DataSetReader::Read().
u_int8_t FileInput::ReadUInt8 (char *& instr) [static]
Reads an 8 bit unsigned integer from a big endian file stream (memory map pointer).
Parameters:
instr The input file stream.
Returns:
The integer read from the file stream.
Definition at line 206 of file FileInput.cpp.
The documentation for this class was generated from the following files:
calvin_files/parsers/src/FileInput.h
calvin_files/parsers/src/FileInput.cpp