Affymetrix Power Tools: affxchp::CResequencingResults Class Reference
affxchp::CResequencingResults Class Reference
#include <CHPFileData.h>
Public Member Functions
CResequencingResults ()
~CResequencingResults ()
void Clear ()
const std::vector< char > & GetCalledBases ()
char GetCalledBase (int index)
int GetCalledBasesSize () const
void ResizeCalledBases (int size)
void SetCalledBase (int index, char call)
const std::vector< float > & GetScores ()
float GetScore (int index)
int GetScoresSize () const
void ResizeScores (int size)
void SetScore (int index, float score)
const std::vector
< ForceCallType > & GetForceCalls ()
ForceCallType GetForceCall (int index)
int GetForceCallsSize () const
void ResizeForceCalls (int size)
void SetForceCall (int index, ForceCallType call)
const std::vector< BaseCallType > & GetOrigCalls ()
BaseCallType GetOrigCall (int index)
int GetOrigCallsSize () const
void ResizeOrigCalls (int size)
void SetOrigCall (int index, BaseCallType call)
Protected Attributes
std::vector< char > calledBases
std::vector< float > scores
std::vector< ForceCallType > forceCalls
std::vector< BaseCallType > origCalls
Detailed Description
Resequencing results.
Definition at line 560 of file CHPFileData.h.
Constructor & Destructor Documentation
affxchp::CResequencingResults::CResequencingResults () [inline]
Constructor
Definition at line 579 of file CHPFileData.h.
affxchp::CResequencingResults::~CResequencingResults () [inline]
Destructor
Definition at line 582 of file CHPFileData.h.
References Clear().
Member Function Documentation
void affxchp::CResequencingResults::Clear (void) [inline]
Clears the members.
Definition at line 585 of file CHPFileData.h.
References calledBases, forceCalls, origCalls, and scores.
Referenced by affxchp::CCHPFileData::Open(), and ~CResequencingResults().
char affxchp::CResequencingResults::GetCalledBase (int index) [inline]
Gets the called base at the given index.
Parameters:
index The index to the called bases array.
Returns:
The called base.
Definition at line 596 of file CHPFileData.h.
References calledBases.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults(), and affxchpwriter::CCHPFileWriter::Save().
const std::vector<char>& affxchp::CResequencingResults::GetCalledBases () [inline]
Gets the called bases.
Returns:
The array of called bases.
Definition at line 590 of file CHPFileData.h.
References calledBases.
int affxchp::CResequencingResults::GetCalledBasesSize () const [inline]
Gets the size of the called bases array.
Returns:
The size of the called bases array.
Definition at line 601 of file CHPFileData.h.
References calledBases.
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults(), and affxchpwriter::CCHPFileWriter::Save().
ForceCallType affxchp::CResequencingResults::GetForceCall (int index) [inline]
Gets the force call at the given index.
Parameters:
index The index to the force calls array.
Returns:
The force call.
Definition at line 650 of file CHPFileData.h.
References forceCalls.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults(), and affxchpwriter::CCHPFileWriter::Save().
const std::vector<ForceCallType>& affxchp::CResequencingResults::GetForceCalls () [inline]
Gets the force calls.
Returns:
The array of force calls.
Definition at line 644 of file CHPFileData.h.
References forceCalls.
int affxchp::CResequencingResults::GetForceCallsSize () const [inline]
Gets the size of the force calls array.
Returns:
The size of the force calls array.
Definition at line 655 of file CHPFileData.h.
References forceCalls.
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults(), and affxchpwriter::CCHPFileWriter::Save().
BaseCallType affxchp::CResequencingResults::GetOrigCall (int index) [inline]
Gets the original called base at the given index.
Parameters:
index The index to the original calls array.
Returns:
The original call.
Definition at line 677 of file CHPFileData.h.
References origCalls.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults(), and affxchpwriter::CCHPFileWriter::Save().
const std::vector<BaseCallType>& affxchp::CResequencingResults::GetOrigCalls () [inline]
Gets the original called bases.
Returns:
The array of original calls.
Definition at line 671 of file CHPFileData.h.
References origCalls.
int affxchp::CResequencingResults::GetOrigCallsSize () const [inline]
Gets the size of the original calls array.
Returns:
The size of the original calls array.
Definition at line 682 of file CHPFileData.h.
References origCalls.
Referenced by affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertMas5File(), affymetrix_chp_converter::CHPFileConvertToCalvin::ConvertXDAFile(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults(), and affxchpwriter::CCHPFileWriter::Save().
float affxchp::CResequencingResults::GetScore (int index) [inline]
Gets the score at the given index.
Parameters:
index The index to the scores array.
Returns:
The score.
Definition at line 623 of file CHPFileData.h.
References scores.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults(), and affxchpwriter::CCHPFileWriter::Save().
const std::vector<float>& affxchp::CResequencingResults::GetScores () [inline]
Gets the scores.
Returns:
The array of scores.
Definition at line 617 of file CHPFileData.h.
References scores.
int affxchp::CResequencingResults::GetScoresSize () const [inline]
Gets the size of the scores array.
Returns:
The size of the scores array.
Definition at line 628 of file CHPFileData.h.
References scores.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults().
void affxchp::CResequencingResults::ResizeCalledBases (int size) [inline]
Resizes the called bases array.
Parameters:
size The size of the array.
Definition at line 606 of file CHPFileData.h.
References calledBases.
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affxchp::CCHPFileData::Open().
void affxchp::CResequencingResults::ResizeForceCalls (int size) [inline]
Resizes the force calls array.
Parameters:
size The size of the array.
Definition at line 660 of file CHPFileData.h.
References forceCalls.
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affxchp::CCHPFileData::Open().
void affxchp::CResequencingResults::ResizeOrigCalls (int size) [inline]
Resizes the original calls array.
Parameters:
size The size of the array.
Definition at line 687 of file CHPFileData.h.
References origCalls.
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affxchp::CCHPFileData::Open().
void affxchp::CResequencingResults::ResizeScores (int size) [inline]
Resizes the scores array.
Parameters:
size The size of the array.
Definition at line 633 of file CHPFileData.h.
References scores.
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affxchp::CCHPFileData::Open().
void affxchp::CResequencingResults::SetCalledBase (int index, char call) [inline]
Sets the called base.
Parameters:
index The index to the array.
call The call.
Definition at line 612 of file CHPFileData.h.
References calledBases.
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affxchp::CCHPFileData::Open().
void affxchp::CResequencingResults::SetForceCall (int index, ForceCallType call) [inline]
Sets the force call.
Parameters:
index The index to the array.
call The force call.
Definition at line 666 of file CHPFileData.h.
References forceCalls.
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affxchp::CCHPFileData::Open().
void affxchp::CResequencingResults::SetOrigCall (int index, BaseCallType call) [inline]
Sets the original call.
Parameters:
index The index to the array.
call The original call.
Definition at line 693 of file CHPFileData.h.
References origCalls.
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affxchp::CCHPFileData::Open().
void affxchp::CResequencingResults::SetScore (int index, float score) [inline]
Sets the score.
Parameters:
index The index to the array.
score The score.
Definition at line 639 of file CHPFileData.h.
References scores.
Referenced by affymetrix_chp_converter::CHPConversionUtilities::Copy(), and affxchp::CCHPFileData::Open().
Member Data Documentation
std::vector<char> affxchp::CResequencingResults::calledBases [protected]
The called bases.
Definition at line 564 of file CHPFileData.h.
Referenced by Clear(), GetCalledBase(), GetCalledBases(), GetCalledBasesSize(), ResizeCalledBases(), and SetCalledBase().
std::vector<ForceCallType> affxchp::CResequencingResults::forceCalls [protected]
An array of force calls - base calls the algorithm would have made if the thresholds were removed.
Definition at line 570 of file CHPFileData.h.
Referenced by Clear(), GetForceCall(), GetForceCalls(), GetForceCallsSize(), ResizeForceCalls(), and SetForceCall().
std::vector<BaseCallType> affxchp::CResequencingResults::origCalls [protected]
An array of original calls. The calledBases contained the results of the algorithm and user edits. If a user edits a base the original algorithm called base is stored in this vector.
Definition at line 575 of file CHPFileData.h.
Referenced by Clear(), GetOrigCall(), GetOrigCalls(), GetOrigCallsSize(), ResizeOrigCalls(), and SetOrigCall().
std::vector<float> affxchp::CResequencingResults::scores [protected]
Base call scores.
Definition at line 567 of file CHPFileData.h.
Referenced by Clear(), GetScore(), GetScores(), GetScoresSize(), ResizeScores(), and SetScore().
The documentation for this class was generated from the following file:
file/CHPFileData.h