Affymetrix Power Tools: affymetrix_calvin_io::CDFProbeInformation Class Reference
affymetrix_calvin_io::CDFProbeInformation Class Reference
#include <CDFProbeInformation.h>
Public Member Functions
CDFProbeInformation ()
u_int32_t GetListIndex () const
int GetExpos () const
u_int16_t GetX () const
u_int16_t GetY () const
int8_t GetPBase () const
int8_t GetTBase () const
u_int16_t GetProbeLength () const
u_int16_t GetProbeGrouping () const
Protected Types
enum DataSetColumns {
XCoordCol, YCoordCol, ListIndexCol, IndexPosCol,
BaseProbeCol, BaseTargetCol, ProbeLenCol, ProbeGroupCol
}
Protected Member Functions
void CopyFromDataSet (DataSet *ds, int32_t row)
Protected Attributes
u_int16_t xCoord
u_int16_t yCoord
u_int32_t listIndex
u_int32_t indexPos
int8_t baseProbe
int8_t baseTarget
u_int16_t probeLength
u_int16_t probeGrouping
Friends
class CDFProbeGroupInformation
Detailed Description
Class that exposes the CDF probe information
Definition at line 38 of file CDFProbeInformation.h.
Constructor & Destructor Documentation
CDFProbeInformation::CDFProbeInformation ()
Constructor
Definition at line 29 of file CDFProbeInformation.cpp.
References baseProbe, baseTarget, indexPos, listIndex, probeGrouping, probeLength, xCoord, and yCoord.
Member Function Documentation
void CDFProbeInformation::CopyFromDataSet (DataSet * ds, int32_t row) [protected]
Definition at line 42 of file CDFProbeInformation.cpp.
References baseProbe, baseTarget, affymetrix_calvin_io::DataSet::GetData(), indexPos, listIndex, xCoord, and yCoord.
Referenced by affymetrix_calvin_io::CDFProbeGroupInformation::GetCell().
int affymetrix_calvin_io::CDFProbeInformation::GetExpos () const [inline]
Get the exon position of the probe (for reseq)
Definition at line 47 of file CDFProbeInformation.h.
References indexPos.
Referenced by affymetrix_fusion_io::FusionCDFProbeInformation::GetExpos().
u_int32_t affymetrix_calvin_io::CDFProbeInformation::GetListIndex () const [inline]
Get the list index (atom number) of the probe
Definition at line 45 of file CDFProbeInformation.h.
References listIndex.
Referenced by affymetrix_fusion_io::FusionCDFProbeInformation::GetListIndex(), affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetStart(), and affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetStop().
int8_t affymetrix_calvin_io::CDFProbeInformation::GetPBase () const [inline]
Get the base of the probe at the substitution position
Definition at line 53 of file CDFProbeInformation.h.
References baseProbe.
Referenced by affymetrix_fusion_io::FusionCDFProbeInformation::GetPBase().
u_int16_t affymetrix_calvin_io::CDFProbeInformation::GetProbeGrouping () const [inline]
Get the probe grouping
Definition at line 59 of file CDFProbeInformation.h.
References probeGrouping.
Referenced by affymetrix_fusion_io::FusionCDFProbeInformation::GetProbeGrouping().
u_int16_t affymetrix_calvin_io::CDFProbeInformation::GetProbeLength () const [inline]
Get the probe length
Definition at line 57 of file CDFProbeInformation.h.
References probeLength.
Referenced by affymetrix_fusion_io::FusionCDFProbeInformation::GetProbeLength().
int8_t affymetrix_calvin_io::CDFProbeInformation::GetTBase () const [inline]
Get the base of the target at the interrogation position
Definition at line 55 of file CDFProbeInformation.h.
References baseTarget.
Referenced by affymetrix_fusion_io::FusionCDFProbeInformation::GetTBase().
u_int16_t affymetrix_calvin_io::CDFProbeInformation::GetX () const [inline]
Get the x-coordinate of the probe
Definition at line 49 of file CDFProbeInformation.h.
References xCoord.
Referenced by affymetrix_fusion_io::FusionCDFProbeInformation::GetX().
u_int16_t affymetrix_calvin_io::CDFProbeInformation::GetY () const [inline]
Get the y-coordinate of the probe
Definition at line 51 of file CDFProbeInformation.h.
References yCoord.
Referenced by affymetrix_fusion_io::FusionCDFProbeInformation::GetY().
Member Data Documentation
int8_t affymetrix_calvin_io::CDFProbeInformation::baseProbe [protected]
Base of the probe at the substitution position, m_PBase in C++
Definition at line 77 of file CDFProbeInformation.h.
Referenced by CDFProbeInformation(), CopyFromDataSet(), and GetPBase().
int8_t affymetrix_calvin_io::CDFProbeInformation::baseTarget [protected]
Base of the probe at the interrogation position, m_TBase in C++
Definition at line 79 of file CDFProbeInformation.h.
Referenced by CDFProbeInformation(), CopyFromDataSet(), and GetTBase().
u_int32_t affymetrix_calvin_io::CDFProbeInformation::indexPos [protected]
exon position for reseq, m_Expos in C++
Definition at line 75 of file CDFProbeInformation.h.
Referenced by CDFProbeInformation(), CopyFromDataSet(), and GetExpos().
u_int32_t affymetrix_calvin_io::CDFProbeInformation::listIndex [protected]
list index (atom number), m_ListIndex in C++
Definition at line 73 of file CDFProbeInformation.h.
Referenced by CDFProbeInformation(), CopyFromDataSet(), and GetListIndex().
u_int16_t affymetrix_calvin_io::CDFProbeInformation::probeGrouping [protected]
Probe grouping, m_ProbeGrouping in C++
Definition at line 83 of file CDFProbeInformation.h.
Referenced by CDFProbeInformation(), and GetProbeGrouping().
u_int16_t affymetrix_calvin_io::CDFProbeInformation::probeLength [protected]
Probe length, m_ProbeLength in C++
Definition at line 81 of file CDFProbeInformation.h.
Referenced by CDFProbeInformation(), and GetProbeLength().
u_int16_t affymetrix_calvin_io::CDFProbeInformation::xCoord [protected]
x-coordinate of the probe, m_X in C++
Definition at line 69 of file CDFProbeInformation.h.
Referenced by CDFProbeInformation(), CopyFromDataSet(), and GetX().
u_int16_t affymetrix_calvin_io::CDFProbeInformation::yCoord [protected]
y-coordinate of the probe, m_Y in C++
Definition at line 71 of file CDFProbeInformation.h.
Referenced by CDFProbeInformation(), CopyFromDataSet(), and GetY().
The documentation for this class was generated from the following files:
calvin_files/data/src/CDFProbeInformation.h
calvin_files/data/src/CDFProbeInformation.cpp