Affymetrix Power Tools: ChipSummary Class Reference
ChipSummary Class Reference
Class for objects that provide chip summary metrics.
#include <ChipSummary.h>