Affymetrix Power Tools: affymetrix_cel_converter::CELFileConvertToXDA Class Reference
affymetrix_cel_converter::CELFileConvertToXDA Class Reference
#include <CELFileConvertToXDA.h>
Public Member Functions
CELFileConvertToXDA ()
~CELFileConvertToXDA ()
void SetExtraParameters (const affymetrix_calvin_parameter::ParameterNameValueTypeVector *params)
CELFileConverterErrorCode ErrorCode () const
bool ConvertCalvinFile (const char *fileName, const char *newFile, CELFileConversionOptions *options=NULL)
bool ConvertASCIIFile (const char *fileName, const char *newFile, CELFileConversionOptions *options=NULL)
Detailed Description
This class will convert a CEL file to XDA format.
Definition at line 35 of file CELFileConvertToXDA.h.
Constructor & Destructor Documentation
CELFileConvertToXDA::CELFileConvertToXDA ()
Constructor
Definition at line 43 of file CELFileConvertToXDA.cpp.
CELFileConvertToXDA::~CELFileConvertToXDA ()
Destructor
Definition at line 60 of file CELFileConvertToXDA.cpp.
Member Function Documentation
bool CELFileConvertToXDA::ConvertASCIIFile (const char * fileName, const char * newFile, CELFileConversionOptions * options = NULL)
Convert the ASCII file to XDA format.
Parameters:
fileName The full path name of the CEL file.
newFile The name of the new CEL file.
Returns:
True if successful.
Definition at line 68 of file CELFileConvertToXDA.cpp.
References affymetrix_cel_converter::CELConversionUtilities::Copy(), affxcel::CCELFileData::Read(), affxcel::CCELFileData::SetFileFormat(), affxcel::CCELFileData::SetFileName(), and affxcel::CCELFileWriter::WriteXDABCel().
Referenced by affymetrix_cel_converter::CELFileConverter::ConvertFile().
bool CELFileConvertToXDA::ConvertCalvinFile (const char * fileName, const char * newFile, CELFileConversionOptions * options = NULL)
Convert the Calvin file to XDA format.
Parameters:
fileName The full path name of the CEL file.
newFile The name of the new CEL file.
Returns:
True if successful.
Definition at line 105 of file CELFileConvertToXDA.cpp.
References affymetrix_cel_converter::CELConversionUtilities::Copy(), affymetrix_calvin_io::CelFileReader::Read(), affxcel::CCELFileData::SetChipType(), affxcel::CCELFileData::SetFileFormat(), affxcel::CCELFileData::SetFileName(), affymetrix_calvin_io::CelFileReader::SetFilename(), and affxcel::CCELFileWriter::WriteXDABCel().
Referenced by affymetrix_cel_converter::CELFileConverter::ConvertFile().
CELFileConverterErrorCode affymetrix_cel_converter::CELFileConvertToXDA::ErrorCode () const [inline]
Gets the error code for the conversion process.
Returns:
The error code associated with the last failure.
Definition at line 53 of file CELFileConvertToXDA.h.
Referenced by affymetrix_cel_converter::CELFileConverter::ConvertFile().
void affymetrix_cel_converter::CELFileConvertToXDA::SetExtraParameters (const affymetrix_calvin_parameter::ParameterNameValueTypeVector * params) [inline]
Set extra parameters that are to be written to the file.
Parameters:
params A collection of ParameterNameValueTypes to add to the file.
Definition at line 48 of file CELFileConvertToXDA.h.
The documentation for this class was generated from the following files:
calvin_files/converters/cel/src/CELFileConvertToXDA.h
calvin_files/converters/cel/src/CELFileConvertToXDA.cpp