Affymetrix Power Tools: CNLog2RatioAdjustmentMethodHighPassFilter Class Reference
CNLog2RatioAdjustmentMethodHighPassFilter Class Reference
A class for calulating background.
#include <CNLog2RatioAdjustmentMethodHighPassFilter.h>