Affymetrix Power Tools: CNReferenceMethodAdditionalWaves Class Reference
CNReferenceMethodAdditionalWaves Class Reference
A class for calulating WaveCorrection.
#include <CNReferenceMethodAdditionalWaves.h>