Affymetrix Power Tools: Annotation Class Reference
Annotation Class Reference
Annotation - Wrapper class for the SQLite Annotation database.
#include <Annotation.h>