Affymetrix Power Tools: ChipStreamDataTransform Class Reference
ChipStreamDataTransform Class Reference
Wrapper for ChipStream objects that makes them into DataTransform objects.
#include <ChipStreamDataTransform.h>