Affymetrix Power Tools: PmAdjuster Class Reference
PmAdjuster Class Reference
Interface for determining a change based on intensity of perfect match.
#include <PmAdjuster.h>