Affymetrix Power Tools: QuantMethodExprCCCHPReport Class Reference
QuantMethodExprCCCHPReport Class Reference
Class for reporting results of quantification methods.
#include <QuantMethodExprCCCHPReport.h>