Affymetrix Power Tools: affx::CELTransformerEngine Class Reference
affx::CELTransformerEngine Class Reference
#include <CELTransformerEngine.h>