Affymetrix Power Tools: affymetrix_calvin_io::CHPTilingFileReader Class Reference
affymetrix_calvin_io::CHPTilingFileReader Class Reference
#include <CHPTilingFileReader.h>
Public Member Functions
CHPTilingFileReader ()
~CHPTilingFileReader ()
const std::string GetFilename () const
void SetFilename (const std::string &name)
void Read (CHPTilingData &data)
Protected Attributes
std::string fileName
Detailed Description
This class reads a tiling CHP data file. It is an interpreter class.
Definition at line 38 of file CHPTilingFileReader.h.
Constructor & Destructor Documentation
CHPTilingFileReader::CHPTilingFileReader ()
Constructor
Definition at line 33 of file CHPTilingFileReader.cpp.
CHPTilingFileReader::~CHPTilingFileReader ()
Destructor
Definition at line 40 of file CHPTilingFileReader.cpp.
Member Function Documentation
const std::string affymetrix_calvin_io::CHPTilingFileReader::GetFilename () const [inline]
Gets the name of the input file.
Returns:
The name of the file to read.
Definition at line 52 of file CHPTilingFileReader.h.
References fileName.
void CHPTilingFileReader::Read (CHPTilingData & data)
Reads the file header of the generic file and reads all the DataPlaneHeader information.
Parameters:
data A reference to a GenericData object that will receive information from the file.
Exceptions:
affymetrix_calvin_exceptions::FileNotFoundException The file does not exist.
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Definition at line 44 of file CHPTilingFileReader.cpp.
References affymetrix_calvin_io::CHPTilingData::Clear(), fileName, affymetrix_calvin_io::CHPTilingData::GetFilename(), affymetrix_calvin_io::CHPTilingData::GetGenericData(), affymetrix_calvin_io::GenericFileReader::ReadHeader(), and affymetrix_calvin_io::GenericFileReader::SetFilename().
void affymetrix_calvin_io::CHPTilingFileReader::SetFilename (const std::string & name) [inline]
Sets the name of the input file.
Parameters:
name The name of the file to read.
Definition at line 58 of file CHPTilingFileReader.h.
References fileName.
Member Data Documentation
std::string affymetrix_calvin_io::CHPTilingFileReader::fileName [protected]
Name of the file to read
Definition at line 71 of file CHPTilingFileReader.h.
Referenced by GetFilename(), Read(), and SetFilename().
The documentation for this class was generated from the following files:
calvin_files/parsers/src/CHPTilingFileReader.h
calvin_files/parsers/src/CHPTilingFileReader.cpp