Affymetrix Power Tools: affymetrix_fusion_io::IFusionCELDataAdapter Class Reference
affymetrix_fusion_io::IFusionCELDataAdapter Class Reference
Adapter that wraps both GCOS and Calvin cell file readers and contains the interfaces to the data.
#include <FusionCELDataAdapterInterface.h>