Affymetrix Power Tools: affymetrix_calvin_io::ArrayFileReader Class Reference
affymetrix_calvin_io::ArrayFileReader Class Reference
#include <ArrayFileReader.h>
Public Member Functions
ArrayFileReader ()
~ArrayFileReader ()
bool Read (const std::string &fileName, affymetrix_calvin_array::ArrayData &arrayData, bool headerOnly=false)
Static Public Member Functions
static bool IsFileType (const std::string &fileName, const affymetrix_calvin_utilities::AffymetrixGuidType &dataTypeId)
static
affymetrix_calvin_utilities::AffymetrixGuidType DataTypeIdentifier (const std::string &fileName)
Protected Attributes
std::wstring fileVersionNumber
Detailed Description
This class provides interfaces to read an array file.
Definition at line 41 of file ArrayFileReader.h.
Constructor & Destructor Documentation
ArrayFileReader::ArrayFileReader ()
Constructor
Definition at line 41 of file ArrayFileReader.cpp.
ArrayFileReader::~ArrayFileReader ()
Destructor
Definition at line 48 of file ArrayFileReader.cpp.
Member Function Documentation
affymetrix_calvin_utilities::AffymetrixGuidType ArrayFileReader::DataTypeIdentifier (const std::string & fileName) [static]
The identifier of the type of data stored in the file.
Parameters:
fileName The name of the file to check.
Returns:
The identifier of the type of data.
Definition at line 117 of file ArrayFileReader.cpp.
References affymetrix_calvin_array::ArrayData::DataTypeIdentifier(), and Read().
Referenced by IsFileType().
bool ArrayFileReader::IsFileType (const std::string & fileName, const affymetrix_calvin_utilities::AffymetrixGuidType & dataTypeId) [static]
Determines if a file is of the specified type.
Parameters:
fileName The name of the file to check.
dataTypeId An identifier to the type of data.
Returns:
True if the file matches the type desired.
Definition at line 106 of file ArrayFileReader.cpp.
References DataTypeIdentifier().
bool ArrayFileReader::Read (const std::string & fileName, affymetrix_calvin_array::ArrayData & arrayData, bool headerOnly = false)
Reads the entire contents of the file.
Parameters:
fileName The name of the array file to read.
arrayData The array data to read from the file.
headerOnly Flag to indicate that the header line should only be read.
Definition at line 55 of file ArrayFileReader.cpp.
References affymetrix_calvin_array::ArrayData::Clear(), affymetrix_calvin_io::SAXArrayHandlers::FileVersionNumber(), and fileVersionNumber.
Referenced by DataTypeIdentifier(), and affymetrix_fusion_io::FusionArrayFileReader::Read().
Member Data Documentation
std::wstring affymetrix_calvin_io::ArrayFileReader::fileVersionNumber [protected]
The files version number.
Definition at line 52 of file ArrayFileReader.h.
Referenced by Read().
The documentation for this class was generated from the following files:
calvin_files/parsers/src/ArrayFileReader.h
calvin_files/parsers/src/ArrayFileReader.cpp