Affymetrix Power Tools: MAS5CHPUtils Class Reference
MAS5CHPUtils Class Reference
#include <MAS5CHPUtils.h>
Public Member Functions
MAS5CHPUtils ()
void SetProgramInformation (const std::wstring &name, const std::wstring &co, const std::wstring &id)
void Clear ()
bool SaveCHPFile (const std::string &chpFile, CExpressionAlgorithmImplementation &exp, ExpressionReport::ExpressionProbeSetReporter &report, bool reportPass, bool saveToLegacyFile)
Detailed Description
Provides utilities for writing MAS5 CHP files.
Definition at line 38 of file MAS5CHPUtils.h.
Constructor & Destructor Documentation
MAS5CHPUtils::MAS5CHPUtils () [inline]
Constructor
Definition at line 150 of file MAS5CHPUtils.h.
References Clear().
Member Function Documentation
void MAS5CHPUtils::Clear (void)
Clears the members.
Definition at line 124 of file MAS5CHPUtils.cpp.
Referenced by MAS5CHPUtils().
bool MAS5CHPUtils::SaveCHPFile (const std::string & chpFile, CExpressionAlgorithmImplementation & exp, ExpressionReport::ExpressionProbeSetReporter & report, bool reportPass, bool saveToLegacyFile)
Save the data to a CHP file.
Parameters:
schpFile The name of the output CHP file.
exp The MAS5 results object.
report The report results.
reportPass True if the report has results.
saveToLegacyFile True is saving to older CHP file format.
Returns:
True if successful.
Referenced by MAS5Workflow::Execute().
void MAS5CHPUtils::SetProgramInformation (const std::wstring & name, const std::wstring & co, const std::wstring & id)
Set the program informaion.
Parameters:
name The name of the program
co The company or institution creating the program.
id The identifier of the program.
Definition at line 78 of file MAS5CHPUtils.cpp.
Referenced by MAS5Workflow::Execute().
The documentation for this class was generated from the following files:
mas5-stat/workflow/MAS5CHPUtils.h
mas5-stat/workflow/MAS5CHPUtils.cpp