Affymetrix Power Tools: CNReferenceMethodPDNN Class Reference
CNReferenceMethodPDNN Class Reference
A class for calulating pdnn.
#include <CNReferenceMethodPDNN.h>