Affymetrix Power Tools: affymetrix_fusion_io::FusionGrcFileReader Class Reference
affymetrix_fusion_io::FusionGrcFileReader Class Reference
#include <FusionGrcFileReader.h>
Public Member Functions
FusionGrcFileReader ()
~FusionGrcFileReader ()
bool Read (const std::string &fileName, affymetrix_grid_control::GridControlData &data)
Detailed Description
This class provides GRC file reading capabilities.
This class will read either the GCOS or Calvin format GRC files.
Definition at line 36 of file FusionGrcFileReader.h.
Constructor & Destructor Documentation
FusionGrcFileReader::FusionGrcFileReader ()
Constructor
Definition at line 38 of file FusionGrcFileReader.cpp.
FusionGrcFileReader::~FusionGrcFileReader ()
Destructor
Definition at line 45 of file FusionGrcFileReader.cpp.
Member Function Documentation
bool FusionGrcFileReader::Read (const std::string & fileName, affymetrix_grid_control::GridControlData & data)
Reads the contents of a GRC file.
Parameters:
fileName The name of the file to read.
data A reference to an object that will receive information from the file.
Returns:
True if successful.
Definition at line 53 of file FusionGrcFileReader.cpp.
References affxgrc::CGRCFileData::Read(), affymetrix_calvin_io::GridControlFileReader::Read(), and affxgrc::CGRCFileData::SetFileName().
The documentation for this class was generated from the following files:
calvin_files/fusion/src/FusionGrcFileReader.h
calvin_files/fusion/src/FusionGrcFileReader.cpp