Affymetrix Power Tools: affymetrix_calvin_array::ArrayAuditEntry Class Reference
affymetrix_calvin_array::ArrayAuditEntry Class Reference
#include <ArrayAudit.h>
Public Member Functions
ArrayAuditEntry ()
~ArrayAuditEntry ()
std::wstring & UserName ()
affymetrix_calvin_utilities::DateTime & DateTime ()
affymetrix_calvin_utilities::AffymetrixGuidType & ActionType ()
affymetrix_calvin_utilities::AffymetrixGuidType & ArrayGuid ()
affymetrix_calvin_utilities::AffymetrixGuidTypeList & InputFileGuids ()
affymetrix_calvin_utilities::AffymetrixGuidTypeList & OutputFileGuids ()
affymetrix_calvin_parameter::ParameterNameValuePairList & ActionParameters ()
void Clear ()
Protected Attributes
std::wstring userName
affymetrix_calvin_utilities::AffymetrixGuidType actionType
affymetrix_calvin_utilities::AffymetrixGuidType arrayGuid
affymetrix_calvin_utilities::AffymetrixGuidTypeList inputFileGuids
affymetrix_calvin_utilities::AffymetrixGuidTypeList outputFileGuids
affymetrix_calvin_parameter::ParameterNameValuePairList actionParameters
affymetrix_calvin_utilities::DateTime actionDateTime
Detailed Description
A class to store an audit entry associated with an array.
Definition at line 41 of file ArrayAudit.h.
Constructor & Destructor Documentation
ArrayAuditEntry::ArrayAuditEntry ()
Constructor
Definition at line 29 of file ArrayAudit.cpp.
ArrayAuditEntry::~ArrayAuditEntry ()
Destructor
Definition at line 36 of file ArrayAudit.cpp.
References Clear().
Member Function Documentation
affymetrix_calvin_parameter::ParameterNameValuePairList& affymetrix_calvin_array::ArrayAuditEntry::ActionParameters () [inline]
The list of parameters associated with the action.
Returns:
The list of parameters associated with the action.
Definition at line 113 of file ArrayAudit.h.
References actionParameters.
Referenced by affymetrix_calvin_io::AuditFileReader::Read(), and affymetrix_calvin_io::AuditFileWriter::Write().
affymetrix_calvin_utilities::AffymetrixGuidType& affymetrix_calvin_array::ArrayAuditEntry::ActionType () [inline]
The type of action.
Returns:
The type of action.
Definition at line 89 of file ArrayAudit.h.
References actionType.
Referenced by affymetrix_calvin_io::AuditFileReader::Read(), and affymetrix_calvin_io::AuditFileWriter::Write().
affymetrix_calvin_utilities::AffymetrixGuidType& affymetrix_calvin_array::ArrayAuditEntry::ArrayGuid () [inline]
The id of the physical array associated with the action.
Returns:
The physical array id.
Definition at line 95 of file ArrayAudit.h.
References arrayGuid.
Referenced by affymetrix_calvin_io::AuditFileReader::Read(), and affymetrix_calvin_io::AuditFileWriter::Write().
void ArrayAuditEntry::Clear ()
Clears the member objects.
Clears each member.
Definition at line 44 of file ArrayAudit.cpp.
References actionDateTime, actionParameters, actionType, arrayGuid, affymetrix_calvin_utilities::DateTime::Clear(), inputFileGuids, outputFileGuids, and userName.
Referenced by affymetrix_calvin_io::AuditFileReader::Read(), and ~ArrayAuditEntry().
affymetrix_calvin_utilities::DateTime& affymetrix_calvin_array::ArrayAuditEntry::DateTime () [inline]
The date and time of the action.
Returns:
The date and time of the action.
Definition at line 83 of file ArrayAudit.h.
References actionDateTime.
Referenced by affymetrix_calvin_io::AuditFileReader::Read(), and affymetrix_calvin_io::AuditFileWriter::Write().
affymetrix_calvin_utilities::AffymetrixGuidTypeList& affymetrix_calvin_array::ArrayAuditEntry::InputFileGuids () [inline]
The list of guids for the input files to the action.
Returns:
The list of guids for the input files to the action.
Definition at line 101 of file ArrayAudit.h.
References inputFileGuids.
Referenced by affymetrix_calvin_io::AuditFileReader::Read(), and affymetrix_calvin_io::AuditFileWriter::Write().
affymetrix_calvin_utilities::AffymetrixGuidTypeList& affymetrix_calvin_array::ArrayAuditEntry::OutputFileGuids () [inline]
The list of guids for the input files to the action.
Returns:
The list of guids for the output files of the action.
Definition at line 107 of file ArrayAudit.h.
References outputFileGuids.
Referenced by affymetrix_calvin_io::AuditFileReader::Read(), and affymetrix_calvin_io::AuditFileWriter::Write().
std::wstring& affymetrix_calvin_array::ArrayAuditEntry::UserName () [inline]
The user name associated with the audit entry.
Returns:
The user name associated with the audit entry.
Definition at line 77 of file ArrayAudit.h.
References userName.
Referenced by affymetrix_calvin_io::AuditFileReader::Read(), and affymetrix_calvin_io::AuditFileWriter::Write().
Member Data Documentation
affymetrix_calvin_utilities::DateTime affymetrix_calvin_array::ArrayAuditEntry::actionDateTime [protected]
The date and time of the action.
Definition at line 70 of file ArrayAudit.h.
Referenced by Clear(), and DateTime().
affymetrix_calvin_parameter::ParameterNameValuePairList affymetrix_calvin_array::ArrayAuditEntry::actionParameters [protected]
A list of parameters associated with the action.
Definition at line 67 of file ArrayAudit.h.
Referenced by ActionParameters(), and Clear().
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_calvin_array::ArrayAuditEntry::actionType [protected]
The type of action being performed.
Definition at line 55 of file ArrayAudit.h.
Referenced by ActionType(), and Clear().
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_calvin_array::ArrayAuditEntry::arrayGuid [protected]
The guid to the physical array associated with the action.
Definition at line 58 of file ArrayAudit.h.
Referenced by ArrayGuid(), and Clear().
affymetrix_calvin_utilities::AffymetrixGuidTypeList affymetrix_calvin_array::ArrayAuditEntry::inputFileGuids [protected]
A list of guids for the input file ids to the action.
Definition at line 61 of file ArrayAudit.h.
Referenced by Clear(), and InputFileGuids().
affymetrix_calvin_utilities::AffymetrixGuidTypeList affymetrix_calvin_array::ArrayAuditEntry::outputFileGuids [protected]
A list of guids for the output file ids from the action.
Definition at line 64 of file ArrayAudit.h.
Referenced by Clear(), and OutputFileGuids().
std::wstring affymetrix_calvin_array::ArrayAuditEntry::userName [protected]
The user name creating the audit entry.
Definition at line 52 of file ArrayAudit.h.
Referenced by Clear(), and UserName().
The documentation for this class was generated from the following files:
calvin_files/array/src/ArrayAudit.h
calvin_files/array/src/ArrayAudit.cpp