Affymetrix Power Tools: TranslationCommonControl Class Reference
TranslationCommonControl Class Reference
Static Public Member Functions
static void defineCommonOptions (class TranslationEngine *engine)
TranslationCommonControl::defineCommonOptions Synopsis:
static bool initializeInputFileModels (class RunTimeEnvironment &rte, class MarkerListModel **returnMlm, class CopyNumberTableModel **returnCnrm, class GenotypeTableModel **returnGtm, class TranslationTableModel **returnTtm, class SampleInfoTableModel **returnSitm, class GenotypeOverrideTableModel **returnGotm)
Synopsis: Convert the Copy Number Report, Genotype Short Report and Translation Tablem input files into in memory models.
static void setCommonADTOptions (class ADTOptions &adtOpts, class TranslationEngine *engine)
TranslationCommonControl::setCommonADTOptions: Synopsis: A quasie ADTOptions constructor.
static void validateCommonOptions (class RunTimeEnvironment &rte, class TranslationEngine *engine)
TranslationCommonControl::validateCommonOptions Synopsis:
Detailed Description
Definition at line 41 of file TranslationCommonControl.h.
Member Function Documentation
void TranslationCommonControl::defineCommonOptions (class TranslationEngine * engine) [static]
TranslationCommonControl::defineCommonOptions Synopsis:
Define the space of possible PgOptions for command line or console.
Parameters:
opts - newly allocated PgOptions from either console or command line.
Definition at line 79 of file TranslationCommonControl.cpp.
References APT_ERR_ASSERT.
bool TranslationCommonControl::initializeInputFileModels (class RunTimeEnvironment & rte, class MarkerListModel ** returnMlm, class CopyNumberTableModel ** returnCnrm, class GenotypeTableModel ** returnGtm, class TranslationTableModel ** returnTtm, class SampleInfoTableModel ** returnSitm, class GenotypeOverrideTableModel ** returnGotm) [static]
Synopsis: Convert the Copy Number Report, Genotype Short Report and Translation Tablem input files into in memory models.
Note that all the input paramaters are for return.
Parameters:
rte - single instance run-time environment data model
returnMlm - marker list single instance data model
returnCnrm - DMET2 only copy number list single instance data model
returnGtm - Genotype data (CHP) single instance data model.
returnTtm - Translation table data single instance data mode.
returnSitm - Sample info single instance data model.
returnGotm - Genotype override single instance data model.
Returns:
true - all models where successfully allocated on the heap.
Definition at line 181 of file TranslationCommonControl.cpp.
References APT_ERR_ASSERT, and Verbose::out().
Referenced by TranslationEngine::runImp().
void TranslationCommonControl::setCommonADTOptions (class ADTOptions & adtOpts, class TranslationEngine * engine) [static]
TranslationCommonControl::setCommonADTOptions: Synopsis: A quasie ADTOptions constructor.
Perhaps it should be? Copies all the passed in options to the ADTOptions single instance object that itself is stashed in the rte.
Parameters:
adtOpts - the ADTOptions to set up.
ptOpts - from command line or console.
Definition at line 295 of file TranslationCommonControl.cpp.
References Options::getOpt(), Options::getOptBool(), Options::getOptInt(), BaseEngine::getProgName(), and TranslationTableModel::getTranslationTableFileType().
void TranslationCommonControl::validateCommonOptions (class RunTimeEnvironment & rte, class TranslationEngine * engine) [static]
TranslationCommonControl::validateCommonOptions Synopsis:
Validate options after they have been filled in by the call the setCommonOptions. If any errors are detected during validation then an exception is thrown via Err::Abort.
Parameters:
rte - the single instance run time environment that houses the ADTOptions object as m_adtOpts previously set in setCommonOptions. .
engine - to be validated.
Definition at line 894 of file TranslationCommonControl.cpp.
References APT_ERR_ABORT, APT_ERR_ASSERT, Fs::mkdirPath(), and Verbose::out().
The documentation for this class was generated from the following files:
translation/TranslationCommonControl.h
translation/TranslationCommonControl.cpp