Affymetrix Power Tools: affymetrix_fusion_io::GCOSCELDataAdapter Class Reference
affymetrix_fusion_io::GCOSCELDataAdapter Class Reference
GCOS Adapter that wraps GCOS cell file reader for Fusion and contains the interfaces to the data.
#include <GCOSCELDataAdapter.h>