Affymetrix Power Tools: ProbeListPacked Class Reference
ProbeListPacked Class Reference
Public Member Functions
ProbeListPacked (ProbeList_Head *ptr)
bool isNull () const
int get_type () const
void set_type (int type)
int getApidStart () const
void setApidStart (int start)
int findProbeApid (int qPid, int qAllele, int qContext, int qChannel) const
int byte_size () const
int block_cnt () const
int probe_cnt () const
int max_name_len () const
int get_numMatch () const
void set_numMatch (int numMatch)
int get_blockSize (int bidx) const
void set_blockSize (int bidx, int val)
short get_blockAnn (int bidx) const
void set_blockAnn (int bidx, short val)
int get_blockAllele (int bidx) const
void set_blockAllele (int bidx, int val)
int get_blockContext (int bidx) const
void set_blockContext (int bidx, int val)
int get_blockChannel (int bidx) const
void set_blockChannel (int bidx, int val)
int get_blockRepType (int bidx) const
void set_blockRepType (int bidx, int val)
int findBlockMatch (int qAllele, int qContext, int qChannel) const
bool hasDuplicateBlocks () const
int get_probeIdxForBlock (int blockIdx) const
ProbeList_E_Block * get_addr_E_block (unsigned int i) const
ProbeList_E_Probe * get_addr_E_probe (unsigned int i) const
int get_probeId (int pidx) const
void set_probeId (int pidx, int val)
void get_probeIds (std::vector< int > &probeIds) const
void get_probeIdsForBlock (int blockIdx, std::vector< int > &probeIds) const
int pidxToBidx (int pidx) const
bool isPm (int pidx) const
int get_probeApid (int pidx) const
Gets the Apid of this probe. /// See the note next to m_apid_start about probeId!=probeApid.
int8_t get_probeGc (int pidx) const
void set_probeGc (int pidx, int8_t val)
char * get_addr_E_name ()
const char * get_addr_E_name () const
const char * get_name_cstr () const
std::string get_name_string () const
void set_name (const std::string &name)
void dump () const
Static Public Member Functions
static int byte_size (int b_cnt, int p_cnt, int n_len)
Public Attributes
ProbeList_Head * m_headptr
Static Public Attributes
static double timecheck10
static double timecheck11
Detailed Description
Definition at line 541 of file ProbeListFactory.h.
Member Function Documentation
int ProbeListPacked::findBlockMatch (int qAllele, int qContext, int qChannel) const
Todo:
this should be somehow unified with the ProbeListStl version.
Definition at line 346 of file ProbeListFactory.cpp.
int ProbeListPacked::get_blockSize (int bidx) const
Todo:
add set_XXX(std::vector<int>);
Definition at line 276 of file ProbeListFactory.cpp.
Referenced by ProbeListFactory::asProbeSet(), ProbeListStl::operator=(), and ChipLayout::writeSpfProbeListRecord().
The documentation for this class was generated from the following files:
chipstream/ProbeListFactory.h
chipstream/ProbeListFactory.cpp