Affymetrix Power Tools: SparseMart Class Reference
SparseMart Class Reference
SparseMart Class for representing only a subset of cel file intensity data in memory.
#include <SparseMart.h>