Affymetrix Power Tools: affymetrix_calvin_io::DataGroupHeaderReader Class Reference
affymetrix_calvin_io::DataGroupHeaderReader Class Reference
#include <DataGroupHeaderReader.h>
Public Member Functions
DataGroupHeaderReader ()
void ReadAllMinimumInfo (std::ifstream &fs, FileHeader &fh, u_int32_t dataGroupCnt)
void ReadAll (std::ifstream &fileStream, FileHeader &fh, u_int32_t dataGroupCnt)
u_int32_t ReadMinimumInfo (std::ifstream &fileStream, DataGroupHeader &dch)
u_int32_t Read (std::ifstream &fileStream, DataGroupHeader &dch)
u_int32_t ReadHeader (std::ifstream &fileStream, DataGroupHeader &dch)
Protected Member Functions
void ReadDataGroupStartFilePos (std::ifstream &fileStream, DataGroupHeader &grpHdr)
void ReadNextDataGroupFilePos (std::ifstream &fileStream, DataGroupHeader &dch)
void ReadFirstDataSetFilePos (std::ifstream &fileStream, DataGroupHeader &dch)
u_int32_t ReadDataSetCnt (std::ifstream &fileStream, DataGroupHeader &dch)
void ReadDataGroupName (std::ifstream &fileStream, DataGroupHeader &dch)
Detailed Description
This class reads the all the DataGroupHeader information from a file into a FileHeader object.
Definition at line 44 of file DataGroupHeaderReader.h.
Constructor & Destructor Documentation
DataGroupHeaderReader::DataGroupHeaderReader ()
Constructor
Definition at line 35 of file DataGroupHeaderReader.cpp.
Member Function Documentation
u_int32_t DataGroupHeaderReader::Read (std::ifstream & fileStream, DataGroupHeader & dch)
Read the DataGroupHeader and all DataSetHeaders associated with this DataGroupHeader from the file.
Parameters:
fileStream Open fstream positioned at the start of the first DataGroupHeader in the file.
dch DataGroupHeader object to fill.
Returns:
The file position of the next data group
Definition at line 98 of file DataGroupHeaderReader.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetNextGroupPos(), affymetrix_calvin_io::DataSetHeaderReader::ReadAll(), ReadDataGroupStartFilePos(), and ReadHeader().
Referenced by affymetrix_calvin_io::GenericData::DataGroup(), and ReadAll().
void DataGroupHeaderReader::ReadAll (std::ifstream & fileStream, FileHeader & fh, u_int32_t dataGroupCnt)
Reads all the DataGroupHeaders in a file and all information for each DataSetHeader in every DataGroup.
Parameters:
fileStream Open fstream positioned at the start of the first DataGroupHeader in the file.
fh FileHeader object to fill.
dataGroupCnt Number of DataGroup in the file.
Definition at line 63 of file DataGroupHeaderReader.cpp.
References affymetrix_calvin_io::FileHeader::GetFirstDataGroupFilePos(), and Read().
Referenced by affymetrix_calvin_io::GenericFileReader::ReadFileHeader().
void DataGroupHeaderReader::ReadAllMinimumInfo (std::ifstream & fs, FileHeader & fh, u_int32_t dataGroupCnt)
Reads all the DataGroupHeaders in a file and the minimum information for each DataSetHeader in every DataGroup.
Parameters:
fs Open fstream positioned at the start of the first DataGroupHeader in the file.
fh FileHeader object to fill.
dataGroupCnt Number of DataGroup in the file.
Definition at line 42 of file DataGroupHeaderReader.cpp.
References affymetrix_calvin_io::FileHeader::GetFirstDataGroupFilePos(), and ReadMinimumInfo().
Referenced by affymetrix_calvin_io::GenericFileReader::ReadFileHeaderMinDP().
void DataGroupHeaderReader::ReadDataGroupName (std::ifstream & fileStream, DataGroupHeader & dch) [protected]
Reads the number of DataGroup name.
Parameters:
fileStream Open fstream positioned at the start of the DataGroupHeader name.
dch DataGroupHeader object to which to add the DataGroup name.
Definition at line 165 of file DataGroupHeaderReader.cpp.
References affymetrix_calvin_io::FileInput::ReadString16(), and affymetrix_calvin_io::DataGroupHeader::SetName().
Referenced by ReadHeader().
void DataGroupHeaderReader::ReadDataGroupStartFilePos (std::ifstream & fileStream, DataGroupHeader & grpHdr) [protected]
Read the file position of the start of the DataGroup.
Parameters:
fileStream Open fstream positioned at the start of the DataGroupHeader.
dsh Reference to the DataGroupHeader object to fill.
Definition at line 124 of file DataGroupHeaderReader.cpp.
References affymetrix_calvin_io::DataGroupHeader::SetHeaderStartFilePos().
Referenced by Read(), and ReadMinimumInfo().
u_int32_t DataGroupHeaderReader::ReadDataSetCnt (std::ifstream & fileStream, DataGroupHeader & dch) [protected]
Reads the number of DataSets associated with the current DataGroup.
Parameters:
fileStream Open fstream positioned at the start of the DataGroupHeader count.
dch DataGroupHeader object in which to add the DataSet count.
Definition at line 154 of file DataGroupHeaderReader.cpp.
References affymetrix_calvin_io::FileInput::ReadUInt32().
Referenced by ReadHeader().
void DataGroupHeaderReader::ReadFirstDataSetFilePos (std::ifstream & fileStream, DataGroupHeader & dch) [protected]
Reads the file position of the first DataSet associated with the current DataGroup.
Parameters:
fileStream Open fstream positioned at the start of the file position of the first DataSetHeader in the DataGroup.
dch DataGroupHeader object to which to add the DataSetHeader information.
Definition at line 143 of file DataGroupHeaderReader.cpp.
References affymetrix_calvin_io::FileInput::ReadUInt32(), and affymetrix_calvin_io::DataGroupHeader::SetDataSetPos().
Referenced by ReadHeader().
u_int32_t DataGroupHeaderReader::ReadHeader (std::ifstream & fileStream, DataGroupHeader & dch)
Reads the DataGroupHeader from the file. Doesn't read all DataSetHeader information.
Parameters:
fileStream Open fstream positioned at the start of a DataGroupHeader in the file.
dch DataGroupHeader object to fill with the header information.
Returns:
The number of DataSetHeaders associated with the current DataGroupHeader.
Definition at line 112 of file DataGroupHeaderReader.cpp.
References ReadDataGroupName(), ReadDataSetCnt(), ReadFirstDataSetFilePos(), and ReadNextDataGroupFilePos().
Referenced by Read(), and ReadMinimumInfo().
u_int32_t DataGroupHeaderReader::ReadMinimumInfo (std::ifstream & fileStream, DataGroupHeader & dch)
Reads the DataGroupHeader and the minimum information for all DataSetHeaders associated with this DataGroupHeader from the file.
Parameters:
fileStream Open fstream positioned at the start of the first DataGroupHeader in the file.
dch DataGroupHeader object to fill.
Returns:
The file position of the next data group
Definition at line 84 of file DataGroupHeaderReader.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetNextGroupPos(), affymetrix_calvin_io::DataSetHeaderReader::ReadAllMinimumInfo(), ReadDataGroupStartFilePos(), and ReadHeader().
Referenced by ReadAllMinimumInfo().
void DataGroupHeaderReader::ReadNextDataGroupFilePos (std::ifstream & fileStream, DataGroupHeader & dch) [protected]
Reads the file position of the next DataGroup.
Parameters:
fileStream Open fstream positioned at the start of the file position of a DataGroupHeader.
dch DataGroupHeader object in which to write the file position.
Definition at line 132 of file DataGroupHeaderReader.cpp.
References affymetrix_calvin_io::FileInput::ReadUInt32(), and affymetrix_calvin_io::DataGroupHeader::SetNextGroupPos().
Referenced by ReadHeader().
The documentation for this class was generated from the following files:
calvin_files/parsers/src/DataGroupHeaderReader.h
calvin_files/parsers/src/DataGroupHeaderReader.cpp