Affymetrix Power Tools: affymetrix_calvin_io::GenericData Class Reference
affymetrix_calvin_io::GenericData Class Reference
#include <GenericData.h>
Public Member Functions
GenericData ()
~GenericData ()
AffymetrixGuidType FileIdentifier ()
AffymetrixGuidType ArrayFileIdentifier ()
AffymetrixGuidType ArrayIdentifier ()
FileHeader & Header ()
u_int32_t DataGroupCnt () const
void DataGroupNames (WStringVector &names)
u_int32_t DataSetCnt (u_int32_t dataGroupIdx)
u_int32_t DataSetCnt (const std::wstring &dataGroupName)
void DataSetNames (u_int32_t dataGroupIdx, WStringVector &names)
void DataSetNames (const std::wstring &dataGroupName, WStringVector &names)
affymetrix_calvin_io::DataSet * DataSet (u_int32_t dataGroupIdx, u_int32_t dataSetIdx)
affymetrix_calvin_io::DataSet * DataSet (const std::wstring &dataGroupName, const std::wstring &dataSetName)
affymetrix_calvin_io::DataGroup DataGroup (u_int32_t dataGroupFilePos)
void Clear ()
void UseMemoryMapping (bool value)
void LoadEntireDataSetHint (bool value)
void ReadFullDataSetHeader (DataSetHeader *dph)
bool IsDSHPartiallyRead (const affymetrix_calvin_io::DataSetHeader *dph)
void OpenFStream (std::ifstream &ifs)
affymetrix_calvin_io::DataGroupHeader * FindDataGroupHeader (const std::wstring &name)
affymetrix_calvin_io::DataGroupHeader * FindDataGroupHeader (int32_t index)
bool Open ()
void Close ()
bool MapFile ()
void UnmapFile ()
affymetrix_calvin_io::DataSet * CreateDataSet (DataSetHeader *dsh)
Static Public Member Functions
static
affymetrix_calvin_io::DataSetHeader * FindDataSetHeader (affymetrix_calvin_io::DataGroupHeader *dch, u_int32_t dataSetIdx)
static
affymetrix_calvin_io::DataSetHeader * FindDataSetHeader (affymetrix_calvin_io::DataGroupHeader *dch, const std::wstring &dataSetName)
Protected Attributes
affymetrix_calvin_io::FileHeader header
bool useMemoryMapping
std::ifstream fileStream
bool loadEntireDataSetHint
Friends
class DataGroup
Detailed Description
This class provides interfaces to store analysis results and data.
Definition at line 51 of file GenericData.h.
Constructor & Destructor Documentation
GenericData::GenericData ()
Constructor
Definition at line 40 of file GenericData.cpp.
References loadEntireDataSetHint, and useMemoryMapping.
GenericData::~GenericData ()
Destructor
Definition at line 53 of file GenericData.cpp.
References Clear().
Member Function Documentation
affymetrix_calvin_utilities::AffymetrixGuidType GenericData::ArrayFileIdentifier ()
Returns the parent array file identifier.
Returns:
The parent array file identifier.
Definition at line 69 of file GenericData.cpp.
References ARRAY_TYPE_IDENTIFIER, affymetrix_calvin_io::GenericDataHeader::FindParent(), affymetrix_calvin_io::GenericDataHeader::GetFileId(), and header.
affymetrix_calvin_utilities::AffymetrixGuidType GenericData::ArrayIdentifier ()
Returns the parent array identifier.
Returns:
The parent array identifier.
Definition at line 86 of file GenericData.cpp.
References ARRAY_ID_PARAM_NAME, ARRAY_TYPE_IDENTIFIER, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_io::GenericDataHeader::FindParent(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), and header.
void GenericData::Clear ()
Clears the contents of the class.
Definition at line 337 of file GenericData.cpp.
References Close(), header, and useMemoryMapping.
Referenced by CNFamilialReporterFamilial::addParentHeaders(), affymetrix_fusion_io::FusionCHPGenericData::Clear(), Calvin::load(), CNCychp::readFile(), and ~GenericData().
void GenericData::Close ()
Closes the file.
Definition at line 462 of file GenericData.cpp.
References fileStream, and UnmapFile().
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), and Clear().
DataSet * GenericData::CreateDataSet (DataSetHeader * dsh)
Creates a new DataSet
Parameters:
dsh The DataSetHeader of the DataSet to create.
Returns:
The new DataSet
Definition at line 268 of file GenericData.cpp.
References DataSet(), fileStream, Header(), loadEntireDataSetHint, ReadFullDataSetHeader(), and useMemoryMapping.
Referenced by DataSet().
affymetrix_calvin_io::DataGroup GenericData::DataGroup (u_int32_t dataGroupFilePos)
Returns a DataGroup object based on a DataGroup file position. This is useful when there are many DataGroups and the file position of each DataGroup is known (Calvin CDF). In this case the GenericFileReader::ReadHeader() method should be called with the ReadNoDataGroupHeader flag.
Parameters:
dataGroupFilePos File position of the DataGroup in the current file
Returns:
DataGroup object.
Definition at line 288 of file GenericData.cpp.
References fileStream, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), Header(), loadEntireDataSetHint, Open(), OpenFStream(), affymetrix_calvin_io::DataGroupHeaderReader::Read(), and useMemoryMapping.
u_int32_t GenericData::DataGroupCnt () const
Return the number of DataGroups in the GenericData object.
Returns:
Number of DataGroups.
Definition at line 107 of file GenericData.cpp.
References affymetrix_calvin_io::FileHeader::GetDataGroupCnt(), and header.
Referenced by EngineUtil::checkCelChipTypes(), and affymetrix_calvin_io::GenericFileReader::GetDataGroupCnt().
void GenericData::DataGroupNames (WStringVector & names)
Return the names of the DataGroups in the generic data object.
Parameters:
names An [in,out] vector that will receive the names of all DataGroups.
Definition at line 115 of file GenericData.cpp.
References header.
Referenced by Calvin::load(), and CNCychp::readFile().
DataSet * GenericData::DataSet (u_int32_t dataGroupIdx, u_int32_t dataSetIdx)
Returns a pointer to the DataSet object by DataGroup and DataSet index. Each call will return a new DataSet object. The caller should call Delete when finished with the DataSet.
Parameters:
dataGroupIdx The index of the DataGroup from which to find the DataSet.
dataSetIdx The index of the DataSet to return.
Returns:
DataSet
Exceptions:
affymetrix_calvin_exceptions::DataGroupNotFoundException DataGroup not found.
affymetrix_calvin_exceptions::DataSetNotFoundException DataSet not found.
Definition at line 204 of file GenericData.cpp.
References CreateDataSet(), FindDataGroupHeader(), FindDataSetHeader(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and Open().
Referenced by CreateDataSet(), affymetrix_calvin_io::CelFileData::GetDataSetParameters(), Calvin::load(), affymetrix_calvin_io::CHPQuantificationData::OpenQuantificationDataSet(), affymetrix_calvin_io::CHPQuantificationDetectionData::OpenQuantificationDetectionDataSet(), affymetrix_calvin_io::CHPTilingData::OpenTilingSequenceDataSet(), affymetrix_calvin_io::CHPData::PrepareBackgroundZoneDataSet(), affymetrix_calvin_io::CHPData::PrepareExprEntryDataSet(), affymetrix_calvin_io::CHPData::PrepareForceDataSet(), affymetrix_calvin_io::CHPData::PrepareGenoEntryDataSet(), affymetrix_calvin_io::CHPData::PrepareOrigDataSet(), affymetrix_calvin_io::CHPData::PrepareReseqEntryDataSet(), affymetrix_calvin_io::CHPData::PrepareUnivEntryDataSet(), affymetrix_calvin_io::GridControlFileReader::Read(), and CNCychp::readFile().
DataSet * GenericData::DataSet (const std::wstring & dataGroupName, const std::wstring & dataSetName)
Returns a pointer to the DataSet object by DataGroup and DataSet name. Each call will return a new DataSet object. The caller should call Delete when finished with the DataSet.
Parameters:
dataGroupName The name of the DataGroup from which to find the DataSet.
dataSetName The name of the DataSet to return.
Returns:
DataSet
Exceptions:
affymetrix_calvin_exceptions::DataGroupNotFoundException DataGroup not found.
affymetrix_calvin_exceptions::DataSetNotFoundException DataSet not found.
Definition at line 236 of file GenericData.cpp.
References CreateDataSet(), FindDataGroupHeader(), FindDataSetHeader(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and Open().
u_int32_t GenericData::DataSetCnt (const std::wstring & dataGroupName)
Return the number of DataSets in the DataGroup referenced by name.
Parameters:
dataGroupName Name of the DataGroup.
Returns:
Number of DataSets associated with the DataGroup.
Exceptions:
affymetrix_calvin_exceptions::DataGroupNotFoundException DataGroup not found.
Definition at line 145 of file GenericData.cpp.
References FindDataGroupHeader(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt().
u_int32_t GenericData::DataSetCnt (u_int32_t dataGroupIdx)
Return the number of DataSets in the DataGroup referenced by index.
Parameters:
dataGroupIdx Index of the DataGroup.
Returns:
Number of DataSets associated with the DataGroup.
Exceptions:
affymetrix_calvin_exceptions::DataGroupNotFoundException DataGroup not found.
Definition at line 130 of file GenericData.cpp.
References FindDataGroupHeader(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt().
void GenericData::DataSetNames (u_int32_t dataGroupIdx, WStringVector & names)
Return the DataSet names associated with a DataGroup.
Parameters:
dataGroupIdx Index of the DataGroup from which to retrieve the DataSet names.
names An [in,out] vector that will receive the names of all DataSets.
Exceptions:
affymetrix_calvin_exceptions::DataGroupNotFoundException DataGroup not found.
Definition at line 160 of file GenericData.cpp.
References FindDataGroupHeader(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and affymetrix_calvin_io::DataGroupHeader::GetDataSetIterators().
Referenced by Calvin::load(), and CNCychp::readFile().
void GenericData::DataSetNames (const std::wstring & dataGroupName, WStringVector & names)
Return the DataSet names associated with a DataGroup.
Parameters:
dataGroupName Name of the DataGroup from which to retrieve the DataSet names.
names An [in,out] vector that will receive the names of all DataSets.
Exceptions:
affymetrix_calvin_exceptions::DataGroupNotFoundException DataGroup not found.
Definition at line 182 of file GenericData.cpp.
References FindDataGroupHeader(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and affymetrix_calvin_io::DataGroupHeader::GetDataSetIterators().
affymetrix_calvin_utilities::AffymetrixGuidType GenericData::FileIdentifier ()
Returns the file identifier.
Returns:
The file identifier.
Definition at line 61 of file GenericData.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetFileId(), and header.
Referenced by affymetrix_fusion_io::FusionCHPTilingData::FileId(), affymetrix_fusion_io::FusionCHPQuantificationDetectionData::FileId(), affymetrix_fusion_io::FusionCHPQuantificationData::FileId(), affymetrix_fusion_io::FusionCHPGenericData::FileId(), and affymetrix_calvin_io::GridControlFileReader::Read().
DataGroupHeader * GenericData::FindDataGroupHeader (int32_t index)
Finds a DataGroupHeader by index.
Parameters:
index The index of the DataGroup.
Returns:
A pointer to the DataGroupHeader. If not found, the return is 0.
Definition at line 357 of file GenericData.cpp.
References affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::FileHeader::GetDataGroupCnt(), and header.
DataGroupHeader * GenericData::FindDataGroupHeader (const std::wstring & name)
Finds a DataSetHeader by name.
Parameters:
name The name of the DataGroup
Returns:
A pointer to the DataGroupHeader. If not found, the return is 0.
Definition at line 348 of file GenericData.cpp.
References affymetrix_calvin_io::FileHeader::FindDataGroupHeader(), and header.
Referenced by DataSet(), DataSetCnt(), DataSetNames(), and affymetrix_calvin_io::GenericFileReader::GetDataGroupReader().
DataSetHeader * GenericData::FindDataSetHeader (affymetrix_calvin_io::DataGroupHeader * dch, const std::wstring & dataSetName) [static]
Finds a DataSetHeader by name.
Parameters:
dch The DataGroupHeader of the DataGroup to which the DataSet belongs.
dataSetName The DataSet name of the DataSetHeader to find.
Returns:
A pointer to the DataSetHeader if it is found, otherwise 0.
Definition at line 370 of file GenericData.cpp.
DataSetHeader * GenericData::FindDataSetHeader (affymetrix_calvin_io::DataGroupHeader * dch, u_int32_t dataSetIdx) [static]
Finds a DataSetHeader by index.
Parameters:
dch The DataGroupHeader of the DataGroup to which the DataSet belongs.
dataSetIdx The DataSet index of the DataSetHeader to find.
Returns:
A pointer to the DataSetHeader if it is found, otherwise 0.
Definition at line 383 of file GenericData.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetDataSet().
Referenced by DataSet(), and affymetrix_calvin_io::DataGroup::DataSet().
FileHeader& affymetrix_calvin_io::GenericData::Header () [inline]
Returns a reference to the file header object
Returns:
File header object
Definition at line 79 of file GenericData.h.
Referenced by affymetrix_calvin_io::CelFileData::AddAlgorithmParameter(), affymetrix_calvin_io::CHPTilingData::AddAlgParams(), affymetrix_calvin_io::CHPQuantificationDetectionData::AddAlgParams(), affymetrix_calvin_io::CHPQuantificationData::AddAlgParams(), affymetrix_calvin_io::CHPMultiDataData::AddAlgParams(), affymetrix_calvin_io::CHPMultiDataData::AddAppMetaInfo(), affymetrix_calvin_io::CHPData::AddColumns(), affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), CNFamilialReporterFamilial::addParentHeaders(), affymetrix_calvin_io::CHPQuantificationDetectionData::AddSummaryParams(), affymetrix_calvin_io::CHPQuantificationData::AddSummaryParams(), affymetrix_calvin_io::CHPMultiDataData::AddSummaryParams(), affymetrix_calvin_io::CHPTilingData::AddTilingSequenceData(), affymetrix_calvin_io::CelFileData::CelFileData(), affymetrix_calvin_io::CHPData::CHPData(), affymetrix_calvin_io::CHPMultiDataData::CHPMultiDataData(), affymetrix_calvin_io::CHPQuantificationData::CHPQuantificationData(), affymetrix_calvin_io::CHPQuantificationDetectionData::CHPQuantificationDetectionData(), affymetrix_calvin_io::CHPTilingData::CHPTilingData(), affymetrix_calvin_io::DATData::Clear(), affymetrix_calvin_io::CHPTilingData::Clear(), affymetrix_calvin_io::CHPQuantificationDetectionData::Clear(), affymetrix_calvin_io::CHPQuantificationData::Clear(), affymetrix_calvin_io::CHPMultiDataData::Clear(), affymetrix_calvin_io::CHPData::Clear(), affymetrix_calvin_io::CelFileData::Clear(), affymetrix_calvin_io::CDFData::Clear(), CreateDataSet(), CopyNumberResultWriter::CreateResultFile(), DataGroup(), affymetrix_calvin_io::DATData::DATData(), affymetrix_calvin_io::CelFileData::Exists(), affymetrix_calvin_io::CelFileData::FindAlgorithmParameter(), QuantMethodMultiDataCCCHPReport::finish(), QuantMethodExprCCCHPReport::finish(), FromHP(), affymetrix_calvin_io::CelFileData::GetAlgorithmParameters(), affymetrix_calvin_io::CHPData::GetAlgParam(), affymetrix_calvin_io::CHPTilingData::GetAlgParams(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetAlgParams(), affymetrix_calvin_io::CHPQuantificationData::GetAlgParams(), affymetrix_calvin_io::CHPMultiDataData::GetAlgParams(), affymetrix_calvin_io::CHPData::GetAlgParams(), affymetrix_calvin_io::CHPData::GetAssayType(), affymetrix_calvin_io::CHPData::GetBackgroundZoneCnt(), affymetrix_calvin_io::CHPData::GetChipSum(), affymetrix_calvin_io::CHPData::GetChipSums(), affymetrix_calvin_io::CHPMultiDataData::GetDataGroupHeader(), affymetrix_calvin_io::CHPMultiDataData::GetDataGroupIndex(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetDataSetHeader(), affymetrix_calvin_io::CHPQuantificationData::GetDataSetHeader(), affymetrix_calvin_io::CHPMultiDataData::GetDataSetHeader(), affymetrix_calvin_io::CDFData::GetDataTypeId(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetEntryCount(), affymetrix_calvin_io::CHPQuantificationData::GetEntryCount(), affymetrix_calvin_io::CHPData::GetEntryCount(), affymetrix_calvin_io::CHPTilingData::GetFileHeader(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetFileHeader(), affymetrix_calvin_io::CHPQuantificationData::GetFileHeader(), affymetrix_calvin_io::CHPMultiDataData::GetFileHeader(), affymetrix_calvin_io::CHPData::GetFileHeader(), affymetrix_calvin_io::CelFileData::GetFileHeader(), affymetrix_calvin_io::CDFData::GetFileHeader(), affymetrix_calvin_io::DATData::GetFilename(), affymetrix_calvin_io::CDFData::GetFilename(), affymetrix_calvin_io::CHPData::GetForceCnt(), affymetrix_calvin_io::CHPData::GetInt32FromGenericHdr(), affymetrix_calvin_io::CHPData::GetMagic(), affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets(), affymetrix_fusion_io::FusionCDFFileHeader::GetNumQCProbeSets(), affymetrix_calvin_io::CHPData::GetOrigCnt(), affymetrix_calvin_io::DATData::GetParentArrayGenericDataHeader(), affymetrix_calvin_io::DATData::GetPixelSize(), affymetrix_fusion_io::FusionCDFData::GetProbeSetInformation(), affymetrix_calvin_io::CDFData::GetProbeSetInformation(), affymetrix_calvin_io::CDFData::GetProbeSetName(), affymetrix_fusion_io::FusionCDFData::GetProbeSetType(), affymetrix_fusion_io::FusionCDFData::GetQCProbeSetInformation(), affymetrix_calvin_io::CDFData::GetQCProbeSetInformation(), affymetrix_calvin_io::CDFData::GetRefSequence(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetSummaryParams(), affymetrix_calvin_io::CHPQuantificationData::GetSummaryParams(), affymetrix_calvin_io::CHPMultiDataData::GetSummaryParams(), affymetrix_calvin_io::CHPTilingData::GetTilingSequenceEntryCount(), affymetrix_calvin_io::CHPData::GetVersion(), affymetrix_calvin_io::CelFileData::GetVersion(), affymetrix_calvin_io::CHPData::GetWStringFromGenericHdr(), affymetrix_calvin_io::DataSetUpdater::Initialize(), Calvin::load(), makeMultiCelFileSubset(), MapFile(), OpenFStream(), QuantMethodMultiDataCCCHPReport::prepare(), QuantMethodExprCCCHPReport::prepare(), affymetrix_calvin_io::GridControlFileReader::Read(), CNCychp::readFile(), affymetrix_calvin_io::GenericFileReader::ReadFileHeader(), affymetrix_calvin_io::GenericFileReader::ReadFileHeaderMinDP(), affymetrix_calvin_io::GenericFileReader::ReadFileHeaderNoDataGroupHeader(), CNReporterCnchp::run(), CNFamilialReporterFamilial::run(), affymetrix_calvin_io::CHPData::SetBackgroundZoneCnt(), affymetrix_calvin_io::CHPQuantificationDetectionData::SetEntryCount(), affymetrix_calvin_io::CHPQuantificationData::SetEntryCount(), affymetrix_calvin_io::CHPData::SetEntryCount(), affymetrix_calvin_io::DATData::SetFilename(), affymetrix_calvin_io::CHPTilingData::SetFilename(), affymetrix_calvin_io::CHPQuantificationDetectionData::SetFilename(), affymetrix_calvin_io::CHPQuantificationData::SetFilename(), affymetrix_calvin_io::CHPMultiDataData::SetFilename(), affymetrix_calvin_io::CHPData::SetFilename(), affymetrix_calvin_io::CelFileData::SetFilename(), affymetrix_calvin_io::CDFData::SetFilename(), affymetrix_calvin_io::CHPData::SetFloatToGenericHdr(), affymetrix_calvin_io::CHPData::SetForceCnt(), affymetrix_calvin_io::CHPData::SetInt32ToGenericHdr(), affymetrix_calvin_io::CHPData::SetOrigCnt(), affymetrix_calvin_io::DATData::SetPixelSize(), affymetrix_calvin_io::CDFData::SetRefSequence(), CNFamilialReporterFamilial::setupDataSetHeaderPaternityTesting(), CNFamilialReporterFamilial::setupDataSetHeaderSamples(), CNFamilialReporterFamilial::setupDataSetHeaderSegmentOverlaps(), CNFamilialReporterFamilial::setupDataSetHeaderSegments(), CNFamilialReporterFamilial::setupHeader(), and affymetrix_calvin_io::CHPData::SetWStringToGenericHdr().
bool GenericData::IsDSHPartiallyRead (const affymetrix_calvin_io::DataSetHeader * dph)
Determine if the DataSetHeader has been partially read.
Parameters:
dph Pointer to the DataSetHeader to check
Returns:
true if the dph has only been partially read or is 0, otherwise false.
Definition at line 428 of file GenericData.cpp.
References affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), affymetrix_calvin_io::DataSetHeader::GetNameValParamCnt(), and affymetrix_calvin_io::DataSetHeader::GetRowCnt().
Referenced by ReadFullDataSetHeader().
void affymetrix_calvin_io::GenericData::LoadEntireDataSetHint (bool value) [inline]
Set the data loading policy for DataSets and DataGroups created by GenericData. This is considered a hint to DataSet. Default value is false.
Parameters:
value If value is true, DataSets created subsequently will attempt to read the entire DataSet data into a memory buffer.
Definition at line 164 of file GenericData.h.
bool GenericData::MapFile ()
Opens a memory map on the file. Has no effect on non-Windows systems.
Returns:
True if the memory-mapping was opened successfully.
Definition at line 472 of file GenericData.cpp.
References Header(), and Verbose::out().
Referenced by Open().
bool GenericData::Open ()
Opens the file for access. Has no effect on non-Windows systems.
Returns:
True if the memory-mapping was opened successfully.
Definition at line 450 of file GenericData.cpp.
References fileStream, MapFile(), OpenFStream(), and useMemoryMapping.
Referenced by DataGroup(), and DataSet().
void GenericData::OpenFStream (std::ifstream & ifs)
Opens a ifstream object on the file set on the Header() method
Parameters:
ifs The stream to open on the file.
Definition at line 440 of file GenericData.cpp.
References affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and Header().
Referenced by DataGroup(), Open(), and ReadFullDataSetHeader().
void GenericData::ReadFullDataSetHeader (DataSetHeader * dph)
Read the full DataSetHeader if it has only been parially read.
Parameters:
dph Pointer to the DataSetHeader to read
Definition at line 399 of file GenericData.cpp.
References fileStream, affymetrix_calvin_io::DataSetHeader::GetHeaderStartFilePos(), IsDSHPartiallyRead(), OpenFStream(), affymetrix_calvin_io::DataSetHeaderReader::Read(), and useMemoryMapping.
Referenced by CreateDataSet().
void GenericData::UnmapFile ()
Closes the memory map. Windows only
Definition at line 505 of file GenericData.cpp.
Referenced by Close().
void affymetrix_calvin_io::GenericData::UseMemoryMapping (bool value) [inline]
Sets the file access method when reading data. Set this value before getting the first DataSet or DataGroup. The default is to use memory-mapping.
Parameters:
value If value is true the file will be accessed with memory-mapping, if false, STL fstream will be used
Definition at line 158 of file GenericData.h.
Member Data Documentation
std::ifstream affymetrix_calvin_io::GenericData::fileStream [protected]
fstream file access member
Definition at line 250 of file GenericData.h.
Referenced by Close(), CreateDataSet(), DataGroup(), Open(), and ReadFullDataSetHeader().
affymetrix_calvin_io::FileHeader affymetrix_calvin_io::GenericData::header [protected]
The header and generic header objects
Definition at line 236 of file GenericData.h.
Referenced by ArrayFileIdentifier(), ArrayIdentifier(), Clear(), DataGroupCnt(), DataGroupNames(), FileIdentifier(), and FindDataGroupHeader().
bool affymetrix_calvin_io::GenericData::loadEntireDataSetHint [protected]
Indicates whether DataSets and DataGroups created by GenericData should attempt to read all data into a memory buffer.
Definition at line 253 of file GenericData.h.
Referenced by CreateDataSet(), DataGroup(), and GenericData().
bool affymetrix_calvin_io::GenericData::useMemoryMapping [protected]
Flag that indicates the file access technique; true = use memory-mapping, false = use ifstream
Definition at line 247 of file GenericData.h.
Referenced by Clear(), CreateDataSet(), DataGroup(), GenericData(), Open(), and ReadFullDataSetHeader().
The documentation for this class was generated from the following files:
calvin_files/data/src/GenericData.h
calvin_files/data/src/GenericData.cpp