Affymetrix Power Tools: summaryVis Class Reference
summaryVis Class Reference
Classes
class outputSortCriterion
Class for function predicate, to sort summaryVisOutput by the seqName, then by start position.
class summaryVisOutput
fileRoot Strip path (return root) from input file.
Public Member Functions
summaryVis (int argc, const char *argv[], const std::string &version)
Constructor.
~summaryVis ()
Destructor.
void run ()
Read, process data, write output.
Detailed Description
Definition at line 43 of file SummaryVis.h.
Constructor & Destructor Documentation
summaryVis::summaryVis (int argc, const char * argv[], const std::string & version)
Constructor.
Parameters:
argc Number of command line arguments.
argv Command line arguments.
version Version string.
argc Number of command line arguments.
argv Command line arguments.
version Version string.
Errors: throw exception to display help messages, if too few input files.
Definition at line 166 of file SummaryVis.cpp.
References PgOptions::commandLine(), Err::errAbort(), PgOptions::get(), PgOptions::getArg(), PgOptions::getArgCount(), PgOptions::getBool(), PgOptions::getInt(), PgOpt::getValue(), PgOpt::getValueCount(), PgOptions::mustFindOpt(), Fs::mustOpenToWrite(), PgOptions::parseArgv(), PgOpt::push_user_values_into(), Err::setThrowStatus(), ToStr(), and PgOptions::usage().
Member Function Documentation
void summaryVis::run ()
Read, process data, write output.
Errors: abort if unable to read any input file.
Definition at line 285 of file SummaryVis.cpp.
References Verbose::out().
The documentation for this class was generated from the following files:
chipstream/apt-probeset-summarize/SummaryVis.h
chipstream/apt-probeset-summarize/SummaryVis.cpp