Affymetrix Power Tools: Err Class Reference
Err Class Reference
Err.
#include <Err.h>
Classes
class Param
Utility class for having static parameters across all instances.
Static Public Member Functions
static void setErrorPrefix (const std::string &prefix)
static Param & getParam ()
This function gets around the problem of static variable initialization as local static variables work more consistently.
static void errAbort (const std::string &msg, const std::string &prefix)
Print the message supplied and abort program.
static void errAbort (const std::string &msg)
static void pushHandler (ErrHandler *handler)
Add a new handler for errors.
static ErrHandler * popHandler ()
Pop off the current handler and return it for cleanup, etc.
static void check (bool passed, const char *msg)
errAbort based version of assert with an error message.
static void check (bool passed, const std::string &msg)
errAbort based version of assert with an error message.
static void setThrowStatus (bool doThrow)
Give the current error handler a hint about whether or not to throw exceptions.
static bool getThrowStatus ()
Return true if curerntly configured to throw exceptions on error, false otherwise.
static void configureErrHandler (bool doThrow, bool verbose, bool exitOnError=false, int exitOnErrorValue=-1)
Configure new error handler.
static void setNewLineOnError (bool newline)
Toggle whether we are throwing exceptions or exiting on errors.
static void apt_err_assert (const std::string &file, int line, const std::string &condstr, bool cond, const std::string &msg)
The function called by the APT_ERR_ASSERT macro ///.
static void apt_err_abort (const std::string &file, int line, const std::string &msg)
The function called by the APT_ERR_ABORT macro. ///.
static void setExitOnError (bool val)
Toggle whether to set the value returned when exiting on errors This is primarily used to suppress Windows OS handling of return values indicating an exe did not terminate successfully.
static void setExitOnErrorValue (int val)
Value to return when the flag setExitOnError is true and exiting on errors.
Static Public Attributes
static std::string m_errorPrefix = "FATAL ERROR:"
Detailed Description
Err.
Common abort with message function for programs to call.
Definition at line 60 of file Err.h.
Member Function Documentation
void Err::apt_err_abort (const std::string & file, int line, const std::string & msg) [static]
The function called by the APT_ERR_ABORT macro. ///.
Parameters:
file Filled in from __FILE__ ///
line Filled in from __LINE__ ///
msg The message to abort with
Definition at line 162 of file Err.cpp.
References errAbort(), and ToStr().
void Err::apt_err_assert (const std::string & file, int line, const std::string & condstr, bool cond, const std::string & msg) [static]
The function called by the APT_ERR_ASSERT macro ///.
Parameters:
file Filled in from __FILE__ ///
line Filled in from __LINE__ ///
condstr The string form of the conditional ///
cond The evaluated conditional ///
msg The message to report on an error
Definition at line 148 of file Err.cpp.
References errAbort(), and ToStr().
static void Err::check (bool passed, const std::string & msg) [inline, static]
errAbort based version of assert with an error message.
Parameters:
passed - Condition to be checked.
msg - Error message if failed.
Definition at line 143 of file Err.h.
static void Err::check (bool passed, const char * msg) [inline, static]
errAbort based version of assert with an error message.
Try to use this method in conjunction with a const char * message (rather than constructing a string every time) when writing a check that will be called lots of times.
Parameters:
passed - Condition to be checked.
msg - Error message if failed.
Definition at line 124 of file Err.h.
Referenced by QuantBRLMM::callHaploidSnp(), CelExtract::CelExtract(), QuantBRLMM::computeClusterStats(), affx::ClfFile::defineFileClf(), affx::PgfFile::defineFilePgf(), DmListener::DmListener(), DmListener::fillInQuartet(), affx::ClfFile::getOrder(), affx::ClfFile::getSequential(), QuantBRLMM::makePrior(), affx::PgfFile::open(), affx::ClfFile::open(), QuantMethodGTypeCHPReport::prepare(), QuantMethodExprCHPReport::prepare(), QuantMethodExprCHPReport::QuantMethodExprCHPReport(), QuantMethodGTypeCHPReport::QuantMethodGTypeCHPReport(), CelReader::readFiles(), QuantMethodGTypeChipSummary::report(), and Util::schrageRandom().
void Err::configureErrHandler (bool doThrow, bool verbose, bool exitOnError = false, int exitOnErrorValue = -1) [static]
Configure new error handler.
Parameters:
doThrow - should an exception be thrown, or call exit
verbose - should the error handler call verbose methods
Definition at line 133 of file Err.cpp.
References pushHandler().
Referenced by BaseEngine::parseArgv(), and SocketClient::SocketClient().
void Err::errAbort (const std::string & msg, const std::string & prefix) [static]
Print the message supplied and abort program.
Parameters:
msg - Message for user about what went wrong.
prefix - Prefix to add to the error message.
Definition at line 68 of file Err.cpp.
References getParam(), and Err::Param::m_ErrHandlers.
Referenced by AnalysisInfo::addClientMetaInfo(), AnalysisInfo::addParam(), PgOptions::addPgOpt_nocopy(), PmAdjusterFactory::adjusterForString(), apt_err_abort(), apt_err_assert(), ProbeListFactory::asProbeSet(), RMA::backgroundCorrect(), MultiChannelNonOverlapCelListener::calcLogDiff(), GcAdjust::calcParams(), SignalBackgroundCelListener::calcStats(), HomHiLoCelListener::CalculateEMContrast(), EmGenderCelListener::CalculateEMContrast(), CytogeneticsTrioAnalysis::calculateLODPaternity(), callGenotypes(), QuantBRLMM::callHaploidSnp(), calvinEquiv(), CelExtract::CelExtract(), EngineUtil::checkCelChipTypes(), EngineUtil::checkChipTypeVectors(), MsgSocketHandler::checkForKill(), SelfDoc::Opt::checkOption(), ExportImputeFormatEngine::checkOptionsImp(), ExportDataFilesEngine::checkOptionsImp(), PgOpt::checkParseIsOk(), EngineUtil::checkTsvFileChipType(), ChipStreamFactory::chipStreamForString(), QuantBRLMM::clusterModelFromStrings(), QuantBRLMM::clusterPriorFromStrings(), CNAnalysisMethodFactory::CNAnalysisMethodForString(), CnProbeGenderCelListener::CnProbeGenderCelListener(), TableFile::columnFromFile(), TableFile::columnFromRowFile(), columnNamesForTransformation(), QuantRma::computeEstimate(), QuantPlier::computeEstimate(), QuantLabelZ::computeEstimate(), QuantIterPlier::computeEstimate(), QuantDabg::computeEstimate(), QuantBRLMM::computeEstimate(), AnalysisStreamFactory::constructAnalysisStream(), AnalysisStreamFactory::constructExpressionAnalysisStages(), AnalysisStreamFactory::constructExpressionAnalysisStream(), AnalysisStreamFactory::constructGTypeAnalysisStream(), ContrastCentersStretch(), ContrastExtremesStretch(), convertBgpFile(), File5_Sqlite::copyData(), copyFile5File(), copyRow(), ChipStreamFactory::cStreamForString(), DataStore::DataStore(), DTFactory::dataTransformForString(), AnalysisStreamExpression::doAnalysis(), AnalysisStreamExpPcaSel::doAnalysis(), dumpPgf::dumpPgf(), CalvinToText::error(), CNCychp::error(), SQLiteDatabase::execute(), EngineUtil::explainParameter(), SketchQuantNormTran::extractSketch(), file5Equiv(), FileGenders::FileGenders(), GcAdjust::fillChipBins(), fillInCelFiles(), fillInFile5Files(), fillInHaploidSnps(), fillInHaploidSnpsVersion1(), fillInHaploidSnpsVersion2(), ChipLayout::fillInKillList(), SelfCreate::fillInNameParam(), fillInOptions(), DmListener::fillInQuartet(), fillInTsvFiles(), QuantLabelZ::FindGender(), QuantMethodRunReport::finish(), QuantMethodMultiDataCCCHPReport::finish(), QuantMethodGTypeCHPReport::finish(), QuantMethodExprCHPReport::finish(), QuantMethodExprCCCHPReport::finish(), TmpFileFactory::genDirname(), TmpFileFactory::genFilename_basic(), GenoCallCoder::GenoCallCoder(), EngineUtil::getCdfChipType(), SparseMart::getCelData(), DiskIntensityMart::getCelData(), QuantLabelZ::getConfidence(), QuantBRLMM::getConfidence(), QuantBirdseedv2::getConfidence(), QuantBirdseedv1::getConfidence(), QuantBirdseedDev::getConfidence(), SelfDoc::getDocOption(), QuantMedian::getFeatureEffect(), QuantDabg::getFeatureEffect(), QuantAvgDiff::getFeatureEffect(), SgIoHelper::getFile5Line(), QuantLabelZMulti::getForcedCall(), affx::getGenderString(), GenoSeedTxt::getGenoCalls(), DmListener::getGenoCalls(), QuantLabelZMulti::getGTypeForcedCall(), CNCychp::getGuidFromARRFile(), TableFile::getHeaderValue(), SgIoHelper::getLine(), BaseEngine::getMetaDataDescription(), ChipSummary::getMetric(), ChipSummary::getMetrics(), SnpModelConverter::GetModelHeaders(), SgIoHelper::getNextMarker(), SgIoHelper::getNextMarkerFile5(), SgIoHelper::getNextMarkerTsvSingle(), SgIoHelper::getNextMarkerTwoTsv(), Options::getOpt(), Options::getOptBool(), Options::getOptDouble(), Options::getOptInt(), Options::getOptVector(), IdxGroup::getOthersGroupContainingIdx(), EngineUtil::getPgfChipType(), Options::getPgOpt(), DiskIntensityMart::getProbeCountFromCel(), DataStore::getProbeIntensity(), QuantMedian::getResidual(), QuantAvgDiff::getResidual(), EngineUtil::getSpfChipType(), ChipStream::getTransformedIntensity(), PgOpt::getValue(), MultiChannelNonOverlapCelListener::GimmeContrast(), MultiChannelHomHiLoCelListener::GimmeContrast(), GlobalTmpFileFactory(), affx::GType_from_int(), affx::GType_to_int(), affx::GTypeCallToChpValue(), DataStore::initFromCelFile(), DataStore::initFromDataStore(), DataStore::initFromFile(), GenoCallCoder::initialize(), RmaBgTran::initializeData(), MedNormTran::initializeData(), CNReporter::isSetup(), GcBg::learnParameters(), Calvin::load(), CNLog2RatioData::loadGenderOverrideFile(), CNAnalysisMethodReference::loadLayout(), QuantBRLMM::loadPrior(), loadSNPHints(), QuantBRLMM::loadSnpModels(), QuantBRLMM::loadSnpPriors(), main(), DmListener::makeCall(), makeCelFileSubset(), makeMultiCelFileSubset(), QuantLabelZ::makeNorm(), QuantBRLMM::makePrior(), EngineUtil::makePSetNameSubset(), AnalysisStreamExpression::makeSelectProbesetGroup(), PgOptions::matchOneArg(), matrixDiff(), Util::matrixDifferences(), RowFile::matrixFromFile(), QuantMethodMultiDataCCCHPReport::medianOfPmProbes(), QuantMethodGTypeCHPReport::medianOfPmProbes(), RMA::medianPolishPsetFromMatrix(), RMA::medianPolishWithPrecomputedEffectsOnePass(), RMA::medianPolishWithPrecomputedEffectsUsedAsSeedValues(), MedNormTran::MedNormTran(), MsgStream::message(), midasConfigureRun::midasConfigureRun(), midasEngine::midasEngine(), midasSpliceDetector::midasSpliceDetector(), ChipLayout::mmId(), PgOptions::mustFindOpt(), MultiChannelHomHiLoCelListener::newChip(), DmListener::newChip(), DataStore::newChip(), AdjHomHiLoCelListener::newChip(), SketchQuantNormTran::newChipSuppliedTargetSketch(), CNReferenceMethodAdditionalWaves::newObject(), RmaBgTran::newObject(), QuantAvgDiff::newObject(), PmSumAdjust::newObject(), PmOnlyAdjust::newObject(), MmAdjust::newObject(), GcAdjust::newObject(), RowFile::nextCStringRowExpect(), RowFile::nextLine(), RowFile::nextRowExpect(), DmListener::okForDm(), TableFile::open(), RowFile::open(), LineFile::open(), ChipLayout::openCdf(), affxchpwriter::CCHPFileUpdater::OpenCHPFile(), affymetrix_calvin_io::CalvinCHPFileUpdater::OpenCHPFile(), ChipLayout::openPgf(), QuantMethodFactory::openPrecompFeatureEffects(), SpfReader::openSpf(), ChipLayout::openSpf_v3(), ChipLayout::openSpf_v4(), BaseEngine::openStandardLog(), ChipLayout::parseProbeListRecord(), PmAdjusterFactory::pmAdjusterForString(), PmSumAdjust::pmAdjustment(), MmAdjust::pmAdjustment(), GcAdjust::pmAdjustment(), popHandler(), QuantMethodSamplerReport::prepare(), QuantMethodMultiDataCCCHPReport::prepare(), QuantMethodGTypeCHPReport::prepare(), QuantMethodExprCHPReport::prepare(), QuantMethodExprCCCHPReport::prepare(), Probe::Probe(), AnalysisStreamFactory::probeListFromBgpFile(), ProbesetGenotypeEngine::ProbesetGenotypeEngine(), ProbesetGenotypeStageEngine::ProbesetGenotypeStageEngine(), Options::pushOpt(), QuantMethodFactory::qMethodForString(), QuantBRLMM::QuantBRLMM(), QuantDabg::QuantDabg(), QuantMethodFactory::quantExprMethodForString(), QuantMethodFactory::quantGTypeMethodForString(), RMA::quantileNorm(), QuantLabelZ::QuantLabelZ(), QuantMethodFactory::QuantMethodFactory(), QuantMethodFactory::quantMethodForString(), QuantMethodSqlExprReport::QuantMethodSqlExprReport(), QuantMethod::quantTypeToTxt(), ChipLayout::readCdfProbeSet(), DataStore::readCelFile(), readCopyNumberFile(), TableReader::readFiles(), CelReader::readFiles(), RowFile::readHeader(), GenoSeedTxt::readInPrecompGenoTypes(), MetaProbeset::readMetaProbesetList(), MetaProbeset::readMetaProbesets(), EngineUtil::readProbeClassFile(), EngineUtil::readProbeFile(), ChipLayout::readProbeListCdfFileKillList(), ChipLayout::readProbeListPgfFileKillList(), EngineUtil::readProbeSetFile(), MetaProbeset::readProbesetSubset(), QCAnalysisOptions::readQCAFile(), QCProbesetOptions::readQCCFile(), ArtifactReduction::readReferenceProfileFromFile(), SketchQuantNormTran::readTargetSketchFromFile(), AnalysisStreamExpPcaSel::registerChipStreamObjs(), QuantBRLMM::removeHetFromPrior(), QuantMethodSqlGTypeReport::report(), QuantMethodSqlExprReport::report(), QuantMethodSamplerReport::report(), QuantMethodMultiDataCCCHPReport::report(), QuantMethodGTypeReport::report(), QuantMethodGTypeExprChipSummary::report(), QuantMethodGTypeCHPReport::report(), QuantMethodGTypeChipSummary::report(), QuantMethodExprReport::report(), QuantMethodExprCHPReport::report(), QuantMethodExprChipSummary::report(), QuantMethodExprCCCHPReport::report(), MultiQuantMethodListener::report(), QuantMethodGTypeCHPReport::reportFailure(), QuantMethodExprCHPReport::reportFailure(), QuantMethodExprCCCHPReport::reportFailure(), SparseMart::reserve(), RmaBgTran::RmaBgTran(), CNReporterCnchp::run(), CNLog2RatioAdjustmentMethodWaveCorrection::run(), CNFamilialAnalysisMethodLOD::run(), ExportImputeFormatEngine::runImp(), ExportDataFilesEngine::runImp(), midasSpliceDetector::runMidasMultiple(), midasSpliceDetector::runMidasSingle(), QuantMethod::scaleToTxt(), QuantLabelZ::SelectGoodProbes(), SelfCreate::selfCreateFromString(), PgOptions::set(), setBgpFile(), DmListener::setDefaultCallIndex(), DmListener::setDefaultChrXCallIndex(), SelfDoc::setDocOptions(), FsPath::setErr(), Fs::setErr(), Options::setOpt(), PgOptions::setOptionsFromXMLFile(), SelfDoc::setOptValue(), SketchQuantNormTran::setParameters(), QuantMethod::setParameters(), QuantLabelZ::setParameters(), QuantBirdseed::setParameters(), PmAdjuster::setParameters(), DataStore::setProbeOrder(), AnalysisStreamGType::setQuantMethod(), AnalysisStreamExpression::setQuantMethod(), SketchQuantNormTran::setTargetSketch(), QuantRma::setUp(), QuantPlierBase::setUp(), QuantLabelZMulti::setUp(), QuantLabelZ::setUp(), QuantDabg::setUp(), QuantBRLMM::setUp(), QuantBirdseed::setUp(), QuantMethodFactory::setupQuantMethodFactory(), QuantRma::setUsePrecompFeatureEffects(), QuantPlierBase::setUsePrecompFeatureEffects(), SgIoHelper::SgIoHelper(), SocketServer::SocketServer(), ARRSAXHandler::startElement(), QuantBRLMM::stringForTransformation(), stringForTransformation(), Probe::stringForType(), summaryVis::summaryVis(), Convert::toBool(), Convert::toDouble(), Convert::toFloat(), Convert::toInt(), Convert::toUnsignedInt(), Convert::toUnsignedInt64(), SketchQuantNormTran::transform(), RmaBgTran::transform(), QuantBRLMM::transformationForString(), transformationForString(), tsv_util_paste(), tsv_util_paste_basic(), tsvJoin::tsvJoin(), ChipLayout::typeFromCdfType(), valueForTransformation(), TableFile::write(), and QuantLabelZ::writeSnpPosteriorTsv().
Err::Param & Err::getParam () [static]
This function gets around the problem of static variable initialization as local static variables work more consistently.
Returns:
Param - Our static parameters for this class.
Definition at line 54 of file Err.cpp.
Referenced by errAbort(), getThrowStatus(), popHandler(), pushHandler(), setExitOnError(), setExitOnErrorValue(), setNewLineOnError(), and setThrowStatus().
ErrHandler * Err::popHandler () [static]
Pop off the current handler and return it for cleanup, etc.
Returns:
- last handler pushed onto the stack.
Definition at line 93 of file Err.cpp.
References errAbort(), getParam(), and Err::Param::m_ErrHandlers.
Referenced by BaseEngine::checkDiskSpace(), BaseEngine::checkOptions(), and BaseEngine::run().
void Err::pushHandler (ErrHandler * handler) [static]
Add a new handler for errors.
Parameters:
handler - Pointer to handler to call when things go wrong.
Definition at line 85 of file Err.cpp.
References getParam(), and Err::Param::m_ErrHandlers.
Referenced by configureErrHandler().
void Err::setExitOnError (bool val) [static]
Toggle whether to set the value returned when exiting on errors This is primarily used to suppress Windows OS handling of return values indicating an exe did not terminate successfully.
if val is true, the value in setExitOnErrorValue will be returned.
Definition at line 177 of file Err.cpp.
References getParam(), Err::Param::m_ErrHandlers, ErrHandler::setExitOnError(), and Verbose::warn().
Referenced by SocketClient::SocketClient().
void Err::setNewLineOnError (bool newline) [static]
Toggle whether we are throwing exceptions or exiting on errors.
Parameters:
doThrow - if true exceptions will be thrown, if false exit(1) called.
Definition at line 144 of file Err.cpp.
References getParam(), and Err::Param::m_NewLineOnError.
Referenced by SocketClient::SocketClient().
void Err::setThrowStatus (bool doThrow) [static]
Give the current error handler a hint about whether or not to throw exceptions.
Note that this is just a hint and that if a specifical behavior is really required it is best to push a custom error handler onto the stack.
Parameters:
doThrow - if true requesting exceptions to be thrown, if false not to be thrown
Definition at line 111 of file Err.cpp.
References getParam(), Err::Param::m_ErrHandlers, and ErrHandler::setThrows().
Referenced by CallSetTest::addCallElement(), MatrixCheck::check(), BaseEngine::checkDiskSpace(), SelfDoc::Opt::checkOption(), BaseEngine::checkOptions(), TranslationTableModelTest::constructor(), CopyNumberTableModelTest::constructor(), CallSetTest::describeVerbose(), dumpPgf::dumpPgf(), main(), AAOptionsTest::noOptions(), CallSetTest::operator_equal(), BaseEngine::run(), SocketClient::SocketClient(), summaryVis::summaryVis(), translateEngineMessageHandlingCallBack(), and tsvJoin::tsvJoin().
The documentation for this class was generated from the following files:
util/Err.h
util/Err.cpp