Affymetrix Power Tools: affymetrix_chp_converter::CHPFileConvertToCalvin Class Reference
affymetrix_chp_converter::CHPFileConvertToCalvin Class Reference
#include <CHPFileConvertToCalvin.h>
Public Member Functions
CHPFileConvertToCalvin ()
~CHPFileConvertToCalvin ()
void SetArrayID (const char *str)
void SetArrayBarcode (const wchar_t *str)
void SetParentFileName (const char *str)
void SetExtraParameters (const affymetrix_calvin_parameter::ParameterNameValueTypeVector *params)
CHPFileConverterErrorCode ErrorCode () const
bool ConvertXDAFile (const char *fileName, const char *libPath, const char *newFile)
bool ConvertMas5File (const char *fileName, const char *celFile, const char *libPath, const char *maskFile, const char *newFile)
bool ValidateXDAFile (const char *fileName, const char *libPath, const char *newFile)
bool ValidateMas5File (const char *fileName, const char *celFile, const char *libPath, const char *maskFile, const char *newFile)
bool ComputeBackgroundZoneInfo (FusionCELData &celData, const char *libPath, AllZonesInfoType &zonesInfo) const
bool ComputeBackgroundZoneInfo (FusionCELData &celData, const char *libPath, const char *maskPath, AllZonesInfoType &zonesInfo) const
Protected Member Functions
void FillParentGenericDataHeader (affymetrix_calvin_io::GenericDataHeader &hdr)
bool GetParentGenericDataHeader (affymetrix_calvin_io::GenericDataHeader &hdr)
void AddExtraParameters (affymetrix_calvin_io::CHPData &data)
bool CheckAlgorithmType (const std::string &algorithmName)
Detailed Description
This class will convert a CHP file to Calvin format.
Definition at line 40 of file CHPFileConvertToCalvin.h.
Constructor & Destructor Documentation
CHPFileConvertToCalvin::CHPFileConvertToCalvin ()
Constructor
Definition at line 60 of file CHPFileConvertToCalvin.cpp.
CHPFileConvertToCalvin::~CHPFileConvertToCalvin ()
Destructor
Definition at line 77 of file CHPFileConvertToCalvin.cpp.
Member Function Documentation
void CHPFileConvertToCalvin::AddExtraParameters (affymetrix_calvin_io::CHPData & data) [protected]
Adds any extra parameters from the extraParameter collection to the file header.
Parameters:
data The target CHPData.
Definition at line 774 of file CHPFileConvertToCalvin.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), and affymetrix_calvin_io::CHPData::GetFileHeader().
Referenced by ConvertMas5File(), and ConvertXDAFile().
bool CHPFileConvertToCalvin::CheckAlgorithmType (const std::string & algorithmName) [protected]
Checks that conversion is supported based on the algorithm name.
Parameters:
algorithmName The algorithm name. ExpressionCall, ExpressionStat etc.
Returns:
True if conversion of a CHP based on the indicated algorithm is supported.
Definition at line 788 of file CHPFileConvertToCalvin.cpp.
Referenced by ConvertMas5File(), and ConvertXDAFile().
bool CHPFileConvertToCalvin::ComputeBackgroundZoneInfo (FusionCELData & celData, const char * libPath, const char * maskPath, AllZonesInfoType & zonesInfo) const
Compute the zone background for an expression array.
Parameters:
celData An open FusionCELData object.
libPath The path of the library folder.
maskPath The full name of the mask file. If there is no mask file, it can be NULL.
zonesInfo Receives the results of the background computation.
Returns:
True if the background was successully computed, otherwise false.
Definition at line 361 of file CHPFileConvertToCalvin.cpp.
bool CHPFileConvertToCalvin::ComputeBackgroundZoneInfo (FusionCELData & celData, const char * libPath, AllZonesInfoType & zonesInfo) const
Compute the zone background for an expression array.
Parameters:
celData An open FusionCELData object.
libPath The path of the library folder.
zonesInfo Receives the results of the background computation.
Returns:
True if the background was successully computed, otherwise false.
Definition at line 354 of file CHPFileConvertToCalvin.cpp.
Referenced by ConvertMas5File().
bool CHPFileConvertToCalvin::ConvertMas5File (const char * fileName, const char * celFile, const char * libPath, const char * maskFile, const char * newFile)
Convert a non-XDA file to Calvin format.
Parameters:
fileName The full name of the CHP file.
celFile The full name of the CEL file.
libPath The path of the library folder.
maskFile The full name of the mask file. If there is no mask file, it can be NULL.
newFile The name of the new CHP file.
Returns:
True if successful.
Definition at line 540 of file CHPFileConvertToCalvin.cpp.
References AddExtraParameters(), affymetrix_calvin_io::GenericDataHeader::AddParent(), CheckAlgorithmType(), ComputeBackgroundZoneInfo(), affymetrix_fusion_io::FusionCELData::Exists(), FillParentGenericDataHeader(), affymetrix_calvin_io::Genotyping, affxchp::CCHPFileHeader::GetAlgName(), affxchp::CCHPFileHeader::GetAssayType(), affxchp::CResequencingResults::GetCalledBasesSize(), affxchp::CCHPFileData::GetExpressionResults(), affymetrix_calvin_io::CHPData::GetFileHeader(), affxchp::CResequencingResults::GetForceCallsSize(), affxchp::CCHPFileData::GetHeader(), affxchp::CCHPFileHeader::GetNumProbeSets(), affxchp::CResequencingResults::GetOrigCallsSize(), affxchp::CCHPFileData::GetResequencingResults(), affxchp::CExpressionProbeSetResults::m_HasCompResults, affymetrix_fusion_io::FusionCELData::Read(), affymetrix_calvin_io::CHPData::SetBackgroundZoneCnt(), affymetrix_calvin_io::CHPData::SetEntryCount(), affymetrix_fusion_io::FusionCELData::SetFileName(), affxchp::CCHPFileData::SetFileName(), affymetrix_calvin_io::CHPData::SetForceCnt(), affymetrix_calvin_io::CHPData::SetOrigCnt(), and affymetrix_calvin_io::CHPData::SetParentCell().
bool CHPFileConvertToCalvin::ConvertXDAFile (const char * fileName, const char * libPath, const char * newFile)
Convert the XDA file to Calvin format.
Parameters:
fileName The full path name of the CHP file.
newFile The name of the new CHP file.
Returns:
True if successful.
Definition at line 396 of file CHPFileConvertToCalvin.cpp.
References AddExtraParameters(), affymetrix_calvin_io::GenericDataHeader::AddParent(), CheckAlgorithmType(), FillParentGenericDataHeader(), affymetrix_calvin_io::Genotyping, affxchp::CCHPFileHeader::GetAlgName(), affxchp::CCHPFileHeader::GetAssayType(), affxchp::CCHPFileHeader::GetBackgroundZones(), affxchp::CResequencingResults::GetCalledBasesSize(), affxchp::CCHPFileData::GetExpressionResults(), affymetrix_calvin_io::CHPData::GetFileHeader(), affxchp::CResequencingResults::GetForceCallsSize(), affxchp::CCHPFileData::GetHeader(), affxchp::CCHPFileHeader::GetNumProbeSets(), affxchp::CResequencingResults::GetOrigCallsSize(), affxchp::CCHPFileData::GetResequencingResults(), affxchp::CExpressionProbeSetResults::m_HasCompResults, affymetrix_calvin_io::CHPData::SetBackgroundZoneCnt(), affymetrix_calvin_io::CHPData::SetEntryCount(), affxchp::CCHPFileData::SetFileName(), affymetrix_calvin_io::CHPData::SetForceCnt(), affymetrix_calvin_io::CHPData::SetOrigCnt(), and affymetrix_calvin_io::CHPData::SetParentCell().
CHPFileConverterErrorCode affymetrix_chp_converter::CHPFileConvertToCalvin::ErrorCode () const [inline]
Gets the error code for the conversion process.
Returns:
The error code associated with the last failure.
Definition at line 73 of file CHPFileConvertToCalvin.h.
void CHPFileConvertToCalvin::FillParentGenericDataHeader (affymetrix_calvin_io::GenericDataHeader & hdr) [protected]
Fills the GenericDataHeader with the parent file header which it gets either from the parent file or generates based on the GCOS CEL file.
Parameters:
hdr The GenericDataHeader that will be filled with the parent file header information.
inFile The GCOS CEL file.
Definition at line 736 of file CHPFileConvertToCalvin.cpp.
References GetParentGenericDataHeader().
Referenced by ConvertMas5File(), and ConvertXDAFile().
bool CHPFileConvertToCalvin::GetParentGenericDataHeader (affymetrix_calvin_io::GenericDataHeader & hdr) [protected]
Gets the GenericDataHeader from the parent Command Console file. The arrayID member is ignored.
Parameters:
hdr The GenericDataHeader that will be filled with the parent file information.
Returns:
True if the parent file GenericDataHeader information was found.
Definition at line 748 of file CHPFileConvertToCalvin.cpp.
References affymetrix_calvin_io::CelFileData::GetFileHeader(), affymetrix_calvin_io::CelFileReader::Read(), and affymetrix_calvin_io::CelFileReader::SetFilename().
Referenced by FillParentGenericDataHeader().
void affymetrix_chp_converter::CHPFileConvertToCalvin::SetArrayBarcode (const wchar_t * str) [inline]
Set the array barcode.
Parameters:
str The array barcode.
Definition at line 58 of file CHPFileConvertToCalvin.h.
void affymetrix_chp_converter::CHPFileConvertToCalvin::SetArrayID (const char * str) [inline]
Set the physical array id.
Parameters:
str The physical array id.
Definition at line 53 of file CHPFileConvertToCalvin.h.
void affymetrix_chp_converter::CHPFileConvertToCalvin::SetExtraParameters (const affymetrix_calvin_parameter::ParameterNameValueTypeVector * params) [inline]
Set extra parameters that are to be written to the file.
Parameters:
params A collection of ParameterNameValueTypes to add to the file.
Definition at line 68 of file CHPFileConvertToCalvin.h.
void affymetrix_chp_converter::CHPFileConvertToCalvin::SetParentFileName (const char * str) [inline]
The full path and name of the parent file.
Parameters:
str The full path and name of the parent file.
Definition at line 63 of file CHPFileConvertToCalvin.h.
bool CHPFileConvertToCalvin::ValidateMas5File (const char * fileName, const char * celFile, const char * libPath, const char * maskFile, const char * newFile)
Validate the conversion of a non-XDA file to Calvin format.
Parameters:
fileName The full name of the CHP file.
celFile The full name of the CEL file.
libPath The path of the library folder.
maskFile The full name of the mask file. If there is no mask file, it can be NULL.
newFile The name of the new CHP file.
Returns:
True if the validation was successful. If false is returned, call ErrorCode.
Definition at line 833 of file CHPFileConvertToCalvin.cpp.
References affymetrix_fusion_io::FusionCDFData::Exists(), affymetrix_fusion_io::FusionCELData::Exists(), affxchp::CCHPFileHeader::GetAssayType(), affymetrix_fusion_io::FusionCELData::GetChipType(), affxchp::CCHPFileData::GetHeader(), Fs::join(), affymetrix_fusion_io::FusionCELData::ReadHeader(), affxchp::CCHPFileData::ReadHeader(), affymetrix_fusion_io::FusionCDFData::SetFileName(), affymetrix_fusion_io::FusionCELData::SetFileName(), and affxchp::CCHPFileData::SetFileName().
bool CHPFileConvertToCalvin::ValidateXDAFile (const char * fileName, const char * libPath, const char * newFile)
Validate the conversion of an XDA file to Calvin format.
Parameters:
fileName The full path name of the CHP file.
newFile The name of the new CHP file.
Returns:
True if the validation was successful. If false is returned, call ErrorCode.
Definition at line 802 of file CHPFileConvertToCalvin.cpp.
References affxchp::CCHPFileData::ReadHeader(), and affxchp::CCHPFileData::SetFileName().
The documentation for this class was generated from the following files:
calvin_files/converters/chp/src/CHPFileConvertToCalvin.h
calvin_files/converters/chp/src/CHPFileConvertToCalvin.cpp