Affymetrix Power Tools: CelReader Class Reference
CelReader Class Reference
Class for reading cel files and passing the data to memory representation and analysis objects.
#include <CelReader.h>