Affymetrix Power Tools: ArtifactReduction Class Reference
ArtifactReduction Class Reference
ArtifactReduction for doing normalization.
#include <ArtifactReduction.h>