Affymetrix Power Tools: midasSpliceDetector Class Reference
midasSpliceDetector Class Reference
midasSpliceDetector
#include <MidasSpliceDetector.h>
Public Member Functions
midasSpliceDetector (const std::vector< int > &groups, int wantPvalues, int wantFstats, int wantNormalized, const float &logStabilize, int noLogTransform)
Constructor.
void runMidasSingle (const std::vector< float > &exonData, const std::vector< float > &geneData, float *fstat, std::vector< float > *normalizedSignal, float *pvalue)
Calculates stats on single exon, gene data.
void runMidasMultiple (const std::vector< std::vector< float > > &exonData, const std::vector< float > &geneData, std::vector< float > *fstat, std::vector< std::vector< float > > *normalizedSignal, std::vector< float > *pvalue)
Calculates stats on multiple exons, gene data.
Detailed Description
midasSpliceDetector
Object for Midas, Microarray Detection of Alternative Splicing.
Performs one-way ANOVA to detect alternative spliced cassette exons from exon array data. See the white paper 'Alternative Analysis Methods for Exon Arrays' for a detailed description of the method.
The constructor midasSpliceDetector() has input parameter a vector of integers, e.g., [ 1 1 1 2 2 3 ], one for each microarray scan, describing the experimental groups. These can be in any order and need not be consecutive; [ 2 1 1 5 7 7 3 ] is valid. The order of group ids matches the order of the exon and gene data passed to runMidas.
Subsequent data analysis can be performed either on a single or multiple exon basis. For processing a single exon, the caller provides a vector of floats, one entry per scan, of exon data, and another vector of floats of gene data. These may be produced by an earlier Plier run and must be of the same size as the groups vector. RunMidas calculates the F statistic, normalized signal, and p value for this exon. The normalized signal, based on a log value, is a normalized measure of how much exon specific expression differs between groups; it is returned as a vector of floats, of the same dimension as the exon and gene input. The midasSpliceDetector output is returned by reference to lvalues allocated by the caller.
For processing multiple exons, the caller provides a vector of vectors of exon data, one vector for each exon, and one vector of gene data; all exons are compared with the single gene data vector. Output is returned as a vector of F statistics, one entry per exon, a vector of vectors of normalized exon signal, one vector per exon of length the number of scans, and a vector of p values, one entry per exon. Here also, output is returned by reference to lvalues allocated by the caller.
The caller may choose not to receive one or more of the outputs; this is signaled by flags passed to the constructor.
Definition at line 81 of file MidasSpliceDetector.h.
Constructor & Destructor Documentation
midasSpliceDetector::midasSpliceDetector (const std::vector< int > & groups, int wantPvalues, int wantFstats, int wantNormalized, const float & logStabilize, int noLogTransform)
Constructor.
Parameters:
groups Experimental groups.
wantPvalues Caller requests p values.
wantFstats Caller requests F statistics.
wantNormalized Caller requests normalized exon signal.
logStabilize Amount to add to data before taking logarithm.
noLogTransform Do not log transform data.
Translates group ids into offsets into list of unique ids, builds full, reduced design matrices.
Parameters:
groups Vector of experimental group ids.
wantPvalues Caller requests p values.
wantFstats Caller requests F statistics.
wantNormalized Caller requests normalized exon signal.
logStabilize Amount to add to data before taking logarithm.
noLogTransform Do not log transform data.
Errors: call errAbort if all requested output flags are false.
Definition at line 55 of file MidasSpliceDetector.cpp.
References Err::errAbort().
Member Function Documentation
void midasSpliceDetector::runMidasMultiple (const std::vector< std::vector< float > > & exonData, const std::vector< float > & geneData, std::vector< float > * fstat, std::vector< std::vector< float > > * normalizedSignal, std::vector< float > * pvalue)
Calculates stats on multiple exons, gene data.
Process multiple exons, single gene data.
Parameters:
exonData Multiple exon data.
geneData Gene data.
fstat returned F statistic vector
normalizedSignal returned vector of vectors of normalized exon signal
pvalue returned P values vector
Invokes the single exon, gene data runMidas for each exon in the input vector of vectors. Produce vector of fstat and pvalue results, vector of vector of normalizedSignal results.
Errors: call errAbort if the respective output requested flag is set, and the fstat, normalizedSignal, and pvalue vectors are not each equal in size to that of the exon vector.
Parameters:
exonData Exon data as a vector of vectors.
geneData Gene data as a vector.
Returns:
fstat F statistics as a vector.
normalizedSignal(s) as a vector of vectors.
pvalue P values as a vector.
Definition at line 176 of file MidasSpliceDetector.cpp.
References Err::errAbort(), and runMidasSingle().
void midasSpliceDetector::runMidasSingle (const std::vector< float > & exonData, const std::vector< float > & geneData, float * fstat, std::vector< float > * normalizedSignal, float * pvalue)
Calculates stats on single exon, gene data.
Process single exon, gene data.
Parameters:
exonData Single exon data.
geneData Gene data.
fstat F statistic.
normalizedSignal Vector of normalized exon signal.
pvalue P value.
Matlab: Do a 1-way ANOVA testing for no sample effects. model tests: log (exon signal) - log (gene signal) = constant against log (exon signal) - log (gene signal) = constant + sample effect
Output: (1) fstat: for this nexon, the F-statistic on dfModel (reduced design) numerator degrees of freedom and df1 (full design) denominator degrees of freedom. (2) normalizedSignal: a vector of nscans normalized exon signal. Each vector is relative to the nexon, max is 0. Within groups the values are the same. (3) pvalue: p-value corresponding to the f statistic. The output normalizedSignal vector is preallocated by the caller.
Errors: call errAbort if the exon and gene data vectors are not both equal in size to the count N of group ids (scans). If normalizedSignal output is requested, call errAbort if the normalizedSignal vector is not equal in size to the count N of group ids.
Parameters:
exonData Exon data.
geneData Gene data.
Returns:
fstat F statistic.
normalizedSignal Vector of normalized exon signals.
pvalue P value.
Definition at line 113 of file MidasSpliceDetector.cpp.
References Err::errAbort(), and affxstat::Ftest().
Referenced by runMidasMultiple().
The documentation for this class was generated from the following files:
midas/MidasSpliceDetector.h
midas/MidasSpliceDetector.cpp