Affymetrix Power Tools: QuantDabg Class Reference
QuantDabg Class Reference
Class for doing Detected Above BackGround (DABG) analysis.
#include <QuantDabg.h>