Affymetrix Power Tools: CNAnalysisMethodAllelicDifferenceCytoScan Class Reference
CNAnalysisMethodAllelicDifferenceCytoScan Class Reference
The AllelicDifference analysis method - the CytoScan variation.
#include <CNAnalysisMethodAllelicDifferenceCytoScan.h>