Affymetrix Power Tools: affymetrix_comparer::CHPCompareCalvintoCalvin Class Reference
affymetrix_comparer::CHPCompareCalvintoCalvin Class Reference
#include <CHPCompareCalvintoCalvin.h>
Public Member Functions
void Clear ()
bool CompareFiles (const char *file1, const char *file2)
std::string Differences () const
Detailed Description
Provides for information about CHP file versions.
Definition at line 38 of file CHPCompareCalvintoCalvin.h.
Member Function Documentation
void CHPCompareCalvintoCalvin::Clear ()
Clears the members.
Definition at line 38 of file CHPCompareCalvintoCalvin.cpp.
References affymetrix_calvin_io::CHPData::Clear().
Referenced by CompareFiles().
bool CHPCompareCalvintoCalvin::CompareFiles (const char * file1, const char * file2)
Determines the version number of the file.
Parameters:
file1 The first file.
file2 The second file.
Returns:
True if identical.
Definition at line 70 of file CHPCompareCalvintoCalvin.cpp.
References Clear().
std::string affymetrix_comparer::CHPCompareCalvintoCalvin::Differences () const [inline]
The differences between the files.
Returns:
A string representation of the differences.
Definition at line 105 of file CHPCompareCalvintoCalvin.h.
Referenced by affymetrix_comparer::CHPComparer::CompareFiles().
The documentation for this class was generated from the following files:
calvin_files/converters/chp/comparer/CHPCompareCalvintoCalvin.h
calvin_files/converters/chp/comparer/CHPCompareCalvintoCalvin.cpp