Affymetrix Power Tools: QuantPlier Class Reference
QuantPlier Class Reference
Class for doing probe set quantification using the PLIER (Probe Logarithmic Error Intensity Estimate) method.
#include <QuantPlier.h>