Affymetrix Power Tools: util/Convert.h File Reference
Convert.h File Reference
Utility functions for converting between types.
#include "portability/affy-base-types.h"
#include <cmath>
#include <cstring>
#include <sstream>
#include <string>
#include <vector>
Classes
class Convert
Convert.
Functions
template<class T >
std::string ToStr (const T &t)
Little template function to make string conversion easy.
std::string ToStr (const std::string &str)
Convert the arg to a string. ///.
std::string ToStr (double t)
std::string ToStr (float t)
Detailed Description
Utility functions for converting between types.
Author:
Chuck Sugnet
Date:
Wed May 4 14:53:03 2005
Definition in file Convert.h.
Function Documentation
template<class T > std::string ToStr (const T & t)
Little template function to make string conversion easy.
this isn't the fastest way to do things, but it is easy.
Definition at line 245 of file Convert.h.
Referenced by GenoCallCoder::abstractAlleleIntegersToGenotypeCallNum(), SocketServer::acceptNewConnection(), IdxGroup::addGroup(), AnalysisStreamExpPcaSel::AnalysisStreamExpPcaSel(), Err::apt_err_abort(), Err::apt_err_assert(), apt_falcon_merge_plf2plf_nonas(), ProbeListFactory::asProbeSet(), BaseEngine::BaseEngine(), ProbeListFactory::buildProbeId2ApidIndex(), MultiChannelNonOverlapCelListener::calcCrossThreshold(), MultiChannelNonOverlapCelListener::calcNonOverlap(), VariabilityScoreCelListener::calcStats(), SignalBackgroundCelListener::calcStats(), HomHiLoCelListener::CalculateEMContrast(), EmGenderCelListener::CalculateEMContrast(), callGenotypes(), QuantBRLMM::callHaploidSnp(), calvinEquiv(), QuantGTypeMethod::canSetUpProbeSet(), CelExtract::CelExtract(), MixedFileCheck::check(), MatrixCheck::check(), CalvinChpCheck::check(), ModelFileHeaderCheck::check(), ModelFileValidCheck::check(), EngineUtil::checkCelChipTypes(), CelCheck::checkFilePair(), RegressionCheck::checkFloat(), SocketUtil::checkForMsgs(), SelfDoc::Opt::checkOption(), ExportImputeFormatEngine::checkOptionsImp(), ExportDataFilesEngine::checkOptionsImp(), ChipStreamFactory::chipStreamForString(), ChipStreamFactory::chipStreamForStringBoard(), QuantBRLMM::clusterModelFromStrings(), QuantBRLMM::clusterPriorFromStrings(), TableFile::columnFromFile(), TableFile::columnFromRowFile(), columnNamesForTransformation(), QuantPlier::computeEstimate(), QuantLabelZMulti::computeEstimate(), QuantLabelZ::computeEstimate(), QuantIterPlier::computeEstimate(), HomHiLoCelListener::computeStatistic(), AnalysisStreamFactory::constructExpressionAnalysisStream(), convertBgpFile(), File5_Sqlite::copyData(), copyFile5File(), copyRow(), copyTsvFile(), ProbeSetGroup::countPmProbes(), QCMethod::createCelListener(), CelExtract::defineExtractTsv(), AnalysisStreamExpSpectSel::doAnalysis(), AnalysisStreamExpression::doAnalysis(), AnalysisStreamExpPcaSel::doAnalysis(), AnalysisStream::doAnalysis(), CelExtract::doProbeSet(), doRma(), IdxGroup::elementIdxRequire(), ProbeListFactory::ensureSortedName2Idx(), affx::File5_File::equivalent(), EngineUtil::explainParameter(), affx::TsvFile::f_advance_tabs(), file5Equiv(), FileGenders::FileGenders(), SocketBase::fillBufferFromSocket(), GcAdjust::fillChipBins(), fillInCelFiles(), fillInFile5Files(), FileTranslation::fillInFromProbeSets(), fillInHaploidSnpsVersion1(), fillInHaploidSnpsVersion2(), ChipLayout::fillInKillList(), SelfCreate::fillInNameParam(), fillInOptions(), DmListener::fillInQuartet(), fillInTsvFiles(), QuantMethodRunReport::finish(), QuantMethodMultiDataCCCHPReport::finish(), QuantMethodGTypeCHPReport::finish(), QuantMethodExprCHPReport::finish(), QuantMethodExprCCCHPReport::finish(), CNAnalysisMethodCN::fwdback(), GcBg::GcBg(), GenoCallCoder::genotypeCallNumToAbstractAllele(), GenoCallCoder::genotypeCallNumVecToAbstractAlleleVec(), QuantLabelZ::getCallProbabilities(), TranslationTableModel::getColumnIndex(), QuantLabelZ::getConfidence(), QuantBRLMM::getConfidence(), QuantBirdseedv2::getConfidence(), QuantBirdseedv1::getConfidence(), QuantBirdseedDev::getConfidence(), SelfDoc::getDocOption(), getDouble(), SgIoHelper::getFile5Line(), QuantLabelZMulti::getForcedCall(), QuantLabelZMulti::getGTypeForcedCall(), SgIoHelper::getLine(), ChipSummary::getMetric(), ChipSummary::getMetrics(), SnpModelConverter::GetModelHeaders(), QuantBRLMM::getModelString(), IdxGroup::getOthersGroupContainingIdx(), DiskIntensityMart::getProbeIntensity(), DataStore::getProbeIntensity(), SnpClusterStore::getSnpCluster(), MultiChannelHomHiLoCelListener::GimmeContrast(), affx::TsvFile::gotoLine(), IdxGroup::groupIdxRequire(), affx::GTypeCallToChpValue(), SocketTextHandler::handleMessage(), affx::TsvFile::headers_to_fields_v2(), CNAnalysisMethodCN::hmm(), GenoCallCoder::initialize(), RmaBgTran::initializeData(), MedNormTran::initializeData(), SocketHandler::isEscaped(), GcBg::learnParameters(), affx::TsvFileField::linkedvars_assign(), affx::TsvFile::linkvar_link(), QuantBRLMM::loadPrior(), loadSNPHints(), QuantBRLMM::loadSnpModels(), QuantBRLMM::loadSnpPriors(), main(), DmListener::makeCall(), makeMultiCelFileSubset(), QuantBRLMM::makePrior(), AnalysisStreamExpression::makeSelectProbesetGroup(), Util::matrixDifferences(), MedNormTran::MedNormTran(), MsgSocketHandler::message(), ChipLayout::mmId(), VariabilityScoreCelListener::newChip(), SignalBackgroundCelListener::newChip(), MultiChannelNonOverlapCelListener::newChip(), MultiChannelHomHiLoCelListener::newChip(), HomHiLoCelListener::newChip(), DmListener::newChip(), DataStore::newChip(), SketchQuantNormTran::newChipSuppliedTargetSketch(), SketchQuantNormTran::newDataSet(), RmaBgTran::newObject(), QuantAvgDiff::newObject(), PmSumAdjust::newObject(), PmOnlyAdjust::newObject(), MmAdjust::newObject(), GcAdjust::newObject(), ArtifactReduction::newObject(), RowFile::nextCStringRowExpect(), RowFile::nextLine(), RowFile::nextRowExpect(), DmListener::okForDm(), TableFile::open(), SQLiteRecordset::open(), SQLiteDatabase::open(), affx::TsvFile::open(), ChipLayout::openCdf(), affxchpwriter::CCHPFileUpdater::OpenCHPFile(), affymetrix_calvin_io::CalvinCHPFileUpdater::OpenCHPFile(), ChipLayout::openPgf(), QuantMethodFactory::openPrecompFeatureEffects(), SpfReader::openSpf(), ChipLayout::openSpf(), ChipLayout::openSpf_v3(), ChipLayout::openSpf_v4(), DmetEngine::parseArgv(), SocketBase::parseMsgFromBuffer(), ChipLayout::parseProbeListRecord(), RegressionTest::pass(), GcAdjust::pmAdjustment(), CNAnalysisMethodCN::postProcessHMM(), CNAnalysisEngine::postProcessing(), QuantMethodMultiDataCCCHPReport::prepare(), QuantMethodGTypeReport::prepare(), QuantMethodGTypeCHPReport::prepare(), QuantMethodExprCHPReport::prepare(), QuantMethodExprCCCHPReport::prepare(), QuantLabelZ::prepare(), affx::TsvFile::printBindingErrors(), Probe::Probe(), AnalysisStreamFactory::probeListFromBgpFile(), TranslationTableModel::probeSetFilter(), CNReferenceEngine::processData(), MsgSocketHandler::progressBegin(), ProgressDot::progressEnd(), MsgSocketHandler::progressEnd(), MsgSocketHandler::progressStep(), Options::pushOpt(), QuantBirdseedDev::QuantBirdseedDev(), QuantBirdseedv2::QuantBirdseedv2(), QuantBRLMM::QuantBRLMM(), QuantDabg::QuantDabg(), QuantLabelZ::QuantLabelZ(), QuantMedian::QuantMedian(), QuantMethodExprChipSummary::QuantMethodExprChipSummary(), QuantMethodExprCHPReport::QuantMethodExprCHPReport(), QuantMethodFactory::QuantMethodFactory(), QuantMethodFactory::quantMethodForString(), QuantMethodSqlExprReport::QuantMethodSqlExprReport(), QuantRma::QuantRma(), QuantMethod::quantTypeToTxt(), ChipLayout::readCdfProbe(), ChipLayout::readCdfProbeSet(), DataStore::readCelFile(), readCopyNumberFile(), TableReader::readFiles(), CelReader::readFiles(), RowFile::readHeader(), GenoSeedTxt::readInPrecompGenoTypes(), MetaProbeset::readMetaProbesetList(), MetaProbeset::readMetaProbesets(), QuantMethodFactory::readPrecompFeatureEffectsFromFile(), EngineUtil::readProbeFile(), ChipLayout::readProbeListCdfFileKillList(), ChipLayout::readProbeListPgfFileKillList(), QCProbesetOptions::readQCCFile(), TranslationInputTsvTableModel::readTsvFile(), CNAnalysisMethodCN::reEstimate(), QuantBRLMM::removeHetFromPrior(), QuantMethodSqlGTypeReport::report(), QuantMethodGTypeCHPReport::report(), QuantMethodGTypeChipSummary::report(), reportBasics(), QuantMethodGTypeCHPReport::reportFailure(), SparseMart::reserve(), RegressionTest::run(), BaseEngine::run(), CNReferenceMethodPDNN::run(), CNLog2RatioAdjustmentMethodWaveCorrection::run(), CNAnalysisMethodMosaicism::run(), CNAnalysisMethodAllelePeaks::run(), runDmet2AlgorithmRegression(), runDmet3ReportRegression(), TranslationEngine::runImp(), ArtifactReduction::saveMultiChannelProfileToFile(), SketchQuantNormTran::scaleTargetSketch(), QuantMethod::scaleToTxt(), SocketUtil::sendMsg(), SocketBase::sendMsg(), setBgpFile(), DmListener::setDefaultCallIndex(), DmListener::setDefaultChrXCallIndex(), QuantLabelZ::setGenderParam(), QuantLabelZ::setMaxScore(), Options::setOpt(), SelfDoc::setOptValue(), QuantLabelZ::setOverride(), SketchQuantNormTran::setParameters(), QuantRma::setParameters(), QuantPlierBase::setParameters(), RmaBgTran::setPmProbes(), setPra(), DiskIntensityMart::setProbeIntensity(), DataStore::setProbeOrder(), MedNormTran::setTarget(), SketchQuantNormTran::setTargetSketch(), FsTestDir::setTestDir(), QuantLabelZ::setTrustCheck(), QuantRma::setUp(), QuantPlierBase::setUp(), QuantLabelZMulti::setUp(), QuantLabelZ::setUp(), QuantDabg::setUp(), QuantBRLMM::setUp(), QuantBirdseed::setUp(), QuantAvgDiff::setUp(), CNWorkflowEngine::setupParameters(), SgIoHelper::SgIoHelper(), SketchQuantNormTran::SketchQuantNormTran(), CNAnalysisMethodCN::smoothOutliers(), SocketClient::socketConnect(), SocketServer::socketOpen(), TranslationInputStreamTableModel::sortTsvFileByExperiment(), QuantBRLMM::stringForTransformation(), stringForTransformation(), Probe::stringForType(), summaryVis::summaryVis(), RegressionTest::syncDirectory(), AnalysisInfo::toString(), SketchQuantNormTran::transform(), RmaBgTran::transform(), QuantMethodTransform::transformData(), ChipStreamDataTransform::transformData(), TranslationTable::TranslationTable(), tsv_util_paste_basic(), CelExtract::tsvSetProbeAnnotations(), ChipLayout::typeFromCdfType(), valueForTransformation(), affx::TsvFile::writeLevel(), ChipLayout::writePgfFile(), ChipLayout::writeSpfProbeListRecord(), ChipLayout::writeSpfProbeSetRecord(), x_getModelString(), QuantMethodSqlExprReport::~QuantMethodSqlExprReport(), and QuantMethodSqlGTypeReport::~QuantMethodSqlGTypeReport().
std::string ToStr (const std::string & str) [inline]
Convert the arg to a string. ///.
Parameters:
arg which is a string already. ///
Returns:
a string ///
Remarks:
Since it is a string already, no conversion needs to be done. /// ToStr returns a new string, so we match that.
Definition at line 258 of file Convert.h.