Affymetrix Power Tools: calvin_files/converters/utils/src/ConverterFileUtils.h File Reference
ConverterFileUtils.h File Reference
#include "calvin_files/data/src/GenericDataHeader.h"
Functions
bool ConverterMoveFile (const char *oldFile, const char *newFile, bool overwrite=false)
bool ConverterCopyFile (const char *oldFile, const char *newFile, bool overwrite=false)
bool ConverterRemoveFile (const char *fileName)
bool ConverterFileExists (const char *fileName)
void ConverterCreateAndAddParentArrayGenericDataHeader (affymetrix_calvin_io::GenericDataHeader &hdr, std::string arrayID, std::wstring arrayBarcode)
Detailed Description
This file contains file system utility functions.
Definition in file ConverterFileUtils.h.
Function Documentation
bool ConverterCopyFile (const char * oldFile, const char * newFile, bool overwrite = false)
Copies a file.
Parameters:
oldFile The name of the file to copy.
newFile The name of the new file.
overwrite A flag indicating if an existing file should be deleted prior to the copy.
Returns:
True if the file was copied.
Definition at line 102 of file ConverterFileUtils.cpp.
void ConverterCreateAndAddParentArrayGenericDataHeader (affymetrix_calvin_io::GenericDataHeader & hdr, std::string arrayID, std::wstring arrayBarcode)
Creates and adds the array set GenericDataHeader as a parent to the hdr parameter. The arrayID member will be set as the affymetrix-array-id value.
Parameters:
hdr The GenericDataHeader that will receive the array set parent header.
arrayID. The array ID. (physcial array ID).
arrayBarcode. The array barcode.
Definition at line 153 of file ConverterFileUtils.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_io::GenericDataHeader::AddParent(), ARRAY_BARCODE_PARAM_NAME, ARRAY_ID_PARAM_NAME, ARRAY_TYPE_IDENTIFIER, affymetrix_calvin_io::GenericDataHeader::SetFileTypeId(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueAscii(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueText().
bool ConverterFileExists (const char * fileName)
Checks if a file exists.
Parameters:
fileName The name of the file to delete.
Returns:
True if exists.
Definition at line 148 of file ConverterFileUtils.cpp.
References affymetrix_calvin_utilities::FileUtils::Exists().
bool ConverterMoveFile (const char * oldFile, const char * newFile, bool overwrite = false)
Moves a file.
Parameters:
oldFile The name of the file to move.
newFile The name of the new file.
overwrite A flag indicating if an existing file should be deleted prior to the move.
Returns:
True if the file was moved.
Definition at line 73 of file ConverterFileUtils.cpp.
bool ConverterRemoveFile (const char * fileName)
Deletes a file.
Parameters:
fileName The name of the file to delete.
Returns:
True if the file was deleted.
Definition at line 130 of file ConverterFileUtils.cpp.