Affymetrix Power Tools: dm/DM.cpp File Reference
DM.cpp File Reference
#include "dm/DM.h"
#include "dm/DmPTable.h"
#include <string.h>
Classes
struct PairLess
Defines
#define MIN(x, y) ((x)<(y))? (x) : (y)
#define MAX(x, y) ((x)>(y))? (x) : (y)
Functions
int GetState (const int &model)
converting function between model and state
double Omega (const double &mu, const double &var, const double &estmu)
A simple utility function.
void CalcMu (const CQuartet &quartet, const int &model, double mu[])
calculate the mean for a given model
void CalcSigma (const CQuartet &quartet, double mu[], double sigma[], const int &model)
calculate the sigma for a given model with given means
double round (double val, int places)
Round the double and return it.
double CalcLogLikelihood (const CQuartet &quartet, double mu[], double sigma[])
calculate loglikelihood of a probe quartet given model mean and sigma
float CalcLogLikelihood (const CQuartet &quartet, const int &model)
calculate loglikelihood of a probe quartet for a given model
bool CheckLargeBackground (const CQuartet &quartet, const int &model)
check whether backgroud is higher than foreground or not for a given model
float GetPValue (const vector< float > &x)
Apply Wilcoxon signed rank test on the loglikelihood difference vector to compute a p-value.
bool CallDM (const vector< CQuartet > &vquartets, pair< float, int > &results, const float &hetMult)
the main entry function of DM algorithm, which starts with a vector of probe quartets and some parameters then run through the whole DM flow, return the genotype along with a p-value associated with
Detailed Description
Author:
Xiaojun Di
Date:
March 8 2006
DRAFT: wraps the DM algorithmics for genotyping under SDK
Definition in file DM.cpp.
Function Documentation
double CalcLogLikelihood (const CQuartet & quartet, double mu[], double sigma[])
calculate loglikelihood of a probe quartet given model mean and sigma
Parameters:
quartet - the probe quartet
mu - the mean to the model
sigma - the mean to the model
Returns:
the loglikelihood
Definition at line 235 of file DM.cpp.
References CQuartet::intensity, Omega(), CQuartet::pixels, round(), and CQuartet::variance.
Referenced by CalcLogLikelihood(), and CallDM().
float CalcLogLikelihood (const CQuartet & quartet, const int & model)
calculate loglikelihood of a probe quartet for a given model
Parameters:
quartet - the probe quartet
model - the model in consideration
Returns:
the loglikelihood
Definition at line 263 of file DM.cpp.
References CalcLogLikelihood(), CalcMu(), and CalcSigma().
void CalcMu (const CQuartet & quartet, const int & model, double mu[])
calculate the mean for a given model
Parameters:
quartet - the probe quartet
model - the current model
mu - the mean to be returned
Returns:
void
Definition at line 110 of file DM.cpp.
References GetState(), CQuartet::intensity, and CQuartet::pixels.
Referenced by CalcLogLikelihood().
void CalcSigma (const CQuartet & quartet, double mu[], double sigma[], const int & model)
calculate the sigma for a given model with given means
Parameters:
quartet - the probe quartet
model - the current model
mu - the mean to this model
sigma - the sigmas to be returned
Returns:
void
Definition at line 155 of file DM.cpp.
References GetState(), CQuartet::intensity, Omega(), CQuartet::pixels, and CQuartet::variance.
Referenced by CalcLogLikelihood().
bool CallDM (const vector< CQuartet > & vquartets, pair< float, int > & results, const float & hetMult)
the main entry function of DM algorithm, which starts with a vector of probe quartets and some parameters then run through the whole DM flow, return the genotype along with a p-value associated with
Parameters:
vquartets - a vector of probe quartets
results - a result container to hold the genotype and p-values and return
hetMult - the heterozygote multiplier to be multiplied on AB model
Returns:
true if no error, false otherwise
Definition at line 481 of file DM.cpp.
References CalcLogLikelihood(), CheckLargeBackground(), GetPValue(), NUMCELLS, and round().
Referenced by DmListener::makeCall().
bool CheckLargeBackground (const CQuartet & quartet, const int & model)
check whether backgroud is higher than foreground or not for a given model
Parameters:
quartet - the probe quartet to be checked
model - the model to be tested
Returns:
true if yes, false otherwise
Definition at line 288 of file DM.cpp.
References CQuartet::intensity.
Referenced by CallDM().
float GetPValue (const vector< float > & x)
Apply Wilcoxon signed rank test on the loglikelihood difference vector to compute a p-value.
Parameters:
x - the loglikelihood difference vector
Returns:
the p-value
Todo:
Why are we summing
Definition at line 342 of file DM.cpp.
References mask().
Referenced by CallDM().
int GetState (const int & model)
converting function between model and state
Parameters:
model - model index
Returns:
the state the model is mapped to
Definition at line 78 of file DM.cpp.
Referenced by CalcMu(), and CalcSigma().
double Omega (const double & mu, const double & var, const double & estmu)
A simple utility function.
Parameters:
mu - observed mean
var - variance
estmu - estimated mean
Returns:
the omega value
Definition at line 96 of file DM.cpp.
Referenced by CalcLogLikelihood(), and CalcSigma().
double round (double val, int places)
Round the double and return it.
Parameters:
d - The double to round.
iDecimalPlaces - The number of decimal places to round to.
Returns:
- rounded double value.
Definition at line 197 of file DM.cpp.
Referenced by FileTranslation::calcDimensions(), CalcLogLikelihood(), CallDM(), QuantGTypeMethod::extractProbes(), RmaBgTran::RmaBgTran(), QuantGTypeMethod::summarizeAllele(), MultiChannelHomHiLoCelListener::summarizeAllele(), and ChipLayout::trackGlobalStats().