Affymetrix Power Tools: dmet/regression/dmet-genotype-test.cpp File Reference
dmet-genotype-test.cpp File Reference
Program for doing regression tests on dmet-genotype data.
#include "util/CalvinChpCheck.h"
#include "util/ChpCheck.h"
#include "util/Convert.h"
#include "util/FsTestDir.h"
#include "util/RegressionTest.h"
#include "util/Util.h"
#include "util/Verbose.h"
#include <cstring>
#include <string>
#include <vector>
Classes
class DmetGenotypeTest
Functions
int main (int argc, char *argv[])
Everybody's favorite function.
Variables
string m_celsSuffix = ".CEL"
const char * m_cels []
Detailed Description
Program for doing regression tests on dmet-genotype data.
Author:
Alan Williams
Date:
Fri Sep 12 12:07:04 PDT 2008
Definition in file dmet-genotype-test.cpp.
Function Documentation
int main (int argc, char * argv[])
Everybody's favorite function.
Definition at line 233 of file dmet-genotype-test.cpp.
References Verbose::out(), Verbose::setLevel(), FsTestDir::setTestDir(), and ToStr().
Variable Documentation
const char* m_cels[]
Initial value:
{
  "ZQ_C01_NA19193",    "ZQ_C02_NA12004",    "ZQ_C03_NA19194",
  "ZQ_C04_NA18856",    "ZQ_C05_NA19137",    "ZQ_C06_NA19144",
  "ZQ_C07_NA12003",    "ZQ_C08_NA19143",    "ZQ_C09_NA10838",
  "ZQ_C10_NA19130",    "ZQ_C11_NA18855",    "ZQ_C12_NA19139",
  "ZQ_D01_NA18856",    "ZQ_D02_NA19194",    "ZQ_D03_NA19138",
  "ZQ_D04_NA19131",    "ZQ_D05_NA10838",    "ZQ_D06_NA19192",
  "ZQ_D07_NA19145",    "ZQ_D08_NA19132",    "ZQ_D09_NA18857",
  "ZQ_D10_gCtrl_1",    "ZQ_D11_gCtrl_2",    "ZQ_D12_gCtrl_3",
  NULL
}
Definition at line 46 of file dmet-genotype-test.cpp.