Affymetrix Power Tools: translation/regression/dmet-translation-test.cpp File Reference
dmet-translation-test.cpp File Reference
Regression tests for apt-dmet-translation.cpp.
#include "translation/RegressionExperimentReport.h"
#include "translation/RunTimeEnvironment.h"
#include "translation/regression/ATDRegression.h"
#include "translation/regression/DMET2Check.h"
#include "translation/regression/DMET3TestCaseCheck.h"
#include "translation/regression/DMET3TestCaseTableModel.h"
#include "calvin_files/utils/src/FileUtils.h"
#include "util/Err.h"
#include "util/Fs.h"
#include "util/FsTestDir.h"
#include "util/LogStream.h"
#include "util/PgOptions.h"
#include "util/RegressionTest.h"
#include "util/Util.h"
#include "pcrecpp.h"
#include <cassert>
#include <sstream>
Functions
void displayHelpAndExit (PgOptions *opts)
displayHelpAndExit: Synopsis: Calls the PGOptions usage method.
void getOptions (int argc, char *argv[], RunTimeEnvironment &rte, const FsTestDir &testDir)
getOptions: Synopsis: Fill the PGOptions data structure with our options.
map< string, vector
< RegressionCheck * > > getDMET2AlgorithmChecks (RunTimeEnvironment &rte)
getDMET2AlgorithmChecks: Synopsis: Get the DME2 Genotype files and their corresponding DMET2 files for regression comparision
bool runDmet2AlgorithmRegression (RunTimeEnvironment &rte)
runDmet2AlgorithmRegression: Synopsis: Run algorithem regression
map< string, vector
< RegressionCheck * > > getDMET3ReportChecks (RunTimeEnvironment &rte)
getDMET3ReportChecks: Synopsis: Get the DMET3 test case CSV files.
bool runDmet3ReportRegression (RunTimeEnvironment &rte)
runDmet3ReportRegression: Synopsis:
int main (int argc, char *argv[])
main Synopsis: main control loop.
Detailed Description
Regression tests for apt-dmet-translation.cpp.
Author:
Mybrid Spalding
Date:
Wed Jun 4 08:25:55 PDT 2008
Definition in file dmet-translation-test.cpp.
Function Documentation
void displayHelpAndExit (PgOptions * opts)
displayHelpAndExit: Synopsis: Calls the PGOptions usage method.
Parameters:
opts - PgOptions for printing the usage. return - exits program.
Definition at line 65 of file dmet-translation-test.cpp.
References PgOptions::usage().
map< string, vector< RegressionCheck *> > getDMET2AlgorithmChecks (RunTimeEnvironment & rte)
getDMET2AlgorithmChecks: Synopsis: Get the DME2 Genotype files and their corresponding DMET2 files for regression comparision
Parameters:
rte - the run time environment
cmd - for return
Returns:
- The vector of RegressionCheck objects as well as a command to run them.
Definition at line 137 of file dmet-translation-test.cpp.
References APT_ERR_ABORT, Fs::basename(), Fs::join(), affymetrix_calvin_utilities::FileUtils::ListFiles(), and Verbose::out().
Referenced by runDmet2AlgorithmRegression().
map< string, vector< RegressionCheck *> > getDMET3ReportChecks (RunTimeEnvironment & rte)
getDMET3ReportChecks: Synopsis: Get the DMET3 test case CSV files.
Parameters:
rte - the run time environment
Returns:
- The vector of RegressionCheck objects
Todo:
add this to Fs.
Definition at line 371 of file dmet-translation-test.cpp.
References Fs::join(), affymetrix_calvin_utilities::FileUtils::ListFiles(), and Verbose::out().
Referenced by runDmet3ReportRegression().
void getOptions (int argc, char * argv[], RunTimeEnvironment & rte, const FsTestDir & testDir)
getOptions: Synopsis: Fill the PGOptions data structure with our options.
Note that this program is intended to run with no options via "make regression". If there are options they should be passed in via the Makefile.
Parameters:
name1 - description
name1 - description
Returns:
- description
Definition at line 90 of file dmet-translation-test.cpp.
References PgOptions::defineOption(), PgOptions::get(), PgOptions::getProgName(), PgOptions::parseArgv(), and Verbose::setLevel().
Referenced by main().
int main (int argc, char * argv[])
main Synopsis: main control loop.
Parameters:
argc - command line
argv - command line
Returns:
- 0 ok, 1 on error
Definition at line 493 of file dmet-translation-test.cpp.
References APT_ERR_ABORT, Profile::begin(), getOptions(), Util::getTimeStamp(), RunTimeEnvironment::initializeRunTimeEnvironment(), Fs::join(), Fs::mkdirPath(), Fs::mustOpenToWrite(), Verbose::out(), Verbose::pushProgressHandler(), runDmet2AlgorithmRegression(), runDmet3ReportRegression(), Verbose::setLevel(), FsTestDir::setTestDir(), and Err::setThrowStatus().
bool runDmet2AlgorithmRegression (RunTimeEnvironment & rte)
runDmet2AlgorithmRegression: Synopsis: Run algorithem regression
Parameters:
name1 - description
name1 - description
Returns:
- description
Definition at line 209 of file dmet-translation-test.cpp.
References getDMET2AlgorithmChecks(), Verbose::out(), and ToStr().
Referenced by main().
bool runDmet3ReportRegression (RunTimeEnvironment & rte)
runDmet3ReportRegression: Synopsis:
Parameters:
rte - the run time envrionment
Returns:
- true if all tests passed, false otherwise.
Definition at line 444 of file dmet-translation-test.cpp.
References getDMET3ReportChecks(), Verbose::out(), and ToStr().
Referenced by main().