Affymetrix Power Tools: chipstream/GenoUtility.h File Reference
GenoUtility.h File Reference
#include "chipstream/BioTypes.h"
#include "chipstream/ClusterZ.h"
#include "chipstream/ProbeSet.h"
#include "calvin_files/fusion/src/FusionCELData.h"
#include "stats/stats.h"
#include "newmat.h"
#include <cfloat>
#include <cstring>
#include <string>
#include <vector>
Enumerations
enum Transformation { MvA, RvT, CES, CCS }
Functions
bool probesetMeanStd (affymetrix_fusion_io::FusionCELData *cel, const ProbeSet *ps, float &mean, float &std)
bool probesetStd (affymetrix_fusion_io::FusionCELData *cel, const ProbeSet *ps, float &std)
bool probesetMean (affymetrix_fusion_io::FusionCELData *cel, const ProbeSet *ps, float &mean)
double logRatio (double sigA, double sigB)
Calculate the natural log ratio for two probeset signal.
void loadTargetSketchFromFile (const char *fileName, std::vector< float > &sketch)
Open and read a target distribution from a text file.
void loadSNPHints (std::string fileName, std::vector< std::string > &colNames, std::map< std::string, std::vector< affx::GType > > &knownCalls)
Read in the precomputed genotypes from a tab delimited file.
void valueForTransformation (double aVal, double bVal, enum Transformation trans, double K, double &xVal, double &yVal)
the engine that transforms the data
enum Transformation transformationForString (const std::string &s)
Convert a (text insensitive) text repesentation of a transformation into the enumration.
std::string stringForTransformation (enum Transformation t)
Convert a transformation enum to string representation.
std::pair< std::string,
std::string > columnNamesForTransformation (enum Transformation t)
Return the calumn names for the values generated by a given transformation.
void GenoUtility_transformData (std::vector< double > &aVals, std::vector< double > &bVals, Transformation m_Transform, double m_K)
transforms a vector of data
void ContrastCentersStretch (double K, double a, double b, double &x, double &y)
Contrast Centers Stretch.
void ContrastExtremesStretch (double K, double a, double b, double &x, double &y)
Contrast Extremes Stretch.
bool alleleMedians (affymetrix_fusion_io::FusionCELData *cel, const ProbeSet *ps, float &Amedian, float &Bmedian)
Calculate the median PM values for the A and B alleles given data in cel file.
bool probesetMinMax (affymetrix_fusion_io::FusionCELData *cel, const ProbeSet *ps, float &Min, float &Max)
Detailed Description
Author:
Earl Hubbell
Date:
Aug 2 2006
Fix up utility routines for genotypes common transformations, etc.
Definition in file GenoUtility.h.
Enumeration Type Documentation
enum Transformation
Enumerator:
MvA
Minus Vs Average.
RvT
R vs Theta.
CES
Contrast Extremes Stretch (nee south san francisco).
CCS
Contrast Centers Stretch (nee alternative south san francisco).
Definition at line 99 of file GenoUtility.h.
Function Documentation
bool alleleMedians (affymetrix_fusion_io::FusionCELData * cel, const ProbeSet * ps, float & Amedian, float & Bmedian)
Calculate the median PM values for the A and B alleles given data in cel file.
Parameters:
cel - Cel file of data.
ps - ProbeSet for determining A and B alleles.
Amedian - Filled in with median PM A value.
Bmedian - Filled in with median PM B value.
Returns:
Definition at line 230 of file GenoUtility.cpp.
References ProbeSet::atoms, ProbeSet::atomsPerGroup, affymetrix_fusion_io::FusionCELData::GetIntensity(), Probe::id, ProbeSet::numGroups, Atom::probes, and ProbeSet::psType.
Referenced by HomHiLoCelListener::CalculateEMContrast(), and EmGenderCelListener::CalculateEMContrast().
std::pair<std::string,std::string> columnNamesForTransformation (enum Transformation t)
Return the calumn names for the values generated by a given transformation.
Parameters:
t - tranformation enum value.
Returns:
- a pair of column names
Definition at line 137 of file GenoUtility.cpp.
References CCS, CES, Err::errAbort(), MvA, RvT, and ToStr().
Referenced by QuantLabelZ::getAlleleValueNames().
void ContrastCentersStretch (double K, double a, double b, double & x, double & y)
Contrast Centers Stretch.
In 2007 this is the current favorite for algorithms, scales values between -1 and 1.
Parameters:
a - Value (usually summarized intensity) from A allele.
b - Value (usually summarized intensity) from B allele.
In 2007 this is the current favorite for algorithms, scales values between -1 and 1.
Parameters:
K -
a - Value (usually summarized intensity) from A allele.
b - Value (usually summarized intensity) from B allele.
x -
y -
Definition at line 185 of file GenoUtility.cpp.
References Err::errAbort(), and log2.
Referenced by EmGenderCelListener::CalculateEMContrast(), and valueForTransformation().
void ContrastExtremesStretch (double K, double a, double b, double & x, double & y)
Contrast Extremes Stretch.
Parameters:
K -
a - Value (usually summarized intensity) from A allele.
b - Value (usually summarized intensity) from B allele.
x -
y -
Definition at line 209 of file GenoUtility.cpp.
References Err::errAbort(), and log2.
Referenced by HomHiLoCelListener::CalculateEMContrast(), MultiChannelNonOverlapCelListener::GimmeContrast(), MultiChannelHomHiLoCelListener::GimmeContrast(), and valueForTransformation().
void loadSNPHints (std::string fileName, std::vector< std::string > & colNames, std::map< std::string, std::vector< affx::GType > > & knownCalls)
Read in the precomputed genotypes from a tab delimited file.
Must be a column for each Celfile with same header name as celfile and an row for every snp to be analyzed. There can be extra columns and order of columns is not important as the resulting order will be the same as the colNames vector. Steal from GenoSeedTxt.
Parameters:
fileName - text file containing the known genotype calls colNames - the name of samples. knownCalls -- the map that store knownCalls infomation for each SNP.
Definition at line 438 of file GenoUtility.cpp.
References Fs::basename(), affx::TsvFile::close(), Err::errAbort(), affx::GType_from_int(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), Verbose::out(), ToStr(), and affx::TSV_BIND_REQUIRED.
void loadTargetSketchFromFile (const char * fileName, std::vector< float > & sketch)
Open and read a target distribution from a text file.
Must have a column called 'intensities' with distribution quantiles sorted from highest to lowest.
Parameters:
fileName - text file containing column of quantiles. sketch - vector that stores the sketch.
Definition at line 410 of file GenoUtility.cpp.
References affx::TsvFile::close(), affx::TsvFile::cname2cidx(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), and affx::TSV_OK.
double logRatio (double sigA, double sigB)
Calculate the natural log ratio for two probeset signal.
signalA -- e.x. signal channel signalB -- e.x. background channel
Definition at line 395 of file GenoUtility.cpp.
std::string stringForTransformation (enum Transformation t)
Convert a transformation enum to string representation.
Parameters:
t - tranformation enum value.
Returns:
- text description of enumeration.
Definition at line 111 of file GenoUtility.cpp.
References CCS, CES, Err::errAbort(), MvA, RvT, and ToStr().
Referenced by QuantLabelZ::QuantLabelZ().
enum Transformation transformationForString (const std::string & str)
Convert a (text insensitive) text repesentation of a transformation into the enumration.
Parameters:
s - string specifying transformation.
Returns:
- Enumeration version of transformation.
Definition at line 90 of file GenoUtility.cpp.
References Util::downcaseString(), and Err::errAbort().
Referenced by QuantLabelZMulti::newObject(), and QuantLabelZ::newObject().
void valueForTransformation (double aVal, double bVal, enum Transformation trans, double K, double & xVal, double & yVal)
the engine that transforms the data
the engine that transforms the data
Parameters:
aVal - a allele probe summary
bVal - b allele probe summary
trans - transformation of data
K - stretching parameter
xVal - output difference of a vs b, transformed
yVal - output total amount of stuff, transformed
Definition at line 52 of file GenoUtility.cpp.
References CCS, CES, ContrastCentersStretch(), ContrastExtremesStretch(), Err::errAbort(), log2, MvA, RvT, and ToStr().
Referenced by GenoUtility_transformData().