Affymetrix Power Tools: mas5-stat/src/IntensityFileType.h File Reference
IntensityFileType.h File Reference
#include "calvin_files/fusion/src/FusionCELData.h"
Functions
bool FromHP (affymetrix_fusion_io::FusionCELData &cel)
Detailed Description
This file contains functions to check if a CEL file is from an HP scanner.
Definition in file IntensityFileType.h.
Function Documentation
bool FromHP (affymetrix_fusion_io::FusionCELData & cel)
Checks if the CEL file is from an HP scanner.
Parameters:
cel The CEL file object.
Returns:
True if from a HP scanner.
Definition at line 70 of file IntensityFileType.cpp.
References DAT_HEADER_PARAM_NAME, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_fusion_io::FusionCELData::GetDatHeader(), affymetrix_fusion_io::FusionCELData::GetGenericData(), affymetrix_fusion_io::FusionCELData::GetGridCorners(), affymetrix_calvin_io::GenericDataHeader::GetParent(), affymetrix_calvin_io::GenericDataHeader::GetParentCnt(), affymetrix_calvin_io::GenericData::Header(), SCANNER_TYPE_PARAM_NAME, affymetrix_calvin_parameter::ParameterNameValueType::ToString(), affymetrix_fusion_io::FGridCoords::upperleft, affymetrix_fusion_io::FPoint::x, and affymetrix_fusion_io::FPoint::y.