Affymetrix Power Tools: util/md5.cpp File Reference
md5.cpp File Reference
///
#include "util/md5.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
Defines
#define PUT_64BIT_LE(cp, value)
#define PUT_32BIT_LE(cp, value)
#define F1(x, y, z) (z ^ (x & (y ^ z)))
#define F2(x, y, z) F1(z, x, y)
#define F3(x, y, z) (x ^ y ^ z)
#define F4(x, y, z) (y ^ (x | ~z))
#define MD5STEP(f, w, x, y, z, data, s) (w += f(x, y, z) + data, w = w<<s | w>>(32-s), w += x)
Functions
void MD5Init (MD5_CTX *ctx)
Start MD5 accumulation. Set bit count /// to 0 and buffer to mysterious initialization constants.
void MD5Update (MD5_CTX *ctx, const unsigned char *input, u_int32_t len)
Update context to reflect the concatenation of another buffer full of bytes. ///.
void MD5Final (unsigned char digest[MD5_DIGEST_LENGTH], MD5_CTX *ctx)
Final wrapup - pad to 64-byte boundary with the bit pattern /// 1 0* (64-bit count of bits processed, MSB-first) ///.
void MD5Transform (u_int32_t state[4], const u_int8_t block[MD5_BLOCK_LENGTH])
The core of the MD5 algorithm, this alters an existing MD5 hash to reflect the addition of 16 longwords of new data.
Detailed Description
///
The public domain md5 functions
Definition in file md5.cpp.
Define Documentation
#define PUT_32BIT_LE (cp, value)
Value:
do {                                    \
        (cp)[3] = (value) >> 24;                                        \
        (cp)[2] = (value) >> 16;                                        \
        (cp)[1] = (value) >> 8;                                         \
        (cp)[0] = (value); } while (0)
Definition at line 51 of file md5.cpp.
#define PUT_64BIT_LE (cp, value)
Value:
do {                                    \
        (cp)[7] = (value) >> 56;                                        \
        (cp)[6] = (value) >> 48;                                        \
        (cp)[5] = (value) >> 40;                                        \
        (cp)[4] = (value) >> 32;                                        \
        (cp)[3] = (value) >> 24;                                        \
        (cp)[2] = (value) >> 16;                                        \
        (cp)[1] = (value) >> 8;                                         \
        (cp)[0] = (value); } while (0)
Definition at line 41 of file md5.cpp.
Function Documentation
void MD5Final (unsigned char digest[MD5_DIGEST_LENGTH], MD5_CTX * ctx)
Final wrapup - pad to 64-byte boundary with the bit pattern /// 1 0* (64-bit count of bits processed, MSB-first) ///.
Parameters:
digest The output digest ///
ctx The content to finalize
Definition at line 119 of file md5.cpp.
References MD5Context::count, MD5Update(), and MD5Context::state.
Referenced by affx::md5sum::final().
void MD5Init (MD5_CTX * ctx)
Start MD5 accumulation. Set bit count /// to 0 and buffer to mysterious initialization constants.
Parameters:
ctx The context structure to init
Definition at line 67 of file md5.cpp.
References MD5Context::count, and MD5Context::state.
Referenced by affx::md5sum::init().
void MD5Transform (u_int32_t state[4], const u_int8_t block[MD5_BLOCK_LENGTH])
The core of the MD5 algorithm, this alters an existing MD5 hash to reflect the addition of 16 longwords of new data.
MD5Update blocks the data and converts bytes into longwords for this routine.
Definition at line 164 of file md5.cpp.
Referenced by MD5Update().
void MD5Update (MD5_CTX * ctx, const unsigned char * input, u_int32_t len)
Update context to reflect the concatenation of another buffer full of bytes. ///.
Parameters:
ctx The context to update ///
input pointer to the buffer of bytes ///
len buffer length
Definition at line 81 of file md5.cpp.
References MD5Context::buffer, MD5Context::count, MD5Transform(), and MD5Context::state.
Referenced by MD5Final(), affx::md5sum::update(), and affx::md5sum::update_nbo().