Affymetrix Power Tools: chipstream/example/multiChannelExample.cpp File Reference
multiChannelExample.cpp File Reference
A simple example of multi channel analysis Please do not use this example for real life data analysis.
#include "chipstream/AnalysisStreamFactory.h"
#include "chipstream/BioTypes.h"
#include "chipstream/CelReader.h"
#include "chipstream/DiskIntensityMart.h"
#include "chipstream/FileGenders.h"
#include "chipstream/GenoSeedTxt.h"
#include "chipstream/MultiQuantMethodListener.h"
#include "chipstream/PmOnlyAdjust.h"
#include "chipstream/QuantLabelZ.h"
#include "chipstream/QuantMethodFactory.h"
#include "chipstream/QuantMethodGTypeReport.h"
#include "chipstream/QuantMethodReportListener.h"
#include "chipstream/SpecialSnps.h"
#include "file/TsvFile/TsvFile.h"
#include "util/Fs.h"
#include "util/LogStream.h"
#include "util/PgOptions.h"
#include <cstring>
#include <iostream>
#include <string>
#include <vector>
Classes
class AOptions
Functions
void define_options (PgOptions *opts)
void fillInOptions (PgOptions *opts, AOptions &o)
void callGenotypes (AOptions &o)
void printParams (string algo)
int main (int argc, const char *argv[])
Everbody's favorite function...
Detailed Description
A simple example of multi channel analysis Please do not use this example for real life data analysis.
Author:
Alan Williams
Date:
Fri Jan 4 13:53:19 PST 2008
Definition in file multiChannelExample.cpp.
Function Documentation
void callGenotypes (AOptions & o)
Todo:
not particularly space efficient
Todo:
set time string
Todo:
set command line string
Todo:
set command line string
Todo:
populate analysis info object
Todo:
much of this should probably be in a MultiQuantLabelZ /// rather than using QuantLabelZ directly. Accessing /// m_Results directly is ugly as well.
Todo:
default should be global (ie if we have a channel file, then all probesets must be found in it. only default to 0/1 when there is no channel file)
Definition at line 268 of file multiChannelExample.cpp.
References QuantMethodReport::addStdHeaders(), ProbeListFactory::asProbeSet(), Fs::basename(), AOptions::celFiles, Util::cloneString(), affx::TsvFile::close(), QuantLabelZ::computeEstimate(), AnalysisStreamFactory::constructAnalysisStream(), Err::errAbort(), fillInHaploidSnps(), QuantMethodExprReport::finish(), QuantMethodReport::finish(), affxutil::Guid::GenerateNewGuid(), AOptions::genoTypesFile, FileGenders::getGenders(), ChipLayout::getProbeListAtIndex(), ChipLayout::getProbeSetCount(), QuantExprMethod::getType(), Fs::join(), QuantLabelZ::loadInitialCallsForSnp(), affx::TsvFile::m_optEscapeOk, ProbeSetGroup::name, ProbeSet::name, affx::TsvFile::nextLevel(), affx::TsvFile::open(), ChipLayout::openCdfAll(), Verbose::out(), QuantMethodExprReport::prepare(), QuantMethodReport::prepare(), Verbose::progressStep(), QuantMethodFactory::quantGTypeMethodForString(), QuantLabelZ::readSnpPriorMap(), AnalysisStreamFactory::readTargetSketchFromFile(), QuantMethodReport::report(), QuantMethodExprReport::report(), affx::TsvFile::rewind(), QuantLabelZ::setAlleleValues(), QuantLabelZ::setGenders(), QuantLabelZ::setHaploidSnps(), QuantLabelZ::setKnownGenoTypes(), QuantLabelZ::setProbeSetName(), QuantLabelZ::setSpecialSnps(), AnalysisStreamFactory::setWriteSketchDir(), ToStr(), QuantLabelZ::transform(), affx::TSV_BIND_REQUIRED, affx::UnknownGender, QuantLabelZ::writeSnpPosteriorTsv(), and QuantLabelZ::writeSnpProbeTsv().
Referenced by main().
void fillInOptions (PgOptions * opts, AOptions & o)
Todo:
we order the channels by order seen, not the label /// would be nice to track the label and associate via /// label in lib/panel file
Definition at line 176 of file multiChannelExample.cpp.
References APT_ERR_ABORT, Fs::basename(), AOptions::celFiles, Util::chompLastIfSep(), affx::TsvFile::cidx2cname(), affx::TsvFile::close(), Err::errAbort(), PgOptions::findOpt(), AOptions::genoTypesFile, affx::TsvFile::get(), PgOptions::get(), PgOptions::getBool(), affx::TsvFile::getColumnCount(), PgOptions::getInt(), affx::TsvFile::m_optEscapeOk, Fs::mkdirPath(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), Verbose::out(), PgOpt::push_user_values_into(), affx::TsvFile::rewind(), ToStr(), and affx::TSV_BIND_REQUIRED.
int main (int argc, const char * argv[])
Everbody's favorite function...
Definition at line 648 of file multiChannelExample.cpp.
References callGenotypes(), fillInOptions(), PgOptions::get(), PgOptions::getBool(), Fs::join(), Fs::mustOpenToWrite(), PgOptions::parseArgv(), Verbose::pushProgressHandler(), Verbose::setLevel(), and PgOptions::usage().