Affymetrix Power Tools: affxstat Namespace Reference
affxstat Namespace Reference
We want the output to be the same as the perl code, so //! we have converted the code to C. Refer to the perldocs //! for more info.
Typedefs
typedef enum affxstat::_TAIL_TYPE TAIL_TYPE
Enumerations
enum _TAIL_TYPE { ONE_SIDED_LOWER, ONE_SIDED_UPPER, TWO_SIDED }
Functions
double gammln (double xx)
double log_gamma (double aa)
double log_beta (double a, double b)
double Incomplete_Beta (double a, double b, double x)
double Incomplete_Gamma (double a, double z, bool doLog)
double CalcHWEqPValue (int nAA, int nAB, int nBB)
double Ftest (double F, double vone, double vtwo)
double erf (double x)
double pnorm (double x, double mu, double sigma, bool lower_tail, bool log_p)
double pwilcox (unsigned int w, unsigned int nx, unsigned int ny, bool lower_tail, bool log_p)
double psignrank (unsigned int t, unsigned int n, bool lower_tail, bool log_p)
double nChooseK (unsigned int n, unsigned int k)
double ranksumTest (double *x1, int n1, double *x2, int n2, int tail_type, bool log_p)
void ranksumTest (double *x1, int n1, double *x2, int n2, bool *tied, double *pval, int tail_type, bool log_p)
void ranksumTest (double *x1, int n1, double *x2, int n2, int *nTied, double *pval, double *signal, int tail_type)
double signedRankTest (double *x, int n, int tail_type, bool log_p)
void signedRankTest (double *x, int n, bool *tied, bool *nZero, bool *tiedAndZero, double *pval, int tail_type, bool log_p)
void signedRankTest (double *x, int n, int *tied, int *nZero, int *tiedAndZero, double *pval, double *signal)
double pseudoMedian (double *x, int n)
double medianDifference (double *x, int nX, double *y, int nY)
double PearsonCorrelation (float *x1, float *x2, int nPoints, float(*transform)(float x)=NULL)
template<typename T1 >
T1 chisqrprob (int n, T1 x)
The chi-squared probability ///.
template<typename T1 >
T1 uprob (T1 x)
upper probability of the u distribution (u=-0.85) ///
template<typename T1 >
T1 tDistribution (T1 x, T1 degFreedom)
template<typename T1 >
T1 normalDistribution (T1 ecks, T1 mu, T1 sigma)
Detailed Description
We want the output to be the same as the perl code, so //! we have converted the code to C. Refer to the perldocs //! for more info.
These used to live in stats-distributions.cpp, but are now templates //! so we get the float and double versions.
Typedef Documentation
typedef enum affxstat::_TAIL_TYPE affxstat::TAIL_TYPE
Tail types for statistical tests.
Enumeration Type Documentation
enum affxstat::_TAIL_TYPE
Tail types for statistical tests.
Enumerator:
ONE_SIDED_LOWER
One sided lower tail
ONE_SIDED_UPPER
Once sided upper tail
TWO_SIDED
Two sided tail
Definition at line 81 of file statfun.h.
Function Documentation
double affxstat::CalcHWEqPValue (int nAA, int nAB, int nBB)
Calculate the hardy weinburg equilibrium
Parameters:
nAA The number of AA calls
nAB The number of AB calls
nBB The number of BB calls
Returns:
The HW equilibrium
Definition at line 1470 of file statfun.cpp.
template<typename T1 > T1 affxstat::chisqrprob (int n, T1 x)
The chi-squared probability ///.
Parameters:
n degrees of freedom ///
x chi-square value ///
Returns:
upper probability of the chi-square
Definition at line 61 of file stats-distributions.h.
References uprob().
Referenced by affx::Dabg::compute_target_fisher(), and test_target().
double affxstat::erf (double x)
This function ...
Parameters:
x The ...
Returns:
The ...
Definition at line 387 of file statfun.cpp.
Referenced by pnorm().
double affxstat::Ftest (double F, double vone, double vtwo)
This function ...
Parameters:
F The ...
vone The ...
vtwo The ...
Returns:
The ...
Definition at line 375 of file statfun.cpp.
References Incomplete_Beta().
Referenced by midasSpliceDetector::runMidasSingle().
double affxstat::gammln (double xx)
This function ...
Parameters:
xx The ...
Returns:
The ...
Definition at line 156 of file statfun.cpp.
Referenced by log_beta().
double affxstat::Incomplete_Beta (double a, double b, double x)
This function ...
Parameters:
a The ...
b The ...
x The ...
Returns:
The ...
Definition at line 362 of file statfun.cpp.
Referenced by Ftest().
double affxstat::Incomplete_Gamma (double a, double z, bool doLog)
This function ...
Parameters:
a The ...
z The ...
doLog The ...
Returns:
The ...
Definition at line 295 of file statfun.cpp.
double affxstat::log_beta (double a, double b)
This function ...
Parameters:
a The ...
b The ...
Returns:
The ...
Definition at line 222 of file statfun.cpp.
References gammln(), and log_gamma().
double affxstat::log_gamma (double aa)
This function ...
Parameters:
aa The ...
Returns:
The ...
Definition at line 172 of file statfun.cpp.
Referenced by log_beta().
double affxstat::medianDifference (double * x, int nX, double * y, int nY)
Computes the median over all pairwise differences in two arrays of values.
Parameters:
x The first array of values.
nX The number of points in the x1 array.
y The second array of values.
nY The number of points in the x2 array.
Returns:
The median of all n1*n2 pairwise differences.
Definition at line 1225 of file statfun.cpp.
Referenced by ranksumTest().
double affxstat::nChooseK (unsigned int n, unsigned int k)
This function compute the N choose K value.
Parameters:
n The N value
k The K value
Returns:
N choose K
Definition at line 674 of file statfun.cpp.
double affxstat::PearsonCorrelation (float * x1, float * x2, int nPoints, float(*)(float x) transform = NULL)
This function calculates Pearson's correlation coefficient between 2 arrays of floats
Parameters:
x1 The first array of floats
x2 The second array of floats
nPoints The size of each array. assumed the same
transform A function to transform the data
Returns:
Pearson's correlation
Definition at line 1249 of file statfun.cpp.
double affxstat::pnorm (double x, double mu, double sigma, bool lower_tail, bool log_p)
This function ...
Parameters:
x The ...
mu The ...
sigma The ...
lower_tail Flag indicating if lower tail should be computed.
log_p Flag indicating if the p-value should be logged.
Returns:
The ...
Definition at line 462 of file statfun.cpp.
References erf(), and SQRT_TWO.
double affxstat::pseudoMedian (double * x, int n)
Computes the pseudo median.
Parameters:
x The array of values for which to compute the pseudomedian.
n The number of points in the x array.
Returns:
The pseudo median.
Definition at line 929 of file statfun.cpp.
Referenced by signedRankTest().
double affxstat::psignrank (unsigned int t, unsigned int n, bool lower_tail, bool log_p)
The implementation of wilcoxon signed rank statistic.
Parameters:
w The ...
n The ...
lower_tail Flag indicating if lower tail should be computed.
log_p Flag indicating if the p-value should be logged.
Returns:
The signed rank statistic.
Definition at line 634 of file statfun.cpp.
References LOG_TWO, and PSIGNRANK_MAX_N.
Referenced by signedRankTest().
double affxstat::pwilcox (unsigned int w, unsigned int nx, unsigned int ny, bool lower_tail, bool log_p)
This function ...
Parameters:
w The ...
nx The ...
xy The ...
lower_tail Flag indicating if lower tail should be computed.
log_p Flag indicating if the p-value should be logged.
Returns:
The ...
Definition at line 575 of file statfun.cpp.
References choose().
Referenced by ranksumTest().
double affxstat::ranksumTest (double * x1, int n1, double * x2, int n2, int tail_type, bool log_p)
Performs a Wilcoxon rank sum test. This is the simplest interface.
Parameters:
x1 The array of values for the first sample.
n1 The number of points in the x1 array.
x2 The array of values for the second sample.
n2 The number of points in the x2 array.
tail_type The tail type for the test (one of ONE_SIDED_UPPER, ONE_SIDED_LOWER, TWO_SIDED)
log_p Boolean flag indicating if the p-value should be logged.
Returns:
The computed p-value.
Definition at line 1002 of file statfun.cpp.
Referenced by ranksumTest().
void affxstat::ranksumTest (double * x1, int n1, double * x2, int n2, int * nTied, double * pval, double * signal, int tail_type)
Performs a Wilcoxon rank sum test. This is the legacy interface.
Parameters:
x1 The array of values for the first sample.
n1 The number of points in the x1 array.
x2 The array of values for the second sample.
n2 The number of points in the x2 array.
nTied Value will be incremented by one if there were ties in the input data.
pval The computed p-value.
signal The median of all pairwise differences in x1 and x2 (Hodges-Lehmann estimator)
tail_type The tail type for the test (one of ONE_SIDED_UPPER, ONE_SIDED_LOWER, TWO_SIDED)
Definition at line 981 of file statfun.cpp.
References medianDifference(), and ranksumTest().
void affxstat::ranksumTest (double * x1, int n1, double * x2, int n2, bool * tied, double * pval, int tail_type, bool log_p)
Performs a Wilcoxon rank sum test. This is the full interface.
Parameters:
x1 The array of values for the first sample.
n1 The number of points in the x1 array.
x2 The array of values for the second sample.
n2 The number of points in the x2 array.
tied Boolean flag, value will reflect whether or not there were ties in the input data.
pval The computed p-value.
tail_type The tail type for the test (one of ONE_SIDED_UPPER, ONE_SIDED_LOWER, TWO_SIDED)
log_p Boolean flag indicating if the p-value should be logged.
Definition at line 1015 of file statfun.cpp.
References APPROX_RANKSUM_CUTOFF, LOG_TWO, ONE_SIDED_LOWER, ONE_SIDED_UPPER, pwilcox(), and TWO_SIDED.
void affxstat::signedRankTest (double * x, int n, int * tied, int * nZero, int * tiedAndZero, double * pval, double * signal)
Performs a signed rank test, returns logged lower-tail p-value and computes pseudoMedian. This is the legacy interface.
Parameters:
x The array of values to analyze.
n The number of points in the x array.
tied The number of observations that were tied.
nZero The number of observations that were zero.
tiedAndZero The number of observations that were tied and zero.
pval The p-value.
signal The pseudo median.
Definition at line 698 of file statfun.cpp.
References ONE_SIDED_LOWER, pseudoMedian(), and signedRankTest().
double affxstat::signedRankTest (double * x, int n, int tail_type, bool log_p)
Performs a Wilcoxon signed rank test. This is the simplest interface.
Parameters:
x The array of values to analyze.
n The number of points in the x array.
tail_type The tail type for the test (one of ONE_SIDED_UPPER, ONE_SIDED_LOWER, TWO_SIDED)
log_p Flag indicating if the p-value should be logged.
Returns:
The computed p-value.
Definition at line 714 of file statfun.cpp.
Referenced by signedRankTest().
void affxstat::signedRankTest (double * x, int n, bool * tied, bool * nZero, bool * tiedAndZero, double * pval, int tail_type, bool log_p)
Performs a signed rank test. This is the full interface.
Parameters:
x The array of values to analyze.
n The number of points in the x array.
tied The number of observations that were tied.
nZero The number of observations that were zero.
tiedAndZero The number of observations that were tied and zero.
pval The p-value.
signal The pseudo median.
tail_type The tail type for the test (one of ONE_SIDED_UPPER, ONE_SIDED_LOWER, TWO_SIDED)
log_p Flag indicating if the p-value should be logged.
Definition at line 735 of file statfun.cpp.
References APPROX_SIGNRANK_CUTOFF, LOG_TWO, ONE_SIDED_LOWER, ONE_SIDED_UPPER, psignrank(), and TWO_SIDED.
template<typename T1 > T1 affxstat::uprob (T1 x)
upper probability of the u distribution (u=-0.85) ///
Parameters:
x ??? ///
Returns:
0.0-1.0
Definition at line 99 of file stats-distributions.h.
Referenced by chisqrprob().