Affymetrix Power Tools: affx Namespace Reference
affx Namespace Reference
This defines an object which has fields and some methods // to make working with PGF files a snap. Basicly we define /// user friendly method which map to TsvFile mothods.
Classes
class CELTransformerEngine
class TsvReport
Unifies the presentation of file/TsvFile and file ///.
class Dabg
class BgpFile
To be called a BGP file, the file requires.
class ClfFile
To be called a CLF file, the file requires.
class PgfFile
This defines an object which has fields and some methods // to make working with PGF files a snap. Basicly we define /// user friendly method which map to TsvFile mothods.
class SpfFile
class TsvFileBinding
TsvFileBinding records the binding of a Column to a field. When "tsv->bind()" is called, a TsvFileBinding is created to record /// The details of the binding. When a file is opened, the bindings are /// linked to the correct Columns.
class TsvFileField
TsvFileField holds the data read from a column. /// The data is read into a std::string buffer. /// Rather than resizing the buffer all the time, we try and /// fill it "in place". Most of the time the new value should be the same /// size as the old value. /// We store the clvl and cidx info in the Column as well. /// Saves having to search for it in the TsvFile object. /// / "cidx" is counted from *after* the leading tabs. ///.
class TsvFileIndex
TsvFileIndex maps values to line positions.
class TsvFileHeaderLine
This is a key-value pair with sort order.
class TsvFile
A class for reading and writing Tab Seperated Value (TSV) files. /// See the TsvFile format document /// and the example program tsv-example.cpp .
class TsvFileDiff
class File5_File
class File5_Group
class File5_Matrix
struct _ColumnNameType
struct _TableOfContentsEntry
class File5_MultiDataUtils
class File5_Object
class File5_TsvColumn
class File5_Tsv
union File5_type_pun
class File5_Vector
class md5sum
an object oriented interface to generating MD5s. /// provides methods to do strings and files with one call.
Typedefs
typedef unsigned char GType
typedef uint32_t linenum_t
line numbers cant be negative
typedef struct
affx::_ColumnNameType ColumnNameType
typedef struct
affx::_TableOfContentsEntry TableOfContentsEntry
typedef union affx::File5_type_pun File5_type_pun_t
Enumerations
enum GType_enum {
AA, AB, BB, NN,
INVALID
}
Types of Genotype calls made.
enum Gender { Female, Male, UnknownGender }
Those pesky XY people need a different prior for all the SNPs on X that aren't on the psuedoautosomal region.
enum bindto_t { TSV_BINDTO_NONE = 0, TSV_BINDTO_CIDX = 1, TSV_BINDTO_CNAME = 2 }
Selector for what is used to link the binding.
enum valstate_t { VALSTATE_NONE = 0, VALSTATE_INT = 1, VALSTATE_DOUBLE = 2, VALSTATE_STRING = 3 }
enum tsv_type_t {
TSV_TYPE_UNKNOWN = 0, TSV_TYPE_ERR = 1, TSV_TYPE_STRING = 2, TSV_TYPE_INT = 3,
TSV_TYPE_FLOAT = 4, TSV_TYPE_DOUBLE = 5
}
enum tsv_return_t {
TSV_OK = -1, TSV_LINE_BLANK = -2, TSV_LINE_COMMENT = -3, TSV_ERR_UNKNOWN = -11,
TSV_ERR_NOTFOUND = -12, TSV_ERR_NULL = -13, TSV_ERR_CONVERSION = -14, TSV_ERR_FILEIO = -15,
TSV_ERR_FORMAT = -16, TSV_ERR_EOF = -17, TSV_HEADER = -30, TSV_HEADER_LAST = -31,
TSV_LEVEL_LAST = -32, TSV_FIND_LAST = -33, TSV_ERR_BINARY = -40, TSV_ERR_CALVIN = -41,
TSV_ERR_HDF5 = -42, TSV_LASTVALUE = -99
}
Return values to signal Error codes.
enum tsv_op_t {
TSV_OP_LT = 0x01, TSV_OP_LTEQ = 0x03, TSV_OP_EQ = 0x02, TSV_OP_GTEQ = 0x06,
TSV_OP_GT = 0x04
}
Flags supplied to when finding matches.
enum tsv_indexkind_t {
TSV_INDEX_STRING = 0x1, TSV_INDEX_INT = 0x2, TSV_INDEX_DOUBLE = 0x3, TSV_INDEX_UINT = 0x4,
TSV_INDEX_ULONGLONG = 0x5
}
The datatype of a index.
enum tsv_orderby_t { TSV_ORDERBY_LINE = 0x01, TSV_ORDERBY_VAL = 0x02 }
Should the results be ordered by the line nubmer or value.
enum tsv_fileformat_t {
TSV_FORMAT_NONE = 0x00, TSV_FORMAT_V1 = 0x01, TSV_FORMAT_V2 = 0x02, TSV_FORMAT_TABLE = 0x03,
TSV_FORMAT_BAD = 0xff
}
The format of the file.
enum tsv_bindopt_t { TSV_BIND_OPTIONAL = 0x01, TSV_BIND_WARNING = 0x02, TSV_BIND_REQUIRED = 0x04, TSV_BIND_NOFLAG = 0x00 }
Requirements for binding.
enum tsv_addflag_t { TSV_ADD_NONE = 0x00, TSV_ADD_KEYS = 0x01, TSV_ADD_COMMENTS = 0x02, TSV_ADD_ALL = (TSV_ADD_KEYS|TSV_ADD_COMMENTS) }
Flags for querying headers.
enum tsv_optionflag_t { TSV_OPT_NONE = 0x00, TSV_OPT_CASESENSTIVE = 0x01, TSV_OPT_CASEINSENSTIVE = 0x02 }
misc optional flags
enum File5_dtype_t {
FILE5_DTYPE_UNKNOWN = 0, FILE5_DTYPE_ERR, FILE5_DTYPE_ANY, FILE5_DTYPE_STRING,
FILE5_DTYPE_CHAR, FILE5_DTYPE_SHORT, FILE5_DTYPE_INT, FILE5_DTYPE_FLOAT,
FILE5_DTYPE_DOUBLE
}
enum File5_flag_t {
FILE5_REPLACE = 0x01, FILE5_CREATE = 0x02, FILE5_OPEN = 0x04, FILE5_RO = 0x10,
FILE5_RW = 0x11, FILE5_NOERR = 0x80, FILE5_OPEN_RO = 0x14, FILE5_OPEN_CREATE = FILE5_OPEN | FILE5_CREATE
}
enum File5_kind_t {
FILE5_KIND_UNKNOWN = 0, FILE5_KIND_FILE, FILE5_KIND_GROUP, FILE5_KIND_MATRIX,
FILE5_KIND_OBJECT, FILE5_KIND_TSV, FILE5_KIND_TSV_COLUMN, FILE5_KIND_VECTOR
}
enum File5_state_t { FILE5_STATE_UNKNOWN = 0, FILE5_STATE_OPEN, FILE5_STATE_CLOSED }
enum File5_return_t {
FILE5_OK = 0, FILE5_EOF, FILE5_ERR, FILE5_ERR_BADID,
FILE5_ERR_NOTFOUND, FILE5_ERR_REFCNT
}
Functions
int GType_to_int (GType gtype)
Convert a GType enum to an external integer value ///.
GType GType_from_int (int gtype_int)
Convert an integer from a file to an internal GType ///.
int GType_valid (int gtype)
Check that the gtype is AA,AB,BB,NN ///.
int GType_called (int gtype)
Check that the gtype is AA,AB,BB (not NN) ///.
int GTypeCallToChpValue (GType call)
Convert the enumerant to a value used by the CHP files.
const char * getGenderString (affx::Gender gender)
convert the BioType Gender to a string ///
affx::Gender flipMaleFemaleGender (affx::Gender gender)
Change gender call Male <-> Female. Unknown stays the same. This /// is used for chrZW gender calling. ///.
void ltrim (std::string &str)
Trim whitespace from the left of a string ///.
void rtrim (std::string &str)
Trim whitespace from the right of a string ///.
void trim (std::string &str)
Trim whitespace from both sides of a string ///.
std::string tolower (const std::string &str)
void dequote (std::string &str)
Remove quotes from a string if they are matching ///.
int splitstr (const std::string &str, char c, std::vector< std::string > &vec)
Split a string into a vector ///.
int countchars (const std::string &str, char c)
int unescapeChar (int c)
Convert the escaped char to the char which it represents ///.
int escapeChar (int c)
std::string escapeString (const std::string &str, const char escapeChar)
bool header_ptr_less (const affx::TsvFileHeaderLine *a, const affx::TsvFileHeaderLine *b)
Function for comparing TsvFileHeaderLine pointers.
void File5_open ()
void File5_close ()
std::vector< int > file5_dims (int d0)
std::vector< int > file5_dims (int d0, int d1)
std::vector< int > file5_dims (int d0, int d1, int d2)
std::vector< int > file5_dims (int d0, int d1, int d2, int d3)
void file5_dims_hsize_copy (std::vector< hsize_t > &dst, const std::vector< int > &src)
affx::File5_dtype_t as_file5_dtype (affx::tsv_type_t tsv_dtype)
affx::File5_dtype_t as_file5_dtype (hid_t hdf5_dtype)
std::string file5_dtype_to_string (affx::File5_dtype_t dtype)
affx::File5_dtype_t file5_string_to_dtype (const std::string &str)
hid_t as_hdf5_dtype (affx::tsv_type_t tsv_dtype)
hid_t as_hdf5_dtype (affx::File5_dtype_t file5_dtype)
hid_t as_h5t_native_type (hid_t dtype)
void dump_h5_dset (hid_t dset_id, std::ostream &ostm=std::cout)
void dump_h5_dspace (hid_t dspace_id, std::ostream &ostm=std::cout)
void dump_h5_dtype (hid_t dtype_id, std::ostream &ostm=std::cout)
void touchEngines ()
Variables
const int TSV_INTERNSIZE_UNSET = -1
Detailed Description
This defines an object which has fields and some methods // to make working with PGF files a snap. Basicly we define /// user friendly method which map to TsvFile mothods.
Typedef Documentation
typedef struct affx::_ColumnNameType affx::ColumnNameType
The name and column type.
typedef struct affx::_TableOfContentsEntry affx::TableOfContentsEntry
Stores a display and associated group name.
Enumeration Type Documentation
enum affx::bindto_t
Selector for what is used to link the binding.
Enumerator:
TSV_BINDTO_NONE
The binding wont be bound.
TSV_BINDTO_CIDX
Bound to column indexed by number.
TSV_BINDTO_CNAME
Bound to a column index by name.
Definition at line 68 of file TsvFile.h.
enum affx::Gender
Those pesky XY people need a different prior for all the SNPs on X that aren't on the psuedoautosomal region.
Enumerator:
Female
Has XX chromosomes.
Male
Has XY chromosomes.
UnknownGender
Don't know genotype, use XX model.
Definition at line 71 of file BioTypes.h.
enum affx::GType_enum
Types of Genotype calls made.
Enumerator:
AA
Homozygous A version of allele. (0).
AB
Heterozygous, one copy of both A and B. (1).
BB
Homozygous B version of allele. (2).
NN
No call, unknown genotype. The internal is value is '3'; external is '-1',.
Definition at line 43 of file BioTypes.h.
enum affx::tsv_addflag_t
Flags for querying headers.
Enumerator:
TSV_ADD_KEYS
just for nothing...
TSV_ADD_COMMENTS
return keys
TSV_ADD_ALL
return comments
Definition at line 153 of file TsvFile.h.
enum affx::tsv_bindopt_t
Requirements for binding.
Enumerator:
TSV_BIND_WARNING
bind if present
TSV_BIND_REQUIRED
warn if not bound
TSV_BIND_NOFLAG
error if not bound
Definition at line 146 of file TsvFile.h.
enum affx::tsv_return_t
Return values to signal Error codes.
Enumerator:
TSV_OK
No Error.
TSV_LINE_BLANK
The line is blank (m_lineLvl).
TSV_LINE_COMMENT
The line is a comment line (m_lineLvl).
TSV_ERR_UNKNOWN
An otherwise unknown error.
TSV_ERR_NOTFOUND
The value was not found.
TSV_ERR_NULL
The value was null.
TSV_ERR_CONVERSION
The value could not be converted.
TSV_ERR_FILEIO
Some sort of file IO error.
TSV_ERR_FORMAT
The format of the file is bad.
TSV_ERR_EOF
Hit the end of the file.
TSV_HEADER
A header line was read.
TSV_HEADER_LAST
Did not read a header line.
TSV_LEVEL_LAST
Did not read a line of the correct level.
TSV_FIND_LAST
Found the last matching value.
TSV_ERR_BINARY
This is some sort of binary file.
TSV_ERR_CALVIN
This is a calvin file.
TSV_ERR_HDF5
This is a HDF5 file.
TSV_LASTVALUE
end of errors
Definition at line 91 of file TsvFile.h.
Function Documentation
void affx::dequote (std::string & str)
Remove quotes from a string if they are matching ///.
Parameters:
str String to remove them from
Definition at line 154 of file TsvFile.cpp.
Referenced by AnnotationTable::AnalyzeFiles(), affx::TsvFile::f_read_column(), and affx::TsvFile::f_read_header_v1().
affx::Gender affx::flipMaleFemaleGender (affx::Gender gender)
Change gender call Male <-> Female. Unknown stays the same. This /// is used for chrZW gender calling. ///.
Parameters:
gender an affx::Gender value ///
Returns:
gender an affx::Gender value
Definition at line 164 of file BioTypes.cpp.
References Female, and Male.
Referenced by CnProbeGenderCelListener::newChip().
const char * affx::getGenderString (affx::Gender gender)
convert the BioType Gender to a string ///
Parameters:
gender an affx::Gender value ///
Returns:
pointer to a const string
Definition at line 141 of file BioTypes.cpp.
References Err::errAbort(), Female, Male, and UnknownGender.
Referenced by QuantMethodGTypeChipSummary::finish(), EmGenderCelListener::newChip(), DmListener::newChip(), and CnProbeGenderCelListener::newChip().
int affx::GType_called (int gtype)
Check that the gtype is AA,AB,BB (not NN) ///.
Parameters:
gtype ///
Returns:
true if called
Definition at line 127 of file BioTypes.cpp.
References AA, AB, and BB.
GType affx::GType_from_int (int gtype_int)
Convert an integer from a file to an internal GType ///.
Parameters:
gtype_int int to convert ///
Returns:
GType enum
Definition at line 88 of file BioTypes.cpp.
References Err::errAbort().
Referenced by loadSNPHints(), DmListener::makeCall(), GenoSeedTxt::readInPrecompGenoTypes(), QuantMethodMultiDataCCCHPReport::report(), and QuantMethodGTypeCHPReport::report().
int affx::GType_to_int (GType gtype)
Convert a GType enum to an external integer value ///.
Parameters:
gtype The GType to convert ///
Returns:
the value to use for output
Definition at line 61 of file BioTypes.cpp.
References AA, AB, BB, Err::errAbort(), and NN.
Referenced by QuantLabelZ::computeEstimate(), QuantGTypeMethod::getCall(), QuantGTypeMethod::getForcedCall(), QuantLabelZ::SelectGoodProbes(), and QuantBRLMM::setUp().
int affx::GType_valid (int gtype)
Check that the gtype is AA,AB,BB,NN ///.
Parameters:
gtype ///
Returns:
true if valid
Definition at line 115 of file BioTypes.cpp.
References AA, AB, BB, and NN.
Referenced by DmListener::makeCall().
int affx::GTypeCallToChpValue (affx::GType call)
Convert the enumerant to a value used by the CHP files.
Parameters:
call The gtype call value.
Returns:
The CHP file call value.
Definition at line 42 of file BioTypes.cpp.
References AA, AB, BB, Err::errAbort(), NN, and ToStr().
Referenced by QuantMethodMultiDataCCCHPReport::report().
void affx::ltrim (std::string & str)
Trim whitespace from the left of a string ///.
Parameters:
str the string to trim
Definition at line 108 of file TsvFile.cpp.
Referenced by affx::TsvFile::f_read_header_v2(), and trim().
void affx::rtrim (std::string & str)
Trim whitespace from the right of a string ///.
Parameters:
str the string to trim
Definition at line 121 of file TsvFile.cpp.
Referenced by affx::TsvFile::f_read_header_v2(), and trim().
int affx::splitstr (const std::string & str, char c, std::vector< std::string > & vec)
Split a string into a vector ///.
Parameters:
str string to split ///
c character to split on ///
vec vector to fill with split strings
Returns:
number of resulting strings
Definition at line 189 of file TsvFile.cpp.
Referenced by affx::TsvFile::defineFileParse(), affx::TsvFile::f_read_header_v1(), and affx::TsvFile::headers_to_fields_v2().
void affx::trim (std::string & str)
Trim whitespace from both sides of a string ///.
Parameters:
str the string to trim
Definition at line 134 of file TsvFile.cpp.
References ltrim(), and rtrim().
Referenced by affx::TsvFile::f_read_column(), and affx::TsvFile::f_read_header_v2().
int affx::unescapeChar (int c)
Convert the escaped char to the char which it represents ///.
Parameters:
c the escaped char ///
Returns:
the converted char
Definition at line 217 of file TsvFile.cpp.
Referenced by affx::TsvFile::f_read_column().