Affymetrix Power Tools: algorithm/em/PrimeEM.cpp File Reference
PrimeEM.cpp File Reference
#include "algorithm/em/PrimeEM.h"
#include <iostream>
Defines
#define NA -1*numeric_limits<double>::max()
NA.
#define MAX_DOUBLE numeric_limits<double>::max()
maximum of doubles
#define INF numeric_limits<double>::infinity()
infinity of doubles
#define EPSILON numeric_limits<double>::epsilon()
very small positive double number
Functions
double calcGaussianWithExpTail (const double z, const double zCut, const double factor)
Utility function to calculate value from Gaussian function with an exponential tail.
double calcProbability (const double x, const double mu, const double sigma, const double weight, const double zCut, bool useWeight)
Utility function to calculate probability from Gaussian distibution with an exponential tail given the mean and standard deviation.
Detailed Description
Author:
Xiaojun Di
Date:
Tue Aug 14 11:56 2006
DRAFT: wraps the EM algorithmics for genotyping under SDK
Definition in file PrimeEM.cpp.
Function Documentation
double calcGaussianWithExpTail (const double z, const double zCut, const double factor)
Utility function to calculate value from Gaussian function with an exponential tail.
Utility function to calculate probability from Gaussian distibution with an exponential tail given the mean and standard deviation.
Parameters:
z - the z value
zCut - where the exponential part starts
factor - a scale factor
Returns:
the value of z
Definition at line 56 of file PrimeEM.cpp.
Referenced by CPrimeEM::assignClassAndConfidence(), and calcProbability().
double calcProbability (const double x, const double mu, const double sigma, const double weight, const double zCut, bool useWeight)
Utility function to calculate probability from Gaussian distibution with an exponential tail given the mean and standard deviation.
Utility function to calculate value from Gaussian function with an exponential tail.
Parameters:
x - the observation
mu - mean of the gaussian distribution
sigma - standard deviation of the gaussian distribution
weight - the weight
zCut - where the exponential part starts
useWeight - flag to indicate whether weight should be used or not
Returns:
the probability of x from the given Gaussian distribution
Definition at line 86 of file PrimeEM.cpp.
References calcGaussianWithExpTail().
Referenced by CPrimeEM::assignClassAndConfidence(), and CPrimeEM::doEstep().