Affymetrix Power Tools: algorithm/em/PrimeEM.h File Reference
PrimeEM.h File Reference
#include <algorithm>
#include <cmath>
#include <functional>
#include <limits>
#include <map>
#include <numeric>
#include <vector>
Classes
class CEMSeed
Object to hold all prior information to constitute an EM seed.
class CEMEst
Object to hold all EM posterior information including some classification quality stats.
struct PairLess
class CEMParam
Object to hold all EM parameters.
class CEMPrior
Object to hold all EM prior information.
class CPrimeEM
The primary class to hold all EM operations.
Enumerations
enum LOSSFUNC { ML = 1, AIC = 2, BIC = 4, BIC_SEP = 8 }
different loss function options
Functions
double calcProbability (const double x, const double mu, const double sigma, const double weight, const double zCut, bool useWeight=false)
Utility function to calculate value from Gaussian function with an exponential tail.
double calcGaussianWithExpTail (const double z, const double zCut, const double factor=1)
Utility function to calculate probability from Gaussian distibution with an exponential tail given the mean and standard deviation.
Detailed Description
Author:
Xiaojun Di
Date:
Tue Aug 14 2006
DRAFT: wraps the EM algorithmics for genotyping under SDK
Definition in file PrimeEM.h.
Function Documentation
double calcGaussianWithExpTail (const double z, const double zCut, const double factor)
Utility function to calculate probability from Gaussian distibution with an exponential tail given the mean and standard deviation.
Parameters:
x - the observation
mu - mean of the gaussian distribution
sigma - standard deviation of the gaussian distribution
weight - the weight
zCut - where the exponential part starts
useWeight - flag to indicate whether weight should be used or not
Returns:
the probability of x from the given Gaussian distribution
Utility function to calculate probability from Gaussian distibution with an exponential tail given the mean and standard deviation.
Parameters:
z - the z value
zCut - where the exponential part starts
factor - a scale factor
Returns:
the value of z
Definition at line 56 of file PrimeEM.cpp.
Referenced by CPrimeEM::assignClassAndConfidence(), and calcProbability().
double calcProbability (const double x, const double mu, const double sigma, const double weight, const double zCut, bool useWeight)
Utility function to calculate value from Gaussian function with an exponential tail.
Parameters:
z - the z value
zCut - where the exponential part starts
factor - a scale factor
Returns:
the value of z
Utility function to calculate value from Gaussian function with an exponential tail.
Parameters:
x - the observation
mu - mean of the gaussian distribution
sigma - standard deviation of the gaussian distribution
weight - the weight
zCut - where the exponential part starts
useWeight - flag to indicate whether weight should be used or not
Returns:
the probability of x from the given Gaussian distribution
Definition at line 86 of file PrimeEM.cpp.
References calcGaussianWithExpTail().
Referenced by CPrimeEM::assignClassAndConfidence(), and CPrimeEM::doEstep().