Affymetrix Power Tools: chipstream/QuantLabelZ.cpp File Reference
QuantLabelZ.cpp File Reference
#include "chipstream/ArtifactReduction.h"
#include "chipstream/QuantLabelZ.h"
#include "chipstream/BioTypes.h"
#include "chipstream/MatrixUtil.h"
#include "chipstream/QuantLabelZIO.h"
#include "chipstream/QuantMethodFactory.h"
#include "chipstream/GenotypeInfo.h"
#include "util/Fs.h"
Functions
template<typename T1 >
void t_place_subset (vector< T1 > &Target, vector< T1 > &src, vector< int > &subset)
Utility function for returning subset values to place in whole sample list.
template<typename T1 >
void t_extract_subset (std::vector< T1 > &target, std::vector< T1 > &source, std::vector< int > &subset)
Utility function to grab a set of samples (like male/female).
Gender t_CallEMGender (const std::vector< double > &contrast, double &em_thresh, double &em_cutoff, double &gender_cutoff)
Calls gender using EM.
Detailed Description
Author:
Earl Hubbell
Date:
Fri Feb 24 11:02:09 2006
Definition in file QuantLabelZ.cpp.
Function Documentation
Gender t_CallEMGender (const std::vector< double > & contrast, double & em_thresh, double & em_cutoff, double & gender_cutoff)
Calls gender using EM.
This should not be anywhere near LabelZ, but code structure & time make this easiest.
Parameters:
contrast - list of contrast values for chrX snps in one sample
em_thresh - when are we done?
em_cutoff - enough data to make decision?
gender_cutoff - make decision as to gender
Definition at line 899 of file QuantLabelZ.cpp.
References CPrimeEM::EMEstimate(), CPrimeEM::getEMEstimates(), CEMEst::m_class, CPrimeEM::setData(), CEMSeed::setMaxMu(), CEMSeed::setMaxSigma(), CEMSeed::setMinMu(), CEMSeed::setMinSigma(), CEMSeed::setMu(), CEMSeed::setSigma(), CPrimeEM::setThreshold(), and CEMSeed::setWeight().
Referenced by QuantLabelZ::FindGender().
template<typename T1 > void t_extract_subset (std::vector< T1 > & target, std::vector< T1 > & source, std::vector< int > & subset)
Utility function to grab a set of samples (like male/female).
Parameters:
target - destination for values
source - values defined for subset
subset - definition of subset of samples
Definition at line 70 of file QuantLabelZ.cpp.
Referenced by QuantLabelZ::computeEstimate().
template<typename T1 > void t_place_subset (vector< T1 > & Target, vector< T1 > & src, vector< int > & subset)
Utility function for returning subset values to place in whole sample list.
Parameters:
Target - destination for values
src - values defined for subset
subset - definition of subset of samples
Definition at line 51 of file QuantLabelZ.cpp.
Referenced by QuantLabelZ::computeEstimate().