Affymetrix Power Tools: chipstream/example/simpleRmaExample.cpp File Reference
simpleRmaExample.cpp File Reference
A simple example of RMA as implemented in the ChipStream framework to give a flavor of how things work. To keep example simple and readable very little error checking is done as we progress. Please do not use this example for real life data analysis.
#include "chipstream/AnalysisStreamFactory.h"
#include "chipstream/CelReader.h"
#include "chipstream/DiskIntensityMart.h"
#include <cstring>
#include <iostream>
#include <string>
#include <vector>
Functions
void doRma (const string cdfFile, const string outDir, vector< string > &celFiles)
Perform Robust Multichip Average (RMA) analysis on the cel files specified.
int main (int argc, const char *argv[])
Everybody's favorite function.
Detailed Description
A simple example of RMA as implemented in the ChipStream framework to give a flavor of how things work. To keep example simple and readable very little error checking is done as we progress. Please do not use this example for real life data analysis.
Author:
Chuck Sugnet
Date:
Thu Jan 12 11:06:30 2006
Definition in file simpleRmaExample.cpp.
Function Documentation
void doRma (const string cdfFile, const string outDir, vector< string > & celFiles)
Perform Robust Multichip Average (RMA) analysis on the cel files specified.
This simple example doesn't do very much in the way of error checking and shouldn't be included as error checking.
Parameters:
cdfFile - Layout of probesets on chip.
outDir - Directory to write results to.
numCelFiles - How many cel files are in the array.
celFiles - Array of cel file names to be used.
Definition at line 54 of file simpleRmaExample.cpp.
References AnalysisStream::addStdHeaders(), ProbeListFactory::asProbeSet(), AnalysisStreamFactory::constructAnalysisStream(), AnalysisStream::doAnalysis(), AnalysisStream::getChipStreamHead(), ChipLayout::getProbeListAtIndex(), ChipLayout::getProbeSetCount(), ChipLayout::openCdfAll(), Verbose::out(), CelReader::readFiles(), IntensityReader::registerIntensityMart(), IntensityReader::registerStream(), IntensityReader::setFiles(), and ToStr().
Referenced by main().
int main (int argc, const char * argv[])
Everybody's favorite function.
Definition at line 122 of file simpleRmaExample.cpp.
References doRma().