Affymetrix Power Tools: label/snp.label.h File Reference
snp.label.h File Reference
#include "chipstream/BioTypes.h"
#include "chipstream/SelfDoc.h"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <memory>
#include <new>
#include <string>
#include <utility>
#include <vector>
Classes
class cluster_data
this class summarizes a single genotype
class binned_data
this class summarizes binned data
class snp_distribution
this class holds all three genotype clusters
class snp_param
this holds all the parameters for a snp, including alg choices
Functions
void bayes_label (std::vector< affx::GType > &call, std::vector< double > &conf, std::vector< double > &x, std::vector< double > &y, std::vector< int > &genohints, std::vector< double > &SubsetInbred, snp_param &sp)
This is the magic function that does the clustering for the outside world.
void bayes_label (std::vector< affx::GType > &call, std::vector< double > &conf, std::vector< double > &x, std::vector< double > &y, std::vector< int > &genohints, std::vector< double > &SubsetInbred, snp_param &sp, std::vector< double > &ted, std::vector< double > &teh, std::vector< double > &tec, bool store_probabilites)
Detailed Description
Author:
Earl Hubbell
Date:
Jan 22 2007
Definition in file snp.label.h.
Function Documentation
void bayes_label (vector< affx::GType > & call, vector< double > & conf, vector< double > & x, vector< double > & y, vector< int > & genohints, vector< double > & SubsetInbred, snp_param & sp)
This is the magic function that does the clustering for the outside world.
This is the magic function that does the clustering for the outside world.
Parameters:
call - output of genotypes per data point
conf - output of confidences (1-relative probability)
x - contrast values per data point
y - size values per data point - used as QC check for copy number
genohints - any reference genotypes you have lying around as hints
sp - snp parameters: prior information, algorithm parameters, etc.
Definition at line 2129 of file snp.label.cpp.
References bayes_label().
Referenced by bayes_label(), QuantLabelZMulti::computeEstimate(), and QuantLabelZ::computeEstimate().