Affymetrix Power Tools: label/snp.label.cpp File Reference
snp.label.cpp File Reference
#include "label/snp.label.h"
#include "chipstream/BioTypes.h"
#include "chipstream/MatrixUtil.h"
#include "newmat.h"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <functional>
#include <memory>
#include <new>
#include <utility>
#include <vector>
Classes
struct first_less
make utility for comparing pairs
struct second_less
utility for comparing pairs
Functions
int hax (int i, int j, int length)
hash indexer
void transfer (double *final, double *source, int length)
copies one float vector to another
void cumsum (double *final, double *source, int length)
cumulative sum of source vector
void vcumsum (vector< double > &final, const vector< double > &source, int length)
cumulative sum of source vector using STL
double delta (double *source, int length, int a, int b)
difference in cumulative sums: i.e.
void apply_sum (vector< double > &final, const vector< double > &source, int length, int flag)
sum up the source array along one axis
void reversecumsum (double *final, const double *source, int length)
takes a cumulative sum and makes it cumulate from the other end
void vreversecumsum (vector< double > &final, const vector< double > &source, int length)
takes a cumulative sum and makes it cumulate from the other end
void outer_minus (double *final, const double *a, const double *b, int length)
takes outer difference of two vectors
void mask (double *final, int length, double val)
mask out a portion of an array
void vmask (vector< double > &final, int length, double val)
mask out a portion of an array
void vsum (double *final, const double *a, const double *b, int length)
sum two vectors
void vplusscaldr (double *final, double *a, double k, int length)
add a constant to each element of a vector
void vmult (vector< double > &X, double factor)
multiply each element of a vector by a value
void inversethree (vector< double > &w, vector< double > &v)
inverts 3x3 matrix specialty code, avoid calling external routines
void sumthree (vector< double > &z, vector< double > &a, vector< double > &b)
sum two vectors
void timesthree (vector< double > &z, vector< double > &a, vector< double > &b)
multiply two 3x3 matrices
void timesone (vector< double > &z, vector< double > &a, vector< double > &b)
multiply a 1x3 vector by a 3x3 matrix
double b_mean (double k, double m, double mm, double n)
bayesian mean - prior + observed
double b_var (double v, double pv, double ddx, double cc, double nc, double k, double mcc, double pm)
bayesian variance - prior + observed + shift in means
double l_posterior (double xcx, double lc, double xc, double yc, double dvc)
gaussian likelihood, in convenient running sums form
double l_normal (double m, double x, double v)
gaussian likelihood, for just one piece of data
double l_two_normal (double x, double y, cluster_data &cl, double inflatePRA)
double l_inverse (double av, double dv, double v)
cheap inverse-gamma likelihood, for one piece of data
double fix_shell (double a, double b, double h, double shell)
check if centers too close, return bignum if true
double fix_hom_shell (double a, double b, double h, double shell)
prevents hom clusters from approaching midline not useful on B chip due to asymmetric probe choice
void make_a_call (affx::GType &call, double &conf, double txd, double txh, double txc)
Given 3 genotype probabilities, make a call/confidence output.
void make_calls (vector< affx::GType > &call, vector< double > &conf, vector< double > &x, int length, cluster_data &pa, cluster_data &ph, cluster_data &pb, int cn, int freqflag, vector< double > &vTxa, vector< double > &vTxh, vector< double > &vTxb, bool store_probabilities)
Given cluster parameters for each genotype, call data as genotypes.
void make_two_calls (vector< affx::GType > &call, vector< double > &conf, vector< double > &x, vector< double > &y, int length, snp_distribution &p, int cn, int freqflag, double ocean, double inflatePRA, vector< double > &vTxa, vector< double > &vTxh, vector< double > &vTxb, bool store_probabilities)
Given cluster parameters for each genotype, call data as genotypes.
void make_label_calls (vector< affx::GType > &call, vector< double > &conf, vector< double > &x, int length, vector< double > &ed, vector< double > &ec, vector< double > &eh, int cn)
make calls using the final labelings - primarily a matter of unsorting the contrast values
int setup_bins (binned_data &zall, vector< double > &z, vector< double > &w, vector< int > &zerohints, vector< double > &zeroInbred, int zlength, int bins, int hok, double Cpenalty)
assigns the sorted constrast data into "bins" for fast processing
void compute_binned_cluster (double &n, double &m, double &s, binned_data &zall, vector< double > &wi, int ZS)
generate sums of data based on weighted cluster membership
void compute_two_binned_cluster (vector< double > &six, binned_data &zall, vector< double > &wi, int ZS)
generate sums of data based on weighted cluster membership
void expand_data (vector< double > &tex, int length, vector< double > &ex, vector< double > &nz, int ZS)
take probabilities of bins and turn them into probabilities of individual points
void qtoeq (vector< double > &q, int ZS)
convert log-likelihood of all labelings into relative probability
void eqtoproblabel (vector< double > &ec, vector< double > &eh, vector< double > &ed, int ZS, vector< double > q)
turn the overall relative probability of labelings into relative probability of individual genotypes
void setupBRLMM (vector< double > &m, vector< double > &Minv, vector< double > &Sinv, snp_param &sp)
setup the matrixes for doing individual BRLMM steps
void force_isotonic (double &mb, double &mh, double &ma, double wb, double wh, double wa, double delta)
void force_IsoHetY (snp_distribution &post, double IsoHetWeight)
void bayes_two_variance (cluster_data &post, vector< double > &sixc, cluster_data &prior)
void shrink_cluster_variance (cluster_data &out, cluster_data &a, cluster_data &b, cluster_data &c, double lambda)
void bayes_two_shrink_variance (snp_param &sp)
void Dump_Matrix (Matrix &M)
void Dump_Column (ColumnVector &V)
void labels_two_posterior (vector< double > &ec, vector< double > &eh, vector< double > &ed, int ZS, binned_data &zall, snp_param &sp)
void labelstoposterior (vector< double > &ec, vector< double > &eh, vector< double > &ed, int ZS, binned_data &zall, snp_param &sp)
convert binned label relative probabilities into cluster parameters
double mixture_penalty (double a, double b, double c, double oa, double ob, double oc, double lambda)
This penalizes unusual frequency distributions.
double HW_penalty (double a, double b, double c, double lambda)
This penalizes unusual cluster distributions (violating HW extremely) Expected to be useful for screening/finding initial priors.
void integratebrlmmoverlabelings (vector< double > &ec, vector< double > &eh, vector< double > &ed, int ZS, binned_data &zall, snp_param &sp)
This is the "labeling" routine that tries out all plausible genotypes for best likelihood Basic goal: efficiently evaluate likelihood of three clusters based on seed Loops over BB,...BB (i times), AB,...AB (j-i), AA,...AA (n-j+1).
void apply_wobble (snp_param &sp)
tunes up the prior to allow for cluster shifts
void qc_modify_confidences (vector< affx::GType > &call, vector< double > &conf, vector< double > &y, double perr)
void qc_compute_copy_posterior (vector< affx::GType > call, vector< double > &y, snp_distribution &posterior)
void qc_posterior_modify_confidences (vector< affx::GType > &call, vector< double > &conf, vector< double > &y, double perr, snp_distribution dist)
void initialize_bins (binned_data &zall, vector< double > &x, vector< double > &y, vector< int > &genohints, vector< double > &SubsetInbred, int numbins, int hok, double CP)
Set up the binned data from the regular data compute running sums, allocate sorted bins.
void bayes_label (vector< affx::GType > &call, vector< double > &conf, vector< double > &x, vector< double > &y, vector< int > &genohints, vector< double > &SubsetInbred, snp_param &sp)
The master routine: takes data and turns it into genotypes with no seeds needed.
void bayes_label (vector< affx::GType > &call, vector< double > &conf, vector< double > &x, vector< double > &y, vector< int > &genohints, vector< double > &SubsetInbred, snp_param &sp, vector< double > &ted, vector< double > &teh, vector< double > &tec, bool store_probabilities)
Detailed Description
Author:
Earl Hubbell
Date:
Jan 22 2007
Does the labeling algorithmics.
Definition in file snp.label.cpp.
Function Documentation
void apply_sum (vector< double > & final, const vector< double > & source, int length, int flag)
sum up the source array along one axis
Parameters:
final - output, marginal sums of array
source - input, all the individual values
length - dimension of array
flag - which margin to sum to
Definition at line 135 of file snp.label.cpp.
References hax().
Referenced by eqtoproblabel().
void apply_wobble (snp_param & sp)
tunes up the prior to allow for cluster shifts
Definition at line 1836 of file snp.label.cpp.
References snp_distribution::aa, snp_distribution::ab, snp_distribution::bb, cluster_data::k, and snp_param::wobble.
double b_mean (double k, double m, double mm, double n)
bayesian mean - prior + observed
Parameters:
k - prior pseudo-observations
m - prior mean
mm - observed sum of data
n - number of observations
Definition at line 357 of file snp.label.cpp.
double b_var (double v, double pv, double ddx, double cc, double nc, double k, double mcc, double pm)
bayesian variance - prior + observed + shift in means
Parameters:
v - prior pseudo-observations
pv - prior variance
ddx - sum of squares of observations
cc - sum of observations
nc - number of observations
k - prior pseudo-observations for mean
mcc - observed mean
pm - prior location for mean
Definition at line 375 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings(), and labelstoposterior().
void bayes_label (vector< affx::GType > & call, vector< double > & conf, vector< double > & x, vector< double > & y, vector< int > & genohints, vector< double > & SubsetInbred, snp_param & sp)
The master routine: takes data and turns it into genotypes with no seeds needed.
This is the magic function that does the clustering for the outside world.
Parameters:
call - output of genotypes per data point
conf - output of confidences (1-relative probability)
x - contrast values per data point
y - size values per data point - used as QC check for copy number
genohints - any reference genotypes you have lying around as hints
sp - snp parameters: prior information, algorithm parameters, etc.
Definition at line 2129 of file snp.label.cpp.
References bayes_label().
Referenced by bayes_label(), QuantLabelZMulti::computeEstimate(), and QuantLabelZ::computeEstimate().
void compute_binned_cluster (double & n, double & m, double & s, binned_data & zall, vector< double > & wi, int ZS)
generate sums of data based on weighted cluster membership
Parameters:
n - effective number of data points
m - effective sum of data points
s - effective sum of squares of data points
zall - binned contrast data for points
wi - weight of bins
ZS - number of bins
Definition at line 871 of file snp.label.cpp.
References binned_data::nz, binned_data::zz, and binned_data::zzx.
Referenced by labelstoposterior().
void compute_two_binned_cluster (vector< double > & six, binned_data & zall, vector< double > & wi, int ZS)
generate sums of data based on weighted cluster membership
Parameters:
n - effective number of data points
m - effective sum of data points
s - effective sum of squares of data points
zall - binned contrast data for points
wi - weight of bins
ZS - number of bins
Definition at line 896 of file snp.label.cpp.
References binned_data::nz, binned_data::zxy, binned_data::zy, binned_data::zz, binned_data::zzx, and binned_data::zzy.
void cumsum (double * final, double * source, int length)
cumulative sum of source vector
Parameters:
final - destination for cumulative sum
source - source of individual values
length - length of data
Definition at line 87 of file snp.label.cpp.
double delta (double * source, int length, int a, int b)
difference in cumulative sums: i.e.
sum from b to a
Parameters:
source - vector of cumulative sums
length - length of data
a - larger cumulative point
b - smaller cumulative point
Definition at line 117 of file snp.label.cpp.
Referenced by SummaryStats::addData(), CumulativeStats< double >::addData(), CNAnalysisMethod::binEqualSpacing(), RMA::medianPolishPsetFromMatrix(), RMA::medianPolishWithPrecomputedEffectsOnePass(), RMA::medianPolishWithPrecomputedEffectsUsedAsSeedValues(), and CNAnalysisMethodCN::viterbi().
void eqtoproblabel (vector< double > & ec, vector< double > & eh, vector< double > & ed, int ZS, vector< double > q)
turn the overall relative probability of labelings into relative probability of individual genotypes
Parameters:
ec - relative probability of c = a allele dominant
eh - relative probability of h = ab allele about equal
ed - relative probability of d = b allele dominant
ZS - marginal size of matrix
q - matrix of relative probability of labelings
Definition at line 984 of file snp.label.cpp.
References apply_sum(), and vcumsum().
Referenced by integratebrlmmoverlabelings().
void expand_data (vector< double > & tex, int length, vector< double > & ex, vector< double > & nz, int ZS)
take probabilities of bins and turn them into probabilities of individual points
Parameters:
tex - output per point
length - number of real data points
ex - binned data
nz - number of points per bin
ZS - number of bins
Definition at line 927 of file snp.label.cpp.
double fix_hom_shell (double a, double b, double h, double shell)
prevents hom clusters from approaching midline not useful on B chip due to asymmetric probe choice
Parameters:
a - cluster aa mean
b - cluster bb mean
h - cluater ab mean
shell - homs can't be closer to center than this or penalty
Definition at line 481 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings().
double fix_shell (double a, double b, double h, double shell)
check if centers too close, return bignum if true
Parameters:
a - cluster aa
b - cluster bb
h - cluster ab
shell - minimum distance squared for penalty
Definition at line 460 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings().
int hax (int i, int j, int length) [inline]
hash indexer
Parameters:
i - first index
j - second index
length - size of side of array
Definition at line 62 of file snp.label.cpp.
Referenced by apply_sum(), integratebrlmmoverlabelings(), mask(), outer_minus(), qtoeq(), and vmask().
double HW_penalty (double a, double b, double c, double lambda)
This penalizes unusual cluster distributions (violating HW extremely) Expected to be useful for screening/finding initial priors.
Parameters:
a - hom cluster freq
b - hom cluster freq
c - het cluster freq
Definition at line 1493 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings().
void initialize_bins (binned_data & zall, vector< double > & x, vector< double > & y, vector< int > & genohints, vector< double > & SubsetInbred, int numbins, int hok, double CP)
Set up the binned data from the regular data compute running sums, allocate sorted bins.
Parameters:
zall - overall structure to keep track of data + soft genotype labels by bin
x - initial data points (unsorted)
genohints - hints associated with data points
numbins - how many bins to make, if bins>points, go with points
store sorted data
Definition at line 2038 of file snp.label.cpp.
References binned_data::noc, binned_data::nod, binned_data::noh, binned_data::nz, setup_bins(), binned_data::zxy, binned_data::zy, binned_data::zz, binned_data::zzx, and binned_data::zzy.
void integratebrlmmoverlabelings (vector< double > & ec, vector< double > & eh, vector< double > & ed, int ZS, binned_data & zall, snp_param & sp)
This is the "labeling" routine that tries out all plausible genotypes for best likelihood Basic goal: efficiently evaluate likelihood of three clusters based on seed Loops over BB,...BB (i times), AB,...AB (j-i), AA,...AA (n-j+1).
Parameters:
ec - relative probability of c = a allele dominates
eh - relative probability of h = ab allele similar
ec - relative probability of d = b allele dominates
ZS - number of bins + 1 = size of data
zall - data in bins, sum, sum of squares
sp - snp parameters
Definition at line 1519 of file snp.label.cpp.
References snp_distribution::aa, snp_distribution::ab, b_var(), snp_distribution::bb, snp_param::bic, snp_param::comvar, snp_param::copynumber, snp_param::CSepPen, snp_param::CSepThr, eqtoproblabel(), fix_hom_shell(), fix_shell(), snp_param::hardshell, hax(), snp_param::hints, HW_penalty(), inversethree(), cluster_data::k, l_inverse(), l_normal(), l_posterior(), snp_param::lambda, cluster_data::m, snp_param::mix, mixture_penalty(), binned_data::noc, binned_data::nod, binned_data::noh, binned_data::nz, qtoeq(), snp_param::SafetyFrequency, setupBRLMM(), snp_param::shellbarrier, cluster_data::ss, sumthree(), timesone(), timesthree(), cluster_data::v, vcumsum(), vreversecumsum(), binned_data::zz, and binned_data::zzx.
void inversethree (vector< double > & w, vector< double > & v)
inverts 3x3 matrix specialty code, avoid calling external routines
Parameters:
w - output inverse of matrix
v - input matrix
Definition at line 278 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings(), and labelstoposterior().
double l_inverse (double av, double dv, double v)
cheap inverse-gamma likelihood, for one piece of data
Parameters:
av - prior expected variance
dv - observed variance
v - pseudo-observations for prior
Definition at line 447 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings().
double l_normal (double m, double x, double v)
gaussian likelihood, for just one piece of data
Parameters:
m - mean
x - observed value
v - variance
Definition at line 412 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings(), and make_calls().
double l_posterior (double xcx, double lc, double xc, double yc, double dvc)
gaussian likelihood, in convenient running sums form
Parameters:
xcx - sum of squares of observations
lc - posterior mean
xc - sum of observations
yc - number of observations
dvc - posterior variance
Definition at line 398 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings().
void labelstoposterior (vector< double > & ec, vector< double > & eh, vector< double > & ed, int ZS, binned_data & zall, snp_param & sp)
convert binned label relative probabilities into cluster parameters
Parameters:
ec - relative probability of c = a allele dominates
eh - relative probability of h = ab about equal
ed - relative probability of d = b allele dominates
ZS - length of bins
zall - all binned data, sums, sums of squares
sp - snp parameters
Definition at line 1363 of file snp.label.cpp.
References snp_distribution::aa, snp_distribution::ab, b_var(), snp_distribution::bb, compute_binned_cluster(), snp_param::comvar, snp_param::hardshell, inversethree(), cluster_data::k, snp_param::lambda, cluster_data::m, cluster_data::Set(), setupBRLMM(), snp_param::shellbarrier, cluster_data::ss, sumthree(), timesone(), timesthree(), cluster_data::v, snp_distribution::xhb, cluster_data::xyss, cluster_data::ym, and cluster_data::yss.
void make_a_call (affx::GType & call, double & conf, double txd, double txh, double txc)
Given 3 genotype probabilities, make a call/confidence output.
- call of final genotype 2,1,0 - confidence of final genotypes 1-likelihood - relative probability of d = b allele dominant - relative probability of a+b allele - relative probability of c = a allele dominant
Definition at line 502 of file snp.label.cpp.
Referenced by make_calls(), make_label_calls(), and make_two_calls().
void make_calls (vector< affx::GType > & call, vector< double > & conf, vector< double > & x, int length, cluster_data & pa, cluster_data & ph, cluster_data & pb, int cn, int freqflag, vector< double > & vTxa, vector< double > & vTxh, vector< double > & vTxb, bool store_probabilities)
Given cluster parameters for each genotype, call data as genotypes.
Parameters:
call - output called genotypes
conf - output confidences for each call
x - input data in contrast space
length - number of data points
rbma - aa cluster mean
rbva - aa cluster variance
rbmb - bb cluster mean
rbvb - bb cluster variance
rbmh - ab cluster mean
rbvh - ab cluster variance
cn - copy number - are we 1 copy (all homs) or two allowing hets
Definition at line 534 of file snp.label.cpp.
References cluster_data::k, l_normal(), cluster_data::m, make_a_call(), and cluster_data::ss.
void make_label_calls (vector< affx::GType > & call, vector< double > & conf, vector< double > & x, int length, vector< double > & ed, vector< double > & ec, vector< double > & eh, int cn)
make calls using the final labelings - primarily a matter of unsorting the contrast values
Parameters:
call - output called genotypes
conf - confidence of call
x - raw contrast values (unsorted)
length - number of data points
ed - estimated relative probability for d = bb genotype (sorted)
ec - estimated relative probability for c = aa genotype (sorted)
eh - estimated relative probability for h = ab genotype (sorted)
cn - copynumber 1 = homs only, copynumber 2 = hets allowed
Definition at line 741 of file snp.label.cpp.
References make_a_call().
void make_two_calls (vector< affx::GType > & call, vector< double > & conf, vector< double > & x, vector< double > & y, int length, snp_distribution & p, int cn, int freqflag, double ocean, double inflatePRA, vector< double > & vTxa, vector< double > & vTxh, vector< double > & vTxb, bool store_probabilities)
Given cluster parameters for each genotype, call data as genotypes.
Parameters:
call - output called genotypes
conf - output confidences for each call
x - input data in contrast space
length - number of data points
rbma - aa cluster mean
rbva - aa cluster variance
rbmb - bb cluster mean
rbvb - bb cluster variance
rbmh - ab cluster mean
rbvh - ab cluster variance
cn - copy number - are we 1 copy (all homs) or two allowing hets
Definition at line 624 of file snp.label.cpp.
References snp_distribution::aa, snp_distribution::ab, snp_distribution::bb, cluster_data::k, and make_a_call().
void mask (double * final, int length, double val)
mask out a portion of an array
Parameters:
final - array to be masked
length - size of margin of array
val - value to be placed in masked area
Definition at line 207 of file snp.label.cpp.
References hax().
Referenced by GetPValue().
double mixture_penalty (double a, double b, double c, double oa, double ob, double oc, double lambda)
This penalizes unusual frequency distributions.
Parameters:
a - first cluster freq
b - second cluster freq
c - third cluster freq
oa - number of observations
ob - number of observations
oc - number of observations
lambda - parameterized safety value to avoid zero frequency
Definition at line 1471 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings().
void outer_minus (double * final, const double * a, const double * b, int length)
takes outer difference of two vectors
Parameters:
final - output matrix
a - input vector
b - input vector
length - length of data
Definition at line 191 of file snp.label.cpp.
References hax().
void qtoeq (vector< double > & q, int ZS)
convert log-likelihood of all labelings into relative probability
Parameters:
q - matrix to be converted
ZS - edge size of matrix
Definition at line 949 of file snp.label.cpp.
References hax(), and vmask().
Referenced by integratebrlmmoverlabelings().
void reversecumsum (double * final, const double * source, int length)
takes a cumulative sum and makes it cumulate from the other end
Parameters:
final - output, reverse cumulative sum
source - input, forward direction cumulative sum
length - length of data
Definition at line 161 of file snp.label.cpp.
int setup_bins (binned_data & zall, vector< double > & z, vector< double > & w, vector< int > & zerohints, vector< double > & zeroInbred, int zlength, int bins, int hok, double Cpenalty)
assigns the sorted constrast data into "bins" for fast processing
Parameters:
zall - the bins of the data, number per bin, sums, sum-squares, hints
z - the raw data, sorted by constrast
zerohints - what are the reference genotypes supplied
zlength - how many values in the data
bins - how many bins at most for the data
hok - can homs be flipped in hints?
Definition at line 785 of file snp.label.cpp.
References binned_data::noc, binned_data::nod, binned_data::noh, binned_data::nz, binned_data::zxy, binned_data::zy, binned_data::zz, binned_data::zzx, and binned_data::zzy.
Referenced by initialize_bins().
void setupBRLMM (vector< double > & m, vector< double > & Minv, vector< double > & Sinv, snp_param & sp)
setup the matrixes for doing individual BRLMM steps
Parameters:
m - prior mean vector
Minv - inverse matrix of covariances (pseudo-observations) for means
Sinv - inverse matrix of variances of observations within genotypes
snp_param - parameters of algorithm
Definition at line 1027 of file snp.label.cpp.
References snp_distribution::aa, snp_distribution::ab, snp_distribution::bb, cluster_data::k, cluster_data::m, cluster_data::ss, and snp_distribution::xhb.
Referenced by integratebrlmmoverlabelings(), and labelstoposterior().
void sumthree (vector< double > & z, vector< double > & a, vector< double > & b)
sum two vectors
Parameters:
z - output
a - input
b - input
Definition at line 305 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings(), and labelstoposterior().
void timesone (vector< double > & z, vector< double > & a, vector< double > & b)
multiply a 1x3 vector by a 3x3 matrix
Parameters:
z - output
a - 3x3 matrix (as 9 length vector)
b - 1x3 vector (as 3 length vector)
Definition at line 340 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings(), and labelstoposterior().
void timesthree (vector< double > & z, vector< double > & a, vector< double > & b)
multiply two 3x3 matrices
Parameters:
z - output
a - input 3x3 matrix (as 9 length vector)
b - input 3x3 matrix (as 9 length vector)
Definition at line 319 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings(), and labelstoposterior().
void transfer (double * final, double * source, int length)
copies one float vector to another
Parameters:
final - destination vector
source - source vector
length - length of data
Definition at line 74 of file snp.label.cpp.
void vcumsum (vector< double > & final, const vector< double > & source, int length)
cumulative sum of source vector using STL
Parameters:
final - destination for cumulative sum
source - source of individual values
length - length of data to sum over [carried over]
Definition at line 101 of file snp.label.cpp.
Referenced by eqtoproblabel(), and integratebrlmmoverlabelings().
void vmask (vector< double > & final, int length, double val)
mask out a portion of an array
Parameters:
final - array to be masked
length - size of margin of array
val - value to be placed in masked area
Definition at line 222 of file snp.label.cpp.
References hax().
Referenced by qtoeq().
void vmult (vector< double > & X, double factor)
multiply each element of a vector by a value
Parameters:
X - vector
factor - factor to multiply each element by
Definition at line 265 of file snp.label.cpp.
void vplusscaldr (double * final, double * a, double k, int length)
add a constant to each element of a vector
Parameters:
final - output vector
a - input vector
k - value to be added
length - length of data
Definition at line 253 of file snp.label.cpp.
void vreversecumsum (vector< double > & final, const vector< double > & source, int length)
takes a cumulative sum and makes it cumulate from the other end
Parameters:
final - output, reverse cumulative sum
source - input, forward direction cumulative sum
length - length of data (not needed for STL)
Definition at line 174 of file snp.label.cpp.
Referenced by integratebrlmmoverlabelings().
void vsum (double * final, const double * a, const double * b, int length)
sum two vectors
Parameters:
final - output
a - input vector
b - input vector
length - length of input vectors
Definition at line 239 of file snp.label.cpp.