Affymetrix Power Tools: chipstream/SpecialSnps.cpp File Reference
SpecialSnps.cpp File Reference
#include "chipstream/SpecialSnps.h"
#include "file/TsvFile/TsvFile.h"
#include "file5/File5.h"
#include "stats/stats.h"
#include "util/Fs.h"
#include "util/Util.h"
Functions
void readCopyNumberFile (CopyNumberMap &copyNumberMap, const std::string &copyNumberFilePath)
void readSpecialSnpsFile (SpecialSnpMap *specialSnps, std::string *chipType, std::string *specialSnpVersion, const std::string &specialSnpsPath)
void readSpecialSampleSnpsFile (SpecialSampleSnpMap *specialSampleSnps, SpecialSampleNameVector *specialSampleName, const std::string &specialSampleSnpsPath)
void makeSpecialSnpsFromChrXFile (SpecialSnpMap *specialSnps, const std::string &chrXPath)
void haploidFromSpecial (SpecialSnpMap &SpecialSnps, map< string, bool > &haploidSnps)
void specialFromHaploid (SpecialSnpMap &SpecialSnps, map< string, bool > &haploidSnps)
void fillInHaploidSnpsVersion1 (string file, map< string, bool > &haploidSnps, ChipLayout *layout, bool permissive)
Open a text file and read in snps that are possibly haploid.
void fillInHaploidSnpsVersion2 (string file, std::map< std::string, bool > &haploidSnps, ChipLayout *layout, bool permissive)
Open a text file and read in snps that are possibly haploid.
void fillInHaploidSnps (string file, std::map< std::string, bool > &haploidSnps, ChipLayout *layout, bool permissive)
Determine which version of a chrx snp have and open appropriately.
bool isChrX (const SpecialSnpMapIter &specialSnp)
Determines if special snp is from chrX based on male/female cn.
bool isChrY (const SpecialSnpMapIter &specialSnp)
Determines if special snp is from chrY based on male/female cn.
bool isHaploid (const SpecialSnpMapIter &specialSnp)
Determines if special snp is from chrX or chrY.
bool isHaploid (const SpecialSnpMap &snpMap, const std::string &probeset_name)
Detailed Description
Definition in file SpecialSnps.cpp.
Function Documentation
void fillInHaploidSnps (string file, std::map< std::string, bool > & haploidSnps, ChipLayout * layout, bool permissive)
Determine which version of a chrx snp have and open appropriately.
Parameters:
file - chrX file to read
haploidSnps - Map of probeset names that are marked as chrX
layout -
permissive -
Definition at line 312 of file SpecialSnps.cpp.
References affx::TsvFile::close(), Err::errAbort(), fillInHaploidSnpsVersion1(), fillInHaploidSnpsVersion2(), affx::TsvFile::getHeader(), and affx::TsvFile::open().
Referenced by callGenotypes().
void fillInHaploidSnpsVersion1 (string file, map< string, bool > & haploidSnps, ChipLayout * layout, bool permissive)
Open a text file and read in snps that are possibly haploid.
Currently only chrX snps are supported.
Parameters:
file - chrX file to read
haploidSnps - Map of probeset names that are marked as chrX
layout -
Definition at line 249 of file SpecialSnps.cpp.
References affx::TsvFile::close(), ChipLayout::containsProbeSet(), Err::errAbort(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), Verbose::out(), ToStr(), and affx::TSV_BIND_REQUIRED.
Referenced by fillInHaploidSnps().
void fillInHaploidSnpsVersion2 (string file, std::map< std::string, bool > & haploidSnps, ChipLayout * layout, bool permissive)
Open a text file and read in snps that are possibly haploid.
Currently only chrX snps are supported.
Parameters:
file - chrX file to read
haploidSnps - Map of probeset names that are marked as chrX
layout -
permissive -
Definition at line 277 of file SpecialSnps.cpp.
References affx::TsvFile::close(), ChipLayout::containsProbeSet(), Err::errAbort(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), Verbose::out(), ToStr(), and affx::TSV_BIND_REQUIRED.
Referenced by fillInHaploidSnps().
void readCopyNumberFile (CopyNumberMap & copyNumberMap, const std::string & copyNumberFilePath)
Todo:
cannot assume that the order is the same!
Definition at line 36 of file SpecialSnps.cpp.
References Fs::basename(), Util::changeEnd(), Err::errAbort(), and ToStr().