Affymetrix Power Tools: chipstream/SpecialSnps.h File Reference
SpecialSnps.h File Reference
#include "chipstream/ChipLayout.h"
#include <cstring>
#include <map>
#include <string>
Typedefs
typedef std::map< std::string,
std::vector< int > > CopyNumberMap
typedef std::map< std::string,
std::pair< int, int > > SpecialSnpMap
typedef std::map< std::string,
std::pair< int, int >
>::const_iterator SpecialSnpMapIter
typedef std::map< std::string,
std::vector< int > > SpecialSampleSnpMap
typedef std::vector< std::string > SpecialSampleNameVector
Functions
void readCopyNumberFile (CopyNumberMap &copyNumberMap, const std::string &copyNumberFilePath)
void readSpecialSnpsFile (SpecialSnpMap *specialSnps, std::string *chipType, std::string *specialSnpVersion, const std::string &specialSnpsPath)
void readSpecialSampleSnpsFile (SpecialSampleSnpMap *specialSampleSnps, SpecialSampleNameVector *specialSampleName, const std::string &specialSampleSnpsPath)
void makeSpecialSnpsFromChrXFile (SpecialSnpMap *specialSnps, const std::string &chrXPath)
void specialFromHaploid (SpecialSnpMap &SpecialSnps, std::map< std::string, bool > &haploidSnps)
void haploidFromSpecial (SpecialSnpMap &SpecialSnps, std::map< std::string, bool > &haploidSnps)
void fillInHaploidSnps (std::string file, std::map< std::string, bool > &haploidSnps, ChipLayout *layout, bool permissive)
Determine which version of a chrx snp have and open appropriately.
void fillInHaploidSnpsVersion2 (std::string file, std::map< std::string, bool > &haploidSnps, ChipLayout *layout, bool permissive)
Open a text file and read in snps that are possibly haploid.
void fillInHaploidSnpsVersion1 (std::string file, std::map< std::string, bool > &haploidSnps, ChipLayout *layout, bool permissive)
Open a text file and read in snps that are possibly haploid.
bool isChrX (const SpecialSnpMapIter &specialSnp)
Determines if special snp is from chrX based on male/female cn.
bool isChrY (const SpecialSnpMapIter &specialSnp)
Determines if special snp is from chrY based on male/female cn.
bool isHaploid (const SpecialSnpMapIter &specialSnp)
Determines if special snp is from chrX or chrY.
bool isHaploid (const SpecialSnpMap &snpMap, const std::string &probeset_name)
Determines if given probeset_name is a special snp and if it is from chrX or chrY.
Detailed Description
Definition in file SpecialSnps.h.
Function Documentation
void fillInHaploidSnps (string file, std::map< std::string, bool > & haploidSnps, ChipLayout * layout, bool permissive)
Determine which version of a chrx snp have and open appropriately.
Parameters:
file - chrX file to read
haploidSnps - Map of probeset names that are marked as chrX
layout -
permissive -
Definition at line 312 of file SpecialSnps.cpp.
References affx::TsvFile::close(), Err::errAbort(), fillInHaploidSnpsVersion1(), fillInHaploidSnpsVersion2(), affx::TsvFile::getHeader(), and affx::TsvFile::open().
Referenced by callGenotypes().
void fillInHaploidSnpsVersion1 (string file, map< string, bool > & haploidSnps, ChipLayout * layout, bool permissive)
Open a text file and read in snps that are possibly haploid.
Currently only chrX snps are supported.
Parameters:
file - chrX file to read
haploidSnps - Map of probeset names that are marked as chrX
layout -
Definition at line 249 of file SpecialSnps.cpp.
References affx::TsvFile::close(), ChipLayout::containsProbeSet(), Err::errAbort(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), Verbose::out(), ToStr(), and affx::TSV_BIND_REQUIRED.
Referenced by fillInHaploidSnps().
void fillInHaploidSnpsVersion2 (string file, std::map< std::string, bool > & haploidSnps, ChipLayout * layout, bool permissive)
Open a text file and read in snps that are possibly haploid.
Currently only chrX snps are supported.
Parameters:
file - chrX file to read
haploidSnps - Map of probeset names that are marked as chrX
layout -
permissive -
Definition at line 277 of file SpecialSnps.cpp.
References affx::TsvFile::close(), ChipLayout::containsProbeSet(), Err::errAbort(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), Verbose::out(), ToStr(), and affx::TSV_BIND_REQUIRED.
Referenced by fillInHaploidSnps().