Affymetrix Power Tools: stats/stats.h File Reference
stats.h File Reference
///
#include "stats/stats-util.h"
#include "portability/affy-base-types.h"
#include "util/Util.h"
#include <algorithm>
#include <cassert>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cstring>
#include <functional>
#include <iostream>
#include <map>
#include <string>
#include <vector>
#include <ext/algorithm>
Classes
class Median< RAIterator >
class Average< RAIterator, LargeNumber >
class Variance< RAIterator, LargeNumber >
class UnbiasedVariance< RAIterator, LargeNumber >
class Covariance< RAIterator, LargeNumber >
class UnbiasedCovariance< RAIterator, LargeNumber >
Functions
template<class RAIterator >
iterator_traits< RAIterator >
::value_type percentile (RAIterator start, RAIterator stop, double percentage, size_t sampleSize=ULONG_MAX)
Return the value at a given percentile ///.
template<class RAIterator >
iterator_traits< RAIterator >
::value_type percentile_in_place (RAIterator start, RAIterator stop, double percentage)
Find the value for a given precentile, modifying the data is ok. ///.
template<class RAIterator >
iterator_traits< RAIterator >
::value_type median (RAIterator start, RAIterator stop, size_t sampleSize=ULONG_MAX)
template<class RAIterator >
iterator_traits< RAIterator >
::value_type median_in_place (RAIterator start, RAIterator stop)
template<class RAIterator >
double average (RAIterator start, RAIterator stop)
template<class RAIterator >
double pseudo_median (RAIterator start, RAIterator stop)
template<class RAIterator >
double variance (RAIterator start, RAIterator stop)
template<class RAIterator >
double unbiased_variance (RAIterator start, RAIterator stop)
template<class RAIterator >
double varcoeff (RAIterator start, RAIterator stop)
template<class RAIterator >
double unbiased_stddev (RAIterator start, RAIterator stop)
template<class RAIterator >
double stddev (RAIterator start, RAIterator stop)
template<class RAIterator >
iterator_traits< RAIterator >
::value_type interquartile_range (RAIterator start, RAIterator stop, long sampleSize=LONG_MAX)
template<class RAIterator >
double unbiased_covariance (RAIterator start1, RAIterator stop1, RAIterator start2)
template<class RAIterator >
double covariance (RAIterator start1, RAIterator stop1, RAIterator start2)
template<class RAIterator >
double correlation_coeff (RAIterator start1, RAIterator stop1, RAIterator start2)
template<class RAIterator >
double variation_coeff (RAIterator start, RAIterator stop)
template<class RAIterator >
double robust_variation_coeff (RAIterator start, RAIterator stop)
template<class RAIterator >
RAIterator reproducible_random_sample (RAIterator start, RAIterator stop, RAIterator out, uint32_t size, int32_t seed=0)
Detailed Description
///
Stats functions written for the transcriptome project.
Definition in file stats.h.
Function Documentation
template<class RAIterator > iterator_traits<RAIterator>::value_type percentile (RAIterator start, RAIterator stop, double percentage, size_t sampleSize = ULONG_MAX)
Return the value at a given percentile ///.
Parameters:
start beginning iterator ///
stop end iterator ///
percentage which precentile to return (0-100) ///
sampleSize (optional) size of sample to take from the input data. ///
Remarks:
This does not modify the input data. If the /// sampleSize is larger than the inputsize, all the input /// is used.
Definition at line 71 of file stats.h.
References percentile_in_place().
Referenced by QuantDabg::getDefaultDocOptions(), and QuantDabg::newObject().
template<class RAIterator > iterator_traits<RAIterator>::value_type percentile_in_place (RAIterator start, RAIterator stop, double percentage)
Find the value for a given precentile, modifying the data is ok. ///.
Parameters:
start beginning iterator ///
stop end iterator ///
percentage the percentile to find (0-100) ///
Returns:
the value found ///
Remarks:
Work with the data "in_place" -- we may shuffle /// the values around as we work. No copy needed.
Definition at line 110 of file stats.h.
Referenced by percentile().