Affymetrix Power Tools: translation/TranslationCommonControl.cpp File Reference
TranslationCommonControl.cpp File Reference
Controller code common to both command line and console controllers.
#include "calvin_files/utils/src/FileUtils.h"
#include "file/TsvFile/TsvFile.h"
#include "translation/ADTOptions.h"
#include "translation/CopyNumberTableModel.h"
#include "translation/ExperimentFileTableModel.h"
#include "translation/GenotypeOverrideTableModel.h"
#include "translation/GenotypeTableModel.h"
#include "translation/MarkerListModel.h"
#include "translation/SampleInfoTableModel.h"
#include "translation/TranslationCommonControl.h"
#include "translation/TranslationEngine.h"
#include "translation/TranslationTableModel.h"
#include "util/Err.h"
#include "util/Fs.h"
#include "util/Verbose.h"
#include "pcrecpp.h"
#include <cstring>
#include <string>
Functions
bool _validateInputExperimentFilesFromFileDMET3 (RunTimeEnvironment &rte, TranslationEngine *engine)
_validateInputExperimentFilesFromFileDMET3: Synopsis:
bool _validateInputExperimentFilesFromVectorDMET3 (RunTimeEnvironment &rte, TranslationEngine *engine)
TranslationCommonControl::_validateInputExperimentFilesFromVectorDMET3: Synopsis:
Variables
const std::string TRANSLATION_OPT_GENO_DMET2_FILE = "(DMET2: 1 of 2 experiment files) => YYYYMMDD_*_DMET[23]_Genotypes*.txt"
const std::string EXCEPTION_MISSING_TRANSLATION_TABLE = "Invalid option: translation file is required (i.e. -t, --translate-file option)."
const std::string EXCEPTION_MISSING_EXPERIMENT_CHP_FILE = "Invalid option: experiment CHP files is required (i.e. -e, --experiment-list option)."
const std::string HAPLOTYPE_REPORT_OPTION_FIRST = "Reporting only first named haplotype among non-differentiable haplotype names in translation file."
const std::string HAPLOTYPE_REPORT_OPTION_DUPLICATE = "Reporting a combined haplotype name based on all non-differentiable haplotype names in translation file."
Detailed Description
Controller code common to both command line and console controllers.
Author:
Mybrid Spalding
Date:
Tue Jul 8 09:26:28 PDT 2008
Definition in file TranslationCommonControl.cpp.
Function Documentation
bool _validateInputExperimentFilesFromFileDMET3 (RunTimeEnvironment & rte, TranslationEngine * engine)
_validateInputExperimentFilesFromFileDMET3: Synopsis:
Helper function to _validateInputFilesDMET3, broken out for clarity.
This routine reads a listing of files from a file, i.e. -E chp_files.txt.
Parameters:
rte - the single instance run time environment that houses the ADTOptions object as m_adtOpts.
pgOopts - command line options object
Returns:
- true if all input files were valid.
Definition at line 487 of file TranslationCommonControl.cpp.
References ExperimentFileTableModel::validateFiles().
bool _validateInputExperimentFilesFromVectorDMET3 (RunTimeEnvironment & rte, TranslationEngine * engine)
TranslationCommonControl::_validateInputExperimentFilesFromVectorDMET3: Synopsis:
See validateInputFiles, broken out for clarity.
This routine reads a listing of files from a std::vector passed in by the console.
Parameters:
rte - the single instance run time environment that houses the ADTOptions object as m_adtOpts.
pgOopts - command line options object
Returns:
- true if all input std::vector data was valid.
Definition at line 527 of file TranslationCommonControl.cpp.
References Options::getOptVector(), and Verbose::out().