#
# cvs:affy/sdk/file/Makefile ---
#
# $Id: Makefile,v 1.3 2009-04-16 16:32:09 awilli Exp $
#

#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
include ../../Makefile.inc
#
sdk_cpp_ignore=\
	MMDataSetDataWriter.cpp \
	MMDATFileWriter.cpp
#
include ${sdk_makefile_post}
