#
# cvs:affy/sdk/chipstream/apt-snp-summary/Makefile ---
#
# $Id: Makefile,v 1.9 2009/09/25 17:48:57 mspald Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
#
$(call sdk_define_exe,apt-snp-summary,apt-snp-summary.cpp)
$(call sdk_define_install_exe,apt-snp-summary)
#
include ${sdk_makefile_post}

