#
# cvs:affy/sdk/mas5-stat/src/Makefile ---
#
# $Id: Makefile,v 1.8 2009-04-16 14:40:15 awilli Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
sdk_cpp_cflags+=-I${sdk_root}/rawq/src
#
include ${sdk_makefile_post}
