#
# cvs:affy/sdk/util/Makefile2 ---
#

#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
#
sdk_cpp_ignore=$(wildcard *.cpp)
#
$(call sdk_define_check_exe,test-probeset-summarize,$(wildcard *.cpp) ../SummaryVis.cpp)
#
include ${sdk_makefile_post}
