#
# cvs:affy/sdk/file/Makefile ---
#
# $Id: Makefile,v 1.1 2007-05-22 06:51:03 awilli Exp $
#

#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
include ../../Makefile.inc
#
sdk_cpp_ignore=$(wildcard *.cpp)
#
$(call sdk_define_check_exe,test-calvin-array,$(wildcard *.cpp))
#
include ${sdk_makefile_post}
