#
# cvs:affy/sdk/dm/Makefile ---
#
# $Id: Makefile,v 1.5 2009-09-25 17:49:06 mspald Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
#
include ${sdk_makefile_post}

# Local Variables:
# mode: makefile
# End:
