#
# cvs:affy/sdk/util/Makefile2 ---
#
# $Id: Makefile,v 1.5 2009-09-25 17:48:57 mspald Exp $
#

#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
#
#
sdk_cpp_ignore=$(wildcard *.cpp)
#
$(call sdk_define_check_exe,test-snp-summary,$(wildcard *.cpp))
#
include ${sdk_makefile_post}
#
