#
# cvs:affy/sdk/label/Makefile ---
#
# $Id: Makefile,v 1.1 2007-12-08 00:38:47 awilli Exp $
# Earl copied from rma

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#

$(call sdk_define_exe,apt-summary-genotype,apt-summary-genotype.cpp)
$(call sdk_define_install_exe,apt-summary-genotype)
#
include ${sdk_makefile_post}

# Local Variables:
# mode: makefile
# End:
