#
# cvs:affy/sdk/dabg/Makefile ---
#
# $Id: Makefile,v 1.1 2009-04-16 14:39:57 awilli Exp $
#

#
sdk_root:=..
include ${sdk_root}/Makefile.defs
# ignore the other directories
sdk_subdirs:=src workflow test
#
include ${sdk_makefile_post}
