#
# affy/sdk/calvin_files/exception/src/Makefile ---
#
# $Id: Makefile,v 1.2 2006-10-26 20:22:33 harley Exp $
#

#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
include ../../Makefile.inc
#
include ${sdk_makefile_post}
