#
# cvs:affy/sdk/rma/Makefile ---
#
# $Id: Makefile,v 1.3 2006-04-26 17:29:37 harley Exp $
#

#
sdk_root:=..
include ${sdk_root}/Makefile.defs
#
include ${sdk_makefile_post}

# Local Variables:
# mode: makefile
# End:
