#
# cvs:affy/sdk/file/Makefile ---
#
# $Id: Makefile,v 1.3 2007-08-11 00:06:47 awilli Exp $
#

#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
#
# Not all the files have
sdk_cpp_ignore=$(wildcard *.cpp)
#
$(call sdk_define_check_exe,test-calvin-portability,$(wildcard *.cpp))
#
include ${sdk_makefile_post}

