#
# cvs:affy/sdk/file/Makefile ---
#
# $Id: Makefile,v 1.2 2006-10-26 20:22:32 harley Exp $
#

#
sdk_root:=../../../..
include ${sdk_root}/Makefile.defs
include ../../../Makefile.inc
#
sdk_cpp_ignore:=\
	CmdLine.cpp
#
include ${sdk_makefile_post}
