#
# cvs:affy/sdk/chipstream/apt-convert-spf/Makefile ---
#
# $Id: Makefile,v 1.4 2009-06-10 07:14:23 harley Exp $
#

# before include
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
$(call sdk_define_exe,apt-convert-spf,apt-convert-spf.cpp)
#sdk_cpp_ignore+=simpleRmaExample.cpp
#
include ${sdk_makefile_post}
