#
# cvs:affy/sdk/dabg/Makefile ---
#
# $Id: Makefile,v 1.5 2009-04-16 14:40:08 awilli Exp $
#

#
sdk_root:=..
include ${sdk_root}/Makefile.defs
# ignore the other directories
sdk_subdirs:=src workflow test apt-mas5
#
include ${sdk_makefile_post}
