#
# cvs:affy/sdk/util/Makefile ---
#
# $Id: Makefile,v 1.14 2009-09-25 17:49:07 mspald Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
#
#
sdk_cpp_ignore=$(wildcard *.cpp)
#
$(call sdk_define_check_exe,test-stats,$(wildcard *.cpp))
#
include ${sdk_makefile_post}
