#
# sdk/copynumber/CPPTest/Makefile ---
#
# $Id: Makefile,v 1.2 2009-09-25 17:48:57 mspald Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
sdk_cpp_ignore=$(wildcard *.cpp)
#
$(call sdk_define_check_exe,test-cppunit-copynumber,$(wildcard *.cpp))
#
include ${sdk_makefile_post}

# Local Variables:
# mode: makefile
# End:
