#
# cvs:affy/sdk/file/Makefile ---
#
# $Id: Makefile,v 1.3 2006-10-26 20:22:33 harley Exp $
#

#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
include ../../Makefile.inc
#
sdk_subdirs:=CalvinAdapter/ GCOSAdapter/
#
include ${sdk_makefile_post}
