#
# cvs:affy/sdk/dm/Makefile ---
#
# $Id: Makefile,v 1.4 2007-05-21 18:04:14 awilli Exp $
#

#
sdk_root:=..
include ${sdk_root}/Makefile.defs
#

$(call sdk_define_exe,dm-platform-issue,DmPlatformIssue.cpp)
include ${sdk_makefile_post}
