#
# cvs:affy/sdk/file/util/chp_to_txt/Makefile ---
#
# $Id: Makefile,v 1.3 2009-09-25 17:48:52 mspald Exp $
#

ctt_files:=$(wildcard *.cpp)
#
sdk_root:=../../..
include ${sdk_root}/Makefile.defs
include ../../Makefile.inc
#
$(call sdk_define_exe,calvin-data-file-extractor,${ctt_files})
#
include ${sdk_makefile_post}
