#
# cvs:affy/sdk/rma/Makefile ---
#
# $Id: Makefile,v 1.4 2009-09-25 17:49:06 mspald Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
#
sdk_cpp_ingore=$(wildcard *.cpp)
#
$(call sdk_define_check_exe, test-rma, $(wildcard *.cpp) )
#
include ${sdk_makefile_post}

# Local Variables:
# mode: makefile
# End:
