#
# affy/sdk/chipstream/apt-probeset-genotype/Makefile ---
#
# $Id: Makefile,v 1.2 2009-09-25 17:49:04 mspald Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
# classic
$(call sdk_define_exe,apt-mas5,apt-mas5.cpp)
$(call sdk_define_install_exe,apt-mas5)

include ${sdk_makefile_post}
