#
# cvs:affy/sdk/file/util/chp_to_txt/Makefile ---
#
# $Id: Makefile,v 1.8 2009-09-25 17:48:53 mspald Exp $
#


#
sdk_root:=../../../..
include ${sdk_root}/Makefile.defs
include ../../../Makefile.inc
#
ctt_files:=$(wildcard *.cpp)
#
$(call sdk_define_exe,calvin-converter-chp,${ctt_files})
#
include ${sdk_makefile_post}
