#
# cvs:affy/sdk/util/apt-data-subset/Makefile ---
#
# $Id: Makefile,v 1.2 2009-09-25 17:48:56 mspald Exp $
#

sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
#
$(call sdk_set_lib_name,affyutil)
#$(call sdk_set_link_libs,affyutil m xerces)
#
$(call sdk_define_exe,apt-data-subset,apt-data-subset.cpp)
#$(call sdk_define_install_exe,apt-data-subset)

include ${sdk_makefile_post}
