#
# affy/sdk/chipstream/apt-probeset-genotype/Makefile ---
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
# classic
$(call sdk_define_exe,apt-probeset-genotype,apt-probeset-genotype.cpp)
$(call sdk_define_install_exe,apt-probeset-genotype)
# cel-gender
#$(call sdk_define_exe,cel-gender,cel-gender.cpp)
#$(call sdk_define_install_exe,cel-gender)
#$(call sdk_define_exe,cc-chp-check,cc-chp-check.cpp)

#
include ${sdk_makefile_post}
