#
# /nfs/ss11/harley/Apt/work/apt2-1/affy/sdk/bboard/extra/Makefile ---
#
# $Id: Makefile,v 1.1 2009-10-28 00:06:03 harley Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#

#
include ${sdk_makefile_post}
